### ISSUE TITLE
[TForm] 使用TInput 组件增加number 类型校验，输入数字无法校验通过

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#1013]
### tdesign-vue-next 版本

0.16.0

### 重现链接

[复现代码](https://stackblitz.com/edit/angular-m4xqfu?file=src/demo.vue)

### 重现步骤

使用TInput 组件增加number 类型校验，输入数字无法校验通过
```
<template>
  <t-form :data="formData" :rules="rules">
    <t-form-item label="用户名" help="这是用户名字段帮助说明" name="number">
      <t-input v-model="formData.number" type="number" />
    </t-form-item>
  </t-form>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue';

export default defineComponent({
  name: 'Result404',
  setup() {
    return {
      formData: reactive({ number: '' }),
      rules: {
        number: [{ required: true, message: '格式必须为邮箱', type: 'warning' }, { number: true }],
      },
    };
  },
});
</script>
```

**Comment by dennlian** [comment]
0.16.0
![image](https://user-images.githubusercontent.com/20961979/174427372-2129bfda-a543-4ae8-8890-a7c7d5292804.png)

**Comment by chaishi** [comment]
看不懂问题，请详细描述。（Input 组件的 type=number 是完全直接透传原生属性到 html 标签，组件没有做任何处理，请查看原生属性特性）

**Comment by dennlian** [comment]
传入的是number 类型

**Comment by chaishi** [comment]
关于数字，建议使用更规范的 `InputNumber`

**Comment by dennlian** [comment]
![image](https://user-images.githubusercontent.com/20961979/174427415-65d1c7ae-d88f-4925-b85e-0302cda4cfa3.png)

**Comment by dennlian** [comment]
之前0.15的版本是可以的

**Comment by chaishi** [comment]
我看不懂，到底是 Input 的问题，还是 Form 表单校验的问题。就没法帮你解决问题。

首先，你需要提供可以复现问题的 Demo

**Comment by dennlian** [comment]
TForm 表单验证使用TInput 增加number:true 的验证时候验证不通过

**Comment by chaishi** [comment]
【提供可以复现问题的 Demo】 的意思是需要提供【代码】，我们属于不同的大脑，你单独一句话的描述，我真的没办法帮你排查问题。

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/11605702/174427756-396a9473-debb-4b96-bac3-095445e4453a.png">

**Comment by dennlian** [comment]
在写，一会提交给你

**Comment by dennlian** [comment]
<template>
  <t-form :data="formData" :rules="rules">
    <t-form-item label="用户名" help="这是用户名字段帮助说明" name="number">
      <t-input v-model="formData.number" />
    </t-form-item>
  </t-form>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue';

export default defineComponent({
  name: 'Result404',
  setup() {
    return {
      formData: reactive({ number: '' }),
      rules: {
        number: [{ required: true, message: '格式必须为邮箱', type: 'warning' }, { number: true }],
      },
    };
  },
});
</script>

**Comment by dennlian** [comment]
<template>
  <t-form :data="formData" :rules="rules">
    <t-form-item label="用户名" help="这是用户名字段帮助说明" name="number">
      <t-input v-model="formData.number" />
    </t-form-item>
  </t-form>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue';

export default defineComponent({
  name: 'Result404',
  setup() {
    return {
      formData: reactive({ number: '' }),
      rules: {
        number: [{ required: true, message: '格式必须为邮箱', type: 'warning' }, { number: true }],
      },
    };
  },
});
</script>

**Comment by dennlian** [comment]
复现的源码跟链接都提交了

**Comment by pengYYYYY** [comment]
```html
<template>
  <t-form :data="formData" :rules="rules">
    <t-form-item label="用户名" help="这是用户名字段帮助说明" name="number">
      <t-input v-model.number="formData.number" type="number" />
    </t-form-item>
  </t-form>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue';

export default defineComponent({
  name: 'Result404',
  setup() {
    return {
      formData: reactive({ number: '' }),
      rules: {
        number: [{ required: true, message: '格式必须为邮箱', type: 'warning' }, { number: true }],
      },
    };
  },
});
</script>
用 `number` 修饰符吧
```

**Comment by dennlian** [comment]
0.16.0版本用numbnumber一样验证失败
