### ISSUE TITLE
[Dialog] 函数式调用时，无法识别tdesign组件

### ISSUE THREAD

**Issue by zuobuer** [Tencent/tdesign-vue-next#1031]
### tdesign-vue-next 版本

0.15.3

### 重现步骤

`DialogPlugin({
    header: '修改',
    body: () => <t-tag>hello world</t-tag>,
    footer: false
  })`

### 期望结果

能正确的显示t-tag组件

### 实际结果

[Vue warn]: Failed to resolve component: t-tag
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

**Comment by pengYYYYY** [comment]
这种jsx写法需要用从组件库的包导入tag组件，然后用<TTag>

**Comment by pengYYYYY** [comment]
```js
import { DialogPlugin, Tag } from 'tdesign-vue-next';

const confirmDia = DialogPlugin({
        header: 'Dialog-Plugin',
        body: () => <Tag>123123</Tag>,
        className: 't-dialog-new-class1 t-dialog-new-class2',
        style: 'color: rgba(0, 0, 0, 0.6)',
        onConfirm: ({ e }) => {
          console.log('confirm clicked', e);
          confirmDia.hide();
        },
      });
```
