### ISSUE TITLE
[Dropdown] 下拉菜单多点几次后就不出现下拉菜单了

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#1040]
### tdesign-vue-next 版本

0.16.1

### 重现链接

https://stackblitz.com/edit/angular-wae3pj

### 重现步骤

挨个点击“选项一”，“选项二”，“选项三",多重复几次即可

**Comment by timi137137** [comment]
此问题并未发现，如果你指的是动画还未跑完导致的不出现，则无法解决，请尝试复现该问题（期间等菜单完全消失或未消失时点击）

**Comment by arieslee** [comment]
> 此问题并未发现，如果你指的是动画还未跑完导致的不出现，则无法解决，请尝试复现该问题（期间等菜单完全消失或未消失时点击）

我不知道我这么操作，是不是您 所指的动画未跑完的状态
[这里看复现](https://github.com/arieslee/cloud-snapshot/blob/main/2022-06-02%2009:44/iShot_2022-06-23_08.17.33.mp4)

**Comment by timi137137** [comment]
> > 此问题并未发现，如果你指的是动画还未跑完导致的不出现，则无法解决，请尝试复现该问题（期间等菜单完全消失或未消失时点击）
> 
> 我不知道我这么操作，是不是您 所指的动画未跑完的状态 [这里看复现](https://github.com/arieslee/cloud-snapshot/blob/main/2022-06-02%2009:44/iShot_2022-06-23_08.17.33.mp4?raw=true) https://user-images.githubusercontent.com/2550216/175182771-76849877-afe3-4049-b482-c1dc6eb2605a.MOV

这里未发现这种情况，有待核实

**Comment by pengYYYYY** [comment]
无法复现这个问题，找到必现方法的话可以reopen
