### ISSUE TITLE
[Checkbox] 二次封装Checkbox（change事件会触发两次）

### ISSUE THREAD

**Issue by uncledrewzhaopeng** [Tencent/tdesign-vue-next#1044]
### tdesign-vue-next 版本

0.16.1

### 封装 `Checkbox` 组件
```HTML
<template>
  <div class="hl-checkbox">
    <t-checkbox v-bind="$attrs">
      <template v-for="(index, name) in $slots" v-slot:[name]>
        <slot :name="name" />
      </template>
    </t-checkbox>
  </div>
</template>
```
```JS
<script setup name="HlCheckbox">
</script>
```

### 页面中使用
```HTML
<template>
  <div class="hl-pagination-examples">
    <div class="examples-item">
      <div class="main-title">基础多选框</div>
      <div class="description">最简单的多选框形式，常用于表单中数据多选的场景。</div>
      <div>
        <hl-checkbox @change="handleSelected">未选中项</hl-checkbox>
      </div>
    </div>
<template>
```

```JS
<script setup lang="jsx">
const handleSelected = (check) => {
  console.log('check', check);
}
</script>
```

### 结果
![image](https://user-images.githubusercontent.com/48023419/174970575-824f83a8-22e0-4b1e-98f7-678a0f4f9204.png)

### 框架版本

Vue(3.2.37)

### 浏览器版本

Chrome(101.0.4951.54)

### 系统版本

Windows

### Node版本

16.14.2

**Comment by timi137137** [comment]
经过测试，组件没有问题，问题出现在你的封装上
请详细阅读相关文档
[Vue3](https://staging-cn.vuejs.org/guide/typescript/composition-api.html#typing-component-emits)
[关于emit的用法](https://blog.csdn.net/sllailcp/article/details/78595077)
[子组件属性传递](https://staging-cn.vuejs.org/guide/components/attrs.html)
