### ISSUE TITLE
[Notification] 关于Notification中文档的错误

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next#1045]
### tdesign-vue-next 版本

0.16.0

### 重现链接

https://tdesign.tencent.com/vue-next/components/notification#%E6%8F%92%E4%BB%B6%E8%B0%83%E7%94%A8%E4%B8%8E%E5%87%BD%E6%95%B0%E5%BC%8F%E8%B0%83%E7%94%A8

### 重现步骤

文档中
```
示例：NotifyPlugin.warning('请输入信息') 或 this.$notify.warning('请输入信息')
```

其中的`NotifyPlugin.warning('请输入信息')`无效，因为类型约束，应该传入`options: NotificationInfoOptions`，而不是字符串。

**Comment by pengYYYYY** [comment]
这一块需要在common里面秀

**Comment by timi137137** [comment]
我现在就提(

**Comment by timi137137** [comment]
> 这一块需要在common里面修

@pengYYYYY 看了一下，style/web/components/notification/index.html 没有关于本ISSUE的问题，应该要追溯到docs

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/blob/develop/examples/notification/notification.md 在这边

**Comment by timi137137** [comment]
> https://github.com/Tencent/tdesign-vue-next/blob/develop/examples/notification/notification.md 在这边

(x 我已经找到并且开了pr并关联了此issue
