### ISSUE TITLE
table 组件，表尾能否做合并行需求功能？

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next#1047]
### 这个功能解决了什么问题

table 组件，表尾能否做合并行需求功能？

可以解决，表尾固定到表格底部，展示动态列内容。

![image](https://user-images.githubusercontent.com/78259973/174991323-a8e00bea-0b79-42a5-b3ae-c50fae8867fe.png)

示例数据：
`
  {
          "Code": 0,
          "Msg": "success",
          "Data": {
              "MaterialDetails": [{
                  "No": "MA00003",
                  "MaterialNo": "MA00003",
                  "TargetPrice": 0.00000,
                  "TargetPriceCurrency": 1,
              }, {

                  "No": "MA00002",
                  "MaterialNo": "MA00002",
                  "TargetPrice": 0.00000,
                  "TargetPriceCurrency": 1
              }],
              "SuppliersQuotedprices": [{
                  "SuppliersNo": "GYS001",
                  "SuppliersName": "供应商A",
                  "MinNumber": 0,
                  "SuppliersInMaterialPrices": [{
                      "MaterialNo": "MA00002",
                      "F_CreatorTime": "2022-06-21 10:45:37",
                      "PriceCurrency": 0,
                      "Price":7
                  }, {
                      "MaterialNo": "MA00003",
                      "F_CreatorTime": "2022-06-21 10:45:37",
                      "PriceCurrency": 0,
                      "Price": 6
                  }]
              },
              {
                  "SuppliersNo": "GYS002",
                  "SuppliersName": "供应商B",
                  "MinNumber": 3,
                  "SuppliersInMaterialPrices": [{
                      "MaterialNo": "MA00002",
                      "F_CreatorTime": "2022-06-21 10:45:37",
                      "PriceCurrency": 0,
                      "Price": 5
                  }]
              },
              {
                  "SuppliersNo": "GYS003",
                  "SuppliersName": "供应商C",
                  "MinNumber": 5,
                  "SuppliersInMaterialPrices": []
              }]
          }
      }`

SuppliersQuotedprices 是动态加成列。
我用element-ui2.0 也没找到合并表尾，期望tdesign 能实现。

![image](https://user-images.githubusercontent.com/78259973/174991967-ab87f808-a657-4410-978a-5ad333386dad.png)

![image](https://user-images.githubusercontent.com/78259973/174992489-36b6098e-e92e-4dcd-b816-cd73c15fb9ba.png)
![image](https://user-images.githubusercontent.com/78259973/174992585-2e07dc0c-f60c-43e0-93e6-aa603f0aff13.png)

### 你建议的方案是什么

支持表尾做合并行功能

**Comment by chaishi** [comment]
已在群里为用户提供解决方案：因 table 组件支持冻结固定任意一行在底部，用户可以设置普通的最后一行为总结行，然后固定即可。

<img width="849" alt="image" src="https://user-images.githubusercontent.com/11605702/176989384-0a440a0f-de36-49d3-9730-0d363ce44a07.png">

**Comment by chaishi** [comment]
后续会考虑支持 表尾合并行，因有备选方案，不紧急

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/1217
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/1357

**Comment by pengYYYYY** [comment]
0.19.1 已修复
