### ISSUE TITLE
[Select] 分组选择在列表尾部会产生多余渲染，每个group中第一个选项会生成一个t-option

### ISSUE THREAD

**Issue by latte-z** [Tencent/tdesign-vue-next#1048]
### tdesign-vue-next 版本

0.16.1

### 重现链接

https://tdesign.woa.com/vue-next/components/select?tab=demo#%E5%88%86%E7%BB%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

![image](https://user-images.githubusercontent.com/7680235/175006691-959c5946-5b47-445e-8a49-134571190287.png)

除了渲染bug外，似乎例子点击显示的label也有问题

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/1026 这个issue已处理

**Comment by pengYYYYY** [comment]
0.17.0已修复
