### ISSUE TITLE
[Nuxt]增加 nuxt-starter 的组件示例

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-vue-next#1054]
## 原因
当前 `nuxt-starter` 示例过少，在做发布前集成测试的时候无法测到一些问题，导致发布后的版本会有不可用的情况。希望能增加更多组件示例

## TODO
在 [tdesign-vue-next-nuxt-starter](https://github.com/yixiaco/tdesign-vue-next-nuxt-starter) 项目中增加组件示例

**Comment by sufuwang** [comment]
没有明白是什么意思？指的是起一个 `nuxt` 项目，测试一下 `tdesign-vue-next` 的组件在 `nuxt` 项目中是否可用 ？

**Comment by pengYYYYY** [comment]
[tdesign-vue-next-nuxt-starter](https://github.com/yixiaco/tdesign-vue-next-nuxt-starter)  在这个项目中增加示例就好，主要是看哪些组件在nuxt下有问题

**Comment by sufuwang** [comment]
> [tdesign-vue-next-nuxt-starter](https://github.com/yixiaco/tdesign-vue-next-nuxt-starter) 在这个项目中增加示例就好，主要是看哪些组件在 `nuxt` 下有问题

认领一个，我把 tree 组件的 demo 写进去

**Comment by pengYYYYY** [comment]
> > [tdesign-vue-next-nuxt-starter](https://github.com/yixiaco/tdesign-vue-next-nuxt-starter) 在这个项目中增加示例就好，主要是看哪些组件在 `nuxt` 下有问题
> 
> 认领一个，我把 tree 组件的 demo 写进去

按组件列表往里面多补一些吧
