### ISSUE TITLE
[t-upload] 上传进度一直停在0%，如果用onProgress获取百分比，则会先快速到100%，然后再重新开始递进。

### ISSUE THREAD

**Issue by jasonxxp** [Tencent/tdesign-vue-next#1062]
### tdesign-vue-next 版本

0.16.1

### 重现步骤

<t-upload v-model="files" action="/" accept=".csv,.txt" tips="仅支持csv、txt格式上传"
              :percent="percent" :format-response="formatResponse" @progress="onProgress" @fail="handleFail" />

methods: {
    onProgress(obj) {
      this.percent = obj.percent;
      console.log(`上传中：${obj.percent}%`);
    },
}

**Comment by pengYYYYY** [comment]
0.17.0已修复

**Comment by jasonxxp** [comment]
现在不加:percent="percent"  progress="onProgress" 是能显示进度了，但以上传三百多M的文件为例，进度一开始还是在乱跳，过了一会儿到了60%多才开始慢慢正常上升到100%。
