### ISSUE TITLE
[TreeSelect] 建议增加显示上级节点功能

### ISSUE THREAD

**Issue by pony5551** [Tencent/tdesign-vue-next#1069]
### 这个功能解决了什么问题

TreeSelect 树选择 多选时 不能显示上及节点

### 你建议的方案是什么

建议 TreeSelect 树选择 多选时，可选择上级节点并显示， 
比如
江苏省/南京市
江苏省/苏州市

现在选中江苏省时，只会显示 南京市，苏州市
建议加个控制，可显示  江苏省，南京市，苏州市

**Comment by pony5551** [comment]
这个功能暂时不会实现吗？

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
