### ISSUE TITLE
[Improve][Message] 优化显示动画

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#107]
![image](https://user-images.githubusercontent.com/11605702/147798850-ae0dd5eb-8eb7-45a6-8d12-ed98c2eee9af.png)

![image](https://user-images.githubusercontent.com/11605702/147798858-638561d6-5663-41e3-bb71-8798418a5ed4.png)

**Comment by gaopeak** [comment]
嗯

**Comment by pattybaby110** [comment]
@Wen1kang

**Comment by Wen1kang** [comment]
已经在统一优化了，感谢反馈哦～
