### ISSUE TITLE
[Table] 动态合并单元格，如果数据发生动态变化，合并有问题

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#1070]
### tdesign-vue-next 版本

0.16.1

### 重现步骤

修改源码 useRowspanAndColspan方法即可修复

![image](https://user-images.githubusercontent.com/20961979/175564965-3171d951-4da5-4ed8-9905-3cfa461d2fb3.png)

### 期望结果

![image](https://user-images.githubusercontent.com/20961979/175565053-7723a0bc-7b82-4078-b4ec-23d7259af43f.png)

### 实际结果

![image](https://user-images.githubusercontent.com/20961979/175565474-36c27f3c-1bea-40bf-8389-6b7556ed4579.png)

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/1135

**Comment by chaishi** [comment]
see here: https://github.com/Tencent/tdesign-vue/issues/1045

Vue2 已修复，同步至 Vue3

**Comment by pengYYYYY** [comment]
0.17.3版本已修复
