### ISSUE TITLE
[Pagination] Pagination组件的疑惑

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next#1073]
### tdesign-vue-next-starter 版本

0.16.0

### 重现步骤

令人疑惑的文档表述方式
![image](https://user-images.githubusercontent.com/36812439/175552999-ac681bcc-1557-4d1a-a82b-745bd386c3eb.png)
这是想给用户两种使用方式还是？

**Comment by uyarn** [comment]
@timi137137 可以理解为下面是vue的on语法糖 @xxx 上面是JSX里的事件语法糖 确实都可以用 而且都需要支持 
可以对比一下 react的文档是没有下面这部分的

**Comment by timi137137** [comment]
> @timi137137 可以理解为下面是vue的on语法糖 @xxx 上面是JSX里的事件语法糖 确实都可以用 而且都需要支持 可以对比一下 react的文档是没有下面这部分的

这个就完美关于我们之前说的文档分离问题了，有待讨论

**Comment by pengYYYYY** [comment]
完美关于我们是？

**Comment by timi137137** [comment]
> 完美关于我们是？

啊？我记得我提过一个关于文档的JS/TS代码分离，然后现在可以顺便对JSX TSX也分离，但是当初是想着先讨论

**Comment by pengYYYYY** [comment]
不是很清楚你想表达的是关于文档里ts的问题，还是我们的时间相关的API会有一个event和一个函数事件参数

**Comment by timi137137** [comment]
> 不是很清楚你想表达的是关于文档里ts的问题，还是我们的时间相关的API会有一个event和一个函数事件参数

文档示例代码中增加JSX和Vue(sfc)的示例切换 帮助用户更好理解事件相关API 就不用上图的

**Comment by pengYYYYY** [comment]
> > 不是很清楚你想表达的是关于文档里ts的问题，还是我们的时间相关的API会有一个event和一个函数事件参数
> 
> 文档示例代码中增加JSX和Vue(sfc)的示例切换 帮助用户更好理解事件相关API

或许可以通过增加一个 `Q&A` 来说明这些东西。在每个 `demo` 做这个事件的切换工作量很大。这个事情挂到这边了 https://github.com/Tencent/tdesign-vue-next/issues/326 

<img width="770" alt="image" src="https://user-images.githubusercontent.com/35833812/175803062-a7ed1eb2-49cb-4295-b9f3-24c6c90244fd.png">
