### ISSUE TITLE
[Select] 自定义 keys 字段别名的场景下，filterable 的时候 placeholder 显示不正确

### ISSUE THREAD

**Issue by skytt** [Tencent/tdesign-vue-next#1078]
### tdesign-vue-next 版本

0.16.1

### 重现链接

https://stackblitz.com/edit/angular-usstrf?file=src%2Fdemo.vue

### 重现步骤

1. 通过 `keys` 参数自定义字段别名，开启 `filterable` 模式
2. 选择一个 option，再次点击编辑框
3. 查看编辑框 placeholder
<img width="1327" alt="image" src="https://user-images.githubusercontent.com/7420660/175856694-66300f03-4c15-42cb-9fd0-dd983710cc77.png">

### 期望结果

和文档 demo 里一样，显示正常的 label 文字，而非直接显示 value （可能是兜底方案？）
如：
<img width="933" alt="image" src="https://user-images.githubusercontent.com/7420660/175856767-ae928b31-f73f-45eb-9421-6500bca5cb4b.png">

### 实际结果

显示了 value

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/1020 已修复

**Comment by pengYYYYY** [comment]
0.17.0已修复
