### ISSUE TITLE
[t-input] type设置成number之后 , maxlength不起作用

### ISSUE THREAD

**Issue by Jinzhengba** [Tencent/tdesign-vue-next#1079]
### tdesign-vue-next 版本

0.16.1

### 重现步骤

<t-form-item label="手机" name="mobile">
    <t-input v-model="formData.mobile" placeholder="请输入手机号" type="number" :maxlength="11" :suffix="suffix"></t-input>
</t-form-item>

### 补充说明

type设置text , tel 都可以起作用

**Comment by pengYYYYY** [comment]
maxlength 与 `type= number` 的结合在浏览器是不生效的。
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-maxlength
<img width="784" alt="image" src="https://user-images.githubusercontent.com/35833812/175886408-27f0deba-6b0f-4206-b681-00653819155d.png">

todo

**Comment by sinbadmaster** [comment]
这个问题我看看呢
