### ISSUE TITLE
[Upload] 图片上传可以给个设置宽高的参数吗？

### ISSUE THREAD

**Issue by williambao** [Tencent/tdesign-vue-next#1087]
### 这个功能解决了什么问题

当用Upload上传图片时(theme=image)， 出来的框可以设置下宽度和高度吗？因为这个图片上传不只有上传功能，还有preview功能，可以当image组件使用。
比如下图的，我在table里用Upload上传个icon, 可能不需要110px的宽高，只要50px就够了。
另外，像一些上传卡片或banner时，可能需要一个长方形的图片。

所以如果把这个.t-upload__card-container里的width和height开放出来让用户可以设置，就好用多了。
![CleanShot 2022-06-28 at 12 18 39@2x](https://user-images.githubusercontent.com/779521/176091868-5875f6e2-9a97-48bf-8ac2-8557f2146f77.png)

### 你建议的方案是什么

Upload组件当theme是image时，可以设置图片框的宽度和高度。

**Comment by chaishi** [comment]
可以通过覆盖 CSS 进行设置吗

**Comment by williambao** [comment]
@chaishi 不太好设置， 除非全局覆盖。 貌似在vue组建内(有scoped)覆盖无法生效。

**Comment by pengYYYYY** [comment]
用:deep https://vuejs.org/api/sfc-css-features.html#scoped-css
