### ISSUE TITLE
[Drawer] closeOnOverlayClick 属性无效 无论设置为true还是false 都会触发关闭事件

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#1097]
### tdesign-vue-next 版本

0.17.1

### 重现步骤

[Drawer] closeOnOverlayClick 属性无效 无论设置为true还是false 都会触发关闭事件

**Comment by pengYYYYY** [comment]
感谢反馈，会在下个版本修复

**Comment by pengYYYYY** [comment]
0.17.3版本已修复

**Comment by pengYYYYY** [comment]
0.17.3版本已修复
