### ISSUE TITLE
split组件

### ISSUE THREAD

**Issue by zhongguodong** [Tencent/tdesign-vue-next#1106]
### 这个功能解决了什么问题
左右切屏，上下切屏

### 你建议的方案是什么？
有开发这个组件的计划吗？

**Comment by timi137137** [comment]
能否提供更多资料？这是什么组件

**Comment by zhongguodong** [comment]
![image](https://user-images.githubusercontent.com/10219953/176458616-3455894d-1d44-435d-9cba-c8e1ce1f36c8.png)

**Comment by zhongguodong** [comment]
很多UI组件，好像都把它给遗忘了，easyui的layout布局组件有，启动split就能拖拉内容区域了。

**Comment by timi137137** [comment]
emmmm你指的是电脑端还是移动端，如果是电脑端能否举例用途 @zhongguodong

**Comment by zhongguodong** [comment]
![image](https://user-images.githubusercontent.com/10219953/176463134-0b474db0-c832-4faf-b5db-1f0d073eccdb.png)

**Comment by timi137137** [comment]
@pengYYYYY 看看然后跟设计部门那边讨论一下？

**Comment by zoooob** [comment]
可以看看这个，https://antoniandre.github.io/splitpanes/

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
