### ISSUE TITLE
[RadioGroup] 第二次赋不存在值时，样式出问题

### ISSUE THREAD

**Issue by fenbitou** [Tencent/tdesign-vue-next#1107]
### tdesign-vue-next 版本

0.17.2

### 重现步骤

variant="primary-filled"  类型的 radio group。 
第一次选中某个选项后，将其置为一个不存在的值，active 会保留上次的状态，但 内容 text 无法正常显示。
<img width="535" alt="image" src="https://user-images.githubusercontent.com/15060047/176373639-4a2f092b-e806-48f6-82b0-e10731ab4cf9.png">

### 期望结果

置为不存在值后，显示全部未被选中的状态。

**Comment by timi137137** [comment]
同样遇到该问题，待会修复
