### ISSUE TITLE
[textarea] 不知道从哪个版本开始,设置高度无效了

### ISSUE THREAD

**Issue by Jinzhengba** [Tencent/tdesign-vue-next#1111]
### tdesign-vue-next 版本

0.17.2

### 重现步骤

<t-textarea v-model="formData.extensions" :style="{ height: '200px' }" />

### 补充说明

之前的某个版本可以 , 但是忘记哪个版本了

**Comment by timi137137** [comment]
什么叫高度无效了，有代码吗，而且我记得0.16及以上都可以手动限制高度
![image](https://user-images.githubusercontent.com/36812439/176445794-a08d57d9-fd9f-4534-8104-b780946739fd.png)

**Comment by sinbadmaster** [comment]
@Jinzhengba 期望的结果是什么呢？

**Comment by sinbadmaster** [comment]
对组件进行测试目前发现有这两种情况：
1. 目前组件的实现中如果设置了autosize，会自动覆盖textarea的高度。这个prop会导致css中的height覆盖，这个在文档里也有体现。如果是想用css自己来覆盖textarea的样式的话，就不需要使用autosize这个属性。这种情况是autosize设置的style为行内样式优先级较高，如一定想要使用css覆盖那么添加```!important```就可以对高度进行覆盖设置
2. 直接使用此类代码来设置样式```<t-textarea :style="{height: '100px'}" />```，Vue组件的class和style默认是由组件内的根元素直接继承，所以设置style会设置到```<textarea />```的父元素上。如果是期望可以将style直接设置到内部的textarea上，那么就需要改变组件的这种默认行为。只是这样是否会对所有组件的一致性有影响？

@pengYYYYY

**Comment by Jinzhengba** [comment]
<t-textarea v-model="formData.residence_district_address" :style="{ height: '100px' }" tips="地址需要具体到门牌号" placeholder="请输入详细户口地址" />
我并没有设置 autosize

**Comment by Jinzhengba** [comment]
<t-textarea v-model="formData.residence_district_address" :style="{ height: '100px' }" tips="地址需要具体到门牌号" placeholder="请输入详细户口地址" />

**Comment by Jinzhengba** [comment]
之前贴的代码没出来 , 没选择代码块

**Comment by Jinzhengba** [comment]
@sinbadmaster 代码贴出来了 , 之前的某个版本是可以的 , 样式没动

**Comment by sinbadmaster** [comment]
@Jinzhengba 好的明白了，属于情况2那种
