### ISSUE TITLE
input演示站不同尺寸实际是相同尺寸

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#112]
tdesign-vue-next版本：
![image](https://user-images.githubusercontent.com/30982989/147806039-b1bbb247-3826-44e8-9cc1-21bd0b23a63c.png)
tdesign-vue版本：
![image](https://user-images.githubusercontent.com/30982989/147806071-4b684e66-39d3-48b4-8e53-f614a628a3b2.png)

**Comment by pengYYYYY** [comment]
修复 PR： https://github.com/Tencent/tdesign-vue-next/pull/136
