### ISSUE TITLE
[Table] 懒加载数据显示错误

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#1122]
### tdesign-vue-next 版本

0.17.2

### 重现链接

https://stackblitz.com/edit/angular-pykccx?file=src%2Fdemo.vue

### 重现步骤

![图片](https://user-images.githubusercontent.com/19170277/176820888-887b5422-3eb3-4511-bf95-fbe324bca66a.png)
点击懒加载加载按钮
![图片](https://user-images.githubusercontent.com/19170277/176820949-131d0f80-0d44-4dbc-bbc7-2a8b4342bcda.png)
再点击子级展开
![图片](https://user-images.githubusercontent.com/19170277/176820998-2fa36d55-431f-4ecb-8247-af55f359ddf7.png)
数据加载到了“10198号下面”，应该加到刚刚点开的子级下面才对
![图片](https://user-images.githubusercontent.com/19170277/176821089-128e5ccb-9109-4151-85c0-fbed7df60701.png)
再点击刚刚展开的子级收起，再展开
![图片](https://user-images.githubusercontent.com/19170277/176821188-f1102c7c-e3b5-424d-97e8-078f31cabd03.png)
结构正常，但数据似乎不对了？

### 期望结果

按照正常树结构展示

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/1219/commits/726c66d837d59740f0bbf7e558a6c2d432e91db9

https://github.com/Tencent/tdesign-vue-next/pull/1219

**Comment by pengYYYYY** [comment]
0.18.0 已修复
