### ISSUE TITLE
[Menu] 分组和操作区 box-sizing: border-box 样式遗漏

### ISSUE THREAD

**Issue by skytt** [Tencent/tdesign-vue-next#1129]
### tdesign-vue-next 版本

0.17.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/menu#%E5%8F%AF%E5%88%86%E7%BB%84%E7%9A%84%E4%BE%A7%E8%BE%B9%E5%AF%BC%E8%88%AA

### 重现步骤

1. 查看 demo

### 期望结果

box样式正常

### 实际结果

box样式不正常
<img width="419" alt="image" src="https://user-images.githubusercontent.com/7420660/176864585-1955e67e-fb89-4bbd-af30-dc5d5a95bdb6.png">

**Comment by pengYYYYY** [comment]
感谢反馈，已收到

**Comment by pengYYYYY** [comment]
0.17.3版本已修复
