### ISSUE TITLE
[TreeSelect] 能否设置节点是一个文件夹还是文件

### ISSUE THREAD

**Issue by hexu2016** [Tencent/tdesign-vue-next#1134]
### 这个功能解决了什么问题

比如节点是文件夹类似的东西时,只可以展开子节点,节点是文件类似的东西时,才可以被选中

### 你建议的方案是什么

希望可以支持

**Comment by pengYYYYY** [comment]
https://tdesign.tencent.com/vue-next/components/tree?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89 可以参考这个自定义图标的树，用 treeprops 去render icon
