### ISSUE TITLE
[Menu] 是否可以调整一下menu组件展开的过度动画，现在的过度太过生硬了

### ISSUE THREAD

**Issue by OneSeven** [Tencent/tdesign-vue-next#1138]
### 这个功能解决了什么问题

视觉效果友好

### 你建议的方案是什么

https://element-plus.org/zh-CN/component/menu.html
https://arco.design/vue/component/menu

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
