### ISSUE TITLE
[Bug][Cascader]组件任意一级缺少高亮效果，变更窗口大小时，弹窗未更新定位

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#114]
![image](https://user-images.githubusercontent.com/30982989/147806519-d11aa2b1-4b02-4342-bb9b-c7de1373589b.png)
对比
选中时：
![image](https://user-images.githubusercontent.com/30982989/147806542-c1dd06d5-65fe-4acd-a9a2-64980d2b7334.png)
未选中时：
![image](https://user-images.githubusercontent.com/30982989/147806658-9539c12a-07d6-440f-8385-0cd9e630870a.png)

变更了浏览器窗口
![image](https://user-images.githubusercontent.com/30982989/147806617-4da1ef97-555c-45fc-a9a5-c9d0be088b7a.png)

**Comment by yixiaco** [comment]
多选数量显示这样会更友好
![image](https://user-images.githubusercontent.com/30982989/147806728-29fb2088-959e-4f16-86e0-01ef1f924f9a.png)

**Comment by yixiaco** [comment]
定位不会更新
![image](https://user-images.githubusercontent.com/30982989/147811422-69d87ae3-32db-4d03-8965-5f6b6c0da2e3.png)

**Comment by yixiaco** [comment]
可以参考我以前用jquery做的效果  😄 🤣
https://yixiaco.github.io/lay_cascader/

**Comment by wy2022** [comment]
很好的建议

**Comment by pengYYYYY** [comment]
Cascader 后面会组合几个input的组件重构，视觉上的问题需要稍等一下。

**Comment by pengYYYYY** [comment]
0.10.0 已修复
