### ISSUE TITLE
[TimePicker] 滚到 23 或者 0 的时候会抽搐几下

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1144]
### tdesign-vue-next 版本

0.17.2

### 重现步骤

https://user-images.githubusercontent.com/11605702/177069816-e0caf6dd-550d-4205-a74f-22b5a3849a49.mov

**Comment by timi137137** [comment]
@chaishi 无法复现
https://user-images.githubusercontent.com/36812439/177116766-68cb72e0-e100-40ee-bc94-0369091dc18d.mov

**Comment by uyarn** [comment]
duplicated of  https://github.com/Tencent/tdesign-vue-next/issues/1012  
在#1012 跟进吧
