### ISSUE TITLE
[table] 分页total发生变化时 当前页数没有改变

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1145]
### tdesign-vue-next 版本

可以

### 重现链接

https://angular-lpvjf4--3000.local.webcontainer.io/

### 重现步骤

本身有30条数据。选中第三页， 搜索一，剩余12条数据，页数疑似还在第三页，但其实应该在第二页，并且分页的高亮消失了

### 期望结果

当分页的total变化时，分页的当前页数应该随着total的变化而变化 

### 实际结果

当分页的total变化时，分页的当前页数并没有随着total的变化而变化 

### 补充说明

当我选中分页的最后一页的时候，去搜索数据，搜出来只有少量数据，分页的当前页数需要变化，

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/177087620-2f5713b3-3e4c-4cf3-84f4-fb8476dd68b6.png)
（思索）待会有时间测试看看

**Comment by timi137137** [comment]
无法复现，能给业务代码吗？

**Comment by luoyu-233** [comment]
[table.txt](https://github.com/Tencent/tdesign-vue-next/files/9037321/table.txt)

**Comment by luoyu-233** [comment]
> 无法复现，能给业务代码吗？
[table.txt](https://github.com/Tencent/tdesign-vue-next/files/9037334/table.txt)

**Comment by timi137137** [comment]
> > 无法复现，能给业务代码吗？
> > [table.txt](https://github.com/Tencent/tdesign-vue-next/files/9037334/table.txt)

用的就是你这个代码，我复现不了你说的`分页total发生变化时 当前页数没有改变`

**Comment by luoyu-233** [comment]
> 无法复现，能给业务代码吗？

分页条数点3，角色名称搜索1，

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/177109163-68ca1c1c-b8d3-46fb-9bd5-18b27b7f7b49.png)

**Comment by timi137137** [comment]
分页器有问题，我看看

**Comment by luoyu-233** [comment]
> 分页器有问题，我看看

麻烦了

**Comment by timi137137** [comment]
@luoyu-233 已修复等待合并，也许下两个版本能修好，目前你可能需要自己截取事件或者每次刷新数据后手动将当前页面设置为1

**Comment by pengYYYYY** [comment]
0.17.3版本已修复
