### ISSUE TITLE
[select] 多选tag显示问题

### ISSUE THREAD

**Issue by GaoXiaoBoGitHub** [Tencent/tdesign-vue-next#1148]
### tdesign-vue-next 版本

0.17.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/select#%E5%A4%9A%E9%80%89%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

![image](https://user-images.githubusercontent.com/41282358/177129874-08178e5e-3022-40e9-93fd-0dac7b54d228.png)

**Comment by uyarn** [comment]
已修复待发布

**Comment by uyarn** [comment]
https://preview-pr1143-tdesign-vue-next.surge.sh/vue-next/components/select

**Comment by pengYYYYY** [comment]
0.17.3版本已修复
