### ISSUE TITLE
[Bug][Tabs]增删选项卡bug

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#116]
![20211231143236](https://user-images.githubusercontent.com/30982989/147807560-06228611-d6cf-4f7b-9871-e9b5e05669ce.gif)
![20211231143330](https://user-images.githubusercontent.com/30982989/147807563-c73521d5-7bbf-4007-8101-3febfa4e98ba.gif)

tdesign-vue版本：
![20211231143448](https://user-images.githubusercontent.com/30982989/147807618-2ef9d224-0f41-48c5-bef3-aeb58dcc2b91.gif)

**Comment by simpleAndElegant** [comment]
i am working on it

**Comment by simpleAndElegant** [comment]
#148

**Comment by yixiaco** [comment]
@simpleAndElegant 
一共有三个bug
1.关闭第一个选项卡时，内容区域不见了
2.关闭全部选项卡时，选项卡不见了
3.超出选项卡长度时，选项卡变长了，而不是和tdesign-vue一样，选项卡长度固定，出现左右箭头可以滑动

**Comment by simpleAndElegant** [comment]
好的 有时间我在看下哈

**Comment by bubai1125** [comment]
![微信图片_20220106110004](https://user-images.githubusercontent.com/49055470/148321390-26287f4a-3983-48e2-b642-9befa5b91458.png)
可滑动的选项卡中 点击左右切换会因为下方选项卡位置不正确而无法点击，需要先点击选项卡才能点击切换

**Comment by pengYYYYY** [comment]
> ![微信图片_20220106110004](https://user-images.githubusercontent.com/49055470/148321390-26287f4a-3983-48e2-b642-9befa5b91458.png) 可滑动的选项卡中 点击左右切换会因为下方选项卡位置不正确而无法点击，需要先点击选项卡才能点击切换

https://github.com/Tencent/tdesign-vue-next/issues/115

**Comment by bubai1125** [comment]
> > ![微信图片_20220106110004](https://user-images.githubusercontent.com/49055470/148321390-26287f4a-3983-48e2-b642-9befa5b91458.png)可跳的选项卡中点击左右切换会因为下面的选项卡位置不正确而无法点击，先需要点击选项卡无法点击切换
> 
> 哈喽，你说的这个问题在本期#115

OK

**Comment by simpleAndElegant** [comment]
最近休假了 我今天开始搞一下哈

**Comment by simpleAndElegant** [comment]
#148

**Comment by pengYYYYY** [comment]
0
