### ISSUE TITLE
Swiper 轮播框 SwiperNavigation 属性BUG

### ISSUE THREAD

**Issue by 4566704** [Tencent/tdesign-vue-next#1162]
### tdesign-vue-next 版本

0.17.3

### 重现链接

https://tdesign.tencent.com/vue-next/components/swiper

### 重现步骤

Swiper组件 API: SwiperNavigation的type属性值'dots'  和 'dots-bar' `无效 

代码如下， 来自官方文档
```
<t-swiper :navigation="{ type: 'dots' }">
  <t-swiper-item>
    <div class="demo-item demo-large">1</div>
  </t-swiper-item>
  <t-swiper-item>
    <div class="demo-item demo-large">2</div>
  </t-swiper-item>
  <t-swiper-item>
    <div class="demo-item demo-large">3</div>
  </t-swiper-item>
</t-swiper>
```

### 期望结果

期望与官方文档描述那样，能显示点状和点条状导航器

官方文档描述：
导航器类型，点状(dots)、点条状(dots-bar)、条状(bars)、分式(fraction)等。

### 实际结果

不显示导导航器

### 框架版本

vue3.2

### 浏览器版本

Chrome/103.0.0.0

### 系统版本

Windows 10 21H2

### Node版本

v14.17.5

**Comment by 4566704** [comment]
顺带把分式(fraction) 也修复一下，它的位置不受placement控制，显示在外侧outside了

**Comment by pengYYYYY** [comment]
@btea 处理中

**Comment by 4566704** [comment]
等待修复

**Comment by pengYYYYY** [comment]
【腾讯 CoDesign】三期组件
https://codesign.qq.com/s/qxWyZ1wErA9mVXk
访问密码：OIPF
