### ISSUE TITLE
滑块只有在鼠标移入元素时会显示弹窗

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#117]
![20211231143947](https://user-images.githubusercontent.com/30982989/147807833-71481d7e-b671-4b59-aae5-2443d353f879.gif)
## antd
![20211231144027](https://user-images.githubusercontent.com/30982989/147807852-7546d007-78de-4bc0-86b3-e36e0f095eaa.gif)

**Comment by vnues** [comment]
这块我来认领
