### ISSUE TITLE
[t-table] 表头吸顶无效

### ISSUE THREAD

**Issue by pony5551** [Tencent/tdesign-vue-next#1170]
### tdesign-vue-next-starter 版本

今天刚下的开发版依然有问题

### 重现链接

http://localhost:3002/#/list/base

### 重现步骤

下载最新release版本或最新开发版，然后npm run dev运行，
http://localhost:3002/#/list/base这里的几个表头吸顶全部无效，我看官网演示是可以的
win 11,edge浏览器(chrome 103)

### 期望结果

-

### 实际结果

-

### 框架版本

Vue(3.2.31)

### 浏览器版本

Microsoft Edge (版本 103.0.1264.37 (正式版本) (64 位))

### 系统版本

Windows 11 专业工作站版 (22000.739)

### Node版本

v16.15.1

### 补充说明

-

**Comment by uyarn** [comment]
> 可以通过调整 attach 来调整滚动的元素

使用问题 我再更新一下starter那边的配置

**Comment by uyarn** [comment]
@pony5551  vue-next 0.17.3版本 https://github.com/Tencent/tdesign-vue-next-starter/pull/215 按这个PR的使用方式 
https://tdesign.tencent.com/starter/vue-next/#/list/base 现在官网已经正常了  可以重新拉一下代码
