### ISSUE TITLE
[table] 合并表格函数无响应式处理

### ISSUE THREAD

**Issue by chiyu1996** [Tencent/tdesign-vue-next#1189]
### tdesign-vue-next 版本

0.17.3

### 重现链接

https://stackblitz.com/edit/angular-ygeglg-ln2jyy?file=src%2Fdemo.vue

### 重现步骤

向数组中添加元素时,合并表格函数没有被调用,导致新增行没有被合并

**Comment by chaishi** [comment]
### 注意写法，示例代码点击添加，直接报错

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/11605702/178176447-1027cba8-5181-45a9-8c52-406b03ec4408.png">

**Comment by chiyu1996** [comment]
> ### 注意写法，示例代码点击添加，直接报错
> <img alt="image" width="1152" src="https://user-images.githubusercontent.com/11605702/178176447-1027cba8-5181-45a9-8c52-406b03ec4408.png">

稍等，没有保存新代码.
https://stackblitz.com/edit/angular-ygeglg-ln2jyy?file=src%2Fdemo.vue

**Comment by chaishi** [comment]
### 内部监听不到外层的变化，调整下写法即可

<img width="591" alt="image" src="https://user-images.githubusercontent.com/11605702/178179693-33c8b488-bd86-4ef1-9c28-53869832f221.png">

**Comment by chaishi** [comment]
### 示例代码里面，改一行代码，就好了

<img width="614" alt="image" src="https://user-images.githubusercontent.com/11605702/178179886-c6348803-de12-4c41-ada1-5661598dac2f.png">

**Comment by chiyu1996** [comment]
> ### 示例代码里面，改一行代码，就好了
> <img alt="image" width="614" src="https://user-images.githubusercontent.com/11605702/178179886-c6348803-de12-4c41-ada1-5661598dac2f.png">

ok，谢谢解答
