### ISSUE TITLE
menu菜单禁用还可以点击

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#119]
![20211231145900](https://user-images.githubusercontent.com/30982989/147808647-1e275699-1ed8-4c8e-87bb-47423fcd515c.gif)

**Comment by pengYYYYY** [comment]
有兴趣的话可以处理一点issue喔

**Comment by yixiaco** [comment]
> 有兴趣的话可以处理一点issue喔

我只是偶尔兼职做一下前端，实际我是后端开发
![3A05DB28](https://user-images.githubusercontent.com/30982989/147809253-c74b24ad-3d32-44ca-9ade-abcac290f414.jpg)

**Comment by yixiaco** [comment]
可以将你们选中时的闪光效果开放成组件出来吗

**Comment by pengYYYYY** [comment]
闪亮效果是哪个

**Comment by pengYYYYY** [comment]
> > 有兴趣的话可以处理一点issue喔
> 
> 我只是偶尔兼职做一下前端，实际我是后端开发 ![3A05DB28](https://user-images.githubusercontent.com/30982989/147809253-c74b24ad-3d32-44ca-9ade-abcac290f414.jpg)

可以的，欢迎用TD，也欢迎提issue，这边会尽快解决哈

**Comment by yixiaco** [comment]
> 闪亮效果是哪个
按钮选中会有一个推进的效果
![20211231152057](https://user-images.githubusercontent.com/30982989/147809505-6fa8d687-eb79-436a-be6c-4bb78b4f9667.gif)

**Comment by pengYYYYY** [comment]
可以可以

**Comment by simpleAndElegant** [comment]
#127
