### ISSUE TITLE
[TreeSelect] 数据回显问题

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#1193]
### tdesign-vue-next 版本

0.17.2

### 重现链接

https://stackblitz.com/edit/angular-fqbsmq?file=package.json,src%2Fdemo.vue

### 重现步骤

![图片](https://user-images.githubusercontent.com/19170277/178202932-05bcd4ea-87fb-4600-bceb-7eff99b60056.png)
value值为1.1，但是数据是在懒加载以后的，希望能在懒加载后，把label“1.1嘿嘿”显示出来，而不是保持1.1

### 期望结果

数据回显能根据懒加载数据联动

**Comment by pengYYYYY** [comment]
0.17.4已修复
