### ISSUE TITLE
[menu] Firefox 顶部导航下拉菜单无法收起

### ISSUE THREAD

**Issue by werfei** [Tencent/tdesign-vue-next#1198]
### tdesign-vue-next 版本

all

### 重现步骤

必重现

### 期望结果

能正常收回

### 实际结果

无法收回，控制台报错

### 浏览器版本

Firefox 102.0.1

### 系统版本

win11

### Node版本

14.17.1

### 补充说明
![图片](https://user-images.githubusercontent.com/18606985/178397846-d7bd3d44-ba41-4ade-8df0-da2001256617.png)

_No response_

**Comment by werfei** [comment]
#1202 pull request

**Comment by pengYYYYY** [comment]
0.19.1 已修复
