### ISSUE TITLE
上传输入框有两个删除按钮

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#120]
![image](https://user-images.githubusercontent.com/30982989/147809639-27d6e37a-3413-471a-a1cf-13e3a98b2aac.png)

**Comment by pengYYYYY** [comment]
应该下周会把这些问题处理掉 🙇‍♀️

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/126
