### ISSUE TITLE
[table] 吸顶表头高度在无横向滚动条情况下会多扣除滚动条的高度6px

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#1200]
### tdesign-vue-next 版本

0.17.4

### 重现链接

https://stackblitz.com/edit/angular-tkjh5r?file=src/demo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/20508822/178444894-0fbdfc09-c83f-4813-a4e5-66a8d0dbd371.png)

### 期望结果

吸顶块高度应与原表头高度一致

### 实际结果

吸顶块高度比原表头少了一个scroll-bar的高度

### 框架版本

Vue(3.2.37)

### 浏览器版本

Chrome(103.0.5060.114)

### 系统版本

MacOS(12.4)

### Node版本

14.19.2

**Comment by litt1e-p** [comment]
try to add height property for `.t-table__affixed-header-elm-wrap` may do help

**Comment by pengYYYYY** [comment]
能否提供更多信息，待提供后再reopen
