### ISSUE TITLE
[tree] 优化单测

### ISSUE THREAD

**Issue by ardor-zhang** [Tencent/tdesign-vue-next#1204]
### 这个功能解决了什么问题

目前的单测能够实现测试的功能，但是当出现错误时，如下，仅仅只能知道出现错误的单测文件，但并不能清楚的看出是哪一个单元出现的错误，无法快速的排查。
![image](https://user-images.githubusercontent.com/44194929/178657282-f221622e-0851-4826-85d1-4791d8c50648.png)
出现这个问题的原因在于单测的 expect 为异步执行的写法上，如下，这样写的话能够跑完整个测试，但是当 expect 执行完成后，it 捕获不到对应的结果，因此建议做一些优化。
![image](https://user-images.githubusercontent.com/44194929/178657569-cfd1b869-f7ed-45a8-80fd-519fbc576cb0.png)

### 你建议的方案是什么

优化的方案大致如下：
异步执行 expect 修改为同步执行
![image](https://user-images.githubusercontent.com/44194929/178658145-270d0edd-967a-4c42-9349-707428474388.png)
这样修改后，it 就能捕获到 expect 的结果
![image](https://user-images.githubusercontent.com/44194929/178658083-20e837a5-79b3-4fed-b506-39ea77e08167.png)

**Comment by ardor-zhang** [comment]
@pengYYYYY 如果方案可行，我可以对此进行优化

**Comment by pengYYYYY** [comment]
可以的
