### ISSUE TITLE
[tree] tree 修改节点时报 node.walk() 异常

### ISSUE THREAD

**Issue by ardor-zhang** [Tencent/tdesign-vue-next#1205]
### tdesign-vue-next 版本

是

### 重现链接

https://codesandbox.io/s/tdesign-react-demo-forked-tob0dv?file=/src/demo.jsx

### 重现步骤

根节点点击两次
<img width="706" alt="image" src="https://user-images.githubusercontent.com/44194929/178663482-e18dd3b3-faa9-47c6-9bb9-70384f9c0c88.png">

### 期望结果

节点正常被修改

### 实际结果

异常错误

**Comment by ardor-zhang** [comment]
1. 问题原因：
此问题是使用上导致的错误，即 setData 传参错误。

2. 优化方案
在尽量少改动的前提下，可以在 setData 做一层拦截，至少避免因此传参错误导致程序崩溃

**Comment by pengYYYYY** [comment]
0.18.2 已修复
