### ISSUE TITLE
[InputNumber] 初始值是null或者空字符串时，输入框边框为error状态

### ISSUE THREAD

**Issue by wdm741206977** [Tencent/tdesign-vue-next#1208]
### tdesign-vue-next 版本

0.17.1

### 重现步骤

[InputNumber] 初始值是null或者空字符串时，输入框边框为error状态

### 期望结果

InputNumber初始值可以为空

### Node版本

v16.14.0

**Comment by timi137137** [comment]
请更新你的组件库版本
