### ISSUE TITLE
[ColorPicker] 下拉框样式异常

### ISSUE THREAD

**Issue by ali-pay** [Tencent/tdesign-vue-next#1212]
### tdesign-vue-next 版本

0.17.4

### 重现链接

https://tdesign.tencent.com/vue-next/components/color-picker

### 重现步骤

![vue3](https://user-images.githubusercontent.com/54493910/178748226-43363121-e03e-4fd0-af75-9d1214051dea.png)
![vue2](https://user-images.githubusercontent.com/54493910/178748823-cd0b0573-3840-4352-b5b4-c3e048ce7351.png)

**Comment by 4566704** [comment]
终于有人反馈了，好几个问题，都没修复好

**Comment by pengYYYYY** [comment]
感谢反馈，最近默认 reset 去掉了，有一些影响

**Comment by pengYYYYY** [comment]
0.17.5 已修复
