### ISSUE TITLE
[TimePicker] 是否考虑支持24:00:00的模式，或者可自定义picker-options

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1213]
### 这个功能解决了什么问题

背景：业务需求涉及到一些起止时间的配置。如 21:00-22:00
![image](https://user-images.githubusercontent.com/3871365/178769150-23f84a0b-c24f-4044-8374-7de828b2d923.png)
但是用了 TimePicker 却不支持24:00,最大选泽到23:59:59，
为了匹配到24:00需要做不少工作量，录入的时候+0.1秒，表单赋值的时候-0.1秒
如果step设置了60分钟，界面上也只能选泽到23:00，使用上废弃了该组件，反而采用select组件来兼容。
是否考虑支持24:00:00的模式?

其他竞品：
ElementUi 支持time-select来支持时间选泽到24:00，可参考
https://element-plus.gitee.io/zh-CN/component/time-select.html

### 你建议的方案是什么

初步方案：TimePicker 支持 24:00:00 的配置，当选到 24 点时分钟和秒自动切换到0

进阶方案：
TimePicker 底层是个 RangePicker，支持更多的范围查询，RangePicker提供个用户使用，支持传入数组 
可实现返回选泽：  【周一】【上午】【10:00】 -------【 周五】【上午】【12:00】

**Comment by linzhenjie** [comment]
业界TimePicker为什么只支持到23:59:59，轮子都一样，还是有个标准？
从产品角度上配置时间上到 24:00:00 ，是符合逻辑的。

因为TimePicker都不能到23:59:59 所以绕弯路用TimeSelect 来处理。

**Comment by uyarn** [comment]
我看看依赖支不支持24:00:00 如果支持可以增加个API来支持你的需求 不是所有场景都需要

**Comment by pengYYYYY** [comment]
issue暂时关闭，如有新的结论，请reopen
