### ISSUE TITLE
极简版分页选择页码被遮挡

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#122]
## tdesign-vue-next
![image](https://user-images.githubusercontent.com/30982989/147810614-8a429269-9180-4910-93fd-0797b01ce6f1.png)

## tdesign-vue
![image](https://user-images.githubusercontent.com/30982989/147810647-e21aa25a-b59d-4cc4-b52a-8f6eadeb8c6f.png)

**Comment by pengYYYYY** [comment]
已处理
