### ISSUE TITLE
[Menu] 侧导航折叠状态下，为图标添加tooltip友好提示

### ISSUE THREAD

**Issue by yangJinRui325** [Tencent/tdesign-vue-next#1220]
### 这个功能解决了什么问题

版本号："tdesign-vue-next": "^0.17.5"
问题描述：侧导航折叠状态下，图标没有文本提示，用户体验不友好。如下图：
![99284f8fb39059841776cae8b7dd71a](https://user-images.githubusercontent.com/27172821/179131710-cf3f8a13-3dc9-4e1f-884b-35e11cf6d924.png)

### 你建议的方案是什么

建议折叠状态下增加提示，如下图
![b6a0734112c68b8bced5fa2fb669d94](https://user-images.githubusercontent.com/27172821/179131754-6454bb97-8329-4423-8d36-3212053d4463.png)

**Comment by timi137137** [comment]
这个问题可能要交给设计那边的同学们查看， @pengYYYYY  py你看看？

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
