### ISSUE TITLE
[Dialog] 会修改body样式

### ISSUE THREAD

**Issue by 4566704** [Tencent/tdesign-vue-next#1221]
### tdesign-vue-next 版本

0.17.3

### 重现链接

https://tdesign.tencent.com/vue-next/components/dialog

### 重现步骤

0.17.4Dialog滚动条遗留bug
Dialog打开后会修改 body的style，如果页面没有滚动条，会导致整个页面左移(变小),并且右侧出现空白
![image](https://user-images.githubusercontent.com/94276735/179133119-d2f3b106-9b64-441f-8285-deaa451b1132.png)

body右侧出现空白
![image](https://user-images.githubusercontent.com/94276735/179133451-afcc3a1c-cbd1-4b37-b265-a040e97eda8a.png)

### 期望结果

body不左移，不出现空白

### 实际结果

body左移变小，出现空白

### 框架版本

vue3.2.25

### 浏览器版本

Chrome/103.0.0.0

### 系统版本

Windows 10 21H2

### Node版本

v14.17.5

**Comment by huoyuhao** [comment]
已领取，预计7.22日前提交修复

**Comment by huoyuhao** [comment]
@4566704  我这里没有复现您所说反馈的问题。
复现demo:页面无滚动，点击按钮弹出dialog(三种mode都试过)，查看body样式，并没有复现您说的bug.
可否详细说一下您的 issue 模版背景信息。

**Comment by 4566704** [comment]
Dialog打开后会修改 body的style，**如果页面没有滚动条，会导致整个页面左移**(变小),并且右侧出现空白   

条件是  如果页面没有滚动条

**Comment by 4566704** [comment]
这种设置逻辑上就有问题，上个版本我反馈了滚动条BUG，开发人员只是把滚动条给隐藏了，并没有修复BUG，这是一个遗留BUG

**Comment by huoyuhao** [comment]
您好，想问一下这里是不是因为使用了微服务框架或者其他框架导致的。
或者可否把demo放在https://stackblitz.com/。目前最新版本0.18.0 没有复现这个bug。

**Comment by 4566704** [comment]
我提交的的，就是官方文档。稍后写个demo

我一点一点说吧：

1.Dialog打开后会修改 body的style  body的宽度减少 一个滚动条宽度左右
2.如果页面没有滚条动，不就出现空白了么(上面图2所示)

正确应该是 像  0.0.16版本那样，或者动态获取页面是否有滚动条(考虑浏览器窗口大小变化)，再去减少body宽度
这种设置逻辑上就是错的

**Comment by 4566704** [comment]
上个修复Dialog BUG的开发人员，只想着2分钟修复BUG(改body的style)，直接隐藏滚动条，并没有把BUG给修复了

**Comment by huoyuhao** [comment]
您好，我说一下对您反馈的理解：
1、第一个是Dialog打开，如果有滚动跳，会修改 body的style body的宽度减少 一个滚动条宽度左右；
2、如果没有滚动条，预期效果不应该修改body的style；

目前，我看代码实现是通过Dialog创建后，计算滚动条宽度：
```
 onMounted(() => {
    scrollWidth.value = window.innerWidth - document.body.offsetWidth;
  });
```
然后dialog打开，查看scrollWidth是否大于0，大于的话，修改body减去滚动宽度，同时body不能滚动（相当于隐藏滚动条）。

这边您的问题是
1、没有滚动条，body减去了滚动宽度，不符合预期（这里我没有复现）；
2、应该动态获取页面是否有滚动条(考虑浏览器窗口大小变化)，再去减少body宽度，而不是onMounted事件中

您看我的理解是否正确

**Comment by 4566704** [comment]
是的。

最快复现方式就是，按F12 把滚动条隐藏掉， body  style overflow: hidden;
dialog 的 showOverlay = false  就能清楚的看到右侧空白了

在官方文档中就能复现bug   https://tdesign.tencent.com/vue-next/components/dialog

**Comment by huoyuhao** [comment]
如果页面存在滚动
showOverlay : true  preventScrollThrough : true 遮罩层且禁止滚动穿透 隐藏滚动条，body - scrollWidth
<img width="1672" alt="image" src="https://user-images.githubusercontent.com/13276425/180158467-8e1cd92f-8195-4bb1-8b08-1ca0d0d591ee.png">

showOverlay : true  preventScrollThrough : false 遮罩层且不禁止滚动穿透 显示滚动条，body不减去scrollWidth
<img width="1669" alt="image" src="https://user-images.githubusercontent.com/13276425/180158586-5c955905-67c2-46ee-bdf8-cdb236702a8f.png">

showOverlay : false  preventScrollThrough : true 隐藏遮罩层且禁止滚动穿透 隐藏滚动条，body - scrollWidth
<img width="1707" alt="image" src="https://user-images.githubusercontent.com/13276425/180158735-29c7fda7-3ae5-4c30-a10b-ac1db3588e86.png">

showOverlay : false  preventScrollThrough : false 隐藏遮罩层且不禁止滚动穿透 显示滚动条，body不减去scrollWidth
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/13276425/180158785-3d4806fa-e360-48b8-837c-003cfc696c0f.png">

以上应该是期望内容，看是否符合你的要求。

另外没有复现页面没有滚动会导致body减去了滚动宽度，不符合预期（这个可否发一下dialog配置）

**Comment by 4566704** [comment]
是的。

不隐藏滚动条场景，也会有这BUG，我得再检查一下什么原因引起的。
目前猜测是：原本页面无滚条动，也不隐藏滚动条。当弹出对话框，就会导致页面出现滚动条，tdesign框架使用了 class="t-dialog--lock"  隐藏了滚动条，总结：还是隐藏了滚动条。

**Comment by 4566704** [comment]
终于找到原因了，哎。乌龙事件.....

过程：
1.我使用了  height:'calc(100vh - xx) 计算 t-content 高度
2.当打开Dialog 会影响 100vh  导致calc计算后页面出现滚条动- > Dialog 计算 scrollWidth.value 时页面已经有滚条动了

**这算乌龙，我没认真检查，辛苦你了，我的错。**
项目中不要用 100vh 就可以了，因为Dialog 打开时会影响它。

可能检查的还是不太严谨

**Comment by 4566704** [comment]
虽然是个乌龙，还是希望考虑一下 overflow: hidden; 场景，或者是有人在项目中使用 100vh

**Comment by huoyuhao** [comment]
目前确实存在问题，我们也在讨论这个问题，因为实际是不提倡修改body样式，这样会造成全局样式污染，而且在微前端框架还存在问题，不过具体方案可能还需要讨论一下。

这边我稍后修复一下preventScrollThrough的问题

**Comment by huoyuhao** [comment]
另外，非常感谢您提供的issue问题，下次建议提供一下组件的参数，这样可能更方便定位问题，如果有线上demo更好。

**Comment by 4566704** [comment]
一直没找到原因，就没提供参数。

现在还是没找到原因，需要在特定的组件中才能复现，现在定位到  t-aside了，还需要一点时间

**Comment by 4566704** [comment]
本来 几个小时前 就能给demo了，因为忽略掉了  t-aside

**Comment by 4566704** [comment]
本来3个小时前就能找到原因了，写demo时 没引用  t-aside，就分析其他原因去了。

```
<template>
  <!--背景颜色 方便观察-->
  <div style="background-color: #000000;">
    <t-layout>
      <t-layout>
        <t-aside style="background-color: #00a870;">
          只位，不能删除
        </t-aside>

        <!--下方 calc(100vh)  为了计算内中后台内容高度 为了演示BUG 简化成 calc(100vh)-->
        <t-content style="height: calc(100vh); background-color: #ed7b2f;">
          <t-button @click="visible=true;">打开对话框</t-button>
        </t-content>
      </t-layout>
    </t-layout>
  </div>

  <!--对话框-->
  <t-dialog v-model:visible="visible">
    <p>This is a dialog</p>
  </t-dialog>
</template>

<script lang="ts" setup>
import { ref } from "vue";

const visible= ref(false);
</script>

<style>
body{
  margin: 0px;
}
</style>


```

**Comment by huoyuhao** [comment]
确实，有时候确实很难分析问题原因，我最开始也没有想到preventScrollThrough的原因。
这边preventScrollThrough的问题我提交一个pr修复，是否还有其他问题？

**Comment by 4566704** [comment]
你测试我上面 提供的demo没有，它是 dialog 还是 t-layout的问题

**Comment by 4566704** [comment]
简化后的demo，去掉了calc(100vh)替换成了固定高度

最终发现  t-aside 高度 + t-content 高度 大于浏览器可视窗口高度，打开对话框就会出现被隐藏的滚动条


```
<template>
  <!--背景颜色 方便观察-->
  <div style="background-color: #000000;">
    <t-layout>
      <t-layout>
        <!--下方 t-aside 高度 + t-content 高度 大于浏览器可视窗口高度，就会出来滚动条  -->
        <!-- 测试时请修改下方两个组件高度，相加后要大于浏览器可视窗口高度 -->
        <t-aside style="background-color: #00a870;height: 400px;"></t-aside>
        <t-content style="height: 800px; background-color: #ed7b2f;">
          <t-button @click="visible=true;">打开对话框</t-button>
        </t-content>
      </t-layout>
    </t-layout>
  </div>

  <!--对话框-->
  <t-dialog v-model:visible="visible">
    <p>This is a dialog</p>
  </t-dialog>
</template>

<script lang="ts" setup>
import { ref } from "vue";

const visible= ref(false);
</script>

<style>
body{
  margin: 0px;
}
</style>
```

**Comment by 4566704** [comment]
要不把话题关闭了吧，等更新后再测试看看。把问题反馈到t-layout组件，应该是他们style没搞好

**Comment by huoyuhao** [comment]
我先把preventScrollThrough的问题修复掉，然后再关闭话题

**Comment by pengYYYYY** [comment]
0.18.1已修复
