### ISSUE TITLE
[Select] Select 在表格里面，要点 2 次，才能退出编辑态

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1227]
### tdesign-vue-next 版本

0.17.5

### 重现步骤

<img width="631" alt="企业微信截图_6dcb9e0c-c5fc-4c90-a806-53b0210bf0d4" src="https://user-images.githubusercontent.com/11605702/179217103-682ca14a-5412-45ac-8cb0-55e7a2ce45bc.png">

**Comment by morningbao** [comment]
尝试了一下table里嵌多选select，并没有出现描述的问题。
[demo链接](https://codesandbox.io/s/table-cell-multi-select-ir9pyy?file=/src/demo.vue)

**Comment by chaishi** [comment]
官网「可编辑行」功能里面，可复现

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
