### ISSUE TITLE
[t-table] 当表格水平与垂直滚动条同时出现时，右下角会出现白点（仅暗黑模式）

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next#1233]
### tdesign-vue-next 版本

0.17.5

### 重现步骤

在drak主题下才能复现
![image](https://user-images.githubusercontent.com/36812439/179351703-40e43d41-9e27-414b-aa22-a8e037df1aed.png)

### 实际结果

样式统一为黑色

**Comment by litt1e-p** [comment]
@timi137137 just rewrite style for ***t-table*** in:
```css
background-color: var(--td-bg-color-container);
```

**Comment by RayJason** [comment]
👌认领此issue，今日提交
![image](https://user-images.githubusercontent.com/15711610/183265361-17a3037b-704d-4bf6-bc72-feeb98000207.png)
![image](https://user-images.githubusercontent.com/15711610/183265373-31ce78f9-529e-49f4-aa13-8370e1efce79.png)

**Comment by pengYYYYY** [comment]
0.19.1 已修复
