### ISSUE TITLE
[TreeSelect] 希望可以获取到Tree对象

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#1238]
### 这个功能解决了什么问题

https://stackblitz.com/edit/angular-3bcdbo-ejncql?file=src%2Fdemo.vue
1.已知value值‘1.1’对应的label是‘1-1’，但又有树数据未加载。所以只能select内只能显示‘1.1‘
2.通过valueDisplay去控制显示内容，配合一个判断方法，当树结构中存在value值，则显示树结构中对应的label，没有的话则默认显示已知label
3.但由于tree的data不是响应式数据，所以判断方法永远只能判断初始的树数据，一直是false
![图片](https://user-images.githubusercontent.com/19170277/179471614-dcda5bf8-acd5-4db4-a05a-b3536526e867.png)

### 你建议的方案是什么

1.新增可以获取tree的对象透传方法，比如treeProps中传入ref:xxxx，可以通过ref值调用tree的getItem
2.将treeData改成响应式
3.有别的解决方案可以实现以上需求

**Comment by pengYYYYY** [comment]
这个PR 好像修复过这个问题https://github.com/Tencent/tdesign-vue-next/pull/1194

**Comment by Waynefong** [comment]
> > > 这个PR 好像修复过这个问题#1194
> > 
> > 
> > 这个是回显，这次的需求不是回显。我知道这个value对应的label是‘1-1’，**树结构里没有这个value我也给他显示上去这个label值**，如果有这个value就正常显示
> 
> 直接将下层的数据写在data里觉得怎么样？能解决你的问题吗？ https://stackblitz.com/edit/angular-sejwm7?file=src%2Fdemo.vue

这样会有问题呢，假设这是一个三级节点四级节点。我也不知道他属于哪个二级哪个三级。如果都采用预先写好的方式。提前去递归获取数据，就等于失去了懒加载的意义了。

**Comment by Waynefong** [comment]
> 这种情况改selectInput的value可以直接覆盖显示值，可以满足您的需求嘛

这个处理一下应该也可以，现在用的是tree-select里的valueDisplay解决了这个需求。感谢感谢啦

**Comment by pengYYYYY** [comment]
好的
