### ISSUE TITLE
[Bug][menu] menu-item在不使用icon插槽的时候, 在左侧收回的时候多了一个数字

### ISSUE THREAD

**Issue by wzs28150** [Tencent/tdesign-vue-next#124]
## tdesign-vue-next

You will open a bug issue at tdesign-vue-next。

### Describe Environment

browser version: 
tdesign-vue-next version: 0.6.0

### Describe the bug
menu-item在不使用icon插槽的时候, 在左侧收回的时候多了一个数字
![image](https://user-images.githubusercontent.com/21290257/147812498-34bdf4c6-a933-4287-9ae5-628e459f99ed.png)
问题出在样式这，不知道这个1起什么作用
![image](https://user-images.githubusercontent.com/21290257/147812364-f8c41620-2c0c-4859-920c-4ce3029c1382.png)

codesandbox online demo:

**Comment by pengYYYYY** [comment]
挺巧的，今天我们也发现了这个问题，已经在修复了，感谢反馈
