### ISSUE TITLE
[t-radio] 点击选择父盒子点击事件触发两次

### ISSUE THREAD

**Issue by jianfa007** [Tencent/tdesign-vue-next#1240]
### tdesign-vue-next 版本

0.17.4

### 重现链接

https://codesandbox.io/s/dawn-sound-8qqg9n

### 框架版本

Vue(3.2.37)

### 浏览器版本

Chrome(101.0.4951.54)

### 系统版本

Windows

### Node版本

16.15.1

**Comment by timi137137** [comment]
你把事件写在父组件上肯定触发两次啊，你倒是把事件写在组件里啊

**Comment by jianfa007** [comment]
写在父标签不会触发两次的，除非你子组件和父标签事件名写成一样的；点击子组件是通过冒泡触发的父标签事件，阻止子组件冒泡事件父标签事件不会触发；

**Comment by timi137137** [comment]
测试了一下，组件好像不接受修饰符
![image](https://user-images.githubusercontent.com/36812439/179691070-58de84c3-ebd0-45b7-8278-54fb63f058b5.png)
等待其他开发人员help

**Comment by pengYYYYY** [comment]
0.18.1已修复
