### ISSUE TITLE
[Menu]火狐浏览器中横版导航布局不能自动关闭

### ISSUE THREAD

**Issue by itlanjing** [Tencent/tdesign-vue-next#1243]
### tdesign-vue-next-starter 版本

0.3.5

### 实际结果

![微信截图_20220716120453](https://user-images.githubusercontent.com/92659423/179338585-fb0de749-790e-4c31-8116-c111737c054b.png)

**Comment by pengYYYYY** [comment]
升级大新版本看看呢

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
