### ISSUE TITLE
【咨询】【抽屉】请问怎么不显示“抽屉组件的‘’确认button和取消button”

### ISSUE THREAD

**Issue by jamesz2011** [Tencent/tdesign-vue-next#1244]
### 这个功能解决了什么问题

![image](https://user-images.githubusercontent.com/16397200/179524338-9a4fddd7-da53-488a-a0b0-8f8e13cd6fe3.png)

### 你建议的方案是什么

![Uploading image.png…]()

**Comment by chaishi** [comment]
请参看 API 文档里面写的，confirmBtn 或者 cancelBtn 值为 false 或者 null 时不显示

**Comment by pengYYYYY** [comment]
footer false 可以隐藏

**Comment by jamesz2011** [comment]
@pengYYYYY 感谢，footer=" ",就能解决
![image](https://user-images.githubusercontent.com/16397200/179696917-8380d77f-b02c-4c5d-aa96-ad23fefd1d1e.png)
