### ISSUE TITLE
[Table] 滚动条应该位于tbody内，目前滚动条可以传入header，效果不是很美观

### ISSUE THREAD

**Issue by L1yp** [Tencent/tdesign-vue-next#1245]
### 这个功能解决了什么问题

滚动条设计问题

### 你建议的方案是什么

实现一个滚动条组件在tbody使用~

**Comment by chaishi** [comment]
不接受“滚动条应该位于 tbody 内”这个设定
也不接受“ header”包含滚动条就不美观这个主观感受

横向滚动条，固定左侧列和固定右侧列 也包含滚动条。同理，固定的表头为何就不能包含滚动条

**Comment by chaishi** [comment]
再解释下原因：目前的非吸顶表格，且非虚拟滚动表格，固定列和固定表头的 thead 和 tbody 均公用一个表格，只渲染一次 thead 和 tbody 。
但如果为了你说的 只有 tbody 滚动，thead 不包含在内的这个效果，就需要多一次重复渲染 thead 和 tbody 中的 固定表头、固定列。当数据量大的时候，重复渲染是一件得不偿失的事情
