### ISSUE TITLE
[描述列表 Description] 新增描述列表组件

### ISSUE THREAD

**Issue by gotounix** [Tencent/tdesign-vue-next#1246]
### 这个功能解决了什么问题

用于详情页的展示

### 你建议的方案是什么

类似：

https://arco.design/vue/component/descriptions

https://element-plus.org/zh-CN/component/descriptions.html

**Comment by gotounix** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/1139

**Comment by timi137137** [comment]
@gotounix 重复了，你关了吧，等设计那边出设计才能做
