### ISSUE TITLE
[InputNumber] 交互问题

### ISSUE THREAD

**Issue by Hongic** [Tencent/tdesign-vue-next#1247]
### tdesign-vue-next 版本

0.18.0

### 重现步骤

https://tdesign.tencent.com/vue-next/components/input-number
InputNumber 数字输入框
这里的演示有点问题：
1、输入66
2、开启readonly
3、点击66文本框
4、随意点击空白处
文本框会出现66被删除

### 期望结果

readonly 开启时，点击数字文本框后，点击其他地方，值不能被清空

**Comment by pengYYYYY** [comment]
0.18.1已修复
