### ISSUE TITLE
[Table]表格列拖拽之后设置列配置，位置错乱（Vue3 拖拽排序统一问题）

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1250]
### tdesign-vue-next 版本

1.8.0

### 重现链接

https://stackblitz.com/edit/angular-kw2scy-xtqvcs?file=src%2Fdemo.vue

### 重现步骤

当我将资产大类和资产净值拖拽换完顺序之后去列配置里面展示一个市值字段，表格的字段出现了混乱

### 期望结果

拖拽完之后的表格希望再去设置列配置不会出现表格字段混乱

### 实际结果

当我将资产大类和资产净值拖拽换完顺序之后去列配置里面展示一个市值字段，表格的字段出现了混乱

**Comment by luoyu-233** [comment]
这是代码

**Comment by luoyu-233** [comment]
> Vue3 的拖拽排序：行拖拽排序 和 列拖拽排序，都有点问题。(Vue3 和 React 正常）

vue3的有问题

**Comment by luoyu-233** [comment]
[index.zip](https://github.com/Tencent/tdesign-vue-next/files/9138495/index.zip)
附带上代码

**Comment by luoyu-233** [comment]
给表格加上 hover 属性 好像并没有悬浮效果

**Comment by litt1e-p** [comment]
Table component should expose a doLayout method for those rerender needs

**Comment by chaishi** [comment]
针对 Vue3 特殊处理
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2105 https://github.com/Tencent/tdesign-vue-next/pull/2105/commits/d1fc58302908cc86d3cce512b55dd749fa5f2f35
