### ISSUE TITLE
[Table] 数据重置后表格dom没有变化

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#1251]
### tdesign-vue-next 版本

0.18.0

### 重现链接

https://stackblitz.com/edit/angular-jjzvm9?file=package.json,src%2Fdemo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/19170277/179693585-0637855c-b271-40fb-af6c-b6141f45bd52.png)
展开66666这条数据
![image](https://user-images.githubusercontent.com/19170277/179693667-49d0ac40-f76b-459f-9428-49e89acd22a9.png)
点击重置数据
![image](https://user-images.githubusercontent.com/19170277/179693854-4449017a-f5cc-4eac-814d-c54a24fbff1b.png)
数据层面更新了，但dom没有更新

### 期望结果

希望重置后恢复到初始加载的样子，可以重新进行懒加载等等

**Comment by ssdate** [comment]
解决了吗？就是数据更新之后视图不更新把？ 现在表格数据更新之后，视图不更新。

**Comment by chaishi** [comment]
解决了，请使用组件实例方法 `tableRef.value.resetData(newData)` 更新视图
