### ISSUE TITLE
[SelectInput ] 筛选器输入框 输入值按确定，文本框没有清空值

### ISSUE THREAD

**Issue by Hongic** [Tencent/tdesign-vue-next#1252]
### tdesign-vue-next 版本

0.18.0

### 重现步骤

https://tdesign.tencent.com/vue-next/components/select-input
SelectInput 筛选器输入框
![image](https://user-images.githubusercontent.com/8119873/179895111-4c6d1a9e-67aa-444c-92e4-db7d695ac518.png)
文本框输入值，按enter，生产了选项，但是文本框的值没有清空，导致输入下个值时连着
![image](https://user-images.githubusercontent.com/8119873/179895465-094e30f1-a9fc-4236-a937-fe53509adbc3.png)

### 期望结果

文本框确定时，生成选项，同时清空文本框输入的值

**Comment by pengYYYYY** [comment]
这个需要组件调用方处理，selectIinput 需要满足很多种场景
