### ISSUE TITLE
选择下拉组件有bug 二次封装显示不出数据内容。

### ISSUE THREAD

**Issue by wfc66986** [Tencent/tdesign-vue-next#1253]
### tdesign-vue-next 版本

0.17.5

### 重现步骤

请问选择器下拉组件二次封装后 版本0.17.5插槽使用有问题数据不出来.在0.15.4版本是没问题的.

![1](https://user-images.githubusercontent.com/54029486/179909143-e360b095-537d-480c-87a8-a1764a3fdcc5.png)

![2](https://user-images.githubusercontent.com/54029486/179909056-761c2fa7-2fec-4fef-b83c-0f9d6a3b8b97.png)
![3](https://user-images.githubusercontent.com/54029486/179906524-9a220f18-b147-41ee-ac14-a44b8eb796dc.png)
![4](https://user-images.githubusercontent.com/54029486/179906538-4ff73661-f30c-47c6-aae1-a4114a320b7c.png)

### 期望结果

希望下个版本出来能解决 可以测试下0.15.4版本可以的 辛苦了。

### 实际结果

二次封装组件支持.

### 框架版本

3.2.37

**Comment by timi137137** [comment]
也许你能提供完整的代码？

**Comment by wfc66986** [comment]
我那上面有代码图&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月20日(周三) 下午5:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-vue-next] 选择下拉组件有bug 二次封装显示不出数据内容。 (Issue #1253)




 
也许你能提供完整的代码？

**Comment by wfc66986** [comment]
select 下拉二次封装代码在0.15版本是可以运行的 最新0.17就不可以了。麻烦帮忙看下谢谢项目已在使用麻烦安排下。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-vue-next"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月20日(星期三) 晚上6:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue-next] 选择下拉组件有bug 二次封装显示不出数据内容。 (Issue #1253)





  
我那上面有代码图&nbsp;
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2022年7月20日(周三) 下午5:06 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [Tencent/tdesign-vue-next] 选择下拉组件有bug 二次封装显示不出数据内容。 (Issue #1253) 也许你能提供完整的代码？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
不够完整

**Comment by wfc66986** [comment]
请问解决好了吗 多久发布下已在开发使用中

**Comment by pengYYYYY** [comment]
下周一会解决

**Comment by pengYYYYY** [comment]
0.18.1已修复
