### ISSUE TITLE
Calendar 日历

### ISSUE THREAD

**Issue by wfc66986** [Tencent/tdesign-vue-next#1254]
### tdesign-vue-next 版本

0.17.5

### 重现步骤

Calendar 日历二次封装插槽使用不生效，希望能得到解决。
![image](https://user-images.githubusercontent.com/54029486/179930563-d9d9a90f-13b5-4744-ba3b-aee32c781176.png)
![image](https://user-images.githubusercontent.com/54029486/179930899-c51737f3-c8ab-498b-84ee-52574c393f3f.png)
![image](https://user-images.githubusercontent.com/54029486/179930959-18feb176-9f76-468a-b400-a8d3159b2607.png)

**Comment by wfc66986** [comment]
日历组件二次封装 界面能出来能使用但是插槽使用不了值为空。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-vue-next"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月20日(星期三) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue-next] Calendar 日历 (Issue #1254)





 
也许你能给完整的代码？

**Comment by PsTiu** [comment]
> 日历组件二次封装 界面能出来能使用但是插槽使用不了值为空。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Tencent/tdesign-vue-next" ***@***.***&gt;; 发送时间:&nbsp;2022年7月20日(星期三) 下午5:05 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Tencent/tdesign-vue-next] Calendar 日历 (Issue #1254) 也许你能给完整的代码？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

你好，可以尝试修改如下：
![image](https://user-images.githubusercontent.com/880720/180351820-593d1771-c48e-41c0-ac11-8b7317c35079.png)
