### ISSUE TITLE
[Card卡片] loading属性无法使用

### ISSUE THREAD

**Issue by colafun** [Tencent/tdesign-vue-next#1259]
### tdesign-vue-next 版本

0.17.5以上版本

### 重现链接

https://tdesign.tencent.com/vue-next/components/card?tab=demo

### 重现步骤

<template><t-card
  loading>
          仅有内容区域的卡片形式。卡片内容区域可以是文字、图片、表单、表格等形式信息内容。可使用大中小不同的卡片尺寸，按业务需求进行呈现。
        </t-card></template>
带上loading属性就报错
![1011fedfa813fb0b8b8b9e9e0a7bfc4](https://user-images.githubusercontent.com/20595364/180150855-ec914f5c-0be0-4bcb-ba7c-dc3f9a7844cd.png)

### 期望结果

<template><t-card
  loading>
          仅有内容区域的卡片形式。卡片内容区域可以是文字、图片、表单、表格等形式信息内容。可使用大中小不同的卡片尺寸，按业务需求进行呈现。
        </t-card></template>
带上loading属性就报错
![1011fedfa813fb0b8b8b9e9e0a7bfc4](https://user-images.githubusercontent.com/20595364/180150855-ec914f5c-0be0-4bcb-ba7c-dc3f9a7844cd.png)

**Comment by pengYYYYY** [comment]
0.18.1已修复
