### ISSUE TITLE
[Table] 反向排序功能

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1263]
### 这个功能解决了什么问题

当我首次点击降序的icon时，降序高亮，再次点击的时候，取消了排序，感觉有点呆呆的，可以再次点击的时候切换到升序吗，如果可以反向排序是否交互体验会好一点

### 你建议的方案是什么

当我没有开始排序的时候，首次点击降序的icon时，降序排序，再次点击的时候要升序排序，再次点击取消排序

**Comment by chaishi** [comment]
如果想升序，可直接点击「升序图标」，而非通过点击「降序图标」来达到「升序」的效果，不符合正常认知

交互非常不合理，不予处理。
