### ISSUE TITLE
[Tree] 如果是目录树，可以限制叶子结点不能drop到子结点作为 从而变为目录

### ISSUE THREAD

**Issue by zhoulujun** [Tencent/tdesign-vue-next#1265]
#### 1. 如果是目录树，可以限制叶子结点不能drop到子结点作为 从而变为目录，
![wecom-temp-f9963c5506c9ff80d647b1f201abcd52](https://user-images.githubusercontent.com/4243366/180208215-d5eae0e6-7c83-4a74-b29f-399f55a10be9.png)
比如在element-ui，allow-drop ,返回为false，即不接收子结点。node-drop 返回 false，会取消拖曳。
![image](https://user-images.githubusercontent.com/4243366/180216346-2fdb7736-f7fe-410c-a14c-1bebc0abf36f.png)
#### 你建议的方案是什么

增加 allow-drop ，属性。
让用户判断是否 可以drop。比如有的目录不接收子结点，或者达到一定条件，才可以接收子结点。

####  2.  增加目录值可以收放（展开、关闭），不能关闭选中
比如目录，叶子结点才是具体的业务 id，其他为目录，不可选中
![image](https://user-images.githubusercontent.com/4243366/180217754-5d6e8b91-6439-4189-8551-5bfae6aa0c84.png)

#### 你建议的方案是什么
增加 expand-on-click-node，或者 取值  node-clik 函数

**Comment by zhoulujun** [comment]
> 需改了

**Comment by ardor-zhang** [comment]
@pengYYYYY 可以具体的讨论一下，包括具体的功能和属性名

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
