### ISSUE TITLE
[Upload] 上传组件无法完全自定义上传方法

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next#1266]
### tdesign-vue-next 版本

0.18.0

### 重现步骤

requestMethod没有暴露内部xhr函数，导致无法控制上传进度

### 期望结果

![image](https://user-images.githubusercontent.com/36812439/180240046-944188a8-bc17-4733-bfc7-7d71d3d45475.png)
暴露内部参数供完全自定义

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/180267117-6e2c0f03-1b4b-47cc-bb80-f118172eac13.png)
![image](https://user-images.githubusercontent.com/36812439/180267185-12e52cbb-d8d1-47d2-8353-d9dd10a52b4a.png)
谁跟我说能用file.percent我跟谁急

**Comment by pengYYYYY** [comment]
你这是哪个版本，file.percent 有响应问题

**Comment by timi137137** [comment]
> 你这是哪个版本，file.percent 有响应问题

![image](https://user-images.githubusercontent.com/36812439/180474475-163e6f5d-6829-4416-9e10-5f86d024c9de.png)

**Comment by pengYYYYY** [comment]
ok，我看下这个场景怎么修复

**Comment by timi137137** [comment]
> ok，我看下这个场景怎么处理

卑微，因为这个问题我被老板骂了好几天。交给你了

**Comment by linzhenjie** [comment]
可以的，直接拿file上传即可

<img width="315" alt="image" src="https://user-images.githubusercontent.com/3871365/180489371-528dd9f6-2b36-4c3d-8f1a-df5de637d784.png">



<img width="701" alt="image" src="https://user-images.githubusercontent.com/3871365/180489353-8b525268-b51e-48cf-9145-bad815e38381.png">

`      onUpload(files: UploadFile) {
        return new Promise((resolve) => {
          if (!files.raw) {
            resolve({ status: "fail", error: "未选择文件", response: {} });
            return;
          }
          let reader = new FileReader();
          const name = files.name || "";
          const extname = name.split(".").reverse()[0];
          reader.readAsDataURL(files.raw);
          reader.onload = function () {
            if (!reader.result || typeof reader.result !== "string") {
              resolve({ status: "fail", error: "未选择文件", response: {} });
              return;
            }
            const blob = fileUrltoBlob(reader.result);
            Upload({ file: blob, extname: extname[0] }).then((res) => {
              if (res.code === 0) {
                resolve({
                  status: "success",
                  response: {
                    url: res.url,
                  },
                });
              } else {
                resolve({ status: "fail", error: res.msg, response: {} });
              }
            });
          };
        });
      },
      onFail(e) {
        console.log(e);
      },`

**Comment by pengYYYYY** [comment]
增加了一个实例方法，`setPercent` 用于设置上传进度，直接改 `file` 有响应式问题，等后续对组件全局状态做一次重构

**Comment by pengYYYYY** [comment]
0.18.2已修复,增加了相关示例
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/35833812/182334145-85a3f047-0e7d-40c6-9f68-10ebc73247a3.png">
