### ISSUE TITLE
[Textarea] 最大字符数显示区域被遮挡

### ISSUE THREAD

**Issue by qianglao007** [Tencent/tdesign-vue-next#1268]
### tdesign-vue-next 版本

0.18.0

### 重现链接

https://stackblitz.com/edit/angular-t5woxu?file=src%2Fdemo.vue

### 重现步骤

textarea使用maxlength属性限制一个比较大的字数， 输入比较多的字符，当字符到textarea右下角的时候会遮挡最大字符数区域

### 期望结果

最大字符数区域不被遮挡

### 实际结果

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/906136/180350620-8844c5ea-7d0a-42c2-a97d-704b6e4db232.png">

### 框架版本

Vue 3.2.31

### 浏览器版本

Chrome( 103.0.5060.114)

### 系统版本

MacOS(12.4)

**Comment by pengYYYYY** [comment]
0.18.1已修复

**Comment by qianglao007** [comment]
在最大字符数显示区域加背景色不就变成了底下文字被遮挡了？
