### ISSUE TITLE
[select] onChange回调选中相同的选项也有回调

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#1276]
### tdesign-vue-next 版本

0.17.4

### 期望结果

![image](https://user-images.githubusercontent.com/10460238/180377496-a908c1c0-f64a-49b7-9e47-a24028b6c214.png)
期望选中不同的选项才有回调

### 实际结果

期望相同的选项也有回调

**Comment by pengYYYYY** [comment]
0.18.1已修复
