### ISSUE TITLE
[InputNumber] 数字输入框 增加 label、suffix、suffixIcon

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1281]
### 这个功能解决了什么问题

数字输入框  应该和输入框 有同样的表现形式，增加 label、suffix、suffixIcon 属性

<img width="637" alt="image" src="https://user-images.githubusercontent.com/3871365/180485866-d9807a0b-dd3b-4b89-9051-2c1c00236249.png">

### 你建议的方案是什么

同输入框

**Comment by pengYYYYY** [comment]
`input-number` 依赖于 `input` 实现，可以通过 `inputProps` 属性透传所有 `input` 的属性
