### ISSUE TITLE
[Upload] 上传组件蒙层内容可自定义成slot

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1282]
### 这个功能解决了什么问题

<img width="327" alt="image" src="https://user-images.githubusercontent.com/3871365/180486028-432c9a30-c11b-4002-a51d-bbeca2483cb3.png">

上传组件蒙层内容可自定义slot

点击删除按钮可最加事件

### 你建议的方案是什么

<img width="450" alt="image" src="https://user-images.githubusercontent.com/3871365/180486147-2a285647-eed4-407e-9acb-e2c067599bf7.png">

蒙层可自定义，如 单文件上传是，点蒙层可以重新上传，不需要删除再上传

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
