### ISSUE TITLE
[Upload] 上传组件preview无法配置属性，大图会溢出

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1283]
### 这个功能解决了什么问题

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/3871365/180487053-6cb989ff-1304-453b-a1e4-31ee93533d92.png">

上传组件preview增加配置属性，解决高度太大的图会出现滚动，体验不好
preview 增加跳转链接的配置，方便打开图片链接
preview slot 可自定义，开发者自行实现 Dialog 组件。

### 你建议的方案是什么

期望可自定义preview 属性。如宽度，高度。跳转链接
preview  slot  化，开发者可二次开发程度更高

**Comment by pengYYYYY** [comment]
可以先用 `css` 处理一下

**Comment by pengYYYYY** [comment]
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/35833812/182315104-f67c7145-c3f3-47f8-8e38-3f7799b29bc7.png">

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
