### ISSUE TITLE
[Menu] 横向菜单栏子类过多，样式错乱问题

### ISSUE THREAD

**Issue by zldqpm** [Tencent/tdesign-vue-next#1285]
菜单栏过多，样式错乱问题 
![image](https://user-images.githubusercontent.com/41427383/180589828-7ac90eae-19a4-4911-82b8-ac5945b11c3b.png)
建议改成这个样式
![image](https://user-images.githubusercontent.com/41427383/180589860-2232467b-cdfd-4a7f-b77d-9a6b1539f193.png)

**Comment by pengYYYYY** [comment]
[ardor-zhang](https://github.com/ardor-zhang) 处理中

**Comment by LeeJim** [comment]
这个 issue 应该要依赖设计师跟进
