### ISSUE TITLE
[Tabs] 增加按钮希望可以自定义内容

### ISSUE THREAD

**Issue by xuyingping10001** [Tencent/tdesign-vue-next#1288]
### 这个功能解决了什么问题

1

### 你建议的方案是什么

tabs addable ='tue'，增加选项卡时，增加按钮希望可以自定义内容（即可以支持 slot/function）

**Comment by pengYYYYY** [comment]
会在这边统一增加 https://github.com/Tencent/tdesign-vue-next/issues/1403

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
