### ISSUE TITLE
[InputNumber] 设置了min时还能通过按钮点到小于min的值

### ISSUE THREAD

**Issue by Charles-1999** [Tencent/tdesign-vue-next#1291]
### 重现链接
https://stackblitz.com/edit/angular-n2ugyz?file=src%2Fdemo.vue
<img width="146" alt="image" src="https://user-images.githubusercontent.com/60194808/180697011-f7eaadfd-9cb2-4b7a-9ce1-3f780cb3afb7.png">

### 重现步骤
给 t-input-number 设置 min = 0，然后不输入任何值，直接点击"-"号按钮。

### 期望结果
t-input-number的值变成min的值，或者按钮被禁用。

### 实际结果
t-input-number的值变成-1，小于min的值。

| Environment | Info |
|---|---|
| 相关版本 | 0.18.0 |
| 框架版本 / 基础库版本 | Vue(3.2.25) |
| 系统、浏览器 | MacOS\Chrome |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
0.18.1已修复
