### ISSUE TITLE
[package.json] 在package.json增加exports项，原生支持node的esm功能

### ISSUE THREAD

**Issue by sklme** [Tencent/tdesign-vue-next#1295]
### 这个功能解决了什么问题

因为node是不支持module项的（这个只是打包工具的事实约定）。
增加exports field，可以原生支持node的esm功能，让组件库在一些情况下更加方便使用，比如基于esm的测试。

更多信息：
https://github.com/vitest-dev/vitest/issues/1713

### 你建议的方案是什么

在package.json增加exports

**Comment by pengYYYYY** [comment]
收到，有兴趣的话，可以提PR喔

**Comment by sklme** [comment]
> 

这个可能得由你们来添加比较好。
因为这个设计到编译产物和入口的限制，而且我看到你们在`unplugin-vue-plugin`那边有增加一个resolver，有变化的话可能导致这个resolver不可用。

我建议在一个minor转为支持标准的esm。

**Comment by sklme** [comment]
> 收到，有兴趣的话，可以提PR喔

这个可能得由你们来添加比较好。
因为这个设计到编译产物和入口的限制，而且我看到你们在unplugin-vue-plugin那边有增加一个resolver，有变化的话可能导致这个resolver不可用。

我建议在一个minor转为支持标准的esm。

**Comment by sklme** [comment]
我现在自己folk过来解决一下，如果修改发现可以不是破坏性的，我会提交一个pr
