### ISSUE TITLE
[Table] 视图不响应已存在的单条数据的更新，以及 columns 类型错误

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#1297]
### tdesign-vue-next 版本

最新版

### 重现链接

https://gitee.com/crazymuyang/tdesign-enhanced-table-columns-type-error

### 重现步骤

```html
<template>
  <div style="width: 600px">
    <t-enhanced-table
      ref="table"
      row-key="id"
      :data="list"
      :columns="columns"
      :tree="{ childrenKey: 'children', indent: 50 }"
    />

    <Button @click="handleDataUpdate">Update Table Data</Button>
    <hr>
    <Table
      row-key="id"
      :data="list"
      :columns="columns"
    />
  </div>
</template>
<script setup lang="tsx">
import { EnhancedTable as TEnhancedTable, Button, Table } from 'tdesign-vue-next';
import { ref } from 'vue'
const list = ref([
  { id: 0, title: 'test1', children: [ { id: 3, title: 'cTtile3'}] },
  { id: 2, title: 'test2' },
])
const columns = [
  { colKey: 'title', title: 'Title'},
  { colKey: 'operation', title: 'Operation', align: 'right', cell: (h, {row}) => {
    return <span> do sth </span>
  }}
]
const handleDataUpdate =() => {
  list.value[1].title = 'test2222'
}
</script>
```

Table 可正常响应数据更新，EnhancedTable 不响应
![image](https://user-images.githubusercontent.com/28809916/180950407-53c1abb0-f219-45f2-a0bb-204c4f4f9bc4.png)

vscode，使用 Volar 插件，且在 SFC 中手动引入 td 组件时（Table 组件有相同的问题）
![image](https://user-images.githubusercontent.com/28809916/180946472-0cc8dcd2-6ce9-47c0-9fd4-344358b956c0.png)

**Comment by chaishi** [comment]
> 视图不响应已存在的单条数据的更新

`list.value[1].title = 'test2222'`

请参考官网更新单条数据的方式，而非直接根据经验或者感觉直接对数据对象赋值

即使是早期的 Vue2，这样直接改对象的方式，也无法更新视图

**Comment by Crazymuyang** [comment]
即使是完全覆盖原数据也不响应数据更新


不清楚你说的官网更新方式是什么，只看到了18.1有新增的resetData ，但文档里没有找到



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sheepluo ***@***.***&gt;
发送时间: 2022年7月26日 18:20
收件人: Tencent/tdesign-vue-next ***@***.***&gt;
抄送: Ender-x ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [Tencent/tdesign-vue-next] [Table] 视图不响应已存在的单条数据的更新，以及 columns 类型错误 (Issue #1297)

**Comment by chaishi** [comment]
> columns 类型错误

请给自己定义的 `columns` 加上 TS 类型定义，定义 Object 的方式不是 `const obj = { c: 1, d:2 }`，而是 `const obj: ObjectType = { c: 1, d: 2 }`
