### ISSUE TITLE
[form] 下拉框blur效验 第一次选中会显示错误信息。第二次才消失

### ISSUE THREAD

**Issue by xxxlj** [Tencent/tdesign-vue-next#1298]
### tdesign-vue-next 版本

0.16.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/form#%E4%B8%8D%E5%90%8C%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99%E7%9A%84%E8%A1%A8%E5%8D%95

**Comment by pengYYYYY** [comment]
@k1nz 处理中

**Comment by pengYYYYY** [comment]
0.18.2已修复

**Comment by k1nz** [comment]
这个问题和 input 的 blur 行为有关，当你鼠标指向 select 下拉框并且鼠标按下（mousedown）时，此时会触发了 input 的 blur 事件且 select 是没有选中值的，这就是为什么第一次选中会显示错误信息。

![2](https://user-images.githubusercontent.com/67723917/182895186-d2bd05c3-e61a-428b-8b1a-5e50810c2f70.gif)

如果需要 select 在选中值清除错误信息的话，要加多一条 trigger: 'change' 的校验规则。
![image](https://user-images.githubusercontent.com/67723917/182891222-e0dcc8ec-5102-4de5-bea0-9a7fc1dad891.png)
