### ISSUE TITLE
[Improve][icon] 请问icon的name支不支持动态设置

### ISSUE THREAD

**Issue by wzs28150** [Tencent/tdesign-vue-next#130]
## tdesign-vue-next

You will open an feature issue at tdesign-vue-next

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
我要实现一个图标选择的功能，我选择了 select 与 icon的搭配
![image](https://user-images.githubusercontent.com/21290257/147869793-c84232cf-0cbc-4965-a275-6108a1c87f5b.png)
然后，在select的左侧图标插槽中显示选中的图标预览样式 ,在select右边的框中显示图标的name
但是我发现我切换之后如果是下面这样写的并不随着切换
```
<t-icon :name="selectedIcon" size="18px" />
```
尝试了好多最后我采取了 引入https://tdesign.gtimg.com/icon/web/index.css
然后这样调用实现的
```
<i :class="`t-icon t-icon-${selectedIcon}`"></i>
```
不知道icon组件是否支持 还是我实现的有问题
**Describe alternatives you've considered**

**Additional context**

**Comment by pengYYYYY** [comment]
哈喽，这个问题是一个bug，随后会修复 https://github.com/Tencent/tdesign-vue-next/issues/41

**Comment by wzs28150** [comment]
感谢 希望越来越好~

**Comment by uyarn** [comment]
已修复 但由于此前锁住了版本，如果直接使用`t-icon`的方式需要等待下个vue-next的版本发布；


如果着急 可以直接`npm install tdesign-icons-vue-next@0.0.5`；

`import { Icon } from 'tdesign-icons-vue-next';`

把使用 `t-icon` 的换成 `icon` 即可
