### ISSUE TITLE
[Select] 选择框组件选中多个选项后，多占一空行

### ISSUE THREAD

**Issue by fenbitou** [Tencent/tdesign-vue-next#1306]
### tdesign-vue-next 版本

0.18.1

### 重现步骤

<img width="588" alt="image" src="https://user-images.githubusercontent.com/15060047/181466006-961cccc8-86be-419c-84e0-66375a4a519d.png">
初始化选择框后，默认选中其中几个选项，偶现多占一空行。刷新后消失。

**Comment by pengYYYYY** [comment]
已经修复此问题，升级到新版本
