### ISSUE TITLE
[Table] 【没有示例代码，看不懂问题，无法处理】表格使用合并功能的同时使用表格合并收起功能会导致表格多一行

### ISSUE THREAD

**Issue by kkk48ku** [Tencent/tdesign-vue-next#1313]
### tdesign-vue-next 版本

0.18.0

### 重现步骤

表格展开时会在表格新增一行，旧的合并逻辑没办法适配新增一行后的表格数据就会打乱表格合并的样式，有没有办法在表格展开收起后改变rowspanAndColspan方法

### 期望结果

表格展开收起同步改变rowspanAndColspan方法或者改变合并的行数

**Comment by litt1e-p** [comment]
@kkk48ku try call `refreshTable()` after expand toggle or in nextTick callback

**Comment by chaishi** [comment]
辛苦提供一下可以复现问题的代码，方便我们尽快排查问题。

一般会优先处理提供示例代码的 issue

**Comment by chaishi** [comment]
时间太长，版本号太低，又没有回复，issue 关闭
