### ISSUE TITLE
[Popup] content为纯英文时无法自动换行

### ISSUE THREAD

**Issue by renzhe200** [Tencent/tdesign-vue-next#1318]
### tdesign-vue-next 版本

0.18.1

### 重现链接

https://stackblitz.com/edit/angular-tfc3y3?file=src/demo.vue

### 重现步骤

<template>
  <div>
      <t-popup
        content="test1,test2,test3,test4,test1,test2,test3,test4,test1,test2,test3,test4"
        :overlay-style="{ maxWidth: '250px' }"
        placement="bottom"
        destroy-on-close
      >
        <t-button variant="outline">浮层最大宽度,英文显示</t-button>
      </t-popup>
  </div>
</template>

### 期望结果

无论中英文内容都可以正常换行

### 实际结果

设定 :overlay-style="{ maxWidth: '250px' }"
1.中文内容可正常换行显示
![image](https://user-images.githubusercontent.com/66165407/182028780-68e4457e-6c2d-4430-a5c1-39e5a48f13c3.png)

2.纯英文内容无法正常换行
![image](https://user-images.githubusercontent.com/66165407/182028679-ed6e25f8-9687-4719-b995-8ae799124e8e.png)

**Comment by pengYYYYY** [comment]
0.18.2已修复
