### ISSUE TITLE
[Table] 希望增加一个配置：当列数据为空时显示某个值

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#1320]
### 这个功能解决了什么问题

![18574c318f163775441deaca022a4ff](https://user-images.githubusercontent.com/19170277/182063830-d5e04fc2-65ee-4f41-b065-2c44129495fc.jpg)
当列数据为空时显示一个自定义字符串

### 你建议的方案是什么

新增一个全局配置项,dataEmpty

**Comment by timi137137** [comment]
可行，认领

**Comment by timi137137** [comment]
done #1348

**Comment by chaishi** [comment]
正要说我来处理，@timi 已经处理了，

下次设计到 API 变更（新增、删除、调整等），辛苦提前告知一下我们哈，避免返工。

API 一般需要评审的

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/1254/commits/21656ac763f7af3d0a741dbca9eac1af4f71a615
https://github.com/Tencent/tdesign-vue/pull/1254

**Comment by pengYYYYY** [comment]
0.19.1 已修复
