### ISSUE TITLE
[table] 文档 `validateRowDate`拼写未改过来

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#1321]
### tdesign-vue-next 版本

0.18.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

可编辑表格的文档说明未跟随版本迭代修改，`validateRowDate`应改为`validateRowData`

![image](https://user-images.githubusercontent.com/20508822/182090667-3d74dfcd-9ea3-4b6a-ac09-2923dd3f0f9b.png)

### 期望结果

validateRowData

### 实际结果

validateRowDate

### 框架版本

Vue(3.2.37)

### 浏览器版本

Chrome(103.0.5060.114)

### 系统版本

MacOS(12.4)

### Node版本

14.19.2

**Comment by chaishi** [comment]
感谢提醒，我看下

**Comment by wandoupeas** [comment]
> 

对的 我说的就是文档哈

**Comment by pengYYYYY** [comment]
0.18.2已修复
