### ISSUE TITLE
[Upload]  upload组件 draggable 不支持 multiple

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1326]
### tdesign-vue-next 版本

0.18.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/upload

### 重现步骤

upload组件 draggable 不支持 multiple

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/3871365/182288001-68858e3e-9056-4126-bc2a-c4a7664dae26.png">

一打开 multiple 组件被隐藏了
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/3871365/182287911-7e7d6e08-4f59-4521-97bc-8e7e3d268935.png">

### 期望结果

upload 同组件 draggable

**Comment by pengYYYYY** [comment]
多选的话请用 `theme="file-flow"`，这边是 `live demo` 的问题

**Comment by pengYYYYY** [comment]
0.18.2已修复
