### ISSUE TITLE
[Upload] upload组件开启 draggable后配置 theme 无效

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1327]
### tdesign-vue-next 版本

0.18.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/upload

### 重现步骤

<img width="1185" alt="image" src="https://user-images.githubusercontent.com/3871365/182288812-39720493-5039-45ba-9ba2-598d71144905.png">

### 期望结果

draggable 只是行为，跟样式无关，theme 才是决定样式。
theme="image"  表现形式应该一致，只是多了拖拽上传的功能。
<img width="348" alt="image" src="https://user-images.githubusercontent.com/3871365/182288862-72959a0d-972f-4148-933d-9db2a0a0cdf2.png">

draggable 开启组件是否支持拖拽， 增加 theme="draggable"  的样式来兼容现用

**Comment by pengYYYYY** [comment]
这个组件比较复杂，需要多种情况做组合才，比如开启了 `file-flow` 就必须开启 `mutiple` 才可以展示文件列表，使用时需要正确配置参数。

**Comment by pengYYYYY** [comment]
开启 `draggable` 图片上传的样式在 `demo` 里面有
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/35833812/182311666-b01f14f7-29c1-4c18-9a85-c2e6313613f2.png">

**Comment by pengYYYYY** [comment]
这个组件先以 `demo` 先以展示的使用为主，`live demo` 这边后续我们做一些修复
