### ISSUE TITLE
[t-tab-panel]  支持配置宽度 ，以及超出显示省略号 ellipsis  

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1328]
### 这个功能解决了什么问题

t-tab-panel 支持自定义配置宽度 ，以及超出显示省略号 ellipsis
 
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/3871365/182289363-4793eedf-4c2f-4542-ad97-f19feaa3b260.png">

当选项卡文字很长表现很差， slot 写 label 有点费劲，期望增强下
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/3871365/182289634-714d8eae-446a-41e7-9614-fa8f2d68942c.png">

### 你建议的方案是什么

<img width="721" alt="image" src="https://user-images.githubusercontent.com/3871365/182289947-f1e326d3-fd31-469e-9005-5a3d6c7784af.png">

t-tab-panel 宽度表现一致 ，超出显示省略号

**Comment by pengYYYYY** [comment]
这个可以css处理一下，覆盖一下样式
