### ISSUE TITLE
[Upload] 组件支持右键显示dropdown菜单

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1330]
### 这个功能解决了什么问题

多文件上传时经常需要调整焦点图的位置，如左移一位或右移一位，
高级的用法还有自定义裁剪组件，期望能增加右键赋予开发更多功能集成。

### 你建议的方案是什么

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/3871365/182298480-4512b738-5cfe-4550-a5ae-c88b4dfb9213.png">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/3871365/182298873-9ca54faf-f4b7-464a-9e21-553e0d517bbd.png">

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。
