### ISSUE TITLE
[Input/Textarea] 组件增加可以主动调用的focus、blur等常用方法

### ISSUE THREAD

**Issue by latte-z** [Tencent/tdesign-vue-next#1338]
### 这个功能解决了什么问题

例子：https://stackblitz.com/edit/angular-meueu9?file=src%2Fdemo.vue

当前的目标是实现一个点击单行input，弹出popup形式的多行textarea的组件，展开状态下textarea会完全覆盖掉input的显示。
textarea的autofocus会因为input而冲突导致失效，想利用popup的visible-change事件，主动触发textarea的focus，但是目前没有暴露出来。

参考其他家的组件库，例如element就有默认暴露的三个方法：
![image](https://user-images.githubusercontent.com/7680235/182575580-d60f0e8a-492c-4426-bd56-793ef6492314.png)

### 你建议的方案是什么

增加相关可以主动调用的事件方法。

另外感觉例子中这种形式的input可以开发成一个通用的组件来使用。

**Comment by timi137137** [comment]
@latte-z 你有试过使用吗，我看代码是有导出这两个函数的

**Comment by timi137137** [comment]
![image](https://user-images.githubusercontent.com/36812439/182830807-3d05819c-c608-48fa-9475-0b1bd82b0b40.png)

**Comment by latte-z** [comment]
> ![image](https://user-images.githubusercontent.com/36812439/182830807-3d05819c-c608-48fa-9475-0b1bd82b0b40.png)

你这个截图是input的？看了一下Textarea应该是没有expose的，昨天使用的时候通过ref调用是undefined。

**Comment by timi137137** [comment]
> > ![image](https://user-images.githubusercontent.com/36812439/182830807-3d05819c-c608-48fa-9475-0b1bd82b0b40.png)
> 
> 你这个截图是input的？看了一下Textarea应该是没有expose的，昨天使用的时候通过ref调用是undefined。

yes，你试试input的，如果能用我给你加个textarea的

**Comment by latte-z** [comment]
> 

试了下input expose focus确实能用，不过我自己本身的这个例子可能有什么其他用法冲突，导致input的focus失效了，我自己先来解决一下。辛苦加个textarea的。

**Comment by timi137137** [comment]
> > 
> 
> 试了下input expose focus确实能用，不过我自己本身的这个例子可能有什么其他用法冲突，导致input的focus失效了，我自己先来解决一下。辛苦加个textarea的。

ok问题不大

**Comment by timi137137** [comment]
done
- #1349

ps: 顺便加上了文档

**Comment by pengYYYYY** [comment]
0.19.1 已修复
