### ISSUE TITLE
[Textarea] autosize填{ minRows: 5 } ts校验报错

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1340]
### tdesign-vue-next 版本

0.18.2

### 重现步骤
vscode编辑
`
<t-textarea  :autosize="{ minRows: 5 }"  />
`

### 期望结果

无告警

### 实际结果

(property) autosize?: boolean
不能将类型“{ minRows: number; }”分配给类型“boolean”。ts(2322)

### Node版本

v16.16.0

**Comment by pengYYYYY** [comment]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/35833812/183579555-3a7cf444-7284-40ca-9b08-0995b5383fee.png">
 无报错

**Comment by waney** [comment]
![image](https://user-images.githubusercontent.com/69211/212630398-e75463da-f563-422d-a9ba-61959ae50ebc.png)
