### ISSUE TITLE
[Dialog] 对话框全屏

### ISSUE THREAD

**Issue by gotounix** [Tencent/tdesign-vue-next#1342]
### 这个功能解决了什么问题

对话框全屏。

### 你建议的方案是什么

类似：https://arco.design/vue/component/modal#fullscreen

**Comment by ardor-zhang** [comment]
@pengYYYYY 不知道有没有属性名的规范，如果没有，看是否直接使用 fullscreen 就可以，可以的话我可以处理这个问题

**Comment by pengYYYYY** [comment]
由于需求类issue处理优先级会低于bug类issue，导致会被被遗忘，所以需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close。

**Comment by pengYYYYY** [comment]
> @pengYYYYY 不知道有没有属性名的规范，如果没有，看是否直接使用 fullscreen 就可以，可以的话我可以处理这个问题

新组件进度统一规划

**Comment by huoyuhao** [comment]
领取任务9月13日前完成。
