### ISSUE TITLE
[GlobalConfigProvider] 希望`GlobalConfigProvider.TableConfig`增加`bordered`、`stripe`等设置

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#1343]
### 这个功能解决了什么问题

希望`GlobalConfigProvider.TableConfig`增加`bordered`、`stripe`等简单的全局通用设置，这样可以统一配置全局的表格风格，精简表格`props`使用时重复的选项

### 你建议的方案是什么

可否考虑将`table`的`props`部分样式相关的选项加入`GlobalConfigProvider.TableConfig`，例如边框、斑马纹、表头吸顶等选项

**Comment by pengYYYYY** [comment]
需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close
