### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1344]
### tdesign-vue-next 版本

0.19.0

### 重现步骤

![image](https://user-images.githubusercontent.com/3871365/182785247-345e7269-4846-455f-bd68-c2c2cba8abbd.png)

![image](https://user-images.githubusercontent.com/3871365/182785301-007b6043-f59a-45c9-879a-c73872a468f3.png)

popupElem.value 在路由跳转后不存在了， 执行 popupElem.value.handleClose() 会抛异常

### 期望结果

 popupElem.value?.handleClose()

**Comment by RayJason** [comment]
请问这个具体是在什么场景出现的？可以看看调用代码吗？我不知道怎么复现跳转路由后执行```popupElem.value.handleClose()```

**Comment by pengYYYYY** [comment]
0.19.1 已修复
