### ISSUE TITLE
[Dialog] confirm-btn设置null，编译器给出提示：不能将类型“null”分配给类型“string”。ts(2322)

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1347]
### tdesign-vue-next 版本

0.18.2

### 重现步骤

vscode编辑：
`<t-dialog :confirm-btn="null" />`

### 期望结果

不提示错误

### 实际结果

(property) confirm-btn: null
不能将类型“null”分配给类型“string”。ts(2322)

**Comment by chaishi** [comment]
收到，我们处理一下，加一下数据类型

**Comment by pengYYYYY** [comment]
0.19.1 已修复
