### ISSUE TITLE
[Pagination] 分页跳转页面控件希望增加change事件，当前仅有blur事件

### ISSUE THREAD

**Issue by Kythuen** [Tencent/tdesign-vue-next#1352]
### 这个功能解决了什么问题

https://tdesign.tencent.com/vue-next/components/pagination?tab=demo#%E5%B8%A6%E5%BF%AB%E9%80%9F%E8%B7%B3%E8%BD%AC%E7%9A%84%E5%88%86%E9%A1%B5

show-jumper： 现在跳转页面，只有失焦后才会触发跳转 

### 你建议的方案是什么

希望增加change事件触发跳转

**Comment by ardor-zhang** [comment]
@Kythuen change 吗，不知道你是不是指 input 触发

**Comment by Kythuen** [comment]
是的，就是指跳转输入框的触发，现在只有失焦才会触发页码变化，但是一般操作都是输入完回车就触发。能否做一定的调整，或者由选项控制。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-vue-next"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月8日(星期一) 下午3:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue-next] [Pagination] 分页跳转页面控件希望增加change事件，当前仅有blur事件 (Issue #1352)





 
@Kythuen change 吗，不知道你是不是指 input 触发

**Comment by pengYYYYY** [comment]
已经增加了onEnter事件触发
