### ISSUE TITLE
[组件性能探讨] 大量数据渲染卡顿间接导致全局卡顿

### ISSUE THREAD

**Issue by latte-z** [Tencent/tdesign-vue-next#1353]
### tdesign-vue-next 版本

0.19.0

### 重现步骤

目前有多个大量渲染的场景，包括但不限于如下：

1. Select 在启用 virtual scroll 特性的前提下，option 几百到上万条不等，且开启了 filter 特性。
2. Tree 包含上千的节点，且开启了 filter 特性。

表现：在组件初始化，通过请求获取到 option 给到完整数据后（最长的请求也不会超过100毫秒），首次 focus 展开（tree 是节点展开）会有明显的卡顿感，同时会拖慢整个页面的响应。如果启用了过滤，会在输入的过程中感受到更为明显的响应中断。第二次触发展开后性能会稍好，但是同样也有肉眼可见的延迟。同时其他所有的页面元素都会受到影响。

目前手头很多维护老项目基于vue2+element开发，之前select哪怕不使用virtual scroll也不太会出现这样的情况，tree甚至比select的性能更好，filter的响应速度也是飞快。

由于主职后端不是专业的前端，无法推测出是vue3新的底层逻辑问题，还是本身组件部分逻辑的实现问题。

### 期望结果

解决较为普遍的性能问题

### Node版本

18.0.0

**Comment by chaishi** [comment]
收到，我们审查下代码

**Comment by chaishi** [comment]
方便提供一下示例代码 和 脱敏处理的数据源吗？（方便我们看看是否有别的内置组件影响）

**Comment by latte-z** [comment]
> 

我内网联系一下你吧

**Comment by pengYYYYY** [comment]
select 的 virtual scroll 还没推上去

**Comment by latte-z** [comment]
> select 的 virtual scroll 还没推上去

我跟sheepluo沟通的过程中重新run了一下项目，发现select卡顿的问题没有了（会有不易感知的一点点卡），不确定是不是vite热更新的问题，估计等virtual scroll更新应该就能解决了。tree的问题也单独反馈了，等待后续整顿。

**Comment by taomas** [comment]
@pengYYYYY 请问select组件的virtual scroll要那个版本才能更新上去呢
