### ISSUE TITLE
[咨询] 怎么替换“浏览器窗口上的logo”

### ISSUE THREAD

**Issue by jamesz2011** [Tencent/tdesign-vue-next#1355]
### 这个功能解决了什么问题

咨询怎么替换“浏览器窗口上的logo”
![image](https://user-images.githubusercontent.com/16397200/183277865-04f315c6-f2a6-4daf-a6dd-4071d7e078f8.png)

### 你建议的方案是什么

咨询怎么替换“浏览器窗口上的logo”
![image](https://user-images.githubusercontent.com/16397200/183277865-04f315c6-f2a6-4daf-a6dd-4071d7e078f8.png)

**Comment by pengYYYYY** [comment]
https://www.cnblogs.com/stooges/p/15196675.html

**Comment by jamesz2011** [comment]
@pengYYYYY 感谢指导
![image](https://user-images.githubusercontent.com/16397200/183414030-a1e0faa2-ec7c-4e6f-84b1-bf6d88b65740.png)
