### ISSUE TITLE
[tdesign-vue-next] core.js 版本警告

### ISSUE THREAD

**Issue by 2992362310** [Tencent/tdesign-vue-next#1360]
### tdesign-vue-next 版本

0.19.0

### 重现步骤

<img width="892" alt="image" src="https://user-images.githubusercontent.com/43593232/183369824-3c9703bf-af30-495d-a4f8-6e68e0e21395.png">

### 期望结果

tdesign 是否可升级 core.js 依赖版本

### 实际结果

目前依赖 core-js@1.2.7，会有警告

**Comment by pengYYYYY** [comment]
tdesign没有直接依赖core.js, 这边的 core.js 是其他包依赖的，框架每隔一段时间会统一升级依赖。

**Comment by 2992362310** [comment]
pnpm why core-js

**Comment by 2992362310** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/43593232/183613987-61ae0360-76c3-4245-9c57-defddbca0adc.png">
