### ISSUE TITLE
[穿梭框] 结合tree组件时，如果如果子节点children 为空数组时，不会展示该条父节点内容

### ISSUE THREAD

**Issue by xyunyun** [Tencent/tdesign-vue-next#1366]
### tdesign-vue-next 版本

1.9.0

### 重现步骤

当我用穿梭框结合tree组件使用的时候, 假设数据结构是这样
 `const items = [
  {
    value: '1',
    label: '1',
    children: [
      {
        value: '1.1',
        label: '1.1',
      },
    ],
  },
  {
    value: '2',
    label: '2',
    children: [],
  },
];`
value：2 这条数据的子节点是个空数组，并没有展示当前数据的父节点，我觉得应该是需要展示的

**Comment by luoyu-233** [comment]
+1

**Comment by pengYYYYY** [comment]
处理中

**Comment by pengYYYYY** [comment]
0.20.2 已修复
