### ISSUE TITLE
[table] 可编辑的表格中，如果校验项不在第一项，则没有校验

### ISSUE THREAD

**Issue by Apollo-zz** [Tencent/tdesign-vue-next#1368]
### tdesign-vue-next 版本

0.19.0

### 重现链接

https://stackblitz.com/edit/angular-i35ctq?file=src%2Fdemo.vue

### 重现步骤

官方示例是将需要校验的 input 放在第一项，修改时会校验；
将官方示例中需要校验的 input 改到第二项，修改时不会校验。

### 期望结果

无论需要校验的项位置在哪里，修改或保存时会校验。

### 实际结果

将官方示例中需要校验的 input 改到第二项，修改时不会校验。

### 框架版本

Vue(3.2.25)

### 浏览器版本

Chrome( 103.0.5060.114)

### 系统版本

MacOs Monterey(12.4)

### Node版本

14.17.0

**Comment by chaishi** [comment]
issue 重复，请关注 https://github.com/Tencent/tdesign-vue-next/issues/1339

即将发布
