### ISSUE TITLE
按说明使用按需导入后，官网定制的样式，使用无效

### ISSUE THREAD

**Issue by qsk617** [Tencent/tdesign-vue-next#1372]
### tdesign-vue-next 版本

19

### 重现步骤

import AutoImport from 'unplugin-auto-import/vite';
import Components from 'unplugin-vue-components/vite';
import { TDesignResolver, ElementPlusResolver } from 'unplugin-vue-components/resolvers';
//进行按需导入设置
。。。
。。。
// 下方使用定制样式表，无效。使用ElementPlus测试，配置没问题的。td会有不同吗？？
      scss: {
        additionalData: `@use "./src/theme/global.scss" as *;`, 
      },

### 期望结果

td定制的样式生效

### 实际结果

不生效。

### 补充说明

thks~

**Comment by uyarn** [comment]
// 下方使用定制样式表，无效。使用ElementPlus测试，配置没问题的。td会有不同吗？？
scss: {
additionalData: @use "./src/theme/global.scss" as *;,
},

请问是将生成器生成的token放在`global.scss `中  然后不生效吗
