### ISSUE TITLE
[Dialog] 对话框 组件增加回车确认事件

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1376]
### 这个功能解决了什么问题

<img width="521" alt="image" src="https://user-images.githubusercontent.com/3871365/183820816-a0711a9e-4775-441e-bd1b-a3205f93cada.png">

同关闭操作，弹窗支持回车确认。方便在点出弹窗后，通过键盘快速进行操作。

### 你建议的方案是什么

组件

:confirmOnEnterKeydown="true"
:on-enter-keydown="onConfirm"

函数：
DialogPlugin.confirm({
     confirmOnEnterKeydown: true,
    onEnterKeydown : onConfirm
})

**Comment by pengYYYYY** [comment]
支持enter键框触发confirm方法，不会增加API

**Comment by huoyuhao** [comment]
OK 我来处理一下
