### ISSUE TITLE
[DatePicker] 样式问题：不加allowInput属性，输入框就没有默认的白色底色

### ISSUE THREAD

**Issue by Apollo-zz** [Tencent/tdesign-vue-next#1378]
### tdesign-vue-next 版本

0.19.1

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Findex.css,src%2Fdemo.vue

**Comment by pengYYYYY** [comment]
请提供更详细的issue描述

**Comment by pengYYYYY** [comment]
<img width="953" alt="image" src="https://user-images.githubusercontent.com/35833812/184585902-e96cd904-8a15-4b4c-9165-1ee71b55fd68.png">

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/35833812/184585919-f1f9f1d6-e5fa-43a6-af27-67ce26aca6e0.png">

没有问题喔

**Comment by Apollo-zz** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/22813180/185583874-e2c4bd11-d750-411b-bab4-753797b5ecaf.png">
@pengYYYYY 没有allow-input属性的，才会有问题

**Comment by Apollo-zz** [comment]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/22813180/185584933-9e91ba94-330f-4149-b52e-3298714f6f87.png">
@pengYYYYY 级联选择器也有类似的表现
