### ISSUE TITLE
[TDialog] 对话框下部的padding过大，导致footer不显示的情况下，界面显示效果较差

### ISSUE THREAD

**Issue by chnykn** [Tencent/tdesign-vue-next#1380]
### tdesign-vue-next 版本

0.19.1

### 重现步骤

 对话框下部的padding过大，导致footer不显示的情况下，界面显示效果较差。
其实，footer显示情况，如果只是提示几行文本，看起来还是可以的；但是，如果显示内容较多，尤其是footer不显示，采用body中的下部按钮的情况下，界面下部的空白区域太高。如下图所示：
![1](https://user-images.githubusercontent.com/4152089/183852331-29221212-659e-4863-ae69-20da3211ca19.png)

### 期望结果

我通过修改style、className两个属性的内容，均没有达到缩小下部空白区域的效果。
建议：默认窗体下部的空白区域（padding）能否小一些，比如8px。如果用户想要增加的话，完全可以在自己的body内容部分，自行搞定。

**Comment by pengYYYYY** [comment]
用css覆盖一下就好了

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
