### ISSUE TITLE
[table] 表格组件的编辑功能在编辑时间选择器的时候不能切换年和月

### ISSUE THREAD

**Issue by xyunyun** [Tencent/tdesign-vue-next#1384]
### tdesign-vue-next 版本

1.8.0

### 重现步骤

当我在表格当中编辑日期时用到了时间选择器，然而当我进行月份和年份切换的时候发现点击完之后时间选择器的弹出层竟然消失了，会不会是切换的时候触发了退出编辑的事件，

### 期望结果

当切换年份和月份的时候并不应该退出编辑事件，应该只当我选中时间后才会触发退出编辑事件

**Comment by chaishi** [comment]
我来

**Comment by chaishi** [comment]
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/1392

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/1275

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
