### ISSUE TITLE
[Cascader] 无法绑定style

### ISSUE THREAD

**Issue by hxywuya** [Tencent/tdesign-vue-next#1385]
### tdesign-vue-next 版本

0.19.1

### 重现链接

https://stackblitz.com/edit/angular-gyu9ev?file=package.json

### 重现步骤

添加  `:style="{ width: '180px' }"` 属性

### 期望结果

能绑定上style

### 实际结果

未绑定上style

### 框架版本

3.2.37

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
