### ISSUE TITLE
[Upload] size-limit 使用MB单位不能正常拦截

### ISSUE THREAD

**Issue by Apollo-zz** [Tencent/tdesign-vue-next#1386]
### tdesign-vue-next 版本

0.19.1

### 重现链接

https://stackblitz.com/run?file=package.json

### 重现步骤

官网示例，上传超过5M的文件，不会被拦截。
<img width="250" alt="image" src="https://user-images.githubusercontent.com/22813180/184060902-c766e6fc-c7fe-4d87-bd9f-00bcacc90842.png">

如果单位改成KB，拦截正常。MB则不会拦截。

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
