### ISSUE TITLE
[table] 可编辑表格可否增加一个参数`edit.editable`

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#1387]
### 这个功能解决了什么问题

可编辑表格，当前编辑的cell需要根据当前行的其他某些值来动态判断是否可编辑，`edit.props`只能控制控件的`props`，让类似`input`等组件`readonly`，无法根本上让其变为不可编辑或文本状态

### 你建议的方案是什么

可否提供一个`edit.editable`属性(`editable?: booelan | (params: BaseTableCellParams<T>) => boolean`)，用以动态判断当前cell是否可编辑

**Comment by chaishi** [comment]
可以，我看下

**Comment by chaishi** [comment]
如果将 API 添加在 edit.editable，那么需要每一列都设置一遍可编辑状态，十几列就是十几遍，不合适。

`editableRowKeys` 控制某一行是否显示为编辑
同理，新增 `editableCellRowKeys` 控制某一个单元格是否显示为编辑状态

**Comment by chaishi** [comment]
- `editableCellState` 表格全局属性，用于控制单元格是否允许编辑。返回值为 `true` 则表示可编辑；返回值为 `false` 则表示不可编辑，只读状态

**Comment by wandoupeas** [comment]
是新的api吗

**Comment by pengYYYYY** [comment]
0.20.2 已修复

**Comment by wandoupeas** [comment]
> 不需要每一列设置. `edit.editable`，直接使用下方属性全局设置即可。
> 
> * `editableCellState` 表格全局属性，用于控制单元格是否允许编辑。返回值为 `true` 则表示可编辑；返回值为 `false` 则表示不可编辑，只读状态

我有看到新的api(`editableCellState`)的用法，但是好像跟我描述的有点偏差。

本来我想达到的效果是在`columns.edit`属性内添加一个控制本列数据是否可编辑的属性，这个属性接受一个响应式的boolean对象或者是一个返回boolean类型的function，function的入参即为`PrimaryTableCellParams<T>`。

现在是在table的props内添加了一个类似的属性，这样目前遇到两个问题：
1. 文档中的返回值`true/false`貌似写反了，返回`false`现在表现为可以编辑，`true`不可编辑，这应该是个bug吧。

<img width="984" alt="image" src="https://user-images.githubusercontent.com/20508822/186130709-791741f4-80b5-4c0d-bdd7-6261017e84e9.png">

3. 当我需要根据行数据控制多列属性的编辑状态时，这样个api就显得不是那么方便了，我需要判断当前列的列名是什么，当row中的某个值为什么的时候，来动态返回编辑状态，例如如下代码，这样我觉得不是很方便，所以我还是建议可以在`columns.edit`中添加一个`editable`属性，这样编码时也可以再`columns`中更清晰的看到当前列的可编辑状态

![image](https://user-images.githubusercontent.com/20508822/186131704-671131ff-28cb-449a-ae1d-ae63cae3cf67.png)
