### ISSUE TITLE
[DatePicker] 无法只选择时分

### ISSUE THREAD

**Issue by hxywuya** [Tencent/tdesign-vue-next#1389]
### tdesign-vue-next 版本

0.19.1

### 重现链接

https://stackblitz.com/edit/angular-rybfup?file=src/demo.vue

### 期望结果

使用 format 或 time-picker-props 的 format 实现 时间部分只选择时分

### 实际结果

不论是format和 time-picker-props 的 format 均无用

**Comment by uyarn** [comment]
<img width="456" alt="image" src="https://user-images.githubusercontent.com/26377630/184073934-46cef306-c252-4bc9-98d6-1784997c1f34.png">
format

**Comment by uyarn** [comment]
https://stackblitz.com/edit/angular-rybfup-kouszy?file=src%2Fdemo.vue

**Comment by hxywuya** [comment]
我·········· 润了
