### ISSUE TITLE
t-date-picker 初始值与设置mode不符时浏览器卡死

### ISSUE THREAD

**Issue by dodu2014** [Tencent/tdesign-vue-next#1390]
### tdesign-vue-next 版本

0.19.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/date-picker#app

### 重现步骤

1. 在组件展示页面，在右侧配置中，设置mode为week
2. 左侧组件中随意选择一周，也即是给组件设置一个值
3. 右侧配置中，变更mode为date
4. 点击左侧组件时，浏览器卡死 😂

### 期望结果

实际应用中，很多时候 t-date-picker 组件都会有默认值，如果默认值格式与组件mode期望的值格式不符，点击组件的时候，就会卡死了，可能时在变更mode时，触发组件事件中，没有对现有值进行容错处理，希望改进

### 实际结果

希望改进

### 框架版本

Vue(3.2.0)

### 浏览器版本

edge(104.0.1293.47 )

### 系统版本

windows11

### Node版本

v14.18.2

**Comment by HQ-Lin** [comment]
这版本处理下
