### ISSUE TITLE
使用苹果平板table组件在滚动时，表格内容和表头不同步（Safari 浏览器）

### ISSUE THREAD

**Issue by qsk617** [Tencent/tdesign-vue-next#1393]
### tdesign-vue-next 版本

19

### 重现链接

https://tdesign.tencent.com/vue-next/components/table

### 重现步骤

官网例子

**Comment by chaishi** [comment]
只有一句话，只有一个官网地址，无法定位问题， 长时间未收到回复，issue 关闭

我这边看了下官网，没有看到标题中所提到的问题

**Comment by chaishi** [comment]
试了下 safari 有类似问题
