### ISSUE TITLE
table支持数据导出

### ISSUE THREAD

**Issue by Prc-PY** [Tencent/tdesign-vue-next#1394]
### 这个功能解决了什么问题

内部使用的应用，用户对源数据有一套自己的处理逻辑，可能需要将当前数据能以excel或csv等格式导出供用户使用

### 你建议的方案是什么

table里添加一个可导出的参数，参数可支持导出格式选择和导出当前筛选数据还是所有数据

**Comment by chaishi** [comment]
没有看明白 table 能做点什么，看上去都是表格外面的需求。

参数，筛选，都是外部数据，为何不是在外面做导出，里面好像什么也做不了，除了提供一个导出的按钮

**Comment by pengYYYYY** [comment]
导出应该是数据结合xlsx.js插件做的，和组件库无关。
