### ISSUE TITLE
[Pagination] 分页选择，Select 宽度不够导致信息显示不完整

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1395]
### tdesign-vue-next 版本

0.19.1

### 重现步骤

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/11605702/184274853-3bad647d-0628-421b-8a6f-df0adc860e8c.png">

**Comment by uyarn** [comment]
0.19.1的版本更新字体配置的影响 已经修复

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
