### ISSUE TITLE
[Transfer] 穿梭框支持 height 属性调整高度

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#1405]
### 这个功能解决了什么问题

Transfer 穿梭框 默认高度只有240， 加上搜索呈现的条目太少。

目前可用css处理，但不够优雅
  ::v-deep(.t-transfer__search .t-transfer__list) {
    height: 340px;
  }

### 你建议的方案是什么

期望可自定义高度
:height = 320

**Comment by pengYYYYY** [comment]
此类需求统一转移到，目前优先级可能不太高，暂时用css实现。https://github.com/Tencent/tdesign-vue-next/issues/848
