### ISSUE TITLE
t-dialog,页面初始化时，会触发on-confirm绑定的函数

### ISSUE THREAD

**Issue by daoYou666** [Tencent/tdesign-vue-next#1408]
### tdesign-vue-next 版本

0.19.1

### 重现步骤

<t-dialog
      v-model:visible="visible"
      :header="$t('placeholder.batch')"
      mode="modal"
      draggable
      :on-confirm="onExportData"
>
      
</t-dialog>
上面的代码，页面初始化时，会触发onExportData方法；
下面的写法不会，
<t-dialog
      v-model:visible="visible"
      :header="$t('placeholder.batch')"
      mode="modal"
      draggable
      :on-confirm="() => { onExportData() }"
>
      
</t-dialog>

### 系统版本

window11

### Node版本

16.15.0

**Comment by pengYYYYY** [comment]
https://tdesign.tencent.com/vue-next/components/dialog#%E7%A1%AE%E8%AE%A4%E7%B1%BB%E5%AF%B9%E8%AF%9D%E6%A1%86
