### ISSUE TITLE
Tree:tree组件在checkable（可选）开启时，无法触发onActive函数，无法收集高亮行信息

### ISSUE THREAD

**Issue by ChangJian2077** [Tencent/tdesign-vue-next#1409]
### 重现链接
https://stackblitz.com/edit/angular-ircimw-vukpsw?file=src/demo.vue

### 重现步骤
1.默认无checkable情况下可以进行高亮选中并执行onActive函数，并正常在控制台得到输；
2.开启可选后onActive函数不执行；
图片:
![without_checkable](https://user-images.githubusercontent.com/78943431/184498144-7b805d27-ceaa-4b77-b54e-74de4465f200.png)
![with_checkable](https://user-images.githubusercontent.com/78943431/184498175-f5e83f4c-fabf-4aaf-a9d3-c432106bf143.png)

### 期望结果
希望active的行为能与check独立

### 实际结果
开启可选后onActive函数不执行；

### 补充说明
不确定是否设计本身如此，目前用起来有些不舒服

| Environment | Info |
|---|---|
| 相关版本 | 0.19.1 |
| 框架版本 / 基础库版本 | Vue(3.2.13) |
| 系统、浏览器 | Chrome(104.0.5112.81) |
| Node版本 | 16.13.2 |

**Comment by zhangpaopao0609** [comment]
处理中

**Comment by pengYYYYY** [comment]
0.20.2 已修复
