### ISSUE TITLE
Tree: tree组件实例的setItem方法无效

### ISSUE THREAD

**Issue by ChangJian2077** [Tencent/tdesign-vue-next#1410]
### 重现链接
https://stackblitz.com/edit/angular-ircimw-l1fbic?file=src/demo.vue

### 重现步骤
例子根据官网示例：https://tdesign.tencent.com/vue-next/components/tree?tab=demo#%E5%B8%A6%E6%93%8D%E4%BD%9C%E5%8A%9F%E8%83%BD%E7%9A%84%E6%A0%91简化修改(关闭可选check)
1.在首个节点点击添加子节点
2.折叠收起首个节点
3.选中高亮首个节点
4.点击展开高亮节点
5.控制台输出打印该节点信息，但是节点无法展开

### 期望结果
希望能展开该节点

### 实际结果
节点无法展开，并且因为疑似代码bug源码中开放的三个实际可修改属性"expanded"、"actived"、"checked"均无法正确设置

![expand_bug](https://user-images.githubusercontent.com/78943431/184499359-8d56cc0a-a2c9-4b33-aa76-7976ef2e2b30.png)

### 补充说明
原因疑似setItem方法调用TreeNode实例setExpanded、setActived、setChecked方法时没有按照实例方法的参数要求进行传递(方法要求传递首个参数为boolean，第二个参数时配置)，实际传入第一个参数为修改的配置参数对象
```
// useExposeFunc.ts中方法
 const setItem = (value: TreeNodeValue, options: TreeNodeState) => {
    const node: TreeNode = treeStore.value.getNode(value);
    const spec = options;
    const keys = Object.keys(spec);
    if (node && spec) {
      ['expanded', 'actived', 'checked'].forEach((name) => {
        if (keys.includes(name)) {
          node[`set${upperFirst(name)}`](spec); //疑似此处调用参数传错？
        }
      });
    }
  };
```
```
//tree-node.js 类中方法实现  类似还有setActived和setChecked
// 设置节点展开状态
  public setExpanded(expanded: boolean, opts?: TypeSettingOptions): TreeNodeValue[] {
    const { tree } = this;
    const options = {
      directly: false,
      ...opts,
    };

    let map = tree.expandedMap;
    if (!options.directly) {
      map = new Map(tree.expandedMap);
    }
```

| Environment | Info |
|---|---|
| 相关版本 | 0.19.1 |
| 框架版本 / 基础库版本 | Vue(3.2.13) |
| 系统、浏览器 | Chrome(104.0.5112.81) |
| Node版本 | 16.13.2 |

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
