### ISSUE TITLE
Tree: tree组件希望能提供在删除已经懒加载得到节点后重新进行懒加载的功能

### ISSUE THREAD

**Issue by ChangJian2077** [Tencent/tdesign-vue-next#1411]
### 这个功能解决了什么问题
场景需求：
业务使用的树上可能存在很多个根节点，我之前使用过程中会自行维护一个缓存机制，当懒加载缓存满了之后会清除掉以前懒加载的节点数据，目前由于删除节点后expand状态无法通过setItem方法正确设置（已经提交issue），并且源码中当加载过之后children会被设置为数组，无法返回到true状态，我无法通过组件目前功能实现该业务场景。

### 你建议的方案是什么？
1.希望暴露更多的TreeNode实例属性给setItem方法进行设置，比如children；
2.或者缓存构建树的初始数据，当子节点被删除后重新折叠并可再次进行加载

**Comment by pengYYYYY** [comment]
需求类issue会统一迁移到 https://github.com/Tencent/tdesign-vue-next/issues/848，先可以关注该 issue 动态，有些能力会处理，有些不会支持。这边先close

**Comment by PDB6912** [comment]
这需求被标记为已完成，具体需要怎么使用呢
