### ISSUE TITLE
核心贡献者招募

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1418]
招募要求：

1. 3 年以上工作经验，5 年，10 年，15 年更好
2. 能够熟练使用 Vue3/React 进行组件开发，两者都会的是宝贝

有兴趣的大佬，欢迎加入

**Comment by amadeus711** [comment]
这个 issue 是那个有奖解决 issue 的报名处吗？

**Comment by pengYYYYY** [comment]
不是喔，可以宣传文章里面找一下哈。

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/1530 可以参与issueshot，后面再逐渐成为核心贡献者
