### ISSUE TITLE
[Tree树] 可以增加个选项，当子节点选中时，父节点也选中吗？

### ISSUE THREAD

**Issue by williambao** [Tencent/tdesign-vue-next#1421]
### 这个功能解决了什么问题

一个节点有多个子节点时，当选中其中一个子节点时，目前父节点是半选中状态(其实是没选中)。但是有些场景，只有有一个子节点被选中。父节点即需要被选。 如下图中权限授权页面。箭头1处的子功能若被选中。 箭头2和3的父节点也得被选中。
目前树型无法做到这一点。若点箭头2的【会员明细】处的选择框时，下面所有子节点会都会被选中。
而开了check-strictly="true"选项时，节点间会失去关联，1，2，3都得单独点才行。
![CleanShot 2022-08-15 at 14 04 46@2x](https://user-images.githubusercontent.com/779521/184585261-c2bdd9b9-f8b4-423f-af52-6290aac865aa.png)

### 你建议的方案是什么

增加一个选项。打开时，若选了任意子选项时，父选项自动被选中。

**Comment by pengYYYYY** [comment]
父组件和组件有关联时，父组件有半选状态， 可以使用严格模式，自行控制选中状态，参考下面这个demo
