### ISSUE TITLE
[Collapse] expandOnRowClick属性不能对CollapsePanel Props的header插槽生效？

### ISSUE THREAD

**Issue by a1501255708** [Tencent/tdesign-vue-next#1426]
### tdesign-vue-next 版本

0.19.1

### 重现步骤
如何在header自定义插槽中也触发展开事件？
_No response_

**Comment by pengYYYYY** [comment]
expandOnRowClick 只是一个开关而已，可以通过点击header然后控制value 来处理哪些面板展开
