### ISSUE TITLE
Tree: issue#1410的tree实例的setItem方法无效仍然存在问题

### ISSUE THREAD

**Issue by ChangJian2077** [Tencent/tdesign-vue-next#1428]
### tdesign-vue-next 版本

0.20.0

### 重现链接

https://github.com/Tencent/tdesign-vue-next/issues/1410

### 重现步骤

如上述issue，在新版本下仍然无法通过setItem方法展开，高亮，选中

### 期望结果

希望该方法能正常运行

### 实际结果

方法不生效

### 框架版本

Vue(3.2.13)

### 浏览器版本

Chrome(104.0.5112.81)

### Node版本

16.13.2

### 补充说明

疑似传参options中少传入了directly:true，否则不能调用this.update();刷新树

```
if (keys.includes(name)) {
          // 疑似少传入{ directly: true }这个options参数导致树不更新
          node[`set${upperFirst(name)}`](spec[name], { directly: true });
}
```

**Comment by pengYYYYY** [comment]
有兴趣的话可以提个PR

**Comment by pengYYYYY** [comment]
0.20.2 已修复

**Comment by centmaster** [comment]
更新到0.20.2版本
        tree.value?.setItem(activeNode?.value, {
          checked: true,
          actived: true,
          expanded: true,
        });
        节点还是没有高亮，并且打印节点信息checked还是false
![image](https://user-images.githubusercontent.com/18643537/187400897-0594fcca-9285-4fdd-8cca-cae711bb87a0.png)
