### ISSUE TITLE
[Menu] 平铺式侧边导航折叠后样式出问题

### ISSUE THREAD

**Issue by cloudfun** [Tencent/tdesign-vue-next#1429]
### tdesign-vue-next 版本

0.20

### 重现链接

https://tdesign.tencent.com/vue-next/components/menu

### 重现步骤

<img width="353" alt="image" src="https://user-images.githubusercontent.com/962598/184683539-32b77042-b5f7-4ef0-b39c-5d05bd4f4f53.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/962598/184684542-1c96c4fc-b699-4443-b924-1609108e01aa.png">

如上图，menu组件使用侧边导航样式折叠收起后，hover菜单图标显示二级菜单时的样式出问题，而且无法点击二级菜单，鼠标一放上去菜单消失

### 框架版本

Vue 3.2.31

### 浏览器版本

chrome 103.0.5060.134

### Node版本

18.7

**Comment by pengYYYYY** [comment]
由于popup做了一些改动，正在修复中，今天会修复

**Comment by pengYYYYY** [comment]
0.20.1 已修复
