### ISSUE TITLE
[Improve][scroller] 请问是否有添加滚动条组件的计划

### ISSUE THREAD

**Issue by wzs28150** [Tencent/tdesign-vue-next#143]
## tdesign-vue-next

You will open an feature issue at tdesign-vue-next
现在目前要想使用滚动条 是在父级上增加 class: narrow-scrollbar，是通过样式来解决的。当里面内容有少到多变化时, 滚动条突然出现之后，占据一定宽度会造成内容的左右闪烁。
出现滚动条之前:
![image](https://user-images.githubusercontent.com/21290257/148160436-2c0d9110-7bcd-4664-aba1-c8507b6def36.png)
出现滚动条之后:
![image](https://user-images.githubusercontent.com/21290257/148160459-672b6877-9ff3-49c4-a35d-fcee68352b55.png)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pengYYYYY** [comment]
已收到， 后面会进行评估
