### ISSUE TITLE
[TreeSelect]等组件 0.20 版本背景色透明

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#1430]
### tdesign-vue-next 版本

最新版

### 重现链接

https://codesandbox.io/s/bug-td-select-showarrow-forked-61iexf?file=/src/App.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/28809916/184779491-6c670d39-9bea-4712-9202-a1437aea4aa7.png)
上层wrap标签没有提供背景色`--td-bg-color-specialcomponent` 导致的吗？

### 期望结果

背景色不透明

### 实际结果

![image](https://user-images.githubusercontent.com/28809916/184779766-d751c321-4eff-471b-8a97-df9ed03eab4c.png)

**Comment by pengYYYYY** [comment]
codesandbox 样式隔离的问题，导致css variables 获取不到。正常使用应该没有这个问题
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/35833812/187366695-0359182c-8f4c-48a8-ad4d-90e78b8a4672.png">

**Comment by Crazymuyang** [comment]
0.20.3 刚修复的
