### ISSUE TITLE
[TimePicker] 滚动到底部或顶部会重复跳动

### ISSUE THREAD

**Issue by wilonjiang** [Tencent/tdesign-vue-next#1435]
### tdesign-vue-next 版本

0.20.1

### 重现链接

https://tdesign.tencent.com/vue-next/demos/time-picker/hms

### 重现步骤

mac osx系统
1. 激活time-picker下拉选择
2. 使用鼠标或笔记本面板在选择时间区域内滚动
3. 在选择时间区域内容接近滚动条底部时，再次触发滚动，此时会出现重复弹跳多次的情况。

### 期望结果

mac osx系统
1. 激活time-picker下拉选择
2. 使用滚轮滑动小时或分钟区域
3. 如果接近底部时滚动，已滚动至底部后，不再重复跳动。

### 实际结果

如果接近底部时滚动，内容已滚动至底部，此时会出现重复弹跳多次的情况。

**Comment by uyarn** [comment]
已知问题 
duplicate of https://github.com/Tencent/tdesign-vue-next/issues/1012 
暂时没想出来怎么处理 如果有兴趣可以一块研究下处理方式

**Comment by uyarn** [comment]
统一关注https://github.com/Tencent/tdesign-vue-next/issues/1012的进展 这个Issue先关闭了
