### ISSUE TITLE
[table] 编辑单元格的校验信息疑似样式错位

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1441]
### tdesign-vue-next 版本

0.20.1

### 重现步骤

![image](https://user-images.githubusercontent.com/101392056/185272373-3e5f01b4-a555-42ac-93f4-2d3c415cc885.png)

### 期望结果

![image](https://user-images.githubusercontent.com/101392056/185272664-9bd6a270-580a-46a9-b642-4d9e3a8dc9c9.png)

**Comment by chaishi** [comment]
这个问题已经 PR 修复，并合并，待发布

**Comment by pengYYYYY** [comment]
0.20.2 已修复
