### ISSUE TITLE
[table] 编辑单元格的disabled可能存在的问题

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1443]
### tdesign-vue-next 版本

0.20.1

### 重现步骤

![image](https://user-images.githubusercontent.com/101392056/185277946-a084b4b5-2b06-499b-b863-d8b7107f9318.png)
第二列的是不可编辑的，但是编辑按钮存在，如果我点击编辑按钮是这样的效果
![image](https://user-images.githubusercontent.com/101392056/185278053-e1c0eb9f-d9fa-427e-9ae4-936984dffbdc.png)
当我再次点击其他地方的时候走了校验规则
![image](https://user-images.githubusercontent.com/101392056/185278144-2764b3a2-fe6e-45dc-8ff0-55103cc7f149.png)

### 期望结果

当表格的编辑单元格的功能，组件如果是不可编辑的情况下，可以不走校验吗，假设一个这样的场景，第一列的内容的内容决定了第二列的变化，第一列是个下拉框，下拉的内容是可输入，不可输入，如果第一列选中可输入字段  第二列会去判断 第一列的值为可输入的时候，第二列可编辑，第一列选中不可输入的时候，第二列不可编辑，两者都是必填项，当第二列为不可编辑的时候应该不走校验规则

**Comment by chaishi** [comment]
可以复现问题的链接没找到

**Comment by luoyu-233** [comment]
> 可以复现问题的链接没找到
[demo.txt](https://github.com/Tencent/tdesign-vue-next/files/9388846/demo.txt)
我附带上demo吧，第一列选中可输入时，第二列可编辑，第二列选中不可输入时，第二列不可编辑，但是还是可以进入编辑状态虽然编辑不了，并且退出编辑的时候第二列触发了校验

**Comment by chaishi** [comment]
对于不可编辑功能，请使用下个版本的新特性 `editableCellState`，用于控制哪些单元格为可编辑状态

**Comment by pengYYYYY** [comment]
我理解这个issue应该可以关掉了吧
