### ISSUE TITLE
[table] 可编辑行，多列联动时，校验规则对联动数据无效

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1444]
### tdesign-vue-next 版本

0.20.1

### 重现链接

https://stackblitz.com/edit/angular-czwauu-ymd8zd?file=src/demo.vue

### 重现步骤

如果我输入的是第一列的内容，我会改变掉第一列和第二列的内容，校验的时候发现，第二列其实是空，，
![image](https://user-images.githubusercontent.com/101392056/185280653-434ed5ab-134b-4cca-9aa6-1dd459d76ce2.png)

但其实内容是已经上去了的

**Comment by chaishi** [comment]
问题描述，其实可以再认真些（读起来太费劲儿了，稍微考虑下读者的感受）
如果我们的文档也这样描述，怕是没人看得懂了

**Comment by pengYYYYY** [comment]
0.20.2 已修复
