### ISSUE TITLE
[menu] safari浏览器下箭头菜单展开/收起箭头没有变化

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#1445]
### tdesign-vue-next 版本

0.20.0

### 重现步骤

![企业微信截图_246abefb-1f18-4ad6-9512-52cc98b605a5](https://user-images.githubusercontent.com/10460238/185281409-0c1cf4a7-c059-466d-a5f3-585768250435.png)
![企业微信截图_332548e5-7a45-4b53-b3ae-5e3b1597d82b](https://user-images.githubusercontent.com/10460238/185281448-e6ebefba-baf9-4e82-9d6b-4be92711bbcb.png)

**Comment by woshishade** [comment]
safari浏览器版本：15.6

**Comment by uyarn** [comment]
属于已知的兼容性问题 
实现方式是active下改变svg的path的d属性 来实现箭头翻转
<img width="622" alt="image" src="https://user-images.githubusercontent.com/26377630/185285891-051ad164-4564-4ed5-9340-4d2b7d85dfbf.png">
但是safari对这个属性不认识
<img width="786" alt="image" src="https://user-images.githubusercontent.com/26377630/185285850-01802c29-22a9-43cb-ab8c-5836cd7260eb.png">

**Comment by woshishade** [comment]
@uyarn 不太想从上层修改样式，你们有办法兼容这个问题吗？

**Comment by uyarn** [comment]
> @uyarn 不太想从上层修改样式，你们有办法兼容这个问题吗？

之前最开始是想通过rotate3d实现 但是rotate3d在翻转到水平面会完全水平 视觉上会完全呈现一条线 不是最理想的效果
@Wen1kang 看看能不能接受safari用rotate3d来兼容？

**Comment by Wen1kang** [comment]
> > @uyarn 不太想从上层修改样式，你们有办法兼容这个问题吗？
> 
> 之前有想通过rotate3d实现 但是rotate3d在翻转到水平面会完全水平 视觉上会完全呈现一条线 不是最理想的效果 @Wen1kang 看看能不能接受safari用rotate3d来兼容？

不建议使用 rotate3D 来实现哦，不然做出来效果和期望会不太一致，针对Safari能否降级就直接 down 切换成 up 过渡变化就OK了。
