### ISSUE TITLE
Cascader 级联选择器

### ISSUE THREAD

**Issue by wfc66986** [Tencent/tdesign-vue-next#1448]
### tdesign-vue-next 版本

0.18.1

### 重现链接

https://stackblitz.com/edit/angular-ptmg5w?file=package.json,src%2Fdemo.vue

### 重现步骤

初始化onMounted 加入数据，界面点击懒加载不显示。
![image](https://user-images.githubusercontent.com/54029486/185326982-a1db9952-7110-4118-bcb3-41dfacb4b4d2.png)

### 期望结果

初始化加入数据懒加载，可以点击界面效果

**Comment by pengYYYYY** [comment]
0.20.2 已修复
