### ISSUE TITLE
[slider] 刻度值跌到底部了...

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#1449]
### tdesign-vue-next 版本

0.20.1

### 重现步骤

![image](https://user-images.githubusercontent.com/10460238/185343786-dc0251ed-b5fc-49b0-9846-f83e1abc7c28.png)
![image](https://user-images.githubusercontent.com/10460238/185343813-739f25af-3228-4f7d-9de5-fba7c225111e.png)

**Comment by pengYYYYY** [comment]
0.20.2 已修复
