### ISSUE TITLE
[Dialog] 非模态对话框 显示不够直观

### ISSUE THREAD

**Issue by ali-pay** [Tencent/tdesign-vue-next#1452]
### 没有阴影的：
![Snipaste_2022-08-19_09-21-17](https://user-images.githubusercontent.com/54493910/185522015-40e8e1d7-64a1-4a32-9d0f-e71cf55437b1.png)

### 有阴影的：
![Snipaste_2022-08-19_09-19-10](https://user-images.githubusercontent.com/54493910/185521790-b42f02c7-8152-4606-936d-ca99461ffdfa.png)

### 你建议的方案是什么

建议 非模态对话框 加入 box-shadow、cursor:move 样式，或修改为类似 Card 的可配置属性；

可能需要再加入 user-select:none ，因为现在可以拖拽的对话框已经不能复制了，但是鼠标放在文字上还是会可以选中文字，类似这样：
![Snipaste_2022-08-19_09-28-39](https://user-images.githubusercontent.com/54493910/185522867-1fec52b6-883b-4402-81da-f5b957ca48da.png)

**Comment by huoyuhao** [comment]
ok 我会尽快处理

**Comment by huoyuhao** [comment]
@ali-pay 这里确认了一下 确实存在这个问题，modelss非模态对话框模式下
draggable 属性配置为true，弹窗内容无法复制。

我的问题是：这个原因是因为拖拽功能绑定鼠标按下事件，所以无法复制弹窗文字。
你这里期待的结果是使用拖拽时，不应该可以选中文字，使用cursor:move 或者 user-select:none 样式。

麻烦确认一下理解是否正确

**Comment by ali-pay** [comment]
> @ali-pay 这里确认了一下 确实存在这个问题，modelss非模态对话框模式下 draggable 属性配置为true，弹窗内容无法复制。
> 
> 我的问题是：这个原因是因为拖拽功能绑定鼠标按下事件，所以无法复制弹窗文字。 你这里期待的结果是使用拖拽时，不应该可以选中文字，使用cursor:move 或者 user-select:none 样式。
> 
> 麻烦确认一下理解是否正确

是的，修改鼠标的样式，感觉上更能体现这是个可以拖动的组件
