### ISSUE TITLE
[tree] 能否监听到节点上的右键点击事件

### ISSUE THREAD

**Issue by centmaster** [Tencent/tdesign-vue-next#1454]
### 这个功能解决了什么问题

希望通过右键点击事件实现树节点的复制和删除，能否提供onRightClick类似事件

### 你建议的方案是什么

提供onRightClick类似事件

**Comment by pengYYYYY** [comment]
可以通过 `label slot` 来处理，然后对 `label slot` 做 `contextmenu` 的监听，这样可以做到你需要的效果。

**Comment by xiangshj** [comment]
> 可以通过 `label slot` 来处理，然后对 `label slot` 做 `contextmenu` 的监听，这样可以做到你需要的效果。
添加到label上的右键无法覆盖整个节点这一行，只能在label区域才有右键，节点所在行的其他区域没有无法触发；
