### ISSUE TITLE
[Select] 组件建议加入blur/focus实例方法和autofocus自动聚焦属性

### ISSUE THREAD

**Issue by latte-z** [Tencent/tdesign-vue-next#1456]
### 这个功能解决了什么问题

在可转换编辑态组件替换的场景下，切换显示后需要主动激活select的交互，同时也可以利用这个focus/blur的事件变化来触发保存的请求。

### 你建议的方案是什么

增加实例方法和属性

**Comment by pengYYYYY** [comment]
感谢反馈，这个需求移动到 https://github.com/Tencent/tdesign-vue-next/issues/848 统一进行管理，本issue关闭。相关进展关注此issue
