### ISSUE TITLE
[menu] 当顶部菜单过多，菜单栏会一直往后挤压，导致右边内容丢失

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1457]
### tdesign-vue-next 版本

0.20.1

### 重现步骤

这是少数菜单项的情况下
![image](https://user-images.githubusercontent.com/101392056/185582324-b3c8b47b-e503-474d-b7bc-9fb668e3c414.png)
zhe这是多数菜单项的情况下
![image](https://user-images.githubusercontent.com/101392056/185581947-afdd6abe-00cc-49d3-a262-b89013b4601d.png)

### 期望结果

是否可以优化一下这个挤压问题，当菜单栏过多，可以出现一个点击按钮，可以左右切换菜单栏

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/1285 相同issue
