### ISSUE TITLE
[Select] 远程搜索带过滤时，已选择会出问题

### ISSUE THREAD

**Issue by williambao** [Tencent/tdesign-vue-next#1466]
### tdesign-vue-next 版本

0.20.1

### 重现步骤

当远程搜索模式+多选模式时， 再次输入过滤关键字去查询新列表时，已经选择的内容会从label变为value
![CleanShot 2022-08-21 at 12 19 36](https://user-images.githubusercontent.com/779521/185775393-2af9a48c-5fa8-4403-bd93-b070a1ddb52c.gif)
。

### 期望结果

已选择的内容应该缓存起来，当再次过滤时，不应该去影响已选内容。

**Comment by pengYYYYY** [comment]
lable中的显示会根据返回的内容来，这种情况应该是返回的数据没有带你已经选中的那个值。

**Comment by pengYYYYY** [comment]
待提供更详细的示例

**Comment by sechi747** [comment]
> 待提供更详细的示例
![QQ录屏20220822084645](https://user-images.githubusercontent.com/73569598/185819135-44bfab0a-8504-4d29-8188-848a2ea6f164.gif)
[复现地址](https://stackblitz.com/edit/angular-ydsjkn?file=src/demo.vue)

**Comment by williambao** [comment]
@williambao @sechi747  是这个原因的， 远程搜索时每次输入关键词返回不同列表，否则不需要做过滤了。
感觉这个在带远程搜索时常规操作了。
是否能把已选择的label和value关系缓存在控件里？

**Comment by pengYYYYY** [comment]
这个场景我想想怎么处理吧

**Comment by hkaikai** [comment]
我这边自己处理了这种情况，把modelValue的label默认push到options里面
