### ISSUE TITLE
[table] 希望可编辑行表格的`TableEditableCellConfig.rules`增加function形式

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#1472]
### 这个功能解决了什么问题

`TableEditableCellConfig.rules`现在是与`form`的`rules`保持一致，但是`form`可以自定义`validate`来使用`form`中的其他属性与当前属性值进行比较判断，但是放到`table`中的话就不好弄了，我无法准确的获取我需要比对的行内数据，所以希望`TableEditableCellConfig.rules`属性可以和`TableEditableCellConfig.props`一样支持`function`类型的配置项，入参也可以和`props`一致`(params: TableEditableCellPropsParams<T>) => Array`

### 你建议的方案是什么

edit: {
  ...
  rules: Array | (params: TableEditableCellPropsParams<T>) => Array
}

**Comment by chaishi** [comment]
支持，这个逻辑不复杂执行一下函数就好了。看看是否方便提一个 PR 呢？

同理的话，也许每一个配置都需要是 function，这样的话，可能后续需要考虑直接给整个 edit: TableEditConfig 支持下 function

**Comment by wandoupeas** [comment]
> 支持，这个逻辑不复杂执行一下函数就好了。看看是否方便提一个 PR 呢？
> 
> 同理的话，也许每一个配置都需要是 function，这样的话，可能后续需要考虑直接给整个 edit: TableEditConfig 支持下 function

提PR的话我也只能提vue3的

**Comment by chaishi** [comment]
你能的会的愿意的，你来
你不能的不会的或者不愿意的，我来

本次先仅支持 rules 支持 function，涉及到 API 变更，执行下方命令行获取最新的 API 定义
```
git clone https://github.com/TDesignOteam/tdesign-api
npm run api:docs Table 'VueNext(PC)' finalProject
```
注意保持 tdesign-api 和 tdesign-vue-next 目录同级

**Comment by wandoupeas** [comment]
okk

**Comment by luoyu-233** [comment]
> 你能的会的愿意的，你来 你不能的不会的或者不愿意的，我来
> 
> 本次先仅支持 rules 支持 function，涉及到 API 变更，执行下方命令行获取最新的 API 定义
> 
> ```
> git clone https://github.com/TDesignOteam/tdesign-api
> npm run api:docs Table 'VueNext(PC)' finalProject
> ```
> 
> 注意保持 tdesign-api 和 tdesign-vue-next 目录同级
提个问题，如果我主动去调用rules的函数，会触发校验吗(我)

> 你能的会的愿意的，你来 你不能的不会的或者不愿意的，我来
> 
> 本次先仅支持 rules 支持 function，涉及到 API 变更，执行下方命令行获取最新的 API 定义
> 
> ```
> git clone https://github.com/TDesignOteam/tdesign-api
> npm run api:docs Table 'VueNext(PC)' finalProject
> ```
> 
> 注意保持 tdesign-api 和 tdesign-vue-next 目录同级

提个问题，如果我主动调用rules写好的函数，会触发该行数据的校验吗？(我想让他触发校验)

**Comment by chaishi** [comment]
> 调用`PrimaryTableInstanceFunctions.validateTableDate`或者`PrimaryTableInstanceFunctions.validateRowData`即可

`validateRowDate` 已废弃，请使用 `validateRowData`
