### ISSUE TITLE
[Cascader] load不触发

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1477]
### tdesign-vue-next 版本

0.20.1

### 重现链接

https://stackblitz.com/edit/angular-as9iuv?file=package.json,src%2Fdemo.vue

### 期望结果

load正常触发

### 实际结果

load没有触发

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/1471 已修复

**Comment by pengYYYYY** [comment]
0.20.2 已修复
