### ISSUE TITLE
[docs] 使用 less style 的组件示例在 stackblitz 缺少 less 依赖

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [Tencent/tdesign-vue-next#1478]
### tdesign-vue-next 版本

0.20.1

### 重现步骤

1. 官网打开 Affix 第二个 demo
2. 在 Stackblitz 中打开显示缺少 less 依赖
![image](https://user-images.githubusercontent.com/54026110/185975108-543b6088-cc76-4bbc-8f04-afe02c3111b3.png)

### 补充说明

所有使用 less style 的 demo 都缺少 less 依赖

**Comment by Lmmmmmm-bb** [comment]
pr https://github.com/Tencent/tdesign-vue-next/pull/1479

**Comment by pengYYYYY** [comment]
0.20.2 已修复
