### ISSUE TITLE
[Form] Form组件实例方法，如何获得ts的类型支持？

### ISSUE THREAD

**Issue by 15779735060** [Tencent/tdesign-vue-next#1481]
### tdesign 版本

0.20.1

### 期望结果

提供对form组件实例方法的支持

### 实际结果

Property 'validate' does not exist on type 'string'.

### 框架版本

vue Next 0.20.1

**Comment by chaishi** [comment]
这个问题有点抽象，没有任何代码，只有一个提示

**Comment by 15779735060** [comment]
实际情况就是，我需要对表单进行验证，需要调用该组件下的validate方法，于是我在组件绑定了一个ref，:ref="(e) =&gt; (state.formRef = e)"，因为采用的是ts编码，需要给我的state.fromRef指定一个类型，于是我引入了一个&nbsp;import type { FormInstanceFunctions } from "tdesign-vue-next";，最后实际调用vilidate方法的时候，是这样的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-vue-next"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 中午1:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue-next] [Form] Form组件实例方法，如何获得ts的类型支持？ (Issue #1481)





 
这个问题有点抽象，没有任何代码，只有一个提示
