### ISSUE TITLE
[Icon] 既然已经提供了icon的全局特性配置，为什么引入图标的url不能自定义呢？

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#1482]
### 这个功能解决了什么问题

离线加载图标

### 你建议的方案是什么

看源码，好像`图标地址，地址内容参考[组件内部默认加载图标](https://tdesign.gtimg.com/icon/web/index.css)`为什么不能在`全局特性配置`中暴露出url自定义的方法呢？

**Comment by chaishi** [comment]
当开放一个需求的时候，新的需求随之而来

**Comment by arieslee** [comment]
> 当开放一个需求的时候，新的需求随之而来

我觉得这是解决离线使用图标的一个好方法呀！

**Comment by uyarn** [comment]
离线环境可以用按需引入的方式 文档FAQ有说明 想问问是什么场景 一定要用iconfont的方式来使用图标？

**Comment by arieslee** [comment]
> 离线环境可以用按需引入的方式 文档FAQ有说明 想问问是什么场景 一定要用iconfont的方式来使用图标？

额，文档我看过的，就拿这个项目来说：https://tdesign.tencent.com/starter/vue-next/#/dashboard/base
侧栏的菜单中的图标基本都是
` ` ` if (typeof item.icon === 'string') {
    return () => item.icon && <t-icon name={item.icon}></t-icon>;
  }`` ` 
这处方式展示的图标，要按照文档中说的全换成` svgIcon` ，有点麻烦^_^

**Comment by pengYYYYY** [comment]
没有问题的话，issue先关闭了，待后续回复可以reopen
