### ISSUE TITLE
[table] 编辑单元格数据展示问题

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1483]
### tdesign-vue-next 版本

0.20.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

![image](https://user-images.githubusercontent.com/101392056/186089342-312a64bd-9cf6-4955-b2b2-517407d3b656.png)
将该行数据删掉
![image](https://user-images.githubusercontent.com/101392056/186089579-843280b8-2988-4734-807a-18cc70f76969.png)
再去将下一行删除
![image](https://user-images.githubusercontent.com/101392056/186089664-983d66ea-c705-47e2-a6dc-a9f7e8ebcc5f.png)
结果上一行的内容又显示出来了
![image](https://user-images.githubusercontent.com/101392056/186089719-5cbe353a-cfe4-41fc-ba64-19ea6aef0120.png)
看数据像是已经删掉了，但不知为什么页面没变化

### 期望结果

1. 页面展示可能不对
2. 清空该数据内容之后，能否保留该数据依旧可编辑？

**Comment by chaishi** [comment]
确实，清空需要保证依旧保持可编辑，需要看看哪里的问题

**Comment by Lmmmmmm-bb** [comment]
看了下这部分是 demo 的问题
