### ISSUE TITLE
[Input 输入框] 能否支持input的keyup.enter之类的事件

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#1484]
### 这个功能解决了什么问题

与vue原生input事件兼容

### 你建议的方案是什么

```
 <t-input @keyup.enter="finishEdit"  />
```

**Comment by sechi747** [comment]
感觉可以增加一个事件？比如` <t-input @press-enter="finishEdit"  />` 或者 ` <t-input :onPressEnter="finishEdit"="finishEdit"  />`

**Comment by pengYYYYY** [comment]
这个的话，可以用返回值event里面的code来判断。可以自己缝状一下，暂时不做API增加
