### ISSUE TITLE
[Tree 树] 无法用数组.push方法动态添加节点

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#1485]
### tdesign-vue-next 版本

0.20.1

### 重现链接

https://stackblitz.com/edit/angular-el8egt?file=package.json,src%2Fdemo.vue

### 重现步骤

点击示例中的“动态添加节点”

```
<template>
  <div class="tdesign-tree-base">
    <t-button @click="add">动态添加节点</t-button>
    <div v-for="(value, key) in data.items">{{ value.label }}</div>
    <t-tree :data="data.items" activable hover transition />
  </div>
</template>

<script setup>
import { reactive } from 'vue';
const data = reactive({
  items: [
    {
      label: '第一段',
      children: [
        {
          label: '第一段',
        },
        {
          label: '第二段',
        },
      ],
    },
    {
      label: '第二段',
      children: [
        {
          label: '第一段',
        },
        {
          label: '第二段',
        },
      ],
    },
  ],
});
const add = () => {
  data.items.push({
    label: 'aaa',
    children: [
      {
        label: 'aaa.1',
      },
      {
        label: 'aaa.2',
      },
    ],
  });

  // const items = data.items;
  // data.items = [];
  // data.items.push(...items);
};
</script>
<style scoped>
.demo-tree-base {
  display: block;
}
</style>

```

### 期望结果

能像原生vue的div一样动态显示最新结果

另外，data是否支持 v-model 双向绑定，主要是 拖拽节点后，自动修改 data，避免用户使用还需要二次写代码

### 实际结果

没有反应

**Comment by chaishi** [comment]
对，应该不支持这种方式。

请参考官网文档，查阅如何添加节点。有示例代码。

**Comment by Alsmile** [comment]
> 对，应该不支持这种方式。
> 
> 请参考官网文档，查阅如何添加节点。有示例代码。

我是想说，从易用角度，这种方式更简单直接，也符合vue原生习惯

**Comment by pengYYYYY** [comment]
data 暂不支持双向绑定，data是作为选项参数使用的，并不是作为类似value这种主参数用的，这类参数不会考虑做语法糖。节点插入参考一下文档https://tdesign.tencent.com/vue-next/components/tree#%E8%87%AA%E5%AE%9A%E4%B9%89。有其他问题再reopen

**Comment by Alsmile** [comment]
这些功能，我已经实现了，之所以提出这些问题，只是觉得，数据驱动显示或者双向绑定，能减少使用者的额外负担，否则重复造轮子的意义就是为了KPI？

目前，插入节点是：
```
data.push(item)
```
使用方便，还是
```
const insertAfter = (node) => {
  const item = getInsertItem();
  if (item) {
    tree.value.insertAfter(node.value, item);
    setLabel(item.value);
  }
};
```
方便？

我拖拽树节点后，如何得到与之匹配的data？是一个双向绑定的语法糖，还是 写一堆树遍历函数，而且写不好还容易有性能和死循环问题

**Comment by beloved-zh** [comment]
也是在这块踩坑了，没有注意到添加节点的案例，直接看api了，根据编写vue的习惯直接操作data没起作用，看了这个才发现，是要操作实例方法，不是很符合直觉

**Comment by supmry** [comment]
> 这些功能，我已经实现了，之所以提出这些问题，只是觉得，数据驱动显示或者双向绑定，能减少使用者的额外负担，否则重复造轮子的意义是什么？
> 
> 目前，插入节点是：
> 
> ```
> data.push(item)
> ```
> 
> 使用方便，还是
> 
> ```
> const insertAfter = (node) => {
>   const item = getInsertItem();
>   if (item) {
>     tree.value.insertAfter(node.value, item);
>     setLabel(item.value);
>   }
> };
> ```
> 
> 方便？
> 
> 我拖拽树节点后，如何得到与之匹配的data？是一个双向绑定的语法糖，还是 写一堆树遍历函数，哪怕有个回调函数也好。以为只需要简单的遍历一下，发现没这么简单，如果不是Immutability，很容易出问题，整个树乱套。看起来，似乎Tree的很多功能没有真正的在实际项目用用过

确实太麻烦了，最不能理解的就是 TreeNodeModel中有个label， TreeNodeModel.data中有个label,这两个label还需要手动setLabel来保持一致
