### ISSUE TITLE
[Table] enhanced-table的tree.treeNodeColumnIndex属性支持动态修改

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1487]
### 这个功能解决了什么问题

根据条件判断那列可以展开

### 你建议的方案是什么

tree.treeNodeColumnIndex变化时，表格可展开的列相应变化

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/1740

**Comment by xiaosansiji** [comment]
已在 0.48.3 版本修复
