### ISSUE TITLE
[table] 关于`editableCellState`的问题及建议

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#1488]
我有看到新的api(`editableCellState`)的用法，但是好像跟我描述的有点偏差。

本来我想达到的效果是在`columns.edit`属性内添加一个控制本列数据是否可编辑的属性，这个属性接受一个响应式的boolean对象或者是一个返回boolean类型的function，function的入参即为`PrimaryTableCellParams<T>`。

现在是在table的props内添加了一个类似的属性`editableCellState`，这样目前遇到两个问题：
1. `可编辑行的表格`情况下，`editableCellState`的表现与`可编辑单元格的表格`的表现相反，返回`false`现在表现为可以编辑，`true`不可编辑，这应该是个bug吧。

<img width="984" alt="image" src="https://user-images.githubusercontent.com/20508822/186130709-791741f4-80b5-4c0d-bdd7-6261017e84e9.png">

2. 当我需要根据行数据控制多列属性的编辑状态时，这样个api就显得不是那么方便了，我需要判断当前列的列名是什么，当row中的某个值为什么的时候，来动态返回编辑状态，例如如下代码，这样我觉得不是很方便，所以我还是建议可以在`columns.edit`中添加一个`editable`属性，这样编码时也可以在`columns`中更清晰的看到当前列的可编辑状态

![image](https://user-images.githubusercontent.com/20508822/186131704-671131ff-28cb-449a-ae1d-ae63cae3cf67.png)

_Originally posted by @wandoupeas in https://github.com/Tencent/tdesign-vue-next/issues/1387#issuecomment-1223854368_

**Comment by chaishi** [comment]
第一点，确实反了，有同学提了 PR，会调整

第二点，对于你的需求来说，无非是加个 if 的判断就可以实现相关需求。但是组件库不能只考虑某一个具体的需求。
今天你 需要 控制某一列是否可编辑
明天他 需要 控制某一行是否可编辑
后天她 需要 控制 某一个单元格是否编辑

你觉得在 column 里面编码更清晰，是因为你只看到自己的业务是列编辑控制。

但是有更多其他场景的可编辑控制

**Comment by chaishi** [comment]
第一点，已于 `0.20.3` 修复
