### ISSUE TITLE
[Form] FormInstanceFunctions type有问题，怎么都是可选

### ISSUE THREAD

**Issue by dmyz** [Tencent/tdesign-vue-next#1491]
### tdesign-vue-next 版本

0.20.2

### 
```
const form = ref(null);
const resetPhoneNumber = () => {
  form.value?.reset({ fields: ['tel'] });
};
```

**Comment by PDieE** [comment]
如果是 ts 的话，试试下面的

```` typescript
const form = ref<FormInstanceFunctions>();
````

**Comment by k1nz** [comment]
没有导出是什么意思呢？如果用的是 `setup()` 的话检查一下 `form` 有没有 return

**Comment by dmyz** [comment]
![image](https://user-images.githubusercontent.com/15307200/186360648-81685f70-b125-4e1c-b74b-cf941e2c8006.png)

**Comment by k1nz** [comment]
先用 `formRef.value?.reset?.()`，types 文件可能会统一修改一下

**Comment by k1nz** [comment]
相同 issue #1481

**Comment by dmyz** [comment]
好的

**Comment by k1nz** [comment]
![image](https://user-images.githubusercontent.com/67723917/186364749-f317e2a2-c818-45a3-b887-5ab3de5db484.png)

@chaishi 麻烦看下 Form 实例方法的 api 是否需要修改呢，这些方法都不应该是可选的

**Comment by chaishi** [comment]
Function 都改成必须存在
