### ISSUE TITLE
[Select] multiple和filterable状态下，选中选项后再次输入，无法输入新标签。

### ISSUE THREAD

**Issue by taomas** [Tencent/tdesign-vue-next#1495]
tdesign-vue-next 版本
0.20.2

重现链接
No response

重现步骤
1、组件多选和filterable状态下，组件选中选项后，再次输入则无法输入新标签，按下空格键会默认清空输入的值。
2、当失去焦点后再次输入，按下空格键则标签输入正常。

![Kapture 2022-08-24 at 15 51 21](https://user-images.githubusercontent.com/17002702/186362438-0746a023-c9c7-4540-8cf4-fb009d123f01.gif)

重现案例：https://stackblitz.com/edit/angular-sohbwj?file=package.json

期望结果
多选和filterable状态下，选中选项后，再次输入可以正常输入。

实际结果
No response

框架版本
No response

浏览器版本
No response

系统版本
No response

Node版本
No response

补充说明
No response

**Comment by jiazengp** [comment]
领取 @pengYYYYY

**Comment by funczh** [comment]
> 

目前解决的进展如何呢？我在使用的过程中也发现了这个问题，但是这个issue好像很久没有进展了@pengYYYYY

**Comment by pengYYYYY** [comment]
并未发现该问题，
