### ISSUE TITLE
[Card] actions 区域是完全自定义区域，不应该有颜色

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1499]
### tdesign-vue-next 版本

0.20.2

### 重现步骤

<img width="1102" alt="企业微信截图_fc4b2d9b-4346-4781-aa7a-7782bbd62257" src="https://user-images.githubusercontent.com/11605702/186388811-b1a73969-8820-443d-8969-9de501f9713c.png">

**Comment by Tomaolala** [comment]
领取 预计26号之前

**Comment by uyarn** [comment]
@Tomaolala  因为颜色从样式里去掉了 为了保证demo不变 需要把action的demo改用Link组件或者增加个颜色展示
