### ISSUE TITLE
[Select] creatable选择后不显示

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1500]
### tdesign-vue-next 版本

0.20.2

### 重现链接

https://stackblitz.com/edit/angular-ur5ehw?file=src%2Fdemo.vue

### 重现步骤

在表单下 Select开启creatable和filterable后，创建的条目选择不显示，点击提交按钮后才显示

且校验不通过（已经选择了创建的条目）

还有一个问题待重现：同样的情况，选择创建的条目后，点击提交按钮会清空

### 期望结果

创建的条目功能正常

**Comment by D-xuanmo** [comment]
@hkaikai 你看下我这个链接，试试是不是你需要的效果，每次新增之后需要保存一下添加的数据
[https://stackblitz.com/edit/angular-ur5ehw-qoqd8p?file=src/demo.vue](https://stackblitz.com/edit/angular-ur5ehw-qoqd8p?file=src/demo.vue)

**Comment by hkaikai** [comment]
https://stackblitz.com/edit/angular-ur5ehw-z1hda1?file=src%2Fdemo.vue
@D-xuanmo 
![image](https://user-images.githubusercontent.com/19343340/186631382-2093233a-41d7-4677-b526-9168ccd3cc65.png)

加一个多选后有问题，这个应该是这个问题的复现：`同样的情况，选择创建的条目后，点击提交按钮会清空`

**Comment by PDieE** [comment]
你这个 demo 里面 formdata 都不是响应式的 怎么可能响应啊

**Comment by pengYYYYY** [comment]
在第一次创建时，点击创建条目后没有触发v-model更新

**Comment by pengYYYYY** [comment]
`const formData = { ...INITIAL_DATA }; ` 这一行的问题，需要为 `ref` ，https://stackblitz.com/edit/angular-jep45i?file=src%2Fdemo.vue 表现正常
