### ISSUE TITLE
[Cascader] selectInputProps 属性透传事件时，变成了数组

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1502]
### tdesign-vue-next 版本

0.20.2

### 重现链接

https://stackblitz.com/edit/angular-rjyxma?file=src%2Fdemo.vue

### 重现步骤

```javasript
<t-cascader
      v-model="value"
      :options="options"
      clearable
      @change="onChange"
      filterable
      :select-input-props="{ onFocus: focus }"
    />
```
focus 无法执行，控制台报：
[Vue warn]: Invalid prop: type check failed for prop "onFocus". Expected Function, got Array

**Comment by pengYYYYY** [comment]
<img width="881" alt="image" src="https://user-images.githubusercontent.com/35833812/186429580-5ed36ee6-1bb7-42a6-beb1-81a483fc298d.png">
cascader 组件已经有onFocus 透出，可以用这一个
