### ISSUE TITLE
[DatePicker] 日期文本和右侧图标没有居中对齐

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1506]
### tdesign-vue-next 版本

0.20.2

### 重现步骤

<img width="491" alt="image" src="https://user-images.githubusercontent.com/11605702/186524836-bfdc371c-5916-4060-9bc6-2a11af91c297.png">

**Comment by PDieE** [comment]
领取任务，预计8月25日完成
