### ISSUE TITLE
[DatePicker] 组件中， TExtraContent 这个自定义的组件，关于 `selectedValue` 的 props 定义的不正确

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1508]
### tdesign-vue-next 版本

0.22.0

### 重现步骤

<img width="1062" alt="企业微信截图_534d9f78-cafd-4494-92f1-6eb68f464154" src="https://user-images.githubusercontent.com/11605702/186561014-2038171b-83f1-4125-bce1-cd47a37eb372.png">

`TExtraContent` 这自定义的组件，关于 `selectedValue` 的 props 定义的不正确，应当是
```js
value: {
    type: [String, Number, Array, Date] as PropType<TdDatePickerProps['value']>,
  }
```

<img width="733" alt="企业微信截图_04bd1fff-4655-45ce-a4b7-8479bf98f2e6" src="https://user-images.githubusercontent.com/11605702/186560699-2ec92357-0c4c-4f47-a424-fd6debd081a7.png">

**Comment by pengYYYYY** [comment]
0.20.3已修复
