### ISSUE TITLE
[InputNumber] 0.20.2 版本中，设置 decimalPlaces 时，非大数的值类型为 string 的问题

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#1510]
### tdesign-vue-next 版本

最新版

### 重现链接

https://codesandbox.io/s/bug-td-select-showarrow-forked-8d8xc6?file=/src/App.vue:317-331

### 重现步骤

失焦后，由 number 变成 string；
0.20.1 版本正常；

### 期望结果

依然保持 number 类型

**Comment by chaishi** [comment]
需求不清晰，需要再描述下。
`decimalPlaces=2` 的情况下，`12.10` 只能是字符串，如果接受 `12.10` 转换为 `12.1`，不保留尾部的 0， 可能需要我们新增一个开关控制

**Comment by Crazymuyang** [comment]
> 



> 需求不清晰，需要再描述下。 `decimalPlaces=2` 的情况下，`12.10` 只能是字符串，如果是希望 `‘12.10’` 转换为数字 `12.1`，不保留尾部的 0， 可能需要我们新增一个开关控制。
> 
> 或者，不要使用 `decimalPlaces=2`，`12.1` 也不是保留 2 位小数

0.20.1 版本前的是能够保证类型一致的，升级后因为类型不一致导致了很多报错，所以我们又退回了0.20.1 版本。
这算不上是一个需求，只是对我们的项目来说算是一个破坏性的变更。
既然无法改回原来的状态，那只能我们自己适配后再考虑升级最新版了。
