### ISSUE TITLE
[Select] 文档Option Props缺少key字段

### ISSUE THREAD

**Issue by RayJason** [Tencent/tdesign-vue-next#1515]
### tdesign-vue-next 版本

0.20.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/select?tab=api#option-props

### 重现步骤

[样例demo](https://tdesign.tencent.com/vue-next/components/select?tab=demo) 的`t-option` 标签都有写key和value，文档中却没有key的说明，不确定是否必填。

### 期望结果

不确定此处的key对组件渲染是否起到像v-for一样的作用，请PMC 同学评估一下～
1. 文档补充对`key`的说明介绍。
2. 删除demo中的`key`。

**Comment by pengYYYYY** [comment]
key 就是vue的key，和组件无关
