### ISSUE TITLE
[table] 支持组件序号ID

### ISSUE THREAD

**Issue by zhairy** [Tencent/tdesign-vue-next#1517]
### 这个功能解决了什么问题

table 组件的序号，也就是rowkey 无法自动生成序号ID,每次数据导入必须 手动赋值序号id,如果删除行，那么就必须写个方法，每次删除或者插入之类的 都调用该方法 重新生成序号id并进行排序，这样太消耗性能了，而且手动生成的序号id 遇到分页的时候，第二页也是接续上一页的序号的，但是实际使用过程中，序号id 是为了方便用户 查看 选中行是当前页的第几行数据而已 ，而不是用户关心 这个是整个数据的第几条数据

### 你建议的方案是什么

建议根据分页大小 自动生成，并且提供两种方案 一种auto  即自动生成ID 或者使id=colindex+1  另一种可以开发者根据需求自己指定

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/1740
