### ISSUE TITLE
[Cascader] Clearable无效

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#1521]
### tdesign-vue-next 版本

0.20.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/cascader

### 重现步骤

官网`Cascader 级联选择器`前两个实例都可以重现

### 期望结果

点击"x"后，可以清空选中的值

### 实际结果

点击"x"后，并未清空选中的值

**Comment by Lmmmmmm-bb** [comment]
pr https://github.com/Tencent/tdesign-vue-next/pull/1524
