### ISSUE TITLE
[Calendar] onCellClick和onCellDoubleClick疑似有冲突

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1526]
### tdesign-vue-next 版本

0.20.2

### 重现步骤

当我给日历加上日历单元格双击时触发，日历单元格点击时触发，这两个api的时候，双击单元格触发了次点击事件和一次双击事件，感觉像是有一点问题，如果我在某个较短的时间段内进行了两次点击，是否可以只触发双击事件，而不是触发两次点击和一次双击

### 期望结果

当我给日历加上日历单元格双击时触发，日历单元格点击时触发，这两个api的时候，双击单元格触发了次点击事件和一次双击事件，如果我在某个较短的时间段内进行了两次点击，是否可以只触发双击事件，而不是触发两次点击和一次双击

### 实际结果

当我给日历加上日历单元格双击时触发，日历单元格点击时触发，这两个api的时候，双击单元格触发了次点击事件和一次双击事件，

### 补充说明
有需要点击日期单元格出现一个弹框进行文本记事，双击日期单元格来展示我对应的记事内容和当天某信息数据
_No response_

**Comment by PsTiu** [comment]
> ### tdesign-vue-next 版本
> 0.20.2
> 
> ### 重现链接
> _No response_
> 
> ### 重现步骤
> 当我给日历加上日历单元格双击时触发，日历单元格点击时触发，这两个api的时候，双击单元格触发了次点击事件和一次双击事件，感觉像是有一点问题，如果我在某个较短的时间段内进行了两次点击，是否可以只触发双击事件，而不是触发两次点击和一次双击
> 
> ### 期望结果
> 当我给日历加上日历单元格双击时触发，日历单元格点击时触发，这两个api的时候，双击单元格触发了次点击事件和一次双击事件，如果我在某个较短的时间段内进行了两次点击，是否可以只触发双击事件，而不是触发两次点击和一次双击
> 
> ### 实际结果
> 当我给日历加上日历单元格双击时触发，日历单元格点击时触发，这两个api的时候，双击单元格触发了次点击事件和一次双击事件，
> 
> ### 框架版本
> _No response_
> 
> ### 浏览器版本
> _No response_
> 
> ### 系统版本
> _No response_
> 
> ### Node版本
> _No response_
> 
> ### 补充说明
> 有需要点击日期单元格出现一个弹框进行文本记事，双击日期单元格来展示我对应的记事内容和当天某信息数据 _No response_

你好，建议你可以这样处理：
`
<template>
    <t-calendar
      @cell-click="cellClick"
      @cell-double-click="cellDoubleClick"
    />
</template>

<script setup>
// 单元格单击和双击事件共存的时候，双击事件会触发单击事件（两次），这“可能不是”正确的效果，
// 这种场景下建议对单击事件进行延迟处理（详见下面 cellClick 和 cellDoubleClick 的代码）
let cellClickTimmer = null;

const cellClick = (options) => {
  clearTimeout(cellClickTimmer); // 用于在双击事件中取消掉额外触发的一次单击事件
  cellClickTimmer = setTimeout(() => {
    console.log(`鼠标左键单击单元格 ${options.cell.formattedDate}`);
  }, 300);
};

const cellDoubleClick = (options) => {
  clearTimeout(cellClickTimmer); // 用于在双击事件中取消掉额外触发另外一次单击事件
  console.log(`鼠标双击单元格 ${options.cell.formattedDate}`);
};
</script>
`
