### ISSUE TITLE
[Cascader ] 可过滤的级联选择器在输入时entry 键会默认全选第一个选项的全部内容

### ISSUE THREAD

**Issue by zuobuer** [Tencent/tdesign-vue-next#1529]
### tdesign-vue-next 版本

0.20.2

### 重现链接

https://stackblitz.com/edit/angular-h3yhfn?file=package.json,src%2Fdemo.vue

### 重现步骤

1、在 Cascader 组件内输入 选项二
2、按 entry 键
3、组件默认选中第一个选项的全部内容

**Comment by pengYYYYY** [comment]
已收到
