### ISSUE TITLE
[Message] 文本为中文时换行

### ISSUE THREAD

**Issue by TingShine** [Tencent/tdesign-vue-next#1539]
### tdesign-vue-next 版本

0.20.2

### 重现步骤

MessagePlugin传入的content为中文时会换行，英文不会

### 框架版本

Vue(3.2.25)

### 浏览器版本

Chrome(103.0.5060.114)

### 系统版本

MACOS(12.4)

**Comment by pengYYYYY** [comment]
这个应该是一个css问题，比较好解决，欢迎提PR
