### ISSUE TITLE
[t-form] whitespace 校验问题

### ISSUE THREAD

**Issue by 734839030** [Tencent/tdesign-vue-next#1546]
### tdesign-vue-next 版本

0.20.3

### 重现链接

https://stackblitz.com/edit/angular-nktfqh-ag9udv?file=package.json

### 重现步骤

1、whitespace 校验不填写message ,没有默认错误信息

### 补充说明

![image](https://user-images.githubusercontent.com/12107198/187404334-ac6ee299-7c44-46a3-a7b3-62e614f75e08.png)

**Comment by Lmmmmmm-bb** [comment]
要确认下这部分，API 文档中有 `whitespace` 的描述，但 `FormRule` 类型中没有 `whitespace` 字段信息

**Comment by 734839030** [comment]
> 要确认下这部分，API 文档中有 `whitespace` 的描述，但 `FormRule` 类型中没有 `whitespace` 字段信息

https://github.com/Tencent/tdesign-vue-next/issues/1098
