### ISSUE TITLE
Menu: 低版本浏览器兼容问题

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1561]
### tdesign-vue-next 版本

0.20.2

### 重现步骤

关于兼容性描述支持Chrome >=84，但是公司用的是Chrome 71 版本的，目前用的 0.20.1版本的组件没什么问题，但是更新到0.20.2的版本发现顶部菜单栏会失效（不清楚最新版本有没有这个问题），如果我想兼容一下旧版本的浏览器需要怎么做。。。

**Comment by pengYYYYY** [comment]
失效的表现是什么样的

**Comment by luoyu-233** [comment]
> 失效的表现是什么样的

![image](https://user-images.githubusercontent.com/101392056/187819307-344b32d0-c40f-41ec-af42-fe922809807f.png)
假设现在是高版本的情况下的布局设置，相同的布局设置下切换到Chrome71 之后是这样
![image](https://user-images.githubusercontent.com/101392056/187819638-55276bb1-dab9-43e7-ac94-515d977861fa.png)
这一部分没有了

**Comment by pengYYYYY** [comment]
0.22.0 应该已经修复了这个问题，先close，如果有问题，再开启这个issue
