### ISSUE TITLE
[v0.20.3] 版本升级带了的问题

### ISSUE THREAD

**Issue by benbenonline** [Tencent/tdesign-vue-next#1578]
### tdesign-vue-next 版本

是的

### 重现步骤

为了解决select-input的clearable以及select-input input-change的问题，从0.13.0版本升级到0.20.3版本，初步查看遇到了如下问题：
1.t-select高度由原来32px变为34px,和其他组件高度不一致
2.t-form-item的 <template #label></template>没有显示
3.t-form__item的添加的margin-bottom:24px;去掉了原min-height:56px，导致原所有页面的复杂的表单需要重新布局，升级成本比较大
4.t-menu，collapsed场景下，无法选中默认的子菜单项
5.其他，版本升级导致的各类问题，主要就是样式和DOM结构发生的变化，导致页面需要重新调整。

### 期望结果

1.期望高度统一
2.修复显示
3.是否升级版本考虑如何兼容老版本的情况，
4.修复选中
5.其他，同3，希望版本升级无需过多调整。

### 框架版本

Vue3.2

### 浏览器版本

Chromium: 80.0.3987.163 Res: 2106.481

### 系统版本

MacOS11.6

### Node版本

node/14.18.0

**Comment by pengYYYYY** [comment]
您好，前期ui上存在一些设计不合理的地方，0.13.0离目前的版本比较久，会存在比较大的breakingChange，我们在升级过程中尽量在避免不兼容的情况，组件会越来越稳定。如果升级给您带来了不便和麻烦的地方，请谅解。组件相关问题欢迎提issue，我们会尽快解决。
