### ISSUE TITLE
[InputNumber 数字输入框] 获得焦点

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#1584]
### 这个功能解决了什么问题

代码自动设置焦点

### 你建议的方案是什么

```
 <t-input-number  ref="input"  />


const input = ref();

onMounted(() => {
  input.value.focus();  //  允许设置焦点
})
```

**Comment by pengYYYYY** [comment]
可以先通过设置 :input-props="{ autofocus: true }"   来达到这个效果，这个需求移至 https://github.com/Tencent/tdesign-vue-next/issues/848 这边统一管理，本issue暂时关闭
