### ISSUE TITLE
[tabel]当表头处于吸顶状态时，鼠标拖拽表格左右滚动，直至超出表格范围，会导致吸顶表格与内容错位

### ISSUE THREAD

**Issue by leihaoj** [Tencent/tdesign-vue-next#1587]
### tdesign-vue-next 版本

0.20.3

**Comment by chaishi** [comment]
无图无代码无视频，3 无 issue，难以处理

**Comment by chaishi** [comment]
官网没有复现上述问题

https://user-images.githubusercontent.com/11605702/188094089-5767793b-0e6c-4b81-ab1e-c58e3c6ba1e9.mov
