### ISSUE TITLE
[Upload] 如何手动触发上传内存提交给后端，[TODO] triggerUpload api 文档待补充

### ISSUE THREAD

**Issue by 81867370** [Tencent/tdesign-vue-next#1594]
### tdesign-vue-next 版本

0.20.2

### 重现步骤

`<t-upload
              ref="uploadRef"
              v-model="files"
              theme="custom"
              allow-upload-duplicate-file
              accept="image/*"
              :max="1"
              :on-select-change="onSelectChangeFile"
              :auto-upload="false"
              :action="uploadUrl"
              :data="{ params }"
            >
              <t-button theme="primary"> 选择图片 </t-button>
            </t-upload>`

### 期望结果

请问那个API，可以手动触发上传提交给后端。或者在ref 暴露个 submit 

### 实际结果

关闭自动上传后，外面自定义按钮，不知道如何手动触发组件提交数据给后端。

**Comment by pengYYYYY** [comment]
uploadRef.triggerUpload()

**Comment by 81867370** [comment]
> 

没有实现期望效果，文件选择完毕，再触发 triggerUpload() 只是重复弹出 选择文件窗口，并不是触发数据提交

**Comment by pengYYYYY** [comment]
重新触发数据提交那一步没有这个API，你可以自行封装上传动作。因为选择文件后你是可以拿到文件对象的。再调用你自己封装的上传方法即可。

**Comment by 81867370** [comment]
> 重新触发数据提交那一步没有这个API，你可以自行封装上传动作。因为选择文件后你是可以拿到文件对象的。再调用你自己封装的上传方法即可。

目前是这样干的，OK

**Comment by pengYYYYY** [comment]
好的
