### ISSUE TITLE
[Upload] 图片上传预览，预览对话框中图片未根据对话框宽度自适应。[TODO]: 使用image-viewer实现图片预览

### ISSUE THREAD

**Issue by renzhe200** [Tencent/tdesign-vue-next#1595]
### tdesign-vue-next 版本

0.20.3

### 重现链接

https://stackblitz.com/edit/angular-uvsygu?file=src/demo.vue

### 重现步骤

上传图片后，预览对话框中图片未根据对话框宽度自适应。
![image](https://user-images.githubusercontent.com/66165407/188254460-2170a0e0-ea36-4129-9ff9-1199bac8e8be.png)

### 期望结果

建议方案：根据对话框宽度限定img的max-width

**Comment by pengYYYYY** [comment]
您好，暂时可以自行写css覆盖一些，后续会使用image-viewer组件替代这一部分

**Comment by chaishi** [comment]
已实现，待发布

https://github.com/Tencent/tdesign-vue-next/pull/1723
