### ISSUE TITLE
[Slider] 垂直布局预览失效了

### ISSUE THREAD

**Issue by wbxl2000** [Tencent/tdesign-vue-next#1600]
### tdesign-vue-next 版本

0.20.3

### 重现链接

https://tdesign.tencent.com/vue-next/components/slider

### 重现步骤

layout 选择 vertical

### 期望结果

垂直 slider

### 实际结果

一个小圆点

### 补充说明

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/57169560/188277571-10d1e877-3326-44b5-9d06-5913f70dcddc.png">

**Comment by pengYYYYY** [comment]
看起来是垂直布局没有高度，有兴趣的话可以修一下

**Comment by wbxl2000** [comment]
看起来高度很短，要不要直接外层100%？
