### ISSUE TITLE
[WIP] CompositionAPI 分支更新内容

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-vue-next#161]
## 开发规范

https://github.com/Tencent/tdesign-vue-next/wiki/TDesign--CompositionAPI-%E5%BC%80%E5%8F%91%E8%A7%84%E8%8C%83

## 组件重构进度
|  组件  | 贡献者 |  备注 | 状态 |
| ----- | ------ | ------ | ---- |
| dropdown |   @qunbotop | 预计5.1后提PR |  ⚡️ 进行中 |
| cascader |  @pengYYYYY | core |  🚀 CR中  |
| select | @geff1991 |  活跃 |  ⚡️ 进行中 |
| form | @K1nZ |  活跃 |  ⚡️ 进行中 |
| time-picker | @uyarn | 跟随组件UI重构,进行中 | ⚡️ 进行中 |
| date-picker | @HQ-Lin  | 跟随组件UI重构,进行中 | ⚡️ 进行中 |
| tree | @TabSpace |  活跃 |  ⚡️ 进行中 |

## 说明

‼️ 请基于 **compositionAPI**  创建你的开发分支。
‼️ 原则上 **compositionAPI** 不接受 `common` 的改动

**compositionAPI** 分支用于 **compositionAPI** https://github.com/Tencent/tdesign-vue-next/issues/58 重构代码的提交,大家对组件重构后请提交至 **compositionAPI** 分支。内容会由管理员按周期合并到 `develop`。

`develop` 分支用于日常迭代、新组件的开发。如果大家在重构中发现 `bug` 的话，修复 `bug` 的代码请提交至 `develop`。

## 基础Hook:

- [x] useConfig：全局配置 `hook`。 @pengYYYYY 
- [x] useEmitEvent: @vnues  #177 (不推荐，事件参数类型不明确，建议直接使用 props.onXXX)
- [x] useDefault： 用于实现 `v-model`，内置受控和非受控处理。 @chaishi 
- [x] useVModel： 用于实现 `v-model:xxx`，内置受控和非受控处理。 @chaishi 
- [x] useTNode:  用于在 `setup` 组合 `TNode`，`render` 函数渲染 `TNode` 请使用 `renderTNodeJSX`。 @pengYYYYY 
- [x] useChildComponentSlots：渲染 `default slot`，获取子组件 `VNode`。处理多种子组件创建场景。
- [x] useIcon: 多种icon的render方式  @vnues 
- [x] useVirtualScroll @Louiszhai

## 组件

- [x] `alert` 组件 `renderIcon` 与 `renderClose`  用 `useIcon` 抽离 

### `provider` 与 `inject`

`providerKey` 统一使用组件名, `provider` 内容请不要直接将整个父组件往下透传，按需透传，保持逻辑清晰，定义TS接口。

最重要的一点，避免 `optionsAPI` 照搬到 `compostionAPI`, `setup` 应该是简单清晰的

### 插槽逻辑组合

请注意不要在做逻辑组合的时候 `render slot function`，`slot function` 应该是在 `render` 过程中被执行的。

## Wiki

建议在重构时做组件逻辑图，可写下你对组件逻辑的思想到 `discussions` 或 `issue`，并关联此 `issue` 。完整成熟后会放到项目 `wiki` 中。

**Comment by vnues** [comment]
目前要处理兼容emitEvent函数，因为组件文档写了兼容@change和:onChange这种事件的写法

**Comment by vnues** [comment]
目前`renderTNode`只是针对于选项式api的，组合式api可以考虑加一个`useRenderTNode`Hook

**Comment by pengYYYYY** [comment]
> useRenderTNode

好的

**Comment by chaishi** [comment]
> 目前要处理兼容emitEvent函数，因为组件文档写了兼容@change和:onChange这种事件的写法

⚠️ 注意，Vue3 不需要任何的 emitEvent 函数，直接执行 `props.onChange?.(xxx)` 即可，会自动支持到 `@change` 和 `:onChange` ⚠️

**Comment by pengYYYYY** [comment]
issue关闭，重构进入收尾阶段内容挂到 #58
