### ISSUE TITLE
[所有组件] 针对 webstorm 缺少组件属性以及插槽名称提示

### ISSUE THREAD

**Issue by wanghan-js** [Tencent/tdesign-vue-next#1617]
### 这个功能解决了什么问题

解决了：针对 webstorm 用户，在使用 TDesign 组件时，无法获得组件属性、以及组件插槽名称提示的问题

### 你建议的方案是什么

编写类型文件给 webstorm 解析

**Comment by 107236074** [comment]
idea编辑器同样的问题 提示无法识别的插槽

**Comment by tolking** [comment]
我之前写了工具[components-helper](https://github.com/tolking/components-helper)，是通过解析文档生成相关代码提示文件。
我大致看了下组件文档，其中组件属性和事件是支持的。插槽不支持（无相关文档）

如果需要我可以完成这个

**Comment by yarnk** [comment]
的确挺难受的，特别是升级到 2022.2+完全没提示了
