### ISSUE TITLE
[Form，Table] 用form表单嵌套table时使用时间选择器和日期选择器会出现莫名情况的悬浮窗

### ISSUE THREAD

**Issue by Marrygang** [Tencent/tdesign-vue-next#1622]
### TDesign 版本 0.20.2

0.20.2

### 重现步骤

发现了一个神奇的现象，我再做这个可编辑的表格时，t5时使用了date-picker，随后就发现了如图片所示现象，除了范围选择器不会产生悬浮框，其他例如日期选择器，时间选择器都睡产生这种现象，现在很尴尬，虽然table表格有可编辑功能，但是不满足需求，用这种方法就会出现这种莫名其妙的情况

<template>
  <div class="form-common-container">
    <t-form ref="form" :data="formData" :label-width="90" colon :rules="rules" @reset="onReset" @submit="onSubmit">
      <t-card title="表单信息" :bordered="false">
        <template #actions>
          <a href="javascript:void(0)" @click="router.back()">返回</a>
        </template>
        <t-row :gutter="[16, 24]">
          <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
            <t-form-item label="表单输入" name="s1">
              <t-input v-model="formData.s1" />
            </t-form-item>
          </t-col>
          <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
            <t-form-item label="表单选择" name="s2">
              <t-select v-model="formData.s2" :options="STATUS_OPTIONS" />
            </t-form-item>
          </t-col>
          <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
            <t-form-item label="表单日期" name="s3">
              <t-date-range-picker v-model="formData.s3" clearable />
            </t-form-item>
          </t-col>
          <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
            <t-form-item label="表单数字" name="s4">
              <t-input-number v-model="formData.s4" theme="normal" :min="0" style="width: 100%" />
            </t-form-item>
          </t-col>
          <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
            <t-form-item label="表单输入" name="s5">
              <t-input v-model="formData.s5" type="search" />
            </t-form-item>
          </t-col>
          <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
            <t-form-item label="表单多项选择" name="s6" :label-width="120">
              <t-select v-model="formData.s6" :options="STATUS_OPTIONS" :min-collapsed-num="2" multiple />
            </t-form-item>
          </t-col>
          <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
            <t-form-item label="表单日期" name="s7">
              <t-date-picker v-model="formData.s7" />
            </t-form-item>
          </t-col>

          <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
            <t-form-item label="表单数字" name="s8">
              <t-input-number v-model="formData.s8" theme="normal" :min="0" style="width: 100%" />
            </t-form-item>
          </t-col>
          <t-col :span="12">
            <t-form-item label="表单上传" name="s9"> </t-form-item>
          </t-col>
          <t-col :span="12">
            <t-form-item label="表单文本" name="s10">
              <t-textarea v-model="formData.s10" />
            </t-form-item>
          </t-col>
        </t-row>
      </t-card>
      <t-card style="margin-top: 20px" title="编辑表格" :bordered="false">
        <t-space>
          <t-button theme="primary" @click="handleClickAddRow">新增</t-button>
        </t-space>
        <t-form-item :label-width="0" name="s11">
          <t-form ref="form" :data="formData" :label-width="0" colon :rules="rules">
            <t-table
              class="edit-table"
              stripe
              bordered
              row-key="index"
              vertical-align="middle"
              :data="formData.s11"
              :columns="columns"
              :loading="false"
              :header-affixed-top="false"
            >
              <template #t1="{ row, rowIndex }">
                <t-form-item :name="'s11.' + rowIndex + '.t1'">
                  <t-input v-model="row.t1" />
                </t-form-item>
              </template>
              <template #t2="{ row, rowIndex }">
                <t-form-item :name="'s11.' + rowIndex + '.t2'">
                  <t-input v-model="row.t2" />
                </t-form-item>
              </template>
              <template #t3="{ row, rowIndex }">
                <t-form-item :name="'s11.' + rowIndex + '.t3'">
                  <t-select v-model="row.t3" :options="STATUS_OPTIONS" />
                </t-form-item>
              </template>
              <template #t4="{ row, rowIndex }">
                <t-form-item :name="'s11.' + rowIndex + '.t4'">
                  <t-select v-model="row.t3" :options="STATUS_OPTIONS" />
                </t-form-item>
              </template>
              <template #t5="{ row, rowIndex }">
                <t-form-item :name="'s11.' + rowIndex + '.t5'">
                  <t-date-range-picker v-model="row.t5" />
                </t-form-item>
              </template>
              <template #op="slotProps">
                <a>编辑</a>
                <t-divider layout="vertical" />
                <a>删除</a>
              </template>
            </t-table>
          </t-form>
        </t-form-item>
      </t-card>
    </t-form>
  </div>
</template>

<script lang="ts">
export default {
  name: 'SingleModuleForm',
};
</script>

<script setup lang="ts">
import { STATUS, STATUS_OPTIONS } from '@/constants';
import router from '@/router';
import { ref } from 'vue';
// 定义表单项
const formData = ref({
  s1: null,
  s2: null,
  s3: [],
  s4: null,
  s5: null,
  s6: null,
  s7: null,
  s8: null,
  s9: [],
  s10: null,
  s11: [],
});

// 定义校验规则
const rules = {
  s1: [{ required: true, message: '请输入' }],
  s2: [{ required: true, message: '请选择' }],
  s3: [{ required: true, message: '请选择' }],
  s4: [{ required: true, message: '请输入' }],
  s5: [{ required: true, message: '请输入' }],
  s6: [{ required: true, message: '请选择' }],
  s7: [{ required: true, message: '请选择' }],
  s8: [{ required: true, message: '请输入' }],
  s9: [{ required: true, message: '请上传' }],
  s10: [{ required: true, message: '请输入' }],
  t1: [{ required: true, message: '请输入' }],
};

// 定义表格列
const columns = [
  {
    title: '列一',
    ellipsis: true,
    align: 'center',
    colKey: 't1',
  },
  {
    title: '列二',
    align: 'center',
    ellipsis: true,
    colKey: 't2',
  },
  {
    title: '列三',
    align: 'center',
    ellipsis: true,
    colKey: 't3',
  },
  {
    title: '列四',
    align: 'center',
    ellipsis: true,
    colKey: 't4',
  },
  {
    title: '列五',
    align: 'center',
    ellipsis: true,
    colKey: 't5',
  },
  {
    title: '列六',
    align: 'center',
    ellipsis: true,
    colKey: 't6',
  },
  {
    align: 'center',
    fixed: 'right',
    width: 150,
    colKey: 'op',
    title: '操作',
  },
];

// 新增编辑表单行
const handleClickAddRow = () => {
  formData.value.s11.push({
    t1: null,
    t2: null,
    t3: null,
    t4: null,
    t5: [],
    t6: null,
  });
};

// 重置表单
const onReset = () => {};

// 提交表单
const onSubmit = () => {};
</script>

<style lang="less" scoped>
@import '@/style/variables.less';
@import '@/style/form.less';
</style>

![image](https://user-images.githubusercontent.com/53104549/188806539-1836706d-1483-4924-802c-a8f391d2b421.png)
![image](https://user-images.githubusercontent.com/53104549/188807486-9f94ee91-8995-405a-abdd-980f5a75e69a.png)

### 期望结果

那个悬浮框不知道怎么出现的，希望可以变正常

**Comment by Marrygang** [comment]
> ### TDesign 版本 0.20.2
> 0.20.2
> 
> ### 重现链接
> _No response_
> 
> ### 重现步骤
> 发现了一个神奇的现象，我再做这个可编辑的表格时，t5时使用了date-picker，随后就发现了如图片所示现象，除了范围选择器不会产生悬浮框，其他例如日期选择器，时间选择器都睡产生这种现象，现在很尴尬，如果没法解决只能换框架了啊啊啊
> 
> 返回
> ```
>       <t-col :xs="12" :sm="6" :md="6" :lg="4" :xl="3">
>         <t-form-item label="表单数字" name="s8">
>           <t-input-number v-model="formData.s8" theme="normal" :min="0" style="width: 100%" />
>         </t-form-item>
>       </t-col>
>       <t-col :span="12">
>         <t-form-item label="表单上传" name="s9"> </t-form-item>
>       </t-col>
>       <t-col :span="12">
>         <t-form-item label="表单文本" name="s10">
>           <t-textarea v-model="formData.s10" />
>         </t-form-item>
>       </t-col>
>     </t-row>
>   </t-card>
>   <t-card style="margin-top: 20px" title="编辑表格" :bordered="false">
>     <t-space>
>       <t-button theme="primary" @click="handleClickAddRow">新增</t-button>
>     </t-space>
>     <t-form-item :label-width="0" name="s11">
>       <t-form ref="form" :data="formData" :label-width="0" colon :rules="rules">
>         <t-table
>           class="edit-table"
>           stripe
>           bordered
>           row-key="index"
>           vertical-align="middle"
>           :data="formData.s11"
>           :columns="columns"
>           :loading="false"
>           :header-affixed-top="false"
>         >
>           <template #t1="{ row, rowIndex }">
>             <t-form-item :name="'s11.' + rowIndex + '.t1'">
>               <t-input v-model="row.t1" />
>             </t-form-item>
>           </template>
>           <template #t2="{ row, rowIndex }">
>             <t-form-item :name="'s11.' + rowIndex + '.t2'">
>               <t-input v-model="row.t2" />
>             </t-form-item>
>           </template>
>           <template #t3="{ row, rowIndex }">
>             <t-form-item :name="'s11.' + rowIndex + '.t3'">
>               <t-select v-model="row.t3" :options="STATUS_OPTIONS" />
>             </t-form-item>
>           </template>
>           <template #t4="{ row, rowIndex }">
>             <t-form-item :name="'s11.' + rowIndex + '.t4'">
>               <t-select v-model="row.t3" :options="STATUS_OPTIONS" />
>             </t-form-item>
>           </template>
>           <template #t5="{ row, rowIndex }">
>             <t-form-item :name="'s11.' + rowIndex + '.t5'">
>               <t-date-range-picker v-model="row.t5" />
>             </t-form-item>
>           </template>
>           <template #op="slotProps">
>             <a>编辑</a>
>             <t-divider layout="vertical" />
>             <a>删除</a>
>           </template>
>         </t-table>
>       </t-form>
>     </t-form-item>
>   </t-card>
> </t-form>
> ```
> 
> <script lang="ts"> export default { name: 'SingleModuleForm', }; </script> <script setup lang="ts"> import { STATUS, STATUS_OPTIONS } from '@/constants'; import router from '@/router'; import { ref } from 'vue'; // 定义表单项 const formData = ref({ s1: null, s2: null, s3: [], s4: null, s5: null, s6: null, s7: null, s8: null, s9: [], s10: null, s11: [], }); // 定义校验规则 const rules = { s1: [{ required: true, message: '请输入' }], s2: [{ required: true, message: '请选择' }], s3: [{ required: true, message: '请选择' }], s4: [{ required: true, message: '请输入' }], s5: [{ required: true, message: '请输入' }], s6: [{ required: true, message: '请选择' }], s7: [{ required: true, message: '请选择' }], s8: [{ required: true, message: '请输入' }], s9: [{ required: true, message: '请上传' }], s10: [{ required: true, message: '请输入' }], t1: [{ required: true, message: '请输入' }], }; // 定义表格列 const columns = [ { title: '列一', ellipsis: true, align: 'center', colKey: 't1', }, { title: '列二', align: 'center', ellipsis: true, colKey: 't2', }, { title: '列三', align: 'center', ellipsis: true, colKey: 't3', }, { title: '列四', align: 'center', ellipsis: true, colKey: 't4', }, { title: '列五', align: 'center', ellipsis: true, colKey: 't5', }, { title: '列六', align: 'center', ellipsis: true, colKey: 't6', }, { align: 'center', fixed: 'right', width: 150, colKey: 'op', title: '操作', }, ]; // 新增编辑表单行 const handleClickAddRow = () => { formData.value.s11.push({ t1: null, t2: null, t3: null, t4: null, t5: [], t6: null, }); }; // 重置表单 const onReset = () => {}; // 提交表单 const onSubmit = () => {}; </script> <style lang="less" scoped> @import '@/style/variables.less'; @import '@/style/form.less'; </style>
> ![image](https://user-images.githubusercontent.com/53104549/188806539-1836706d-1483-4924-802c-a8f391d2b421.png) ![image](https://user-images.githubusercontent.com/53104549/188807486-9f94ee91-8995-405a-abdd-980f5a75e69a.png)
> 
> ### 期望结果
> 那个悬浮框不知道怎么出现的，希望可以变正常
> 
> ### 实际结果
> _No response_
> 
> ### 框架版本
> _No response_
> 
> ### 浏览器版本
> _No response_
> 
> ### 系统版本
> _No response_
> 
> ### Node版本
> _No response_
> 
> ### 补充说明
> _No response_

**Comment by chaishi** [comment]
这个应该是因为你是设置了 `ellipsis: true`，超出省略，从截图来看，输入框已经超出
