### ISSUE TITLE
[Table] className 属性设置无效

### ISSUE THREAD

**Issue by ojhaywood** [Tencent/tdesign-vue-next#1626]
### tdesign-vue-next 版本

0.20.5

### 重现链接

https://stackblitz.com/edit/angular-gmohtt?file=src%2Fdemo.vue

### 重现步骤

添加 className 无效

### 期望结果

class 生效

### 实际结果

class 不生效

### 框架版本

Vue(3.2.37)

### 浏览器版本

Chrome(104.0.5112.101 arm64)

### 系统版本

MacOS(12.5.1)

### Node版本

16.15.1

**Comment by chaishi** [comment]
官网看着是有效的

<img width="955" alt="image" src="https://user-images.githubusercontent.com/11605702/188843253-c9baab0a-7256-4783-acaf-40a785e03fca.png">

**Comment by chaishi** [comment]
https://stackblitz.com/edit/angular-gmohtt?file=src%2Fdemo.vue
你提供的链接也是有效的
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/11605702/188843548-ed9c5d2f-e23c-43eb-bd56-d6250f86b0d2.png">

**Comment by chaishi** [comment]
这个特性很早很早就支持了
