### ISSUE TITLE
[Table] column-controller取消全选会导致禁用的列选中

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1631]
### tdesign-vue-next 版本

0.20.5

### 重现链接

https://stackblitz.com/edit/angular-w94n7v?file=src%2Fdemo.vue

### 重现步骤

[Dcfonb-forked---StackBlitz.webm](https://user-images.githubusercontent.com/19343340/188926226-1d30c0c6-ae4a-4823-9154-034669c2e651.webm)

**Comment by hkaikai** [comment]
查询选择展示的列后。列宽也有点问题

**Comment by chaishi** [comment]
>重新选择展示的列后。列宽也有点问题

描述有些宽泛，不知需要做些什么

**Comment by chaishi** [comment]
示例代码版本号：`"tdesign-vue-next": "0.20.5"`

最新版本：`0.22.1` 表现，由于「序号」不能参与显示控制，因此「序号」默认选中，默认显示，符合预期。

请升级版本号

**Comment by hkaikai** [comment]
> 示例代码版本号：`"tdesign-vue-next": "0.20.5"`
> 
> 最新版本：`0.22.1` 表现，由于「序号」不能参与显示控制，因此「序号」默认选中，默认显示，符合预期。
> 
> 请升级版本号，解决问题。
> 
> <img alt="image" width="1155" src="https://user-images.githubusercontent.com/11605702/192282240-e0c1109c-88cd-4422-89b2-f8a0a1c0a8ab.png">

序号也是代码里面设置的一列，并不是组件的默认序号，第一次打开就是没有选中的，点击全选后，禁止的序号复选框被选中了

**Comment by hkaikai** [comment]
https://stackblitz.com/edit/angular-w94n7v-a43c5x?file=src%2Fdemo.vue

第一次打开情况
![image](https://user-images.githubusercontent.com/19343340/192989026-9bc0616e-dd12-4aea-8941-254714d9c1c1.png)

点击全选后
![image](https://user-images.githubusercontent.com/19343340/192989176-efff8c04-2bac-4b37-8ff7-2cfbc24533c9.png)
