### ISSUE TITLE
Select 选择器bug（可过滤的选择器与远程搜索选择器）

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#164]
## 1.可过滤的选择器与远程搜索选择器

- [ ] 下拉框需要双击背景才能关闭
- [ ] 打开一个下拉框时，再选中另外一个select选择器不会关闭之前的下拉框

## 2.可创建新条目的选择器，演示代码有问题
![image](https://user-images.githubusercontent.com/30982989/148650879-81ffd00a-afa7-4134-ac27-6d0564d04382.png)
由于value是可被监听的对象，当改变了value值时，之前push到数组中的对象的值会跟着改变

**就像这样**

![image](https://user-images.githubusercontent.com/30982989/148650917-ee03b8b5-277b-46e1-84dd-615e604b9178.png)

**Comment by pengYYYYY** [comment]
收到

**Comment by pengYYYYY** [comment]
两次点击的问题后续会统一处理
