### ISSUE TITLE
[Switch] 允许 value 默认值为 undefined

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1645]
### tdesign-vue-next 版本

0.20.5

### 重现步骤

<img width="622" alt="image" src="https://user-images.githubusercontent.com/11605702/189312266-1afee27b-9447-408d-94b2-85f094b931bf.png">

**Comment by pengYYYYY** [comment]
https://stackblitz.com/edit/angular-9fdc3d?file=src%2Fdemo.vue

暂未发现此问题
