### ISSUE TITLE
[Select ] 选项返回值类型返回布尔时报错

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#1651]
### tdesign-vue-next 版本

0.20.5

### 重现步骤

![image](https://user-images.githubusercontent.com/46079969/189811261-1daad6d1-ac7b-466d-891f-d4535c547a6f.png)

**Comment by pengYYYYY** [comment]
不支持布尔值，如果是布尔值用checkbox这种组件
