### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by sizq-it** [Tencent/tdesign-vue-next#1652]
### tdesign-vue-next-starter 版本

0.20.5

### 重现步骤

![image](https://user-images.githubusercontent.com/95328416/189031710-45184bcc-75ba-4d45-8ab1-93f3902e4aaf.png)

![image](https://user-images.githubusercontent.com/95328416/189031738-68a4dcfc-de1a-42b2-a3f3-cf65cd6cdda8.png)

当有滚动条是下面的拖拽有个框

### 期望结果

失望在有滚动条时，哪个缩放的东西没有外边距或者可调节

**Comment by uyarn** [comment]
@sizq-it 没看懂问题 麻烦再描述一下..

**Comment by pengYYYYY** [comment]
属于滚动条的正常表现
