### ISSUE TITLE
[table] 树形表格，数据渲染有问题

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#1653]
### tdesign-vue-next 版本

0.20.5

### 重现步骤

[新建文本文档.txt](https://github.com/Tencent/tdesign-vue-next/files/9554093/default.txt)
附上代码
不清楚这个问题存在多久了，当我修改的时候并不会时时渲染
![image](https://user-images.githubusercontent.com/101392056/189825367-6af77902-1911-4838-aa49-7135f62cc36b.png)
当我点击修改之后，页面没有变化，而当我新增的时候发现页面更新了，而且之前的修改也带上了，
但是这时候控制台出现了报错
![image](https://user-images.githubusercontent.com/101392056/189825834-cbfa9aad-3653-4aec-b616-2b34feea5efa.png)
但是我也指定rowKey了，而且没有重复的key存在

**Comment by chaishi** [comment]
短期内，请参考官方文档，使用 `resetData` 更新表格数据，而非感官上的 `.push`

<img width="821" alt="image" src="https://user-images.githubusercontent.com/11605702/192196604-cc1e7ac6-84e2-4b6f-bcf2-36a39a06f2f2.png">

**Comment by freeopsvue** [comment]
期待只要用这个方法就能直接更新表格数据，不需要再去判断id是否变化了。
更期待直接改变绑定的数据就行，不需要再用这个方法。

**Comment by chaishi** [comment]
https://stackblitz.com/edit/angular-gjyury?file=package.json,src%2Fdemo.vue
尝试了一下，在最新版本 `v0.24.9` 中，已经支持 `data.push` 更新数据

**Comment by chaishi** [comment]
关于数据编辑，默认支持这种写法 `data.value[1].a = 233;` 意味着数据的 deep 监听，将不会支持，在框架变更之前，也永久不会支持。
请更为使用 `table.value.setData(row.key, newData);` ，类似 Vue2 的 `this.$set(data, xx, xx )`

**Comment by chaishi** [comment]
文本描述 和 示例代码，提到的相关问题，均已回复，支持的已支持，不支持的已说明原因。issue 关闭

若还有其他疑惑，可再单独提 issue
