### ISSUE TITLE
[Tree] 必须要打开checkable属性才能够高亮显示树节点，但checkable打开后必有节点复选框

### ISSUE THREAD

**Issue by centmaster** [Tencent/tdesign-vue-next#1654]
### tdesign-vue-next 版本

0.20.5

### 重现步骤

checkable这个变量关联了两个事情。1.输入的选中态是否需要被选中（树中的value属性） 2.是否需要复选框

复现步骤：不改变选中值及所有树参数的情况下，增加checkable=true就可以有选中态了，但同时也有了复选框

### 期望结果

期望具备选中态效果，但不需要复选框

解耦选中态和复选框

### 实际结果

增加checkable=true就可以有选中态了，但同时也有了复选框

**Comment by pengYYYYY** [comment]
选中态和checkable就是强关联的，可以用actived来控制单选情况下的高亮

**Comment by pengYYYYY** [comment]
展开用expanded

**Comment by pengYYYYY** [comment]
value 为选中值，expanded 为展开节点值，actived 为高亮值，分别承担不同的角色
