### ISSUE TITLE
[Transfer] 希望穿梭框可以绑定对象值

### ISSUE THREAD

**Issue by yangyuexiong** [Tencent/tdesign-vue-next#1658]
### 这个功能解决了什么问题

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/26624465/189906417-82745fab-f092-4f8f-a145-9c85b6b3e022.png">
可以拓展其他参数提交给后端，而不仅仅是id

### 你建议的方案是什么

穿梭框可以绑定对象值，拓展其他参数，而不仅仅是id值

**Comment by pengYYYYY** [comment]
value 为对象值？

**Comment by yangyuexiong** [comment]
<img width="814" alt="image" src="https://user-images.githubusercontent.com/26624465/190336721-2bf2da3a-a284-459f-880f-d79479231820.png">

**Comment by pengYYYYY** [comment]
这个对象的数据可以通过id自行映射到呀

**Comment by yangyuexiong** [comment]
希望这样的数据格式：[{},{},{}]  进行数据交互，而不是我通过组装生成： {id:{}}

**Comment by pengYYYYY** [comment]
了解了，这个需求移到需求列表，暂时没有预期的支持时间

**Comment by NetFreeOps** [comment]
两年了，没人管
