### ISSUE TITLE
[Select] clear 清除操作，当前会设置 value 为空字符串，不符合预期

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1678]
### tdesign-vue-next 版本

0.21.0

### 重现步骤

clear 清除操作，当前会设置 value 为空字符串，如果 value 本身是 number 类型，就会面临数据类型被转换的问题

期望：单选场景，清空操作，设置 value 为 `undefined`。多选场景，清空操作设置 value 为 `[]`

**Comment by linzcity** [comment]
@PengYYYYY 你好，对于select下拉组件来说，clearable选项，是不是恢复成初始值更合理，比如初始值是null，如果恢复成""或者undefined，感觉都不太准确。最好给个配置，如" initial | null | undefined | '' "能让开发者自由选择
