### ISSUE TITLE
[Select] 使用插槽功能，无法回显

### ISSUE THREAD

**Issue by dianjie** [Tencent/tdesign-vue-next#1679]
### tdesign-vue-next 版本

0.21.0

### 重现链接

https://tdesign.tencent.com/vue-next/components/select

### 重现步骤

![image](https://user-images.githubusercontent.com/16601627/190544353-ca1caa5d-2f96-436a-8b14-4fd252c81bab.png)

另prefixIcon前缀图标，建议和input组件一样，组件内自动加间距，不用自己加style

```vue
<template #prefixIcon>
      <icon name="browse" style="margin-right: 8px" />
</template>
```

**Comment by pengYYYYY** [comment]
无法回显是？

**Comment by dianjie** [comment]
@pengYYYYY 选择Orange，select的input显示placeholder请选择，而不是Orange
