### ISSUE TITLE
[t-rate] 居然不支持四舍五入算半星

### ISSUE THREAD

**Issue by yarnk** [Tencent/tdesign-vue-next#1683]
### tdesign-vue-next 版本

0.21.0

### 补充说明

建议升级星小数点算法并支持string类型传入

**Comment by HQ-Lin** [comment]
不理解为何要支持string，难道还要支持 “四点五” 这种中文转化阿拉伯数字的需求？

**Comment by Yilun-Sun** [comment]
你是想要 3.9 算 4 星吗？
如果想要同时支持四舍五入和半星，那会有冲突的吧。3.6 四舍五入算 4，但是又想要半星，但是它又不可能 ”四舍五入“ 到 3.5。
还是说你想要 3.6 ”四舍五入“ 到 3.5？

而且显示的话只有整星和半星这种。如果想要做四舍五入的操作，建议直接在传入数值之前做处理。

**Comment by HQ-Lin** [comment]
星星只有 `0` `0.5` `1` 三种形态，传给组件 0.6 什么的也没有规范说要变成 0.5，具体要多少交给业务自行决定，你觉得 0.6 属于半星那就转成0.5 再给组件，你觉得是1 那就转成0.6再给组件
