### ISSUE TITLE
[TimePicker] 无法选择23:59:59

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#1693]
### tdesign-vue-next 版本

0.22.0

### 重现步骤

https://user-images.githubusercontent.com/30982989/190914799-25846457-a5dd-43dd-a72f-2ada4dfd7391.mp4

### 浏览器版本

Google Chrome 104.0.5112.81

### 系统版本

版本	Windows 10 专业版
版本号	21H1
安装日期	‎2021/‎5/‎29
操作系统内部版本	19043.1826
体验	Windows Feature Experience Pack 120.2212.4180.0

**Comment by uyarn** [comment]
windows上使用有缺陷 本周版本修复

**Comment by uyarn** [comment]
@yixiaco 有其他什么配置吗 或者鼠标有什么特殊的吗.. 我这边用windows没出现这个情况 但是确实这几天有人反馈.. （视频是滚动操作 点击也测试过了

https://user-images.githubusercontent.com/26377630/191174322-b727329c-2bf5-4229-9986-1b930cab57ef.mov

**Comment by yixiaco** [comment]
> @yixiaco 有其他什么配置吗 或者鼠标有什么特殊的吗.. 我这边用windows没出现这个情况 但是确实这几天有人反馈.. （视频是滚动操作 点击也测试过了
> 
>  Screen.Recording.2022-09-20.at.1.21.36.PM.mov

鼠标是联想小新无线鼠标

**Comment by uyarn** [comment]
@yixiaco 能不能帮忙double check 一下现在你的设备是不是正常的效果
https://preview-pr1711-tdesign-vue-next.surge.sh/vue-next/components/time-picker

**Comment by yixiaco** [comment]
> @yixiaco 能不能帮忙double check 一下现在你的设备是不是正常的效果 https://preview-pr1711-tdesign-vue-next.surge.sh/vue-next/components/time-picker

我回去才能看，公司的电脑也是正常的，晚点回复你

**Comment by yixiaco** [comment]
> @yixiaco 能不能帮忙double check 一下现在你的设备是不是正常的效果 https://preview-pr1711-tdesign-vue-next.surge.sh/vue-next/components/time-picker

可以了，能够正常操作👏

**Comment by uyarn** [comment]
fixed 0.22.1
