### ISSUE TITLE
[table 表格] 单元格样式

### ISSUE THREAD

**Issue by jamespatriot** [Tencent/tdesign-vue-next#1696]
### 这个功能解决了什么问题

能够动态修改单元格的样式，如背景色..

### 你建议的方案是什么

BaseTableCol 添加 cellClass,或者 cellAttrs 属性，支持string ,object,function.

**Comment by chaishi** [comment]
关于类名，有一个列属性，叫：`className`，column.className，参数有 `{ row, rowIndex, col, colIndex }`，可以自由配置任意列，任意单元格的类名，可以先用着。

关于属性，也有一个列属性 `attrs`，column.attrs，暂不支持 function，已支持 string, object，后续支持 function。

短期内，使用 rowClassName + column.className 可以解决关于类名样式的全部需求。属性的话，再等等

**Comment by chaishi** [comment]
已在 v0.24.0 中处理，建议使用更新版本
