### ISSUE TITLE
input 组件使用v-model.trim会将内容清空Bug

### ISSUE THREAD

**Issue by zhairy** [Tencent/tdesign-vue-next#1699]
### 重现链接
https://stackblitz.com/edit/angular-ftdg2p?file=src%2Fdemo.vue

### 重现步骤
再组件的v-model上使用trim  将会造成input 内容被清空

### 期望结果
v-model.trim在使用频率上还是比较常用的，例如在用户登录 ，表单提交，搜索等地方都是需要将用户输入的内容去掉首尾空 防止后台验证不了数据

### 实际结果
已在vue3中使用原生input 测试，该bug 为组件bug

| Environment | Info |
|---|---|
| 相关版本 | 0.21.1 |
| 框架版本 / 基础库版本 | vue^3.2.31 |
| 系统、浏览器 | Microsoft Edge 版本 105.0.1343.33 (正式版本) (64 位) |
| Node版本 |  |

**Comment by zhangpaopao0609** [comment]
<img width="623" alt="image" src="https://user-images.githubusercontent.com/44194929/191411195-89481ab4-5f7e-4f11-8795-0e14f347e655.png">

**Comment by zhangpaopao0609** [comment]
> 分析一下这个问题
> 
> ### 造成的原因
> 下图为 `vue` 处理 `trim` 修饰符的过程，即在 `emit` 时直接对所传参数 `rawArgs` 依次调用 `trim()` 函数来实现功能 <img alt="image" width="360" src="https://user-images.githubusercontent.com/44194929/191412148-1f446e35-2e9f-4b4e-a157-4cbd9facd5ea.png">
> 
> 在我们的 `useVmodel` 中，当改变受控数据时，会直接调用 `emit` 函数并且接收参数，如下： <img alt="image" width="600" src="https://user-images.githubusercontent.com/44194929/191412861-ea79d14a-c13a-4141-a500-a6b11a09fc74.png">
> 
> 因此，当用户使用 `v-mode.trim` 时，此时数据受控，当调用 `setXX` 函数改变数据时会触发 `emit` 函数并传递参数，假如此时传递的参数不兼容 `trim()`，就会报错 <img alt="image" width="360" src="https://user-images.githubusercontent.com/44194929/191413145-a2ea43c0-ac17-46de-9e94-3b0cafe413cb.png">
> 
> 以上就是问题出现的原因
> 
> ### 如何解决
> #### 解决方式 1
> `useVmodel` 做兼容，当使用了 `trim` 修饰符时，对传递的参数做处理
> 
> #### 解决方式 2
> `vue` 底层做兼容（我打算先给 vue 提个 issue，看能不能搞个 pr 😄）

完了，我这真实版丢人现眼，^_^^_^

上面的解决方式都不完全符合我们的设计，符合我们设计的解决方案应该是：
- 删除 `emit('update:xxxx', newValue)` 后面的所有参数，因为在受控场景下，监听的函数 `update:xxx` 仅接收一个参数，其它的参数本身就冗余了，所以删除其它参数即可
> 当然， `vue` 底层我个人觉得还是应该要做兼容的 https://github.com/vuejs/core/issues/6711
