### ISSUE TITLE
[Table] 列配置BaseTableCol类型声明中缺少sorter属性

### ISSUE THREAD

**Issue by HHaoWang** [Tencent/tdesign-vue-next#1700]
### tdesign-vue-next 版本

0.22.0

### 重现步骤

在创建列配置数组时以Typescript方式创建：
```
const columns: Array<BaseTableCol<PassageResult>> = [
{
    colKey: "id",
    title: "#",
    sorter: true,
  },
]
```
由于table的type文件中BaseTableCol类型并未包含sorter属性，会导致IDE报错

### 期望结果

IDE能够识别sorter属性不报错

### 实际结果

IDE未能识别sorter属性导致报错

### 框架版本

Vue(3.2.37)

### 浏览器版本

Edge(105.0.1343.42)

### 系统版本

Windows10

### Node版本

16.15.1

**Comment by chaishi** [comment]
BaseTable 没有排序功能，故而没有 `sorter`


<img width="966" alt="image" src="https://user-images.githubusercontent.com/11605702/191036316-686610eb-5a7f-4fd8-9d54-76422fe8709e.png">
