### ISSUE TITLE
[Table]属性表格渲染错误

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#1702]
### tdesign-vue-next 版本

0.22.0

### 重现步骤

树形表格配置 column-controller 属性后无法渲染，

### 实际结果

希望和之前的版本一样可以渲染

**Comment by chaishi** [comment]
`column-controller` 我这边近期刚刚也在使用树形表格，没有遇到列配置问题。

再有，问题描述实在是太少，我们不是神仙，也无法拥有你的思想，辛苦提供可以完整复现问题的示例代码，否则将无法解决问题。时间到期，issue 关闭

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/1565

请设置 `displayColumns` 或者 `defaultDisplayColumns`，便会正常渲染设置的列

后期回更为默认显示全部列，当前是默认显示 `defaultDisplayColumns` 对应的列
