### ISSUE TITLE
[CollapsePanel] 文档中的content API代码中未实现

### ISSUE THREAD

**Issue by isanxia** [Tencent/tdesign-vue-next#1703]
### tdesign-vue-next 版本

最新版

### 重现步骤

<img width="912" alt="image" src="https://user-images.githubusercontent.com/18731832/191152484-ca0e3ca4-789e-443c-ac3f-4eeb1af29937.png">
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/18731832/191152690-4acd34b1-9311-41e0-a409-8d7ad120243c.png">

文档中描述content API和default用法一致，但代码中实际未实现content，只实现了default。

### 期望结果

将文档修改到和代码一致，避免误导。

**Comment by pengYYYYY** [comment]
有兴趣的话，可以实现一下，提PR

**Comment by isanxia** [comment]
> 有兴趣的话，可以实现一下，提PR，有一个useContent 的hook https://github.com/Tencent/tdesign-vue-next/blob/develop/src/hooks/tnode.ts

default与default哪个优先级高？

**Comment by pengYYYYY** [comment]
default
