### ISSUE TITLE
[tag] close 和 click 事件，当处理close的事件的时候，也触发了click事件

### ISSUE THREAD

**Issue by itzj86** [Tencent/tdesign-vue-next#1710]
### tdesign-vue-next 版本

0.21.1

### 重现步骤

// html
<Tag size="large" theme="success"
      v-for="(route,index) in props.routes" :key="index"
      @close.stop="close(index)"
      @click="topage(route.path)"
      :closable="true" class="nav-tag">
      {{route.meta.title}}
  </Tag>

// script 
const close = (index: number)=>{
     console.log(index)
}
 const topage = (path: string) => {
     console.log(path)
 }

### 期望结果

当点击关闭按钮的时候，输出索引index的值，而不是输出path的值
// console.log
output:  0

### 实际结果

实际上在点击close关闭按钮的时候，index和path都输出了。相当于close和click的事件都执行了。
// console.log
output: 0
output: /home

### 框架版本

Vue(3.2.37)

### 浏览器版本

Microsoft Edge(105.0.1343.33)

### 系统版本

windows 10

### Node版本

v14.18.1

**Comment by pengYYYYY** [comment]
有兴趣的话可以提个PR，
https://github.com/Tencent/tdesign-vue-next/blob/develop/src/tag/tag.tsx#L49
这一行加一个阻止冒泡

**Comment by itzj86** [comment]
可以的。




言嘚菋道
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Tencent/tdesign-vue-next"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月20日(星期二) 下午4:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Tencent/tdesign-vue-next] [tag] close 和 click 事件，当处理close的事件的时候，也触发了click事件 (Issue #1710)





 
有兴趣的话可以提个PR，
 https://github.com/Tencent/tdesign-vue-next/blob/develop/src/tag/tag.tsx#L49
 这一行加一个阻止冒泡
