### ISSUE TITLE
[Table] Table 数据刷新，但是选中数据异常

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#1722]
### tdesign-vue-next 版本

0.22.1

### 重现链接

https://stackblitz.com/edit/angular-einxnr-oyqkcw?file=src/demo.vue

### 重现步骤

改变Table的Data 数据，但是选中后的数据还是旧数据
![image](https://user-images.githubusercontent.com/20961979/191650107-8e7e4cbd-3c90-482d-a8a6-1d6f49ef1e1a.png)

### 期望结果

希望是新的的数据

### 实际结果

还是旧数据

**Comment by xiaosansiji** [comment]
已在 0.48.3 版本修复
