### ISSUE TITLE
[Guide] 样式问题

### ISSUE THREAD

**Issue by eugenewoody** [Tencent/tdesign-vue-next#1727]
### tdesign-vue-next 版本

Vue3 0_22_1

### 1.配图无圆角
·应为--td-radius-default
### 2.配图说明与操作按钮的间距不对
·应为24
<img width="430" alt="截屏2022-09-24 上午12 35 01" src="https://user-images.githubusercontent.com/103838357/192009537-c0f9ba58-1fe6-488d-8a07-6cdc33151983.png">
### 3.框选间距不对
·右侧间距为8
<img width="929" alt="截屏2022-09-24 上午12 27 42" src="https://user-images.githubusercontent.com/103838357/192008401-8a406411-f20e-49e4-aca3-d43a08678819.png">

**Comment by zhangpaopao0609** [comment]
处理中
