### ISSUE TITLE
[Loading] 默认zIndex不生效

### ISSUE THREAD

**Issue by wc19950724** [Tencent/tdesign-vue-next#1751]
### 重现链接
https://tdesign.tencent.com/vue-next/components/loading

### 重现步骤
Loading无默认z-index

### 期望结果
Loading默认z-index为：3500

### 实际结果
Loading无默认z-index

| Environment | Info |
|---|---|
| 相关版本 | 0.22.1 |
| 框架版本 / 基础库版本 | Vue(3.2.39) |
| 系统、浏览器 | Chrome(105.0.5195.127) |
| Node版本 | v16.17.0 |

**Comment by wc19950724** [comment]
> 
@uyarn 有劳确认一下问题

**Comment by uyarn** [comment]
@wc19950724  zIndex只在fullscreen的场景下生效 
refer to https://stackblitz.com/edit/angular-urhnzq?file=src%2Fdemo.vue

**Comment by wc19950724** [comment]
@uyarn 是否可支持任意场景都带有默认zIndex？
原因：Table组件的固定列 fixed 属性 会在 Loading 层级之上。此时不会需要 fullscreen

**Comment by uyarn** [comment]
@wc19950724 got it 
我们把这个API透传给这个场景使用 然后可以自己拿它设置一个高的层级 但是不给默认值了 这个场景给多少都不合适 具体场景具体设置。

**Comment by wc19950724** [comment]
@uyarn 好的，感谢耐心解答
