### ISSUE TITLE
[select] 多选select 点击option边缘无法选中

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1752]
### tdesign-vue-next 版本

0.22.1

### 重现步骤

https://user-images.githubusercontent.com/19343340/192478458-91e434d7-78f7-47a8-bebc-aef41e363f20.mp4

多选的 checkbox 跟选项区域有个 padding，确实点击到那里是没办法触发选中的

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-common/pull/928
