### ISSUE TITLE
[tree] 初次加载，value绑定选中值，父节点状态不正确

### ISSUE THREAD

**Issue by Reg1350** [Tencent/tdesign-vue-next#1754]
### tdesign-vue-next 版本

0.22.1

### 重现链接

https://stackblitz.com/edit/angular-xaletm?file=package.json

### 重现步骤

初次加载tree组件，value中选中所有子节点，父节点的状态显示不正确

### 期望结果

父节点显示选中

### 实际结果

父节点显示未选中

### 框架版本

3.2.37

### 浏览器版本

105.0.5195.127

### 系统版本

Windows

**Comment by yusongH** [comment]
是因为你配置了`checkStrictly`为`true` @Reg1350 

<img width="1874" alt="image" src="https://user-images.githubusercontent.com/45997005/192675062-2157b5da-0e05-43fc-b097-a9d367920968.png">
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/45997005/192675210-49ae63ca-0de2-4205-9423-f9fec32e65e3.png">

**Comment by Reg1350** [comment]
![企业微信截图_16643437725452](https://user-images.githubusercontent.com/36145541/192697107-b793572e-093f-4886-b2c6-41d11ed42f65.png)
改成false，没有效果，刷新后初次加载还是显示不正确。

**Comment by Reg1350** [comment]
![image](https://user-images.githubusercontent.com/36145541/192969395-6946da46-3191-4abb-934f-7289e75f26ef.png)
![企业微信截图_16644373447998](https://user-images.githubusercontent.com/36145541/192970741-e3665780-1381-47a4-9c7e-e1d6ecdb084e.png)
补充上这行代码后，效果达到预期
@pengYYYYY
