### ISSUE TITLE
【Cascader】全路径模式，子选项value相同时，无法显示正确的对应label

### ISSUE THREAD

**Issue by Prc-PY** [Tencent/tdesign-vue-next#1756]
【Cascader】全路径模式，子选项value相同时，无法显示正确的对应label
demo: https://stackblitz.com/edit/angular-pyewqv?file=src%2Fdemo.vue
![image](https://user-images.githubusercontent.com/64288053/192510833-f21d6e61-7325-48d8-bd78-1f7aa0d90eac.png)
![image](https://user-images.githubusercontent.com/64288053/192511039-e86ef47d-32f5-4e41-8148-88f1921c0ae0.png)

**Comment by pengYYYYY** [comment]
cascader 依赖的tree，tree的value需要全局唯一，这个问题优化需要等tree兼容支持不同路径的value可相同
