### ISSUE TITLE
[Select] 建议autoWidth属性的影响范围应该只在popup上面

### ISSUE THREAD

**Issue by jxwanglong** [Tencent/tdesign-vue-next#1757]
### 这个功能解决了什么问题
设置autoWidth之后，select触发器的宽度也变成自适应了，导致对周围的布局影响加大

### 你建议的方案是什么？
方案1：分开两个属性分别控制触发器和弹窗的宽度大小
方案2：autoWidth属性只影响弹窗的宽度，触发器的宽度可以由父组件通过样式来控制

**Comment by chaishi** [comment]
`autoWidth` 本身就是为了触发器的宽度存在，不是为了 下拉框，在部分业务场景下，特别是查询条件，都会希望触发器宽度自适应。

对于，下拉框宽度自适应，请参考官网文档：

https://tdesign.tencent.com/vue-next/components/select-input
<img width="675" alt="image" src="https://user-images.githubusercontent.com/11605702/192523481-f3d3b99e-012b-4be7-9539-ad4ce9ab79a8.png">

**Comment by chaishi** [comment]
下拉框宽度自适应代码如下：

https://stackblitz.com/edit/angular-wgqwg4?file=package.json,src%2Fdemo.vue

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/11605702/192523644-bb6f6742-3164-486e-9d4b-3f27253904c6.png">
