### ISSUE TITLE
[Table] 封装通用表单 行信息获取

### ISSUE THREAD

**Issue by bwensun** [Tencent/tdesign-vue-next#1759]
### 这个功能解决了什么问题

Table组件中，二次封装Table的时候
当使用插槽的方式渲染单元格，支持获取当前Table的所有行信息吗？希望可以将继续将row相关信息传递到父组件中，继续使用插槽来渲染

### 你建议的方案是什么

提供一个获取当前行信息的属性，方便继续传递

**Comment by bwensun** [comment]
传入cell渲染函数可以实现，但在想有没有别的方式

**Comment by chaishi** [comment]
这个问题直接透传 slots 到子组件即可，和组件库无关。不作深入处理，issue 关闭
