### ISSUE TITLE
[Pagination] total属性为0时current属性被重置为0

### ISSUE THREAD

**Issue by uncledrewzhaopeng** [Tencent/tdesign-vue-next#1766]
### tdesign-vue-next 版本

0.20.3

### 重现链接

https://stackblitz.com/edit/angular-tc9dug

### 框架版本

Vue(3.2.37)

### 系统版本

Windows11

### Node版本

16.15.1

**Comment by pengYYYYY** [comment]
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/35833812/196421970-202238bf-f449-44fb-b9a4-0b48b450a758.png">

对于特殊数据，组件侧难以处理到最完美，所以这种情况最好是自行做控制
