### ISSUE TITLE
[tableTree] 分页选中问题

### ISSUE THREAD

**Issue by zqmomotou** [Tencent/tdesign-vue-next#1777]
### 这个功能解决了什么问题

做TableTree 分页是，父子级联选中checked,在跳转的时候，组件报错useTreeSelect.tsx:134 Uncaught (in promise) TypeError: Cannot read property 'row' of undefined

 const children = get(state.row, rowDataKeys.value.childrenKey);

此时rowDataKeys把之前选中的给删除了

### 你建议的方案是什么

考虑下分页table data更新，重新渲染，object深拷贝问题

**Comment by chaishi** [comment]
https://stackblitz.com/run?file=src%2Fdemo.vue
在这个链接里面，复现一下你提到的问题，以便加快我们处理问题的进度

**Comment by chaishi** [comment]
长时间没有回复，如果超过 1 个月，自动关闭吧
