### ISSUE TITLE
dev package.json 文件中缺少 classnames 依赖

### ISSUE THREAD

**Issue by Jeffrey-mu** [Tencent/tdesign-vue-next#1779]
### tdesign-vue-next 版本

next

**Comment by pengYYYYY** [comment]
classnames 不是react的依赖吗？

**Comment by pengYYYYY** [comment]
为啥要依赖这个

**Comment by Jeffrey-mu** [comment]
tdesign-vue-next/src/upload/themes/multiple-flow-list.tsx 
这个文件内引用
![image](https://user-images.githubusercontent.com/66287770/192963154-ff33e9ba-b44f-4b4c-b8ed-0ab93507bb95.png)

**Comment by Jeffrey-mu** [comment]
使用pnpm安装的依赖
包管理工具配置原因？[hoist](https://pnpm.io/zh/npmrc#hoist)

**Comment by Jeffrey-mu** [comment]
使用npm安装依赖会安装calssnames README中可以添加包管理工具信息

**Comment by Jeffrey-mu** [comment]
工具问题 @pengYYYYY
