### ISSUE TITLE
[upload] 0.23.0版本以上 自定义上传方法下 无法拖拽上传

### ISSUE THREAD

**Issue by zhairy** [Tencent/tdesign-vue-next#1780]
### tdesign-vue-next 版本

0.23.0

### 重现链接

  https://stackblitz.com/edit/angular-njbv2n?file=src%2Fdemo.vue

### 重现步骤

 自定义上传 方法  ，单纯的添加draggable不能直接拖拽上传  ，拖拽失效 ，0.22.1,及以下没有这个问题，临时解决方法 是添加了 theme="custom" 这个属性之后就可以了

### 期望结果

额。。根据实际情况 修复吧

**Comment by chaishi** [comment]
链接打开看不到代码

**Comment by zhairy** [comment]
额、。。 我打开没问题的啊

**Comment by zhairy** [comment]
https://stackblitz.com/edit/angular-njbv2n-xcb9f2?file=src%2Fdemo.vue

**Comment by zhairy** [comment]
亲，用上面的链接试试吧  去掉里面的   theme="custom"

**Comment by zhairy** [comment]
@chaishi c
下面这个  是 我这边的代码复现

> 链接打开看不到代码


    <t-upload
      ref="uploadRef"
      v-model="files"
      :request-method="requestMethod"
      placeholder="自定义上传方法需要返回成功或失败信息"
      :on-fail="handleRequestFail"
      draggable
    ></t-upload>

**Comment by zhairy** [comment]
目前 0.24.1 仍然存在这个问题

**Comment by chaishi** [comment]
请设置 `theme` 指定使用哪一种风格（自定义上传方法不等于完全自由上传组件风格）

**Comment by chaishi** [comment]
经测试，Vue2 和 React 拖拽政策，Vue3 确实拖拽失效。

Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/1899
