### ISSUE TITLE
[table] 没有传递参数 `displayColumns` 时，增强表格吸顶和列配置没有显示表格内容

### ISSUE THREAD

**Issue by renjiali666** [Tencent/tdesign-vue-next#1784]
### 这个功能解决了什么问题

![c693828f376ffd09d6fd76c0e67f4b4](https://user-images.githubusercontent.com/111716113/193174395-41a3182d-f9d0-45f1-8765-954fa32dc685.jpg)
![d355aba5fb3f6410f7604299de03f81](https://user-images.githubusercontent.com/111716113/193174403-5015b50a-c0f1-4720-a714-1cf53e736ac4.jpg)
![4e880f47cb6e9fd8304df804d23bc42](https://user-image
![083fe0a9e620aa93baf4eebb0538d1e](https://user-images.githubusercontent.com/111716113/193174422-fa48f621-f96c-4f92-8782-02baa74a4ec0.jpg)
s.githubusercontent.com/111716113/193174408-9999947c-5baa-4e1c-ae54-73e5e12d31dd.jpg)
![6cb36656bcaa0551d70a6a6d83f3135](https://user-images.githubusercontent.com/111716113/193174412-3b411519-f709-47b3-ae4e-e29cb4040560.jpg)

### 你建议的方案是什么

这个是什么原因

**Comment by chaishi** [comment]
缺少参数 `displayColumns`

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue/pull/1633

published at `v0.24.2`
