### ISSUE TITLE
[组件名称] 升级至0.23.1后 全量引入app.use报告警

### ISSUE THREAD

**Issue by a670372846** [Tencent/tdesign-vue-next#1798]
### tdesign-vue-next 版本

0.23.1

### 重现链接

[https://codesandbox.io/s/adoring-benji-lflj46?file=/src/main.js](url)

### 重现步骤

![image](https://user-images.githubusercontent.com/48545213/193967640-f38f5ea6-67e0-416f-bf21-f0f9c9f5e6e4.png)
![image](https://user-images.githubusercontent.com/48545213/193967769-2ac3dee0-3d28-47f6-a08e-536a07ae2955.png)
![image](https://user-images.githubusercontent.com/48545213/193967882-a52f37ca-66ca-484f-9c63-242ebb6c8819.png)

0.22.1版本启动不会报这个告警
升级到0.23.1后启动就报这个告警了

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/1775 已解决
