### ISSUE TITLE
[Popup] `overlayClassName` 无法给最外层添加类名，只能添加到第二层

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1803]
### tdesign-vue-next 版本

0.23.1

### 重现步骤

<img width="691" alt="image" src="https://user-images.githubusercontent.com/11605702/194548235-a6f46e61-5351-4e28-8b57-0a6eb471f3da.png">

关于浮层类名样式的 API 定义

- `overlayClassName` 用于定义浮层样式类名。
- `overlayStyle` 用于定义浮层样式，比如浮层宽度。浮层宽度默认根据内容宽度呈现，可自由设置宽度和最大宽度。值为类型为函数时，可以实现浮层宽度和触发元素同宽。
- `overlayInnerStyle` 用于定义浮层内容部分样式，比如内容最大高度以及是否出滚动条。值为类型为函数时，可以实现浮层内容宽度和触发元素同宽。

**Comment by ikeq** [comment]
最外层是脚本生成的仅提供容器的节点，无任何样式，添加 class 的目的是啥
