### ISSUE TITLE
[疑问]没有类似Vuetify那样的文档吗

### ISSUE THREAD

**Issue by FuckAnyProblem** [Tencent/tdesign-vue-next#1807]

**Comment by FuckAnyProblem** [comment]
今天刚开始接触Vue3，因为之前都是vue2+vuetify，所以才提出这种疑问

**Comment by pengYYYYY** [comment]
我们vue2和vue3是分开来的两个项目，vue2可以参考 https://tdesign.tencent.com/vue/overview
