### ISSUE TITLE
[Dropdown] t-dropdown-item无法使用组件作为填充内容

### ISSUE THREAD

**Issue by jxwanglong** [Tencent/tdesign-vue-next#1825]
### 重现链接
https://stackblitz.com/edit/angular-xjuczk?file=src/demo.vue

### 重现步骤
通过重现链接模拟
1、简单使用dropdown组件，里面包含注释，会把注释内容作为item的填充内容
<img width="1385" alt="企业微信截图_a4e17910-1a33-4673-ad1b-94459010ccc7" src="https://user-images.githubusercontent.com/19237831/194810041-22d8745e-b477-44f4-a6c2-234a69dcd0ed.png">

2、放开注释，使用icon作为item的填充内容，会直接导致无法渲染，死循环
<img width="1699" alt="企业微信截图_46b216b3-c17c-4a44-af4b-50104040b251" src="https://user-images.githubusercontent.com/19237831/194810083-fc9528e6-061f-4253-8433-6afd8a7b2453.png">

### 期望结果
在使用vue组件作为dropdown-item的填充内容时，能够正常渲染

### 实际结果
<img width="1699" alt="企业微信截图_46b216b3-c17c-4a44-af4b-50104040b251" src="https://user-images.githubusercontent.com/19237831/194810083-fc9528e6-061f-4253-8433-6afd8a7b2453.png">

| Environment | Info |
|---|---|
| 相关版本 | 0.24.0 |
| 框架版本 / 基础库版本 | Vue(3.2.37) |
| 系统、浏览器 | Chrome(106.0.5249.103) |
| Node版本 |  |

**Comment by uyarn** [comment]
处理漏了
