### ISSUE TITLE
[Descriptions] 希望可以添加表单描述组件

### ISSUE THREAD

**Issue by LIUSHUAI2018** [Tencent/tdesign-vue-next#1830]
### 这个功能解决了什么问题

解决查看详情数据问题

### 你建议的方案是什么

功能可以参考element plus的描述组件

**Comment by pengYYYYY** [comment]
表单描述组件有具体可参考的嘛

**Comment by timi137137** [comment]
> 表单描述组件有具体可参考的嘛

他说的就是你们万年没做的Descriptionszuj组件
![image](https://user-images.githubusercontent.com/36812439/194978560-083435d6-c93e-43a2-9703-01fe25f1d834.png)

**Comment by LIUSHUAI2018** [comment]
一年了没有下文了，哎

**Comment by LIUSHUAI2018** [comment]
一年了没有下文了

**Comment by timi137137** [comment]
原本认领做这个组件的人鸽了，现在的情况是没人有空去做...
非常抱歉对不起

**Comment by uyarn** [comment]
supported 1.8.0
