### ISSUE TITLE
[Slider] 鼠标在按钮上悬浮时无法显示tooltip

### ISSUE THREAD

**Issue by zrut747** [Tencent/tdesign-vue-next#1834]
### tdesign-vue-next 版本

0.24.1

### 重现链接

https://stackblitz.com/edit/slider-v2sfsl?file=package.json,src%2Fdemo.vue

### 重现步骤

鼠标悬浮在 slider 按钮上时，不能显示 tooltip。
实际测试在 0.20.5 版本是能正常显示的，更新到之后的版本就不行了。（下图是 0.20.5 版本的效果，之后的版本 hover 后没有反应）

![image](https://user-images.githubusercontent.com/32980146/194982976-f76c90c1-47a9-481e-8df5-2020873d7deb.png)

**Comment by ChrisLee0211** [comment]
排查到原因了，应该是2个月前的「popup 支持 overlayInnerStyle」功能迭代过程中覆盖了tooltip变量导致。正在修复中 @zrut747
