### ISSUE TITLE
[Pagination] pageSize选择框在Dialog中默认宽度和直接使用Pagination不一致

### ISSUE THREAD

**Issue by zrut747** [Tencent/tdesign-vue-next#1837]
### tdesign-vue-next 版本

0.24.1

### 重现链接

https://stackblitz.com/edit/pagination-2jsfjv

### 重现步骤

打开 Dialog，里面的 Pagination 的 pageSize 选择框会比不在 Dialog 里时要宽。

![image](https://user-images.githubusercontent.com/32980146/195028932-295a7728-2ab0-4085-93ca-a28ef6300079.png)
![image](https://user-images.githubusercontent.com/32980146/195029258-bc0add17-8a58-4362-9e9d-8608f3f7ed2e.png)

点击一次 pageSize 选择框后，宽度又会恢复正常。

![image](https://user-images.githubusercontent.com/32980146/195030234-f1ad7cef-de35-4eba-8d0d-8a17e6f23a8c.png)

经过测试，Table 绑定的 Pagination 在 Dialog 中打开也会有这样的问题。

### 期望结果

使用 Dialog 和不使用 Dialog 时宽度保持一致

**Comment by pengYYYYY** [comment]
应该是select的问题，mark一下

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/3352
