### ISSUE TITLE
[upload] 自定义上传方法在theme=“image”时展示错误

### ISSUE THREAD

**Issue by qihuantian1** [Tencent/tdesign-vue-next#1844]
### tdesign-vue-next 版本

0.24.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/upload#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0%E6%96%B9%E6%B3%95

### 重现步骤

官方示例  upload自定义上传方法，定义theme="image" 时 没有按照图片类型展示， 见下截图

### 补充说明

![image](https://user-images.githubusercontent.com/10757545/195153774-48e538d9-f0b9-4798-8dd5-8c55b8bef765.png)

**Comment by chaishi** [comment]
根据目前提供的信息，无法定位问题。如果希望我们解决问题，辛苦提供可复现问题的链接，而非简单的一个官网地址。

超过时间回复，issue 将会被关闭。

https://stackblitz.com/run?file=src%2Fdemo.vue
可以在这个链接里面复现一下你说的问题，ctrl + s 保存代码后，把新的链接写上。


图片没有正常显示的可能：检查自定义上传方法返回的 `response` 数据结构是否符合预期

**Comment by qihuantian1** [comment]
补充链接     https://stackblitz.com/edit/angular-5dxlfh?file=src%2Fdemo.vue

点击图片上传后，展示的格式不对， response 内容都是固定的

**Comment by chaishi** [comment]
https://stackblitz.com/edit/angular-5dxlfh-7vaxv8?file=src%2Fdemo.vue

这里有一个正确的示例，试试看

**Comment by qihuantian1** [comment]
非常感谢
