### ISSUE TITLE
[Dropdown ]  在插槽模式下不能渲染图标 下拉选项不能使用IF判断

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#1850]
### tdesign-vue-next 版本

0.24.1

### 重现步骤

[Dropdown ]  在插槽模式下不能渲染图标 下拉选项不能使用IF判断
具体异常已在微信群内反馈

**Comment by uyarn** [comment]
图标应该已经修复了
<img width="407" alt="image" src="https://user-images.githubusercontent.com/26377630/195306149-50bb1603-a235-4184-bc0e-2059405c5aee.png">
