### ISSUE TITLE
[Select] 设置filterable，multiple和onSearch的远程搜索模式下，点击delete按键删除前一次关键词的时候，会删除已选项

### ISSUE THREAD

**Issue by funczh** [Tencent/tdesign-vue-next#1857]
### tdesign-vue-next 版本

0.24.1

### 重现链接

https://stackblitz.com/edit/angular-w8ugfe?file=src%2Fdemo.vue

### 重现步骤

Step1. 输入aaa
Step2. 任意选择一个选项
Step3. 按下键盘上的删除按钮，修改搜索关键词，此时正常的结果应该是删除上一次输入的关键词，但是现在的现象是把前一次选中的项删除了

现象细节：反复尝试这个操作，会出现一次正常一次异常**交替出现**的现象

https://user-images.githubusercontent.com/16182130/195484611-53a417a5-79ef-4f6e-a1db-dc75751f1a04.mov

### 期望结果

每一次都可以正常删除前一次的搜索关键词，而不是删除已选的结果

### 实际结果

键入删除键变更搜索关键词的时候，会把上一次选中的项删除

**Comment by funczh** [comment]
请问这个问题有进展吗，已经两周了

**Comment by funczh** [comment]
为了解决项目问题，我想了一个hack，用完体验尚可，供大家参考。

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2087
