### ISSUE TITLE
CI test snapshot 异常

### ISSUE THREAD

**Issue by HelKyle** [Tencent/tdesign-vue-next#1860]
### tdesign-vue-next 版本

develop

### 重现步骤

从 develop 切分支出来，拉取最新的 common 代码，提交 pr 单元测试没跑过，但是和我的改动没有关系

https://github.com/Tencent/tdesign-vue-next/actions/runs/3240400725/jobs/5310977049

另一个同学的 pr 里也出现了同样的报错

https://github.com/Tencent/tdesign-vue-next/actions/runs/3241710063/jobs/5314018856

### 期望结果

单元测试能正常通过。

**Comment by pengYYYYY** [comment]
1
