### ISSUE TITLE
[tree] 拖曳的树，拖曳时候，鼠标是绿色默认加好，可以改为小手

### ISSUE THREAD

**Issue by zhoulujun** [Tencent/tdesign-vue-next#1864]
### tdesign-vue-next 版本

0.24.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/tree#%E5%8F%AF%E6%8B%96%E6%8B%BD%E7%9A%84%E6%A0%91

### 重现步骤

直接拖动
<img width="653" alt="image" src="https://user-images.githubusercontent.com/4243366/195816470-f5742d43-2817-4a0c-8b12-7dbf7e193623.png">

### 期望结果

绿色默认的加号小手去掉

<h2 style="margin: 0px; padding: 0px; font-weight: 600; font-size: 23px; color: rgb(68, 68, 68); font-family: &quot;Microsoft YaHei&quot;, Tahoma, &quot;Hiragino Sans GB&quot;, SimHei, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://developer.mozilla.org/zh-CN/docs/Web/API/DataTransfer" target="_blank" title="DataTransfer MDN解析" rel="nofollow" style="text-decoration: none; cursor: pointer; color: rgb(18, 42, 178); transition: color 100ms ease-in 0s;">dataTransfer对象</a></h2><p style="margin: 0px 0px 5px; padding: 0px; color: rgb(68, 68, 68); font-family: &quot;Microsoft YaHei&quot;, Tahoma, &quot;Hiragino Sans GB&quot;, SimHei, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">在所有的拖放事件中都提供了一个数据传输对象dataTransfer，主要是<strong>用于在<span style="color: rgb(192, 0, 0);">源对象和目标对象之间</span>传递数据</strong>。</p><blockquote style="margin: 10px 0px; padding: 10px; color: rgb(102, 102, 102); border-left: 4px solid rgb(221, 221, 221); background-color: rgb(242, 251, 255); overflow: hidden; font-family: &quot;Microsoft YaHei&quot;, Tahoma, &quot;Hiragino Sans GB&quot;, SimHei, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><p style="margin: 0px 0px 5px; padding: 0px;">与拖放操作所触发的事件同时派发的对象是DragEvent，它派生于MouseEvent，具有Event与MouseEvent对象的所有功能，并增加了dataTransfer属性。该属性用于保存拖放的数据和交互信息，返回DataTransfer对象。</p></blockquote><p style="margin: 0px 0px 5px; padding: 0px; color: rgb(68, 68, 68); font-family: &quot;Microsoft YaHei&quot;, Tahoma, &quot;Hiragino Sans GB&quot;, SimHei, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">DataTransfer对象定义的属性和方法有很多种，我们看下列入标准的几个。</p>

属性 | 说明
-- | --
types | 只读属性。它返回一个我们在dragstart事件中设置的拖动数据格式的数组。 格式顺序与拖动操作中包含的数据顺序相同。
files | 返回拖动操作中的文件列表。包含一个在数据传输上所有可用的本地文件列表。如果拖动操作不涉及拖动文件，此属性是一个空列表。
dropEffect | 获取当前选定的拖放操作的类型或将操作设置为新类型。它应该始终设置成effectAllowed的可能值之一【none、move、copy、link】。dragover事件处理程序中针对放置目标来设置dropEffect。
effectAllowed | 指定拖放操作所允许的效果。必须是其中之一【 none, copy, copyLink, copyMove, link, linkMove, move, all, uninitialized】默认为uninitialized 表示允许所有的效果。ondragstart处理程序中设置effectAllowed属性

[dataTransfer对象](https://developer.mozilla.org/zh-CN/docs/Web/API/DataTransfer)
在所有的拖放事件中都提供了一个数据传输对象dataTransfer，主要是用于在源对象和目标对象之间传递数据。

与拖放操作所触发的事件同时派发的对象是DragEvent，它派生于MouseEvent，具有Event与MouseEvent对象的所有功能，并增加了dataTransfer属性。该属性用于保存拖放的数据和交互信息，返回DataTransfer对象。

DataTransfer对象定义的属性和方法有很多种，我们看下列入标准的几个。

属性	说明
[types](https://developer.mozilla.org/zh-CN/docs/Web/API/DataTransfer/types)	只读属性。它返回一个我们在dragstart事件中设置的拖动数据格式的数组。 格式顺序与拖动操作中包含的数据顺序相同。
[files](https://developer.mozilla.org/zh-CN/docs/Web/API/DataTransfer/files)	
返回拖动操作中的文件列表。包含一个在数据传输上所有可用的本地文件列表。

如果拖动操作不涉及拖动文件，此属性是一个空列表。

[dropEffect](https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/dropEffect)	获取当前选定的拖放操作的类型或将操作设置为新类型。它应该始终设置成effectAllowed的可能值之一【none、move、copy、link】。dragover事件处理程序中针对放置目标来设置dropEffect。
[effectAllowed](https://developer.mozilla.org/zh-CN/docs/Web/API/DataTransfer/effectAllowed)	指定拖放操作所允许的效果。必须是其中之一【 none, copy, copyLink, copyMove, link, linkMove, move, all, uninitialized】默认为uninitialized 表示允许所有的效果。ondragstart处理程序中设置effectAllowed属性

https://www.zhoulujun.cn/html/webfront/SGML/html5/2016_0124_434.html

### 实际结果

![Uploading 7278e9b52ca5f8f995c53f5d2aaa8497.jpg…]()

**Comment by revilhui** [comment]
请问，拖拽后如何拿到改变后的data数组
