### ISSUE TITLE
[Table] 自定义表头，title值为插槽名称的设计是否友好，如title有中文、重复、国际化等情况（看不明白期望实现什么，需要什么，解决什么问题）

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#1879]
### tdesign-vue-next 版本

0.24.1

### 重现步骤

如题

### 期望结果

是否可以用`title-${colKey}`类似的来作为表头的插槽名称更合适

**Comment by chaishi** [comment]
title = '中文’，表格会正常显示中文；
title =’slot-name' 也可以插槽定义，
title 重复，似乎也什么问题。
国际化，没有实际场景，无法描述。

没有明白是有多复杂的场景无法满足。

辛苦列举无法满足的具体需求场景，而非一句简单的描述来否定。

**Comment by hkaikai** [comment]
我是说这个
@chaishi 
![image](https://user-images.githubusercontent.com/19343340/196389039-61c038f0-b786-48b6-83f2-4b5f38f1a0a4.png)

**Comment by chaishi** [comment]
还是不明白这个有什么问题

大家的大脑彼此不通，存在巨量信息查。

为减少沟通成本，辛苦提出明确的需求或缺陷，清楚地描述问题，以及相关解决方案。

否则 issue 将会一直挂起，我们无法正确处理。超出时间，将自动关闭

**Comment by hkaikai** [comment]
https://stackblitz.com/run?file=src%2Fdemo.vue

自定义表头，title值为插槽名称，如：
```
<template #我是个中文> xxx </template>
```

这种情况感觉不太好，我理解title重复、为中文、国际化化时，不太好用这个来作为插槽名称

**Comment by Aicmortal** [comment]
> https://stackblitz.com/edit/angular-s3tqut?file=src%2Fdemo.vue
> 
> 自定义表头，title值为插槽名称，如：
> 
> ```
> <template #我是个中文> xxx </template>
> ```
> 
> 我觉得title重复、为中文、国际化化时，不太好用这个来作为插槽名称

出现中文等国际化这种情况避免掉不就好了
另外你设想的插槽名称```title-${colKey}```也可以自己实现,插槽名称本身已经可以自定义了
是想要不允许自定义?改为固定规范?
