### ISSUE TITLE
[Menu] 菜单组件样式不对齐问题

### ISSUE THREAD

**Issue by timi137137** [Tencent/tdesign-vue-next#1881]
### tdesign-vue-next 版本

0.24.2

### 重现步骤

![image](https://user-images.githubusercontent.com/36812439/196405377-d07f7f7d-abf8-47fa-8af7-ac38d5281274.png)
![image](https://user-images.githubusercontent.com/36812439/196405416-c2bc8f6d-bfb8-4ed1-842f-5f707d7e7293.png)
![image](https://user-images.githubusercontent.com/36812439/196405723-b319140c-b35d-4793-a5bd-8973bb1845ed.png)

link Tencent/tdesign-vue-next-starter#340

问题出在tdesign-common 中的 `style/web/components/menu/_index-v2.less`第 162 行，因为这个margin-top导致不对齐

**Comment by pengYYYYY** [comment]
1.0 版本已经修复
