### ISSUE TITLE
[Dropdown ] 自定义其他属性的下拉菜单——官方文档示例

### ISSUE THREAD

**Issue by RSS1102** [Tencent/tdesign-vue-next#1882]
### 重现链接
https://tdesign.tencent.com/vue-next/components/dropdown?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%85%B6%E4%BB%96%E5%B1%9E%E6%80%A7%E7%9A%84%E4%B8%8B%E6%8B%89%E8%8F%9C%E5%8D%95

### 重现步骤
1. 官方文档
2. 示例：自定义其他属性的下拉菜单

### 期望结果
实现关于popupProps的示例

### 实际结果
示例并没有关于任何popupProps参考代码。

| Environment | Info |
|---|---|
| 相关版本 | 0.24.2 |
| 框架版本 / 基础库版本 | vue3 |
| 系统、浏览器 | win11 Chrome  106.0.5249.119 |
| Node版本 |  |

**Comment by uyarn** [comment]
是支持的 文档示例应该是误删了 我补充下
<img width="878" alt="image" src="https://user-images.githubusercontent.com/26377630/196583587-ea3ba67d-19f5-400d-845a-370db7793991.png">

**Comment by RSS1102** [comment]
> 是支持的 文档示例应该是误删了 我补充下 <img alt="image" width="878" src="https://user-images.githubusercontent.com/26377630/196583587-ea3ba67d-19f5-400d-845a-370db7793991.png">

请关注一下这个issue：https://github.com/Tencent/tdesign-vue-next-starter/issues/338#issuecomment-1283367182

**Comment by uyarn** [comment]
和 #1910是一个事情 跟进#1910就可以了 这个先关掉
