### ISSUE TITLE
[Select] 过滤选项后，hoverIndex通过上下按键移动不符合预期

### ISSUE THREAD

**Issue by wilonjiang** [Tencent/tdesign-vue-next#1893]
### tdesign-vue-next 版本

0.24.2

### 重现链接

https://stackblitz.com/edit/angular-mlt18h?file=src/demo.vue

### 重现步骤

1. options默认（如：10项内容），随机选中一项
2. 对options中内容进行搜索过滤（如：剩5项）
3. 键盘上或下键，移动hoverIndex
4. hoverIndex标识未按照当前显示的options顺序移动，而是按照未过滤前options顺序移动

### 期望结果

对options中内容进行搜索过滤后，键盘上或下键操作hoverIndex标识应按照当前显示的options顺序移动

### 实际结果

对options中内容进行搜索过滤后，键盘上或下键操作hoverIndex标识按照原始options顺序移动，未按照当前显示的options顺序移动

### 框架版本

vue3.2

### 系统版本

MACOS 11.2.3

### Node版本

Node(v16.15.0)

**Comment by uyarn** [comment]
fixed, upgrade to new version
