### ISSUE TITLE
[Upload] header参数未生效

### ISSUE THREAD

**Issue by huyiwill** [Tencent/tdesign-vue-next#1895]
### tdesign-vue-next-starter 版本

t-upload组件加了headers，但是上传请求的时候没有把头部参数加上

### 重现步骤

这是上传文件。设置了headers
![企业微信截图_16661695115452](https://user-images.githubusercontent.com/19531939/196644169-d235b734-b751-467d-b52e-cc7943bb7a17.png)

但是请求时候头部并没有把参数加上
![Uploading 企业微信截图_16661695776624.png…]()

### 期望结果

headers头部信息加到请求头中去

### Node版本

16.6

**Comment by chaishi** [comment]
resolved in 0.23.1

**Comment by houyi** [comment]
1.9.6  版本， headers  不生效！！ 什么挖一啊
