### ISSUE TITLE
[UPLOAD] 自定义上传方法上传多文件模式下 图片无法显示

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#1898]
### tdesign-vue-next 版本

0.24.2

### 重现步骤

html代码
`       <t-upload ref="uploadRef"
                      v-model="fileList"
                      :request-method="uploadImage"
                      theme="image" tips="允许选择多张图片文件上传，最多只能上传 6 张图片"
                      accept="image/*"
                      :max="6"
                      multiple />
`

执行方法
`
const uploadImage = e => {
  const file = e[0]
  return new Promise((resolve) => {
    file.percent = 0;
    const timer = setTimeout(() => {
      // resolve 参数为关键代码
      resolve({status: 'success', response: {url: 'https://tdesign.gtimg.com/site/avatar.jpg'}});
      file.percent = 100;
      clearTimeout(timer);
    }, 1000);

  })
}
`

返回结果截图：

![image](https://user-images.githubusercontent.com/46079969/197149799-e84782a4-28c2-42e5-8ca9-f54a674cb8b5.png)

### 期望结果

正常显示

**Comment by chaishi** [comment]
same as https://github.com/Tencent/tdesign-vue-next/issues/1780

resolved in https://github.com/Tencent/tdesign-common/pull/918 and https://github.com/Tencent/tdesign-vue-next/pull/1899
