### ISSUE TITLE
[Input 输入框] 是否有类似 antdv的Mentions 提及 功能

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#1902]
### 这个功能解决了什么问题

微博@输入功能，或者模板字符串变量输入功能

### 你建议的方案是什么

输入@或配置的其他字符串{}等，出现一个下拉列表，选择输入一个名称或变量。变量可以有背景区分

antdv的提及组件： https://www.antdv.com/components/mentions-cn

**Comment by pengYYYYY** [comment]
暂时没有，可以通过select-input自行封装
