### ISSUE TITLE
[Slider] 滑动滑块时 Tooltip 不会跟随滑块移动

### ISSUE THREAD

**Issue by Lmmmmmm-bb** [Tencent/tdesign-vue-next#1904]
### tdesign-vue-next 版本

0.24.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/slider

### 重现步骤

1. 移动 **基础滑块** 示例的滑块
2. 滑块的 Tooltip 信息不跟随滑块移动

### 期望结果

滑块 Tooltip 信息跟随滑块移动

### 实际结果

Tooltip 不跟随滑块移动

**Comment by ChrisLee0211** [comment]
@Lmmmmmm-bb 你提供的地址看起来tooltip是可以跟随slider的，能否提供具体的demo？

**Comment by Lmmmmmm-bb** [comment]
> @Lmmmmmm-bb 你提供的地址看起来tooltip是可以跟随slider的，能否提供具体的demo？

确实没有复现，可能我昨晚的网络问题嘛，我晚上回去确认下～

**Comment by Lmmmmmm-bb** [comment]
@ChrisLee0211 

Hello 我这边环境下能够复现这个情况
- Windows 11, version 22H2
- Chrome 106.0.5249.119（正式版本） （64 位）

![screenshot](https://user-images.githubusercontent.com/54026110/197793174-c53d10b0-00c4-4b94-ad4b-41656789ed8b.gif)

**Comment by ChrisLee0211** [comment]
@Lmmmmmm-bb 可以尝试左上角切回到上一个版本试试吗？

**Comment by Lmmmmmm-bb** [comment]
> @Lmmmmmm-bb 可以尝试左上角切回到上一个版本试试吗？

试了下上两个版本的，貌似 Tooltip 都没了。

然后我看最新版的纵向滑块是这个效果，上两个版本的纵向滑块是正常的。

![image](https://user-images.githubusercontent.com/54026110/197805128-a5e50696-2747-417b-af8f-5072b4e4caf7.png)

**Comment by pengYYYYY** [comment]
第二个demo的问题是我改space组件的时候出的问题，我这边处理一下

**Comment by ChrisLee0211** [comment]
@Lmmmmmm-bb 抱歉，我这边始终没办法复现你的问题，或者说你那边有没有一种稳定的复现步骤可以提供一下？

**Comment by Lmmmmmm-bb** [comment]
> @Lmmmmmm-bb 抱歉，我这边始终没办法复现你的问题，或者说你那边有没有一种稳定的复现步骤可以提供一下？

Chrome 版本更新后在下面的环境还是会复现，开启无痕也会这样，但是在 mac 上却是正常的
- Windows 11, version 22H2
- 版本 107.0.5304.88（正式版本） （64 位）

感觉是个例问题，这个 issue 我这边先关闭了吧，如果有其他人遇到的话再打开，感谢跟进~

**Comment by Nakus0426** [comment]
跟随了，但没有完全跟随....

https://user-images.githubusercontent.com/41540888/209619884-fd23eaa0-ed9a-4d00-9857-9cdbe0886e62.mp4
