### ISSUE TITLE
[Select] 输入框内部间距不规范问题

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#1907]
### tdesign-vue-next 版本

0.24.2

### 重现步骤

按理说，如果是基于 SelectInput 开发，应该不会出现这个问题。
否则就是所有下拉组件都有这个问题

<img width="616" alt="image" src="https://user-images.githubusercontent.com/11605702/197787054-d01340d9-11e7-436b-85e5-3f87e3c56b2c.png">

**Comment by RayJason** [comment]
已接，11月1日前完成。

**Comment by RayJason** [comment]
问题原因：
`.t-tag-input` 覆盖了 `.t-input` 原本的内边距。

<img width="550" alt="image" src="https://user-images.githubusercontent.com/15711610/199045046-735163d0-7a6a-45ad-856f-4b0a7d103491.png">
