### ISSUE TITLE
EnhancedTable appendTo is not a function （待提供可复现问题的实例）

### ISSUE THREAD

**Issue by xwtAiyoo** [Tencent/tdesign-vue-next#1911]
### tdesign-vue-next 版本

0_24_3

### 重现链接

https://0_24_3-tdesign-vue-next.surge.sh/vue-next/components/table

### 重现步骤

添加根节点 ，节点懒加载 ， table.value.appendTo() 提示   s.value.appendTo is not a function
![image](https://user-images.githubusercontent.com/25432030/198000166-1effc5c4-bda7-4ae4-9d9a-c340cabadd1d.png)

官方实例中依然有问题  ，复现步骤 
![image](https://user-images.githubusercontent.com/25432030/198000714-ecbd8d1b-6e08-49a3-bb39-63fd0655c33e.png)

注： 打包部署后才有这个问题  npm run 就没问题

**Comment by chaishi** [comment]
刚刚试了下官网示例，没有复现问题

<img width="799" alt="image" src="https://user-images.githubusercontent.com/11605702/198876898-b535f150-f02a-4b54-9c79-742d69574b87.png">

**Comment by chnykn** [comment]
@chaishi，该问题还是存在的，我重新描述了问题 https://github.com/Tencent/tdesign-vue-next/issues/1999

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2004/files
