### ISSUE TITLE
[table] 升级版本后，过滤功能不生效了，点击会报错

### ISSUE THREAD

**Issue by JiaWeApollo** [Tencent/tdesign-vue-next#1912]
### tdesign-vue-next 版本

0.22.1

### 重现链接

https://0_22_1-tdesign-vue-next.surge.sh/vue-next/components/table#%E5%8F%AF%E7%AD%9B%E9%80%89%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

![image](https://user-images.githubusercontent.com/16689041/198000118-0ccffccc-6ff3-420f-8b85-4ed444404c2c.png)
![image](https://user-images.githubusercontent.com/16689041/198000240-95d78b67-5e64-4f09-9cd0-5f1091bcf34d.png)
从0.17.3升级到0.22.1后，table的过滤功能不生效了，点击提示报错。
这是我们系统的生产问题，烦请尽快修复下！感谢

**Comment by chaishi** [comment]
最新版本 `v0.24.3` 官网没有这个问题， 请参考官网示例代码试试

尝试链接：https://stackblitz.com/run?file=src%2Fdemo.vue
