### ISSUE TITLE
[Upload] setPercent 方法丢失

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-vue-next#1913]
### tdesign-vue-next 版本

0.24.3

### 重现步骤

![image](https://user-images.githubusercontent.com/14084550/198002786-b2c1363c-442e-4b73-918d-3fb1c3a8ce2a.png)

setPercent 方法在 0.19.0 版本添加，最近升级到 0.24.3 后 该方法被去除了，但是更新日志未找到是什么时候去除的，且文档也没有替代方式

**Comment by pengYYYYY** [comment]
可以直接更改file上面的percent

**Comment by PDieE** [comment]
他在上传中的时候 v-model 的值是不会更新的，但是如果我去掉 v-model 自己push 那么就会出现两个上传中的，直到上传完成才会变成一个

**Comment by PDieE** [comment]
![image](https://user-images.githubusercontent.com/14084550/198013946-17c7997b-807a-4094-86ba-581810c4cde9.png)
![image](https://user-images.githubusercontent.com/14084550/198013974-27e01750-0de2-42f6-b91a-aee1b5d8f03e.png)
![image](https://user-images.githubusercontent.com/14084550/198014010-dc4e3fd1-da7b-4865-89d7-5c168e49a316.png)

files并不能完全的受控

**Comment by PDieE** [comment]
我又试了下 value 是可以完全受控的······· 而files就会出现上述情况

**Comment by pengYYYYY** [comment]
用v-model应该可以吧
