### ISSUE TITLE
[Button] 按钮组件 点击 样式覆盖困难问题

### ISSUE THREAD

**Issue by wenrouxiansheng** [Tencent/tdesign-vue-next#1915]
### tdesign-vue-next 版本

最新版

active 下的渐变过渡背景 是拿动态生成的div做的 非常不好覆盖样式，为了通用建议看优化一下，不是所有设计稿都要那个过渡效果

**Comment by pengYYYYY** [comment]
可以通过 `globalConfig` 关闭此配置

https://tdesign.tencent.com/vue/config?tab=api
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/35833812/198467973-af671965-10a5-44ea-ab3a-372328c41390.png">

**Comment by pengYYYYY** [comment]
也可以通过 --ripple-color: none 来关闭
