### ISSUE TITLE
[tabs] tabs初始样式异常

### ISSUE THREAD

**Issue by StevenY0o0** [Tencent/tdesign-vue-next#1924]
### tdesign-vue-next 版本

0.24.1

### 重现步骤

在微前端框架中使用会出现初始下标长度异常的情况，切换后正常
<img width="300" alt="企业微信截图_8842fd63-44a5-4aa3-826a-a5ee29deb044" src="https://user-images.githubusercontent.com/31976766/198553083-2e1eb082-d6ee-48f5-85e6-aa69dd6b2958.png">

**Comment by PengYYYYY** [comment]
能提供更多一些的信息吗，这边无法排查问题喔

**Comment by ccccpj** [comment]
无法复现
