### ISSUE TITLE
[t-table] 自动引入报错（自动引入插件问题，非组件本身问题）

### ISSUE THREAD

**Issue by xdewx** [Tencent/tdesign-vue-next#1929]
### tdesign-vue-next 版本

0.24.3

### 重现链接

https://user-images.githubusercontent.com/20438962/198860291-5280efae-37b6-4f8f-ac41-5882fafd97b8.png

### 重现步骤

<img width="625" alt="image" src="https://user-images.githubusercontent.com/20438962/198860291-5280efae-37b6-4f8f-ac41-5882fafd97b8.png">
<img width="980" alt="image" src="https://user-images.githubusercontent.com/20438962/198860328-51ec4ade-c2e5-4a07-895c-e68ad0c0413d.png">

1. 配置自动引入
2. 发现auto-imports.d.ts中自动添加了一条 const TABLE: typeof import('tdesign-vue-next')['ABLE']
3. 报错显示的地方并没有使用到t-table，但是存在一个自定义的Table类

`cp -r node_modules/tdesign-vue-next/es/table node_modules/tdesign-vue-next/es/a-b-l-e`后可以正常编译，但是页面打开不了，控制台提示没有ABLE这个模块，显然是tdesign的模块有问题

### 期望结果

不报错

### 实际结果

报错

**Comment by chaishi** [comment]
我没看懂问题，不知道是自动引入插件的问题，还是组件的问题。

目前，没有其他业务反馈类似问题。

@uyarn @pengYYYYY  xdm 看看呢

**Comment by xdewx** [comment]
> 我没看懂问题，不知道是自动引入插件的问题，还是组件的问题。
> 
> 目前，没有其他业务反馈类似问题。
> 
> @uyarn @pengYYYYY xdm 看看呢

应该是自动引入插件的问题，在不配置自动引入时一切正常，但是配置自动引入后就报错，看起来是tdesign的自动引入的解析逻辑有问题，把一些名字叫TABLE的字符串都解释为需要引入table组件，因此也就出现了在一些非vue组件中加入import t-table的代码，且自动生成的代码的引入路径也有问题，例如：node_modules/tdesign-vue-next/a-b-l-e，这里的able正是自动引入插件导入的ABLE组件（代码中有一段import ABLE as TABLE）

**Comment by pengYYYYY** [comment]
那需要去插件改这个问题了

**Comment by chaishi** [comment]
描述中出现了各样的截图和推荐，但是缺少最重要的信息。请问“配置自动引入” 这句话中提到的是**哪个插件**的自动引入，上文描述中没有看到插件名。

不知道用的什么插件，也不知道怎么复现问题，就更不知道如何解决问题。

**Comment by xdewx** [comment]
> 描述中出现了各样的截图和推荐，但是缺少最重要的信息。请问“配置自动引入” 这句话中提到的是**哪个插件**的自动引入，上文描述中没有看到插件名。 `unplugin-vue-components` ?
> 
> 不知道用的什么插件，也不知道怎么复现问题，就更不知道如何解决问题。

![image](https://user-images.githubusercontent.com/20438962/222955141-c26a475d-1dad-4a97-a86f-de75890ada54.png)
加上红框处的配置就会报错

**Comment by uyarn** [comment]
新的插件已经修复了
