### ISSUE TITLE
[table] 宽度不能随浏览器变化而自动适应

### ISSUE THREAD

**Issue by dodu2014** [Tencent/tdesign-vue-next#1934]
### tdesign-vue-next-starter 版本

0.5.4

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/list/filter

### 重现步骤

浏览器非最大化窗口时，左右调整页面大小，表格的列宽度只会自动变宽，不会自动变窄，底部一旦出现左右滑动的滚动条时，拉宽页面也不会消失，如果宽度合适的化，刷新后表格恢复无滚动条状态。

### 期望结果

表格的列能自动适应

### 框架版本

Vue 3.2.0

### 浏览器版本

Edge 107

### 系统版本

Win 10

**Comment by chaishi** [comment]
已在新版本中修复

**Comment by dodu2014** [comment]
thanks 👍❤️
