### ISSUE TITLE
【table】表格多列排序失效

### ISSUE THREAD

**Issue by Prc-PY** [Tencent/tdesign-vue-next#1951]
vue-next里表格加了多列排序的属性后，就无法进行排序，示例文档中就是这样
![image](https://user-images.githubusercontent.com/64288053/199423988-be7241aa-cec5-412e-b5ba-701b4ebe7642.png)

**Comment by chaishi** [comment]
由于排序功能的实现，有可能是远程排序，有可能是本地排序，故而组件只保证 `sort` 属性字段的正确性，至于具体的数据 `data` 业务侧自行根据 `sort` 对数据做处理

<img width="903" alt="image" src="https://user-images.githubusercontent.com/11605702/204129231-d4617ff1-6fe6-42d6-ad3a-357a9bb279a0.png">
