### ISSUE TITLE
[table]  可编辑状态下，使用本地数据分页的时候 ，如果有分页 数据编辑数据失去响应式

### ISSUE THREAD

**Issue by zhairy** [Tencent/tdesign-vue-next#1952]
### tdesign-vue-next 版本

0.24.5

### 重现链接

https://stackblitz.com/edit/angular-sa8fcq?file=src%2Fdemo.vue

### 重现步骤

table 表格，在可编辑状态下，数据分页后 ，可编辑数据 进行编辑后 退出编辑 数据还是原来的 丢失了响应式，实际表格数据已经更改，编辑组件的 value 未同步，在数据条数小于分页数下，未丢失响应式，远程分页也未丢失响应式

### 期望结果

修复

**Comment by chaishi** [comment]
resolved in `v0.24.9`
