### ISSUE TITLE
[table] 行选中功能支持点击行选中而不仅是点击单选或复选框选中

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#1954]
### 这个功能解决了什么问题
开启行选中功能时，可以点击本行任意区域选中或取消选中当前行，现在是必须点击单选或复选框选中

### 你建议的方案是什么？
点击本行任意区域选中或取消选中当前行

**Comment by chaishi** [comment]
前段时间在处理其他 Feature，我下周支持下这个

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2105
