### ISSUE TITLE
[Popup 弹出层] 当触发元素为MenuItem时, Popup不会弹出

### ISSUE THREAD

**Issue by cloudfun** [Tencent/tdesign-vue-next#1956]
### 重现链接
项目未上线,暂时无法提供链接

### 重现步骤
创建一个Menu, 有诺干menuItem菜单项
在其中一个menuItem使用默认插槽定义触发元素的方式创建一个popup, 使该menuitem变成popup的“ triggerElement”
并设置popup的触发方式为"click", 即trigger="click"

### 期望结果
点击menuItem会触发popup显示

### 实际结果
点击menuItem并未触发popup显示

### 补充说明
triggerElement从父组件使用了v-slot的方式提供

| Environment | Info |
|---|---|
| 相关版本 | 0.24.5 |
| 框架版本 / 基础库版本 | Vue(3.2.41) |
| 系统、浏览器 | Google Chrome(106.0.5249.119 (arm64)) |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
menu 已经做了重构，可以安装新版本试试
