### ISSUE TITLE
[Table] 树形表格展开和收起全部不生效

### ISSUE THREAD

**Issue by ryujane** [Tencent/tdesign-vue-next#1957]
### tdesign-vue-next 版本

0.24.5

### 重现链接

https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E6%A0%91%E5%BD%A2%E7%BB%93%E6%9E%84%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

官网树形结构表格展开全部和收起全部不生效

### 期望结果

树形表格正常展开或收起全部

**Comment by ryujane** [comment]
补充错误信息
<img width="592" alt="image" src="https://user-images.githubusercontent.com/37573832/200469249-957c0404-3f47-4ae2-9176-e9ffe38adfd6.png">

**Comment by ryujane** [comment]
和这个 #1911 类似，第一可以，第二次就不行了，npm run也可以，打包后不行,官网链接可复现

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2004/files
