### ISSUE TITLE
[Transfer] 与Tree结合使用，无法进行勾选

### ISSUE THREAD

**Issue by ldypgod** [Tencent/tdesign-vue-next#1958]
### tdesign-vue-next 版本

0.24.5

### 重现链接

https://tdesign.tencent.com/vue-next/components/transfer?tab=demo#%E4%B8%8E-tree-%E7%BB%93%E5%90%88%E4%BD%BF%E7%94%A8

### 重现步骤

在 Stackblitz 中打开后，运行成功后去树形菜单上进行选中，无法勾选

### 期望结果

能选中

### 实际结果

不能选中，控制台提示 Set operation on key "checked" failed: target is readonly. 

### 框架版本

Vue(3.2.40)

### 浏览器版本

106.0.5249.121（正式版本）

### 系统版本

win10

**Comment by ldypgod** [comment]
<template>
  <t-transfer
    v-model="targetValue"
    v-model:checked="checked"
    :data="items"
    @change="onChange"
    @checked-change="handleCheckedChange"
  >
    <template #tree="slotProps">
      <t-tree v-bind="slotProps" checkable hover expand-all transition />
    </template>
  </t-transfer>
</template>

我刚刚发现 t-tree里不能直接使用v-bind  因为slotProps.value不是checked，tree里的value需要的值是checked

**Comment by pengYYYYY** [comment]
看起来表现正常

**Comment by pengYYYYY** [comment]
https://user-images.githubusercontent.com/35833812/200465152-496560c1-f969-4967-b1f8-de162886559e.mov

**Comment by pengYYYYY** [comment]
issue 暂时关闭，待提供更多信息后，可以reopen

**Comment by ldypgod** [comment]
在 Stackblitz 中打开使用就不行了

**Comment by ldypgod** [comment]
https://user-images.githubusercontent.com/100122128/200466803-15fb6cbd-b858-4959-8d09-010d75c98f43.mp4

**Comment by ldypgod** [comment]
@pengYYYYY 你看看我发的，实例是正常的，在 Stackblitz 中打开使用就不行，我自己本地也不行和在Stackblitz出现同样的问题
