### ISSUE TITLE
[Upload] 自定义上传方法下载修改进度没有生效（用法有误）

### ISSUE THREAD

**Issue by zrut747** [Tencent/tdesign-vue-next#1959]
### tdesign-vue-next 版本

0.24.5

### 重现链接

https://stackblitz.com/edit/angular-3p8sky?file=src%2Fdemo.vue,package.json

### 重现步骤

我参考文档的[自定义上传方法](https://tdesign.tencent.com/vue-next/components/upload?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0%E6%96%B9%E6%B3%95)写了上面那个demo，每秒修改一次file.percent，但是进度条并没有更新，只能从0%直接到下载完成的状态。

**Comment by chaishi** [comment]
完整正确的代码请看 https://stackblitz.com/edit/angular-3p8sky-ht4wjc?file=src%2Fdemo.vue

示例代码有两处错误：
1. `setTimout` 使用有误
2. 缺少 `files.value = [file]` 响应式赋值

```js
const timer = setInterval(() => {
  file.percent += 10;
  // 请注意 Vue3 通过 xxx.value 进行赋值，更新 DOM
  files.value = [file];
  if (file.percent >= 90) {
    clearInterval(timer);
  }
}, 1000);
```
