### ISSUE TITLE
[Table] 行编辑状态，透传的props并不是响应式变动的，无法做到编辑组件之间的联动

### ISSUE THREAD

**Issue by winfcloud** [Tencent/tdesign-vue-next#1960]
### 重现链接
https://stackblitz.com/edit/angular-p6rgmh?file=package.json

### 重现步骤
任意 Framework 列，原始数据是 "React" 的，进入编辑列后 Letters 的 option是 过滤后的，再之后编辑的 Framework 如果切换值，都不会影响 option的选项；
同理，如果 Framework 列原始数据不是 "React "，进入编辑后 Framework 选择 "React"， Letters 的 G/H 选项还是存在，校验通过后可以保存

编辑的props透传，只会在进入编辑的时候生效一次，进入编辑之后再改变值，联动失效

### 期望结果
编辑状态下， 各列会根据修改值响应式变化；
如果希望编辑状态不同列的值可以联动修改，使用组件自带的编辑表格目前无从下手

### 实际结果
联动代码，只会在进入编辑模式当次生效，之后修改值无效，除非保存后再进入编辑触发

### 补充说明
重现链接 使用的是Table页面"可编辑行的表格"
https://tdesign.tencent.com/vue-next/components/table
同一个代码实例，代码197行，对options进行了一次过滤，

实际上只有进入编辑模式时会触发一次props透传；

| Environment | Info |
|---|---|
| 相关版本 | 0.24.5 |
| 框架版本 / 基础库版本 | Vue(3.2.41) |
| 系统、浏览器 | Chrome(版本 106.0.5249.119（正式版本) 64位 |
| Node版本 | 14.18.1 |

**Comment by chaishi** [comment]
resolved in 0.24.9
