### ISSUE TITLE
[Input] 设置了format属性的输入框在有默认值的情况下为什么不format之后展示呢，设计如此吗

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#1964]
### tdesign-vue-next 版本

0.24.5

### 重现链接

https://stackblitz.com/edit/angular-blnqq1?file=src%2Fdemo.vue

### 期望结果

有默认值的情况下，格式化之后展示
![image](https://user-images.githubusercontent.com/54022918/199925514-d1ccedcb-667c-46c7-aeb2-f5802394f0c0.png)

### 实际结果

默认值没有format
![image](https://user-images.githubusercontent.com/54022918/199925615-4ded6d50-c622-454d-ad35-59bc4a9f2114.png)

**Comment by chaishi** [comment]
凡事非聚焦状态都应该 `format`，默认情况也应该如此，

此处处理不完善，待继续修正

如果业务是为了处理数字，建议使用 InputNumber，更规范更准确，同样支持 `format`

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/1968

默认值支持 `format` 呈现
