### ISSUE TITLE
[t-popup] 点击内容可自动收起浮层

### ISSUE THREAD

**Issue by vikyd** [Tencent/tdesign-vue-next#1971]
### 这个功能解决了什么问题

当以 [t-popup] 作为顶部菜单弹出层时，点击内容可若自动收起浮层，可避免遮挡。

### 你建议的方案是什么

[t-popup] 点击内容可自动收起浮层

**Comment by vikyd** [comment]
发现组件有 expose 方法 handleClose，暂可通过 ref 拿到组件实例，再调用实例的 handleClose 方法即可。

**Comment by pengYYYYY** [comment]
自行控制哈
