### ISSUE TITLE
Radio组件 中填充型单选按钮二次封装组件后样式不起作用

### ISSUE THREAD

**Issue by wfc66986** [Tencent/tdesign-vue-next#1973]
### tdesign-vue-next 版本

0.24.5

### 重现链接

https://stackblitz.com/edit/angular-knwe4r?file=src%2Fdemo.vue,src%2FwfcRadioButton.vue

### 重现步骤

二次封装就不行了

**Comment by pengYYYYY** [comment]
<img width="1582" alt="image" src="https://user-images.githubusercontent.com/35833812/200461084-692dc8b2-03dc-4f9b-9e52-db267d0760b5.png">

看起来表现正常

**Comment by pengYYYYY** [comment]
样式问题排查一下你设置的样式权重
