### ISSUE TITLE
[t-upload] 如何自行实现 file-flow？目前拿到的 files 是已上传的文件列表，非正在上传的文件列表

### ISSUE THREAD

**Issue by vikyd** [Tencent/tdesign-vue-next#1976]
### 这个功能解决了什么问题

目前拿到的 files 是已上传的文件列表

### 你建议的方案是什么

希望也能拿到已选中的文件列表，及其 status，类似于实现自定义的 theme file-flow。

**Comment by chaishi** [comment]
后面会支持使用 `fileListDisplay` 自定义列表，包含全部 已上传 、 待上传、上传失败文件

Vue2 已支持，Vue3 在路上

**Comment by chaishi** [comment]
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/1978
