### ISSUE TITLE
[t-date-range-picker] 日期选择器自定义前置图标样式错误

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#1982]
### tdesign-vue-next 版本

0.24.5

### 重现链接

https://tdesign.tencent.com/vue-next/components/date-picker?tab=demo

### 重现步骤

官网demo就有这个问题
![image](https://user-images.githubusercontent.com/54022918/200505690-a6691cb2-b201-4a0d-85d0-0e720420dfae.png)

### 期望结果

前置图标样式大小正常

### 实际结果

前置图标样式明显变小甚至看不清

**Comment by sunjiesama** [comment]
hello？

**Comment by ccccpj** [comment]
感谢反馈，新版本问题已修复～
