### ISSUE TITLE
[TagInput] TagInput被作为Table的自定义筛选组件传入时报出空引用错误

### ISSUE THREAD

**Issue by cloudfun** [Tencent/tdesign-vue-next#1983]
### tdesign-vue-next 版本

0.24.5

### 重现链接

https://tdesign.tencent.com/vue-next/components/tag-input?tab=demo

### 重现步骤

`filter: {
        type: 'custom',
        component: TagInput,
        resetValue: [],
        confirmEvents: ['onEnter'],
        showConfirmAndReset: true,
    },`

### 期望结果

组件正常渲染

### 实际结果

报出空引用错误: TypeError: Cannot read properties of undefined (reading 'length')

### 框架版本

Vue(3.2.41)

### 浏览器版本

Chrome(107.0.5304.87)

### 系统版本

MacOS(13.0)

### 补充说明

很显然, Table的custom filter传入了undefined的filterValue, TabInput没有检查value是undefined的情况

<img width="687" alt="image" src="https://user-images.githubusercontent.com/962598/200506531-d0224a7e-b350-409b-9b48-368a09dcf3f9.png">

报错位置:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/962598/200506353-f7611ff2-a06d-45ec-9920-9ab13fe99c61.png">

**Comment by chaishi** [comment]
设置一下 filterValue.tagInput 的初始值为`[]` 就好了
