### ISSUE TITLE
[table] 表格行内编辑问题

### ISSUE THREAD

**Issue by freeopsvue** [Tencent/tdesign-vue-next#1985]
### tdesign-vue-next 版本

0.24.2

### 重现链接

无

### 重现步骤

1、表格启用行内编辑，部分配置如下
` {
            colKey: "code",
            title: "字典编码",
            edit: {
                component: Input,
                props: {
                    clearable: true,
                    autofocus: true,
                    autoWidth: true,
                },
                showEditIcon: false,

            }
        },`
2、表格加载时，让这列数据为空
3、发现无法编辑该列

### 期望结果

点击该列的单元格即可进行编辑

### 实际结果

数据为空时，该列空单元格无法编辑

### 系统版本

win11

### Node版本

14.17.6

**Comment by chaishi** [comment]
```css
.t-table__cell--editable {
  min-height: 22px;
}
```

当前，你可以通过设置这样的 CSS 解决问题

**Comment by chaishi** [comment]
resolved in `v0.24.9`
