### ISSUE TITLE
[Table] 希望能为列增加 maxWidth 参数

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-vue-next#1986]
### 这个功能解决了什么问题

列宽度不会超过 maxWidth 所限制的宽度

### 你建议的方案是什么

目前 columns 有 minWidth 和 width，这两个参数在当列宽总和小于 table 元素时都会自动拉宽，希望能增加 maxWidth 或更改 width 的表现 使其能够在任何情况下都对列定宽

**Comment by chaishi** [comment]
> 目前 columns 有 minWidth 和 width，这两个参数在当列宽总和小于 table 元素时都会自动拉宽，希望能增加 maxWidth 或更改 width 的表现 使其能够在任何情况下都对列定宽

“期望在任何情况下都对列定宽” 这个要看具体场景，
场景一：如果每一列都设置了定宽，table 宽度也定死，这样不同屏幕的大小无法宽度自适应。凡事希望宽度自适应的，就不能所有列设置定宽，table 宽度也不能定死。如果确实不需要表格随不同屏幕自适应，全部定死宽度，那设置每一列的宽度刚好等于 table 宽度即可。


场景二：期望部分列定宽，其他列宽度随屏幕自适应，只需设置部分列 `width` 即可满足需求

提供一下你的具体宽度需求场景，大概率不需要 maxWidth 也能解决你的问题

**Comment by chaishi** [comment]
- 普通场景，组件暂时不新增支持，业务可以设置 内部元素的本身的 `maxWidth`。
- `resizable` 可调整列宽场景，设置 `:columns="[{ resize: { minWidth: 120, maxWidth: 300 } }]"` 限制
