### ISSUE TITLE
文档中的 [Dialog 对话框] draggable 没有反应

### ISSUE THREAD

**Issue by ibmsoft** [Tencent/tdesign-vue-next#1993]
### tdesign-vue-next 版本

24.6

### 重现链接

https://tdesign.tencent.com/vue-next/components/dialog#app

### 重现步骤

draggable 打开不起作用

### 期望结果

能拖拽 Dialog

### 实际结果

不能

**Comment by sechi747** [comment]
仅非模态弹窗支持拖拽，需要把`mode`设置为`modeless`

**Comment by ibmsoft** [comment]
> 仅非模态弹窗支持拖拽，需要把`mode`设置为`modeless`

试了下，设置成 modeless后可以了，然后，再换成其他的也都可以了
