### ISSUE TITLE
[image] 图片组件的 overlayContent slot 无效

### ISSUE THREAD

**Issue by dodu2014** [Tencent/tdesign-vue-next#1996]
### tdesign-vue-next 版本

0.24.6

### 重现链接

https://tdesign.tencent.com/vue-next/components/image?tab=demo

### 重现步骤

slot overlayContent 无效

### 期望结果

fix

### 框架版本

vue 3.2.0

### 浏览器版本

edge 107

### 系统版本

windows 11

**Comment by sockite** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
