### ISSUE TITLE
[EnhancedTable] 调用过该组件实例的方法后，组件实例的相关方法（method）丢失！

### ISSUE THREAD

**Issue by chnykn** [Tencent/tdesign-vue-next#1999]
### tdesign-vue-next 版本

0.24.6

### 重现链接

https://tdesign.tencent.com/vue-next/components/table

官方网站提供的例子，同样可报错（**第二次点击，才会出错！**），如下：
![err](https://user-images.githubusercontent.com/4152089/201446101-e8a399a7-64b0-4616-ac10-74198f2aa6ab.png)

### 重现步骤

**先决条件**：必须是npm run build 之后的dist代码，npm run dev的方式不会出错。

**重现步骤**：
1、vue文件的<template>部分有如下代码：
```
<enhanced-table
    ref="table"
    ... ...
>
<enhanced-table>
```
2、vue文件的<script>部分，代码中如果有 table.value.XXX的调用，其中XXX是调用的table.value作为 EnhancedTableInstanceFunctions 的相关方法，比如appendTo、getData等，首次执行是不出错的。

3、vue文件的<script>部分，再次执行EnhancedTableInstanceFunctions 的相关方法（不需要跟上次执行的相同），就会出现 `TypeError: e.value.XXX is not a function` 。该错误信息中的e，因build的版本原因，其实指的是table，XXX是EnhancedTableInstanceFunctions中的方法名。

**可能的原因**：
EnhancedTable的实例，在调用EnhancedTableInstanceFunctions相关方法后，table的实例有可能变成了PrimaryTable类型，导致所有作为EnhancedTable类型的EnhancedTableInstanceFunctions不能使用了。

最后，该问题在两周前也有人提过 [https://github.com/Tencent/tdesign-vue-next/issues/1911](url)，只是他没有描述清楚问题

### 框架版本

tdesign-vue-next: 0.24.6,   vue: 3.2.41,  vite: 3.2.3, vue-tsc: 1.0.9

**Comment by chaishi** [comment]
知道是从哪个版本开始不行的吗，之前是可以的，我去查一下代码变动

**Comment by chaishi** [comment]
从编译结果来看，暴露了 `expose` 相关方法

<img width="702" alt="image" src="https://user-images.githubusercontent.com/11605702/201459758-e9fe5053-2bf9-47cd-8c1e-86048fbb8bec.png">

**Comment by chaishi** [comment]
源代码修改如下， `ref={primaryTableRef}` 从前面挪到后面。
```
<PrimaryTable ref={enhancedTableRef} v-slots={context.slots} {...enhancedProps} />
```
修改为
```
<PrimaryTable v-slots={context.slots} {...enhancedProps} ref={primaryTableRef} />
```

属性顺序，导致了 npm run dev 正常，而 npm run build 异常

**Comment by chnykn** [comment]
@chaishi 英明！

**Comment by chnykn** [comment]
@chaishi 罗雪同学，周末还加班啊？

**Comment by chaishi** [comment]
@chnykn 我都是周末在线，平时忙业务
