### ISSUE TITLE
[Bug][Select]下拉框选项显示异常

### ISSUE THREAD

**Issue by baozoulolw** [Tencent/tdesign-vue-next#201]
下拉框选项样式的错误
![QQ截图20220113222604](https://user-images.githubusercontent.com/31173826/149348405-0bf32b88-0c2c-4688-ba0d-60a7e6ba116a.png)
![QQ截图20220113222615](https://user-images.githubusercontent.com/31173826/149348410-aa9fa47e-84ed-45ce-8ca4-7dc68bfa6455.png)
![QQ截图20220113222711](https://user-images.githubusercontent.com/31173826/149348479-86b75fdd-c488-47e9-84ad-fa4986ba42e5.png)

**Comment by pengYYYYY** [comment]
项目引了reset吗？

**Comment by baozoulolw** [comment]
> 项目引了reset吗？

并没有，就所有的下拉类的组件都出现了类似的问题

**Comment by pengYYYYY** [comment]
你可以在现在的版本用一下,下个版本 `reset` 会在包装在组件里面

```js
import 'tdesign-vue-next/es/style/index.css';
```

**Comment by pengYYYYY** [comment]
已修复
