### ISSUE TITLE
[Bug][Input] flex布局下 button按钮的宽度会出现问题

### ISSUE THREAD

**Issue by baozoulolw** [Tencent/tdesign-vue-next#202]
当按钮处于flex布局的div盒子里面时会出现此问题
![QQ截图20220113223654](https://user-images.githubusercontent.com/31173826/149350053-8cdafecc-ac3a-4802-ba73-4713ec913ccf.png)

**Comment by baozoulolw** [comment]
如果和一个input之类的组件放在一个flex row div中，而且input未指定宽度会出现此问题

**Comment by pengYYYYY** [comment]
可以给一个codesandbox嘛

**Comment by vnues** [comment]
是的，建议给个代码段，目前很难get你说的点，这块我跟开发者跟进下

**Comment by pengYYYYY** [comment]
0.8.0 已修复
