### ISSUE TITLE
[DateRangePicker] size属性失效

### ISSUE THREAD

**Issue by cloudfun** [Tencent/tdesign-vue-next#2022]
### tdesign-vue-next 版本

0.24.6

### 重现链接

https://tdesign.tencent.com/vue-next/components/date-picker

### 重现步骤

官方示例中DateRangePicker设置size属性无效,实际项目中使用也确实是这样。

### 框架版本

Vue(3.2.41)

### 浏览器版本

Chrome(107.0.5304.87)

### 系统版本

MacOS(13.0)

### 补充说明

<img width="1114" alt="image" src="https://user-images.githubusercontent.com/962598/202189777-7c78920d-3c2f-43d2-a3da-4604052808fc.png">

**Comment by pengYYYYY** [comment]
已经废弃的API,后面会删掉
