### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by supmry** [Tencent/tdesign-vue-next#2023]
### tdesign-vue-next 版本

0.24.0

### 重现链接

请求添加status的default,与文档的状态一样 default/success/warning/error

### 重现步骤

使用：
          <template #changePoint="{ row }">
            <t-textarea
              v-if="row.isAffect === '是' || row.useCaseChangeType === '新增'"
              v-model="row.changePoint"
              :status="`${row.changePoint ? 'default' : 'error'}`"
              :tips="`${row.changePoint ? '' : '变更点不能为空'}`"
            />
          </template>
报错：Invalid prop: custom validator check failed for prop "status". 
  at <TTextarea key=0 modelValue="666" onUpdate:modelValue=fn<onUpdate:modelValue>  ... > 
原因：t-textarea组件的status属性没有文档上的‘default’,我需要动态给textarea的status赋值时只能通过v-if---else写两遍，赋值null和undefined都报错。
![image](https://user-images.githubusercontent.com/16367988/202197716-f88dba46-7894-4c5a-87c0-87616fb01116.png)
![image](https://user-images.githubusercontent.com/16367988/202197860-e52ed592-d0c5-4c5d-aba2-32d56d08aa92.png)
解决方案：请求技术小哥在\tdesign-vue-next\es\textarea\props.mjs第32行加上‘default’

### 期望结果

请求技术小哥在\tdesign-vue-next\es\textarea\props.mjs第32行加上‘default’

### 实际结果

Invalid prop: custom validator check failed for prop "status". 
  at <TTextarea key=0 modelValue="666" onUpdate:modelValue=fn<onUpdate:modelValue>  ... >

**Comment by supmry** [comment]
请求在\tdesign-vue-next\es\textarea\props.mjs第32行加上‘default’

**Comment by pengYYYYY** [comment]
收到

**Comment by supmry** [comment]
感谢官方支持
