### ISSUE TITLE
[Loading] v-loading 方式使用时会爆出警告

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-vue-next#2025]
### tdesign-vue-next 版本

0.24.7

### 重现步骤

v-loading 方式使用时会爆出警告：
inject() can only be used inside setup() or functional components.

**Comment by chaishi** [comment]
没有这个指令

**Comment by PDieE** [comment]
> 没有这个指令

https://tdesign.tencent.com/vue-next/components/loading#%E6%8C%87%E4%BB%A4%E6%96%B9%E5%BC%8F%E8%B0%83%E7%94%A8

指令方式调用呀

**Comment by uyarn** [comment]
修复过了应该 升级到0.24.5以上就可以

**Comment by PDieE** [comment]
> 修复过了应该 升级到0.24.5以上就可以

升级到 0.24.7 以后依然如此，然后我看了官网的示例也是一样的

![image](https://user-images.githubusercontent.com/14084550/202596189-37c8333c-f0e4-4f9c-9f6b-8ca316efa4fe.png)

**Comment by Aicmortal** [comment]
> > 修复过了应该 升级到0.24.5以上就可以
> 
> 升级到 0.24.7 以后依然如此，然后我看了官网的示例也是一样的
> 
> ![image](https://user-images.githubusercontent.com/14084550/202596189-37c8333c-f0e4-4f9c-9f6b-8ca316efa4fe.png)
我这边倒是正常可以用
![微信截图_20221118102156](https://user-images.githubusercontent.com/16420004/202602037-a98cd663-c6c3-472b-a001-76de86313afe.png)

**Comment by PDieE** [comment]
> > > 修复过了应该 升级到0.24.5以上就可以
> > 
> > 
> > 升级到 0.24.7 以后依然如此，然后我看了官网的示例也是一样的
> > ![image](https://user-images.githubusercontent.com/14084550/202596189-37c8333c-f0e4-4f9c-9f6b-8ca316efa4fe.png)
> > 我这边倒是正常可以用
> > ![微信截图_20221118102156](https://user-images.githubusercontent.com/16420004/202602037-a98cd663-c6c3-472b-a001-76de86313afe.png)

使用是没问题，你看控制台，每一次v-loading的值变成true的时候都会爆一次警告，我提的也是这个警告的问你题

**Comment by uyarn** [comment]
知道了 因为classPrefix那个hook在loading plugin里面没在component里调用..
