### ISSUE TITLE
[Bug][Cascader] 可过滤的级联选择器样式出错

### ISSUE THREAD

**Issue by Wen1kang** [Tencent/tdesign-vue-next#203]
## tdesign-vue-next

You will open a bug issue at tdesign-vue-next。

### Describe Environment

browser version:Chrome 97.0.4692.71
tdesign-vue-next version:0.6.3

### Describe the bug

可过滤的级联选择器展开选择框时，同时出现两个输入框
![image](https://user-images.githubusercontent.com/89069385/149465109-600f7f1f-ce73-4db9-b406-58d155638ec3.png)

**Comment by pengYYYYY** [comment]
已经处理了https://github.com/Tencent/tdesign-vue-next/pull/195
