### ISSUE TITLE
[Upload]第一次文件上传成功后，点击“重新选择”没有反映

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#2032]
### tdesign-vue-next 版本

0.24.7

### 重现链接

https://tdesign.tencent.com/vue-next/components/upload?tab=demo#%E5%8D%95%E6%96%87%E4%BB%B6-%E5%9B%BE%E7%89%87%E6%8B%96%E6%8B%BD%E4%B8%8A%E4%BC%A0

### 重现步骤

随便 上传一张图片 ，上传成功后点击“重新选择”

### 期望结果

点击“重新选择”后可以再次上传图片 

### 实际结果

没反映

### Node版本

v14.19.1

**Comment by Zzongke** [comment]
Hello, would you like to ask whether you upload pictures with the same file name?

**Comment by chaishi** [comment]
给出官网地址，问题没有复现，体验视频如下，


https://user-images.githubusercontent.com/11605702/205455225-9d334eb0-3386-4f18-af27-f41a61b36439.mov

**Comment by chaishi** [comment]
版本号是 `0.24.7`，当前最新版本号为 `0.25.0`，辛苦升级版本之后尝试

也辛苦提供一个正确的可复现问题的链接，方便我们快速定位问题，并解决问题。

<img width="903" alt="image" src="https://user-images.githubusercontent.com/11605702/205455375-65c4a3a3-1548-447e-a11c-0d7c2556c599.png">

**Comment by chaishi** [comment]
issue 关闭，待提供可正确复现问题的示例代码链接后，可以再 reopen
