### ISSUE TITLE
[drawer] 抽屉内使用 from表单校验规则无效bug

### ISSUE THREAD

**Issue by zhairy** [Tencent/tdesign-vue-next#2038]
### tdesign-vue-next 版本

0.24.7

### 重现链接

https://stackblitz.com/edit/angular-ae725a?file=package.json,src%2Fdemo.vue

### 重现步骤

在抽屉中  使用了自定义底部或者头部 按钮后，按钮type  设置submit  表单的校验规则 无法生效，同样在diaolog 中使用  确认有效！

### 期望结果

希望尽快纠正哈

**Comment by chaishi** [comment]
https://stackblitz.com/edit/angular-ae725a-8ktqfc?file=package.json,src%2Fdemo.vue
当前，你可以按照链接中的方式，使用 `formRef.value.validate()` 解决问题

**Comment by chaishi** [comment]
当前，你的写法行不通，是因为按钮没有在 `<form>` 元素中，独立在外面的，此时的 `type=submit` 无效

<img width="756" alt="image" src="https://user-images.githubusercontent.com/11605702/219011170-b90e083c-a7dc-40cc-bbf5-c001509c6528.png">

**Comment by chaishi** [comment]
https://stackblitz.com/edit/angular-ae725a-8ktqfc?file=package.json,src%2Fdemo.vue

这是我尝试的 Dialog 同样的用法，按钮 `<button type="submit" />` 没有在 <form> 元素中，也是无法校验的

**Comment by chaishi** [comment]
由于问题属于使用问题，组件无需处理。issue close

如果还有其他的疑问，可以再单独 提 issue

**Comment by williambao** [comment]
@chaishi 那怎么使用可以实现这个？ 比如drawer中，使用底部的按钮来提交form
