### ISSUE TITLE
[Improve][Button] 按钮过渡效果，使人极其难受。 

### ISSUE THREAD

**Issue by wangdaoo** [Tencent/tdesign-vue-next#204]
## tdesign-vue-next

You will open an feature issue at tdesign-vue-next

![image](https://user-images.githubusercontent.com/28971754/149471044-0e4bebae-767b-4367-bea2-be5f0543308f.png)

点击过渡效果，无论点击什么位置，都是从左往右的过渡？

非常难受的设计！望优化

**Comment by Wen1kang** [comment]
你好，我是TDesign的设计师，这里的过渡是采用腾讯斜8度的图形，我们也在不断优化这里的过渡效果同时提供可关闭斜8度动画效果，后续Q1会一个版本发布，让大家更加无感和明确操作，以后也会根据鼠标事件判断从左到右还是从右到左。

**Comment by yangjunjun** [comment]
希望提供一个开关，并且最好可以提供可以自定义的方法，毕竟这是开源，不是所有的公司喜欢你们“腾讯斜8度”的过渡的。

**Comment by Wen1kang** [comment]
嗯呢，未来我们会提供开关选项的，如果目前实在干扰你，用户还是可以自定义进行删除

**Comment by pengYYYYY** [comment]
0.9.3 已修复
