### ISSUE TITLE
[Dropdown] 下拉菜单多点几次后就不出现下拉菜单了

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#2044]
### tdesign-vue-next 版本

0.24.7

### 重现链接

https://stackblitz.com/edit/angular-wae3pj-invtep?file=src/demo.vue

### 重现步骤

查看视频
<video src="https://user-images.githubusercontent.com/2550216/175182771-76849877-afe3-4049-b482-c1dc6eb2605a.MOV"></video>

挨个点击“选项一”，“选项二”，“选项三",多重复几次即可

### 期望结果

下拉菜单每次都能显示

### 实际结果

不显示

**Comment by Alsmile** [comment]
+1，严重bug不修复，给 item 设置固定高度，看不懂？？？？？？？？？？不允许自定义个性化子选项？

![image](https://user-images.githubusercontent.com/1797302/203476553-81a67649-441e-446a-9913-dc7df84fdf85.png)

**Comment by uyarn** [comment]
> +1，严重bug不修复，给 item 设置固定高度，看不懂？？？？？？？？？？不允许自定义个性化子选项？
> 
> ![image](https://user-images.githubusercontent.com/1797302/203476553-81a67649-441e-446a-9913-dc7df84fdf85.png)

在新增尺寸相关的Token 这里不合理 我们去掉 今天再发给版本处理
