### ISSUE TITLE
[input-number] 无法输入小数点

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#2045]
### 重现链接
https://tdesign.tencent.com/vue-next/components/input-number#%E5%B8%A6%E5%B0%8F%E6%95%B0%E7%9A%84%E6%95%B0%E5%AD%97%E8%BE%93%E5%85%A5%E6%A1%86

### 重现步骤
带小数的数字输入框，选中输入框，输入带小数点的数字，小数点输入无效，粘贴可以

### 期望结果
可输入小数点

### 实际结果
无法输入小数点

| Environment | Info |
|---|---|
| 相关版本 | 0.24.7 |
| 框架版本 / 基础库版本 | Vue(3.2.12) |
| 系统、浏览器 | MacOS(12)、Chrome(107.0.5304.107) |
| Node版本 | 14 |

**Comment by chaishi** [comment]
这个已经修复，我找人发布下新版本
