### ISSUE TITLE
[Menu] 升级 0.24.8 后，菜单样式出问题

### ISSUE THREAD

**Issue by candy-Tong** [Tencent/tdesign-vue-next#2051]
### tdesign-vue-next 版本

0.24.8

### 重现链接

https://tdesign.tencent.com/vue-next/components/menu

### 重现步骤

![image](https://user-images.githubusercontent.com/20377280/203499070-748b5198-39ec-4cd9-8725-92c3b9936052.png)
菜单样式出问题

**Comment by candy-Tong** [comment]
![image](https://user-images.githubusercontent.com/20377280/203499532-cbc895f5-2419-48a0-8e75-b689c3195292.png)

**Comment by pengYYYYY** [comment]
晚些会发一个补丁版本

**Comment by candy-Tong** [comment]
好的，忘了先查看 issue，抱歉
