### ISSUE TITLE
[link] 不配置任何参数或点击事件控制台会报红

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#2057]
### 重现链接
https://tdesign.tencent.com/vue-next/components/link

### 重现步骤
打开官方组件库样例link组件，点击任意demo

### 期望结果
控制台不会有报错信息

### 实际结果
控制台报错
![image](https://user-images.githubusercontent.com/20508822/203670745-8b5833cf-505e-4485-9167-edd2cd85a600.png)

| Environment | Info |
|---|---|
| 相关版本 | 0.24.8 |
| 框架版本 / 基础库版本 | Vue(3.2.12) |
| 系统、浏览器 | MacOS(12),Chrome(101) |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
线上未发现此问题

https://user-images.githubusercontent.com/35833812/204949303-a458c9c9-5f4d-4f16-b287-2f06b92539f0.mov
