### ISSUE TITLE
[menu] 当主题为dark的时候，建议弹出层的子菜单滚动条与背景有个对比色

### ISSUE THREAD

**Issue by dianjie** [Tencent/tdesign-vue-next#2060]
### 这个功能解决了什么问题

让用户知道容器外还有更多子菜单，向下滚动可查看。
![image](https://user-images.githubusercontent.com/16601627/203709927-434d0b1b-0dae-4b7b-b2d3-085ecef3e9eb.png)

### 你建议的方案是什么

建议弹出层的子菜单滚动条与背景有个对比色

**Comment by uyarn** [comment]
cc @Wen1kang

**Comment by Wen1kang** [comment]
这里应该是亮色模式使用了深色主题的导航栏，导致scroll bar没有切换颜色，这里应该要把menu的scroll bar颜色跟随menu主题转变，不受整体暗黑模式切换改变
