### ISSUE TITLE
[Table] 分页场景下，设置 max-height 和 bordered 之后，边框线位置不正确

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#2062]
### tdesign-vue-next 版本

0.24.9

### 重现步骤

![image](https://user-images.githubusercontent.com/10460238/203751955-25f50f8d-aa7f-47cf-b233-1bb6b48d2e5b.png)
官网也会复现

### 期望结果

最后竖线别越界

### 实际结果

最后竖线越界

**Comment by chaishi** [comment]
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/11605702/204132164-58007c86-33bd-4310-a50a-59dbc383ef73.png">

**Comment by chaishi** [comment]
当前可以设置 `.t-table__scroll-bar-divider { top: 0 }` 解决问题

后续，TD 会修复这个问题

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/1849
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/2074
