### ISSUE TITLE
[table] 带吸顶或吸底的有边框的表格右侧固定列会错位（tdesign-starter）

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#2064]
### 重现链接
https://stackblitz.com/edit/vitejs-vite-l5pkzp?file=src/pages/list/base/index.vue

### 重现步骤
官方demo的基础列表页中，给`Table`组件添加`bordered`属性

### 期望结果
应该与组件库内官方demo表现一致，只是改变边框属性，右侧固定列不应该出现样式错位

### 实际结果
出现了样式错位
![image](https://user-images.githubusercontent.com/20508822/203754670-0ef73bd3-593b-4c41-9217-4658ec182367.png)

### 补充说明
经过排查，大致是`tdesign-vue-next-starter`样式文件`reset.less`内全局设置了`box-sizing: border-box`，影响了`Table`组件吸顶与吸底部分的盒子模型表现，产生了异常
<img width="332" alt="image" src="https://user-images.githubusercontent.com/20508822/203755411-7098cca0-1ddc-4442-ab0c-39d952b1241b.png">

| Environment | Info |
|---|---|
| 相关版本 | - |
| 框架版本 / 基础库版本 | Vue(^3.2.31) |
| 系统、浏览器 | MacOS(12) 、Chrome(101) |
| Node版本 | 14 |

**Comment by pengYYYYY** [comment]
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/35833812/212856996-c0f16c4f-15b8-4947-9c76-152ae1a0a383.png">
新版starter已修复
