### ISSUE TITLE
[Table]  serial-number不随页面切换而变化

### ISSUE THREAD

**Issue by koko01024122** [Tencent/tdesign-vue-next#2072]
### tdesign-vue-next 版本

0.24.9

### 重现步骤

t-table绑定多页数据 
设定首列colKey为 serial-number
点击切换页码

### 期望结果

首列序号随翻页变化

### 实际结果

首列序号不随翻页变化

### 系统版本

Windows10

### Node版本

16.15.1

**Comment by chaishi** [comment]
这个问题开发的时候也在思考，这个是否需要随页面切换发生变化。

有的要，有的又不

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2074
