### ISSUE TITLE
[ColorPicker] 想要函数式调用 

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#2076]
### 这个功能解决了什么问题

任意地方调用颜色选择器

### 你建议的方案是什么

像MessagePlugin,或者DialogPlugin一下，引入后就可以随时随地调用 ,如
```
ColorPicker.show()
ColorPicker.hide();
```

**Comment by pengYYYYY** [comment]
暂时不会考虑这样的支持

**Comment by arieslee** [comment]
> 暂时不会考虑这样的支持

那只有引入第三方的颜色选择器了^_^
