### ISSUE TITLE
[upload]:官方网站文档-upload上传-基础文件上传-中有文字错误

### ISSUE THREAD

**Issue by Zzongke** [Tencent/tdesign-vue-next#2078]
### 重现链接
https://tdesign.tencent.com/vue-next/components/upload

### 重现步骤
官方网站文档——upload上传——基础文件上传——的**allowUploadDuplicateFile是否允许上产具有相同文件名的文件**的文字不正确

### 期望结果
上传

### 实际结果
上产
<img width="1011" alt="截屏2022-11-28 19 08 49" src="https://user-images.githubusercontent.com/65376724/204266439-5d65d675-93a5-42c8-9d51-6bd7564756cf.png">

| Environment | Info |
|---|---|
| 相关版本 | 0.24.9 |
| 框架版本 / 基础库版本 | Vue(3.2.12) |
| 系统、浏览器 | MacOS(12.6) |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
收到，有兴趣可以提个PR修复一下

**Comment by Zzongke** [comment]
@pengYYYYY 非常有兴趣提交pr修复😄
