### ISSUE TITLE
Transfer value绑定回显问题

### ISSUE THREAD

**Issue by xuli569070328** [Tencent/tdesign-vue-next#2081]
### 重现链接
https://stackblitz.com/edit/angular-uxzuya?file=package.json,src%2Fdemo.vue

### 重现步骤
![1](https://user-images.githubusercontent.com/95893105/204412903-5d9e5060-4d46-4372-8349-d3e09ba66b58.png)

### 期望结果
:value 能正常回显绑定的transfer值

### 实际结果
:value 不能正常回显

| Environment | Info |
|---|---|
| 相关版本 | 0.24.9 |
| 框架版本 / 基础库版本 | 3.2.31 |
| 系统、浏览器 | Chrome 版本 107.0.5304.107（正式版本） （64 位） |
| Node版本 | v16.13.0 |

**Comment by xuli569070328** [comment]
> 



> 👋 @xuli569070328，感谢给 TDesign 提出了 issue。 请根据 issue 模版确保背景信息的完善，我们将调查并尽快回复你。

尽快回复尽快回复

**Comment by pengYYYYY** [comment]
值需要为叶子结点，tree的值具使用参考tree组件

**Comment by xuli569070328** [comment]
> 值需要为叶子结点，tree的值具使用参考tree组件

好的,谢谢,已解决
