### ISSUE TITLE
[Upload 上传] 能否增加一个新数据字段firstFile

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#2086]
### 这个功能解决了什么问题

方便单文件上传直接获取url

### 你建议的方案是什么

增加一个新数据字段firstFile，为files[0].url

**Comment by chaishi** [comment]
没有明白具体需求是什么，可以的话，辛苦再描述清楚些

**Comment by chaishi** [comment]
长时间没有回复，且看不明白需求，issue 关闭

如果后面还有疑问，可以描述清楚后，再 reopen
