### ISSUE TITLE
[table] column.filter属性增加popup的相关配置项

### ISSUE THREAD

**Issue by wandoupeas** [Tencent/tdesign-vue-next#2088]
### 这个功能解决了什么问题
在dialog中使用table组件时，若数据较少，使用列筛选的时候会出现dialog内部滚动条，产生页面抖动，体验感不是很好，增加filter对应的popup的相关配置，比如attach属性，可以将相应的filter弹框绑定至body等外部dom，这样不会产生抖动
![image](https://user-images.githubusercontent.com/20508822/204724094-cc326700-d38e-447f-8607-4314268c1558.png)
![image](https://user-images.githubusercontent.com/20508822/204724183-fa4d898e-4057-4327-bd14-96a0553d3140.png)

### 你建议的方案是什么？
类似这种：

```
filter: {
  component: DateRangePickerPanel,
  popupProps: {
    attach: 'body',
  },
  props: {
    firstDayOfWeek: 7,
    presets: {
      最近7天: [dayjs().subtract(6, 'day'), dayjs()],
      最近3天: [dayjs().subtract(2, 'day'), dayjs()],
      今天: [dayjs(), dayjs()],
    },
  }
};
```

**Comment by chaishi** [comment]
可以新增一个 `filter.popupProps` 透传 Popup 组件属性

**Comment by chaishi** [comment]
resolved in resolved in https://github.com/Tencent/tdesign-vue-next/pull/2105
