### ISSUE TITLE
[TagInput] 关于该组件对中文的支持的疑问

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#2091]
### tdesign-vue-next 版本

0.24.9

### 重现链接

https://tdesign.tencent.com/vue-next/components/tag-input?tab=demo

### 重现步骤

不知道这个组件设计的时候是否支持中文？输入拼音后，按删除键会直接删除输入框内已有的标签，详情效果gif
![GIF 2022-11-30 16-30-00](https://user-images.githubusercontent.com/54022918/204745972-0137fea0-80ab-4470-b137-e0e840f7c021.gif)

### 期望结果

正常输入中文

### 实际结果

不能正常输入中文

**Comment by sunjiesama** [comment]
hello?

**Comment by chaishi** [comment]
重复 issue

这个问题已在最新版本 `0.25.0` 中修复，请升级版本号之后尝试。
变更日志：https://tdesign.tencent.com/vue-next/changelog

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/11605702/205455704-0349ccc2-ac5c-4869-a1e1-28c88a80891a.png">
