### ISSUE TITLE
[InputNumber] 无法在小数点后的最后一位直接输入0

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#2103]
### tdesign-vue-next 版本

最新版

### 重现链接

https://codesandbox.io/s/bug-td-select-showarrow-forked-61iexf?file=/src/App.vue

### 重现步骤

rt

### 期望结果

可以通过键盘直接输入0.01

### 实际结果

无法输入

### 框架版本

3.2.x

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2107
