### ISSUE TITLE
[Table] 无数据，全局设置通用结果显示，高度被限制，显示不全

### ISSUE THREAD

**Issue by dmyz** [Tencent/tdesign-vue-next#2104]
### tdesign-vue-next 版本

0.25.0

### 重现链接

[地址](https://stackblitz.com/edit/angular-ermqd5?file=src/demo.vue)

### 重现步骤

![1669966597110](https://user-images.githubusercontent.com/15307200/205240662-de9b6e3d-7674-4514-b035-ff43d140e334.jpg)
![1669966751649](https://user-images.githubusercontent.com/15307200/205240739-2eff5883-e1a9-4225-9c00-a62f24350c1d.png)

### 期望结果

没有遮挡，正常显示
![1669966844682](https://user-images.githubusercontent.com/15307200/205241063-581fe749-8275-4b3f-8162-09886b38da72.png)

### 实际结果

有遮挡显示不全

### 框架版本

3.2.45

**Comment by chaishi** [comment]
下次点击这里，提供复现问题的示例代码链接，可以让 issue 处理起来更快

<img width="912" alt="image" src="https://user-images.githubusercontent.com/11605702/205443842-087f2ea2-09dd-44f8-af71-e3c13ecf649e.png">

**Comment by dmyz** [comment]
@chaishi [连接](https://stackblitz.com/edit/angular-ermqd5?file=src/demo.vue)9

**Comment by chaishi** [comment]
当前处理方式：调整 `.t-table__empty` 的 `height: 200px` 为 `min-height: 200px` 即可

<img width="1501" alt="image" src="https://user-images.githubusercontent.com/11605702/205450745-673a7897-459f-49ca-8494-299bdea7b55d.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-common/pull/1063
