### ISSUE TITLE
[TagInput] windows下拼音输入时，按下删除键触发删除标签 此问题在0.25版本依然存在

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#2110]
### tdesign-vue-next 版本

0.25.0

### 重现链接

https://tdesign.tencent.com/vue-next/components/tag-input?tab=demo

### 重现步骤

操作系统：win11
chrome版本：107.0.5304.88
在删除最后一个拼音时依然会触发删除标签

### 期望结果

正常输入删除

### 实际结果

异常输入删除

**Comment by sunjiesama** [comment]
![GIF 2022-12-5 8-59-37](https://user-images.githubusercontent.com/54022918/205527510-d53ae174-10ff-4008-a99d-58cb5c0cc029.gif)

**Comment by chaishi** [comment]
明白了，是最后一个字符的处理漏了

**Comment by dianjie** [comment]
@chaishi https://github.com/vuejs/vue/issues/10277#issuecomment-873337252
可能是这个的问题，本地调试keyup触发了两次
