### ISSUE TITLE
[Tree] TreeInstanceFunctions是不是有问题，实例方法有可能不存在？

### ISSUE THREAD

**Issue by dmyz** [Tencent/tdesign-vue-next#2113]
### tdesign-vue-next 版本

0.25.0

### 重现步骤

![image](https://user-images.githubusercontent.com/15307200/205579240-83aa6583-c822-4b35-92e5-c2f208622043.png)

**Comment by pengYYYYY** [comment]
都是存在的，ts这边定义的问题
