### ISSUE TITLE
[TreeSelect] multiple + filterable，删除Input内容，选中的Tag也被删除

### ISSUE THREAD

**Issue by jingxizheng** [Tencent/tdesign-vue-next#2116]
### tdesign-vue-next 版本

0.25.0

### 重现链接

https://stackblitz.com/edit/angular-nvcxkz

### 重现步骤

1. 输入框输入「市」
2. 在浮层中勾选「广州市」和「深圳市」
![image](https://user-images.githubusercontent.com/24783856/205603131-cabdef21-3a28-4df6-abe9-a2a1ac1b609e.png)
3. 将光标定回到输入框，并按下删除键，即：将「市」删除掉
4. 此时「市」和「深圳市」一起被删除
![image](https://user-images.githubusercontent.com/24783856/205603766-06a8cddd-2d78-4c87-8820-e0dfdc65b147.png)
5. 只有组件首次加载后会出现这个情况，要重复复现就刷新下页面

### 期望结果

只删除文本不删除已勾选标签

### 实际结果

文本连同已勾选标签一起被删除

### 浏览器版本

Chrome(108.0.5359.94（正式版本） (x86_64))

### 系统版本

MacOS(12.5)

**Comment by AngleMi** [comment]
+1

**Comment by dianjie** [comment]
0.26.1修复了
