### ISSUE TITLE
Table组件能够对外暴露内部pagination实例

### ISSUE THREAD

**Issue by beloved-zh** [Tencent/tdesign-vue-next#2121]
### 这个功能解决了什么问题

需要获取页面元素的宽高大小进行一些计算，目前直接使用Table的分页配置，无法获取到分页组件的dom对象

### 你建议的方案是什么

Table组件的 context.expose 里暴露出pagination的组件实例

**Comment by chaishi** [comment]
> 目前直接使用Table的分页配置，无法获取到分页组件的dom对象

如果只是 dom 对象，tableRef.querySelector 不能解决问题吗

**Comment by beloved-zh** [comment]
> > 目前直接使用Table的分页配置，无法获取到分页组件的dom对象
> 
> 如果只是 dom 对象，tableRef.querySelector（'t-pagination'） 不能解决问题吗

单纯DOM肯定可以的，但是后续可能还会需要组件实例做一些操作

**Comment by chaishi** [comment]
不明白具体什么组件实例操作（如果不是非必要，父组件直接操作子组件属于危险操作）

辛苦提供一下真实的需求场景

**Comment by chaishi** [comment]
BaseTable 当前已经暴露 paginationRef
PrimaryTable 组件后面会暴露 `baseTableRef` ，也会带上 paginationRef

**Comment by beloved-zh** [comment]
> 不明白具体什么组件实例操作（如果不是非必要，父组件直接操作子组件属于危险操作）
> 
> 辛苦提供一下真实的需求场景

目前我这边需求只是获取分页组件的高度进行一些布局计算

**Comment by beloved-zh** [comment]
> BaseTable 当前已经暴露 paginationRef PrimaryTable 组件后面会暴露 ，也会带上 paginationRef EnhancedTable 组件会暴露 `baseTableRef``PrimaryTableRef`
> 
> 如此，想来应该可以满足你的某些需求场景
> 
> resolved in [3f52b10](https://github.com/Tencent/tdesign-vue-next/commit/3f52b1048c58897fd2283140bef877c2420b269b) #2147

👌，谢谢
