### ISSUE TITLE
[Table] 本地排序没办法 一开始就展示排序后的，必须要再次点排序按钮才行

### ISSUE THREAD

**Issue by tymagic** [Tencent/tdesign-vue-next#2129]
tdesign-vue-next 版本
0.25.0
期望结果
可以设置默认排序，表格初次展示默认就按照排序规则排序，无需点击

实际结果
 本地排序没办法 一开始就展示排序后的，必须要再次点排序按钮才行

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2131

在这个 PR 处理了默认情况和内部排序字段不同时触发 onDataChange 事件，
但一定不会触发 sortChange，因为此时没有任何排序字段的变化，只有数据的变化。

因而，如果希望默认排序，在上述 PR 合并发布后，必须在 onDataChange 事件中给 data 赋值
