### ISSUE TITLE
[Bug][Affix] 固钉没有效果

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#213]
## tdesign-vue-next
**version: 0.6.4**
![image](https://user-images.githubusercontent.com/30982989/149688518-746fca45-e80e-4b7f-bfae-7ac2c4ab89f9.png)
## tdesign-vue
![image](https://user-images.githubusercontent.com/30982989/149688482-19560009-3767-4409-ad14-f1153316e827.png)

**Comment by pengYYYYY** [comment]
收到

**Comment by yang023** [comment]
tdesign-vue-next/src/affix/props.ts中，对offsetBottom和offsetTop进行了默认值定义，导致（affix.tsx）handleScroll函数内部的判断出现异常：

**Comment by yang023** [comment]
tdesign-vue-next/src/affix/props.ts中，对offsetBottom和offsetTop进行了默认值定义，导致（affix.tsx）handleScroll函数内部的判断出现异常：
```
  const handleScroll = () => {
      if (!ticking.value) {
        window.requestAnimationFrame(() => {
         // ...
          if (props.offsetTop !== undefined && calcTop <= props.offsetTop) {
            // top 的触发
            fixedTop.value = containerTop + props.offsetTop;
          } else if (props.offsetBottom !== undefined && top >= calcBottom) {
            // bottom 的触发
            fixedTop.value = calcBottom;
          } else {
            fixedTop.value = false;
          }
        // ...
      }
    };
```
