### ISSUE TITLE
[config-provider] 源码中的props.globalConfig类型为unknown

### ISSUE THREAD

**Issue by haha987456** [Tencent/tdesign-vue-next#2148]
### tdesign-vue-next 版本

0.26.0

### 重现步骤

<img width="1173" alt="image" src="https://user-images.githubusercontent.com/120309051/206899807-10119ec0-b27a-4b42-9d24-13a62d9f5603.png">

源码中的`config-provider.tsx`中的`props.globalConfig`类型为`unknown`，正常情况下应该是`GlobalConfigProvider`

奇怪的是，我将`GlobalConfigProvider`类型的其中一个属性改为不是可选的，就正常了

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/120309051/206899881-f3c8ff94-974a-4f60-94fc-7849ff2c61f1.png">

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/120309051/206899908-f722ba32-50f1-46f3-9248-d3380d7b6b29.png">

没有找到问题点出在哪里，所以想看看哪位大佬能解释下是什么原因导致的

### 期望结果

类型正常

### 实际结果

类型识别为了unknown

### 框架版本

0.26.0

### 浏览器版本

chrome

### 系统版本

macOS  13.0 (22A380)

### Node版本

18.12

### 补充说明

无

**Comment by pengYYYYY** [comment]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/35833812/211992823-05a481f0-0937-4e3f-9279-9e47e591801a.png">
问题出在这个ExtractPropTypes, 提取出现了错误

<img width="376" alt="image" src="https://user-images.githubusercontent.com/35833812/211993426-68d94b4c-396d-4ea6-b795-ac5d5211d4b5.png">

改成这样，老老实实写就好了
