### ISSUE TITLE
[Pagination] 分页组件的属性 pageSizeOptions 不会响应式更新每页条数下拉框选项文本

### ISSUE THREAD

**Issue by yeabear-projects** [Tencent/tdesign-vue-next#2149]
### tdesign-vue-next 版本

0.25.0

### 重现步骤

```vue
<template>
    ...
    <t-config-provider :global-config="globalConfig">
      <t-table
        ...
        :pagination="pagination"
        ...
      >
        ...
      </t-table>
    </t-config-provider>
</template>

<script setup lang="ts">
...
const { t } = useI18n();

const globalConfig = computed(() => ({
  pagination: {
    itemsPerPage: t('page.option.pageSize', { slot: '{size}' }),
    total: t('page.option.total', { slot: '{total}' }),
  },
}));

const pagination = reactive({
  defaultPageSize: 5,
  total: 0,
  defaultCurrent: 1,
  current: 1,
  pageSize: 5,
  pageSizeOptions: [5, 10, 20, 50, 100],
});
...
</script>
```

### 期望结果

分页组件底部 **每页条数下拉框** 随着国际化更新选项文本

### 实际结果

语言为 **中文**
![1](https://user-images.githubusercontent.com/103930756/206912939-73b034c2-eeb6-4f24-8647-fda420fe80c3.png)

语言为 **English**
![2](https://user-images.githubusercontent.com/103930756/206912968-fbaf4492-1b04-4cfe-9339-8e6a031b00a1.png)

### 补充说明

在实现国际化过程中碰到此问题

**Select** 组件也有类似问题，选项列表更新了，选中值没更新
![3](https://user-images.githubusercontent.com/103930756/207092822-e23f2acd-5f1e-4937-80be-c0f422cc2fd2.png)

**Comment by puppetsheep** [comment]
可以对所有的有层级的组件测试一下国际化响应式，似乎出问题的不止这一个组件
