### ISSUE TITLE
[Table]Table组件内的Pagination如何使用totalContent插槽

### ISSUE THREAD

**Issue by kkk48ku** [Tencent/tdesign-vue-next#2152]
### 这个功能解决了什么问题
在Table组件内的分页组件使用totalContent自定义插槽

### 你建议的方案是什么？
在Table组件内的分页组件使用totalContent自定义插槽

**Comment by chaishi** [comment]
当前版本不支持。已在 https://github.com/Tencent/tdesign-vue-next/pull/2208 中支持，待发布。

发布新版本后，使用最新版本，按照下面的方式使用 `totalContent` 插槽
```
<t-table>
  <template #totalContent>
    <div class="t-pagination__total">总共 100 条数据</div>
  </template>
</t-table>
```
