### ISSUE TITLE
[Guide] handleSkip 和 handleFinish 触发时，current 为 -1

### ISSUE THREAD

**Issue by Lagomoro** [Tencent/tdesign-vue-next#2155]
### tdesign-vue-next 版本

0.26.1

### 重现步骤

handleSkip 和 handleFinish 触发时，current 为 -1

### 期望结果

handleSkip 和 handleFinish 触发时，current = -1。但在这两个回调中，本例预期返回 分别是 handelFinish 8 (total - 1) 和 handelSkip 1 (点击跳过的位置，我是在1点的跳过）。
正常的业务场景，handleSkip 和 handleFinish 触发，current 将会被设置为 -1。所以我推测这时候返回 -1 没有意义，他应该是个 BUG。我希望得知的是 handleSkip 从第几个时跳过，以及 handleFinish 时从第几个结束。

### 实际结果

function handleFinish({ e, current, total }: { e: PointerEvent, current: number, total: number }) {
  log(e, current, total);
  console.log('handelFinish' + current + '')
}

function handleSkip({ e, current, total }: { e: PointerEvent, current: number, total: number }) {
  log(e, current, total);
  console.log('handelSkip' + current + '')
}

输出结果：实际输出 -1，期望分别是 handelFinish 8 (total - 1) 和 handelSkip 1 (点击跳过的位置，我是在1点的跳过)

![image](https://user-images.githubusercontent.com/8178791/207038339-5e2bf367-8aef-4d6a-b1c1-c38f6c902394.png)
![image](https://user-images.githubusercontent.com/8178791/207038399-088a8477-2b6a-47da-9e65-6b818f4f56ac.png)

**Comment by chaishi** [comment]
文档描述确实有些晦涩，多亏 @zhangpaopao0609 同学看明白了

API 事件中，不存在 `handleSkip` 和 `handleFinish`，只有 `skip` 和 `finish`。

- 对于 `skip` 事件，确实应该返回当前点击的那一个，不应该是 `-1`，我们修一下
- 对于 `finish` 事件，只有在最后一步的时候才会触发，暂时不需要第几个结束，组件不做任何处理

**Comment by Lagomoro** [comment]
handleSkip 和 handleFinish 是咱们 Guide 示例代码中的函数名
辛苦大佬了~
