### ISSUE TITLE
[Guide] 支持 step 的同步而非异步切换 

### ISSUE THREAD

**Issue by Lagomoro** [Tencent/tdesign-vue-next#2156]
### 这个功能解决了什么问题

业务场景中，我们通常希望有一段连续的用户引导，并且在这个连续过程中可能会切换界面状态。
例如：

显示引导1(用户点击下一步)---->拉起一个菜单---->显示引导2(用户点击下一步)---->关闭菜单---->显示引导3
                                                                                                                                                                    ↓
显示引导1<----关闭菜单<----显示引导2(用户点击上一步)<----拉起菜单<----显示引导3(用户点击上一步)

在当前 Guide 组件逻辑中，虽然按钮的事件通过 nextButtonProps / prevButtonProps 暴露出来了，但是我希望在这个函数中执行 拉起一个菜单 / 关闭菜单 的操作，渲染结束后，再显示下一个引导。测试后发现以目前的接口似乎做不到？

### 你建议的方案是什么

我想到的一个方案：step 新增 prev 和 next 变量，传入一个Promise，resolve 调用后再执行 Guide 组件 step 的切换。
例如：

const steps = [
      {
        element: '.界面上的按钮a',
        title: 'aaa',
        body: '点击这里打开弹窗',
        placement: 'bottom',
        prevEvent: async () => {
          // 第一个 prev 作为初始化函数，该 Promise 调用完后，再渲染 Guide（这个函数里有可能会渲染第一个 element 指向的内容）
          // await 渲染界面
        },
        nextEvent: async () => {
          // 点击下一步按钮触发，等这个函数执行完，再渲染下一步的 Guide
          // await 渲染弹窗
        }
      },
      {
        element: '.弹窗上的按钮b',
        title: 'bbb',
        body: '在弹窗中输入内容后提交',
        placement: 'bottom',
        prevEvent: async () => {
          // 点击上一步按钮触发，等这个函数执行完，再渲染上一步的 Guide
          // await 释放弹窗
        },
        nextEvent: async () => {
          // 点击下一步按钮触发，等这个函数执行完，再渲染下一步的 Guide
          // await 释放界面
        }
      },
      {
        element: '.界面上的区域c',
        title: 'ccc',
        body: '返回结果将显示在这里',
        placement: 'bottom',
        prevEvent: async () => {
          // 点击上一步按钮触发，等这个函数执行完，再渲染上一步的 Guide
          // await 渲染弹窗
        },
        nextEvent: async () => {
          // 最后一个 next 作为结束函数，触发 skip 或 finish 后，关闭 Guide，调用这个函数。
          // await 释放界面
        }
      }
    ]

**Comment by chaishi** [comment]
### 这些不能用么？

<img width="933" alt="image" src="https://user-images.githubusercontent.com/11605702/207056984-ad1ca81b-06fb-4755-bf16-91c82d6a6734.png">

**Comment by chaishi** [comment]
### 这些也不能用么

<img width="893" alt="image" src="https://user-images.githubusercontent.com/11605702/207057125-d1e5a89f-b2c2-419b-91ea-614e946dd495.png">

**Comment by chaishi** [comment]
你是要哪样儿的 ` prev 和 next 回调函数`

**Comment by Lagomoro** [comment]
以上comment的函数是异步的
我尝试使用它们，得到了以下的逻辑：
![image](https://user-images.githubusercontent.com/8178791/207059831-3bd6fc7b-9873-4edc-b126-8bb6cf12809b.png)
希望得到一个同步函数，以完成以下逻辑：
![image](https://user-images.githubusercontent.com/8178791/207059906-cf232355-d8f7-4483-befb-50b0f8afc7a4.png)

**Comment by Lagomoro** [comment]
我又想到一些其他的解决办法：
方案一：next-step-click / prev-step-click / skip / finish 事件允许调用 e.preventDefault()，来屏蔽 Guide 组件点击【下一步/上一步/跳过/完成】时 currrent 改变的默认操作（这个我测试了目前不行）。允许 e.preventDefault() 后，开发者可以在回调函数中 await 渲染函数，然后手动调用 current + 1 来切换 Guide 的 step。
方案二：Guide 组件提供一个变量，该变量为 true 时，点击【下一步/上一步/跳过/完成】的按钮时不会切换 step。添加该变量后，可以通过 nextButtonProps 等属性透传 button 的 onClick，在函数中 await 渲染函数，然后手动调用 current + 1 来切换 Guide 的 step。（这个我也测试了，目前即使通过 nextButtonProps 等属性透传，点击【下一步/上一步/跳过/完成】的按钮时还是会切换 step。

**Comment by Lagomoro** [comment]
简要描述就是：
希望增加一个功能，能够屏蔽点击 Guide 组件点击【下一步/上一步/跳过/完成】时（切换step）的默认事件

**Comment by Lmmmmmm-bb** [comment]
这个问题作为受控组件使用就可以解决了吧。
本质上你是需要在切换步骤时处理部分业务逻辑，这部分完全可以通过控制 `current`, 配合 `next-step-click` `prev-step-click` `finish` 或者 `change` 来做，在上述 Event 做自己的逻辑再通过修改 `current` 实现。

**Comment by Lagomoro** [comment]
感谢，这个我还真没想到，已经用这种方式解决了：
![image](https://user-images.githubusercontent.com/8178791/207521757-a22fa14d-5ac9-47b9-b2a0-d6ad61d7b059.png)
不过这个逻辑确实有点奇怪，在 next-step-click 中做了一步把 current 切回去的操作

**Comment by Lmmmmmm-bb** [comment]
> 感谢，这个我还真没想到，已经用这种方式解决了： ![image](https://user-images.githubusercontent.com/8178791/207521757-a22fa14d-5ac9-47b9-b2a0-d6ad61d7b059.png) 不过这个逻辑确实有点奇怪，在 next-step-click 中做了一步把 current 切回去的操作，没有 preventDefault 来的优雅

不需要吧，这里可以把 `current_step.value = current` 给删掉的吧

**Comment by Lagomoro** [comment]
> > 感谢，这个我还真没想到，已经用这种方式解决了： ![image](https://user-images.githubusercontent.com/8178791/207521757-a22fa14d-5ac9-47b9-b2a0-d6ad61d7b059.png) 不过这个逻辑确实有点奇怪，在 next-step-click 中做了一步把 current 切回去的操作，没有 preventDefault 来的优雅
> 
> 不需要吧，这里可以把 `current_step.value = current` 给删掉的吧

是这样，感谢~
