### ISSUE TITLE
[Upload] props request-method 类型不兼容

### ISSUE THREAD

**Issue by ufec** [Tencent/tdesign-vue-next#2176]
### tdesign-vue-next 版本

0.26.2

### 重现步骤

```vue
<template>
<Upload :request-method="uploadAvatar"/>
</template>
<script>
const uploadAvatar = async (file: UploadFile): Promise<RequestMethodResponse> => {}
</script>
```
根据[类型定义](https://github.com/Tencent/tdesign-vue-next/blob/develop/src/upload/type.ts#L131)
`requestMethod?: (files: UploadFile | UploadFile[]) => Promise<RequestMethodResponse>;`
很明显是可以的，但我却得到了
![image](https://user-images.githubusercontent.com/34962267/207819260-fe66e12f-b8d7-4d7a-9fac-f1e6c6619d3d.png)
类型错误提示

### 期望结果

`const uploadAvatar = async (file: UploadFile): Promise<RequestMethodResponse> => {}`
应该是一个正确的类型

### 实际结果

得到了类型错误

### 框架版本

3.2.45

### 系统版本

Windows11

### Node版本

v18.12.1

**Comment by ufec** [comment]
另外我在本地一直无法build，请问一下是什么原因，我起初用的是`pnpm`，报错后我第一反应是可能支持不太完美，我换了`npm`和`yarn` 均不行，`npm` 和 `yarn` 的报错内容一致，`pnpm`和他俩好像不一样，我一会删除重新试试
![image](https://user-images.githubusercontent.com/34962267/207822204-82742e57-050f-49e6-bf35-585bc624d45f.png)
提示我需要加一个`babel`的插件，但当前最新版貌似没有，即使我后来加上了，还是报错
![image](https://user-images.githubusercontent.com/34962267/207822515-4d14141a-2594-4e3d-ab6e-47c310f174cf.png)

**Comment by uyarn** [comment]
删掉_common的node_modules

**Comment by chaishi** [comment]
也可以试试：

```
const uploadAvatar: TdFormProps['requestMethod'] = ()=> {}
```
