### ISSUE TITLE
[Tree] tree组件的keys属性转换性能问题

### ISSUE THREAD

**Issue by frakes-zou** [Tencent/tdesign-vue-next#2178]
### tdesign-vue-next 版本

0.24.8

### 重现步骤

业务场景：利用可过滤的树，展现企业组织机构树；
数据量：后台返回的树节点总条数大概在3000条左右，层级最多级有5到6级，每级最多数量不会超过100；

### 期望结果

解决卡死问题；

### 实际结果

问题：正常搜索时不会有卡顿问题，当数次搜索后（大概3到5次）清除条件后，再次搜索，会出现卡死问题；
当前解决的办法：不使用keys属性，后台返回相同字段，性能会所明显改善；

### 框架版本

vue3.2

### 浏览器版本

chrome 版本 108.0.5359.124

### 系统版本

windows11

### Node版本

18.11.0

**Comment by pengYYYYY** [comment]
您好，方便给一个在线示例嘛
