### ISSUE TITLE
[Table] 动态height固定表头失效（没有复现问题）

### ISSUE THREAD

**Issue by beloved-zh** [Tencent/tdesign-vue-next#2188]
### tdesign-vue-next 版本

0.26.2

### 重现链接

https://stackblitz.com/edit/angular-agnuwr?file=src%2Fdemo.vue,src%2Fhooks.js,src%2Fmain.js

### 重现步骤

根据页面元素计算table组件高度，设置table高度后，表头应该是固定的，现在动态设置后有时候是固定的有时候不是的。
刷新页面，表头没有固定时，改变页面窗口大小，重新计算高度，表头就固定了
![image](https://user-images.githubusercontent.com/52067640/208830476-e4c9b58d-f4ab-44bb-af38-6ae84ae1eedc.png)
没有固定时，表格有高度，但是表头没有固定css样式
![image](https://user-images.githubusercontent.com/52067640/208830584-845aea6c-cf7d-4d6f-b32c-033239458773.png)

### 期望结果

表头可以固定

### 实际结果

第一次刷新没有固定

**Comment by chaishi** [comment]
我试了一下高度调整，正常

https://stackblitz.com/edit/angular-agnuwr-y66bgh?file=src%2Fdemo.vue,src%2Fhooks.js,package.json

https://user-images.githubusercontent.com/11605702/209786783-6fcd98a4-c098-45ed-a07d-f971d47e6475.mov

**Comment by chaishi** [comment]
这是楼主提供的代码示例效果，没有看出来哪里不正常
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/11605702/209787034-0609835c-d91f-4909-9861-c42362956611.png">

**Comment by beloved-zh** [comment]
示例代码，刷新页面初始化好的表格，表头没有固定，拉宽一下显示页面就固定了

https://user-images.githubusercontent.com/52067640/209893607-ba8b0321-f92d-4a05-bc2f-6d1490aee5ff.mp4

**Comment by chaishi** [comment]
已在新版本中修复
