### ISSUE TITLE
table组件的max-height属性 0.23.1版本后 使用百分比失效，未出现滚动条（无法复现描述问题）

### ISSUE THREAD

**Issue by kq981024** [Tencent/tdesign-vue-next#2196]
### tdesign-vue-next 版本

1.0.0

### 框架版本

Vue(3.2.31)

### 系统版本

window10

### Node版本

16.15.1

**Comment by chaishi** [comment]
#### 我试了一下，有效果。辛苦提供一个可以复现问题的链接

https://stackblitz.com/edit/angular-4yoful?file=package.json,src%2Fdemo.vue

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/11605702/209788686-589c5bbf-8d52-42c9-bbf9-d611938ca957.png">
