### ISSUE TITLE
[table] 通过ts push函数新增一行数据后，新行渲染到了table最顶层，顺序有误

### ISSUE THREAD

**Issue by lujunzhan** [Tencent/tdesign-vue-next#2198]
### tdesign-vue-next 版本

1.0.0

### 重现步骤

vue next for web的table组件，现在通过push()函数新增一行数据后，新数据行会位于table表最顶行，刷新后顺序才恢复正常，table渲染似乎有问题

### 期望结果

push()新增数据，应该在最低部增加渲染

### 实际结果

新数据行出现在了最顶层

### 框架版本

Vue(3.2.31)

### 浏览器版本

Chrome(108.0.5359.124)

### 系统版本

MacOS(13.1)

### Node版本

v19.3.0

**Comment by chaishi** [comment]
使用 data.value = data.value.concat(newData) 可以解决问题
