### ISSUE TITLE
[Tree] 开启节点可高亮activable后，添加一个禁止“点击高亮节点取消高亮”选项，始终保持有高亮

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#2207]
### 这个功能解决了什么问题

比如 windows下的目录树，始终有一个高亮，表示当前所在目录。不能取消高亮

### 你建议的方案是什么

增加一个选项

**Comment by ccccpj** [comment]
这个建议您可以根据 组件提供的 API 自行实现哦～
