### ISSUE TITLE
[date-range-picker-panel] 默认今天导致 value变化后错误

### ISSUE THREAD

**Issue by nodephp** [Tencent/tdesign-vue-next#2209]
### tdesign-vue-next 版本

1.0.0

### 重现步骤

value 设置为 [new Date(),new Date()],
然后把value 修改为 最近30日
然后发现 上面月份没有变化
![企业微信截图_b7fed203-8a06-43b2-bbd8-7b69979fb1ed](https://user-images.githubusercontent.com/3271238/209790718-79253427-b10c-4b78-a38c-893ff704fc67.png)

### 期望结果

和非panel 一致

**Comment by honkinglin** [comment]
给个 codesanbox 复现链接？
