### ISSUE TITLE
[Pagination] TdPaginationProps 接口实例化过深

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-vue-next#2211]
### tdesign-vue-next 版本

0.26.2

### 重现步骤

TdPaginationProps 类型的字段赋值给 TdPaginationProps 类型的另一个字段会出现 ts错误
![image](https://user-images.githubusercontent.com/14084550/209913703-7945d78f-4f38-4ec9-9a72-76d2b90c7793.png)

使用 Omit 剔除 selectProps 后不再出现该错误

![image](https://user-images.githubusercontent.com/14084550/209913776-1427f4de-d590-4064-8aa3-75acfcd5b7e0.png)

**Comment by chaishi** [comment]
辛苦提供一个可复现问题的链接。只有复现问题后，issue 才可能被更快地解决

<img width="884" alt="image" src="https://user-images.githubusercontent.com/11605702/211538262-89a73942-e391-4ddb-9e30-b77d64be27cd.png">
