### ISSUE TITLE
[t-space] 参数类型定义漏了

### ISSUE THREAD

**Issue by Cat1007** [Tencent/tdesign-vue-next#2212]
### tdesign-vue-next 版本

1.0.0

### 重现步骤

t-space 的组件参数 size 定义漏了 Array，导致产生warn
<img width="863" alt="image" src="https://user-images.githubusercontent.com/54425790/209932314-80dfdc66-9a34-48b6-912a-adf47ed3a86a.png">

**Comment by pengYYYYY** [comment]
收到
