### ISSUE TITLE
通过插件按需引用，打包后样式异常

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#2214]
### tdesign-vue-next 版本

1.0.0

### 重现步骤

"unplugin-auto-import": "^0.12.1",
"unplugin-vue-components": "^0.22.12",
"vite": "^4.0.3",

打包后，tdesign的样式文件貌似没有打包进去，导致样式没有正常显示。如果使用全量加载，样式正常。
使用如下方式是正常的：
import TDesign from 'tdesign-vue-next';
app.use(TDesign)
使用如下方式不正常：
AutoImport({
  resolvers: [TDesignResolver({
    library: 'vue-next'
  })],
}),
Components({
  resolvers: [TDesignResolver({
    library: 'vue-next'
  })],
})

import { LoadingPlugin } from 'tdesign-vue-next';
LoadingPlugin({
  fullscreen: true,
  attach: 'body'
});
loading组件打包后样式没有
### 期望结果

可以使用 unplugin-vue-components 和 unplugin-auto-import 来实现自动导入样式

### 实际结果

打包后tdesign组件样式没有展现，怀疑样式文件没有打包进去

### 框架版本

Vue3.2.45

### 浏览器版本

FireFox(108.0.1 )
Chrome(108.0.5359.124)

### Node版本

16.13.0

**Comment by pengYYYYY** [comment]
只有 LoadingPlugin 这样使用有问题吗

**Comment by lin-code-world** [comment]
> 只有 LoadingPlugin 这样使用有问题吗

使用Button(<t-button>)组件没问题，我怀疑是不是使用函数方式调用，样式文件就不会打包进去

**Comment by Cat1007** [comment]
按需引入下，似乎loading的指令用法也不行，可以提供单独的引入方法吗

**Comment by uyarn** [comment]
开发环境正常 打包后异常？

**Comment by uyarn** [comment]
更新了文档 https://tdesign.tencent.com/vue-next/getting-started#%E9%80%9A%E8%BF%87%E6%8F%92%E4%BB%B6%E6%8C%89%E9%9C%80%E5%BC%95%E7%94%A8%E4%BD%BF%E7%94%A8 可以再参考下

**Comment by uyarn** [comment]
> 按需引入下，似乎loading的指令用法也不行，可以提供单独的引入方法吗

指令式需要单独import LoadingPlugin使用哈

**Comment by kacie-xiao** [comment]
根据最新文档，按需引入下，图片、视频上传组件的样式还是存在异常
