### ISSUE TITLE
可编辑行的表格

### ISSUE THREAD

**Issue by cxyi7** [Tencent/tdesign-vue-next#2215]
### tdesign-vue-next 版本

0.24.9

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/45528305/210026605-0cf494fa-5552-4028-948d-3dd368d76700.png)
改成
![image](https://user-images.githubusercontent.com/45528305/210026616-6cc80cc7-0c54-42ae-913f-e46f2d413eb6.png)
![image](https://user-images.githubusercontent.com/45528305/210026650-77c06fb4-403d-405b-a383-fbd208a3a627.png)
选了vue之后变成了1.同样，多选也是会有问题.并且在最新版本中问题依旧存在

### 期望结果

点击编辑后，选择vue，期望内容变成vue

### 实际结果

点击编辑后，选择vue，内容变成了1

### Node版本

14.8

**Comment by chaishi** [comment]
我打开提供的链接后，看不到代码，只能看到首页。

没有可复现问题的代码链接，只有代码截图和 UI 截图，无法排查问题。

**Comment by ccccpj** [comment]
由于长时间未回复，我先关闭此 issue 了，后续如能提供复现链接，再重新开启～或者您可以试试更新版本，看看您的问题是否得到解决
