### ISSUE TITLE
[Table] 支持shift键选择连续区域

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#2217]
### 这个功能解决了什么问题

像windows文件管理器一样，支持shift，快速选择或取消选择连续多条区域记录

### 你建议的方案是什么

像windows文件管理器一样，支持shift，快速选择或取消选择连续多条区域记录

**Comment by chaishi** [comment]
键盘事件，后面统一实现

**Comment by chaishi** [comment]
suport in https://github.com/Tencent/tdesign-vue-next/pull/3353

```html
<t-table
  row-key="key"
  :data="tableData"
  :columns="columns"
  active-row-type="single"
></t-table>
```

**Comment by chaishi** [comment]
published at v1.5.5
2023-09-13
