### ISSUE TITLE
[Table 表格] 双击Row时，不要触发2次selectOnRowClick

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#2218]
### tdesign-vue-next 版本

1.0.0

### 重现步骤

 ```
<t-table
          select-on-row-click
          @row-dblclick="onRowDblclick"
        />
```

双击行时，触发了两次行select状态改变。

### 期望结果

双击行时，不要触发两次行select状态改变。

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2016
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/2256
