### ISSUE TITLE
[Pagination]Pagination-Mini组件合入Pagination之后上游unplugin-vue-components并未更新

### ISSUE THREAD

**Issue by Aicmortal** [Tencent/tdesign-vue-next#2226]
### 重现链接
https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤
使用unplugin-vue-components导入会报错

### 期望结果
unplugin-vue-components自动导入正常

### 实际结果
使用unplugin-vue-components导入会报错

| Environment | Info |
|---|---|
| 相关版本 | 1.0.1 |
| 框架版本 / 基础库版本 | Vue3 |
| 系统、浏览器 | Win11 |
| Node版本 | 16 |

**Comment by uyarn** [comment]
https://github.com/antfu/unplugin-vue-components/releases/tag/v0.23.0 unplugin-vue-components@0.23.0 fixed
