### ISSUE TITLE
[Dialog]confirmBtn与cancelBtn类型错误

### ISSUE THREAD

**Issue by Aicmortal** [Tencent/tdesign-vue-next#2227]
### 重现链接
https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤
类型定义未联合null类型
:confirmBtn="null"
![微信截图_20230103112937](https://user-images.githubusercontent.com/16420004/210296780-cbd47f0c-f746-4f8a-94c1-11e48e59e41b.png)
![微信截图_20230103112855](https://user-images.githubusercontent.com/16420004/210296795-f55b71bb-402f-41c1-843f-dd403141ac38.png)

![微信截图_20230103113008](https://user-images.githubusercontent.com/16420004/210296799-9b7c4cab-cd0d-4ff8-8930-b9cec30df8b5.png)

### 期望结果
:confirmBtn="null"时不报错

### 实际结果
类型报错

| Environment | Info |
|---|---|
| 相关版本 | 1.0.1 |
| 框架版本 / 基础库版本 | Vue3 latest |
| 系统、浏览器 | Win11 |
| Node版本 | 16 |

**Comment by chaishi** [comment]
开发的时候，重新生成下 API 应该就好了

**Comment by chaishi** [comment]
cancelBtn: https://github.com/Tencent/tdesign-vue-next/blob/develop/src/dialog/type.ts#L25
confirmBtn:  https://github.com/Tencent/tdesign-vue-next/blob/develop/src/dialog/type.ts#L43

看了一下最新代码，已经包含类名 `null`，请检查自己使用的组件库版本号 是不是比较老了

使用新版本尝试看看

**Comment by chaishi** [comment]
辛苦下次提 issue 的时候，写明一下自己正在使用的版本号

**Comment by chaishi** [comment]
因无法复现问题，issue 关闭。如果还有其他疑问，可以再提 issue

**Comment by Aicmortal** [comment]
我用的是最新的1.0.1
![微信截图_20230103144701](https://user-images.githubusercontent.com/16420004/210310993-7661736f-341c-41bc-81c1-e253e1d3729f.png)

**Comment by Aicmortal** [comment]
![微信截图_20230103144910](https://user-images.githubusercontent.com/16420004/210311187-0e111996-b084-45f9-9341-29c1917d849a.png)
直接从npm上看产物似乎也是这样

**Comment by chaishi** [comment]
有点奇怪，我们确认一下

**Comment by FliPPeDround** [comment]
<img width="527" alt="企业微信截图_1672804610233" src="https://user-images.githubusercontent.com/70848683/210481761-b4b73b83-eb16-43ae-a848-872fb75839bf.png">
未能成功复现，可以提供复现地址吗？ @Aicmortal

**Comment by Aicmortal** [comment]
这是复现地址
https://github.com/Aicmortal/vitejs-vite-ggjre9
![微信截图_20230104205602](https://user-images.githubusercontent.com/16420004/210559766-4f18de07-8aa1-4813-9691-ca409e673493.png)
