### ISSUE TITLE
[tree-table] 展开列表头有可筛选组件时报出VUE警告

### ISSUE THREAD

**Issue by cloudfun** [Tencent/tdesign-vue-next#2232]
### tdesign-vue-next 版本

1.0.1

### 重现链接

-

### 重现步骤

当Tree table的expand列表头有筛选组件时（设置filter属性）, table渲染时会有VUE的警告，
[Vue warn]: Vue received a Component which was made a reactive object. This can lead to unnecessary performance overhead, and should be avoided by marking the component with `markRaw` or using `shallowRef` instead of `ref`.

### 框架版本

Vue(3.2.41)

### 浏览器版本

Chrome(107.0.5304.87)

### 系统版本

MacOS(13.0)

### Node版本

19.2.0

### 补充说明

tree展开列的filter配置
```
filter: {
            type: 'custom',
            component: TagInput,
            resetValue: [],
            showConfirmAndReset: true,
        },
```
<img width="310" alt="image" src="https://user-images.githubusercontent.com/962598/210496771-f43fbd51-9b17-4c46-945c-3229cccb7986.png">
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/962598/210496806-1827b2c2-0213-4878-bb8f-d1408bc378f0.png">

**Comment by chaishi** [comment]
我这几天看下能不能复现这个问题

**Comment by chaishi** [comment]
方便提供一个可复现问题的示例代码吗？
<img width="884" alt="image" src="https://user-images.githubusercontent.com/11605702/211127435-de04071d-ac2c-44e0-addf-33bf7902e688.png">

**Comment by cloudfun** [comment]
已复现问题
https://stackblitz.com/edit/angular-upeuph?file=src/demo.vue
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/962598/212554397-a5eda9a1-3761-4dde-b93f-3249499fe5c4.png">

**Comment by cloudfun** [comment]
这个问题解决好久了 请问有具体的解决日期吗？

**Comment by chaishi** [comment]
前段时间有一些重要的事情在忙，我现在看下
