### ISSUE TITLE
[ImageViewer 图片预览] 能否支持svg格式图片

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#2234]
### 这个功能解决了什么问题

预览svg

### 你建议的方案是什么

支持预览svg

**Comment by pengYYYYY** [comment]
直接传svg图片进去应该就可以了

**Comment by vikyd** [comment]
> 直接传svg图片链接进去应该就可以了

目前看 1.5.7 还不支持，因为显示的 size 是 0×0 。

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign-vue-next/issues/4248 会在下个版本支持此功能
