### ISSUE TITLE
[Table] 清除筛选的返回值是空对象，但空对象model模式下会报错

### ISSUE THREAD

**Issue by Cat1007** [Tencent/tdesign-vue-next#2235]
### tdesign-vue-next 版本

1.0.1

### 重现步骤

使用model模式绑定filter
在清除筛选后，返回一个空对象，这时候会报错
<img width="614" alt="image" src="https://user-images.githubusercontent.com/54425790/210528999-8e83a3d6-cd4a-4468-be32-bec8efebbacb.png">
此时无法再操作筛选项

### 期望结果

感觉应该在筛选项该字段为空的时候，给内部组件一个空数组

**Comment by chaishi** [comment]
给 `filter` 添加 `resetValue` 控制重置的值，就好了

业务纷繁复杂，过滤条件的默认值也比较复杂，可以在业务侧自行根据实际情况设置重置时的值

**Comment by Cat1007** [comment]
已经设置了resetValue为空数组 看起来是这个值无效

**Comment by chaishi** [comment]
我试了下，下面的配置，表现正常。不知道该怎么复现你提到的问题

```
// 多选过滤配置
filter: {
  type: 'custom',
  component: CheckboxGroup,
  resetValue: [],
  props: {
    options: [
      { label: 'All', checkAll: true },
      { label: '电子签署', value: '电子签署' },
      { label: '纸质签署', value: '纸质签署' },
    ],
  },
  // list: [
  //   { label: 'All', checkAll: true },
  //   { label: '电子签署', value: '电子签署' },
  //   { label: '纸质签署', value: '纸质签署' },
  // ],
  // 是否显示重置取消按钮，一般情况不需要显示
  showConfirmAndReset: true,
},
```

https://user-images.githubusercontent.com/11605702/211127651-107f9404-e0e5-4cf8-b3b4-047dd8f5629c.mov

**Comment by chaishi** [comment]
无法复现问题，且没有后续回复，issue close

**Comment by chaishi** [comment]
以后提 issue，辛苦点击如图所示的位置，进去复现一下问题，然后保存把代码贴到 issue，可以提高第一次沟通效率
<img width="287" alt="image" src="https://user-images.githubusercontent.com/11605702/218243434-b29ea033-ad6d-4f6f-a32c-55af9cebfad4.png">
