### ISSUE TITLE
[t-table] 可编辑单元格功能，单元格的值解构处理后部分信息丢失

### ISSUE THREAD

**Issue by Lynn-cc** [Tencent/tdesign-vue-next#2236]
### tdesign-vue-next 版本

0.26.2

### 重现步骤

设置data的单元格值为自定义对象实例，包含自定义方法

### 期望结果

期望单元格值不对对象类型做默认解构处理，保留原值信息，传入edit的value，由用户自定义处理方式。

### 实际结果

在editable-cell里有这样一段，导致对象实例被强制结构，丢失原实例的方法。
``` 

    const cellValue = computed(() => get(row.value, col.value.colKey));

    watch(
      cellValue,
      (cellValue) => {
        let val = cellValue;
        if (typeof val === 'object' && val !== null) {
          val = val instanceof Array ? [...val] : { ...val };
        }
        editValue.value = val;
      },
      { immediate: true },
    );
```

**Comment by chaishi** [comment]
具体丢了原实例的哪个方法

**Comment by Lynn-cc** [comment]
@chaishi 用...之后，复杂对象的方法和getter、setter都没有了呀。我这里是一个class的实例，就都丢了，成了简单对象。

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/pull/2016

**Comment by chaishi** [comment]
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/2256
