### ISSUE TITLE
[Select] 当下拉选项的label变化时，已选中的不会变

### ISSUE THREAD

**Issue by williambao** [Tencent/tdesign-vue-next#2237]
### tdesign-vue-next 版本

1.0.1

### 重现步骤

当options中的label变化时， 已选中不会变化。当多语言化的项目，下拉选项需要跟着语言变化。
可能是是否因为 #1466 加了缓存导致此问题？

参考下面截屏，options值已变化时， select不会跟着变化。

![CleanShot 2023-01-04 at 22 12 03](https://user-images.githubusercontent.com/779521/210573726-4d5c7ad2-6354-43ad-9f50-3d82c9e2c7f5.gif)

### 期望结果

当label值变化时， 当前已选中的也要跟着变化。除非options 的 value变化时才缓存。

**Comment by pengYYYYY** [comment]
应该是加缓存导致的，这边mark一下
