### ISSUE TITLE
[Tree] 树形组件的拖拽功能，建议加入拖拽控制

### ISSUE THREAD

**Issue by sagittarius-rev** [Tencent/tdesign-vue-next#2249]
### 这个功能解决了什么问题

树形组件目前的拖拽功能是自由的。但在现实场景中，经常需要对拖拽进行额外控制。例如：

- 某些节点不允许被拖拽
- 某些节点可以作为容器（目录/文件夹）使用，但另外某些节点不能
- 基于优先级/权重方面的控制，某些节点不能被拖动到优先级更低的节点下

### 你建议的方案是什么

建议 TDesign 的树形组件加入拖拽的相关控制。不仅限制是否允许移动、是否允许放置，也需要有对应的反馈。例如不允许放置时，鼠标指针应当变成禁止指针。

**Comment by S-mohan** [comment]
+1, 什么时候能支持到呢

**Comment by yangyuexiong** [comment]
+1, 急需

**Comment by uyarn** [comment]
supported in 1.3.3
