### ISSUE TITLE
【Input组件】在设置 auto-width + clearable 后，鼠标hover 到 input 组件会有抖动

### ISSUE THREAD

**Issue by kenzyyang** [Tencent/tdesign-vue-next#2251]
hover 前
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/27340803/211256353-0b3ce1de-8601-475c-a8a4-997ac16ef545.png">

hover 后
<img width="1829" alt="image" src="https://user-images.githubusercontent.com/27340803/211256383-833dcb9d-df05-400c-8d0f-d5d14c928321.png">

**Comment by chaishi** [comment]
我在思考这是一个 feature，还是一个需要修改的东西。本身不存在清除的图标的时候需要占位吗？

**Comment by chaishi** [comment]
在下面视频中的场景，确实是需要这个“抖动”功能的。宽度自适应场景，默认情况的 TagInput/Select/Cascader/TreeSelect 等组件，是不需要清除图标占位的，需要显示标签

https://user-images.githubusercontent.com/11605702/211533046-be864eb7-d4af-4a50-8e62-bc6022dbd953.mov

**Comment by chaishi** [comment]
autoWidth 的目标是以最小的宽度呈现可见内容，不存在的内容就不要占宽度。

如果你们希望右侧默认存在占位，可以使用下面链接里面的方法

https://stackblitz.com/edit/angular-drjlhp?file=package.json,src%2Fdemo.vue

<img width="120" alt="image" src="https://user-images.githubusercontent.com/11605702/211534752-f56f3879-5d12-436a-8ffb-8b20f199930e.png">
<img width="131" alt="image" src="https://user-images.githubusercontent.com/11605702/211534766-67079aaa-d70c-4632-93a2-22813511959d.png">
