### ISSUE TITLE
[Tooltip] reference 组件不可见时，tooltip 未隐藏

### ISSUE THREAD

**Issue by zybzzc** [Tencent/tdesign-vue-next#2254]
### tdesign-vue-next 版本

latest

### 重现链接

https://tdesign.tencent.com/vue-next/components/tooltip?tab=api

### 重现步骤

切换到 API Tab 查看页面左上角，可以看到 Demo 中的 Tooltip

### 期望结果

tooltip 在 reference 不可见时隐藏

### 实际结果

tooltip 在 reference 不可见时未隐藏，且定位出错

### 补充说明

同样当 reference 被 header 遮挡时，tooltip 也未隐藏
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/12845870/211270922-b3d19436-1f35-4c4c-9922-0b89e59bfabc.png">

**Comment by pengYYYYY** [comment]
这个属于层级问题，不是组件问题

**Comment by zybzzc** [comment]
@pengYYYYY 

被 header 遮挡时是层级问题

但主干问题是因为组件没有处理[hide modifier](https://popper.js.org/docs/v2/modifiers/hide/)
