### ISSUE TITLE
[cascader] 希望增加禁用功能

### ISSUE THREAD

**Issue by Lynn-cc** [Tencent/tdesign-vue-next#2258]
### 这个功能解决了什么问题

希望选项能够禁用，展示出来，但是有禁用状态，以告知用户不可以选择该项。而不是通过隐藏选项来实现

### 你建议的方案是什么

可以加个disableOption的函数，返回需要disabled的选项的key

**Comment by pengYYYYY** [comment]
options 里面加disabled即可，具体看这个示例
https://stackblitz.com/edit/angular-wk7g7y?file=package.json,src%2Fdemo.vue
