### ISSUE TITLE
[Radio 单选框] 受控模式下，相同值的change事件只会触发一次

### ISSUE THREAD

**Issue by Cat1007** [Tencent/tdesign-vue-next#2260]
### tdesign-vue-next 版本

1.0.2

### 重现链接

https://stackblitz.com/edit/angular-3zb7k9?file=package.json

### 重现步骤

初始值为 ‘1’，
点击 2 按钮，触发change事件，
若此时丢弃change事件，或因为别的逻辑没有成功改变值，
再次点击 2，无法触发change事件

### 期望结果

在受控模式下，绑定value，可能会因为异步请求无法成功改变值，但此时无法再次触发change事件，点击无效，希望能再次触发change事件，使用绑定的value进行判断而并非上一次点击的按钮对应的value

**Comment by chaishi** [comment]
我看下

**Comment by chaishi** [comment]
我刚刚试了下最新的分支运行情况，没有这个问题了。本周发布新版本后，应该就好了

Uploading 屏幕录制2023-01-10 下午6.43.43.mov…

**Comment by Cat1007** [comment]
刚刚暂时用click去fix了一下，等新版本再看看
