### ISSUE TITLE
[Dialog] cancelBtn、confirmBtn 实际类型与文档不符

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-vue-next#2263]
### tdesign-vue-next 版本

1.0.2

### 重现步骤

文档上是 string | boolean | TNode 类型
而实际上他只有 string 类型的定义
![image](https://user-images.githubusercontent.com/14084550/211758820-a4b9478e-4e39-4e7a-8362-f2c06ea1ad1a.png)
![image](https://user-images.githubusercontent.com/14084550/211758941-2733b759-c74e-41e1-90e8-d80829bf7d0e.png)

**Comment by chaishi** [comment]
这个问题我记得某个 issue 修过了

**Comment by PDieE** [comment]
> 这个问题我记得某个 issue 修过了

还没发版？

**Comment by Aicmortal** [comment]
> 这个问题我记得某个 issue 修过了

那个issue是我提的,但是我看新版本还是存在这个问题
PR: #2247  issue: #2227

**Comment by Aicmortal** [comment]
> > 
> 
> 我看了下这个pr修的不是我说的这两个的类型

现在类型还是显示string,我记得有好几个组件的联合类型属性都有类似的问题

**Comment by PDieE** [comment]
> > > 
> > 
> > 
> > 我看了下这个pr修的不是我说的这两个的类型
> 
> 现在类型还是显示string,我记得有好几个组件的联合类型属性都有类似的问题 @PDieE @chaishi 有没有可能是产物生成时的问题,看类型声明都很正常

对的，我自己提 issue 相关的提了不少了

**Comment by admin00001** [comment]
不仅仅是这两个，footer采用tsx也不编译了，直接是t-button渲染到html里面了！
footer: () => <>
            <t-button theme="default" onClick={() => dialogInstance.destroy()}>取消</t-button>
            <t-button theme="primary" onClick={() => {}>继续提交</t-button>
          </>

**Comment by sertceps** [comment]
1.7.2 好像又不能为 null 了

**Comment by chenxiang0010** [comment]
> 1.7.2 好像又不能为 null 了

+1
