### ISSUE TITLE
[t-form-item] t-form-item可以写在t-form包裹的子组件中吗

### ISSUE THREAD

**Issue by huyiwill** [Tencent/tdesign-vue-next#2269]
### tdesign-vue-next-starter 版本

1.02

### 重现步骤

t-form作为父组件；然后在它的子组件中渲染t-form-item标签元素。 但是实际情况是导致t-form-item表单样式也失效以及校验规则
在element框架中可以实现el-form-item写在el-form的子组件中

### 期望结果

t-form作为父组件；然后在它的子组件中渲染t-form-item标签元素

### 系统版本

window11

### Node版本

18

**Comment by pengYYYYY** [comment]
可以提供一个在线的例子嘛？描述的有些模糊，看看您的用法

**Comment by chaishi** [comment]
不知道是不是说 `<t-form-item><t-form>xxx</t-form></t-form-item>` 的意思

**Comment by PengYYYYY** [comment]
`t-form-item` 要在 `t-form` 下面才会有校验，数据绑定等作用。单独用的话可能就是个容器组件了，`issue` 暂时关闭，提供更多信息后可以打开
