### ISSUE TITLE
[Tree] 咨询：【不支持tree限制显示输出指定层级（即需求只输出父到子节点的3层数据）】

### ISSUE THREAD

**Issue by jamesz2011** [Tencent/tdesign-vue-next#2274]
### 这个功能解决了什么问题

目前v0.26版本的tree组件：
【问题1】【tree组件】不支持限制显示输出指定层级（即需求只输出父到子节点的3层数据）
【问题2】【tree组件】不支持tree数据的“单选”

### 你建议的方案是什么

1.【tree】只能显示输出前3层
2. 【tree】支持“单选”

**Comment by PengYYYYY** [comment]
1: 暂不支持这个API，只能自行处理数据

**Comment by PengYYYYY** [comment]
2. 支持这种单选
<img width="920" alt="image" src="https://user-images.githubusercontent.com/35833812/218940751-f4cb8a0e-5f79-4047-8015-9409bcc38490.png">

如果是需要 `checkbox` 单选的话，就把组件做成受控的就好，保持 `value` 为一个
