### ISSUE TITLE
[Cascader] 无法像 Select 组件一样使用 0 作为 value

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-vue-next#2278]
### tdesign-vue-next 版本

1.0.3

### 重现链接

https://stackblitz.com/edit/angular-3ewesn?file=package.json,src%2Fdemo.vue

### 重现步骤

Cascader 组件无法像 Select 组件一样使用 0 作为 value

### 期望结果

期望Cascader 组件可以像 Select 组件一样使用 0 作为 value

**Comment by AuYuHui** [comment]
先用字符串 0 吧，看了源码， 数值0 取反 直接 return掉了
