### ISSUE TITLE
[Affix ] nuxt3使用情况下报document is not defined

### ISSUE THREAD

**Issue by ouyangtsin** [Tencent/tdesign-vue-next#2279]
### tdesign-vue-next 版本

1.03

### 重现步骤

document is not defined
![image](https://user-images.githubusercontent.com/26241825/212447073-41880ad2-5a34-40e0-a0ed-f6dc98ac5679.png)

### Node版本

16.13.2

### 补充说明

nuxt3项目页面使用Affix  报错document is not defined

**Comment by Lmmmmmm-bb** [comment]
可以尝试下 Nuxt 提供的 `<ClintOnly>` [相关文档](https://nuxt.com/docs/api/components/client-only#clientonly)
