### ISSUE TITLE
[t-footer] 不应再组件内部设置过多样式

### ISSUE THREAD

**Issue by yudan215** [Tencent/tdesign-vue-next#2281]
### tdesign-vue-next 版本

1.0.3

### 重现步骤

目前Footer Props只有设置一个height属性，但是组件内置了背景色和padding，并且无法定义，设置了height还是会因为padding的原因，导致组件内文字无法居中，

### 期望结果

建议这部分组件不设置过多的属性或者允许外部传值改变

**Comment by pengYYYYY** [comment]
footer 只相当于一个容器，建议自行在里面定义您需要的内容
