### ISSUE TITLE
[Table] 表格组件警告

### ISSUE THREAD

**Issue by rjl-cli** [Tencent/tdesign-vue-next#2288]
### tdesign-vue-next 版本

最新

### 重现步骤

![image](https://user-images.githubusercontent.com/111716113/213423116-82195f16-e073-4c22-b7f7-765a280c1f75.png)
![image](https://user-images.githubusercontent.com/111716113/213423203-7e9b4b6d-49b6-47ef-a658-6d14b5c0e916.png)

**Comment by meymchen** [comment]
我也出现了同样的警告。
只要在`<t-table>`中使用了`data`、`columns`以外的绑定属性就会出现警告。

**Comment by hzgotb** [comment]
#2303 

更新到最新版本。已经修复了。
