### ISSUE TITLE
[Menu] 存在光标

### ISSUE THREAD

**Issue by ONEBUF** [Tencent/tdesign-vue-next#2290]
### tdesign-vue-next 版本

1.04

### 重现步骤

官网示例代码
运行后[](url)

![image](https://user-images.githubusercontent.com/24307511/213466434-aaf0e8ad-6958-4caa-8113-60c5780b84f7.png)

点击的地方有光标闪烁

### 期望结果

其他浏览器暂未发现

### 浏览器版本

Firefox 108.0.2 (20230104165113)

### 系统版本

window10

**Comment by uyarn** [comment]
这个不是组件的问题 是你的浏览器插件 之前也有用户遇到过 看看你装了什么插件导致的
