### ISSUE TITLE
[Input] 指针点击问题

### ISSUE THREAD

**Issue by AllianceTing** [Tencent/tdesign-vue-next#2293]
### tdesign-vue-next 版本

1.0.4

### 重现步骤

<t-header>
<t-header-menu>
<template #operations>
          <t-input-adornment prepend="https://" :append="props">
            <t-input
              clearable
              :v-model="value"
              placeholder="..."
              style="max-width: 500px"
              :style="{ marginRight: '15px',padding:'0'}"
            />
          </t-input-adornment>
          <t-link href="https://tdesign.tencent.com/">
            <t-icon class="t-menu__operations-icon" name="search"
          /></t-link>
</template>
</t-header-menu>
</t-header>
当点击输入框时，input 输入框有重影

![图片](https://user-images.githubusercontent.com/72297937/213875487-8fb63f5b-0a81-481d-ae16-35afcdba1ed6.png)

### 期望结果

取消重影

### 实际结果

有重影 
![图片](https://user-images.githubusercontent.com/72297937/213875482-22e4529d-6c49-425c-9d4c-d765bc282c86.png)

### 框架版本

5.0.8

### 浏览器版本

Chrome(109.0.5414.75)

### 系统版本

windows11

### Node版本

v19.0.0

**Comment by chaishi** [comment]
今天除夕

**Comment by AllianceTing** [comment]
done
