### ISSUE TITLE
[popup] 和avatar组件嵌套使用响应延迟或不响应

### ISSUE THREAD

**Issue by AllianceTing** [Tencent/tdesign-vue-next#2296]
### tdesign-vue-next 版本

1.0.4

### 重现步骤

![图片](https://user-images.githubusercontent.com/72297937/213991453-06497511-4e99-4f04-bf1c-23373f8052c2.png)
![图片](https://user-images.githubusercontent.com/72297937/213991488-61b2e38b-67ac-48e5-ab1f-7444ec662416.png)

### 期望结果

修复

### 框架版本

5.0.8

### 系统版本

windows11

### Node版本

19.0.0

### 补充说明

![图片](https://user-images.githubusercontent.com/72297937/213991580-74260a4c-65ea-4a4d-8794-d94d4222f004.png)
嵌套组件出现问题

**Comment by pengYYYYY** [comment]
https://stackblitz.com/edit/angular-geztew?file=package.json,src%2Fdemo.vue
