### ISSUE TITLE
[Table] 单元格编辑，点击非自身元素无法退出编辑态

### ISSUE THREAD

**Issue by JohnSmiiith** [Tencent/tdesign-vue-next#2302]
### tdesign-vue-next 版本

能

### 重现链接

https://tdesign.tencent.com/vue-next/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

进入编辑单元格状态后，点击其他地方，无法退出编辑态，并且会报错：
![image](https://user-images.githubusercontent.com/38379731/215303511-2fd53cf3-1b62-4e14-8993-e516f713cc7c.png)

### 补充说明

一开始是在目前开发的项目中发现的，后来看到组件库官网也有一样的问题。

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2303
