### ISSUE TITLE
[table] table嵌套错位

### ISSUE THREAD

**Issue by ZONGZI1999** [Tencent/tdesign-vue-next#2309]
### tdesign-vue-next 版本

1.0.4

部署在内网，不方便在此提供

### 重现步骤

table内嵌套table，展开第二 第三个表格时 会出现错位

### 期望结果

不是错位

### 实际结果

错位

### 框架版本

vue 3

### 浏览器版本

Chrome 版本 108.0.5359.124（正式版本） (arm64)

### 系统版本

macos 13.1 (22C65)

### 补充说明

<img width="1609" alt="image" src="https://user-images.githubusercontent.com/56502239/215415265-359ea115-575a-4936-83bd-3a967bb21e24.png">

**Comment by chaishi** [comment]
展开行的功能，含义是展开内容完全自定义，在展开行中定义一个表格，也是自定义内容，和原表格没有任何关系，也不存在对齐或不对齐的关系。本身就是两个完全独立没有任何联系的内容。

如果是对齐，我想你需要的是 树形结构的表格(EnhancedTable)，展开树节点，而非展开行。
http://localhost:17000/vue-next/components/table#%E6%A0%91%E5%BD%A2%E7%BB%93%E6%9E%84%E7%9A%84%E8%A1%A8%E6%A0%BC

<img width="794" alt="image" src="https://user-images.githubusercontent.com/11605702/218242479-de75aa46-4c31-43db-879e-78253331b572.png">
