### ISSUE TITLE
[popup] popup属性overlay-class-name不生效

### ISSUE THREAD

**Issue by JohnnyZhangQiao** [Tencent/tdesign-vue-next#2311]
### tdesign-vue-next 版本

1.0.4

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/29219474/215464640-f06ebc37-7f8c-4bcc-b5ff-94e1471f1e42.png">
class不被采用

### 期望结果

自定义class可以覆盖原本样式

**Comment by pengYYYYY** [comment]
看看这个用法：https://stackblitz.com/edit/angular-ghtv6s?file=package.json,src%2Fdemo.vue

**Comment by JohnnyZhangQiao** [comment]
这样用了全局样式，有同名class时会污染其他组件样式，有更好的scoped局部样式实现吗
