### ISSUE TITLE
[NotifyPlugin] 单独引入 NotifyPlugin，build 时没有带 css 样式

### ISSUE THREAD

**Issue by autodocking** [Tencent/tdesign-vue-next#2312]
### tdesign-vue-next 版本

1.0.4

### 重现步骤

import 'tdesign-vue-next/es/style/index.css'
import {  NotifyPlugin } from 'tdesign-vue-next'

只写上面两条，只引入 NotifyPlugin 的情况下，在 dev 开发模式可以正常显示样式，但是 build 打包后没有引入相应的 css 样式，消息无法正常显示。

一个解决办法是单独引入 import 'tdesign-vue-next/es/notification/style/index.css'
或者是在项目中使用一次 Notification 组件，build 时就会带上 css。

**Comment by BuptStEve** [comment]
> 或者是在项目中使用一次 Notification 组件

你这个用法好奇怪啊，具体是怎么用的呢？

**Comment by BuptStEve** [comment]
或者可以 `app.use(NotifyPlugin)` 一下

**Comment by pengYYYYY** [comment]
NotifyPlugin 源文件没有导出css 文件，已修复
