### ISSUE TITLE
[image] 当图片地址为null 属性error 失效

### ISSUE THREAD

**Issue by 81867370** [Tencent/tdesign-vue-next#2321]
### tdesign-vue-next 版本

1.0.5

### 重现链接

https://stackblitz.com/edit/angular-xnhpjx?file=package.json,src%2Fdemo.vue

### 重现步骤

`<t-image
              v-model:key="errorCount"
              :src="null"
              :style="{ width: '284px', height: '160px' }"
              error="图片失败"
            />`

### 期望结果

如果图片地址为null ，触发 error 属性

### 实际结果

没有触发 error 属性

**Comment by pengYYYYY** [comment]
error 是显示错误的插槽属性
