### ISSUE TITLE
[watermark] 自动导入插件使用的问题提问

### ISSUE THREAD

**Issue by leonWangFearless** [Tencent/tdesign-vue-next#2325]
### tdesign-vue-next 版本

1.0.4

### 重现步骤

vite.config.ts 中写入 unplugin-vue-components/resolvers 的配置以实现自动导入，在使用时发现 Watermark 组件报错，
![image](https://user-images.githubusercontent.com/105188775/216001137-cb3ac3cf-4cb6-441b-8dd8-16527e984fea.png)

找到对应依赖发现问题可能是 Watermark 下没有 style 文件夹导致的，在 unplugin-vue-components 配置项中发现可以用 importStyle: false 来解决报错，页面正常显示。

提问如下： 1. 设置 importStyle: false 会不会影响打包后的样式问题？ 2. 会不会影响其他原子或分子组件的使用？3. 这样配置后推荐在生产中使用吗？4. 是否是 bug 需要双方协商解决？

### 框架版本

Vue(3.2.41)

### 浏览器版本

Chrome(109.0.5414.120)

### 系统版本

win11(22H2)

### Node版本

16.17.1

**Comment by pengYYYYY** [comment]
unplugin-vue-components 属于上游插件，组件库更新后，那边的配置文件可能没有解析到，这类问题我们会统一一个时间处理，有兴趣的话可以先自行解决一下，需要去这边提PR https://github.com/antfu/unplugin-vue-components

**Comment by pengYYYYY** [comment]
importStyle: false 生产环境会出现样式丢失吧

**Comment by uyarn** [comment]
watermark没有样式文件 解决这个问题 我们自己仓库新增个watermark的空样式文件也可以 unplugin发版本挺久的 增加个空文件也不影响体积
