### ISSUE TITLE
[InputNumber ] 小数点，百分位开始无法输入0

### ISSUE THREAD

**Issue by winfcloud** [Tencent/tdesign-vue-next#2332]
### tdesign-vue-next 版本

1.0.5

### 重现链接

https://tdesign.tencent.com/vue-next/components/input-number

### 重现步骤

正常输入框，输入 Y.YX （Y为任意正整数，X为0）
从X位开始后续都无法输入0
无法手动输入，但是可以粘贴

例子：
0.001
0.101
99.000098

### 期望结果

正确输入：
0.001
0.101
99.000098

### 实际结果

0.0   后续无法输入0但是能输入其他正整数
0.1   后续无法输入0但是能输入其他正整数
99.0 后续无法输入0但是能输入其他正整数

### 补充说明

业务中需要定义小数点后8位，可能出现0.0000004这种情况

**Comment by yaogengzhu** [comment]
fixed #2344
