### ISSUE TITLE
[table] 当设置固定某列时，是否考虑固定的列不可拖拽？

### ISSUE THREAD

**Issue by luoyu-233** [Tencent/tdesign-vue-next#2333]
### 这个功能解决了什么问题

当拖拽固定住的那个列的时候，会发生位置错乱是否考虑禁用禁止拖拽固定住的那列
或者再优化一下拖拽列
![image](https://user-images.githubusercontent.com/101392056/216525730-68f61ad0-2eba-43e2-abe6-9e6e31aed84b.png)
![image](https://user-images.githubusercontent.com/101392056/216525784-627f780b-01cb-4df4-85ea-ac0c30f347b2.png)

这个问题是我在组件库文档  
可表头吸顶/表尾吸顶的表格发现的，

### 你建议的方案是什么

是否考虑禁用禁止拖拽固定住的那列
或者再优化一下拖拽列

**Comment by NeilWong84** [comment]
我刚去看了docs，这个不是bug。demo中了表格设置了属性可以按照colum拖拽
把这个属性drag-sort="col" 去掉。同时把绑定的事件@drag-sort 去掉即可

**Comment by chaishi** [comment]
考虑，后续会实现

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2515, 实现效果如下，

https://user-images.githubusercontent.com/11605702/222944729-83a570c6-e2ac-467a-87b3-9b0db83a56ee.mov
