### ISSUE TITLE
[Table] webpack5构建的vue3项目表格组件报错 _this2.renderTd is not a function

### ISSUE THREAD

**Issue by jieyuming** [Tencent/tdesign-vue-next#2334]
### tdesign-vue-next 版本

1.0.0

### 重现步骤

我的项目是采用webpack5搭建的，没采用vite脚手架，官方示例<script setup lang="jsx">的写法其实不支持，我引入@vue/babel-plugin-jsx插件支持jsx语法

### 期望结果

期望能兼容一下webpack5搭建的vue3项目

### Node版本

14.2.0

**Comment by chaishi** [comment]
信息不全，初步估计是函数定义在了 `methods` 中的原因。

https://github.com/Tencent/tdesign-vue-next/pull/2375
在这个 PR 中，已尝试将 `renderTd` 相关函数移动到 `setup` 中，预计 2023.02.14 号左右发布。可使用新版本尝试看看问题是否已经解决

**Comment by jieyuming** [comment]
好的，看源码的确这个方法没定义在methods内



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月11日(周六) 中午1:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-vue-next] [Table] webpack5构建的vue3项目表格组件报错 _this2.renderTd is not a function (Issue #2334)




 
信息不全，初步估计是函数定义在了 methods 中的原因。
 
#2375
 在这个 PR 中，已尝试将 renderTd 相关函数移动到 setup 中，预计 2023.02.14 号左右发布。可使用新版本尝试看看问题是否已经解决
