### ISSUE TITLE
[Table] 文档中有些API说明可能是笔误的，这边收集下

### ISSUE THREAD

**Issue by NeilWong84** [Tencent/tdesign-vue-next#2337]
### tdesign-vue-next 版本

rowClassName API 文档说明

### 重现步骤

行类名，泛型 T 指表格数据类型。
params.row 表示行数据；params.rowIndex 表示行下标；
params.type=body 表示类名作用于 tbody 中的元素；
_params.type=body 表示类名作用于 tfoot 中的元素。_  
......

### 期望结果

_params.type=body 表示类名作用于 tfoot 中的元素。_  （这个应该改为：params.type=foot）

参数说明：`params.row` 表示行数据；`params.rowIndex` 表示行下标；`params.type=body` 表示属性作用于 `tbody` 中的元素；`params.type=foot` 表示属性作用于 `tfoot` 中的元素

(params: RowClassNameParams<T>) => ClassName

主要是源码注释也写错了：

/**
   * 行类名，泛型 T 指表格数据类型。`params.row` 表示行数据；`params.rowIndex` 表示行下标；`params.type=body`  表示类名作用于 `tbody` 中的元素；**`params.type=body` 表示类名作用于 `tfoot` 中的元素**
   */

**Comment by chaishi** [comment]
源代码注释和文档的数据来源是一份
