### ISSUE TITLE
[BUG] [progress] 

### ISSUE THREAD

**Issue by liuqian0413** [Tencent/tdesign-vue-next#234]
### Describe Environment

browser version:
tdesign-vue-next version: 0.4.0

### Describe the bug

progress进度组件，当theme为line时，设置size不生效

codesandbox online demo:

### Additional context

预期：设置不同size，进度条的总长度能跟着变化

**Comment by vnues** [comment]
> ### Describe Environment
> browser version: tdesign-vue-next version: 0.4.0
> 
> ### Describe the bug
> progress进度组件，当theme为line时，设置size不生效
> 
> codesandbox online demo:
> 
> ### Additional context
> 预期：设置不同size，进度条的总长度能跟着变化

切换到最新的版本试试，看看是否存在这个问题

**Comment by pengYYYYY** [comment]
进度条的总长度是继承外部长度，进度用percentage
