### ISSUE TITLE
[Menu] 顶部菜单错误显示折叠按钮

### ISSUE THREAD

**Issue by Cat1007** [Tencent/tdesign-vue-next#2348]
### tdesign-vue-next 版本

1.0.5

### 重现链接

https://stackblitz.com/edit/angular-knl7ef?file=package.json,src%2Fdemo.vue

### 重现步骤

在以较小尺寸进入时，顶部菜单栏会尝试将menu-item项进行折叠，但是，尽管插槽中的元素并不进行展示，也会默认展示折叠按钮，点开后无内容

### 期望结果

当插槽中menu-item不渲染时，不要再显示折叠按钮，释放空间

### 实际结果

存在一个无用的折叠按钮
<img width="318" alt="image" src="https://user-images.githubusercontent.com/54425790/217143013-670c5257-b8a5-40d2-a9fb-307174b873b8.png">

**Comment by uyarn** [comment]
在https://github.com/Tencent/tdesign-vue-next/issues/2779 统一跟进 @Cat1007
