### ISSUE TITLE
[Bug][select] 下拉面板渲染问题

### ISSUE THREAD

**Issue by amadeus711** [Tencent/tdesign-vue-next#235]
## tdesign-vue-next

You will open a bug issue at tdesign-vue-next。

### Describe Environment

browser version:
tdesign-vue-next version: 0.6.4

### Describe the bug

codesandbox online demo: https://codesandbox.io/s/tdesign-vue-next-demo-forked-d08z3?file=/src/demo.vue

### Additional context

点进去先点一下select，面板是暂无数据，然后点击按钮，然后再点击select就能复现

**Comment by pengYYYYY** [comment]
0.7.0版本已修复
