### ISSUE TITLE
[Switch] 支持关闭切换动画

### ISSUE THREAD

**Issue by code2933** [Tencent/tdesign-vue-next#2351]
### 这个功能解决了什么问题

当前点击 switch 的动画给用户一种卡顿的感觉，（应该是动画设计的问题，非性能问题，短暂的点击产生的 handle 拉长产生了运动卡顿的感觉）。

### 你建议的方案是什么

希望可以添加参数，允许关闭切换动画。保留最简单的移动即可，handle 不要在 active 时拉长、移动时缩放。

**Comment by PengYYYYY** [comment]
可以通过 css 覆盖 transition 样式来关闭动画 https://github.com/Tencent/tdesign-common/blob/develop/style/web/components/switch/_index.less#L43
