### ISSUE TITLE
[Select] 选择面板不止是下拉列表的形式

### ISSUE THREAD

**Issue by Cat1007** [Tencent/tdesign-vue-next#2361]
### 这个功能解决了什么问题

在业务场景中，对于某些固定场景的选择，用户会比较熟悉相关的选择项，希望说选择的时候不用下拉列表，而使用类似于checkbox的方式进行多选，这样的话可以避免直接将checkbox平铺出来展示。使用列表无法利用屏幕的横向空间，需要滚动，在高频选择场景下效率不高。

### 你建议的方案是什么

希望提供选择面板的配置，提供不同的排布方式，现在是单行排列，可以支持类似宫格的排列方式，对于比较简短但个数偏多的选项，更好的利用空间。或者支持插槽自定义整个选择面板，提供方法触发某个选项的选择与否。

**Comment by chaishi** [comment]
我想你的需求当前，可以使用 SelectInput 组件实现，这个组件的面板是完全自定义的。

已经用于实现 Select/Cascader/TreeSelect 等多个复杂组件

**Comment by chaishi** [comment]
> 提供不同的排布方式

后续可以安排，需要设计师输出设计稿

**Comment by Cat1007** [comment]
> https://tdesign.tencent.com/vue-next/components/select-input

了解了 初步先用这种方式自己实现一下 但感觉下拉选择换布局的需求比较常见 如果能组件库本身支持就更好了
