### ISSUE TITLE
[表格编辑] 表格编辑下拉框选择之后使用onChange报错

### ISSUE THREAD

**Issue by StevenTang1994** [Tencent/tdesign-vue-next#2362]
### tdesign-vue-next 版本

"tdesign-vue-next": "^1.0.5",

### 重现步骤

```
edit: {
		component: Select,
		// props, 透传全部属性到 Select 组件
		// props 为函数时，参数有：col, row, rowIndex, colIndex, editedRow。一般用于实现编辑组件之间的联动
		props: ({ col, row, rowIndex, colIndex, editedRow }) => {
			// console.log(col, row, rowIndex, colIndex, editedRow);
			// return qryDictList()
			return {
				minCollapsedNum: 1,
				filterable: true,
				onSearch: qryDictList,
				keys: { value: 'dataUpCaseStd', label: 'chName' },
				options: dictList.value,
			};
		},

		on: (editContext) => ({
			onBlur: (...a) => {
				console.log('失去焦点', editContext);
				console.log('onChange之后', a);
			},
			onChange: (...a) => {
				// console.log('onChange之后', editContext); // 报错
				console.log('onChange之后', a);
			},
		}),
		// showEditIcon: false,
		// abortEditOnEvent: ['onChange'],
		onEdited: (context) => {
			table.value.setData(context.row.id, context.newRowData);
			console.log('Edit Letters:', context);
			MessagePlugin.success('Success');
		},
	},
```

### 期望结果

onChange之后 正常拿到参数

### 实际结果

```
Uncaught TypeError: onChange.apply is not a function
    at internalValue.value (useVModel.ts:39:20)
    at Object.setInnerValue2 [as handleValueChange] (select.tsx:74:7)
    at handleClick3 (option.tsx:93:28)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at HTMLLIElement.invoker (runtime-dom.esm-bundler.js:345:9)
```

### 系统版本

Win11

### Node版本

16.15

**Comment by chaishi** [comment]
https://stackblitz.com/run?file=package.json,src%2Fdemo.vue
请在这个链接里面完整地复现上面提到的问题，而非不可运行的纯代码文本。如此，我们才会更快地响应问题

**Comment by StevenTang1994** [comment]
> https://stackblitz.com/run?file=package.json,src%2Fdemo.vue 请在这个链接里面完整地复现上面提到的问题，而非不可运行的纯代码文本。如此，我们才会更快地响应问题
> 
> 复现完成后，保存，复制新链接到 issue

https://stackblitz.com/edit/angular-n2wmcv?file=src/demo.vue

**Comment by chaishi** [comment]
https://stackblitz.com/edit/angular-n2wmcv-jxzhrq?file=src%2Fdemo.vue

属于用法问题，链接里面这样写就对了，属于官方文档示例代码有误，我改一下示例代码

- 记一下规则，凡事 `on: {}` 属性，一律使用不带 on 前缀的中划线事件名称，如：`on: { change: () => {}, blur: () => {xxx} }`
- 作为独立的属性可以使用带 on  的驼峰 `props: { onChange: () => {} }`
这个是 Vue 的规则

**Comment by chaishi** [comment]
- Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/2374
- Vue2/React 没有这个问题

Vue3 出现这个问题的原因，如果给组件传递 2 个 onChage，Vue3 表现为 onChange 变成数组，而 Vue2/React 表现为属性覆盖。

**Comment by chaishi** [comment]
resolved in `v1.0.7`
