### ISSUE TITLE
期望示例代码增加 js/ts 等多种写法

### ISSUE THREAD

**Issue by liweijie0812** [Tencent/tdesign-vue-next#2364]
### 这个功能解决了什么问题

没用过jsx

### 你建议的方案是什么

加个开关切换示例写法
![image](https://user-images.githubusercontent.com/10710889/217816018-1ab78bd1-d54c-4a1f-83ab-14edbedf2e4c.png)

**Comment by chaishi** [comment]
这是一个整个组件库体系是否需要

**Comment by liweijie0812** [comment]
> 这是一个整个组件库体系是否需要

组件库示例代码也不同统一，时而jsx，时而js，还有些是ts

**Comment by chaishi** [comment]
jsx/js/ts 应该不存在你说的统一问题。

首先，代码使用 ts/tsx 开发，是为了让类型定义更加明确。
其次，示例代码使用 js/jsx 开发，是为了照顾不会 TS 的同学，毕竟不是所有人都会 TS，所有人都愿意使用 TS 开发。

示例代码里面存在 jsx 和 插槽多种写法，也是为了告知大家有多种用法，更不是不统一的表现。

**Comment by chaishi** [comment]
由于这不是 Table 一个组件的事情，我们需要整体讨论后续规划，请原谅暂时无法支持，标题也会有所调整

**Comment by liweijie0812** [comment]
https://github.com/Tencent/tdesign-vue-next/discussions/2750
