### ISSUE TITLE
[SelectInput] defaultInputValue不生效

### ISSUE THREAD

**Issue by whitexie** [Tencent/tdesign-vue-next#2372]
### tdesign-vue-next 版本

1.0.6

### 重现链接

https://stackblitz.com/edit/angular-vunxwc?file=package.json

### 重现步骤

```vue
<template>
  <t-select-input
    placeholder="Please Select"
    allow-input
    default-input-value="123321"
  >
  </t-select-input>
</template>
```

### 期望结果

input输入框，展示`123321`

### 实际结果

`false`

### Node版本

v16.14.2

### 补充说明

<img width="702" alt="image" src="https://user-images.githubusercontent.com/30469146/218112821-e43bcc37-ea12-41be-9e3d-25ffa62fd5fe.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2373
预计 2.13 发布
