### ISSUE TITLE
异步加载类对话框，根据文档实例根本没看出来哪里异步了

### ISSUE THREAD

**Issue by wou101771** [Tencent/tdesign-vue-next#2379]
### 这个功能解决了什么问题

异步加载类对话框，根据文档实例根本没看出来哪里异步了。
异步加载类按钮
<template>
  <t-space>
    <t-button @click="visible = true">异步加载类按钮</t-button>
    <t-dialog
      v-model:visible="visible"
      header="保存订单"
      body="订单保存中，请稍后"
      :confirm-btn="{
        content: '保存中...',
        theme: 'primary',
        loading: true,
      }"
      :on-confirm="onConfirm"
      :on-close="close"
    />
  </t-space>
</template>
<script setup>
import { ref } from 'vue';

const visible = ref(false);

const close = () => {
  console.error('===close');
  visible.value = false;
};

const onConfirm = () => {
  console.log('click确定');
};
</script>

### 你建议的方案是什么

提供对应的文档说明

**Comment by chaishi** [comment]
可能标题不合适，但是标题下方有描述。此处是指 确认按钮 可以设置为 `loading` 状态，点击确认按钮，不是立即关闭弹框，而是完成某个操作后再关闭。

<img width="723" alt="image" src="https://user-images.githubusercontent.com/11605702/218273438-373bc747-8c9e-4ef4-9a70-8cdc58e8b2b1.png">

**Comment by chaishi** [comment]
我也看不明白，你是期望修复什么缺陷，还是支持什么特性，issue close
