### ISSUE TITLE
[table] 一键删除子列表，数据源删除了，表格还是显示子列表

### ISSUE THREAD

**Issue by StevenTang1994** [Tencent/tdesign-vue-next#2384]
### tdesign-vue-next 版本

"tdesign-vue-next": "^1.0.5",

### 重现链接

https://stackblitz.com/edit/angular-c5y2le?file=src/demo.vue

### 重现步骤

表格编辑使用下拉框，因为vue3的[onChange回调不能使用](https://github.com/Tencent/tdesign-vue-next/issues/2362)，只能 `context.newRowData` 拿到变更的值之后去做逻辑操作。 

我使用了两种方法都无效
```
// 第一种方法
context.newRowData.children.map((ele) => {
            onDeleteConfirm(ele); // 不是很有效
          });
          // 方法二 根本无效
          context.newRowData.children = null;
// 赋值
 table.value.setData(context.row.id, context.newRowData);

```

### 期望结果

希望能一键删除子列表

### 实际结果

看到newRowData.children已经为null 或者空数组，但是在页面显示上子列表依旧没删除,不过展开符号没有了

### Node版本

16.15

**Comment by chaishi** [comment]
初步估计是，描述的是 “表格的单元格编辑功能”

#2362 这个应该也是你提的吧，我已经里面回复过了，不需要重复 issue

<img width="979" alt="image" src="https://user-images.githubusercontent.com/11605702/218634863-b5a1de3e-f5ab-4cfa-93cc-ccb220a57d19.png">

**Comment by chaishi** [comment]
EnhancedTable 的可编辑功能，还没有实践过，不确定是否正常。
预计 3 月初验证此功能

**Comment by StevenTang1994** [comment]
> EnhancedTable 的可编辑功能，还没有实践过，不确定是否正常。 预计 3 月初验证此功能

不是重复提交代码 是无法一键删除子组件 context.newRowData.children = null; 在数据源里面删除了 但是在页面上没删除

**Comment by chaishi** [comment]
问题已收到，我们会尽快支持 EnhancedTable 完整的可编辑功能

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/3260

fixed at `v1.5.2`
