### ISSUE TITLE
[Select] 开启virtual、multiple和filterable后，下拉选项区域会跳到顶部

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#2385]
### tdesign-vue-next 版本

1.0.6

### 重现链接

https://stackblitz.com/edit/angular-f5sdn9?file=src%2Fdemo.vue

### 重现步骤

1、首次点击下拉选择框
2、在输入框内任意输入
3、将下拉选择区域滚到靠底部
4、任意选择一个选项
5、此时滚动条会自动滚到顶部

### 期望结果

第一次选中后，不会跳到顶部

**Comment by hkaikai** [comment]
1.7.0版本还是有同样的问题，能安排修复一下吗

**Comment by uyarn** [comment]
1.7.1版本已经修复了 可以升级上去看看

**Comment by uyarn** [comment]
1.7.1版本已经修复了 可以升级上去看看

**Comment by IVERSONKI** [comment]
还是存在这个问题，在multiple和filterable都开启的情况下，因为大数据量开启virtual，在将下拉选择区域滚到靠底部，点击选中其中一个选项的时候，panel里scrollTo会直接重置自动滚到顶部，并且点击的选项也没选中
