### ISSUE TITLE
[web-type.json] web-type.json缺少组件slot信息，请补全

### ISSUE THREAD

**Issue by OneSeven** [Tencent/tdesign-vue-next#2389]
### tdesign-vue-next 版本

1.0.6

### 重现链接

https://unpkg.com/browse/tdesign-vue-next@1.0.6/helper/web-types.json

### 重现步骤

https://unpkg.com/browse/tdesign-vue-next@1.0.6/helper/web-types.json

你这个有提示但不完全有，真是，作为webstorm党不太想用下去了

### 期望结果

https://unpkg.com/element-plus@2.2.30/web-types.json

**Comment by chaishi** [comment]
我好像遇到了一位皇帝爷

好想回一句“臣妾做不到啊”

**Comment by chaishi** [comment]
官方回复：信息已收到，需求好说，抽空补充

**Comment by chaishi** [comment]
https://github.com/zloirock/core-js/issues/1179
corejs 开源大佬都吐槽日子不好过了，要么拉赞助，要么找工作。

注意：开源不等于免费。不给钱，不愿意赞助。就请对夜以继日工作，不求回报的开源人好一点。至少语气上客气一点。无论是 ElementUI 还是 TDesign，还是别的什么开源项目。

至少很多像我一样，熬了无数个夜晚在贡献代码，却不是正常拿工资的人。很多像我这样白天忙业务，晚上靠爱发电的人。请尊重一下

**Comment by chaishi** [comment]
这是 Element 官方的赞助位，位置明显，很容易找到，人家做的那么符合你的心意，花个几块，几十块，赞助一下，帮一下也挺好

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/11605702/218925592-c7456dbe-816e-4119-ba4f-4903ff74f92c.png">

**Comment by OneSeven** [comment]
> [zloirock/core-js#1179](https://github.com/zloirock/core-js/issues/1179) corejs 开源大佬都吐槽日子不好过了，要么拉赞助，要么找工作。
> 
> 注意：开源不等于免费。不给钱，不愿意赞助。就请对夜以继日工作，不求回报的开源人好一点。至少语气上客气一点。无论是 ElementUI 还是 TDesign，还是别的什么开源项目。
> 
> 至少很多像我一样，熬了无数个夜晚在贡献代码，却不是正常拿工资的人。很多像我这样白天忙业务，晚上靠爱发电的人，不说喜欢，至少请尊重一下

哦。腾讯没给你钱是吧，是你个人或者是你们非商业化集团的项目吗，你们腾讯原始目的是把这个作为真真开源项目来做的吗，你那么委屈自己内部用啊，开源出来干嘛，还把core-js拿出来比，G点这么高？

**Comment by lvisei** [comment]
> 我好像遇到了一位皇帝爷
> 
> 好想回一句“臣妾做不到啊”

遇到皇帝可选择不伺候，直接忽略就是，处 Issues 之道：

![image](https://user-images.githubusercontent.com/26923747/218938271-19a02672-a287-46af-adcd-cf08624b4502.png)

**Comment by chaishi** [comment]
> 哦。腾讯没给你钱是吧

是啊，腾讯确实不给我参与开源协同项目的工资的，只给我业务开发的工资。全是业余时间哦。

> 还把core-js拿出来比，G点这么高

不是和 corejs 比哦，那我肯定比不上的，至少我给 corejs 捐了 $150 表达敬意和感激，不多，至少有（人民币美元汇率：6.81）。

借用 corejs 也只是想表达开源人不容易，需要的也只是简单的尊敬，大家好声好气地讲话，多好啊。

**Comment by chaishi** [comment]
@lvisei 有道理啊

**Comment by chaishi** [comment]
本来我也以为你的 “请”， 是礼貌用语。但是看完内容，不，你的“请” 是命令，是泄愤。 
标题是不是真的礼貌用语，你比任何人都清楚。
其他的很多很多 issue 都是正常口吻，有很多参考，你可以看看的。

你可以用那句话表达你的看法，我也同样可以表达我的看法呀。你喷你的，我喷你。

你的口碑差也不是没有原因吧，我都几乎看不到有人给你点赞，几乎踩你。如果“给你点赞的人”超过“踩你的人”，我可以立即退出项目，说明不适合。 如果没有超过，回馈最基本的尊重

**Comment by chaishi** [comment]
这才是官方的回复哦“需求好说，抽空就补上”

<img width="419" alt="image" src="https://user-images.githubusercontent.com/11605702/218972958-3210c07a-c5ac-4320-ae3f-4056496af673.png">

**Comment by chaishi** [comment]
应你所愿，不需回复，删除 issue close 后回复

**Comment by chaishi** [comment]
和垃圾人说话真累，你说 issue close 了，别回了。
我删了，我就删掉 close 后的，你还来

**Comment by chaishi** [comment]
本来还想回来着，但是你说 issue close 了都，别回了，那就是不希望 issue 都 close 了还继续嘛。

我删的不仅是自己的，还是你的流浪言论，同一时间段的。公平的啊
而且前面一个时间段，你么有表达意愿，我没动

**Comment by chaishi** [comment]
唉，平时 comment 养成的坏习惯，不该，不该啊。不过你也可以哦。

同事都挺聪明，就我笨啊，一次性理不清楚，打错字啊，想的不太对啊。不像你这么正规，每次都一把过。

**Comment by chaishi** [comment]
我都这么说了，你还…..   好吧，那我先走了

**Comment by chaishi** [comment]
首先，感谢提问。Vue3 resolved in #2393, Vue2 resolved in #2148

其次，带着你的蹩脚的结论，滚

**Comment by MarkGor** [comment]
> 首先，感谢提问。Vue3 resolved in #2393, Vue2 resolved in #2148
> 
> 其次，带着你的蹩脚的结论，滚

看了你的回復，感覺好可愛，確實沒必要卑躬屈膝；
