### ISSUE TITLE
[ColorPicker] 色值输入问题

### ISSUE THREAD

**Issue by zhengweicheng123zwc** [Tencent/tdesign-vue-next#2392]
### tdesign-vue-next 版本

vue next 0.26.2

### 重现链接

https://0_26_2-tdesign-vue-next.surge.sh/vue-next/components/color-picker

### 重现步骤

一：【bug】颜色选择器 渐变模式 不能通过输入来更改色值颜色
二：【bug】颜色选择器 渐变模式 添加多个色值点后 不能删除色值点
三：【优化】颜色选择器 色值输入框HXE输入时默认添加“#”

### 期望结果

一：【bug】颜色选择器 渐变模式 可通过HEX、RGB等输入框来更改渐变颜色
二：【bug】颜色选择器 渐变模式 添加多个色值点后 向外拖动色值点即可删除
三：【优化】颜色选择器 色值输入框HXE输入时默认添加“#”

**Comment by uyarn** [comment]
@zhengweicheng123zwc 和设计讨论了下还有点交互要改 这周的版本先不带上了 下周再带上

**Comment by uyarn** [comment]
[x] 颜色选择器 渐变模式 不能通过输入来更改色值颜色
[ ] 颜色选择器 渐变模式 添加多个色值点后 不能删除色值点 ——— 目前可以通过按删除键删除选中的色值断点 但会新增拖拽删除的交互 duplicate of https://github.com/Tencent/tdesign-vue-next/issues/2544
[ ] 颜色选择器 色值输入框Hex输入时默认添加“#” —— 这个新增到#2544 中跟进 一个issue维护
