### ISSUE TITLE
[Tree] filter过滤显示异常

### ISSUE THREAD

**Issue by chener999** [Tencent/tdesign-vue-next#2400]
### tdesign-vue-next 版本

1.0.5

### 重现步骤

1. TDesign Starter中列表页-树状筛选列表页
2. 过滤框如果是打字搜索 会有部分时候出现全部展示
3. 如果是复制进去 则无异常出现

### 期望结果

<img width="498" alt="image" src="https://user-images.githubusercontent.com/120468431/219262787-f108f6ac-a9c4-48ca-93c1-27cf6f7dbaf9.png">

### 实际结果

<img width="616" alt="image" src="https://user-images.githubusercontent.com/120468431/219262876-40f99720-58c2-41fa-9bc1-4f9318c84a2a.png">

### 框架版本

vue 3.2.45

### 系统版本

Macos 12.6

### Node版本

16.16.0

**Comment by PengYYYYY** [comment]
https://user-images.githubusercontent.com/35833812/219282164-92e75b45-132d-454a-808f-23263ccb4ebe.mov


未发现yi chang异常

**Comment by liweijie0812** [comment]
> 未发现异常

要是用拼音输入法才能触发bug
