### ISSUE TITLE
[Input 输入框] Value为null时，计算出的输入长度是4

### ISSUE THREAD

**Issue by souselesslove** [Tencent/tdesign-vue-next#2401]
### tdesign-vue-next 版本

1.0.7

### 补充说明

[Input 输入框](https://github.com/Tencent/tdesign-vue-next/blob/develop/src/input/useInput.ts)
![image](https://user-images.githubusercontent.com/26608215/219266872-4b7888eb-610c-4719-ae4a-e527a0eb0afc.png)
只判断了undefined，未判断null，使用String()转换就会把null变成'null'

**Comment by chaishi** [comment]
null 的数据类型是 object，可以先设置 undefined 解决问题

**Comment by chaishi** [comment]
`null` 长度计算问题，resolved in https://github.com/Tencent/tdesign-vue-next/pull/2402

预计下周二发布
