### ISSUE TITLE
[Guide] Guide引导框body内容丢失

### ISSUE THREAD

**Issue by keleus** [Tencent/tdesign-vue-next#2411]
### tdesign-vue-next 版本

1.0.7

### 重现链接

https://1_0_7-tdesign-vue-next.surge.sh/vue-next/components/guide

### 重现步骤

- 打开官网1.0.7版本Demo（上述链接）
- 点击基本引导-新手引导的样例

### 期望结果

正常显示Title、body内容。

### 实际结果

只显示了Title，没有显示body内容。

### Node版本

18.14.0

**Comment by chaishi** [comment]
resolved in `v1.0.8`
