### ISSUE TITLE
[t-form] 当form组件使用rules的validator自定义校验时，类型FormRule报错

### ISSUE THREAD

**Issue by ace0109** [Tencent/tdesign-vue-next#2413]
### tdesign-vue-next 版本

1.0.7

### 重现步骤

当form组件使用rules的validator自定义校验时

### 期望结果

`import type {FormRule } from 'tdesign-vue-next';`
类型FormRule在vscode里需要正常

### 实际结果

`import type {FormRule } from 'tdesign-vue-next';`
类型FormRule在vscode里会报错

**Comment by chaishi** [comment]
请问具体是什么报错？方便截图么

**Comment by cafehaus** [comment]
![image](https://user-images.githubusercontent.com/21158560/223053819-6f002534-b642-4e09-9dd6-a4bc2ad26301.png)
我也遇到了这个问题，报错：不能将类型“{ text: { validator: (value: any) => { result: boolean; message: string; type: string; }; }[]; code: { required: boolean; message: string; type: string; trigger: string; }[]; }”分配给类型“{ [x: string]: FormRule[]; }”。
  属性“text”与索引签名不兼容。ts(2322)
