### ISSUE TITLE
tdesign-vue-next 1.0.8 + vite 4.1.x 无法启动dev server

### ISSUE THREAD

**Issue by cloudfun** [Tencent/tdesign-vue-next#2419]
### tdesign-vue-next 版本

1.0.8

### 重现步骤

在vite 4.1.2环境下运行时出现错误，dev server无法启动
failed to load config from /Users/inc0ming/WebstormProjects/unibuying-oa/webfront-v2/vite.config.ts
error when starting dev server:
ReferenceError: window is not defined

### 框架版本

Vue(3.2.47)

### 浏览器版本

Chrome(107.0.5304.87)

### 系统版本

MacOS(13.0)

### Node版本

19.6.1

### 补充说明

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/962598/219843957-bc7ce8cb-216c-4cf6-86da-d7d9a499f0cd.png">

**Comment by chaishi** [comment]
辛苦更新一下标题，感谢

**Comment by PengYYYYY** [comment]
可以暂时使用一下 1.0.9-alpha.3
