### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by catious** [Tencent/tdesign-vue-next#2420]
### tdesign-vue-next 版本

0.24.6

### 重现步骤

input框输入大于号保存后转义，输入小于号保存后直接清空了
![image](https://user-images.githubusercontent.com/47728403/219852685-450b7264-9909-4451-bafd-e8bf939bf10e.png)

### 期望结果

input框输入符号后可以保存原来的样子

### 实际结果

input框输入大于号保存后转义，输入小于号保存后直接清空了

**Comment by PengYYYYY** [comment]
能提供在线示例嘛

**Comment by PengYYYYY** [comment]
没有复现出您这个表现

**Comment by chaishi** [comment]
我也没有复现这个问题。issue 暂时关闭，待有可复现问题的示例代码后，可以 reopen。

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue
可以在这个链接里面复现一下你提到的问题
