### ISSUE TITLE
[Dialog] 通过body属性传递的字符串无法换行

### ISSUE THREAD

**Issue by volatile-static** [Tencent/tdesign-vue-next#2432]
### tdesign-vue-next 版本

1.0.7

### 重现链接

https://stackblitz.com/edit/angular-5kgngj?file=src/demo.vue

### 重现步骤

如链接所示

### 期望结果

可以在字符串内使用\n\r等转义符实现换行显示

### 浏览器版本

所有

### 系统版本

win11

**Comment by chaishi** [comment]
如果有的业务并不希望 `\n` 被显示成换行怎么办

**Comment by AuYuHui** [comment]
可以自己写插槽

**Comment by volatile-static** [comment]
请问dialogplugin调用也可以插槽吗

**Comment by volatile-static** [comment]
> 如果有的业务并不希望 `\n` 被显示成换行怎么办

那是不是可以写成\\n？

**Comment by AuYuHui** [comment]
> 请问dialogplugin调用也可以插槽吗

自己写 render 函数试试

**Comment by volatile-static** [comment]
```js
body: h =>
  h(
    'div',
    msg.split('\n').map(s => h('p', s))
  ),
```
这样写效果很好。如果你们不打算修改的话，可以关闭issue了
