### ISSUE TITLE
[Dialog] 确认按钮主题不应当跟随 Dialog 主题变动

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign-vue-next#2433]
### tdesign-vue-next 版本

1.0.8

### 重现链接

https://tdesign.tencent.com/vue-next/components/dialog?tab=demo

### 期望结果

设计稿：https://www.figma.com/community/file/1053279236128724321
<img width="910" alt="image" src="https://user-images.githubusercontent.com/7600149/220064484-40761fca-5e10-4ec9-b504-e5535def30de.png">

### 实际结果

<img width="727" alt="image" src="https://user-images.githubusercontent.com/7600149/220064569-e05842ba-9a58-4501-92b1-4b843d63f787.png">

**Comment by chaishi** [comment]
我记得最初的版本是不跟随的，啥时候跟随了~~~~

**Comment by xiaosansiji** [comment]
https://github.com/Tencent/tdesign-vue/issues/2162

**Comment by xiaosansiji** [comment]
> 我记得最初的版本是不跟随的，啥时候跟随了~~~~

don't kown... vue2/vue next 这么搞了，react 实现是对的
