### ISSUE TITLE
[Drawer 抽屉] Drawer 展开时如果不获取到焦点，onEscKeydown事件触发不了，必须鼠标点击到Drawer 区域才能触发

### ISSUE THREAD

**Issue by 3109981200** [Tencent/tdesign-vue-next#2437]
### tdesign-vue-next 版本

"tdesign-vue-next": "^1.0.7" 文档和项目中都有复现

### 期望结果

期望在Drawer展开时在未获取焦点时也能触发onEscKeydown事件

### Node版本

18.7.0

**Comment by chaishi** [comment]
如果没有聚焦，也触发关闭，如何知道是作用于 Drawer 呢，
没有灰色背景时的场景，也可能是操作其他

**Comment by 3109981200** [comment]
@chaishi 这么说也是对的，当showOverlay为true显示遮罩时能实现不聚焦也触发关闭吗
