### ISSUE TITLE
[Table]Footer设置合并单元格后，固定列样式不正确（不太明白具体哪里不正确，需求确认中）

### ISSUE THREAD

**Issue by Kigoal** [Tencent/tdesign-vue-next#2443]
### tdesign-vue-next 版本

1.0.8

### 重现链接

无

### 重现步骤

```vue
<script setup lang="ts">
const data = [
  {
    test1: 1,
    test2: 'asdassaasasas',
    test3: '12456443532',
  },
];

const columns = [
  {
    colKey: 'test1',
    title: 'test1',
    width: 100,
    fixed: 'left',
  },
  {
    colKey: 'test2',
    title: 'test2',
    width: 100,
    fixed: 'left',
  },
  {
    colKey: 'test3',
    title: 'test3',
    width: 1000,
  },
];
</script>

<template>
  <PrimaryTable
    :data="data"
    :columns="columns"
    :foot-data="[{ test1: `合计: ${amountTotal}` }]"
    :rowspan-and-colspan-in-footer="
      ({ rowIndex, colIndex }) => {
        if (rowIndex === 0 && colIndex === 0) {
          return {
            colspan: 2,
          };
        }
      }
    "
  />
</template>

```

### 期望结果

正确显示分割条

### 实际结果

表底在横向滚动时没有显示分割条
![image](https://user-images.githubusercontent.com/21240282/220292432-01053f20-5400-4eef-a982-1ab941b70971.png)

**Comment by chaishi** [comment]
没有明白文中描述的“分割条” 具体是指什么，难以处理

**Comment by Kigoal** [comment]
> 没有明白文中描述的“分割条” 具体是指什么，难以处理
就是这个，没有合并单元格时会正常显示
![image](https://user-images.githubusercontent.com/21240282/220299542-c2b4dfd8-f9a3-4205-babc-f724bf95ed3a.png)
![image](https://user-images.githubusercontent.com/21240282/220299626-c60238ea-4f54-4950-9c56-8b9620ac2595.png)

**Comment by Kigoal** [comment]
还有一个问题，在移动端下。有固定列的时候，横向滑动表头和表身不会同步移动
![image](https://user-images.githubusercontent.com/21240282/220302706-f204f38b-111f-40a2-a814-d6874f7f0b06.png)

**Comment by chaishi** [comment]
- 先说标题中的问题，合并列的效果就是 多列合并成一列，如果按照你期望的效果就不再是同一列，而是多列，不符合预期，暂不调整。
- 再看移动端，TDesign Web 类组件暂未考虑过支持移动端，也从未测试过移动端的运行情况，可能暂时也不会处理移动端的情况。  如果希望支持移动端，可以单独再提 issue，大家整体讨论“tdesign-vue-next 是否需要全量支持移动端运行”
