### ISSUE TITLE
[Table] 表格topContent插槽与columnController列控制同时使用时，无法在同一行内显示

### ISSUE THREAD

**Issue by ngyyuusora** [Tencent/tdesign-vue-next#2450]
### tdesign-vue-next 版本

1.0.9

### 重现步骤

文档中有提到可对按钮父元素宽度进行设定实现行内显示，但多次尝试未找到应修改哪个元素的样式
![c6f50ddd6c520f2bed4c29c19d8142b](https://user-images.githubusercontent.com/28800738/220561407-ca8d9359-df82-4a86-b483-8bd4697c6812.png)

需要对该粉色div添加flex可以实现行内显示
![5c89f2d546c7a77ac07abef5e4894dc](https://user-images.githubusercontent.com/28800738/220561513-cd02bf70-ad7a-45fb-bc50-47b27ca08198.png)

### 期望结果

期望效果
![image](https://user-images.githubusercontent.com/28800738/220561650-3fed416f-c210-4f5e-8553-ede825097ed3.png)

### 实际结果

现状
![aa2b4ca492e5a16534b878cec986a27](https://user-images.githubusercontent.com/28800738/220561173-58200b42-1a84-4d1e-bd9d-aea0c7a7e3d3.png)
![64a58a85ff4e6b87a92da516439427b](https://user-images.githubusercontent.com/28800738/220561207-0f108df9-5903-4460-abe9-cb57191d54e2.png)
![dfd3bb1a6f94f4b07d5669c4b855356](https://user-images.githubusercontent.com/28800738/220561220-f6fbad25-4ce1-448e-a08c-4dff7f4e54a7.png)

**Comment by ngyyuusora** [comment]
主要是为了实现此种并非限定对单个记录（row）操作的按钮放置
![image](https://user-images.githubusercontent.com/28800738/220568977-74061ddf-8aaf-48e5-8433-dc71d140f5ab.png)
![image](https://user-images.githubusercontent.com/28800738/220569057-d713b9ca-a57b-4a5c-a3ad-55c3b74605fd.png)

**Comment by ngyyuusora** [comment]
请问哪位可以回复一下吗

**Comment by ngyyuusora** [comment]
请问这个问题有大神可以解答一下吗？目前先写自定义筛选按纽了
这个是不是可以设计成让顶部内容插槽支持筛选按纽或者反过来，让列控制支持插槽可以传按纽进去放在前面展示呢

**Comment by Aicmortal** [comment]
@ngyyuusora 
sorry,久等了
你可以通过:deep的方式修改组件的CSS实现,这是一个简单的Demo
https://stackblitz.com/edit/angular-bbbh4e?file=src/demo.vue
