### ISSUE TITLE
[Input] 输入框设置 clearable 时与 suffixIcon 重叠

### ISSUE THREAD

**Issue by MeanZhang** [Tencent/tdesign-vue-next#2451]
### tdesign-vue-next 版本

1.0.9

### 重现链接

https://stackblitz.com/edit/angular-f9pjyw?file=src/demo.vue

### 重现步骤

代码：
```vue
<template>
  <t-input v-model="value" clearable placeholder="请输入">
    <template #suffix-icon>
      <lock-on-icon />
    </template>
  </t-input>
</template>
<script setup>
import { ref } from 'vue';
import { LockOnIcon } from 'tdesign-icons-vue-next';

const value = ref('Hello TDesign');
</script>
```

### 期望结果

clearable 按钮显示在 suffix 之前

### 实际结果

value不为空时，获取焦点后，clearable 按钮会覆盖 suffix
![image](https://user-images.githubusercontent.com/40561709/220644794-cc1e17f6-f980-47dc-8185-16287bb95096.png)
![image](https://user-images.githubusercontent.com/40561709/220644865-eca9527f-4f1a-4ea1-bc16-1cadc93ad3d7.png)

### 框架版本

Vue(3.2.40)

### 浏览器版本

Edge(109.0.1518.78)

### 系统版本

Windows 11 22H2

### Node版本

v16.14.2

### 补充说明

无

**Comment by chaishi** [comment]
设计如此，不希望一个输入框出现多个的图标，视觉效果不优雅。

如果不想覆盖可以设置suffix
