### ISSUE TITLE
[menu] menu-item 使用:href 属性时, icon图标显示异常(小)

### ISSUE THREAD

**Issue by chutrue** [Tencent/tdesign-vue-next#2452]
### tdesign-vue-next 版本

1.0.9

### 重现链接

https://stackblitz.com/edit/angular-bhpydx?file=package.json,src%2Fdemo.vue

### 重现步骤

```vue
<t-menu-group title="主导航">
  <t-menu-item value="item1" :href='"https://www.baidu.com"'>
    <template #icon>
      <t-icon name="app" />
    </template>
    百度
  </t-menu-item>
</t-menu-group>
```

### 期望结果

当 `t-menu` 的属性  `:collapsed` 为 `真` 时，希望 `t-menu-item` 的 `icon` 大小显示正常, 且 生成的 `a` 标签 `铺满`

### 实际结果

问题：
1. `icon` 显示小
2. 点击 `:href` 生成的导航 `a` 标签宽度太小不能铺满空间

**Comment by chutrue** [comment]
![image](https://user-images.githubusercontent.com/21192098/220840492-a26d486f-e610-4338-b1f1-877a2c387520.png)
![image](https://user-images.githubusercontent.com/21192098/220840710-5a41f33b-d5df-4652-bcd3-c9d407c5e1ca.png)

**Comment by chutrue** [comment]
没有回复吗?

**Comment by tiny-dust** [comment]
我认领此问题，预计今天提交代码
