### ISSUE TITLE
API文档改进意见

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#2453]
### 这个功能解决了什么问题

API文档中如果属性的类型是Function，没有对函数的返回值类型做说明。如：Table表格-BaseTableCol-cell，返回类型可以是string|TNode

### 你建议的方案是什么

API文档中如果属性的类型是Function，可以说明返回类型

**Comment by chaishi** [comment]
按理说，每一个API 都有详细的参数和返回值描述，不知道是哪里没有。请截图告知。

如果你是说 TNode，十分抱歉，这是整个组件库体系频繁出现的数据类型，不会每一个API 去繁琐重复地描述参数和返回值，你可以在 通用数据类型链接 里面查看具体的返回值。

**Comment by lin-code-world** [comment]
![image](https://user-images.githubusercontent.com/43373990/220880299-bae19fa9-91a2-45e3-8aa9-599d213b4ee9.png)

**Comment by chaishi** [comment]
<img width="991" alt="image" src="https://user-images.githubusercontent.com/11605702/222917610-ea53490c-2eb5-4663-a345-12ec7f08f803.png">

@lin-code-world  再重复一下，你的截图就是 TNode，而 `TNode<XXX>` 在所有组件中都是同样的、一模一样的返回值，也就是返回值全部都是 tsx/jsx 节点，也一定不会在文档中刻意重复强调 N 次。

再强调一下，所有的渲染函数返回值均为 JSX/TSX 节点，即：() => <div>1234</div> 或者 () => '1234213'。
cell 可以作为插槽名，也可以作为渲染函数。看到 `TNode` 就要求一定是返回自定义节点。

最后，`详细类型定义` 链接里面包含了十分、非常、特别、完整、全部的 TS 类型，包括你说的返回值。你只需要动动手指头，点击一下跳转查看，搜索 “cell” 直达对应的类型定义。这是查看 API TS 类型最准确的方式，掌握了这项技能，就不会再有类似的问题了。 所有组件的 API，凡事存在复杂类型定义的 API，都会存在「详细类型定义」。

至此，组件文档暂时不会再做额外的补充。
