### ISSUE TITLE
[Textarea]设置autosize属性后，没有限制size大小

### ISSUE THREAD

**Issue by Kigoal** [Tencent/tdesign-vue-next#2456]
### tdesign-vue-next 版本

1.0.9

### 重现链接

https://tdesign.tencent.com/vue-next/components/textarea#%E5%9F%BA%E7%A1%80%E5%A4%9A%E8%A1%8C%E6%96%87%E6%9C%AC%E6%A1%86

### 重现步骤

```vue
<template>
  <Textarea :autosize="{ minRows: 2, maxRows: 5 }" />
</template>
```

### 期望结果

略

### 实际结果

官网示例也可以复现
![Uploading 054bb40e77f2328a5ddac84ed8c2911.png…]()

**Comment by Zzongke** [comment]
<img width="640" alt="截屏2023-03-01 16 40 09" src="https://user-images.githubusercontent.com/65376724/222087653-f090265f-5a6b-4916-b65c-134ae6b19127.png">
See if the textarea you used is wrong, because it should be t-textarea
