### ISSUE TITLE
[Drawer] 找不到DrawerPlugin类

### ISSUE THREAD

**Issue by cloudfun** [Tencent/tdesign-vue-next#2460]
### tdesign-vue-next 版本

1.0.9

### 重现链接

https://tdesign.tencent.com/vue-next/components/drawer?tab=api#drawerplugin

### 重现步骤

import {DrawerPlugin} from "tdesign-vue-next";
提示 ‘Module '"tdesign-vue-next"' has no exported member 'DrawerPlugin'. ’, 看了源码确实没有DrawerPlugin类型.

### 框架版本

Vue(3.2.47)

### 浏览器版本

Chrome(107.0.5304.87)

### 系统版本

MacOS(13.0)

### Node版本

19.6.1

### 补充说明

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/962598/221126983-614e8413-b5f4-48e5-abe2-35e93bb280d6.png">

**Comment by PengYYYYY** [comment]
暂时没有支持这个plugin的计划
