### ISSUE TITLE
[Table] 【Typescript】在表格中加入可选中行时，在定义columns数据时，BaseTableCol类中无`type`字段

### ISSUE THREAD

**Issue by ruancong** [Tencent/tdesign-vue-next#2461]
### tdesign-vue-next 版本

1.0.8

### 重现步骤

 
![image](https://user-images.githubusercontent.com/7631338/221142192-bfee9bf1-579e-43fa-be1b-f2bba7cbc908.png)

### 期望结果

能在BaseTableCol类型中加入type字段

### 框架版本

3.2.45

### 系统版本

windows 10 

### Node版本

16.14.2

### 补充说明

在Table中加入单选或多选列时

**Comment by chaishi** [comment]
Table 总共分 3 个组件：BaseTable/PrimaryTable/EnhancedTable。

行选中列属于 PrimaryTable 的功能，更为使用 `PrimaryTableCol` 即可。

以后遇到类似的类型问题，可以在 [table type.ts](https://github.com/Tencent/tdesign-vue-next/blob/develop/src/table/type.ts) 中搜索查询。这样的方式可以比提 issue 更快地获得想要的结果或答案
