### ISSUE TITLE
[Upload] 批量文件/图片上传`auto-upload = false` 时，支持上传/取消按钮自定义

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#2469]
### 这个功能解决了什么问题

Upload组件auto-upload=false 时，多出来的“取消上传、点击上传”两个按钮可以自定义

### 你建议的方案是什么

Upload组件auto-upload=false 时，多出来的“取消上传、点击上传”两个按钮可以自定义，通过插槽或者属性可以自定义按钮，可以不显示

**Comment by chaishi** [comment]
如果是不显示可以先自己写一个 `display: none` 隐藏

**Comment by lin-code-world** [comment]
> 如果是不显示可以先自己写一个 `display: none` 隐藏

目前我是这么做的。希望能增加自定义的功能，如果要修改按钮样式就比较麻烦了

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/3566

**Comment by chaishi** [comment]
resolved at `v1.6.8` 2023-11-07
已在 `v1.6.8` 中支持
