### ISSUE TITLE
[Improve][Image] 缺少图片组件

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#250]
![image](https://user-images.githubusercontent.com/30982989/150620620-0cd79284-b0f0-4628-9e90-1cd0e8b5a8aa.png)
我看推进计划里面没有，希望能够加上，也算是一个高频组件了

**Comment by pengYYYYY** [comment]
后面会加，还没出稿子，暂时没有那么快

**Comment by yixiaco** [comment]
> 后面会加，还没出稿子，暂时没有那么快

我看推进计划里面没有， 这个组件用到的频率应该蛮高的 :smile:
