### ISSUE TITLE
[Badge] dot, show-zero="false" 不应该显示角标

### ISSUE THREAD

**Issue by wvq** [Tencent/tdesign-vue-next#2502]
### tdesign-vue-next 版本

1.0.9

### 重现步骤

```vue
<template>
  <t-badge count="0" :show-zero="false" dot>
      <t-button>按钮</t-button>
    </t-badge>
</template>
```

### 期望结果

`count=0  show-zero=false` 此时不应该有红点

### 实际结果

配置成`dot`, 始终有红点

**Comment by tiny-dust** [comment]
或许可以改成是 :dot="count !== 0" ?？

**Comment by Aicmortal** [comment]
react正常,vue和vue-next都存在这个问题
