### ISSUE TITLE
[Table] 表格嵌套使用时，内部子表格 size=small 无效

### ISSUE THREAD

**Issue by yiweiyu1225** [Tencent/tdesign-vue-next#2510]
### tdesign-vue-next 版本

[table] 在展开的表格里再放一个表格，设置第二个表格的size为small

### 重现链接

https://stackblitz.com/edit/angular-z9fkgh-myttg2?file=src/demo.vue

### 重现步骤

在展开的表格里再放一个表格，设置第二个表格的size为small，但是不生效

**Comment by Aicmortal** [comment]
事实上当你使用嵌套表格时,父表格的大小会影响子表格,子表格本身也是small了,只是没看出来而已,你可以删除size仔细对比一下;
嵌套的子表格表格处的size处在medium(默认就是),子表格的大小会受到父表格的影响,这是因为类名的影响;
