### ISSUE TITLE
[Upload]关于Upload组件一次性上传多个文件的修改疑问

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#2512]
tdesign-vue-next 版本
1.1.1

关于Upload组件
”一个请求上传多个文件时，去除重复参数 file，保留 file[0] file[1] 即可，同时新增参数 length 表示本次上传文件的数量“的改动，
我想了解下为何要做该改动，原本重复参数file是符合formData形式的传参，后端可以用MultipartFile接受，现在改成file[0] file[1]导致无法接受，是出于什么原因改变这个。

**Comment by chaishi** [comment]
之前的 `file` 和 `file[0]` 是同一个文件，file 是多余的。

改成 `file[0]` `file[1]` 应该也是可以接收的，只是名字不一样。注意接收数据的时候 `file[0]` 不是指数组 `file`，而是字符串 `file[0]`

**Comment by lin-code-world** [comment]
可不可以改成FormData，file数组形式传到后端，这种方式比较通用。file[0]，file[1]....字符串形式有点非常规

**Comment by chaishi** [comment]
本身依然是 FormData，代码见 https://github.com/Tencent/tdesign-common/blob/develop/js/upload/xhr.ts#L79

我尝试过 file 是数组形式，但最终请求里面看到的数据是异常的，如下图数组形式。
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/11605702/222951890-69db0778-a0a6-4fbc-8a2f-15ed848c4ab1.png">

**Comment by chaishi** [comment]
当前，你可以使用 `formatRequest` 完全自定义任何你想要的请求字段，比如：
```
formatRequest = (formData) => ({ file: [xxx, yyy] })
```
<img width="965" alt="image" src="https://user-images.githubusercontent.com/11605702/222951569-efd075fc-a45f-4ae6-a2df-709b95ea2bd0.png">

**Comment by lin-code-world** [comment]
上传文件使用的是Content-Type: multipart/form-data，我建议formatRequest返回FormData类型，现在是返回json

**Comment by chaishi** [comment]
formatRequest 返回的是 Object 对象，传递给请求的时候，就是 FromData
https://github.com/Tencent/tdesign-common/blob/develop/js/upload/xhr.ts#L83

**Comment by lin-code-world** [comment]
https://github.com/Tencent/tdesign-common/pull/2078
能不能按这个方式合并一下代码，解决这个问题？
