### ISSUE TITLE
[Upload] v-model的值为false会报错

### ISSUE THREAD

**Issue by bubai1125** [Tencent/tdesign-vue-next#2513]
### tdesign-vue-next 版本

1.1.1

### 重现步骤

 <t-upload  v-model="files1" action="https://service-bv448zsw-1257786608.gz.apigw.tencentcs.com/api/upload-demo" />

  data(){
    return{
      files1:false,
    }
  }

![image](https://user-images.githubusercontent.com/49055470/222881791-2973d16a-82c8-4303-beeb-a5163bd7ca5a.png)

### 期望结果

绑定的v-model为false或为空的情况下应自动生成数组，且不会报错

### 实际结果

绑定的v-model为false或为空的情况下报错，无法上传文件

**Comment by bubai1125** [comment]
> ### tdesign-vue-next 版本
> 1.1.1
> 
> ### 重现链接
> _No response_
> 
> ### 重现步骤
> data(){ return{ files1:false, } }
> 
> ![image](https://user-images.githubusercontent.com/49055470/222881791-2973d16a-82c8-4303-beeb-a5163bd7ca5a.png)
> 
> ### 期望结果
> 绑定的v-model为false或为空的情况下应自动生成数组，且不会报错
> 
> ### 实际结果
> 绑定的v-model为false或为空的情况下报错，无法上传文件
> 
> ### 框架版本
> _No response_
> 
> ### 浏览器版本
> _No response_
> 
> ### 系统版本
> _No response_
> 
> ### Node版本
> _No response_
> 
> ### 补充说明
> _No response_
![image](https://user-images.githubusercontent.com/49055470/222881875-715d3edf-c51a-4c63-87aa-d22e64ef9462.png)

![image](https://user-images.githubusercontent.com/49055470/222881879-36b85e4c-8c7e-45b2-9ec3-263b3f07af45.png)

**Comment by chaishi** [comment]
请参考文档中数据类型要求，不支持 boolean，以后也不会支持

请更为使用 []

**Comment by bubai1125** [comment]
> 请参考文档中数据类型要求，不支持 boolean，以后也不会支持
> 
> 请更为使用 []

当前在开发类似低代码框架中遇到的问题，例如我设置t-form的提交的是值是postdata，文件上传设置的v-model=“postdata.files”，我在created中设置了this.postdata.files = [];  确实是成功不回报错的，但是这样我每次都要进行设置，且与其他组件并不一致，其他form的组件默认false都是可以的，唯一这个组件不行。 开发上会让人

**Comment by chaishi** [comment]
那就是低代码框架使用不当，本身就是不同的组件会有不同的默认值。即使是多选的 Select，日期范围也都是要求默认值 `[]`，不可能是 false。按照我的理解，写一个组件的 Map 映射关系就可以解决问题。

开发上弄不清楚，多写几次就清楚了。

简而言之，组件本身暂时不会去适应奇怪的不符合要求的数据类型。
