### ISSUE TITLE
[Cascader] 返回值包含父节点

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#2519]
### 这个功能解决了什么问题

tdesign版本号：1.1.1

value-mode="all"  multiple  只有选中全部子节点，父节点才会出现在返回值里，能否选中部分子节点返回值里就包含父节点的值。
value-type="full"   返回的是二维数组，数据结构比较复杂，能否就一维数组

### 你建议的方案是什么

value-mode可以新增一个值，当选中部分子节点，也返回父节点
或者像Tree组件一样，提供一些组件方法(getParents)可自定义操作

**Comment by PengYYYYY** [comment]
valueType="full" 就是输出的二维数组，value-mode="all" 的意思是会把它的全部节点返回来，如果选中部分子节点，父节点不是选中项目。如果你要拿全路径的话，你可以在返回值的 `node` 里面，使用 `node.getParent()` 拿到，`cascader` 是基于 `tree` 封装的。

**Comment by lin-code-world** [comment]
> valueType="full" 就是输出的二维数组，value-mode="all" 的意思是会把它的全部节点返回来，如果选中部分子节点，父节点不是选中项目。如果你要拿全路径的话，你可以在返回值的 `node` 里面，使用 `node.getParent()` 拿到，`cascader` 是基于 `tree` 封装的。

`node.getParent()`这个具体怎么使用？cascader文档里没有写实例方法，value返回的也是String|Number，怎么获取node对象？
