### ISSUE TITLE
抽屉[Drawer]内容部分样式可改不

### ISSUE THREAD

**Issue by williambao** [Tencent/tdesign-vue-next#252]
如题， 抽屉[Drawer]现在内容区域一直是灰色。
这块可以变为正常颜色吗？ 弹出内容有时候是表单编辑，变成灰色很奇怪了。
或者可以修改默认颜色也行。

**Comment by pengYYYYY** [comment]
![image](https://user-images.githubusercontent.com/35833812/150662537-cd004e55-3a99-4bc1-96e7-189fd5965115.png)

**Comment by pengYYYYY** [comment]
是白色呀

**Comment by williambao** [comment]
@pengYYYYY 这个我描述没清楚。 不是背景颜色， 是文字颜色。
默认文字是灰色的
![CleanShot 2022-01-26 at 18 28 52@2x](https://user-images.githubusercontent.com/779521/151147235-0bbade8d-a0cf-45ed-bca1-45d25292721d.png)
。
