### ISSUE TITLE
[Upload] auto-upload为false时，上传失败导致异常清空文件

### ISSUE THREAD

**Issue by hkaikai** [Tencent/tdesign-vue-next#2523]
### tdesign-vue-next 版本

1.1.1

### 重现链接

https://stackblitz.com/edit/angular-ek56yp?file=src%2Fdemo.vue

### 重现步骤

1、点击第一个上传组件，选择任意一个文件
2、点击上传，此时会异常清空已选择的文件

**Comment by PengYYYYY** [comment]
这个表现是正常的，第一步只是选择这个文件。上传过程中出现错误，组件内自动清空掉，很合理呀。issue 暂时关闭
