### ISSUE TITLE
[t-head-menu] 描述问题：t-menu-item上的@click方法不能触发

### ISSUE THREAD

**Issue by wuxianlijiang** [Tencent/tdesign-vue-next#2524]
### tdesign-vue-next 版本

1.1.1

### 重现步骤

`	<t-layout>
		<t-header style="height:128px;">
			<div class="box">
				<t-head-menu :default-expanded="expanded2" default-value="1-1" theme="dark" style="margin-top: 0px">
					<template #logo>
						<img height="28" src="https://tdesign.gtimg.com/site/baseLogo-dark.png" alt="logo" />
					</template>
					<t-submenu value="1">
						<template #title>
							<span>菜单1</span>
						</template>
						<t-menu-item value="1-1" @click="mytest('string')">子菜单1-1</t-menu-item>
						<t-menu-item value="1-2">子菜单1-2</t-menu-item>
						<t-menu-item value="1-3">子菜单1-3</t-menu-item>
					</t-submenu>`

### 期望结果

我希望t-menu-item 上的点击能触发data()中的方法，但它并没有。请问是我写错了吗？应该怎么做？谢谢！

### 实际结果

无效

**Comment by wuxianlijiang** [comment]
我是用[TDesign Starter](https://tdesign.tencent.com/starter/)  初始化的项目。直接在App.vue中写的代码

**Comment by PengYYYYY** [comment]
好的

**Comment by PengYYYYY** [comment]
https://stackblitz.com/edit/angular-z1xcpk?file=package.json,src%2Fdemo.vue

**Comment by PengYYYYY** [comment]
看看这个示例
