### ISSUE TITLE
[DateRangePicker ] 在 "YYYY-MM-DD HH:mm" 格式下选择时间不生效

### ISSUE THREAD

**Issue by foreverDawns** [Tencent/tdesign-vue-next#2527]
### tdesign-vue-next 版本

1.1.1

### 重现链接

https://stackblitz.com/edit/angular-3diqyp?file=package.json,src%2Fdemo.vue

### 重现步骤

<t-date-range-picker
      enable-time-picker
      allow-input
      clearable
      @pick="onPick"
      @change="onChange"
      **format="YYYY-MM-DD HH:mm"**
    />
![image](https://user-images.githubusercontent.com/29656271/223604465-be4e6f7f-1248-406f-84db-5a912d7a260c.png)

### 期望结果

可以选择时间

### 系统版本

win10

**Comment by Ericleungs** [comment]
您好大佬们，我发现这个bug是源于src/_common/js/date-picker/format.ts中，关于日期格式的更改，本来是在这个时候commit了，但是没法push，显示权限拒绝，最后发现这个好像是在另外一个库(tdesign-common)，我需要在这个common的库里面提交吗

**Comment by Ericleungs** [comment]
啊有大佬已经提交了，就是这里的RP，时间格式修改 [fix: 修复时间格式化问题](https://github.com/Tencent/tdesign-common/pull/1194)，修改的思路大致相同

**Comment by uyarn** [comment]
> fix: 修复时间格式化问题

@Ericleungs 谢谢你 刚好早上的时候讨论了一下修复了 你也可以留意其他issue参与贡献
