### ISSUE TITLE
[Upload] 批量上传文件时selectChange不生效

### ISSUE THREAD

**Issue by as953060314** [Tencent/tdesign-vue-next#2531]
我在demo里面的文件批量上传组件里添加@select-change="handleSelectChange"后，发现该函数根本没生效，没有日志输出，请问是批量上传的时候不支持这个事件吗
      <t-upload
        action="xxxxxx"
        placeholder="支持批量上传文件，限文本文件且单个文件大小在3M以内"
        theme="file-flow"
        multiple
        :is-batch-upload="true"
        :data="uploadFileData"
        :auto-upload="false"
        :sizeLimit="{ size: 3, unit: 'MB', message: '文件大小不能超过3MB' }"
        @success="onUploadFileSuccess"
        @select-change="handleSelectChange"
      >

**Comment by yanxugong** [comment]
可否上传更完整的代码，便于判断是否为组件 selectChange 事件不生效的问题。

**Comment by yanxugong** [comment]
<img width="2040" alt="企业微信截图_f49dfc5a-4f4e-4fd9-8d59-b3d1306c9604" src="https://user-images.githubusercontent.com/35914225/227706867-a082332d-00f2-4e92-b14e-cdb56f346133.png">


示例：https://stackblitz.com/edit/angular-sofh5v?file=package.json,src%2Fdemo.vue
