### ISSUE TITLE
[Tag]和[Link]等组件颜色自定义问题

### ISSUE THREAD

**Issue by IainZhuo** [Tencent/tdesign-vue-next#2534]
### 这个功能解决了什么问题

某些组件颜色只能通过风格属性的几个固定值来修改。

### 你建议的方案是什么

希望能新增自定义颜色的属性

**Comment by btea** [comment]
这种颜色修改或许自己用样式来覆盖更好。

**Comment by PengYYYYY** [comment]
自行覆盖吧
