### ISSUE TITLE
[Popup] placement不变时 reference位置接近/重叠 popup没有正常update

### ISSUE THREAD

**Issue by Wesleyyy0808** [Tencent/tdesign-vue-next#2536]
### tdesign-vue-next 版本

1.1.1

### 重现步骤

【Guide】
【原代码】：
    <div class="menu">
        <t-menu>
            <t-menu-item value="0" class="changepws">
                <template #icon>
                    <icon name="edit" size="218px" />
                </template>
                修改密码
            </t-menu-item>
            <t-menu-item value="1" class="moreinfo">
                <template #icon>
                    <icon name="layers" size="218px" />
                </template>
                更多信息
            </t-menu-item>
            <t-menu-item value="2"  class="clogout">
                <template #icon>
                    <icon name="login" size="218px" />
                </template>
                退出登陆
            </t-menu-item>
        </t-menu>
    </div>
【Guide配置】（仅出示部分代码）：
<t-guide v-model="current" :steps="steps" @change="handleChange" @finish="handleFinish" :hideSkip="true" />
const steps = [
    {
        element: '.guide_more',
        title: '新手引导',
        body: '这是更多，点击它会弹出更多选项',
        placement: 'bottom-right',
    },
    {
        element: '.changepws',
        title: '新手引导',
        body: '点击这里可以修改密码',
        placement: 'right',
    },
    {
        element: '.moreinfo',
        title: '新手引导',
        body: '点击这里显示更多信息',
        placement: 'right',
    },
    {
        element: '.clogout',
        title: '新手引导',
        body: '点击这里退出登录',
        placement: 'right',
    },
    {
        element: '.guide_refresh',
        title: '新手引导',
        body: '新手引导的说明文案',
        placement: 'right',
    },
    {
        element: '.guide_darktoggle',
        title: '新手引导',
        body: '新手引导的说明文案',
        placement: 'bottom',
    },
];

### 期望结果

guide-tooltip框应该定位到每个element上

### 实际结果

placement相同时guide-tooltip只会定位到第一个element（如上述代码：bottom-right切换到下一个为right时定位到了这个right的element，当继续点击下一步时，tooltip不会改变位置，仍然保持在第一个element的位置，但是高亮区域有改变！反之，在最后一个placement为bottom点击上一步，tooltip会跳转到上一个标签，继续点击上一步，仍然停留在第一次的位置）
【补充】已在项目进行复现，重装库未能解决问题。
【怀疑】placement相同前提下 x 轴或y 轴未变化，不会触发改变位置

### 框架版本

Vue 3.2.0

### 系统版本

Win10 19041.208

### Node版本

18.0.0

### 补充说明

![ea214ad446e26c82483bd84547ac594](https://user-images.githubusercontent.com/69622989/224376891-4c6ab223-70a5-4a4e-ad73-62e69b0369cb.png)
![ba725a6ed136ae4a915a47571e20d25](https://user-images.githubusercontent.com/69622989/224376912-5eab18ea-02f5-46a0-a818-11b336f92cc4.png)

**Comment by iPv4-Randomseven** [comment]
补充动图：
![IMG_0441](https://user-images.githubusercontent.com/69622989/224454724-915433ec-3126-4323-b4c7-068e3c66da17.GIF)

**Comment by iPv4-Randomseven** [comment]
【补充问题】
能不能加一个API：点击下一步/上一步的 延时操作。
因为有需求是：
点击下一步后element运动出现，导致element还没到结束位置 guide的高亮区和tooltip框就定位了
目前我使用的方法是：
先让element运动出现后再改变current值，这个方法可以但是还是没有定位到，看上面的gif能看出来 第一次到修改密码区域的时候是没有完全定位到的，但是如果增加timeout的时间就会显得卡顿，有0.5秒tooltip和高亮区是没动的，如果用户再次按下一步就会直接跳转到下下一步。
请告诉我上述是否会加入计划当中，如果没有再另想这种需求的解决方案！感谢

**Comment by zhangpaopao0609** [comment]
感谢同学提的 issue  @iPv4-Randomseven 
1. 关于第一个问题：问题收到，但我无法复现，可以辛苦在 stackblitz 中提供一个复现 demo 吗？感谢
2. 关于第二个问题：我个人觉得是可以支持的，不过咱不能决定哈，这个我们讨论一下尽快给到同学回复

**Comment by iPv4-Randomseven** [comment]
收到，我会尽快提供复现demo
另外第二个问题我再具体描述一下：
点击下一步后按照API延时设置，暂不切换下一个选项，但触发Change，或许可以再Change里加一个参数，表明该操作是由什么引起的 如：timeout为延时未切换下一个选项而触发的，xxx为切换为下一项而触发的change。

**Comment by iPv4-Randomseven** [comment]
可以复现的代码：https://stackblitz.com/edit/angular-ohj8bz?file=src/demo.vue
目前好像是ul里的会出现这个问题

**Comment by iPv4-Randomseven** [comment]
@zhangpaopao0609 请查看上述代码是否能复现并确认具体问题！感谢

**Comment by zhangpaopao0609** [comment]
感谢，能够看到复现的情形，正在处理中哈；第二个问题也在讨论中，今明两天进行处理哈
