### ISSUE TITLE
[Table] 排序功能异常

### ISSUE THREAD

**Issue by jieyuming** [Tencent/tdesign-vue-next#2538]
### tdesign-vue-next 版本

1.1.1

### 重现步骤

我是使用webpack5构建的vue3项目，表格组件表头使用排序功能，会提示错误 _this2.getSortIcon is not a function，不开启排序功能表格就能正常渲染，错误图片如下：
![image](https://user-images.githubusercontent.com/21232961/224471049-b48b6c45-e64d-4602-967b-8f0c0001aaf2.png)

代码图片如下:
![image](https://user-images.githubusercontent.com/21232961/224471077-f6f0f6bb-e360-4824-99cf-61700ae20165.png)

### 期望结果

希望官方可以修复这个问题，能让排序功能正常使用，我之前反馈过一个问题，技术大佬们再问题#2375中修复了，尝试将 renderTd 相关函数移动到 setup解决了该问题，很高兴反馈的速度

**Comment by PengYYYYY** [comment]
请问vue-loader 是什么版本的

**Comment by jieyuming** [comment]
你好，是17.0.0版本




&nbsp;


1406821473
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月12日(星期天) 晚上11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tdesign-vue-next] [Table] 排序功能异常 (Issue #2538)





 
请问vue-loader 是什么版本的

**Comment by chaishi** [comment]
初步估计是 `getSortIcon` 放在了 `methods` 中的原因，我调整一下试试看

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2592
