### ISSUE TITLE
代码不提示

### ISSUE THREAD

**Issue by hexu2016** [Tencent/tdesign-vue-next#2539]
### 这个功能解决了什么问题

![image](https://user-images.githubusercontent.com/16769239/224476659-1d3ed91d-aea3-4138-8bd9-1e8ca463caaf.png)
有的组件能识别到能提示，但是像t-table识别不了，代码无法提示

### 你建议的方案是什么

需要装什么插件吗？

**Comment by Aicmortal** [comment]
tsconfig看看

**Comment by hexu2016** [comment]
> tsconfig看看

![image](https://user-images.githubusercontent.com/16769239/224489015-efb427a7-12a6-4386-bc67-2b73add3a403.png)
没改过这个。

**Comment by hexu2016** [comment]
> @hexu2016 你先尝试一下下面两种方式:
> 2. 或者在`tsconfig`中的`types`添加`"tdesign-vue-next/global"`,删掉`include`中的`node_modules/tdesign-vue-next/global.d.ts`:
>    ![code2](https://user-images.githubusercontent.com/16420004/224490292-3e28e32f-eaca-49c5-a9ed-0c9c7b5cdaff.png)

试过了，还是不行.很多组件都正常，就是table识别不到

**Comment by uyarn** [comment]
只有table?

**Comment by hexu2016** [comment]
> 只有table?

还有t-icon,t-radio-button,

**Comment by hexu2016** [comment]
![image](https://user-images.githubusercontent.com/16769239/224536304-719dab5d-37c1-4cf0-80ba-4e0892323b55.png)
idea可以提示这个,为什么vscode不行呢
![image](https://user-images.githubusercontent.com/16769239/224536327-ab5900ef-4154-4bb7-9644-a6605e22ea3e.png)

**Comment by Nakus0426** [comment]
可以试下把`unplugin-vue-components`和`unplugin-auto-import`都用上

**Comment by PengYYYYY** [comment]
确认一下 `volar` 是否有安装

**Comment by uyarn** [comment]
<img width="670" alt="image" src="https://user-images.githubusercontent.com/26377630/224941863-6016ad71-86b9-48b4-a565-300f968c96fe.png">
<img width="730" alt="image" src="https://user-images.githubusercontent.com/26377630/224942036-1f0684fd-1efb-40a6-89e7-2cd332900683.png">
特地重新起了个项目看起来没什么问题..
