### ISSUE TITLE
[Bug][0.7.0版本] 动态组件<component :is="someCondition ? Foo : Bar" />失效

### ISSUE THREAD

**Issue by ceword** [Tencent/tdesign-vue-next#254]
### 环境
浏览器：Microsoft Edge Version 97.0.1072.69 (Official build) (64-bit)
"@vueup/vue-quill": "^1.0.0-beta.7",
"axios": "^0.24.0",
"tdesign-vue-next": "0.7.0",
"vue": "^3.2.25",
 "vue-router": "^4.0.12",
 "vuex": "^4.0.2"

### 描述

我在使用0.7.0版本时，在 <script setup> 语法糖中使用的 动态组件 `<component :is="" />` 直接失去动态效果
自己属于刚入门小白，不太明确具体排查具体问题原因，是否是我的写法有问题？
但可以明确的是，我是一路用着升级上来的，在0.6.4以下都能正常使用。
我切换回0.6.4版本以后，动态组件的切换效果又正常了

### 附上出问题代码

```
<template>
    <component :is="current ? current : config" />
</template>
<script setup lang='ts'>
import { ref, watch, markRaw } from 'vue';

import config from "./config/index.vue"
import tree from "./tree/index.vue"
import article from "./article/index.vue"

const current = ref('null');
const componentList: any = {
    config,
    tree,
    article
}
watch(store.state.uri, (newValue) => {
    current.value = markRaw(componentList[newValue.mod])
})
</script>
```

**Comment by ceword** [comment]
我使用的是全局引入，这个动态组件所在的文件，以及componentList中的3个组件中，都有使用到了tdesign-vue-next的组件

**Comment by pengYYYYY** [comment]
收到

**Comment by pengYYYYY** [comment]
你需要把组件import 进来

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/components/result/index.vue 可以参考这边

**Comment by ceword** [comment]
> 你需要把组件import 进来
组件都import的
```
import config from "./config/index.vue"
import tree from "./tree/index.vue"
import article from "./article/index.vue"
```
这3个就是我引入的组件。

是不是在0.7.0和vue3.2+版本冲突，不能用<script setup>语法糖
我测试了好几次，只要切换0.7.0就不行，以前的版本都是正常。

**Comment by ceword** [comment]
> https://github.com/Tencent/tdesign-vue-next-starter/blob/develop/src/components/result/index.vue 可以参考这边

我已经参考这个方法重新写了一次，依旧是0.7.0版本，动态组件直接无动态效果，但是0.6.4就没问题。
我的vue版本: 3.2.25
@pengYYYYY

**Comment by ceword** [comment]
哎，最后发现是t-content的问题，不是我写的问题。。。。

**Comment by ceword** [comment]
在t-content里，动态组件只获取到了一次props，后面父组件所有props更新，子组件都获取不到
