### ISSUE TITLE
[t-textarea] 设置`maxlength`属性导致大小不可调

### ISSUE THREAD

**Issue by hhucqian** [Tencent/tdesign-vue-next#2540]
### tdesign-vue-next 版本

1.1.1

### 重现步骤

```  
<t-textarea  v-model="value"  :maxlength="20" ></t-textarea>
```

当设置了`maxlength`属性后，textarea就变成了大小不可调的了，我看了下源码：

https://github.com/Tencent/tdesign-vue-next/blob/ef6b38761a854c02899b72b2c60c2c349b13c4ec/src/textarea/textarea.tsx#L222

设置maxlength确实会让textarea变成大小不可变，这是专门这么设计的吗？

### 期望结果

设置maxlength属性不设置`resize: none;`样式

**Comment by chaishi** [comment]
不是设计如此，我来删一下
