### ISSUE TITLE
[t-menu] 不能自动展开到当前菜单项

### ISSUE THREAD

**Issue by hhucqian** [Tencent/tdesign-vue-next#2541]
### tdesign-vue-next 版本

1.1.1

### 重现链接

https://tdesign.tencent.com/starter/vue-next/dashboard/base

### 重现步骤

点击右上角"Tencent"->"个人中心" 进入个人中心页，左侧菜单只高亮了“个人页“一级菜单，没有自动展开子菜单。

### 期望结果

希望能够支持自动展开当前子菜单功能。

**Comment by uyarn** [comment]
这是因为页面模板里的菜单是非受控的配置 
<img width="887" alt="image" src="https://user-images.githubusercontent.com/26377630/224594172-42906bc6-d89f-4bea-9f87-cdeee6e3e546.png">
点击右上角没有触发内部逻辑的变化 有这个需要把defaultExpand改成expand，并自己维护它的状态就可以了
