### ISSUE TITLE
[tree] 延迟加载 children 为 true 的节点的子节点数据，建议将children改为其他值

### ISSUE THREAD

**Issue by wou101771** [Tencent/tdesign-vue-next#2542]
### 这个功能解决了什么问题

在业务场景中，经常会遇到动态加载树的回显问题，因为子节点数据还未加载出来，所以需要手动构建一条数据传入其中，来显示label。但是你们的ui使用了children来判断是否加载，所以当手动构建数据后，children不再为true，没办法用此项方法实现该功能。

### 你建议的方案是什么

可以参考element plus的方式使用isLeaf值来判断，children只当做子节点的数据集。

**Comment by PengYYYYY** [comment]
手动构建数据后，`children` 不再为 `true` 时，这个表现是正常的，手动构建好数据，加载的就是你的数据。`children` 为 `true` 时再加载下一级。不太明白会给你的业务造成什么影响

**Comment by wou101771** [comment]
> 手动构建数据后，`children` 不再为 `true` 时，这个表现是正常的，手动构建好数据，加载的就是你的数据。`children` 为 `true` 时再加载下一级。不太明白会给你的业务造成什么影响。API 也是设计如此哈

当修改表单的时候，传递id给tree，因为子数据还未加载出来，通过手动构建数据的方法，将数据传递到数组中，只是为了回显有label，但是此时children的值不再是true了，但是需要点击展开的时候任然能正常加载子数据。你们的设计能满足这个功能么？
