### ISSUE TITLE
[Upload] 支持设置 input 属性

### ISSUE THREAD

**Issue by gismanli** [Tencent/tdesign-vue-next#2543]
### 这个功能解决了什么问题

upload组件目前不支持设置input[type=file]的属性，譬如我要设置选择文件夹功能，需设置`webkitdirectory`属性，目前参数被设置在了外层div上。

<img width="746" alt="image" src="https://user-images.githubusercontent.com/8967577/224638493-629130f1-09fb-4ad3-abcd-6f5ff903522b.png">

### 你建议的方案是什么

希望upload组件支持`input[type=file]`参数，以实现更多功能。

**Comment by chaishi** [comment]
OK，应该支持

**Comment by yanxugong** [comment]
认领该任务，2天内提交

**Comment by yanxugong** [comment]
resolved in #2554
