### ISSUE TITLE
[table] dialog内嵌table，通过class="myClass"配置max-height: 500px; 会作用到整个 dialog 而不是表格

### ISSUE THREAD

**Issue by easylu** [Tencent/tdesign-vue-next#2546]
### tdesign-vue-next 版本

1.0.2

### 重现链接

https://stackblitz.com/edit/angular-nfdy2h?file=src/demo.vue

### 重现步骤

1、dialog组件中嵌入 table 组件，然后期望控制 table 的 height 出现滚动条
2、通过 table 组件自带的 max-height 设置可以正确生效
3、通过给 table 指定 class，然后在 class 中定义 max-height，发现滚动条突破了 table，对整个 dialog 内生效了

### 期望结果

滚动条只对 table 生效

### 实际结果

滚动条对整个 dialog 生效了
![image](https://user-images.githubusercontent.com/5466705/224684873-d6dd733f-706c-4dfb-8fc0-955bb244433a.png)

**Comment by chaishi** [comment]
如果是希望设置表格的高度，请根据文档设置 `maxHeight` 属性。类名的作用元素完全不同。
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/11605702/224685950-65eaacb4-db7a-4ab8-8621-05dc341a2f10.png">
