### ISSUE TITLE
[t-menu] 设置expanded属性后，无法展开新的子菜单

### ISSUE THREAD

**Issue by hhucqian** [Tencent/tdesign-vue-next#2548]
### tdesign-vue-next 版本

1.1.1

### 重现步骤

接这个问题： #2541
如果使用expand，会让没有展开的菜单项无法点击展开，仿佛整个目录树被锁死了一样。

**Comment by Aicmortal** [comment]
你绑定expand用的v-bind还是v-model?
如果是`:expand="xxx"`,请改为`v-model:expanded="xxx"`的方式试试

**Comment by uyarn** [comment]
不好意思 在#2541 里面没说清楚 如果用expand 就要配合onExpand的事件来控制 做到完全受控 defaultExpand相当于让menu自己控制展开收起了 expand需要你自己控制 在onExpand里持续更新expand的数组。或者像楼上说的双向绑定 然后在点击右上角的操作里再手动更新下双向绑定的值也可以

**Comment by PengYYYYY** [comment]
v-model:expanded="xxx" 是双向绑定，:expanded="XX" 是需要自己去处理这个值的，: defaultExpand ="XX" 内部只处理你这个默认值
