### ISSUE TITLE
[Tag]标签选中时，字体颜色不正确

### ISSUE THREAD

**Issue by wendzhao** [Tencent/tdesign-vue-next#2552]
### 重现链接
https://stackblitz.com/edit/angular-7k6eg3?file=src%2Fdemo.vue

### 重现步骤
在CheckTag 中增加使用badge显示该标签对应的子模块数量，字体选中后不会变成白色

### 期望结果
tag选中后，字体能正常变成白色（如官方的示例）
![image](https://user-images.githubusercontent.com/8084493/224922585-c211549f-66fe-438b-acc8-043722dc87f7.png)

### 实际结果
字体颜色黑色，不会变化
![image](https://user-images.githubusercontent.com/8084493/224922035-50e10fc6-ee39-4420-b2d4-289fc36a89a9.png)

| Environment | Info |
|---|---|
| 相关版本 | 1.1.1 |
| 框架版本 / 基础库版本 | Vue(3.2.47) |
| 系统、浏览器 | Chrome(103) |
| Node版本 |  |

**Comment by ccccpj** [comment]
https://stackblitz.com/edit/jdadva?file=src%2Fmain.js,src%2Fdemo.vue

应使用 badge 嵌套 tag
