### ISSUE TITLE
[switch] table中的switch组件@change传递的数据无法正确同步

### ISSUE THREAD

**Issue by tengfeiyu** [Tencent/tdesign-vue-next#2566]
### tdesign-vue-next 版本

table中的switch组件@change传递的数据无法正确同步

### 重现链接

https://stackblitz.com/edit/angular-tyxgzq?file=package.json,src%2Fdemo.vue

### 重现步骤

操作表格中的 switch 组件，首次能够正确切换状态，但是再第一次之后在操作，switch 组件 @change 传递的数据就无法正确同步表格中的数据。

### 期望结果

switch 组件 @change 传递的数据能够正确同步表格中的数据。

### 实际结果

switch 组件 @change 传递的数据就无法正确同步表格中的数据。

### 框架版本

Vue(^3.2.31)

### 浏览器版本

Microsoft Edge 版本 110.0.1587.69 (正式版本) (64 位)

### 系统版本

window 10

### Node版本

16.17.0

### 补充说明

不知道是switch的原因还是table的原因还是二者混用的问题，请排查后告知。
框架版本："tdesign-vue-next": "~1.1.1"

**Comment by PengYYYYY** [comment]
https://stackblitz.com/edit/angular-g4jzrr?file=package.json,src%2Fdemo.vue

**Comment by PengYYYYY** [comment]
看下这例子，应该是你编码的问题，现在你的用法是 `switch` 的受控用法，组件的表现由你传入的数据决定。和组件混用无关，排查一下你拉取的数据。`issue` 关闭

**Comment by tengfeiyu** [comment]
@PengYYYYY 例子中 第一次操作后，再获取最新的数据，unlocked 计算结果是 false，组件状态是对的与页面展示 选中状态展示的的一样，但是通过change(scope.row, scope.row.unlocked) 函数传递进来的是 unlocked 都是 true。而不应该等同于外部表格上展示的scope.row.unlocked吗？

**Comment by tengfeiyu** [comment]
@PengYYYYY 你给的例子中，如果将 `@change` 替换成  `@click` 事件，结果就是正常的。我还是不理解，你说的编码错误出在哪里，感谢指出。

**Comment by tengfeiyu** [comment]
另一个项目在早之前使用的是 "tdesign-vue": "~0.41.3" 版本，同样编码就不存在此问题。
