### ISSUE TITLE
[comment] actions多出按钮

### ISSUE THREAD

**Issue by rexlily** [Tencent/tdesign-vue-next#2577]
### tdesign-vue-next 版本

1.2.0

### 重现链接

https://stackblitz.com/edit/angular-6nlijm?file=package-lock.json,src%2Fdemo.vue

### 重现步骤

<template>
  <t-list :split="true">
    <t-list-item v-for="(item, index) in commentsData" :key="index">
      <template #content>
        <t-comment
          :avatar="item.avatar"
          :author="item.author"
          :datetime="item.datetime"
          :content="item.content"
        >
          <template #actions>
            <span key="thumbUp" :size="6">
              <t-icon name="thumb-up" />
              <span>6</span>
            </span>
            <span v-if="false">
              <t-icon name="chat" />
              <span>回复</span>
            </span>
          </template>
        </t-comment>
      </template>
    </t-list-item>
  </t-list>
</template>

<script setup>
const commentsData = [
  {
    id: 'A',
    avatar: 'https://tdesign.gtimg.com/site/avatar.jpg',
    author: '评论作者名A',
    datetime: '今天16:38',
    content: '评论作者名A写的评论内容。',
  },
  {
    id: 'B',
    avatar: 'https://tdesign.gtimg.com/site/avatar.jpg',
    author: '评论作者名B',
    datetime: '今天16:38',
    content: '评论作者名B写的评论内容。',
  },
  {
    id: 'C',
    avatar: 'https://tdesign.gtimg.com/site/avatar.jpg',
    author: '评论作者名C',
    datetime: '今天16:38',
    content: '评论作者名C写的评论内容。',
  },
];
</script>
[](url)

### 期望结果

正常显示action的按钮

### 实际结果

<img width="601" alt="image" src="https://user-images.githubusercontent.com/31459705/225820982-281a8173-d4b1-440e-9a69-a7e13f1c216a.png">

**Comment by rexlily** [comment]
<img width="319" alt="image" src="https://user-images.githubusercontent.com/31459705/225821870-22bdf1b0-e95e-4210-a5c5-e870f63913bf.png">
<img width="397" alt="image" src="https://user-images.githubusercontent.com/31459705/225821974-14d6fe03-8abe-4bae-9b60-9ed9b7d95356.png">
只有删掉代码才不会出现，注释掉也有

**Comment by uyarn** [comment]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/26377630/228410505-a19ea605-42b8-47d4-a517-e35af23ae7ca.png">
没有复现你说的问题
https://stackblitz.com/edit/angular-6nlijm-7wmfdq?file=package-lock.json,src%2Fdemo.vue
