### ISSUE TITLE
[switch] table中的switch组件@change传递的数据无法正确同步

### ISSUE THREAD

**Issue by tengfeiyu** [Tencent/tdesign-vue-next#2579]
### tdesign-vue-next 版本

1.2.0

### 重现链接

https://stackblitz.com/edit/angular-tyxgzq-ffs1qx?file=package.json,src%2Fdemo.vue

### 重现步骤

操作表格中的 switch 组件，首次能够正确切换状态，但是再第一次之后在操作，switch 组件 https://github.com/change 传递的数据就无法正确同步表格中的数据。
新补充的复现链接中，click 事件可以正常操作。
另外在 enhanced-table 中通过实例设置更新后的数据，change 事件可以正常操作。

### 期望结果

switch 组件 https://github.com/change 传递的数据能够正确同步表格中的数据。

### 实际结果

switch 组件 https://github.com/change 传递的数据就无法正确同步表格中的数据。

### 框架版本

3.2.40

### 浏览器版本

Microsoft Edge 版本 110.0.1587.69 (正式版本) (64 位)

### 系统版本

window 10

### Node版本

16.17.0

### 补充说明

关联上一个提出的问题 #2566 ，莫名就给关闭了。
同样的编码先前使用 "tdesign-vue": "~0.41.3" 版本，"vue": "^2.6.11"，就不存在此问题。还请排查，虽然已有规避的方式。

**Comment by yanxugong** [comment]
参考 Switch 组件 change 事件的用法。回调函数会读取当前的开关状态。

![Switch 开关示例](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/3eadb654b2d64322bd5dd6a380adc260~tplv-k3u1fbpfcp-watermark.image?)

对于 Switch 组件用法建议作出一下修改：

```diff
<template>
  <!-- 表格 -->
  <t-table :columns="columns" :data="data" row-key="id" hover>
    <template #locked="scope">
      <!-- change 事件的数据无法正确同步 -->
      无法正常操作的
      <t-switch
        :value="scope.row.unLocked"
        :label="['正常', '锁定']"
        :loading="toggleLocked[scope.row.id]"
-       @change="handleRowLockedChange(scope.row, scope.row.unLocked)"
+       @change="(e) => handleRowLockedChange(e, scope.row)"
      />
      选中状态 {{ scope.row.unLocked }}
      <!-- click 事件的数据就可以正确同步 -->
-    <t-switch
-       :value="scope.row.unLocked"
-       :label="['正常', '锁定']"
-      :loading="toggleLocked[scope.row.id]"
-       @click="handleRowLockedChange(scope.row, scope.row.unLocked)"
-     />
      使用click事件代替的，正常操作
    </template>
  </t-table>

  ...

</template>

<script setup lang="ts">
...

// operations methods
- const handleRowLockedChange = async (row: any, passed: boolean) => {
+ const handleRowLockedChange = async (e: any, row: any) => {
  console.log('操作传递数据', row);
- console.log('操作传递状态', passed);
  // ### 此处获取的数据状态在第一次操作成功后，刷新列表再次操作之后就一直无法正确获取
  // ### 取而代之的用button方式，不存在此问题
  toggleLocked.value = {
    ...toggleLocked.value,
    [row.id]: true,
  };
  const matchedRow: any = listData.find((item) => item.id === row.id) || {};
  try {
-   if (row.unLocked) {
+   if (!e) {
      matchedRow.locked = 1;
    } else {
      matchedRow.locked = 0;
    }
    handleTableQuery();
  } finally {
    toggleLocked.value = {
      ...toggleLocked.value,
      [row.id]: false,
    };
  }
};

...

```

具体实例参考这里：'https://stackblitz.com/edit/angular-8g9f3u?file=package.json,src%2Fdemo.vue'
