### ISSUE TITLE
[Dropdown] 控制台报错

### ISSUE THREAD

**Issue by ChenceGu** [Tencent/tdesign-vue-next#2586]
### tdesign-vue-next 版本

1.2.0

### 重现链接

https://tdesign.tencent.com/vue-next/components/dropdown?tab=demo

### 重现步骤

点击网站demo中的下拉菜单报错TypeError: Cannot read properties of undefined (reading 'on-visible-change')

**Comment by uyarn** [comment]
fixed, please upgrade to 1.2.1
