### ISSUE TITLE
[unplugin-auto-import] 自动引入依赖的unplugin插件，webpack依赖问题

### ISSUE THREAD

**Issue by sershine** [Tencent/tdesign-vue-next#2591]
### tdesign-vue-next 版本

1.2.1

### 重现步骤

按官网方式npm install -D unplugin-vue-components unplugin-auto-import 添加2个按需引入的插件
因为项目是使用的vite构建，所以没有webpack
在npm run build的时候，会在node_modules/unplugin/dist/index.d.ts 文件里报import { Compiler, WebpackPluginInstance } from 'webpack'错误的问题

### 期望结果

经测试，可以使用tsconfig里的skipLibCheck:true的方式忽略掉
但是感觉这么做，不太正经
有没有其他方式去解决这个报错的问题

### 框架版本

3.2.47

### 浏览器版本

Edge 111.0.1661.44

### 系统版本

win11

### Node版本

16.17.0

**Comment by PengYYYYY** [comment]
看起来是下层依赖的问题，`td` 没有使用 `webpack`。

**Comment by PengYYYYY** [comment]
可以看下抛出问题的地方是哪个插件

**Comment by sershine** [comment]
unplugin-vue-components这个插件引用了unplugin这个插件
unplugin这个插件，兼容webpack、vite等构建工具
所以引用了webpack

**Comment by sershine** [comment]
`import { Compiler, WebpackPluginInstance } from 'webpack'`
`export { Compiler as WebpackCompiler } from 'webpack'`

`import { Compiler as Compiler$1, RspackPluginInstance } from '@rspack/core'`

这是unplugin这个插件引用的webpack和@repack/core
但是项目里没有这些

**Comment by sershine** [comment]
> 可以看下抛出问题的地方是哪个插件

**Comment by PengYYYYY** [comment]
也许可以去 `unplugin-auto-import` 提个 `issue`
