### ISSUE TITLE
[Bug][Slider] 更新绑定在value上的ref并不会更新滑块位置

### ISSUE THREAD

**Issue by backrunner** [Tencent/tdesign-vue-next#260]
### Environment

browser version: Chrome latest stable
tdesign-vue-next version: 0.6.4 / 0.7.0

### 问题

更新了滑动条绑定到value的ref之后，滑块位置并没有更新。
实测vue2版本没有这个问题。

codesandbox online demo:

[![Edit tdesign-vue-next-demo (forked)](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/tdesign-vue-next-demo-forked-hzme3?fontsize=14&hidenavigation=1&theme=dark)

**Comment by pengYYYYY** [comment]
0.8.0 版本已修复
