### ISSUE TITLE
[Table]  树形结构的表格不能分页

### ISSUE THREAD

**Issue by 3fun4** [Tencent/tdesign-vue-next#2607]
### tdesign-vue-next 版本

1.2.1

### 期望结果

像 t-table 一样支持分页

### 实际结果

使用 t-enhanced-table 即使配置了 pagination 也不分页

### 框架版本

Vue 3.2.38

### 浏览器版本

Microsoft Edge 106.0.1370.47

### 系统版本

Windows 10

### Node版本

16.18.0

**Comment by chaishi** [comment]
- 如果是远程数据分页（即 data.length = pageSize），应该是支持的。如果体验下来不支持，可能是用法问题，请在提供可复现问题的 demo 后 reopen 当前 issue，或者提新的 issue
- 本地数据分页（即 data.length > pageSize），不支持，以后也不会支持，组件无法决定从树形结构的哪一个父节点、中间节点、子节点进行分页，你可以自己根据业务实际需求分页


没有提供可复现问题的 Demo，无法处理问题，issue close
