### ISSUE TITLE
[RadioButton] IDE 代码提示问题

### ISSUE THREAD

**Issue by kenzyyang** [Tencent/tdesign-vue-next#2608]
### tdesign-vue-next 版本

可

### 重现步骤

<img width="563" alt="企业微信截图_d103eb7d-cd35-4b46-aee9-3c1ea6a99948" src="https://user-images.githubusercontent.com/27340803/227169916-219a2b6e-f27f-47d7-a08d-c8df171fa175.png">

### 期望结果

ide 能正确提示

### 实际结果

不能，ide 识别为未知 tag

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2613
