### ISSUE TITLE
[Table] 如何获取最大页数/跳转到最后一页

### ISSUE THREAD

**Issue by Wesleyyy0808** [Tencent/tdesign-vue-next#2612]
### 这个功能解决了什么问题

Pagination的pageSize可以动态更新当前页，但是table的pagination不能动态更新pageSize。

### 你建议的方案是什么

所以Table能否加API？向Pagination的pageSize一样
例如：
PageSize：当前分页，支持语法糖
onDataChange（或其他）：数据更新时触发，返回当前页数（PageSize）与最大页数（MaxPageSize）

### 我的需求
动态push数据到data最后，table跳转到最后一页（即新加数据的那一页）

**Comment by chaishi** [comment]
> table的pagination不能动态更新pageSize

我在官网尝试「远程数据分页」 和 「本地数据分页」 2 个 Demo，是完全可以动态更新分页大小的。
‼️重要：辛苦提供不能动态更新的示例代码。

**Comment by iPv4-Randomseven** [comment]
> > table的pagination不能动态更新pageSize
> 
> 我在官网尝试「远程数据分页」 和 「本地数据分页」 2 个 Demo，是完全可以动态更新分页大小的。 ‼️重要：辛苦提供不能动态更新的示例代码。
> 
> <img alt="image" width="869" src="https://user-images.githubusercontent.com/11605702/227177190-986dace7-54e9-4d24-986e-84cc533cbe40.png">

你好，是可以动态更新分页大小但是我的意思是table的api中没有参数是动态更新数据量（支持语法糖，就是Pagination的pageSize）

**Comment by iPv4-Randomseven** [comment]
以及我想知道如何获取Pagination的最后一页

**Comment by yixiaco** [comment]
t-table的pagination应该不是deep监听的，所以如果需要动态改变参数，需要在传入对象时就是一个代理对象。
其他组件类似这种情况
像这种情况是不能动态改变的：
```vue
<template>
  <t-table
        row-key="id"
        :data="data"
        :columns="columns"
        :pagination="{
          pageSize: pageSize,
        }"
      />
</template>
```
