### ISSUE TITLE
[Dialog] 无法重写Dialog相关的CSS

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#2615]
### tdesign-vue-next 版本

1.2.2

### 重现步骤

<img width="388" alt="image" src="https://user-images.githubusercontent.com/10460238/227419466-b9528368-d8ab-430a-9279-4fb55aef857e.png">
之前1.0.2版本都可以通过这个方式去重写dialog相关的css样式，大概1.0.9左右的版本就不行了，一直到现在1.2.2都不行，求帮忙看一下是哪些问题导致的？
类似的方式去重写table相关的样式也没问题的

### 期望结果

可以重写dialog相关的css样式

### 实际结果

重写dialog相关的css样式无效

**Comment by woshishade** [comment]
改了这种方式去实现样式穿透的话，会造成全局都会影响，:global就算放在`scope`里面还是没用

**Comment by woshishade** [comment]
@Aicmortal

**Comment by woshishade** [comment]
两种方案都会影响全局的样式，有没什么办法只影响局部样式呢？

**Comment by Aicmortal** [comment]
@woshishade 你可以给dialog加一个class,然后再用上面的方法,比如给dialog加一个`abc`的class,那么你你就可以这样写:
```html
<style scoped>
:global(.abc .t-radio-button__label) {
  color: red;
}
</style>
```

**Comment by woshishade** [comment]
好吧，虽然有点麻烦，只能这样处理了

**Comment by leeui2020** [comment]
好愚蠢的更新啊
