### ISSUE TITLE
[Table] 页面渲染完成后更改可编辑单元格，设置为允许编辑的单元格在defaultEditable为ture的情况下，不能进入编辑态

### ISSUE THREAD

**Issue by JasonBrook97** [Tencent/tdesign-vue-next#2621]
### tdesign-vue-next 版本

1.2.2

### 重现链接

https://stackblitz.com/edit/angular-rmmtgc?file=src/demo.vue

### 重现步骤

1.col.edit.defaultEditable 为true
2.默认所有单元格不可编辑
3.等待页面渲染完成后，更改单元格为可编辑
4.看结果，单元格允许编辑，但没有进入编辑态

### 期望结果

col.edit.defaultEditable 为true的情况下.等待页面渲染完成后，更改单元格为可编辑时，自动进入编辑态

### 实际结果

col.edit.defaultEditable 为true的情况下.等待页面渲染完成后，更改单元格为可编辑时，没有自动进入编辑态，还需要再单击一次

### 框架版本

Vue(3.2.47)

### 浏览器版本

Chrome( 111.0.5563.111)

### 系统版本

win11

### Node版本

v18.14.2

**Comment by chaishi** [comment]
`col.edit.defaultEditable`  和 `editableCellState` 不要混用，
`defaultEditable` 仅用于第一次有效，仅用于非常简约的场景，早于 `editableCellState`。（鉴于容易导致误解，后期很可能逐渐废除这个意义不大的属性，不建议在你现在的场景使用）

当你在使用 `editableCellState` 时，`defaultEditable` 就的第一次已经失效了，保持以  `editableCellState`  为准。

看了下代码，完全走到了 `filters.value === null`，自然都是返回 false，不可编辑的。修改你的 `editableCellState` 函数逻辑，保证无论何时，都有正确的编辑态即可。
```js
const editableCellState = (cellParams) => {
  // filter 为空时，所有单元格都不可编辑
  if (filters.value === null) {
    return cellParams.rowIndex === -1;
  }
  return (
    cellParams.rowIndex === filters.value.rowIndex &&
    cellParams.colIndex === filters.value.colIndex
  );
};
```

**Comment by JasonBrook97** [comment]
@chaishi 您好，非常感谢您的回复，根据您的回复我还是不太清楚我怎么处理
之前我对于关键字的理解：
editableCellState：只是描述表格是否编辑
编辑态：是指defaultEditable，当editableCellState为true时，_**自动出现编辑框**_
根据您的描述，我现理解：这两个描述的是一件事情，都指是否可以编辑，与是否出现编辑框无关

根据我的测试，
当col.edit.defaultEditable为 false时，无论editableCellState返回什么样的结果，无论第一次加载还是中间改变editableCellState的返回值，都不会自动出现编辑框。
当col.edit.defaultEditable为 true时，只要是第一次加载加载就会出现编辑框。

我的需求，当我通过editableCellState改变单元格的可编辑状态为true时，可编辑的单元格自动出现编辑框

这个需求的原因：
如果我设置初始所有单元格可编辑，那么第一次进入页面就会全是编辑框，我想这会不会是设置，col.edit.defaultEditable的原因。即使col.edit.defaultEditable为false，初始没有了满屏的编辑框，但每次单击单元格都会出现编辑框，用户体验不是很好，我希望提高编辑操作的复杂度，如：双击（我通过两次单击模拟了双击，在文档中没有找到单元格的双击事件）才能进行编辑。但目前通过editableCellState设置为可编辑，只会让我得到一个可以编辑的状态。正真编辑，要出现编辑框，还需要再点击一次。如果不设置编辑图标，就不会知道editableCellState做了什么。

**Comment by JasonBrook97** [comment]
@chaishi 允许编辑的状态下，点击表格或进入编辑，有没有其他方式能把编辑框调出来
