### ISSUE TITLE
[Dialog] 函数调用方式时 cancelBtn 类型错误

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#2635]
### tdesign-vue-next 版本

1.2.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/dialog#%E6%8F%92%E4%BB%B6%E5%87%BD%E6%95%B0%E5%BC%8F%E8%B0%83%E7%94%A8

### 重现步骤

官网的demo即可伏线

### 期望结果

期望类型正确

### 补充说明

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/54022918/228710171-e88aba1e-84da-4180-b0d2-5bc60d41f436.png">

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/3352

**Comment by chaishi** [comment]
published at v1.5.5
2023-09-13
