### ISSUE TITLE
[Dialog] preventScrollThrough防止滚动穿透优化抖动

### ISSUE THREAD

**Issue by wfq1095745112** [Tencent/tdesign-vue-next#2637]
### 这个功能解决了什么问题

防止滚动穿透是否能不让页面抖动，失去滚动条会有20px左右的宽度
 html body {
          overflow-y: hidden;
          width: calc(100% - 0px);
        }
这里的 0px 是否能计算滚动条宽度去赋值

### 你建议的方案是什么

计算不同浏览器的滚动条宽度去赋值

**Comment by nullhan** [comment]
我遇到了相同的问题
我的解决方案是将原有的 Drawer 组件的 preventScrollThrough 属性设置为false
然后在Drawer 打开的时候手动给body添加如下样式
{
overflow-y: hidden;
  transition: margin 300ms cubic-bezier(0.7, 0.3, 0.1, 1) 0s;
  width: calc(100% - 8px);
}
8px就是我的滚动条宽度
你可以写一个类名,如下:
.prevent-scroll-through {
  overflow-y: hidden;
  transition: margin 300ms cubic-bezier(0.7, 0.3, 0.1, 1) 0s;
  width: calc(100% - 8px);
}

最后在Drawer  关闭时调用close方法,再删除掉该样式
也就是给body删除prevent-scroll-through类名
希望能帮到你
