### ISSUE TITLE
[Popup] close() 方法报错

### ISSUE THREAD

**Issue by qihuantian1** [Tencent/tdesign-vue-next#2639]
### tdesign-vue-next 版本

1.2.3

### 重现步骤

![image](https://user-images.githubusercontent.com/10757545/228771424-ef338f41-2182-4163-9341-aa1cafed0d15.png)

#2596

**Comment by qihuantian1** [comment]
这个问题能帮忙尽快修复下吗？ 急需使用 @ikeq

**Comment by PengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/2838 这里修复了
