### ISSUE TITLE
[List 列表] 能否加一个选中效果

### ISSUE THREAD

**Issue by xiatiandegaga** [Tencent/tdesign-vue-next#2643]
### 这个功能解决了什么问题

![image](https://user-images.githubusercontent.com/47713355/229038795-17b1d6af-7b81-4e33-bba0-7fb3bc5f1d32.png)
类似这种，左边是list列表，点击选中

### 你建议的方案是什么

加一个选中效果

**Comment by PengYYYYY** [comment]
应该不会支持，设计如此，可以自行处理一下
