### ISSUE TITLE
[Dialog] 全屏状态下关闭footer,仍然占据body高度

### ISSUE THREAD

**Issue by xunzhaoliuxingluo** [Tencent/tdesign-vue-next#2644]
### tdesign-vue-next 版本

1.2.2

### 重现步骤

![image](https://user-images.githubusercontent.com/41046019/229048951-3f2eae8b-2d3e-463f-8fe0-b51bb0f5fc1b.png)
![image](https://user-images.githubusercontent.com/41046019/229049068-596083dc-ee37-456e-a3f2-f44c4082cca8.png)

### 框架版本

Vue(3.2.47)

### 浏览器版本

Google Chrome版本 111.0.5563.147（正式版本） （64 位）

### 系统版本

Windows 11 家庭中文版 22H2

**Comment by D-xuanmo** [comment]
认领该任务，预计 2 日内提交
