### ISSUE TITLE
[InputNumber] 数字输入框在设置了 decimalPlaces 属性时，输入超过该属性设置的小数位数为四舍五入

### ISSUE THREAD

**Issue by brankcar** [Tencent/tdesign-vue-next#2645]
### tdesign-vue-next 版本

1.2.3

### 重现步骤

`<t-input-number v-model="value" :decimal-places="2" />`

9.99 输入框失焦显示正常，输入 9.999 失焦后会变成 10.00

### 期望结果

decimal-places设置小数位数限制不影响数据展示

**Comment by uyarn** [comment]
这不是bug 如果没有这样才是bug

**Comment by brankcar** [comment]
> 这不是bug 如果没有这样才是bug

能否分享一下具体是出于什么情况考虑的呢？在我的理解中限制小数位数应该直接截取到指定小数位数，四舍五入是为了兼容JS精度丢失的问题么？
