### ISSUE TITLE
[Bug][t-input-number] 把v-model设置成undefined实现清空，下次激活输入框自动恢复上次的值

### ISSUE THREAD

**Issue by waixingjiandie** [Tencent/tdesign-vue-next#265]
## tdesign-vue-next

You will open a bug issue at tdesign-vue-next。

### Describe Environment

browser version:
tdesign-vue-next version: 0.7.0

### Describe the bug

1. 在输入框输入数字，
2. 保持光标还在输入框，点击清空，即把v-model设置成undefined。
3. 点击输入框，清空前的数字自动恢复

如果第3步的数字没恢复，点击空白处试试。

codesandbox online demo: https://codesandbox.io/s/eager-proskuriakova-5nhik

**Comment by waixingjiandie** [comment]
最好是通过设置成null清空吧。

还有个问题是，我限制最小值为0。
清空后，点击组件自带的让数值减小的按钮，数值会变成-1，小于最小值0了

**Comment by pengYYYYY** [comment]
0.8.0 版本已修复
