### ISSUE TITLE
[Cascader] keys 指定都是 name 出现省市显示异常

### ISSUE THREAD

**Issue by haixwang** [Tencent/tdesign-vue-next#2657]
### tdesign 版本

1.2.2

### 重现链接

No response

### 重现步骤

![image](https://user-images.githubusercontent.com/129025223/228175720-e8dee302-3b1b-4d7a-9acb-7bf5add6db15.png)
![image](https://user-images.githubusercontent.com/129025223/228176206-ca7c5f47-dfc4-4b85-a25f-60188690ebb8.png)
![image](https://user-images.githubusercontent.com/129025223/228176310-1ffc4cbb-7f3b-4960-bb15-1991df7a73ee.png)
![image](https://user-images.githubusercontent.com/129025223/228176376-da41a981-1569-4adc-be56-55ce3dedfc83.png)

### 期望结果

期望选择结果为我选择的

### 实际结果

实际选择结果为省市两级展示错误区级展示正常

### 框架版本

vue3

### 补充说明

keys指定value指定为id的话展示实际输出结果为id，想要的是name

**Comment by PengYYYYY** [comment]
出现了同样的key，不能用同样的key
