### ISSUE TITLE
[Bug][select] 布尔值选中后不显示

### ISSUE THREAD

**Issue by yangjunjun** [Tencent/tdesign-vue-next#266]
## tdesign-vue-next

You will open a bug issue at tdesign-vue-next。

### Describe Environment

browser version: chrome 
tdesign-vue-next version: 最新 0.7

### Describe the bug

当 select 组件的 options 选项值是 true 或者 false 时，选中后不会显示所选的值

codesandbox online demo: 
https://codesandbox.io/s/tdesign-vue-next-demo-forked-tev6z?file=/src/demo.vue

**Comment by pengYYYYY** [comment]
API 不支持 boolean 值

**Comment by pengYYYYY** [comment]
可以使用 switch 组件
