### ISSUE TITLE
[Progress] color 设置为对象和数组时不生效

### ISSUE THREAD

**Issue by rehiy** [Tencent/tdesign-vue-next#2662]
### tdesign 版本

1.1.1

### 重现步骤

使用圆形进度条的情况下，color 只支持string设置

<img width="545" alt="ae4787250f1847edec56745e091b481" src="https://user-images.githubusercontent.com/8297757/224872005-3c48e444-1221-4c81-832a-549775105be5.png">

### 期望结果

不同进度应显示对应的颜色，或在文档予以说明，circle 时不支持

### 实际结果

颜色无法显示

**Comment by PengYYYYY** [comment]
仅支持单颜色的 color 配置
