### ISSUE TITLE
[switch开关] t-switch设置custom-Value="[1, 0]" 没有设置默认值时报错

### ISSUE THREAD

**Issue by superextend** [Tencent/tdesign-vue-next#2667]
### tdesign-vue-next 版本

能

### 重现步骤
![image](https://user-images.githubusercontent.com/58968749/230251105-8922adbc-df27-45a4-9265-71e325681e01.png)

<t-switch  :custom-Value="[1, 0]" ></t-switch>
不设置默认值 报错 
Error: value is not in [1,0]

**Comment by wangyang0210** [comment]
自定义范围值后，初始值需要自己来做下绑定，这个我感觉增加个对应的演示demo，让用户知道如何使用就好吧；

https://stackblitz.com/edit/angular-pexq9h?file=src/demo.vue
