### ISSUE TITLE
[select选择器] 当select 设置为 clearable ，点击清空后，value 的值不是变为空，是变为 undefined，在axios post 提交时此参数会过滤

### ISSUE THREAD

**Issue by superextend** [Tencent/tdesign-vue-next#2673]
### tdesign-vue-next 版本

能

### 重现步骤

<t-select v-model="value" :options="options1" placeholder="请选择云解决方案" clearable></t-select>
当select 设置为 clearable ，点击清空后，value 的值不是变为空，是变为 undefined，在axios post 提交时此参数会过滤

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue-next/blob/develop/src/select/select.tsx#L440 可以提个PR改下这里

**Comment by uyarn** [comment]
reopen since the pr was not merged
