### ISSUE TITLE
[全部组件] 在Typescript中使用时所有组件的类型全为 any 类型

### ISSUE THREAD

**Issue by angx-o** [Tencent/tdesign-vue-next#2674]
### tdesign-vue-next 版本

1.2.3

### 重现步骤

vue + ts 项目；导入组件

**Comment by Aicmortal** [comment]
能提供一下最小复现代码吗?
[为什么需要最小复现?](https://antfu.me/posts/why-reproductions-are-required-zh)

**Comment by uyarn** [comment]
<img width="844" alt="image" src="https://user-images.githubusercontent.com/26377630/230582645-cdb64271-a60c-4b5b-834f-1fe5ae0a05c7.png">
这个加了吗

**Comment by uyarn** [comment]
没有更多回复～ 请参考上面的方式 另外也可能是vue的版本问题影响 依赖3.2+版本的vue 如果有问题再reopen

**Comment by git-lt** [comment]
我升级了一下 tdesign 重新安装一下解决了
