### ISSUE TITLE
[Tab] 当选项卡数量超出最大宽度，无可滑动功能。

### ISSUE THREAD

**Issue by wenkeming** [Tencent/tdesign-vue-next#2679]
### tdesign-vue-next 版本

1.2.4

### 重现链接

https://tdesign.tencent.com/vue-next/components/tabs#%E5%8F%AF%E6%BB%91%E5%8A%A8%E7%9A%84%E9%80%89%E9%A1%B9%E5%8D%A1

### 期望结果

https://tdesign.tencent.com/vue/components/tabs#%E5%8F%AF%E6%BB%91%E5%8A%A8%E7%9A%84%E9%80%89%E9%A1%B9%E5%8D%A1

**Comment by uyarn** [comment]
完整的可滑动功能需要配合scroll组件来做样式 暂时只能通过点击左右来操作 这个示例代码展示的有误 得修复一下

**Comment by wenkeming** [comment]
> 完整的可滑动功能需要配合scroll组件来做样式 暂时只能通过点击左右来操作 这个示例代码展示的有误 得修复一下

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/8252267/230841208-fa65a6c4-eb09-4200-b23d-f53de9b5286c.png">

**Comment by uyarn** [comment]
> > 完整的可滑动功能需要配合scroll组件来做样式 暂时只能通过点击左右来操作 这个示例代码展示的有误 得修复一下
> 
> <img alt="image" width="1213" src="https://user-images.githubusercontent.com/8252267/230841208-fa65a6c4-eb09-4200-b23d-f53de9b5286c.png">

嗯 示例代码有问题
