### ISSUE TITLE
[Menu] MenuItem组件target属性失效

### ISSUE THREAD

**Issue by wulianpu** [Tencent/tdesign-vue-next#2680]
MenuItem组件target属性失效，查看源码发现只有存在href属性时才会用到，但是我使用to属性跳转时，无法指定是否新标签页打开
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/44516614/230707639-ea85827d-a73b-4ba0-8501-6b2e7334d91c.png">

**Comment by PengYYYYY** [comment]
这个属性就是给href用的
