### ISSUE TITLE
layout布局 有没有希望支持 trigger

### ISSUE THREAD

**Issue by AllianceTing** [Tencent/tdesign-vue-next#2684]
### 这个功能解决了什么问题

有希望 使用trigger 解决 组件间的通信问题
![image](https://user-images.githubusercontent.com/72297937/230752159-def34522-7abc-496a-a797-e5a4b9403ec5.png)
不能通过Header 控制 Aside 侧边栏的触发问题 
详细实实例参见 https://antdv.com/components/layout-cn#components-layout-demo-custom-trigger 自定义触发器

### 你建议的方案是什么

不能通过Header 控制 Aside 侧边栏的触发问题 
详细实实例参见 https://antdv.com/components/layout-cn#components-layout-demo-custom-trigger 自定义触发器

**Comment by PengYYYYY** [comment]
这种自己通过store来控制吧，暂不考虑支持
