### ISSUE TITLE
[Upload] 希望可以新增上传剪贴板的图片

### ISSUE THREAD

**Issue by candy-Tong** [Tencent/tdesign-vue-next#2686]
### 这个功能解决了什么问题

我们的审核人员，经常需要从资料中进行截图然后上传，每次保存到本地，然后上传，非常麻烦。
如果直接能从剪贴板读取图片上传就非常方便了

### 你建议的方案是什么

参考方案：
新增粘贴上传，先点击上传组件聚焦，然后按 ctrl+v 上传剪贴板的图片
![image](https://user-images.githubusercontent.com/20377280/230814773-a4aad628-3ee2-4044-a045-0dbcb20f2215.png)

或者点击按钮直接从粘贴板读取图片并上传。类似 picgo
![image](https://user-images.githubusercontent.com/20377280/230815014-67048d98-7482-4181-9a3d-cc6cdac8dbc8.png)

**Comment by chaishi** [comment]
是一个好建议

**Comment by yanxugong** [comment]
resolved in #2814
