### ISSUE TITLE
[Input] 密码输入框会出现两个眼睛

### ISSUE THREAD

**Issue by wulianpu** [Tencent/tdesign-vue-next#2691]
密码输入框会出现两个眼睛，一个是原生的一个是组件自带的

<img width="983" alt="image" src="https://user-images.githubusercontent.com/44516614/230859888-f5bc03ba-ac85-4e09-8549-8c7862e95796.png">

**Comment by PengYYYYY** [comment]
是哪个浏览器的

**Comment by wulianpu** [comment]
> 是哪个浏览器的

我用的Edge

**Comment by wangyang0210** [comment]
隐藏掉edge默认的样式就好了

input[type='password']::-ms-reveal {
      display: none;
    }
