### ISSUE TITLE
[table] resizable API失效

### ISSUE THREAD

**Issue by Wesleyyy0808** [Tencent/tdesign-vue-next#2699]
### tdesign-vue-next 版本

1.2.3

### 重现步骤

TD VueNext 1.2.3 table-bug:
无论设不设置resizable（即使设置为false）仍然可以调整

### 实际结果

无论设不设置resizable（即使设置为false）仍然可以调整

**Comment by Wesleyyy0808** [comment]
官网的示例都是可调整的😄

**Comment by uyarn** [comment]
fixed in 1.3.0
