### ISSUE TITLE
应该建立一个nuxt3的模块包吧

### ISSUE THREAD

**Issue by gao-xiang** [Tencent/tdesign-vue-next#2703]
### 这个功能解决了什么问题

现在Nuxt是vue流行的PC端的服务端渲染方案，tdesign-vue-next没有一个Nuxt中简单使用的模块。

https://nuxt.com/modules

### 你建议的方案是什么

tdesign-vue-next没有一个Nuxt中简单使用的模块。

**Comment by yixiaco** [comment]
不知道指的是不是这个 #726 #2726

**Comment by PengYYYYY** [comment]
有相关的nuxt3实践，可以参考一下
