### ISSUE TITLE
Dialog组件嵌入Upload组件上传图片预览，ESC键退出预览会关闭Dialog组件

### ISSUE THREAD

**Issue by Likunone** [Tencent/tdesign-vue-next#2704]
### tdesign-vue-next 版本

1.3.4

### 重现链接

https://stackblitz.com/edit/angular-3c4gze-nusl4k?file=package.json,src%2Fdemo.vue

### 重现步骤

点击按钮显示弹框
选择图片上传
点击上传组件预览图标
ESC键退出预览

### 期望结果

只关闭图片预览弹框

### 实际结果

图片预览弹框与Dialog组件弹框都关闭了

**Comment by chaishi** [comment]
需要优化处理 ESC 键作用范围

**Comment by chaishi** [comment]
see https://github.com/Tencent/tdesign-vue-next/issues/2928
