### ISSUE TITLE
[select] 太长没有显示省略号

### ISSUE THREAD

**Issue by sampsonliu** [Tencent/tdesign-vue-next#2707]
### tdesign-vue-next 版本

1.2.3

### 重现链接

https://stackblitz.com/edit/angular-1gnhbo?file=package.json

### 重现步骤

<img width="1726" alt="image" src="https://user-images.githubusercontent.com/15682051/231339892-182c221e-5c79-4a7e-ae5b-40536623b2ab.png">

**Comment by wangyang0210** [comment]
通过插槽自定义的话，可以给`t-tag`标签，增加现有的`max-width`属性限制能够实现你想要的效果；
https://stackblitz.com/edit/angular-1gnhbo-j1u1kn?file=src/demo.vue
