### ISSUE TITLE
#1934 并没有修复,只是把操作列写成了fix,列宽依然不会自动变窄

### ISSUE THREAD

**Issue by shaobo4010** [Tencent/tdesign-vue-next#2709]
已在新版本中修复

_Originally posted by @chaishi in https://github.com/Tencent/tdesign-vue-next/issues/1934#issuecomment-1328209184_

**Comment by chaishi** [comment]
提供的信息过于稀缺，尝试过理解，也尝试过，使用。无法明白问题是什么吗，无法处理。issue close

**Comment by chaishi** [comment]
1. 请提供正在使用的组件版本号
2. 提供可复现问题的链接
3. 提供具体的交互操作复现相关问题
