### ISSUE TITLE
[Bug][树-Tree] 树型控件显示不完整及空值自动赋值了

### ISSUE THREAD

**Issue by williambao** [Tencent/tdesign-vue-next#271]
树型控件发现2个问题。
1. 当有顶部节点的value为空值时，他会自动赋值一个值。如t2, t6, t9之类的。
<img width="791" alt="CleanShot 2022-01-26 at 18 40 53@2x" src="https://user-images.githubusercontent.com/779521/151148857-87a4249a-4668-4af8-8059-a295ec27074b.png">

2. 在没有选择时，显示成一条线。选择后才显示完整。
![CleanShot 2022-01-26 at 18 25 25@2x](https://user-images.githubusercontent.com/779521/151148531-ce432e3f-8aa0-4ed6-a3eb-499cc068f4dd.png)

**Comment by pengYYYYY** [comment]
已收到

**Comment by pengYYYYY** [comment]
第一个问题，树需要一个uniKey，所以如果没有值的时候会设置一个值，第二个问题，正在修复

**Comment by pengYYYYY** [comment]
0.8.0 版本已处理
