### ISSUE TITLE
[组件名称] table 

### ISSUE THREAD

**Issue by shaobo4010** [Tencent/tdesign-vue-next#2710]
### tdesign-vue-next 版本

1.2.3

### 重现步骤

stripe 后 表头为灰色,第一行也为灰色

### 期望结果

应该第一行是白色

### 实际结果

第一行也为灰色

### 系统版本

windows10

**Comment by chaishi** [comment]
官网无法复现问题，issue close
<img width="887" alt="image" src="https://user-images.githubusercontent.com/11605702/231632154-0b410a49-4328-41b8-963d-e1285cd0f8de.png">
