### ISSUE TITLE
[t-Switch] 在t-table 中使用t-Switch时传入参数发现有问题

### ISSUE THREAD

**Issue by ko7724** [Tencent/tdesign-vue-next#2731]
### tdesign-vue-next 版本

1.2.3

### 重现步骤

`                <t-table row-key="id" :data="mesHkProcessFlowEntry" :foot-data="[{}]" :columns="ProcessFlowEntryColumns"
                stripe hover bordered size="small" >
                  <template #isLast="{ row }">
                      <el-switch v-model="row.isLast" inline-prompt active-text="是" inactive-text="否" @change="isLastProcessChange('el-switch',row)"/>
                    <t-switch v-model="row.isLast" size="small" :label="['是', '否']" @change="isLastProcessChange('t-switch',row)" />
                    {{ row.ID }}
                  </template>
                  <template #op="{ row, rowIndex }">
                    <el-button link type="primary" size="small" @click="MoveProcessFlowEntry(row,rowIndex,1)">下移</el-button>
                    <el-button link type="primary" size="small" @click="deleteRowProcessFlowEntry(row)">移除</el-button>
                  </template>
                </t-table>`

<script setup>
const isLastProcessChange =  (mm,row) => {
  console.log(mm,row);
}
</script>

**Comment by chaishi** [comment]
https://stackblitz.com/run?file=package.json,src%2Fdemo.vue
请在这个链接里面复现一下你描述的问题，否则我们无法处理这个 issue，超出一定时间后，会自动关闭 issue
