### ISSUE TITLE
[tagInput] 数据为空[]时报错

### ISSUE THREAD

**Issue by bodian520** [Tencent/tdesign-vue-next#2735]
### tdesign-vue-next 版本

vite v2.9.15

### 重现步骤

组件：
            <t-tag-input v-model="formData.signs" label="标签值：" placeholder="请填写标签，按回车添加" clearable
              :disabled="fieldIsReadOnly" :tag-props="{ theme: 'primary' }" class="flex-1" />
变量：
<img width="375" alt="image" src="https://user-images.githubusercontent.com/62273402/232481662-9265521b-21a0-4c6e-87f5-b6ecbcd0722e.png">

### 期望结果

正常不报错

### 实际结果

signs值为[]时，报错：
<img width="814" alt="image" src="https://user-images.githubusercontent.com/62273402/232481526-31842cf7-6a93-4b0b-9b98-dfd84a5044b8.png">

**Comment by wangyang0210** [comment]
可以提供个demo或者代码片段嘛？

> ### tdesign-vue-next 版本
> vite v2.9.15
> 
> ### 重现链接
> _No response_
> 
> ### 重现步骤
> 组件： 变量： <img alt="image" width="375" src="https://user-images.githubusercontent.com/62273402/232481662-9265521b-21a0-4c6e-87f5-b6ecbcd0722e.png">
> 
> ### 期望结果
> 正常不报错
> 
> ### 实际结果
> signs值为[]时，报错： <img alt="image" width="814" src="https://user-images.githubusercontent.com/62273402/232481526-31842cf7-6a93-4b0b-9b98-dfd84a5044b8.png">
> 
> ### 框架版本
> _No response_
> 
> ### 浏览器版本
> _No response_
> 
> ### 系统版本
> _No response_
> 
> ### Node版本
> _No response_
> 
> ### 补充说明
> _No response_

**Comment by wangyang0210** [comment]
https://stackblitz.com/edit/angular-gfuxbs-qxxpw5?file=src/demo.vue

我写了demo试了下，没啥问题，所以可以的话，你可以提供下demo或者代码片段；

**Comment by PengYYYYY** [comment]
<img width="242" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/35833812/b0ecee07-0585-439d-8a5f-bf54e220c56e">
看了下代码，应该是不会出现这种报错的，看下您的版本呢
