### ISSUE TITLE
[Upload] 主题为image时，无法展示size-limit警告文本

### ISSUE THREAD

**Issue by ngyyuusora** [Tencent/tdesign-vue-next#2736]
### tdesign-vue-next 版本

1.0.9

### 重现步骤

theme="image"时，配置size-limit，上传超过配置值大小的文件

### 期望结果

在
![image](https://user-images.githubusercontent.com/28800738/232396850-40e8cbd4-c7fd-4429-8982-2fb09bfb3088.png)
下方出现红色警告文本

### 实际结果

未出现，取消theme="image"可显示出大小限制警告文本

**Comment by ZTH520** [comment]
> > ![image](https://user-images.githubusercontent.com/37199360/232660182-a982c97e-1db6-42de-89ff-3d146c646cde.png) 是这样的效果吗 @chaishi 帮忙评估一下😀
> 
> 有大佬看一下吗

不知道一开始设计 theme="image" 就不要显示还是怎么样的，需要大佬们看看
@uyarn

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/3566

已在 https://github.com/Tencent/tdesign-vue-next/pull/3566 中支持图片大小超出限制提醒

**Comment by chaishi** [comment]
resolved at `v1.6.8` 2023-11-07
