### ISSUE TITLE
[config-provider] 对Table的表头、日期选择器、分页等不能响应式更改，导致仅有一半语言被更改

### ISSUE THREAD

**Issue by GrainInBeard** [Tencent/tdesign-vue-next#2737]
### tdesign-vue-next 版本

1.3.0

### 重现步骤

配置config-provider更改语言，不仅系统自带分页、选择器等没有响应式切换，表格表头的自定义I18N也无法响应式切换，导致两种语言各一半

### 期望结果

能响应式切换全局配置

### 框架版本

Vue 3.2.45

### 浏览器版本

112.0.1722.48 

### 系统版本

Windows 11

### Node版本

16.12.0

**Comment by uyarn** [comment]
table表头 也不生效 是指表头里用了组件还是什么场景？

**Comment by uyarn** [comment]
https://stackblitz.com/edit/angular-fvhxrp?file=src%2Fdemo.vue 可以在这给个示例吗

**Comment by GrainInBeard** [comment]
table的columns的title为string时，无法响应全局配置，当为render时则可以响应，问题不是很大
可以由原来的   
```
title: t('name')
```
 改为
```
title: () => t('name')
```

**Comment by uyarn** [comment]
supported in 1.5.4
