### ISSUE TITLE
[Select] 自定义选项 + filterable + multiple模式下, 筛选结果无法选中

### ISSUE THREAD

**Issue by cloudfun** [Tencent/tdesign-vue-next#2741]
### tdesign-vue-next 版本

1.3.0

### 重现链接

https://stackblitz.com/edit/angular-yzaa5j?file=src%2Fdemo.vue

### 重现步骤

在重现示例中输入 '用户三'筛选出结果, 点击结果时无法选中
<img width="477" alt="image" src="https://user-images.githubusercontent.com/962598/232714957-49329c2e-622b-40ba-89b4-50b3e8ddffcc.png">

### 框架版本

Vue(3.2.41)

### 浏览器版本

Chrome(107.0.5304.87)

### 系统版本

MacOS(13.0)

### Node版本

19.6.1

**Comment by uyarn** [comment]
问题已经修复了 可以先用下1.3.1-alpha.1的版本 或者暂时留在1.2.3
