### ISSUE TITLE
[table] footerAffixedBottom参数设置时控制套报错

### ISSUE THREAD

**Issue by AAAninin** [Tencent/tdesign-vue-next#2744]
### tdesign-vue-next 版本

1.3.0

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤

![image](https://user-images.githubusercontent.com/31433576/232947230-4da05e45-b58d-4401-8ae1-527f09f1bdc6.png)
从官网demo进入分页器条数切换成50条 然后点击表尾吸底checkbox 就会出现

### 系统版本

windows

**Comment by AAAninin** [comment]
![image](https://user-images.githubusercontent.com/31433576/232947382-9710bd0c-8b20-4551-a6c9-f97a41b6f1cb.png)
报错信息

**Comment by uyarn** [comment]
fixed in 1.3.2
