### ISSUE TITLE
请问腾讯哪些产品使用了该框架

### ISSUE THREAD

**Issue by SpringHgui** [Tencent/tdesign-vue-next#2748]
### 这个功能解决了什么问题

请问腾讯哪些产品使用了该框架

### 你建议的方案是什么

请问腾讯哪些产品使用了该框架

**Comment by uyarn** [comment]
这边是中后台框架 所以很多内部系统没法列举访问 这边简单列几个可以访问的
https://wj.qq.com/
https://codesign.qq.com/
https://developers.weixin.qq.com/doc/oplatform/Third-party_Platforms/2.0/product/wxcloudrun.html
