### ISSUE TITLE
[select] t-select组件在multiple模式下，当值改变时onChange事件每次被触发3次

### ISSUE THREAD

**Issue by ZJQ0925** [Tencent/tdesign-vue-next#2752]
### tdesign-vue-next 版本

V1.3.0

### 重现链接

https://stackblitz.com/edit/angular-c2ksng?file=src/demo.vue

### 重现步骤

tdesign-vue-next 版本V1.3.0下，t-select组件使用多选multiple模式下，值发生改变时，onChange事件每次会触发3次，前后两次返回的值一致，中间第二次返回的值有误。

**Comment by uyarn** [comment]
谢谢反馈 已经修复了 今天的版本更新会带上的
