### ISSUE TITLE
[t-loading] 在移动端图标显示不正常

### ISSUE THREAD

**Issue by swordfly1979** [Tencent/tdesign-vue-next#2754]
### tdesign-vue-next 版本

1.3.0

### 重现链接

[_Tdesign-loading_](https://tdesign.tencent.com/vue-next/components/loading?tab=demo)

### 重现步骤

web端显示正常，浏览器切换为移动模式图标显示不正常。tdesign官网示例也是如此。

### 期望结果

正常显示图标

### 框架版本

Vue(3.2.47)

### 浏览器版本

 Chrome 110.0.5481.177（正式版本） （64 位）

### 系统版本

Deepin(20.8)

### Node版本

18.14.2

**Comment by uyarn** [comment]
refer to https://github.com/Tencent/tdesign-vue-next/issues/358
