### ISSUE TITLE
[TDateRangePicker] 设置 valueType 时控制台报警告

### ISSUE THREAD

**Issue by Lyan-u** [Tencent/tdesign-vue-next#2755]
### tdesign-vue-next 版本

1.3.0

### 重现步骤

```vue
<template>
  <t-date-range-picker valueType="YYYY-MM-DD"></t-date-range-picker>
</template>
```
控制台报 valueType 的校验错误的警告
<img width="474" alt="image" src="https://user-images.githubusercontent.com/46185702/233538039-f3ba86ec-64e1-4d5e-a9e0-6a088bc3ff7f.png">

https://github.com/Tencent/tdesign-vue-next/blob/develop/src/date-picker/date-range-picker-props.ts#L138
<img width="620" alt="image" src="https://user-images.githubusercontent.com/46185702/233538180-8bd5d1d2-94fb-43b9-8614-68640dffba5c.png">

这个地方的校验有问题

**Comment by uyarn** [comment]
fixed in 1.3.2
