### ISSUE TITLE
[t-loading] 在移动端图标显示不正常

### ISSUE THREAD

**Issue by swordfly1979** [Tencent/tdesign-vue-next#2756]
### tdesign-vue-next 版本

1.3.0

### 重现步骤

自己页面显示效果：
![录屏_选择区域_20230421133304](https://user-images.githubusercontent.com/44988237/233551808-7fd10973-7e1c-4680-8bbe-3caf06bbd857.gif)
Tdesign官网显示效果
![录屏_选择区域_20230421135735](https://user-images.githubusercontent.com/44988237/233552486-a312c94e-d60c-405a-9d84-9e5a5d7c2e30.gif)

### 期望结果

图标可以在移动端正常显示

### 框架版本

Vue(3.2.47)

### 浏览器版本

 Chrome 110.0.5481.177（正式版本） （64 位）

### 系统版本

Deepin(20.8)

### Node版本

18.14.2

**Comment by uyarn** [comment]
请看你上一个issue的回复 https://github.com/Tencent/tdesign-vue-next/issues/2754

**Comment by swordfly1979** [comment]
![image](https://user-images.githubusercontent.com/44988237/233569166-d6318abf-144f-4a1e-ae92-bd6ea7942956.png)
真机显示是这个效果，也不正常。

**Comment by uyarn** [comment]
> ![image](https://user-images.githubusercontent.com/44988237/233569166-d6318abf-144f-4a1e-ae92-bd6ea7942956.png) 真机显示是这个效果，也不正常。

![wecom-temp-71100-e60f9e933892e4244c837217991f4d41](https://user-images.githubusercontent.com/26377630/233572376-bcdd3d54-0d84-447f-a4f7-4f33ebecaeaf.jpg)
我测试的真机效果是正常的 麻烦再具体描述下你的真机环境
