### ISSUE TITLE
[Select] 组件 默认值的问题

### ISSUE THREAD

**Issue by sershine** [Tencent/tdesign-vue-next#2758]
### tdesign-vue-next 版本

1.3.0-1.3.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/select

### 重现步骤

打开网址，可以看到，select组件在没有设置value属性的时候，显示的值为false

### 期望结果

在没有设置value属性时，应该展示placeholder

### 框架版本

3.2.47

### 浏览器版本

Edge 112.0.1722.48

**Comment by uyarn** [comment]
fixed in 1.3.2
