### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by shaobo4010** [Tencent/tdesign-vue-next#2762]
### tdesign-vue-next 版本

1.3.0

### 重现步骤

<t-select
                            v-model="formData.permissions"
                            :options="permissionOptions"
                            placeholder="请选择节点"
                            multiple
                        >
会把formData.permissions值直接显示出来而不是换算成label,并且也不会勾选

**Comment by uyarn** [comment]
没看懂想表达什么 可以把问题再描述清楚点吗？
