### ISSUE TITLE
[table] table vue next 表格 表头吸顶 功能失效（示例代码缺失，组件功能正常）

### ISSUE THREAD

**Issue by homker** [Tencent/tdesign-vue-next#2764]
### tdesign-vue-next 版本

1.3.1 存在一样的问题

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤

选择表头吸顶，选择一页五十条数据，然后滚动页面。

### 期望结果

和react版本保持一致，表头吸附在页面的顶部。

### 实际结果

表头未吸附

**Comment by homker** [comment]
1.2.3 和 1.3.1 的 vue3 版本均有此问题，1.2.7 的vue2 版本是正常的

**Comment by chaishi** [comment]
提供的链接由于没有保存过，所以其他人访问的时候，什么也看不到，直接跳转到首页。

经过检查，无效只是因为示例代码缺少 `:headerAffixedTop="headerAffixedTop ? { offsetTop: 87, zIndex: 1000 } : undefined"`，补上就好了

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2999
