### ISSUE TITLE
[Select] 开启多选/搜索属性后，输入搜索key并点击选项，无法选中所需选项

### ISSUE THREAD

**Issue by Menffy** [Tencent/tdesign-vue-next#2766]
### tdesign-vue-next 版本

能

### 重现链接

<t-select                     v-model="formData[item.colKey]"                     :filterable="true"                     :clearable="true"                     :options="item['options']"                     :prefix-text="getLabel(item.colKey)"                     class="form-item-content"                     :min-collapsed-num="2"                     multiple                   />

### 重现步骤

<img width="399" alt="image" src="https://user-images.githubusercontent.com/44236460/233913374-013ce3ca-48ca-4d18-ba9e-b2b2b4d8dfa9.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/44236460/233913412-2a901704-3a77-4cba-8ef1-d8055e695cfd.png">
<img width="396" alt="image" src="https://user-images.githubusercontent.com/44236460/233913567-fafe90af-e4db-44a0-b069-23b9d0e2d36e.png">

### 期望结果

**期望：**
<img width="418" alt="image" src="https://user-images.githubusercontent.com/44236460/233913789-8c65f18b-21c1-475d-84ed-8e9aa544f4d5.png">

### 实际结果

**实际过滤后无法选中：**
<img width="421" alt="image" src="https://user-images.githubusercontent.com/44236460/233913635-2e2bc34c-772b-49d3-9486-fa9c2887b2bc.png">

### 框架版本

"version": "1.3.1",

### 浏览器版本

版本 112.0.5615.49（正式版本） (arm64)

### 系统版本

版本13.2.1 (22D68)

### Node版本

v16.20.0

### 补充说明

随意设置场景，只要select组件开启 :filterable="true" 以及multiple即可复线

**Comment by uyarn** [comment]
@Menffy 这个是1.3.0版本的问题 1.3.1已经修复了 你可以升级到1.3.1确认下 如果还有问题 可以企微联系我
