### ISSUE TITLE
[Select]  inputProps中的input-class属性只有在multiple模式中生效

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#2767]
### tdesign-vue-next 版本

1.3.1

### 重现链接

https://stackblitz.com/edit/angular-q3pypp?file=package.json,src%2Fdemo.vue

### 期望结果

inputClass属性正常生效

### 实际结果

inputClass属性未生效

**Comment by uyarn** [comment]
fixed in 1.3.2
