### ISSUE TITLE
[Tooltip] Tooltip无法关闭

### ISSUE THREAD

**Issue by samchenws** [Tencent/tdesign-vue-next#2769]
### tdesign-vue-next 版本

 0.26.2

### 重现步骤

![image](https://user-images.githubusercontent.com/37535153/234229099-bada56cb-396b-4224-994a-5c8ec97822ed.png)
鼠标放到这边不会消失，希望能关闭，视觉明显出现问题

### 期望结果

鼠标放到这边消失

### 实际结果

鼠标放到这边不会消失

**Comment by PengYYYYY** [comment]
版本过低

**Comment by samchenws** [comment]
> 版本过低，请升级到高版本

1.3.3也存在这个问题
