### ISSUE TITLE
Menu 导航菜单

### ISSUE THREAD

**Issue by fengyue-bccsy** [Tencent/tdesign-vue-next#2773]
### 这个功能解决了什么问题

设置expandMutex为true，在同级别互斥展开时候，两个二级菜单会如期效果，如果是点一级菜单，那么展开的二级菜单不能收缩起来，希望的结果是点一级菜单时候，展开的二级菜单也能收起来

### 你建议的方案是什么

希望的结果是点一级菜单时候，展开的二级菜单也能收起来

**Comment by PengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/assets/35833812/e18a8e1a-5b81-44f7-b5de-d2b9c814686b

表现正常喔

**Comment by PengYYYYY** [comment]
每一级的互斥应该只影响他的同级
