### ISSUE TITLE
Table 表格拉伸有问题

### ISSUE THREAD

**Issue by fengyue-bccsy** [Tencent/tdesign-vue-next#2786]
### tdesign-vue-next 版本

1.3.2

### 重现步骤

复制的组件文档例子，在浏览器缩放时候有概率出现如下情况：
![QQ截图20230428191047](https://user-images.githubusercontent.com/65479961/235134842-d396b94d-60b6-4f7b-be1e-e09b48e4e78b.png)

### 期望结果
固定表头和列的表格
在浏览器缩放时候，所有列不漏掉下边框

### 实际结果

在浏览器缩放时候，固定的列，有概率会漏掉下边框，修改默认css，设置不自动换行，就会正常，恢复默认的自动换行，就又不正常

**Comment by chaishi** [comment]
待有稳定复现的示例代码后，再做处理。(或 reopen，或 open another issue）

<img width="301" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/6e8cf8a4-32d4-479e-bd69-42f611473300">
