### ISSUE TITLE
[Dropdown] `OnClick` 类型错误

### ISSUE THREAD

**Issue by RSS1102** [Tencent/tdesign-vue-next#2787]
### tdesign-vue-next 版本

^1.3.2

### 重现链接

https://codesandbox.io/p/github/RSS1102/td-vue-next-demo/main?workspaceId=9efcc96a-b60b-434f-918e-c447eed89dac&file=%2Fsrc%2Fcomponents%2FDropdown%2Fbase.vue&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A31%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A30%7D%5D

### 重现步骤

1. 点击下来选项
2. 在控制台打印选项

### 期望结果

```ts
{
    "content": "操作一",
    "value": 1
}
```

### 实际结果

```ts
{
dropdownItem: DropdownOption, 
context: { e: MouseEvent }}
```

### 框架版本

"vue": "^3.2.47"

### 浏览器版本

112.0.5615.138

### 系统版本

win11

### Node版本

v18.6.0

### 补充说明

[文档](https://tdesign.tencent.com/vue-next/components/dropdown?tab=api#dropdown-events)

**Comment by uyarn** [comment]
![image](https://user-images.githubusercontent.com/26377630/235430253-d4664195-9179-4d89-8686-fa74ac3ff494.png)
<img width="801" alt="image" src="https://user-images.githubusercontent.com/26377630/235430303-8ca1e1c0-0392-418f-87d0-292153707a22.png">
