### ISSUE TITLE
[t-select] 点击选项的时候，控制台会出现警告

### ISSUE THREAD

**Issue by wou101771** [Tencent/tdesign-vue-next#2794]
### tdesign-vue-next 版本

1.3.2

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤

点击选项的时候，控制台会出现警告
![image](https://user-images.githubusercontent.com/52279380/235575804-7c1a08ac-5169-46b2-a15a-728375435946.png)

### 期望结果

修复bug

**Comment by superextend** [comment]
这个问题官方有人修复吗

**Comment by uyarn** [comment]
> 这个问题官方有人修复吗

已经修复了 还没发版本 暂时忽略这个告警
