### ISSUE TITLE
[Input][Button] 中的文字有没有居中吗？还是我看错了？看着非常别扭，感觉文字偏下

### ISSUE THREAD

**Issue by SingerLan** [Tencent/tdesign-vue-next#2798]
### tdesign-vue-next 版本

是

### 重现链接

https://tdesign.tencent.com/starter/vue-next/dashboard/base

### 重现步骤

文档和演示站都有同样的问题

**Comment by uyarn** [comment]
截图看看你看到的效果呢 我看着是居中的 之前倒是遇到过类似的 可能是windows默认字体偏下导致的问题

**Comment by SingerLan** [comment]
![image](https://user-images.githubusercontent.com/44799711/236367363-04746fc7-9385-43b9-b2cf-baf97fe64cab.png)
把按钮高度调矮，很明显能看到文字偏下

**Comment by SingerLan** [comment]
1到2个像素左右，强迫症很难受

**Comment by SingerLan** [comment]
![image](https://user-images.githubusercontent.com/44799711/236367646-c9119d11-79ca-4ad6-9399-cb4e79c79b5b.png)
input 文字也是偏下

**Comment by uyarn** [comment]
大概率是系统默认字体中文行高的影响

**Comment by SingerLan** [comment]
为什么其它框架没有这个问题，只有这个框架会有

**Comment by PengYYYYY** [comment]
<img width="1333" alt="image" src="https://github.com/user-attachments/assets/37bd0050-c03f-4e71-9567-2e397aade9a3">

<img width="1332" alt="image" src="https://github.com/user-attachments/assets/e66fd9c9-47c0-45fe-a4c7-51f3640a0304">


垂直居中，表现符合预期
