### ISSUE TITLE
[Radio 单选框] 当设置v-if的时候出现问题

### ISSUE THREAD

**Issue by samchenws** [Tencent/tdesign-vue-next#2800]
### tdesign-vue-next 版本

 0.26.2

### 重现步骤

![image](https://user-images.githubusercontent.com/37535153/236262298-fb7a7653-ec35-408d-8732-3c2226dd86bf.png)
当设置v-show或者v-if时候选中样式会丢失

### 期望结果

当设置v-show或者v-if时候选中样式不会丢失

### 实际结果

当设置v-show或者v-if时候选中样式会丢失

**Comment by PengYYYYY** [comment]
描述的不是很清楚，另外这种写法看起来不太合理。个人感觉需要写个computed来计算radio的options。
