### ISSUE TITLE
[Collapse] 面板列表数据切换，header值更新但value值未更新

### ISSUE THREAD

**Issue by ananzhusen** [Tencent/tdesign-vue-next#2802]
### tdesign-vue-next 版本

tdesign-vue-next: 1.3.2

### 期望结果

![image](https://user-images.githubusercontent.com/48847159/236408211-91490638-cfbb-4031-943d-0a09c0f6b124.png)
![image](https://user-images.githubusercontent.com/48847159/236408332-357c76d1-ffcc-48c0-b77b-01ff9501f4de.png)
![image](https://user-images.githubusercontent.com/48847159/236408518-0c505d55-62d1-4af0-9f8b-04269e64f32c.png)

header更新了，change方法里面打印的value值未更新

**Comment by Aicmortal** [comment]
你的v-for没有配合:key使用,带上key就好了
https://vuejs.org/guide/essentials/list.html#maintaining-state-with-key

**Comment by ananzhusen** [comment]
明白了，谢谢
