### ISSUE TITLE
table组件代码演示

### ISSUE THREAD

**Issue by R-1018** [Tencent/tdesign-vue-next#2807]
### tdesign-vue-next 版本

1.3.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/Table#app

### 重现步骤

往下拉随便找一个table表格打开代码 会发现是jsx形式 而有些是<script setup> 

### 期望结果

我确实不会React 所以也不会很了解这些js里面写html的形式 但是要么都是jsx的要么就都是js 一部分是jsx 一部分是js 你让这些开发者怎么用 开源开源开源 就开出这么个东西嘛 别的组件都是有ts和js的语法演示 都说大厂卷 你们倒好 开出这么个玩意 还说工作量大 你倒是统一啊 什么玩意

### 补充说明

一线大厂做出来的组件效果很顶,但是细节方面我个人觉得确实有辱这份荣耀

**Comment by uyarn** [comment]
谢谢你的反馈 
首先，纠正一个问题，jsx 和 react 没有强绑定关系，它只是一个语法糖，是JavaScript 的一个的拓展，如果你打开vue的文档，里面也有相关介绍，我觉得学习是和代码打交道的人一直需要做的事情，多点技能没什么不好。
其次，任何功能的实现都可能增加维护成本，有的示例不是不想用template写，也可能是目前组件只实现了jsx的方式，如果你有具体的需求，可以另外提需求来反馈。
当然，示例方面我们会继续改进和完善，包括其他用户提到的js和ts两种都提供的事情，已经在和其他贡献者一起着手推进了。
最后，很多参与贡献的人都是业余时间参与的TDesign，他们都是出于对开源的热爱和对TDesign的坚持。所以请不要用“什么玩意” 这种词汇来评价参与贡献的人的贡献。我不知道你在其他地方是什么措辞，也和我们没有关系，但是礼貌交流是TDesign的社区最基本的要求。
