### ISSUE TITLE
[Upload] 开启拖拽上传点击上传按钮消失不见，并且无法点击拖拽区域进行上传文件

### ISSUE THREAD

**Issue by FEsujian** [Tencent/tdesign-vue-next#2808]
### tdesign-vue-next 版本

1.3.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/upload?tab=demo

### 重现步骤

![image](https://user-images.githubusercontent.com/33425635/236601761-a6e9b607-f9f4-4985-8868-5f90d7a5f383.png)
开启拖拽上传点击上传按钮消失不见，并且无法点击拖拽区域进行上传文件。

如果关闭拖拽上传，则只能点击按钮上传文件，但是

提示文字为：点击上方“选择文件”或将文件拖拽到此区域

### 期望结果

功能正常

**Comment by chaishi** [comment]
顶部的动态 demo 只是最简单的效果示例，可能缺少很多必要参数，复杂场景，建议参考下方实际的示例代码。
正常情况下，是有“重新选择”按钮的

<img width="380" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/127b77c5-0489-4f7d-8838-54f3cca6b7e7">
