### ISSUE TITLE
[Select] onBlur事件触发异常

### ISSUE THREAD

**Issue by 17683813062** [Tencent/tdesign-vue-next#2818]
### tdesign-vue-next 版本

1.0.5

### 重现步骤

多选状态，chang事件 每选中一个 会触发三次
blur事件也有点问题

### 期望结果

多选状态，chang事件 每选中一个 只触发一次

### 实际结果

多选状态，chang事件 每选中一个 触发三次

### 框架版本

Vue（3.2.13）

### 浏览器版本

Chrome（111.0.5563.147）

### 系统版本

window

### Node版本

14.5.0

**Comment by uyarn** [comment]
多选的问题 升级解决下 已经修复了 看下CHANGELOG
