### ISSUE TITLE
[dialog] `destroy`销毁dialog方法，并未完全销毁实例

### ISSUE THREAD

**Issue by RSS1102** [Tencent/tdesign-vue-next#2826]
### tdesign-vue-next 版本

^1.3.2

### 重现链接

https://github.com/RSS1102/td-vue-next-demo/blob/main/src/components/Dialog/destroy.vue

### 重现步骤

1. 创建弹窗
2. 执行`销毁弹窗`
3. 使用`show()`方法，仍然可以打印出实例（dom元素已经被移除）

### 框架版本

"vue": "^3.2.47"

### 浏览器版本

112.0.5615.138

### 系统版本

win11

### Node版本

v18.6.0

**Comment by uyarn** [comment]
instanceDialogPluginOne = null
