### ISSUE TITLE
[table] 表格增加template方式

### ISSUE THREAD

**Issue by jiaxa** [Tencent/tdesign-vue-next#2830]
### 这个功能解决了什么问题

table表格现在全都是js的方式，能不能增加template的方式

### 你建议的方案是什么

表格增加template方式

**Comment by chaishi** [comment]
再看下文档，支持 template 的方式。`colKey` 的值就是 template 插槽的名称

**Comment by jiaxa** [comment]
好的，我再看看，确认下文档

**Comment by jiaxa** [comment]
是需要先设置columns，然后才能使用template 的方式，能不能优化一下，不设置columns，就可以使用template 的方式呢

**Comment by jiaxa** [comment]
@chaishi
