### ISSUE TITLE
select

### ISSUE THREAD

**Issue by shanliangdeYWJ** [Tencent/tdesign-vue-next#2837]
### 这个功能解决了什么问题

下拉菜单希望可以类似于element-ui一样【增加】

在可输入的情况下，鼠标点击框会聚焦打开下拉菜单，再次点击会取消聚焦收起下拉菜单

详情对比
https://element.eleme.cn/#/zh-CN/component/select#ke-sou-suo
https://tdesign.tencent.com/vue-next/components/select?tab=demo#可过滤的选择器

### 你建议的方案是什么

我的建议是增加这个功能，在用户鼠标点击多选选择或者不选的情况下她可以再次点击【不用移动鼠标】【点击外部再取消】

**Comment by PengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/assets/35833812/567763fc-04d3-406c-8507-ae1192f5213e

是这个表现吧
