### ISSUE TITLE
[docs官网] 在暗黑模式下不能正确打开code

### ISSUE THREAD

**Issue by RSS1102** [Tencent/tdesign-vue-next#2846]
### tdesign-vue-next 版本

^1.3.3

### 重现链接

https://tdesign.tencent.com/vue-next/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

1. 打开[官网](https://tdesign.tencent.com/vue-next/components/table#%E5%8F%AF%E7%BC%96%E8%BE%91%E7%9A%84%E8%A1%A8%E6%A0%BC)
2. 设置暗黑模式
3. 刷新浏览器
4. 打开code区域
![1684141569550](https://github.com/Tencent/tdesign-vue-next/assets/81673017/d3cf387e-9e2c-4903-b0c1-ffa645029504)

### 期望结果

正确打开code区域

### 实际结果

无响应

### 框架版本

*

### 浏览器版本

112.0.5615.138

### 系统版本

win11

### Node版本

*

**Comment by uyarn** [comment]
fixed
