### ISSUE TITLE
[Table] 设置了dragSort属性并执行drag操作之后，列表无法正确显示新添加的行数据

### ISSUE THREAD

**Issue by Stormpass** [Tencent/tdesign-vue-next#2847]
### tdesign-vue-next 版本

1.3.0

### 重现链接

https://stackblitz.com/edit/btdwa7?file=package.json,src%2Fdemo.vue

### 重现步骤

我搜索过issue列表，确定在现有issue中无法找到答案。
1. 设置dragSort属性为 row-handler
2. 列表中初始化 多条数据（几条都可以）
3. 此时往表格的数据中添加（push）一条数据

![image](https://github.com/Tencent/tdesign-vue-next/assets/31079748/e2162973-5d58-4645-bc9b-420afc3d7d30)

### 期望结果

新数据预期出现在表格最下部

### 实际结果

数据出现在表格的列表最上部
![image](https://github.com/Tencent/tdesign-vue-next/assets/31079748/cd447b0a-559d-43e5-bb86-6a5e66079c61)

### 框架版本

3.2.47

### 浏览器版本

any

### 系统版本

window10

### Node版本

18.14.0

### 补充说明

链接中的例子取自官网文档中的例子。
https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E7%A4%BA%E4%BE%8B%E4%BA%8C%EF%BC%9A%E6%9C%89%E6%89%8B%E6%9F%84%E5%88%97%E7%9A%84%E8%A1%8C%E6%8B%96%E6%8B%BD%E6%8E%92%E5%BA%8F

**Comment by Stormpass** [comment]
已知的hack方案是通过给 data重新赋值
```js
data = [...data]
```
触发table组件中的watch，重新 sort；
但此时页面会闪，元素首先出现在顶部，接着马上被移动到尾部

**Comment by jesseice** [comment]
还没修复吗 这个 现在都1.5了

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/3822 temprary
