### ISSUE TITLE
[TSelectPanel]  attributes (size) were passed to component

### ISSUE THREAD

**Issue by aoeiuvv** [Tencent/tdesign-vue-next#2849]
### tdesign-vue-next 版本

1.3.3

### 实际结果

[Vue warn]: Extraneous non-props attributes (size) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <TSelectPanel ref=Ref< null > size="medium" multiple=false  ... > 
  at <BaseTransition onEnter=fn onAfterLeave=fn<destroyPopper> appear=true  ... > 
  at <Transition name="t-popup--animation" appear=true onEnter=fn<updatePopper>  ... > 
  at <TPopupContent onResize=fn<emitResize> onVnodeMounted=fn<onVnodeMounted> > 
  at <TPopupContainer ref=fn<re

### 浏览器版本

edge

### 系统版本

windows11

**Comment by aoeiuvv** [comment]
您的来信已收到，我会尽快查收并回复 谢谢

**Comment by uyarn** [comment]
这个问题修复了 你应该是之前的版本 确认升级到1.3.3

**Comment by aoeiuvv** [comment]
> 这个问题修复了 你应该是之前的版本 确认升级到1.3.3

确认是我这里没升级，打扰了
