### ISSUE TITLE
[Dialog] 对话框中，表单验证后会出现滚动条

### ISSUE THREAD

**Issue by beerui** [Tencent/tdesign-vue-next#2856]
### tdesign-vue-next 版本

1.3.3

### 重现链接

https://stackblitz.com/edit/ie5pcu?file=package.json,src%2Fdemo.vue

### 重现步骤

1. 点击按钮弹出对话框
2. 点击确认按钮进行表单验证
3. 出现滚动条

### 期望结果

不出现滚动条

### 实际结果

出现了不在预期内的滚动条

### 框架版本

3.2.47

### 浏览器版本

113.0.5672.93（正式版本） （64 位）

### 系统版本

Window11

### Node版本

14.18.0

**Comment by beerui** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/95088750/1b0d3eb0-dce7-47cd-868c-9034cf42fbc7)
应该是这里绝对定位影响到了

**Comment by uyarn** [comment]
extra不占空间 就是要用绝对定位 这种场景如果有需要 可以自己覆盖下样式处理吧

**Comment by beerui** [comment]
自己写死高度在那也行，感觉处理方式不够优雅

**Comment by uyarn** [comment]
或者你可以在这个场景下 自己改掉extra的相对定位.. extra目前是设计得不占位的
