### ISSUE TITLE
[Table] vue3 vite 项目 使用 columns 里面的 jsx 语法报错

### ISSUE THREAD

**Issue by 17683813062** [Tencent/tdesign-vue-next#2857]
### tdesign-vue-next 版本

1.3.3

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/640840ec-8f63-4ad0-aeaf-d929bd1b354a)
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/f5154b75-22a6-46ba-8725-c687e6800432)
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/7dd5087b-a52d-4726-83bc-b53ee10eb543)
  cell: (h) => {
      return (
      <span>
        <MoveIcon />
      </span>
    )
    }, 
使用这种语法报错

### 期望结果

项目中直接使用这种写法，项目能正常使用

### 实际结果

项目中直接使用这种写法，编辑器报错，项目不能正常运行

### 框架版本

Vue（3.2.47）

### 浏览器版本

Chrome（112.0.5615.121）

### 系统版本

window

### Node版本

18.12.0

**Comment by chaishi** [comment]
<script lang=“jsx”/> 写了吗？`lang=“jsx”`

TS 的话或者 lang=“tsx"

**Comment by 17683813062** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/1555b017-ae24-46f7-90c9-cd60dbf14d55)

**Comment by 17683813062** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/ee8465e7-e685-4916-861c-ab978b8fd30d)
修改了一下，好像是不能多script 标签。然后出现新报错，

**Comment by 17683813062** [comment]
![7AEC9017-5810-40e5-85BF-A5687325D207](https://github.com/Tencent/tdesign-vue-next/assets/56809137/362fce97-ef7d-4f09-8d0f-90b5ae2f0f27)
这样配置后，终于可以了，项目成功运行了，建议在官网把配置教程写清楚

**Comment by 17683813062** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/38b05a90-3d92-4e30-b6b7-1b40ebca2c94)
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/4464668d-b4a6-4880-bbcd-c6e0ae800845)
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/ad8b323d-9289-4664-85df-f7a7c8a5d178)
后面出现的问题是：这种写法，这个 组件好像没有解析出来

**Comment by PengYYYYY** [comment]
https://tdesign.tencent.com/vue-next/components/table 看一下这个demo？你这个图不全，无法排查问题。
