### ISSUE TITLE
在Typescript中使用时所有组件的类型全为 any 类型

### ISSUE THREAD

**Issue by 8023shin** [Tencent/tdesign-vue-next#2865]
vue 版本 3.2.47 tdesign-vue-next 版本 1.3.3 tscofig 中已引入类型文件，任意一个组件类型文件 ts 检查有报错，显示"泛型类型 ComponentOptionsBase"需要介于 8 和 12 类型参数之间

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by uyarn** [comment]
报错截图看看呢

**Comment by 8023shin** [comment]
![IMG_1125](https://github.com/Tencent/tdesign-vue-next/assets/25003693/cd257947-4e6b-45b9-a1d7-2031b801bbcc)
![IMG_1124](https://github.com/Tencent/tdesign-vue-next/assets/25003693/58a19ec1-9c11-42f3-af67-4af58b0974f4)
内网环境不方便截图，只能拍照

**Comment by uyarn** [comment]
找了个新项目试了下没复现 ts是什么版本？tsconfig也发一下看看

**Comment by boogie-ben** [comment]
本月出现了相同的问题，所有的组件类型变成了any

**Comment by boogie-ben** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/29250685/50103a0a-edc4-46ca-ac34-5818025e5d7a)

本月出现了相同的问题，所有组件类型皆为any，即使在组件的index.d.ts文件中的导出类型也是any

**Comment by boogie-ben** [comment]
经过验证发现是1.3.3版本后出现的问题

**Comment by boogie-ben** [comment]
vue版本升级到3.3后，该问题消失了
