### ISSUE TITLE
[Bug][Table] maxHeight属性传字符串时不起作用、传数字时效果与height一样

### ISSUE THREAD

**Issue by litao36253** [Tencent/tdesign-vue-next#287]
![1643854620(1)](https://user-images.githubusercontent.com/22752122/152292493-100f625e-c017-488f-aa59-a21aafffc28b.jpg)

**Comment by pengYYYYY** [comment]
已收到

**Comment by pengYYYYY** [comment]
https://stackblitz.com/edit/angular-rubopu?file=src%2Fdemo.vue

**Comment by pengYYYYY** [comment]
测试并没有撑高，版本0.8.1
