### ISSUE TITLE
[t-cascader] 建议增加只显示前 n 级，屏蔽后面级别的功能

### ISSUE THREAD

**Issue by vikyd** [Tencent/tdesign-vue-next#2870]
### tdesign-vue-next 版本

1.3.4

### 期望结果

假设 tree 有 3 级，省、市、县。

有时需同时显示 省、市、县。
有时只想显示 省、市，不显示 县。

且不想改动 tree 结构。

若组件能提供一个开放层级的选项会很好，例如 `depth="2"`

**Comment by PengYYYYY** [comment]
这种需求自己处理一下原数据就好了
