### ISSUE TITLE
[table] 开启 ellipsis 时，popup 的箭头歪了

### ISSUE THREAD

**Issue by Lyan-u** [Tencent/tdesign-vue-next#2874]
### tdesign-vue-next 版本

1.3.4

### 重现步骤

<img width="1094" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/46185702/f7a67819-136d-4ca1-b176-408416f5d111">

### 期望结果

<img width="906" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/46185702/244d8933-30f1-491c-8a5e-a01e6aa346b2">

**Comment by uyarn** [comment]
问题已经修复了 1.3.4的小缺陷  可以暂时用`tdesign-vue-next@1.3.5-alpha.1`这个包
