### ISSUE TITLE
[Select]上下键选择选项不会跳过过滤项且无法Enter选择

### ISSUE THREAD

**Issue by adminqe** [Tencent/tdesign-vue-next#2877]
### 重现链接
https://tdesign.tencent.com/vue-next/components/select#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤
筛选后上下键选择选项时，被过滤掉的选项不会被跳过，不是预期的选择行为

### 期望结果
跳过被过滤掉的选项，并且支持Enter选择选项

| Environment | Info |
|---|---|
| 相关版本 | 1.3.4 |
| 框架版本 / 基础库版本 | vue3.2 |
| 系统、浏览器 | Macos |
| Node版本 |  |

**Comment by uyarn** [comment]
fixed in 1.3.7
