### ISSUE TITLE
[Bug][Table] 默认导出的 PrimaryTable 类型为 any，使用 t-table 组件时无法获得友好的类型检查和代码提示

### ISSUE THREAD

**Issue by litao36253** [Tencent/tdesign-vue-next#288]
![image](https://user-images.githubusercontent.com/22752122/152300171-527c9b72-3f0a-42b8-8d75-f408cee81871.png)

**Comment by pengYYYYY** [comment]
当前导出方式使用了 mapProps 用于 _PrimaryTable，后面这部分会进行重构

**Comment by pengYYYYY** [comment]
跟随这个PR处理 https://github.com/Tencent/tdesign-vue-next/pull/468

**Comment by pengYYYYY** [comment]
0.12.0 已修复
