### ISSUE TITLE
[t-upload]主题为theme="image"时候，如何使用fileListDisplay自定义已上传文件列表

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#2883]
### tdesign-vue-next 版本

1.3.4

### 重现链接

https://stackblitz.com/edit/rwvkce-eekfyu?file=package.json,src%2Fdemo.vue

### 重现步骤

目前设置组件theme="image"时候，插槽fileListDisplay不生效

**Comment by chaishi** [comment]
1. 确保你正在使用的组件版本号是 2023-07-12 发布的 `v1.3.11` 以后的版本，变更日志查询地址：https://tdesign.tencent.com/vue-next/changelog
2. 参考示例代码：https://stackblitz.com/edit/a6925z?file=package.json,src%2Fdemo.vue

文档说明
<img width="943" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/68443523-ccca-4b30-985f-cebec42b56d0">
