### ISSUE TITLE
[Dialog] 打开或关闭弹窗报错

### ISSUE THREAD

**Issue by 17683813062** [Tencent/tdesign-vue-next#2885]
### tdesign-vue-next 版本

1.3.3

### 重现步骤

1. 点击按钮打开弹窗，打不开，直接报错：caught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
 2. 弹窗默认打开，点击关闭，报错：caught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
 
 

### 期望结果

不知道为什么报错，之前都是好的。

### 实际结果

报错

### 框架版本

Vue(3.2.47)

### 浏览器版本

Chrome(112.0.5615.121)

### 系统版本

window

### Node版本

18.12.0

**Comment by 17683813062** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/176a99b5-7aa2-48d7-b44d-4fd59890fd6c)

**Comment by nined9** [comment]
> ![image](https://user-images.githubusercontent.com/56809137/240212989-176a99b5-7aa2-48d7-b44d-4fd59890fd6c.png)

试了下，没啥问题啊。https://stackblitz.com/edit/ax6jhm?file=package.json,src%2Fdemo.vue

**Comment by PengYYYYY** [comment]
> ![image](https://user-images.githubusercontent.com/56809137/240212989-176a99b5-7aa2-48d7-b44d-4fd59890fd6c.png)

什么版本的啊
