### ISSUE TITLE
[Bug][Menu] t-head-menu logo插槽放文字显示不出

### ISSUE THREAD

**Issue by QuantumzzZ** [Tencent/tdesign-vue-next#289]
#### 版本 0.8.0 环境vite 2.7.2 vue 3.2.25 全量引入
![QQ截图20220208205658](https://user-images.githubusercontent.com/62553709/152991469-4da90e75-70fc-4108-b753-d4dff59265df.png)
![QQ截图20220208205705](https://user-images.githubusercontent.com/62553709/152991476-a7e7f298-bbcc-4082-914f-8fd64ecdf404.png)

**Comment by pengYYYYY** [comment]
这边是因为加了这个属性font-size: 0，后续会处理

**Comment by pengYYYYY** [comment]
0.8.1 已修复
