### ISSUE TITLE
input-number值在改变的时候赋值存在异常情况

### ISSUE THREAD

**Issue by JobinJia** [Tencent/tdesign-vue-next#2900]
### 重现链接
https://stackblitz.com/edit/vitejs-vite-2vjngr?file=src%2Fmain.ts,src%2FApp.vue

### 重现步骤
1： 删除值，在为空值的时候 model中的key丢失。失焦时，model.num的值变为"" 空串
2： 输入`1eee` 之后删除一个字符e. 此时model.num的值变为null, 视图变成NaN,无法再通过删除键删除

### 期望结果
1：删除值为空时为null, 失焦为null
2:  删除非数值字符时不触发v-model的改变（在只考虑10进制，不考虑其它进制的情况下）

### 实际结果
见重现链接

| Environment | Info |
|---|---|
| 相关版本 | 1.3.4 |
| 框架版本 / 基础库版本 | Vue(3.3.4) |
| 系统、浏览器 | Chrome 113.0.5672.127（正式版本） （64 位） |
| Node版本 |  |

**Comment by RSS1102** [comment]
当`InputNumber`的输入框为空时，被修改为了`undefined`
![image](https://github.com/Tencent/tdesign-vue-next/assets/81673017/4cc2017f-d49b-4b9b-b995-11c1b20a237b)

**Comment by chaishi** [comment]
数值为空，应当保持为 `undefined`，而非 `null`。
上述问题，应当属于，输入内容校验遗漏，应该处理的方式为：不允许输入非法数字。`1eee` 已经属于非法数字

**Comment by xixileng** [comment]
> <img alt="image" width="158" src="https://user-images.githubusercontent.com/11605702/254575737-279ab77b-5983-49b9-b1d6-0278c535fb3f.png">
> 我其实不太明白，为什么会期望空值是 `null`，明明 null 的类型是 object。 在某一天，某一处的代码要进行类型判断的时候，不会有坑么？

undefined 代表不存在或者未定义，空值就应该用 null，而 typeof null 这个属于 JS 语言的 “feature”，开发者本就不能用 typeof 判断 null。
