### ISSUE TITLE
[colorpicker] selectInputProps添加popupProps透传

### ISSUE THREAD

**Issue by docodocool** [Tencent/tdesign-vue-next#2904]
### 这个功能解决了什么问题

selectInputProps无法传递selectInputProps.popupProps的属性, 被覆盖了
<img width="673" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/23123540/34b43e2d-9210-4fdf-b6f8-828c175ecaf2">
使用clickoutside时会把选择颜色格式判定为在panel外点击

### 你建议的方案是什么

在popupProps中加入selectInputProps传入的参数, 修改为
```
popupProps={{
    ...selectInputProps.popupProps,
    overlayClassName: `${baseClassName}__select-options`,
}}
```
这样可以在panel处理selectPopup的属性

**Comment by uyarn** [comment]
PR is welcome
