### ISSUE TITLE
[ Checkbox, TagInput ] 组件的value能否支持object 

### ISSUE THREAD

**Issue by yuerzm** [Tencent/tdesign-vue-next#2905]
### 这个功能解决了什么问题

Checkbox, Tag, TagInput 这三个组件的使用 展示的数据和控制业务需要的数据存在差异, 例如展示的是业务对象名称, 实际控制的是业务对象id

### 你建议的方案是什么

value model 支持 object类型, 通过 keys 来控制原生组件的 label 和 value

**Comment by PengYYYYY** [comment]
TagInput 只是作为一个基础组件来提供上层组件的定义。可以使用select来代替。
