### ISSUE TITLE
[Upload] multiple=false时, max=1的表现问题

### ISSUE THREAD

**Issue by wc19950724** [Tencent/tdesign-vue-next#2909]
### tdesign-vue-next 版本

1.3.4

### 重现链接

https://stackblitz.com/edit/qrn372?file=src%2Fdemo.vue

### 重现步骤

当设置单文件上传时, 如果max=1，重新选择文件不会更新成新文件名，并且不会触发change事件

### 期望结果

触发change事件，更新文件名
or
补充文档说明, 单文件时无需设置max=1

### 实际结果

文件名不更新 & change事件不触发

**Comment by chaishi** [comment]
multiple = true 时，max 有效

**Comment by wc19950724** [comment]
> multiple = true 时，max 有效

如果multiple = false & max = 2
只要max !== 1 都可正常触发change和更新文件名
请尽可能的消除这种情况或在文档注明该互斥情况

**Comment by chaishi** [comment]
1. 文档已更新说明
2. 代码中已兼容 `multiple=false,max=1` 的情况，最新代码可以触发 change 事件，并更新文件
resolved in https://github.com/Tencent/tdesign-vue-next/pull/3566

**Comment by chaishi** [comment]
resolved at `v1.6.8` 2023-11-07
