### ISSUE TITLE
[Link] 使用 vue router 的方式进行跳转

### ISSUE THREAD

**Issue by Cat1007** [Tencent/tdesign-vue-next#2916]
### 这个功能解决了什么问题

当单页应用希望通过link提供可以右键新tab打开，或者左键进行router跳转不重载页面时，需要该功能。目前传入href会直接重载页面的进行跳转

### 你建议的方案是什么

提供类似to的属性，在需要进行router跳转时，用一致的ui风格展示链接

**Comment by Cat1007** [comment]
https://tdesign.tencent.com/vue-next/components/menu?tab=api#menuitem-props

**Comment by PengYYYYY** [comment]
使用 target api应该可以满足你的要求吧

**Comment by PengYYYYY** [comment]
这个组件本质上就是一个a标签
