### ISSUE TITLE
[table] JSX相关配置报错问题

### ISSUE THREAD

**Issue by Wesleyyy0808** [Tencent/tdesign-vue-next#2922]
### tdesign-vue-next 版本

1.3.5

### 报错内容
TypeError: Cannot read properties of null (reading 'content')
[vue/compiler-sfc] This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript".

**Comment by Wesleyyy0808** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/6204cb74-4ecf-450a-ba31-0d768c320884)
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/ff6112a8-b050-423e-b45b-9b74869aefae)
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/b9c1ce57-86df-47a6-be14-c9ac3bd83183)
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/b28298a7-7a24-4b4e-a6c0-5f4bde3d622c)
相关内容截图如上，代码是文档demo copy下来的，
如果给setup加上lang="jsx"效果是如下图
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/d58be035-9290-4425-a3ef-c5198dfd84ed)
相关依赖已安装如下
<img width="1261" alt="9eee8674fcd8955265925b054a12f35" src="https://github.com/Tencent/tdesign-vue-next/assets/69622989/66f05ca8-6b53-4306-a716-d6c3fcb72c61">

**Comment by Wesleyyy0808** [comment]
网上说的配置问题试过都不行。但是另一个项目jsx语法是支持的，我尝试把那个项目配置复制到这个项目中，结果仍旧不能用。

**Comment by chaishi** [comment]
看上去是一个通用问题，别的任意组件应该也有类似的问题。

不属于 table 这一个组件的问题，是么？

**Comment by Wesleyyy0808** [comment]
@chaishi  我没有尝试其他组件，我只是在使用table的示例代码【带合并单元格的表格
】出现了问题，错误指向了jsx的错误，但我已经开启/配置了相关选项，不知道是不是配置与问题还是babel新版的的问题？
另外我是用@vue/cli创建的项目。

**Comment by Wesleyyy0808** [comment]
但是奇怪的是如果给两个script标签都加上lang="jsx"去编译就没有问题了。
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/b4fc22b4-f3f4-437a-9cc6-bbfaada28ea3)
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/ecccc5ea-eb0d-4d35-849b-e405bc7955d8)

**Comment by Wesleyyy0808** [comment]
之前看到一个issue提到了demo可以给出多种语法，希望团队可以考虑一下

**Comment by PengYYYYY** [comment]
要使用 `jsx` 语法的话，必须要在 `script` 上面加 `lang="jsx"`
