### ISSUE TITLE
[t-input-adornment] append 和 prepend 属性设置 template 无效

### ISSUE THREAD

**Issue by c1ngular** [Tencent/tdesign-vue-next#2926]
### tdesign-vue-next 版本

1.3.5

### 重现步骤

`        <t-input-adornment>
          <template #prepend>
            <t-select autoWidth placeholder="aaaa">
              <t-option ... />
            </t-select>
          </template>
          <t-input placeholder="blabla"/>
          <template #append>
            <t-button variant="outline">
              <template #icon><t-icon name="download"></t-icon></template>
              测试
            </t-button>
          </template>
        </t-input-adornment>`

### 期望结果

append 和 prepend 属性 template方式设置可以显示

### 实际结果

append 和 prepend 属性 template方式设置无效不显示

### 框架版本

3.2.37

### Node版本

20.1.0

**Comment by Hiram-Wong** [comment]
同问题，1.35 版本有此问题，1.34 没有此问题

**Comment by superextend** [comment]
<t-input-adornment prepend="任意字符"><template #prepend><t-select  auto-Width  v-model="field" :options="options"></t-select></template></t-input-adornment> 这样才有效
