### ISSUE TITLE
[image-viewer] 能否增加按下ESC时是否触发对话框关闭事件，Upload theme="image"时可透传ImageViewer全部属性

### ISSUE THREAD

**Issue by Likunone** [Tencent/tdesign-vue-next#2928]
### 这个功能解决了什么问题

https://github.com/Tencent/tdesign-vue-next/issues/2704

### 你建议的方案是什么

ImageViewer 增加closeOnEscKeydown，Upload 可透传ImageViewer全部属性

**Comment by chaishi** [comment]
- feat(ImageViewer): 新增支持 `closeOnEscKeydown`，用于控制是否允许 ESC 退出预览
- feat(Upload): 图片预览功能，新增支持透传图片预览全部属性 `imageViewerProps`

resolved in https://github.com/Tencent/tdesign-vue-next/pull/3566

**Comment by chaishi** [comment]
resolved at `v1.6.8` 2023-11-07
