### ISSUE TITLE
🏗️ TDesign Vue Mono Repo

### ISSUE THREAD

**Issue by LeeJim** [Tencent/tdesign-vue-next#2934]
# TLDR

在 VueNext 仓库兼容 Vue 2.7 版本，通过工程构建两个 NPM 产物，分别支持 2.7 和 3.x。

# 进展

- 打包构建工程
    - [x] tsconfig 配置
    - [x] babel 配置
- 组件代码兼容转换
    - [x] 多根节点支持
    - [x] getCurrentInstance 兼容
    - [x] Teleport兼容

**Comment by uyarn** [comment]
本周发布基于 tdesign-vue仓库发布的支持2.7使用的版本tdesign-vue@naruto 
在VueNext仓库兼容工程生成之前 vue2.7支持的版本每周都跟vue2迭代同步发布

**Comment by uyarn** [comment]
本周WXG的MISUI也发布了基于naruto的MISUI@naruto版本

**Comment by uyarn** [comment]
仓库及进展 https://github.com/TDesignOteam/tdesign-vue-integrate

**Comment by uyarn** [comment]
仓库monorepo分支 [/feature/monorepo](https://github.com/Tencent/tdesign-vue-next/tree/feature/monorepo)
