### ISSUE TITLE
[Select] t-option value="" 时无法选中

### ISSUE THREAD

**Issue by wc19950724** [Tencent/tdesign-vue-next#2937]
### tdesign-vue-next 版本

1.3.5

### 重现链接

https://stackblitz.com/edit/qrn372-khka8j?file=src%2Fdemo.vue

### 重现步骤

当初始值设置为 '' 空字符串时, 不会默认选中 value=''的option
并且无法选择 value=''的option
已测试为 1.3.3版本出现的此问题~
[#2678](https://github.com/Tencent/tdesign-vue-next/pull/2678/files#diff-35e9793f25936edb7fb2fe850247100246c887acd2da42fe1c4980aadfadf1d7)

### 期望结果

可以默认选中

**Comment by uyarn** [comment]
fixed in 1.3.7
