### ISSUE TITLE
在Nuxt3中使用，一直报Unknown file extension ".css" 

### ISSUE THREAD

**Issue by wulianpu** [Tencent/tdesign-vue-next#2941]
复现链接：https://codesandbox.io/s/pensive-snyder-s57xt4?file=/app.vue
<img width="1370" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/44516614/133ce671-ad0c-4edb-bed4-0650100f3606">

**Comment by PengYYYYY** [comment]
参考一下这个吧https://github.com/yixiaco/tdesign-vue-next-nuxt-starter

**Comment by RayJason** [comment]
参考：https://github.com/nuxt/nuxt/issues/15321#issuecomment-1489039998
解决方案是在 nuxt.config.ts 中配置:
```ts
build: {
  transpile: ['tdesign-vue-next'],
},
```
