### ISSUE TITLE
[t-table] 桌面版 Vue Next 版本1.3.5 表格列从多变少后，表格的宽度没有变化

### ISSUE THREAD

**Issue by gaofenfei** [Tencent/tdesign-vue-next#2951]
### tdesign 版本

1.3.5

### 重现步骤

表格列动态变化，当表格列从多变少后，表格的整体宽度还是变化前的宽度，只是剩余的列均分了原来的宽度，不美观。尝试使用实例的refreshTable方法，无效。

### 期望结果

当显示列变少时，表格宽度也要变小，或者修复refreshTable可以重新渲染。

### 实际结果

当显示列变少时，表格的宽度没有变化，还是变化之前的宽度。 实例的refreshTable无效。

### 浏览器版本

Chrome 113.0.5672.129

### 系统版本

windows 11

### 补充说明

我们没有使用脚手架开发，直接浏览器引用的最新版本（1.3.5）的Tdesign，Vue Next

**Comment by chaishi** [comment]
因为表格宽度设置了 width: 100%。如果你希望有多少列，就多宽，请尝试去除 width: 100% 这个 CSS 属性。

表格的宽度，是 HTML CSS 原生属性样式，你期望是什么样，就设置对应的宽度属性即可，组件本身不会做过多限制。

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/3007
