### ISSUE TITLE
[InputNumber] 如果设置了精度，无法清空输入框

### ISSUE THREAD

**Issue by git-lt** [Tencent/tdesign-vue-next#2956]
### tdesign-vue-next 版本

1.3.6

### 重现链接

https://tdesign.tencent.com/vue-next/components/input-number

### 重现步骤

官方文档 【 带小数的数字输入框 】 示例，无法清空输入框，之前的版本可以，现在的版本不行了，如果值是空，会自动显示为0，且无法清空数值，不确定是不是bug，还是有意这样设计

### 期望结果

可以清空

### 实际结果

无法清空

**Comment by uyarn** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/2948
