### ISSUE TITLE
[Select] 使用options时，option对象存在"tagName"属性时，控制台有警告⚠️

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#2971]
### tdesign-vue-next 版本

1.3.6

### 重现链接

https://stackblitz.com/edit/xszr1y?file=package.json,src%2Fdemo.vue

### 重现步骤

```vue
<template>
  <t-select
    v-model="value1"
    :options="options1"
    placeholder="请选择云解决方案"
    :keys="{ value: 'tagName', label: 'tagName' }"
  ></t-select>
</template>
<script setup lang="jsx">
import { ref } from 'vue';
const options1 = [
  {
    id: '1646496442754478082',
    tagName: '3333333',
  },
  {
    id: '1666248731568312322',
    tagName: '超管可见标签',
  },
];
const value1 = ref('');
</script>

```

### 期望结果

控制台无警告

### 实际结果

控制台有警告

### 补充说明

<img width="1055" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/54022918/ffbcd9d7-6187-408e-acc0-dd0ff1ba339f">

**Comment by PengYYYYY** [comment]
你这里 `keys`应该设置为 `{ value: 'id', label: 'tagName' }`

**Comment by sunjiesama** [comment]
猜测应该是组件内部把`tagName `作为属性作用到标签上了，但是tagName这个属性又是由标签派生的，是只读的

**Comment by uyarn** [comment]
> 猜测应该是组件内部把`tagName `作为属性作用到标签上了，但是tagName这个属性又是由标签派生的，是只读的

you're right

**Comment by PengYYYYY** [comment]
> 请问你试了吗？请教两个问题。
> 
> 1. 为什么不可以用tagName作为value
> 2. keys应该设置为 { value: 'id', label: 'tagName' }依然会有警告

看到你这个 `keys` 设置不对，`issue` 关的有些唐突了，感谢反馈。
