### ISSUE TITLE
[Table] loading 自定义显示有问题

### ISSUE THREAD

**Issue by Liusiyuan-git** [Tencent/tdesign-vue-next#2972]
### tdesign-vue 版本

tdesign-vue-next: "0.21.1",

### 重现步骤

很简单的，随便拿个table，配置上 loading=true，然后，在下面配置自定义loading的slot，例如：
<img width="616" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/52623941/c53a56d5-f760-4dee-a7e6-fb24f8e32fa9">

然后你就能看到如下bug了：
<img width="652" alt="image" src="https://github.com/Tencent/tdesign-vue/assets/52623941/66142335-6004-4745-bda2-528c95aec66f">

### 期望结果

配置了自定义的loading的slot之后，原来的loading图标应该被自定义的替代掉才对，而不是两个同时出现。

**Comment by uyarn** [comment]
新版本已经修复了 https://stackblitz.com/edit/gwodz6?file=package.json,src%2Fdemo.vue 升级到1.x的版本吧 1.x是 LTS 版本
