### ISSUE TITLE
ImageViewer 图片预览 补充一个内容插槽

### ISSUE THREAD

**Issue by rjl-cli** [Tencent/tdesign-vue-next#2975]
### 这个功能解决了什么问题

有些情况资源可能不只是图片或者可能会需要自定义一些预览功能
所以希望如下位置新加22个插槽可以自定义
![image](https://github.com/Tencent/tdesign-vue-next/assets/111716113/e3c161cb-80ff-4934-b614-6e0a88afe5ab)

### 你建议的方案是什么

新加两个插槽

**Comment by rjl-cli** [comment]
就是加一个当前预览的插槽
![image](https://github.com/Tencent/tdesign-vue-next/assets/111716113/abeed07a-20e6-438d-9ba4-15a7d6d63990)

**Comment by chaishi** [comment]
经过再次思考，如果每一部分都自定义的话，那和自己实现 预览功能，似乎没有区别。方便描述一下具体需求么
