### ISSUE TITLE
[Select] 多选选项没有选中态的禁用

### ISSUE THREAD

**Issue by rexlily** [Tencent/tdesign-vue-next#2983]
### tdesign-vue-next 版本

1.3.7

### 重现步骤

```vue
<template>
  <t-select
    v-model="value1"
    :options="options1"
    placeholder="请选择云解决方案"
    multiple
  ></t-select>
</template>
<script setup lang="jsx">
import { ref } from 'vue';

const options1 = [
  { label: '架构云', value: '1', title: '架构云选项' },
  { label: '大数据', value: '2' },
  { label: '区块链', value: '3' },
  { label: '物联网', value: '4', disabled: true },
  { label: '人工智能', value: '5' },
];

const value1 = ref(['4']);
</script>
``` 

### 期望结果

可以禁止取消选中

**Comment by kaishuige** [comment]
请问这种情况的处理方式 是整个禁止选择吗？

**Comment by uyarn** [comment]
> 请问这种情况的处理方式 是整个禁止选择吗？还是别的处理方式呢？

我理解就是这个选项已经选中的时候不允许取消选中 没有选中的时候不选中 全选的时候不包括

**Comment by rexlily** [comment]
<img width="339" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/31459705/1a742447-007e-439b-afa8-3bbf323ca7a6">
这里的标签是否应该也不能删除

**Comment by uyarn** [comment]
> <img alt="image" width="339" src="https://user-images.githubusercontent.com/31459705/253510431-1a742447-007e-439b-afa8-3bbf323ca7a6.png"> 这里的标签是否应该也不能删除

确实还是遗漏了这个逻辑 我修复下

**Comment by rexlily** [comment]
还有分组单选/多选这里的逻辑
