### ISSUE TITLE
[header-menu]无法通过自己的定义css实现header flex布局右置

### ISSUE THREAD

**Issue by wintsa123** [Tencent/tdesign-vue-next#2988]
### tdesign-vue-next 版本

1.3.7

### 重现链接

.t-head-menu__inner .t-menu{   justify-content:space-evenly }

### 重现步骤

就算加！important也不行，新手想问一下为什么
.t-head-menu__inner .t-menu{
  justify-content:space-evenly
}

**Comment by uyarn** [comment]
@xiaosansiji 看看这个问题

**Comment by wintsa123** [comment]
谢谢，已经好了
