### ISSUE TITLE
有哪位大老有tdesign-vue-next的表单生成器呀？

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#2989]
### 这个功能解决了什么问题

想要一个表单生成器，基于tdesign-vue-next ts版本的，后端程序员被逼的，没办法了^_^

### 你建议的方案是什么

支持表格校验、自定义嵌套、样式，可拖拽生成表单即可，就像它吧https://xrender.fun/

**Comment by NWYLZW** [comment]
或许你可以等我写完 [react](https://github.com/zodui/zodui/tree/master/packages/react) 的再来写个 vue 版本的 x(

或者可以等官方也出一个 vue 版本的，现在有一个 [react 版本](https://tdesign-react.formilyjs.org/)的

**Comment by arieslee** [comment]
> 或许你可以等我写完 [react](https://github.com/zodui/zodui/tree/master/packages/react) 的再来写个 vue 版本的 x(
> 
> 或者可以等官方也出一个 vue 版本的，现在有一个 [react 版本](https://tdesign-react.formilyjs.org/)的

好啊，等你哦，大老

**Comment by dengry518** [comment]
我也需要tdesign vue的表单设计器啊，官方还是更重视react

**Comment by arieslee** [comment]
> 我也需要tdesign vue的表单设计器啊，官方还是更重视react

确实，官方更重视React

**Comment by dengry518** [comment]
现在我只能暂时用form-create-designer-tdesign

**Comment by arieslee** [comment]
> 现在我只能暂时用form-create-designer-tdesign

给个链接呗？

**Comment by dengry518** [comment]
https://www.npmjs.com/  中搜form-create-designer-tdesign ，先用着，本人产品:http://82.157.68.9/ 拖拽表单就用的它，貌似现在也只能用它
