### ISSUE TITLE
[Bug][Table] 左、右固定多列 ，表头错位

### ISSUE THREAD

**Issue by Ruphi** [Tencent/tdesign-vue-next#299]
## tdesign-vue-next

You will open a bug issue at tdesign-vue-next。

### Describe Environment

browser version: chrome 97
tdesign-vue-next version: 0.8.0

### Describe the bug

表头固定列（除第一列外）的position计算错误，表头错位

codesandbox online demo: 
https://codesandbox.io/s/otl0r?file=/src/demo.vue

**Comment by pengYYYYY** [comment]
0.9.0 已修复
