### ISSUE TITLE
[alert] 消息提醒希望增加api，用js直接弹出提示框

### ISSUE THREAD

**Issue by wintsa123** [Tencent/tdesign-vue-next#2991]
### 这个功能解决了什么问题

想要在一些路由守卫，跳转前提示，
![image](https://github.com/Tencent/tdesign-vue-next/assets/47288630/f4c33fe2-e8e7-4db9-82fc-02c01fd69ea0)
我看了一下目前只能做到组件绑定v-if/v-show实现，有点捞。

### 你建议的方案是什么

我之前用的elementui/antd都能通过js弹出消息提示框，并且用js直接设定消失时间，弹框内容

**Comment by uyarn** [comment]
如果有问题再reopen
