### ISSUE TITLE
[Bug][Cascader] value类型为Number时，数据回填异常及clearable失效

### ISSUE THREAD

**Issue by hgjinfan** [Tencent/tdesign-vue-next#300]
## tdesign-vue-next

You will open a bug issue at tdesign-vue-next。

### Describe Environment

tdesign-vue-next version: 0.8.0

### Describe the bug

lodash/isEmpty 检查Number类型值总是返回true

导致数据回填异常。
https://github.com/Tencent/tdesign-vue-next/blob/0ba480b3ba4f31721a70c818136a47bd8840dd8e/src/cascader/cascader.tsx#L184

导致clearable失效
https://github.com/Tencent/tdesign-vue-next/blob/0ba480b3ba4f31721a70c818136a47bd8840dd8e/src/cascader/utils/inputContent.ts#L68

**Comment by pengYYYYY** [comment]
0.8.1 已修复
