### ISSUE TITLE
[Dropdown] 不断切换触发下拉列表中的几个操作会出现无法显示出下拉列表的情况

### ISSUE THREAD

**Issue by liqiGeGe** [Tencent/tdesign-vue-next#3000]
### tdesign 版本

1.4.2

### 重现链接

https://tdesign.tencent.com/vue/components/dropdown

### 重现步骤

无明确的复现步骤，但是总是能在偶然间复现！
具体操作[官网demo]是不断切换触发下拉列表中的几个操作，然后就会出现无法显示出下拉列表的情况。
![image](https://github.com/Tencent/tdesign/assets/130582068/0ed60260-b1ad-440b-9a1e-d1bc9efa0451)

### 期望结果

每次hover或者点击的时候，都能显示出下拉列表

### 实际结果

[官网demo]会出现无法显示出下拉列表的情况，然后就一直不出现了，除非刷新页面

https://github.com/Tencent/tdesign/assets/130582068/38d9b07f-9644-4303-957e-28a7cf8292a0

**Comment by uyarn** [comment]
dropdown默认是hover触发 如果是hover触发 目前只支持通过hover的方式来触发dropdown 点击会影响popup的判断 所以没法同时支持既要hover又时不时点击的场景 如果是希望点击触发 可以把dropdown的trigger属性设置为click 保证每次都是click触发

**Comment by uyarn** [comment]
如果还有问题麻烦再reopen或重开issue~ 
在这里补充了新的示例 https://github.com/Tencent/tdesign-vue-next/blob/develop/src/dropdown/_example/base.vue#L3

**Comment by uyarn** [comment]
> 我是用官网demo复现的，那如果说默认的hover触发，如果click就会导致popup的判断，那是不是需要优化呢？ 1）我理解点击之前肯定会触发hover吧？ 2）另外，假设每次都是Hover，但是不清楚我点击popup列表中的操作，是否会影响？ 毕竟我视频中出现这个情况，就是多次切换不同popup中的列表触发的
> 
> 我还是采用click触发吧，谢谢

嗯 确实需要优化 目前hover和click对隐藏逻辑的处理存在冲突
