### ISSUE TITLE
[Form] input 输入框 添加 clearable属性后，输入内容后，hover时，宽度会进行变化

### ISSUE THREAD

**Issue by hdszy** [Tencent/tdesign-vue-next#3001]
### tdesign-vue-next 版本

1.3.7

### 重现链接

https://stackblitz.com/edit/lz1pun?file=package.json,src%2Fdemo.vue

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/22936196/98ab3de5-6aec-4f59-b682-10f763a48280)

### 期望结果

输入内容后，hover时，宽度不进行变化，

### 实际结果

 input 输入框 添加 clearable属性后，输入内容后，hover时，宽度会进行变化

**Comment by blank-peas** [comment]
认领该任务，预计在7-10日前提交

**Comment by hdszy** [comment]
1.3.12 版本 问题还没有解决
