### ISSUE TITLE
[dropdown] <t-dropdown-item>加上for循环后在后面再加上一个<t-dropdown-item> 这个item不会渲染

### ISSUE THREAD

**Issue by jesseice** [Tencent/tdesign-vue-next#3012]
### tdesign-vue-next 版本

1.3.7

### 重现步骤

<t-dropdown :min-column-width="135" trigger="click">
            <template #dropdown>
              <t-dropdown-menu>
                <t-dropdown-item
                  v-for="item in dropdownMenu"
                  :key="item.title"
                  class="operations-dropdown-container-item"
                  @click="item.click()"
                >
                  <template v-if="item.iconName">
                    <t-icon :name="item.iconName"></t-icon>
                  </template>
                  {{ item.title }}
                </t-dropdown-item>
              </t-dropdown-menu>
              <t-dropdown-item>123</t-dropdown-item>
            </template>
            <t-button class="header-user-btn" theme="default" variant="text">
              <template #icon>
                <t-icon class="header-user-avatar" name="user-circle" />
              </template>
              <div class="header-user-account">{{ userStore.userInfo?.username }}</div>
              <template #suffix><t-icon name="chevron-down" /></template>
            </t-button>
          </t-dropdown>

### 期望结果

希望把v-for的下拉item后的item渲染出来

**Comment by uyarn** [comment]
https://tdesign.tencent.com/vue-next/components/dropdown#%E9%80%9A%E8%BF%87%E6%8F%92%E6%A7%BD%E6%96%B9%E5%BC%8F%E4%BD%BF%E7%94%A8%E4%B8%8B%E6%8B%89%E8%8F%9C%E5%8D%95 嵌套的看看这个示例 如果有问题在这复现下
https://stackblitz.com/edit/mhz4wp?file=package.json,src%2Fdemo.vue

**Comment by jesseice** [comment]
> https://tdesign.tencent.com/vue-next/components/dropdown#%E9%80%9A%E8%BF%87%E6%8F%92%E6%A7%BD%E6%96%B9%E5%BC%8F%E4%BD%BF%E7%94%A8%E4%B8%8B%E6%8B%89%E8%8F%9C%E5%8D%95 嵌套的看看这个示例
> 
> 如果有问题在这复现下 https://stackblitz.com/edit/mhz4wp?file=package.json,src%2Fdemo.vue

https://stackblitz.com/edit/mhz4wp-syiqur?file=src%2Fdemo.vue

**Comment by uyarn** [comment]
> > https://tdesign.tencent.com/vue-next/components/dropdown#%E9%80%9A%E8%BF%87%E6%8F%92%E6%A7%BD%E6%96%B9%E5%BC%8F%E4%BD%BF%E7%94%A8%E4%B8%8B%E6%8B%89%E8%8F%9C%E5%8D%95 嵌套的看看这个示例
> > 如果有问题在这复现下 https://stackblitz.com/edit/mhz4wp?file=package.json,src%2Fdemo.vue
> 
> 看一下 复现了https://stackblitz.com/edit/mhz4wp-syiqur?file=src%2Fdemo.vue

明白了 原来是这个用法 我来看看

**Comment by uyarn** [comment]
fixed in 1.3.9
