### ISSUE TITLE
[Bug][Upload] 上传默认post请求无法修改

### ISSUE THREAD

**Issue by comeriven** [Tencent/tdesign-vue-next#302]
### Describe Environment

browser version:
tdesign-vue-next version: 0.8.0

### Describe the bug
https://codesandbox.io/s/cool-surf-sqgkj?file=/src/App.vue
进入后如果报错,刷新一下

上传文件默认post请求, 设置 method 后仍然是post请求

`    
        <t-upload    
            v-model="formData.image"    
            method="GET"     // 失效    
            action="/fileupload"    
            theme="custom"    
            :data="{fileName: 'image', fileType: '2'}"    
        >    
            <t-button theme="default" variant="text" style="color: #2778FF;">上传</t-button>    
        </t-upload>    
`

**Comment by pengYYYYY** [comment]
0.8.1 已修复
