### ISSUE TITLE
[document] 主题编辑器遮挡了图片预览组件的操作栏

### ISSUE THREAD

**Issue by Nakus0426** [Tencent/tdesign-vue-next#3027]
### tdesign-vue-next 版本

1.3.8

### 重现链接

https://tdesign.tencent.com/vue-next/components/image-viewer#%E5%9F%BA%E7%A1%80%E5%9B%BE%E7%89%87%E6%9F%A5%E7%9C%8B%E5%99%A8

### 重现步骤

打开 `ImageViewer` 组件的文档，打开预览，会发现全局的主题编辑器挡住了 `ImageViewer` 组件的操作栏

### 期望结果

全局的主题编辑器适时的隐藏，在需要时再显示

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/41540888/65bed499-cab3-460f-bc4d-c96e8e1715ee)

**Comment by uyarn** [comment]
支持拖拽移动位置 刷新站点可以使用
