### ISSUE TITLE
[Table] 表格序号列没有重新计算

### ISSUE THREAD

**Issue by tanhh326** [Tencent/tdesign-vue-next#3038]
### tdesign-vue-next 版本

1.3.4

### 重现步骤

手动修改表格的`pagination`值跳转页码，序号列没有重新计算

**Comment by PengYYYYY** [comment]
Uploading Screen Recording 2023-07-12 at 15.48.35.mov…

**Comment by PengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/assets/35833812/fdc8ab5c-1233-4268-823b-61a4a6760cf2
