### ISSUE TITLE
[t-tree] 数据不能正确显示

### ISSUE THREAD

**Issue by ouyoungs** [Tencent/tdesign-vue-next#3046]
### tdesign-vue-next 版本

1.3.9

### 重现链接

https://tdesign.tencent.com/vue-next/components/tree

### 重现步骤

当数据传进去，checked: true 应该会显示选中状态，但是没有。  不过 actived 等其它，能正确的显示。

数据如下：

```ts
<t-tree
  :data="myData"
  hover
  line
  :checkable="true"
  :check-strictly="true"
  :activable="true"
  :active-multiple="true"
  :expand-on-click-node="true"
  value-mode="all
/>

const myData = reactive([
  {
    value: '1',
    label: '大唐西域',
    checked: true,
    children: [
      {
        value: '2',
        label: '唐僧',
        checked: true,
        actived: true,
      },
      {
        value: '3',
        label: '八戒',
        checked: true,
        actived: false,
      },
      {
        value: '4',
        label: '悟空',
        checked: true,
        actived: true,
      },
    ],
  },
]);
```

### 期望结果

当数据传进去，checked: true 应该会显示选中状态，但是没有。  不过 actived 等其它，能正确的显示。

**Comment by imp2002** [comment]
verified, reproduction url https://stackblitz.com/edit/lz1pun-xjc5zq?file=vite.config.js,src%2Fdemo.vue

The strange thing is that I clone the repo to try to find out the bug but it works fine, it's work normally in offical demo site.

![image](https://github.com/Tencent/tdesign-vue-next/assets/41513919/d98aca67-f29c-4189-9a3c-e65cd364b32f)
