### ISSUE TITLE
[Table] rowKey 字段希望取消 `id`这个默认值

### ISSUE THREAD

**Issue by kenzyyang** [Tencent/tdesign-vue-next#3059]
### 这个功能解决了什么问题
当输入的数据并没有 id 这个 key 时，所有的 row-key 会被统一设置为 undefined。
在使用扩展行功能时，会导致所有的扩展行被点击后统一展开和收起。
在 vue 中 key 想同的副作用有很多，在面对 table 这种 数据 操作 型组件时 key 想同更加危险，可能导致在复杂的排序变更后最后提交的数据不一定是我想要的效果。

### 你建议的方案是什么？
去除 id 这个默认值字段，要么强制用户必须设置，要么在不设置时提供兜底方案。

**Comment by xixileng** [comment]
不止 table，tree 也有这个问题，在人员选择器中，同一个 id 可以存在于多个节点，而使用 id 当 key 就会提示重复 key 的错误。应该提供自定义 key 的字段或者函数

**Comment by chaishi** [comment]
上文两个描述，应该属于不同的问题。

issue creator 已经群里沟通，去除的只是 key 的默认值，但是本质上还是存在行唯一标识，且必须存在。
