### ISSUE TITLE
[Bug][Notification] 缺少插件方式的 Demo

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#306]
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/11605702/153588280-315a8379-a11d-46c7-8f8b-2ea3cc974c3f.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/11605702/153588378-49cb46a2-5cd4-4d0e-b933-f093b632a3a7.png">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/307

**Comment by pengYYYYY** [comment]
0.8.1 已修复
