### ISSUE TITLE
[Cascader] 建议增加禁用某些选项的功能

### ISSUE THREAD

**Issue by vikyd** [Tencent/tdesign-vue-next#3060]
### tdesign-vue-next 版本

1.3.9

**Comment by PengYYYYY** [comment]
https://stackblitz.com/edit/quxnxp?file=package.json,src%2Fdemo.vue 可以看看这个例子

**Comment by vikyd** [comment]
@PengYYYYY  我没描述清楚，想要的是：禁用第一层，但可以展开到第二层或更深，允许选择第二层或更深层的节点。

**Comment by PengYYYYY** [comment]
本来要选的就是叶子结点吧

**Comment by vikyd** [comment]
> 本来要选的就是叶子结点吧

还需选非叶子节点。需求是除了第一层的节点，其他都可以选择。 官方例子不也允许选任意级别吗： https://tdesign.tencent.com/vue-next/components/cascader#%E9%80%89%E6%8B%A9%E4%BB%BB%E6%84%8F%E4%B8%80%E9%A1%B9%E7%9A%84%E7%BA%A7%E8%81%94%E9%80%89%E6%8B%A9%E5%99%A8
