### ISSUE TITLE
[Loading] loading 图标在移动端下变形

### ISSUE THREAD

**Issue by qihuantian1** [Tencent/tdesign-vue-next#3063]
### tdesign-vue-next 版本

1.3.9

### 重现步骤

官网改成移动端模式 loading 图标变形， 安卓和苹果都一样

![image](https://github.com/Tencent/tdesign-vue-next/assets/10757545/d800bb8c-7e8a-444a-8eaf-95aab1f8e379)

**Comment by uyarn** [comment]
refer to https://github.com/Tencent/tdesign-vue-next/issues/358
