### ISSUE TITLE
[Menu] 导航菜单，在hover子菜单后，父级菜单有时候会消失

### ISSUE THREAD

**Issue by kuma0605** [Tencent/tdesign-vue-next#3065]
### tdesign-vue-next 版本

1.3.10

### 重现步骤

https://github.com/Tencent/tdesign-vue-next/assets/2958589/c0c0776e-893d-45d7-b289-ebf1255738cc

### 期望结果

父级菜单在 hover到子菜单后正常显示

### 实际结果

父级菜单在 hover到子菜单后消失

### 补充说明
触控板不容易复现，鼠标移动更快，容易复现。

**Comment by PengYYYYY** [comment]
https://github.com/user-attachments/assets/afc9428c-fa55-490b-9da1-778a46d83896


最新版线上未复现此问题
