### ISSUE TITLE
表单自定义检验为什么在执行非submit方法也会触发

### ISSUE THREAD

**Issue by imaxun** [Tencent/tdesign-vue-next#3066]
### tdesign-vue-next 版本

最新版本

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/29112991/12c7c366-be63-4fd7-9df6-e369f7a0c29d)

![image](https://github.com/Tencent/tdesign-vue-next/assets/29112991/0365f68f-625c-4db6-adcf-7b80961d7ffb)

**Comment by xixileng** [comment]
表单校验就是会在 blur、change 的时候自动触发（根据 trigger 的配置）

**Comment by PengYYYYY** [comment]
看看组件里面是不是有什么按钮之类的会导致表单验证出发
