### ISSUE TITLE
[Select 选择器 ] valueType为object时, 选中项显示 Value 不显示 Label

### ISSUE THREAD

**Issue by yuerzm** [Tencent/tdesign-vue-next#3067]
### tdesign-vue-next 版本

1.3.10

### 重现链接

https://stackblitz.com/edit/bgeycu?file=src%2Fdemo.vue

### 重现步骤

当选中项不在当前options时, 选中项显示Value, 不显示Label, 当通过滚动加载直至选中项在options 中时, 才正确显示Label

### 期望结果

选项显示: 滚动新增选项20
显示应为 Label 值 

### 实际结果

实际显示: 20
显示为 Value 值

**Comment by uyarn** [comment]
目前对选项的处理逻辑应该是不支持这样使用的 当选项不存在于option时 可以考虑换成在这个时候用valueDisplay来展示
