### ISSUE TITLE
[menu] 侧边菜单使用submenu的问题

### ISSUE THREAD

**Issue by Wesley-0808** [Tencent/tdesign-vue-next#3069]
### tdesign-vue-next 版本

1.3.10

### 重现步骤

点击submenu的title内容时，应该是普通样式，而且展开过快。
奇怪的是官网不能复现，而我的代码是从官网复制下来的

### 实际结果

如图所示
![IMG_2225](https://github.com/Tencent/tdesign-vue-next/assets/69622989/6a4dbe1c-f98a-4c74-9c5f-46641f9f098a)

**Comment by Wesleyyy0808** [comment]
### 另外，我想用jsx封装一个menu组件，就是根据一个配置文件提供的内容进行渲染，现在的问题是渲染是没有问题的，但是会报栈溢出。不知道是不是我的jsx写法有问题。

报错：
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/44e92b04-53a8-4873-88d0-2bd0db2e2592)
部分代码：
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/94cbf3d0-f804-45de-8d71-976a9e09ca6d)
配置文件：
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/7808bd6d-3203-46db-a9d1-227b759537fd)

## 如果需要我提供完整代码可以跟我讲下。你们可以商讨一下 这个问题/能否使用jsx进行二次封装，如果不能实现的话也请告诉我，谢谢！

**Comment by Wesleyyy0808** [comment]
上述，我的jsx封装不打算透传任何方法，只传递值

**Comment by xiaosansiji** [comment]
视频中的点击时效果请提供个复现 demo 链接，官网正常的话大概率是项目中有其他样式影响，可以先检查下对应 DOM 的样式跟官网的有没有不同

**Comment by Wesleyyy0808** [comment]
我看了看TD-SubMenu源代码，发现如下：
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/a023465f-3955-4618-a222-b9b211f77e2a)
这个rippleColor是跟着menu的theme走的，然后我看官网的demo里面css给定了一个rippleColor：
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/bd06f2c1-a35d-494d-b8b1-c8f9fd9edbee)
而我的项目中全局声明的样式变量只有三个，名称不包含ripple等内容，不会影响到样式。
最后我翻了翻useRipple的逻辑，他会获取传递过去的ripplecolor，就是他获取了上文所述的ripplecolor根据menu的theme走的。
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/421f07c1-2baa-4bb0-b231-8d8c02c35f8b)

**Comment by Wesleyyy0808** [comment]
### 或者有可能都不是这个原因，它都没有获取到任何ripplecolor，走了默认的颜色
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/b019e933-aec8-432f-954c-f946eba405e7)
### 但是我感觉就算是默认的颜色也不该是黑色，建议应用为主题色（--td-brand-color-focus）

**Comment by Wesleyyy0808** [comment]
@LeeJim @xiaosansiji @amadeus711

**Comment by Wesleyyy0808** [comment]
可能你们有些忙来不及回复，所以我自己找出了问题所在。确实是td-submenu的问题

**Comment by Wesleyyy0808** [comment]
可能你们有些忙来不及回复，所以我自己找出了问题所在。确实是我自身的问题
我把 es\mjs\menu\submenu.mjs 的下面内容
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/99aaa28b-4152-4e51-9374-dba4d386e0ee)
改成
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/327bb404-2399-414a-8ec1-d6b090977074)
也就是加入了console，但是结果不尽人意，显然：当我的样式为深色时，我传递过去的是个true，而不是规定值：light/dark/global/system，从menu的css也可以看出，theme我传递过去的确实是true：
![image](https://github.com/Tencent/tdesign-vue-next/assets/69622989/3c79093d-1259-4a20-9a4a-87966ae03620)
所以还是希望TD团队尽快适配theme的global选项，感谢！
