### ISSUE TITLE
[tree shaking]使用vite开发时，浏览器过多无用请求

### ISSUE THREAD

**Issue by ChengZicy** [Tencent/tdesign-vue-next#3079]
### tdesign-vue-next 版本

1.3.10

### 重现步骤

使用按需引入或者使用auto-import引入时，都会出现这样的情况
```
import { Button as TButton } from 'tdesign-vue-next'
app.use(TButton)


<t-button>Click</t-button>
```

<img width="353" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/108649468/bad23c8a-57f8-4e00-bfa8-df612fa0218d">
<img width="302" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/108649468/2196887b-3edc-46a0-a919-31a84e57414a">

浏览器会加载所有icon的js，以及所有组件的style，因为请求过多，导致devtools每次打开都会很卡

### 期望结果

按需引入只加载应加载的部分，例如引入button，就只加载button有关的css
可以提供一个开关，是否加载icon资源

### 框架版本

3

### Node版本

18

**Comment by ChengZicy** [comment]
补充：全局导入也是一样

**Comment by wangyang0210** [comment]
https://stackblitz.com/edit/yyyqnc-ytgbmc?file=src%2Fmain.js
import Button from 'tdesign-vue-next/es/button';

**Comment by skywalker512** [comment]
应该可以确定是这个提交导致 icon 被 splitting 了

https://github.com/Tencent/tdesign-icons/pull/52

已经在对应仓库发起了 issue 了。

> 因为请求过多，导致devtools每次打开都会很卡

这个 chrome 的 bug，已经修复合入 chrome 115 了
https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4642732

**Comment by uyarn** [comment]
有两部分 一部分是图标的Chunk 一部分是其他组件的css 处理中

**Comment by uyarn** [comment]
icons-vue-next 升级至 0.1.12 可以解决图标chunk加载的问题
