### ISSUE TITLE
[Bug]手机浏览文档，点击悬浮按钮，滑动查看组件列表，会自动关闭

### ISSUE THREAD

**Issue by JokerLoLgrey** [Tencent/tdesign-vue-next#308]
![image](https://user-images.githubusercontent.com/33446705/153704596-e1f28d39-e443-4b80-ab4e-9f75b59a95d5.png)
点击如图按钮，展示组件列表，滑动列表时，列表会自动关闭

手机型号：iPhone 13 Pro 
手机系统：IOS 15.2.1
浏览器： Safari

**Comment by pengYYYYY** [comment]
该issue已迁移至https://github.com/Tencent/tdesign/issues/84
