### ISSUE TITLE
[dialog] 添加OnBeforeOk事件

### ISSUE THREAD

**Issue by puppetsheep** [Tencent/tdesign-vue-next#3086]
### 这个功能解决了什么问题

使用该事件，在按下确认按钮时，将使确认按钮变为loading状态，直到事件处理完并给出特定返回值。用于异步关闭dialog。
> 同理，可以加入 `OnBeforeCancel` 事件

### 你建议的方案是什么

```
const onBeforeOk = (done) => {
     // 异步操作
    ...
    done( )
}

// 其中，函数类型为
( done: (closed: boolean) => void) => void | boolean | Promise<void | boolean>
```

**Comment by Zz-ZzzZ** [comment]
这是组件调用还是函数调用，组件调用你描述的需求里文档有例子了，函数调用是像element-ui那样吗。

**Comment by puppetsheep** [comment]
类似于[Arco-design](https://arco.design/vue/component/modal#API)的那样子，允许在关闭前执行异步操作

**Comment by Zz-ZzzZ** [comment]
按照你的描述来看，这似乎不需要onBefore的事件吧...

1. 将确定按钮的按钮状态储存于一个`reactive`中
2. 点击按钮，此时触发onConfirm，在异步内更改这个`reactive`内的状态
3. 当异步结束后重置`reactive`的状态，隐藏`dialog`

还是说，想要触发`onBeforeConfirm`时由组件来控制按钮的loading

**Comment by puppetsheep** [comment]
可以通过组件内部进行一个拦截是最好的，因为还有一个 `onBeforeClose` 事件，而触发这个事件的情况有很多种，也很难去做到手动拦截关闭。同样的，去设定确认按钮也需要去做很多的工作，而这个事件又大面积使用，因此建议封装入组件里，能更方便的使用。

**Comment by yuzunyue** [comment]
> 可以通过组件内部进行一个拦截是最好的，因为还有一个 `onBeforeClose` 事件，而触发这个事件的情况有很多种，也很难去做到手动拦截关闭。同样的，去设定确认按钮也需要去做很多的工作，而这个事件又大面积使用，因此建议封装入组件里，能更方便的使用。

赞同

**Comment by czq297297** [comment]
+1

**Comment by colipat** [comment]
赞同，希望加一下

**Comment by chaishi** [comment]
> 使用该事件，在按下确认按钮时，将使确认按钮变为loading状态，直到事件处理完并给出特定返回值。用于异步关闭dialog。

需要 onBeforeOk 的场景大多是因为组件不受控制，组件内部主动操作了关闭。

但是，TDesign Dialog 组件，打开或关闭是完全受 `visible` 控制的，这里描述的需求可以很简单就实现，并不需要 onBeforeOk。示例如下：

https://stackblitz.com/edit/gvvr1q?file=package.json,src%2Fdemo.vue

```
<template>
  <t-space>
    <t-space>
      <t-button @click="visible = true">异步加载类按钮</t-button>
    </t-space>
    <t-dialog
      :visible="visible"
      :on-confirm="onConfirm"
      :on-close="onClose"
      header="保存订单"
      body="订单保存中，请稍后"
      :confirm-btn="{
        content: '保存',
        theme: 'primary',
        loading,
      }"
    />
  </t-space>
</template>
<script setup>
import { ref } from 'vue';
import { DialogPlugin } from 'tdesign-vue-next';

const visible = ref(false);
const loading = ref(false);

const onClose = () => {
  visible.value = false;
};

const onConfirm = () => {
  loading.value = true;
  const timer = setTimeout(() => {
    loading.value = false;
    visible.value = false;
    clearTimeout(timer);
  }, 500);
};
</script>
```

加一个 onBeforeOk 的时间，和加一下 loading 的时间差，应该可以忽略不计。

**Comment by czq297297** [comment]
> > 使用该事件，在按下确认按钮时，将使确认按钮变为loading状态，直到事件处理完并给出特定返回值。用于异步关闭dialog。
> 
> 需要 onBeforeOk 的场景大多是因为组件不受控制，组件内部主动操作了关闭。
> 
> 但是，TDesign Dialog 组件，打开或关闭是完全受 `visible` 控制的，这里描述的需求可以很简单就实现，并不需要 onBeforeOk。示例如下：
> 
> https://stackblitz.com/edit/gvvr1q?file=package.json,src%2Fdemo.vue
> 
> ```
> <template>
>   <t-space>
>     <t-space>
>       <t-button @click="visible = true">异步加载类按钮</t-button>
>     </t-space>
>     <t-dialog
>       :visible="visible"
>       :on-confirm="onConfirm"
>       :on-close="onClose"
>       header="保存订单"
>       body="订单保存中，请稍后"
>       :confirm-btn="{
>         content: '保存',
>         theme: 'primary',
>         loading,
>       }"
>     />
>   </t-space>
> </template>
> <script setup>
> import { ref } from 'vue';
> import { DialogPlugin } from 'tdesign-vue-next';
> 
> const visible = ref(false);
> const loading = ref(false);
> 
> const onClose = () => {
>   visible.value = false;
> };
> 
> const onConfirm = () => {
>   // 设置加载状态
>   loading.value = true;
>   const timer = setTimeout(() => {
>     // 去除加载
>     loading.value = false;
>     // 隐藏弹框
>     visible.value = false;
>     clearTimeout(timer);
>   }, 500);
> };
> </script>
> ```
> 
> 对于实际开发，加一个 onBeforeOk 的时间，和加一下 loading 的时间差，应该可以忽略不计。

并不会忽略不计吧  代码量一多的话
