### ISSUE TITLE
[Pagination] 分页组件在Dialog 对话框中显示，分页大小选择器中的文字会被省略

### ISSUE THREAD

**Issue by Likunone** [Tencent/tdesign-vue-next#3092]
### tdesign-vue-next 版本

 1.3.10

### 重现链接

https://stackblitz.com/edit/p4gmyu?file=package.json,src%2Fdemo.vue

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/3352

**Comment by chaishi** [comment]
published at v1.5.5
2023-09-13
