### ISSUE TITLE
[treeselect/select组件] 关于选择器主键选择值后变成t142等类似于这样字符的问题

### ISSUE THREAD

**Issue by StarryCrystal** [Tencent/tdesign-vue-next#3099]
### tdesign-vue-next 版本

1.3.9

### 重现链接

无

### 重现步骤

如图所示，行政地址框是一个TreeSelect，在第一次加载时（添加一条数据）表现正常
<img width="473" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/17041926/9ccf652a-a0cf-4c3f-8260-0e196860a006">
在修改时打开窗口变成了纯数字
<img width="476" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/17041926/3fd8bb0e-ca9c-430e-b011-3f001ae7ab88">
我感觉这个问题应该是同样的问题，在传值时，勾选的多条数据理应传递label的Value值，实际传递的是一种奇怪的有规律的值
<img width="1112" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/17041926/30cbd98c-d294-4b7b-8f21-6dde2a77f2b1">

### 期望结果

这个问题我能在哪里去排查？或者说这是一个什么样的问题

### 实际结果

无

### 框架版本

3.3.4

### 浏览器版本

Edge( 114.0.1823.79 )

### 系统版本

MacOS(14.0)

### Node版本

V19

**Comment by StarryCrystal** [comment]
> ### tdesign-vue-next 版本
> 1.3.9
> 
> ### 重现链接
> 无
> 
> ### 重现步骤
> 如图所示，行政地址框是一个TreeSelect，在第一次加载时（添加一条数据）表现正常
<img alt="image" width="476" src="https://user-images.githubusercontent.com/17041926/253248409-3fd8bb0e-ca9c-430e-b011-3f001ae7ab88.png"> 在修改时打开窗口变成了纯数字  <img alt="image" width="473" src="https://user-images.githubusercontent.com/17041926/253248045-9ccf652a-a0cf-4c3f-8260-0e196860a006.png"> 我感觉这个问题应该是同样的问题，在传值时，勾选的多条数据理应传递label的Value值，实际传递的是一种奇怪的有规律的值 <img alt="image" width="1112" src="https://user-images.githubusercontent.com/17041926/253248790-30cbd98c-d294-4b7b-8f21-6dde2a77f2b1.png">
> 
> ### 期望结果
> 这个问题我能在哪里去排查？或者说这是一个什么样的问题
> 
> ### 实际结果
> 无
> 
> ### 框架版本
> 3.3.4
> 
> ### 浏览器版本
> Edge( 114.0.1823.79 )
> 
> ### 系统版本
> MacOS(14.0)
> 
> ### Node版本
> V19
> 
> ### 补充说明
> _No response_

前面两张图反了。重新发一下

**Comment by xixileng** [comment]
试试写一个最小复现 demo，贴在 stackblitz 里，然后把链接分享出来，这样方便开发人员排查问题哈～
