### ISSUE TITLE
[Badge] 支持小圆点状态

### ISSUE THREAD

**Issue by wc19950724** [Tencent/tdesign-vue-next#3104]
### 这个功能解决了什么问题

丰富Badge样式风格

### 你建议的方案是什么

类似ant design的Badge，支持小圆点状态
![image](https://github.com/Tencent/tdesign-vue-next/assets/59589936/e8c2337f-3707-4cf9-afba-49b3390145ac)

**Comment by xixileng** [comment]
dot 和 color 配合，不写 slot，就实现了，再自行调整样式

**Comment by PengYYYYY** [comment]
使用样式更改吧
