### ISSUE TITLE
[<t-table>] 当colKey和title完全一致时，使用template语法异常

### ISSUE THREAD

**Issue by zonewancheng** [Tencent/tdesign-vue-next#3106]
### tdesign-vue-next 版本

能复现

### 重现链接

https://codesandbox.io/p/sandbox/lively-brook-rzh8nt?file=%2Fsrc%2FApp.vue%3A12%2C18

### 重现步骤

<t-table>中COLUMNS中colkey和title相同时，使用template渲染colkey，tilte也会被渲染，示例链接中colkey为 ‘op’

### 期望结果

tilte不要被渲染，展示设置的title

```[tasklist]
### Tasks
```

**Comment by xixileng** [comment]
示例中 template 渲染表头的就是使用的就是 title 字段哦～

**Comment by zonewancheng** [comment]
> 示例中 template 渲染表头的就是使用的就是 title 字段哦～

示例有两列，第二列，title为‘op’,渲染的是template的‘删除’

**Comment by zonewancheng** [comment]
<img width="1199" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/9192508/d492e362-9f97-4e8e-876a-c471eeea4327">

**Comment by zonewancheng** [comment]
> > > 示例中 template 渲染表头的就是使用的就是 title 字段哦～
> > 
> > 
> > 示例有两列，第二列，title为‘op’,渲染的是template的‘删除’
> 
> 首先这个问题和 colKey 没有关系，先忽略掉，表头的规则是：
> 
> 1. title 字段是函数则执行 title
> 2. title 字段是字符串，且有对应的 slot，则渲染 slot
> 3. 有 render 字段且 render 字段是函数，则执行 render
> 4. 直接文本渲染 title
> 
> 你描述的是碰到了第二个条件，源代码在 useTableHeader 的 renderTitle 中

额，我明白你的意思了，因为title为‘op’，检测到有slot=op因此，title渲染了slot的值。
而单元格cell因为默认使用colkey作为插槽名称，也是slot=op，所以也渲染了slot的值。
在title和cell（或者colkey）完全一致的情况下，我如果只想让title或者cell其中一个渲染，是不是就不能用slot插槽的写法了？

**Comment by chaishi** [comment]
同为 <t-table> 组件里面的插槽，不允许存在相同的插槽名。建议更为不同的名字。

> 在title和cell（或者colkey）完全一致的情况下，我如果只想让title或者cell其中一个渲染，是不是就不能用slot插槽的写法了？

可以继续使用插槽写法。再添加一个字段 `cell: 'name-column'`，然后使用
```
<t-table><template #name-column>使用 name-column 作为列的插槽名称。</template></t-table>
```

<img width="948" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/08bd0489-8bc9-4637-8a6c-4f5b68f4ffd9">
