### ISSUE TITLE
[Table] 可选表格的选中事件和单击事件冲突

### ISSUE THREAD

**Issue by silentchild** [Tencent/tdesign-vue-next#3115]
### tdesign-vue-next 版本

1.3.11

### 重现链接

https://stackblitz.com/edit/hapy6k?file=src%2Fdemo.vue

### 重现步骤

如以上代码，当我选中一项时不但触发了选中变更事件，也同时会触发两次单击事件，应该是没有做阻止冒泡。

### 期望结果

选中更改时仅触发选中变更事件，不要触发单击事件

### 实际结果

选中更改时仅触发1次选中变更事件和2次单击事件

### 框架版本

vue3.3

### 系统版本

win11

**Comment by chaishi** [comment]
https://tdesign.tencent.com/vue-next/changelog
2023-07-19 `v1.3.12` 发布的新版本，没有上述问题了。

体验地址：https://stackblitz.com/edit/8qibph?file=package.json,src%2Fdemo.vue

**Comment by silentchild** [comment]
> 

好像解决了，赞！
