### ISSUE TITLE
[Select组件] 下拉菜单容器在safari浏览器环境没有阴影效果

### ISSUE THREAD

**Issue by vabora** [Tencent/tdesign-vue-next#3123]
### tdesign-vue-next 版本

1.3.11

### 重现步骤

Select 选择器及其他包含下拉菜单的组件在safari浏览器边框没有阴影效果。

### 期望结果

修复边框阴影。

**Comment by uyarn** [comment]
谢谢你的反馈 ~ 问题已经修复 是官网注入主题的时候 字符中存在多余的字符在safari中未能正常渲染出来所导致 不是组件本身的问题 目前问题已经修复并重新部署官网了 
<img width="1035" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/c311af7e-baf3-4046-a9cf-8907e43d70f4">
