### ISSUE TITLE
[input] 请问 input 的 value 是否支持自定义类型？

### ISSUE THREAD

**Issue by sertceps** [Tencent/tdesign-vue-next#3135]
### 这个功能解决了什么问题

看到 input 中 modelValue 类型定义为 string，目前遇到的问题是，ts 定义了 x 类型为 number ，用于请求体，或是后台返回字段 x 类型为number，需要回填。

这种情况下会有类型冲突。

### 你建议的方案是什么

请求或者回填实际并不影响，但是项目比较看重类型准确性。

想请问有没有办法自定义 input 类型，或者什么方法规避上面的类型冲突？

（issue 没找到提问模板。）

**Comment by sertceps** [comment]
> 不能将类型“number | undefined”分配给类型“string | undefined”。不能将类型“number”分配给类型“string”。ts(2322)

> 所需类型来自属性 "modelValue"，在此处的 "{ type?: "number" | "search" | "password" | "url" | "hidden" | "text" | "submit" | "tel" | undefined; name?: string | undefined; value?: string | undefined; autocomplete?: string | undefined; ... 53 more ...; readonly maxcharacter?: number | undefined; } & Record<...>" 类型上声明该属性

**Comment by liweijie0812** [comment]
number类型用t-input-number

**Comment by sertceps** [comment]
> number类型用t-input-number
@liweijie0812 
好的，谢谢回复👍👍
