### ISSUE TITLE
[Table] onValidate事件不会触发

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#3139]
### tdesign-vue-next 版本

1.3.12

### 重现步骤

Table可编辑行的表格   官方例子中点击校验全部按钮会调用validateTableData方法，文档里写着“实例方法 validateTableData 用于进行表格全部数据校验，onValidate 在全部数据校验完成时触发。实则”@validate="onValidate"该事件不会触发，打开f12控制台可以验证。

### 期望结果

可以触发事件

### 实际结果

没有触发事件

### 框架版本

3.3.4

**Comment by tanhh326** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/82007768/0c7d82ee-9807-49e8-ba7e-52cdd62b0962)

**Comment by lin-code-world** [comment]
https://stackblitz.com/edit/audbg8?file=src%2Fmain.js,src%2Fdemo.jsx
使用jsx该事件不会触发

**Comment by chaishi** [comment]
`validateTableData` 会返回一个 Promise 对象，除了 onValidate 事件，还可以在返回的 Promise 对象中处理

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/3143
