### ISSUE TITLE
[Select 选择器] 使用过滤功能后，选择器列表会发生改变

### ISSUE THREAD

**Issue by CharlesWongcy** [Tencent/tdesign-vue-next#3142]
### tdesign-vue-next 版本

0.24.9版本～最新版本

### 重现步骤

选择器的过滤功能，在使用之后，选择器列表会发生更改

### 期望结果

<img width="564" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/66716843/45e70f69-a99e-438a-a12c-8dafa4f8f75d">

### 实际结果

<img width="421" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/66716843/91a02c02-4da9-484a-96de-ec4ab1a35c9a">

### Node版本

16.14.0

**Comment by uyarn** [comment]
需要提供下你使用的代码 或者在stackblitz上复现下 这样子无法判断问题

**Comment by uyarn** [comment]
这个问题已经修复了 1.5.0之前的版本确实要长列表的异常
