### ISSUE TITLE
[Table] 如果在 validateTableData 中更改 data 数据，会校验历史Table Data数据

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#3148]
### tdesign-vue-next 版本

1.3.12

### 重现链接

https://stackblitz.com/edit/audbg8-pkh4ye?file=src%2Fmain.js,src%2Fvalidator.jsx

### 重现步骤

可编辑table，调用校验方法validateTableData之前，修改table的data值，调用validateTableData之后发现会同时校验历史的data数据。如果row-key设置一个随机值，调用校验方法validateTableData之前给table data重新赋值，每次调用校验方法之后发现会把之前的历史data都会校验。调用校验方法应该只校验当前的table data数据。
需求场景是，需要对列表数据进行修改，会变更table的data值然后提交的时候进行校验。

### 期望结果

调用校验方法应该只校验当前的table data数据。

### 实际结果

调用校验方法validateTableData会校验历史的table data数据。

### 框架版本

3.3.4

**Comment by chaishi** [comment]
可编辑表格，数据分 2 种：非编辑态数据 和 实时变化的编辑态数据。只有确定保存成功后，才会更新非编辑态的表格数据。

故而，进入编辑态之后，编辑态会有单独的数据变量，此时的输入框数据变化，不会影响表格本身的 data 数据。

`data.value = [{ key: Date.now(), name: 'test' }];` 这段代码，更新的是 “非编辑态 的数据”，而 `validateTableData` 校验的时是 “编辑态的变量数据”。

应该是需要提供一个更新编辑态数据的方法，类似这个 issue 的问题：https://github.com/Tencent/tdesign-vue/issues/2577

<img width="1194" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/91068d84-8ab0-494a-8ac4-b5485a48eac3">

**Comment by lin-code-world** [comment]
> @lin-code-world 你的需求场景，方便提供一个更完整 demo 吗

@chaishi https://stackblitz.com/edit/audbg8-fgarxg?file=src%2Fvalidator.jsx,src%2Fmain.js
先新增一行空数据，点击校验，会对该行数据进行校验，显示校验不通过。然后删除该行数据，再次点击校验，按理说应该校验通过，实际还是会对旧数据进行校验，校验不通过。

**Comment by ZJQ0925** [comment]
请问下这个问题解决了吗 @lin-code-world

**Comment by lin-code-world** [comment]
> 请问下这个问题解决了吗 @lin-code-world

没有，官方没人解决，现在更新到1.9.9，这个问题依然存在。校验逻辑只能自己实现，取出当前的表格集合自己判断，不用validateTableData方法

**Comment by uyarn** [comment]
fixed 1.10.6
