### ISSUE TITLE
[Improve][Table]vue3版本表格固定两列，第二列表头横向滚动未固定

### ISSUE THREAD

**Issue by wmhost** [Tencent/tdesign-vue-next#316]

**Comment by pengYYYYY** [comment]
有codesandbox的示例嘛

**Comment by wmhost** [comment]
> 有codesandbox的示例嘛

codesandbox online demo:
https://codesandbox.io/s/otl0r?file=/src/demo.vue

#299

**Comment by pengYYYYY** [comment]
0.9.0 已修复
