### ISSUE TITLE
[Form] rules校验数字时设置min或max不生效

### ISSUE THREAD

**Issue by yuzunyue** [Tencent/tdesign-vue-next#3165]
### tdesign-vue-next 版本

1.4.1

### 重现链接

https://stackblitz.com/edit/yjbcwk?file=src%2Fdemo.vue

### 重现步骤

在rules里设置
{
      number: true,
      min: 0,
      max: 2,
      message: '请输入正确的数字',
      type: 'warning',
}
输入-1或3校验可以通过

### 期望结果

校验不应通过

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/32872977/2234d35c-36cc-4085-bb48-141cf6dbd71c)
![image](https://github.com/Tencent/tdesign-vue-next/assets/32872977/004d1764-1217-408d-9d05-5d416d02a64e)

**Comment by tanhh326** [comment]
```js
const rules = {
  age: [
    { required: true, message: '年龄必填', type: 'error' },
    { min: 0, message: '输入字数应在0到2之间', type: 'error', trigger: 'blur' },
    { max: 2, message: '输入字数应在0到2之间', type: 'error', trigger: 'blur' },
  ],
};
```

**Comment by yuzunyue** [comment]
> ```js
> const rules = {
>   age: [
>     { required: true, message: '年龄必填', type: 'error' },
>     { min: 0, message: '输入字数应在0到2之间', type: 'error', trigger: 'blur' },
>     { max: 2, message: '输入字数应在0到2之间', type: 'error', trigger: 'blur' },
>   ],
> };
> ```

感谢！
