### ISSUE TITLE
[table] 固定列空数据， 暂无数据显示错位

### ISSUE THREAD

**Issue by liweijie0812** [Tencent/tdesign-vue-next#3166]
### tdesign-vue-next 版本

1.4.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/table#%E5%9B%BA%E5%AE%9A%E5%88%97%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

<img width="822" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/10710889/28c810dd-c272-47b1-a6dc-d4ec77ebb6de">

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/3167
