### ISSUE TITLE
[Pagination] 切换每页条数

### ISSUE THREAD

**Issue by 17683813062** [Tencent/tdesign-vue-next#3180]
### tdesign-vue-next 版本

1.3.3

### 重现步骤

当页码不为1时候，切换每页条数，页码需要重置为1
不然可能请求的数据为空

![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/642582d8-d121-4082-81c5-594e9dc8b154)

![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/a80f56ee-90db-470c-b172-392b7d5c2683)

### 期望结果

当页码不为1时候，切换每页条数，页码重置为1

### 实际结果

当页码不为1时候，切换每页条数，页码为之前的页码

### 框架版本

Vue(3.2.47)

### 浏览器版本

Chrome(112.0.5615.121)

### 系统版本

window

### Node版本

18.12.0

**Comment by AuYuHui** [comment]
没有复现，检查下自己的代码
