### ISSUE TITLE
[Bug][Component] 演示文档BUG。Steps 步骤条

### ISSUE THREAD

**Issue by RSS1102** [Tencent/tdesign-vue-next#319]
## tdesign-vue-next

![image](https://user-images.githubusercontent.com/81673017/154180102-b417feed-2c88-417f-abb7-37609f1a75cd.png)
![image](https://user-images.githubusercontent.com/81673017/154180165-1c4dcf9d-e55c-4a8d-a784-164b7a0f251e.png)
描述和行为不准确，这里描述为“下一步”，实际执行“上一步”。

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/311/files

**Comment by pengYYYYY** [comment]
0.8.1 已修复
