### ISSUE TITLE
[Button] 在electron-vite-vue包中button会导致页面一直加载后崩溃

### ISSUE THREAD

**Issue by Epxir** [Tencent/tdesign-vue-next#3191]
### tdesign-vue-next 版本

1.4.2

### 重现链接

https://github.com/electron-vite/electron-vite-vue

### 重现步骤

`
App.vue
<script setup lang="ts">
import { Button as TButton } from 'tdesign-vue-next';
import _ from 'lodash';

</script>

<template>
<t-button>确定</t-button>
</template>

<style>

</style>
`

### 实际结果

main.ts:7 [Vue warn]: Unhandled error during execution of render function 
  at <TButton> 
  at <App>

### 框架版本

vue3

### 系统版本

windows

### Node版本

18

**Comment by Epxir** [comment]
其他组件正常使用

**Comment by RSS1102** [comment]
能否给一个最小的实现的demo，谢谢。

---
你可以把你最小实现错误的代码上传到github仓库，分享一下仓库链接，谢谢。

**Comment by uyarn** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/26377630/f7bdd024-e32c-4b2e-8987-35ca4ab8af57)
是这样吧？

**Comment by Epxir** [comment]
> ![image](https://user-images.githubusercontent.com/26377630/258389130-f7bdd024-e32c-4b2e-8987-35ca4ab8af57.png) 是这样吧？

对的

**Comment by uyarn** [comment]
> ![image](https://user-images.githubusercontent.com/26377630/258389130-f7bdd024-e32c-4b2e-8987-35ca4ab8af57.png) 是这样吧？应该是我们实现的部分插槽用了new Function的方式
你可以先通过`<TButton :content="xx" />`的方式暂时绕开 我们改改这个实现方式

**Comment by uyarn** [comment]
> > ![image](https://user-images.githubusercontent.com/26377630/258389130-f7bdd024-e32c-4b2e-8987-35ca4ab8af57.png) 是这样吧？
> 
> 对的

应该是我们实现的部分插槽用了new Function的方式
你可以先通过`<TButton :content="xx" />`的方式暂时绕开 我们接下来的改改这个实现方式

**Comment by uyarn** [comment]
@Epxir 升级到1.5.0的版本 可以在eletron的环境里正常使用插槽
