### ISSUE TITLE
【咨询】请问下图腾讯云的效果，是用什么组件实现的？

### ISSUE THREAD

**Issue by jamesz2011** [Tencent/tdesign-vue-next#3192]
### tdesign-vue-next 版本

1.3.11

### 重现链接

[flow.png](https://postimg.cc/8jRNGzdz)

### 重现步骤

【咨询】请问下图腾讯云的效果，是用什么组件实现的？

### 期望结果

【咨询】请问下图腾讯云的效果，是用什么组件实现的？

### 实际结果

【咨询】请问下图腾讯云的效果，是用什么组件实现的？

**Comment by jamesz2011** [comment]
[需要咨询的图片链接](https://postimg.cc/8jRNGzdz)

**Comment by AuYuHui** [comment]
> [需要咨询的图片链接](https://postimg.cc/8jRNGzdz)

你要问组件相关的。

**Comment by Likunone** [comment]
https://x6.antv.vision/zh/examples/showcase/practices#orgchart

**Comment by Likunone** [comment]
> [需要咨询的图片链接](https://postimg.cc/8jRNGzdz)

https://x6.antv.vision/zh/examples/showcase/practices#orgchart
