### ISSUE TITLE
[Cascader] keys中加入disabled的自定义字段判定

### ISSUE THREAD

**Issue by puppetsheep** [Tencent/tdesign-vue-next#3193]
### 这个功能解决了什么问题

能自自定义哪个字段会被判定为`disabled`，用来控制禁用项

### 你建议的方案是什么

```
<t-cascader v-model="value" :options="options" clearable :keys="{ disabled:'disable' }" @change="onChange" />
```

**Comment by AuYuHui** [comment]
你可以 在节点 中 设置 disabled为 true 禁用节点

{
    label: '选项一',
    value: '1',
    children: [
      {
        label: '子选项一',
        value: '1.1',
        disabled: true,
      },
      {
        label: '子选项二',
        value: '1.2',
      },
      {
        label: '子选项三',
        value: '1.3',
      },
    ],
  }

**Comment by puppetsheep** [comment]
不一定会有disabled字段，或者需要通过动态判定disabled所使用的字段时，操作起来就极为复杂。

**Comment by PengYYYYY** [comment]
这种自己处理一下数据结构就好了

**Comment by PengYYYYY** [comment]
暂时不考虑增加这样的特性，太奇怪了

**Comment by puppetsheep** [comment]
当前所有主流的vue3组件库都支持这个操作，应该不算很业务的需求了吧？

**Comment by AuYuHui** [comment]
> 当前所有主流的vue3组件库都支持这个操作，应该不算很业务的需求了吧？
哪个？

**Comment by puppetsheep** [comment]
https://arco.design/vue/component/cascader
https://www.naiveui.com/zh-CN/light/components/cascader#API
https://element-plus.org/zh-CN/component/cascader.html#%E6%9C%89%E7%A6%81%E7%94%A8%E9%80%89%E9%A1%B9
https://idux.site/components/cascader/zh?tab=api

**Comment by AuYuHui** [comment]
> https://arco.design/vue/component/cascader https://www.naiveui.com/zh-CN/light/components/cascader#API https://element-plus.org/zh-CN/component/cascader.html#%E6%9C%89%E7%A6%81%E7%94%A8%E9%80%89%E9%A1%B9 https://idux.site/components/cascader/zh?tab=api

对啊  都是在 option 设置 disabled 为 true，禁用该选项。

**Comment by AuYuHui** [comment]
都不是说 :keys="{ disabled:'disable' }" 以这种方式来 禁用选项的，你要禁用哪个 自己 控制 对应的 option 就好了

**Comment by puppetsheep** [comment]
都允许指定某字段或判定disabled的条件，例如Arco中可以直接设置 
```
 <a-cascader
      :options="allDeptList"
      :field-names="{
        value: 'id',
        label: 'title',
        children: 'children',
        disabled: 'disable',
      }"
    />
```

**Comment by AuYuHui** [comment]
> 都允许指定某字段或判定disabled的条件，例如Arco中可以直接设置
> 
> ```
>  <a-cascader
>       :options="allDeptList"
>       :field-names="{
>         value: 'id',
>         label: 'title',
>         children: 'children',
>         disabled: 'disable',
>       }"
>     />
> ```

那你可以 自己 fork一下代码 改

**Comment by puppetsheep** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/3060
https://github.com/Tencent/tdesign-vue-next/issues/2258
都是相关问题

**Comment by chaishi** [comment]
经过讨论，最终予以支持。`keys` 可以用来扩展支持所有场景的字段别名
