### ISSUE TITLE
[Checkbox 多选框] 全选 与 max 选项存在矛盾冲突

### ISSUE THREAD

**Issue by woodcoal** [Tencent/tdesign-vue-next#3197]
### tdesign-vue-next 版本

1.4.2

### 重现步骤

当设置一组多选框时，如果开启全选按钮，同时设置最大选择项，可能会存在矛盾冲突

如：我有10个多选框，但是设置了 max 为 5 时，当我手工选择了 5 个项目后其他选项将变灰无法在选择。
但是如果我开启全选按钮，那么当你点击 全选  时，它会忽略 max 参数，而将所有多选框选中。这样最大选择项将超过 5 个

**Comment by tanhh326** [comment]
我觉得吧，既然有`max`了，就不该有全选

**Comment by PengYYYYY** [comment]
> 我觉得吧，既然有`max`了，就不该有全选

+1, 有max了，全选的时候又选的是哪几个呢
