### ISSUE TITLE
[ColorPicker 颜色选择器] closeBtn 是不是忘记加上了？

### ISSUE THREAD

**Issue by woodcoal** [Tencent/tdesign-vue-next#3200]
### tdesign-vue-next 版本

1.4.2

### 重现步骤

ColorPicker 颜色选择器 中 closeBtn 设置不生效
查看库中源代码发现只做了 closeBtn 类型定义，没有实际的使用代码
莫非忘记设计了？

文档上有此说明
![image](https://github.com/Tencent/tdesign-vue-next/assets/70026047/7407ae35-7d20-4c79-b6db-cb91d8ec4b81)

实际代码搜索没有，只有类型定义
![image](https://github.com/Tencent/tdesign-vue-next/assets/70026047/8b15c53d-b864-4af3-b5ff-2edc123374e9)

**Comment by uyarn** [comment]
这个API应该是之前设计的 现在的UI 没有这个操作区域  我们改动下文档
