### ISSUE TITLE
[form] 表单数据的获取

### ISSUE THREAD

**Issue by cnjackven** [Tencent/tdesign-vue-next#3211]
### tdesign-vue-next 版本

1.4.2

### 重现步骤

`
<t-form
        ref="formRef"
        :data="formData"
        :rules="rules"
        label-width="0"
        @submit="onSubmit"
    >
`
使用formRef.value获取不到表单数据
`
RefImpl {__v_isShallow: false, dep: undefined, __v_isRef: true, _rawValue: Proxy(Object), _value: Proxy(Object)}
dep
: 
undefined
__v_isRef
: 
true
__v_isShallow
: 
false
_rawValue
: 
Proxy(Object) {validate: ƒ, submit: ƒ, reset: ƒ, clearValidate: ƒ, setValidateMessage: ƒ, …}
_value
: 
Proxy(Object) {validate: ƒ, submit: ƒ, reset: ƒ, clearValidate: ƒ, setValidateMessage: ƒ, …}
value
: 
Proxy(Object)
[[Handler]]
: 
Object
get
: 
ƒ get(target, key)
length
: 
2
name
: 
"get"
arguments
: 
[异常:TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.invokeGetter (<anonymous>:3:28)]
caller
: 
(...)
[[FunctionLocation]]
: 
runtime-core.esm-bundler.js:7440
[[Prototype]]
: 
ƒ ()
[[Scopes]]
: 
Scopes[3]
`

### 期望结果

使用formRef能获取到表单数据

**Comment by AuYuHui** [comment]
什么意思，表单数据不就是你绑定的formData 吗？

**Comment by PengYYYYY** [comment]
表单数据直接用 formData 即可，form 组件并没有 expose 出来表单数据。且为啥要用 ref 去拿数据呢。
