### ISSUE TITLE
[Form] Nuxt3最新3.6.5下，路由页面模式中编译失败

### ISSUE THREAD

**Issue by chenyuncai** [Tencent/tdesign-vue-next#3213]
### tdesign-vue-next 版本

1.4.2

### 重现步骤

1. 空的nuxt3项目，使用最新版3.6.5

2. pnpm add tdesign-vue-next

3. nuxt-config 中增加modules 和 build.transpile

4. app.vue组件中增加 <NuxtPage  /> 路由组件

5. 创建pages目录，创建index.vue, 模板中使用t-form表单

### 期望结果

npm run build 正常输出

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/8945203/45f2240e-4bc8-478d-a157-3d669ec4ccc4)

### 框架版本

3.3.4

### 浏览器版本

最新115

### 系统版本

windows 11

### Node版本

18.12.1

### 补充说明

空白最新nuxt3项目，pnpm 8.6.12, node 18.12.1 nuxt 3.6.5

在没有开启pages目录，仅在app组件中引用t-form组件，运行和编译打包都正常，在新建pages目录后的index.vue文件中 使用t-form组件，dev模式运行正常，打包异常。如果增加client-only组件包括，运行打包也正常。

nuxt.config.ts
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  modules: [
    'tdesign-vue-next/es/nuxt'
  ],
  build: {
    transpile: [
      'tdesign-vue-next'
    ],
  }
})

```

pages/index.vue
```
<template>
  <t-button>按钮1</t-button>
  <t-form >
    <t-form-item label="用户名" >
      <t-input />
    </t-form-item>
  </t-form>
</template>
```

**Comment by chenyuncai** [comment]
https://codesandbox.io/p/sandbox/relaxed-orla-3dcqhc 

下方打开terminal, 直接运行npm run build

**Comment by uyarn** [comment]
fixed in 1.9.0
