### ISSUE TITLE
Transfer 穿梭框  UI不对齐

### ISSUE THREAD

**Issue by carson-repository** [Tencent/tdesign-vue-next#3214]
### tdesign-vue-next 版本

1.4.2

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/42593750/d4d77caf-fd5f-48c4-8c82-4a5797a131ac)

<t-transfer v-model="targetValue" theme="primary" :data="list" @change="onChange" />

const list = ref([]);
const targetValue = ref([]);
const onChange = (newTargetValue: any) => {
  console.log('onChange', newTargetValue);
};

### 实际结果

ui不对齐

### 浏览器版本

Chrome  版本 115.0.5790.171（正式版本） （64 位）

### 系统版本

Win 11

### Node版本

v16.20.0

**Comment by PengYYYYY** [comment]
<img width="590" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/35833812/fa9bc867-8e4d-40cb-b40d-2cb40b637964">

**Comment by PengYYYYY** [comment]
看官网好像没什么问题，可以给个复现的链接吗

**Comment by uyarn** [comment]
页面模板的代码问题 把这部分修改掉
<img width="347" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/3b92aff0-801f-48ba-addf-a54a01778dc8">

**Comment by carson-repository** [comment]
不修改这部分 对transfer修改 margin-left: 0 好像无效 @uyarn

**Comment by uyarn** [comment]
@carson-repository https://github.com/Tencent/tdesign-vue-next-starter/pull/586 麻烦参考这个修改下
