### ISSUE TITLE
[ImageViewer] 层级问题

### ISSUE THREAD

**Issue by freeopsvue** [Tencent/tdesign-vue-next#3221]
### tdesign-vue-next 版本

1.4.2

### 重现链接

无

### 重现步骤

在dialog中使用图片预览组件时，图片预览组件层级比dialog层级要低，导致预览弹窗被遮挡

### 期望结果

不被遮挡

### 实际结果

被遮挡

**Comment by sinbadmaster** [comment]
Dialog与ImageViewer都是可以自定义层级的
