### ISSUE TITLE
input组件，type是number的时候，火狐、ie浏览器能输入非数值类型

### ISSUE THREAD

**Issue by zmlHappyCoding** [Tencent/tdesign-vue-next#3222]
<img width="1728" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/30590132/103292e5-088c-4f1e-b9ea-1be5ad33d1f0">

v1.4.2最新版本也存在

**Comment by Ericleungs** [comment]
这个input的type其实最后也会写进去原生的input的type属性中。这个和浏览器有关，Firefox允许在type=number的情况下写入非数字。
可以自己写onkeypress事件、或者在submit中验证是否为数字来规避这点
参见：
https://bugzilla.mozilla.org/show_bug.cgi?id=1398528
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/input/number
