### ISSUE TITLE
切换页面时，新菜单会从底部从下向上滑动得动画，请问如何关闭

### ISSUE THREAD

**Issue by carson-repository** [Tencent/tdesign-vue-next#3226]
### tdesign-vue-next 版本

1.4.2

**Comment by PengYYYYY** [comment]
是哪个组件？

**Comment by carson-repository** [comment]
https://github.com/Tencent/tdesign-vue-next/assets/42593750/0c7c3e9a-acf3-4e90-9698-09c15b1a64d5

@PengYYYYY 这个可以看清楚么 就是切换菜单的时候  右边得界面会有一个从下到上得滑动

**Comment by AuYuHui** [comment]
> 4abf2bdf9eeaa4921d9adcdc46f913c9.mp4 
> @PengYYYYY 这个可以看清楚么 就是切换菜单的时候 右边得界面会有一个从下到上得滑动

这个是你自己布局没写好
