### ISSUE TITLE
[MessagePlugin] MessagePlugin使用options传参时，不生效

### ISSUE THREAD

**Issue by yuzunyue** [Tencent/tdesign-vue-next#3246]
### tdesign-vue-next 版本

1.5.1

### 重现链接

https://stackblitz.com/edit/yjbcwk?file=src%2Fdemo.vue

### 重现步骤

1、参考官网描述，使用MessagePlugin.config，游览器提示MessagePlugin.config is not a function
![image](https://github.com/Tencent/tdesign-vue-next/assets/32872977/71f6dd48-322d-48d0-8a8e-8c67d175447c)
![image](https://github.com/Tencent/tdesign-vue-next/assets/32872977/d938beb8-5d49-470e-9d18-ad0e9739cd93)
2、根据声明文件描述，MessagePlugin.error可以使用MessageInfoOptions，但是调用后，onClose事件未生效
![image](https://github.com/Tencent/tdesign-vue-next/assets/32872977/4705b3a6-ee92-4b10-898b-5200e2ec6871)
![image](https://github.com/Tencent/tdesign-vue-next/assets/32872977/79015581-3b53-4ee2-95a0-41bd5d0faa96)

### 期望结果

应满足官网描述或声明文件的写法

### 实际结果

未实现，参考复现结果

### 框架版本

3.3.4

### 系统版本

Win10

### Node版本

16.20.1

**Comment by yuzunyue** [comment]
onClose在message消失后也未生效

**Comment by Zzongke** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/65376724/9115fe63-7004-4f0c-bf49-10800f7b888a)
![image](https://github.com/Tencent/tdesign-vue-next/assets/65376724/34125e64-094b-4ee5-bd7f-407e16f5476a)
![image](https://github.com/Tencent/tdesign-vue-next/assets/65376724/c9cbd050-8a5a-45db-89f8-1405bac69ce6)
1.看了一下，估計是文檔沒說清楚，又或者裡面沒添加config的引用，不過現在看我截圖的使用方式是可以的
2.我看了一下好像沒有添加onClose事件的觸發

**Comment by huankong233** [comment]
config 函数是被移除了吗，我看类型还在，但是函数已经没了

**Comment by huankong233** [comment]
> config 函数是被移除了吗，我看类型还在，但是函数已经没了

文档里也还在
