### ISSUE TITLE
[Bug][Table] 官网 Table 固定列的表格固定两列 有问题

### ISSUE THREAD

**Issue by candy-Tong** [Tencent/tdesign-vue-next#325]
## tdesign-vue-next

You will open a bug issue at tdesign-vue-next。

### Describe Environment

browser version: Chrome
tdesign-vue-next version:

### Describe the bug

[codesandbox online demo:](https://tdesign.tencent.com/vue-next/components/table#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4%E5%92%8C%E5%88%97%E7%9A%84%E8%A1%A8%E6%A0%BC)

![image](https://user-images.githubusercontent.com/20377280/154257625-42fbfff4-0cc7-458f-87ce-f3e76a62b283.png)

**Comment by pengYYYYY** [comment]
0.9.0 已修复
