### ISSUE TITLE
[所有组件] 能否统一样式 error与danger 建议统一为一个或者通用

### ISSUE THREAD

**Issue by woodcoal** [Tencent/tdesign-vue-next#3251]
### 这个功能解决了什么问题

同样为了表示危险颜色，为什么还区分为 danger 和 error ？

![image](https://github.com/Tencent/tdesign-vue-next/assets/70026047/5a9d1e3c-cd1a-4957-986e-c96d16c0a92b)

![image](https://github.com/Tencent/tdesign-vue-next/assets/70026047/c23cbf49-825e-4fa7-a486-622559cc5c02)

### 你建议的方案是什么

建议统一使用为一个 error 或者 danger

**Comment by sertceps** [comment]
级别不一样吧，不建议统一。

**Comment by qihuantian1** [comment]
同问
