### ISSUE TITLE
[Table] 【select-on-row-click】和【expand-on-row-click】只要其中一个为true行展开和选中行都会同时触发

### ISSUE THREAD

**Issue by NJR10byh** [Tencent/tdesign-vue-next#3254]
### tdesign-vue-next 版本

1.5.1

### 重现链接

https://stackblitz.com/edit/vitejs-vite-5kayms?file=src%2Fcomponents%2FHelloWorld.vue

### 重现步骤

设置【select-on-row-click】和【expand-on-row-click】其中一个为true

### 期望结果

设置【select-on-row-click】为false 【expand-on-row-click】为true时，只触发行展开不触发选中行

### 实际结果

设置【select-on-row-click】为false 【expand-on-row-click】为true时，行展开和选中行同时触发

### 框架版本

Vue(3.2.42)

### 浏览器版本

116.0.1938.43

### 系统版本

macOS 13.5

### Node版本

v18.16.1

**Comment by chaishi** [comment]
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2719
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/3260

**Comment by uyarn** [comment]
fixed in 1.5.2
