### ISSUE TITLE
[menu] 顶部双层菜单中，子菜单中menu-item的click事件无效

### ISSUE THREAD

**Issue by cxw0218** [Tencent/tdesign-vue-next#3256]
### tdesign-vue-next 版本

是的

**Comment by cxw0218** [comment]
<t-head-menu default-value="1-1" :default-expanded="expanded">
      <template #logo>
        <img
          height="28"
          src="https://tdesign.gtimg.com/site/baseLogo-light.png"
          alt="logo"
        />
      </template>
      <t-submenu value="1">
        <template #title>
          <span>菜单1</span>
        </template>
        <t-menu-item value="1-1" @click="handleClick">子菜单1-1</t-menu-item>
        <t-menu-item value="1-2" @click="handleClick">子菜单1-2</t-menu-item>
        <t-menu-item value="1-3" @click="handleClick">子菜单1-3</t-menu-item>
      </t-submenu>
      <t-submenu value="2">
        <template #title>
          <span>菜单2</span>
        </template>
        <t-menu-item value="2-1">子菜单2-1</t-menu-item>
        <t-menu-item value="2-2">子菜单2-2</t-menu-item>
        <t-menu-item value="2-3">子菜单2-3</t-menu-item>
      </t-submenu>
      <t-submenu value="3">
        <template #title>
          <span>菜单3</span>
        </template>
        <t-menu-item value="3-1">子菜单3-1</t-menu-item>
        <t-menu-item value="3-2">子菜单3-2</t-menu-item>
        <t-menu-item value="3-3">子菜单3-3</t-menu-item>
      </t-submenu>
      <t-submenu value="4">
        <template #title>
          <span>菜单4</span>
        </template>
        <t-menu-item value="4-1">子菜单4-1</t-menu-item>
        <t-menu-item value="4-2">子菜单4-2</t-menu-item>
        <t-menu-item value="4-3">子菜单4-3</t-menu-item>
      </t-submenu>
      <t-submenu value="5">
        <template #title>
          <span>菜单5</span>
        </template>
        <t-menu-item value="5-1">子菜单5-1</t-menu-item>
        <t-menu-item value="5-2">子菜单5-2</t-menu-item>
        <t-menu-item value="5-3">子菜单5-3</t-menu-item>
      </t-submenu>
      <t-submenu value="6">
        <template #title>
          <span>菜单6</span>
        </template>
        <t-menu-item value="6-1">子菜单6-1</t-menu-item>
        <t-menu-item value="6-2">子菜单6-2</t-menu-item>
        <t-menu-item value="6-3">子菜单6-3</t-menu-item>
      </t-submenu>
      <template #operations>
        <t-button variant="text" shape="square">
          <template #icon><t-icon name="search" /></template>
        </t-button>
        <t-button variant="text" shape="square">
          <template #icon><t-icon name="mail" /></template>
        </t-button>
        <t-button variant="text" shape="square">
          <template #icon><t-icon name="user" /></template>
        </t-button>
        <t-button variant="text" shape="square">
          <template #icon><t-icon name="ellipsis" /></template>
        </t-button>
      </template>
    </t-head-menu>
script setup lang="ts">
import { ref } from "vue";

const expanded = ref(["1"]);

const handleClick = () => {
  alert(111);
};

**Comment by uyarn** [comment]
fixed in 1.5.2
