### ISSUE TITLE
[WIP] 组件库计划与待认领任务

### ISSUE THREAD

**Issue by PengYYYYY** [Tencent/tdesign-vue-next#326]
## 🌈 组件开发事项

一些需要开发的事项，有兴趣的同学可以在下方评论认领。

|  事项  |  描述  | 预期完成时间 | 状态 |
| ----- | ------ | ---- | ---- | 
| Search 组件 |  新组件开发，#653  | 无 | @sommouns 开发中 |
| Timeline 组件 |  新组件开发，#652  | 无 | 待认领 |
| ImageViewer 组件 |  新组件开发，#628  | 无  | @sufuwang 开发中 |

##  🔨 基础类工作
|  事项  |  描述  | 状态 |
| ----- | ------ | ---- | 
| 单元测试规范  |  单元测试开发流程最佳实践  | 进行中 @pengYYYYY   | 
| `Nuxt` 支持 |  增加 `nuxt-starter` 的组件示例 [tdesign-vue-next-nuxt-starter](https://github.com/yixiaco/tdesign-vue-next-nuxt-starter) | 测试中  | 

## 🚀  TODO
|  事项  |  描述  | 状态 |
| ----- | ------ | ---- | 

##   ✅  Done
|  事项  |  描述  | 时间 |
| ----- | ------ | --------- |
| pnpm |  仓库接入 `pnpm`，仓库无 `lock` 文件，开发者自行接入，增加 `pnpm.lock ignore`  | 2.21 |
| 移除 useEmitEvent  |  移除非必要的 `useEmitEvent`  |  3.09 #413  |
| 语法糖更新时机 |  先更新 `modelvalue` 然后执行 `onChange` 方法   | 3.11  #430 |
| classPrefix  |  完成，相关清单在 `comment` |  3.18 | 
|  tag-input  |  `select-input` 单选 `inputValue` 受控问题  |  3.23 #476  |
| Dialog 组件 |  实现 `showInAttachedElement`  属性  | 5.5 #695   |
| Swiper 组件 |  新组件开发  | #629 |
| 单元测试切换vitest |  框架基础  | #723 |
| 代码优化|  去除组件 `withInstallType`  | #818  |
| 受控与非受控 |  去除高阶组件 `mapProps`  | 完成  |
| Tree  |  可拖拽树 | #1119 | 
| Upload  |  文件重名上传 API，`allowUploadDuplicateFile`   | https://github.com/Tencent/tdesign-vue-next/pull/1187 | 
| TagInput  |  可拖拽调整顺序的标签输入框，可参考react实现 https://github.com/Tencent/tdesign-react/blob/develop/src/tag-input/TagInput.tsx  |  #1271  | 
| alert  |  关闭按钮value使用错误  | https://github.com/Tencent/tdesign-vue-next/pull/1275/commits/3ea5cf4a5c2c73c9d4fc06b1e7c7f64375a68fc1 | 
| Select  |  虚拟滚动  | https://github.com/Tencent/tdesign-vue-next/pull/1451 | 

[相关讨论的结论](https://github.com/Tencent/tdesign-vue-next/wiki/%E4%BB%93%E5%BA%93%E7%9B%B8%E5%85%B3%E8%AE%A8%E8%AE%BA%E7%9A%84%E7%BB%93%E8%AE%BA)

**Comment by pengYYYYY** [comment]
去除高阶组件 mapProps
- [ ] cascader
- [ ] checked
- [ ] DatePicker
- [ ] Input
- [ ] InputNumber
- [ ] Menu
- [ ] Pagination
- [ ] Popup
- [ ] Radio
- [ ] Select
- [ ] Slider
- [ ] Steps
- [ ] Table
- [ ] Tabs
- [ ] Textarea
- [ ] TimePicker
- [ ] Tooltip
- [ ] Transfer
- [ ] Tree
- [ ] TreeSelect
- [ ] Upload
- [ ] PopConfigrm https://github.com/Tencent/tdesign-vue-next/pull/410

**Comment by pengYYYYY** [comment]
commonClassName && prefix 迁移清单

#414 

- [ ] notification
- [ ] pagination
- [ ] popconfirm
- [ ] popup
- [ ] progress
- [ ] radio
- [ ] select
- [ ] select-input
- [ ] skeleton
- [ ] slider
- [ ] steps
- [ ] swiper
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] tag
- [ ] tag-input
- [ ] textarea
- [ ] time-picker
- [ ] tooltip
- [ ] transfer
- [ ] tree
- [ ] tree-select

**Comment by morningbao** [comment]
认领TODO：upload-文件重名上传 API，allowUploadDuplicateFile

**Comment by pengYYYYY** [comment]
<img width="843" alt="企业微信截图_af20e848-0d62-458d-a5aa-050f1e4fbc09" src="https://user-images.githubusercontent.com/35833812/185053668-b4d5adda-bb3b-42f9-a6da-92db137a3689.png">
