### ISSUE TITLE
[t-transfer和t-tree] 自定义label和value时不展示label，点击项没反应

### ISSUE THREAD

**Issue by jasonxxp** [Tencent/tdesign-vue-next#3264]
### tdesign-vue-next 版本

1.5.1

### 重现步骤
https://codesandbox.io/s/tdesign-vue-demo-forked-lrc3zh?file=/src/demo.vue 代码在这

<template>
  <t-dialog :visible="true" width="520px" header="设置" @onClose="close">
    <t-transfer
    v-model="targetValue"
    :data="permsData"
    @change="onChange"
    @checked-change="handleCheckedChange"
    :keys="{label:'name',value:'id'}"
  >
    <template #title="props">
      <div>{{ props.type === 'target' ? '已添加' : '未添加' }}</div>
    </template>
    <template #tree="slotProps">
      <t-tree v-bind="slotProps" checkable hover expand-all transition :keys="{label:'name',value:'id'}"/>
    </template>
  </t-transfer>
  </t-dialog>
</template>

<script setup>
import { ref } from 'vue';

const permsData = [{ "id": 100, "type": 0, "name": "name1", "children": [{ "id": 1000, "type": 0, "name": "name2", "children": [{ "id": 10000, "type": 1, "name": "name3", "children": null }, { "id": 10001, "type": 1, "name": "name4", "children": null }, { "id": 10002, "type": 1, "name": "name5", "children": null }, { "id": 10003, "type": 1, "name": "name6", "children": null }] }, { "id": 1001, "type": 0, "name": "name7", "children": [{ "id": 10004, "type": 1, "name": "name8", "children": null }, { "id": 10005, "type": 1, "name": "name9", "children": null }] }] }];

const targetValue = ref([10003]);
const checkedRef = ref([]);

const handleCheckedChange = ({ checked, sourceChecked, targetChecked, type }) => {
  checkedRef.value = checked;
  console.log('handleCheckedChange', {
    checked,
    sourceChecked,
    targetChecked,
    type,
  });
};

const onChange = (newTargetValue) => {
  console.log('onChange', newTargetValue);
};
</script>

这个例子下，label不展示，点击项没反应

### Node版本

18.14.2

**Comment by jasonxxp** [comment]
https://codesandbox.io/s/tdesign-vue-demo-forked-lrc3zh?file=/src/demo.vue

**Comment by uyarn** [comment]
https://stackblitz.com/edit/ascpx7?file=package.json,src%2Fdemo.vue
