### ISSUE TITLE
upload 单文件/图片拖拽上传 非自动 图片文件上传 选择文件后缩略图不显示

### ISSUE THREAD

**Issue by 395363335** [Tencent/tdesign-vue-next#3273]
### tdesign-vue-next 版本

1.5.2

### 重现步骤

1.3.5版本中该功能完好，后续1.4之后就bug了
非自动上传模式，图片文件，选择图片后缩略图不显示

![image](https://github.com/Tencent/tdesign-vue-next/assets/103189142/450bbdce-ba16-4f19-8400-2aaee77433a0)

### 期望结果

尽快把，升级新版本后，原有功能受限，就纠结了

### 实际结果

1.3版本该功能是正常的
![image](https://github.com/Tencent/tdesign-vue-next/assets/103189142/b6153a43-03b5-48ab-a2e2-a8909cdb6daf)

### 浏览器版本

chrome104

### 系统版本

window11

### Node版本

16.16.0

**Comment by 395363335** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。

**Comment by chaishi** [comment]
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/3276
Vue2 resolved in https://github.com/Tencent/tdesign-vue/pull/2741
