### ISSUE TITLE
封装t-tabs后  无法使用 v-for 生成 t-tab-panel 

### ISSUE THREAD

**Issue by zzc69** [Tencent/tdesign-vue-next#3281]
### tdesign-vue-next 版本

^1.5.2

### 重现链接

https://codesandbox.io/p/sandbox/green-forest-29vpj7?file=/src/App.vue

### 重现步骤

引入组件 TestTabs  v-for 生成 t-tab-panel 

### 期望结果

能正确渲染 t-tab-panel 

### 框架版本

3.2.31

### 浏览器版本

chrome  116.0.5845.110（正式版本） （64 位）

### 系统版本

win 10

### Node版本

18.12.1

**Comment by zzc69** [comment]
v1.5.3问题依旧存在

**Comment by Zz-ZzzZ** [comment]
奇怪了我在本地测试完后才提交的，完全复制codesandbox的代码一点没改
![1693445735667](https://github.com/Tencent/tdesign-vue-next/assets/48228016/52d5f58d-96cf-4fba-a386-1c07203334d7)
![1693445748377(1)](https://github.com/Tencent/tdesign-vue-next/assets/48228016/779a6990-a8ea-4650-8665-a2afc42b3a06)
我重新打开看了一下也没什么问题
![1693445764009](https://github.com/Tencent/tdesign-vue-next/assets/48228016/5b8f142c-bfae-4d75-ba7b-9af24d162bab)

**Comment by Zz-ZzzZ** [comment]
https://stackblitz.com/edit/cgtsuq?file=src%2Fdemo.vue
检查一下你的代码和依赖，我从文档里开了个`stackblitz`完全复制了你的代码没有问题的

**Comment by Zz-ZzzZ** [comment]
@zzc69 @uyarn

**Comment by zzc69** [comment]
删除node_modules后，重装依赖已经生效

**Comment by uyarn** [comment]
@Zz-ZzzZ I see~
