### ISSUE TITLE
[EnhancedTable] expandedTreeNodes属性没有效果

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#3282]
### tdesign-vue-next 版本

1.5.2

### 重现链接

https://stackblitz.com/edit/h1ui3y?file=src%2Fdemo.vue

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/30982989/4b890dca-1a42-4991-9493-40a7afed5477)
这属性不知道怎么回事，展开时既不回写，赋值时也没效果
```vue
<template>
  <t-enhanced-table
        ref="tableRef"
        v-model:column-controller-visible="columnControllerVisible"
        v-model:expanded-tree-nodes="expandedTableTree"
        hover
        :loading="loading"
        :data="menuList"
        row-key="menuId"
        :columns="columns"
        :column-controller="{
          hideTriggerButton: true,
        }"
        :tree="{ childrenKey: 'children', treeNodeColumnIndex: 0, expandTreeNodeOnClick: true }"
        :sort="sort"
        show-sort-column-bg-color
        @sort-change="handleSortChange"
      >
        </template>
      </t-enhanced-table>
</template>
<script lang="ts" setup>
const expandedTableTree = ref([]);
...
</script>
```

### 框架版本

Vue(3.3.4) Vite(4.4.9)

### 浏览器版本

Chrome 版本 115.0.5790.171

### Node版本

1.16.15

**Comment by chaishi** [comment]
https://tdesign.tencent.com/vue-next/components/table
我试了下，官网展开有效果

**Comment by chaishi** [comment]
提 issue， “重现链接”一栏属于必填信息，否则无法证明一定是组件本身的问题。如果我们自己尝试无法复现，issue 会被立即关闭

**Comment by yixiaco** [comment]
> 提 issue， “重现链接”一栏属于必填信息，否则无法证明一定是组件本身的问题。如果我们自己尝试无法复现，issue 会被立即关闭
稍等

**Comment by chaishi** [comment]
https://stackblitz.com/edit/6bfwes?file=package.json,src%2Fdemo.vue
辛苦 在这个链接里面复现你的问题后，保存代码。

<img width="210" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/7c8a1c2e-c641-4dd5-a168-a09514286371">

**Comment by yixiaco** [comment]
@chaishi 链接已经更新上去了，在stackblitz测试这个属性有时候确实有值，但是我在本地运行一直是获取不到值的

**Comment by yixiaco** [comment]
@chaishi 这个问题有下文吗，还是说测试了还是没有问题呢

**Comment by chaishi** [comment]
stackblitz 里面可以复现的问题，才好说明是组件本身的问题，需要修复。
上面提供的链接默认没有选中，手动操作也是正常展开和收起的，没有发现问题。
链接里面尝试设置 `const expandedTableTree = ref(['first_level_1']);` 也是没有问题的。

如果 stackblitz 链接里面无法复现问题，大概率说明组件本身没有问题。

如果 你本地有问题，请检查自己正在使用的版本号是否正确，以及本地是否有什么缓存问题。
https://tdesign.tencent.com/vue-next/changelog 这里面可以查询最新的版本号。
