### ISSUE TITLE
[Watermark] 在暗色模式下无法看见水印

### ISSUE THREAD

**Issue by colaiven** [Tencent/tdesign-vue-next#3285]
### tdesign-vue-next 版本

1.5.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/watermark?tab=demo

### 重现步骤

进入demo切换暗色模式

### 期望结果

在各种背景色下都能够清晰的看见水印

建议加一个能调整水印字体颜色的api

**Comment by LadyChatterleyLover** [comment]
已经有fontColor这个属性了，注意看下文档
