### ISSUE TITLE
[guide] 开发者自定 改变current时机

### ISSUE THREAD

**Issue by Wesley-0808** [Tencent/tdesign-vue-next#3286]
### 我的需求
目前Guide Props API有onNextStepClick以及onPrevStepClick两个Function，在默认状态下点击下一步/上一步将由TGuide直接改变current，当遇到 “下一步的挂载元素（高亮节点element）未出现（未渲染出来）” 的时候就非常蛋疼。。
### 我的想法
添加两个新的Props API，对应上一步和下一步，就如有几个组件（具体是哪个我忘了），当改API传入方法时就调用传入的方法（需要用户改变current），否则调用TGuide的自带的方法改变Current。
这样让用户（开发者）决定什么时候改变这个current，而不是点击下一步立马跳。因为有些操作（渲染组件）需要点时间
我之前的Issue中也有提到过：<ul><li>https://github.com/Tencent/tdesign-vue-next/issues/2536</li></ul>

### 我的代码逻辑
guide点击下一步时需要渲染组件（动态渲染），默认改变current会报错（找不到element）。

### 你建议的方案是什么

如上所述

**Comment by Wesleyyy0808** [comment]
### @zhangpaopao0609 张哥能给个建议否？我确实找不到平替方法，比如：多个guide -->导致显示的步骤会少，但是功能能实现、在当前版本下直接修改guide代码，以达目标 --> 只要TD新版本修复Bug后需要再次更新修改
## 感觉是一个两难问题......
