### ISSUE TITLE
[EnhancedTable] 树形结构的表格添加拖拽排序后显示位置错误，且 defaultExpandAll 无效

### ISSUE THREAD

**Issue by SBDaQingWa** [Tencent/tdesign-vue-next#3295]
### tdesign-vue-next 版本

1.5.2-1.5.3

### 重现链接

https://stackblitz.com/edit/6bfwes-mgw7hw?file=src%2Fdemo.vue

### 重现步骤

树形结构的表格添加拖拽排序后显示顺序错误，最后一个父节点的子节点内容出现在表格最上方，而且 tree.defaultExpandAll 无效，1.5.1 版本时没有这些问题

### 期望结果

表格显示正确

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/17967875/08fce914-6957-4eb2-9d18-cf9469115760)
行顺序显示错误，且拖动排序结果错乱，tree.defaultExpandAll 无效

### 框架版本

Vue(3.3.4)

### 浏览器版本

Microsoft Edge 版本 116.0.1938.62 (正式版本) (64 位)

**Comment by chaishi** [comment]
关于最后一个节点展开
<img width="1553" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/e3ceed15-07bc-482c-a0c9-165996a8f06f">

**Comment by uyarn** [comment]
released in 1.5.4

**Comment by yudan215** [comment]
1.10.2 defaultExpandAll又无效了
