### ISSUE TITLE
Tree 树 组件我想默认选中一个需要怎么实现？？

### ISSUE THREAD

**Issue by imaxun** [Tencent/tdesign-vue-next#3298]
### 这个功能解决了什么问题

Tree 树 组件我想默认选中一个需要怎么实现？？

### 你建议的方案是什么

Tree 树 组件我想默认选中一个需要怎么实现？？

**Comment by TabSpace** [comment]
使用 defaultCheck 属性。
或者 checked 属性传入这个 value。
