### ISSUE TITLE
[Table] 使用 i18n 动态定义 title 标题后，filter 过滤结果行没有显示相应的文案

### ISSUE THREAD

**Issue by puppetsheep** [Tencent/tdesign-vue-next#3303]
### tdesign-vue-next 版本

1.5.3

### 重现步骤

引入`useI18n`的`t`函数
在`columns`的`title`中写为 `()=> t('name')`  ，再补充filter属性为input
执行filter搜索
出现结果为`搜索“() => t("name")：223”，找到 0 条结果`
当`filter`的type为选择器时，options也无法支持到响应式

### 期望结果

执行filter后，显示为正常的i18n文案
filter选择器的options支持i18n的响应式

### 框架版本

Vue 3.3x

### 浏览器版本

Edge 113

### 系统版本

Windows 11

### Node版本

18.15

**Comment by chaishi** [comment]
<img width="712" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/b7ca734e-2a71-4775-abf0-6f0579285298">

我看代码里面的搜索结果文本，很早之前就已经调整为全局配置，动态变量。不知道如何复现你的问题。

纯文本描述，可能会因为彼此对名字的理解不同有歧义。请在下面的链接中提供一个示例代码，能复现描述的问题最好。
https://stackblitz.com/edit/z53atc?file=package.json,src%2Fdemo.vue 
代码修改后，保存代码，复制粘贴新的链接到 issue。（以后提 issue 也辛苦使用同样的流程，减少彼此的沟通障碍、沟通时间）

如果长时间只有纯文本，没有在上述链接中提供可复现问题的代码， issue 会被直接关闭。

**Comment by chaishi** [comment]
经过线下 和 uyarn 沟通，已了解当前 issue 问题。修复如下，

Vue2 fixed in https://github.com/Tencent/tdesign-vue/pull/2771
Vue3 fixed in https://github.com/Tencent/tdesign-vue-next/pull/3321
