### ISSUE TITLE
[tree] 使用可过滤的树

### ISSUE THREAD

**Issue by yunnet** [Tencent/tdesign-vue-next#3317]
### tdesign-vue-next 版本

1.5.3

### 重现链接

https://tdesign.tencent.com/vue-next/components/tree#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E6%A0%91

### 重现步骤

使用可过滤的树时，当搜索一个label后，去掉搜索框的内容，树节点全部展开，再也无法收缩了

### 期望结果

去掉搜索框的内容后，所有节点，可以任意收缩或展开

**Comment by Zz-ZzzZ** [comment]
Hello，重现链接我点进去似乎没用，直接跳转到首页了

**Comment by liweijie0812** [comment]
设置 allow-fold-node-on-filter  
<img width="841" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/10710889/ead1de6b-bca4-4cb9-b70f-2b8490be6d2a">

**Comment by yunnet** [comment]
> ###

谢谢。
