### ISSUE TITLE
官网文档页面跳转bug

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#3332]
### tdesign-vue-next 版本

1.5.3

### 重现链接

https://tdesign.tencent.com/starter/

### 重现步骤

官网先到“页面模板”页面，然后点击 基础组件-Vue Next，页面不会跳转还是停留在“页面模板”

### 期望结果

正常跳转页面

### 实际结果

停留在当前页面，不会跳转

**Comment by uyarn** [comment]
已恢复
