### ISSUE TITLE
[Bug][Upload] theme="image"下，Remove删除按钮无法点击，官网演示的【upload】【图片上传】中也一样

### ISSUE THREAD

**Issue by ceword** [Tencent/tdesign-vue-next#334]
### 重现链接
https://tdesign.tencent.com/vue-next/components/upload

### 重现步骤
theme="image"下：
1. 点击上传按钮；
2. 点击删除按钮  => BUG：Remove删除按钮无法点击及触发事件

### 期望结果
删除图片及事件触发

### 实际结果
图片未删除，删除事件未触发

### 补充说明
官网的upload演示里，图片上传那里就能看到bug

| Environment | Info |
|---|---|
| 相关版本 | 0.8.1 |
| 框架版本 / 基础库版本 | Vue(3.2.25) |
| 系统、浏览器 | Microsoft Edge Version 98.0.1108.55 (Official build) (64-bit) |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
0.9.0 已修复
