### ISSUE TITLE
[Icon] 在ts中使用组件，提示：没有导出的成员

### ISSUE THREAD

**Issue by Lijianganggg** [Tencent/tdesign-vue-next#3348]
### tdesign-vue-next 版本

^1.4.2

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/36977035/237ec289-0c7f-4b16-8095-7160daeb25fb)

![image](https://github.com/Tencent/tdesign-vue-next/assets/36977035/cfea31a8-3f44-4e37-a0c5-2b189710df71)
"dependencies": {
"tdesign-icons-vue-next": "^0.2.2",
}
![image](https://github.com/Tencent/tdesign-vue-next/assets/36977035/b749c3f6-128f-4f95-b95d-5084d57d5fd6)

### 期望结果

能在官网找到的图标、实际使用就能用，而不是报错不能使用！

**Comment by uyarn** [comment]
`npm list tdesign-icons-vue-next` 或者直接看看node_modules里面是不是装了0.2以上的icons
