### ISSUE TITLE
[文档] 组件 Tab 无法切换

### ISSUE THREAD

**Issue by dufu1991** [Tencent/tdesign-vue-next#3363]
### tdesign-vue-next 版本

1.5.4

### 重现链接

https://tdesign.tencent.com/vue-next/components/table?tab=demo

### 重现步骤

当顶部切换【示例/API/指南】这个 Tab ，在下层的表格演示区域或代码区域上层时，点击 Tab 无法切换，光标聚焦的是下层区域。
猜测这个 Tab 使用了定位，又启用了点击穿透导致这个问题。

<img width="1473" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/24769077/e91e902a-037a-4d06-afb7-aa3306108a62">

### 期望结果

能正常跳转

### 实际结果

有时无法跳转，有时又正常。

### 浏览器版本

Arc 1.7.0(chromium Version 116.0.5845.179)

### Node版本

与 Node 无关

**Comment by uyarn** [comment]
没有复现 录个屏看看？

**Comment by dufu1991** [comment]
Screen-2023-09-18-143548.mp4

**Comment by dufu1991** [comment]
https://github.com/Tencent/tdesign-vue-next/assets/24769077/7c59e71f-db6e-4cd5-a2cb-3f39794247e0

**Comment by PengYYYYY** [comment]
目前线上已无该问题
