### ISSUE TITLE
请问后面会加图表组件吗

### ISSUE THREAD

**Issue by XAllure** [Tencent/tdesign-vue-next#3367]
### 这个功能解决了什么问题

图表组件还是很重要的 不知道有没有可能在ui组件上添加图表组件·呢 

### 你建议的方案是什么

图表组件还是很重要的 不知道有没有可能在ui组件上添加图表组件·呢

**Comment by yh0820** [comment]
这个感觉可能性不大，市面上已经有完整成熟的图表组件库了，在tdesgin里加上无疑是加大体积。

**Comment by uyarn** [comment]
definitely not. 图表组件不会出现在tdesign的包里。
