### ISSUE TITLE
[Loading] 显示异常

### ISSUE THREAD

**Issue by 17683813062** [Tencent/tdesign-vue-next#3368]
### tdesign-vue-next 版本

1.5.2

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/d77e7710-1b9e-4492-9f54-5842d83af31e)
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/c099200a-22b6-4301-ac12-8615361c3c43)
以上这样写加载的好像是全局

![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/a15c8bd0-95cc-440f-b4a8-12031a8dde73)
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/c3cb3e94-f4c5-458f-8095-3850e6a76f80)
以上这样包裹着是显示正常的

![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/4a3547b3-f687-4f78-a65c-acfc53dcefe6)
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/fc697c7b-ca75-4d22-bb2f-41a476582bbb)
以上使用指令不显示，
![image](https://github.com/Tencent/tdesign-vue-next/assets/56809137/bca61002-bbf2-4842-9d35-80c94876c240)
控制台还报错

### 期望结果

使用指令，局部能正常显示

### 实际结果

使用指令，局部不显示

### 框架版本

Vue(3.3.4)

### 浏览器版本

Chrome(116.0.5845.97)

### 系统版本

window

### Node版本

18.12.0

**Comment by Zzongke** [comment]
给个CodeSandbox？没复现出你的问题🤣🤣🤣

**Comment by uyarn** [comment]
List没有支持过这种使用方式 目前新的版本已导出loading的diretive供使用 如果还是有这个问题可以尝试自己导入loading的directive
