### ISSUE TITLE
被包裹的按钮需手动触发才能产生样式

### ISSUE THREAD

**Issue by NavyBLLIU** [Tencent/tdesign-vue-next#337]
### 重现链接
https://codesandbox.io/s/tdesign-vue-next-demo-forked-bxpg7j?file=/src/index.css

### 重现步骤
进入页面后鼠标移入【授权添加小程序】

### 期望结果
进入页面按钮直接展示css代码样式

### 实际结果
进入页面后鼠标移入【授权添加小程序】才能触发css代码

| Environment | Info |
|---|---|
| 相关版本 | 0.8.1 |
| 框架版本 / 基础库版本 | Vue(2.6.11) |
| 系统、浏览器 | Chrome(98.0.4758.102) |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
这是未触发前的dom结构

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/35833812/155133522-89eb22d8-a2ea-478e-b58d-9335493bf776.png">

这是触发后的dom结构

<img width="1447" alt="image" src="https://user-images.githubusercontent.com/35833812/155133677-4576a663-490b-4dc9-a01c-f43ea0c8a2f6.png">

触发前，popup dom需要做占位，这段代码的css是不生效的。触发后会transform到指定的容器中。css生效，可以换一种css实现

**Comment by NavyBLLIU** [comment]
好的，3Q！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年2月22日(星期二) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tdesign-vue-next] 被包裹的按钮需手动触发才能产生样式 (Issue #337)





 
这是未触发前的dom结构
 

 
这是触发后的dom结构
 

 
触发前，popup dom需要做占位，这段代码的css是不生效的。触发后会transform到指定的容器中。css生效，可以换一种css实现
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
