### ISSUE TITLE
[LoadingPlugin]  使用函数方式调用后无法更新提示文案 text

### ISSUE THREAD

**Issue by ry0513** [Tencent/tdesign-vue-next#3370]
Loading函数方式文档：[https://tdesign.tencent.com/vue-next/components/loading?tab=demo#%E5%87%BD%E6%95%B0%E6%96%B9%E5%BC%8F%E8%B0%83%E7%94%A8](https://tdesign.tencent.com/vue-next/components/loading?tab=demo#%E5%87%BD%E6%95%B0%E6%96%B9%E5%BC%8F%E8%B0%83%E7%94%A8)

文档只有使用 LoadingPlugin  的调用方法和关闭方法，

 ```js 
  const instance = LoadingPlugin({  // 调用
    fullscreen: true,
    attach: 'body',
    preventScrollThrough: false,
    text: '加载中..',
  });
  const timer = setTimeout(() => {
    instance.hide();  // 关闭
    clearTimeout(timer);
  }, 1000);
```
请问如何更新参数呢，比如更新提示文案 `text`

**Comment by Zzongke** [comment]
声明一个响应式变量传给text就能更新的，我试一下可以更新提示，希望能帮到你
