### ISSUE TITLE
[t-select] keys无效

### ISSUE THREAD

**Issue by xf0012** [Tencent/tdesign-vue-next#3371]
### tdesign-vue-next 版本

1.4.1

**Comment by uyarn** [comment]
https://stackblitz.com/edit/b6dyr8?file=package.json,src%2Fdemo.vue 没有复现你说的问题 keys正常生效

**Comment by xf0012** [comment]
> https://stackblitz.com/edit/b6dyr8?file=package.json,src%2Fdemo.vue没有复现你说的问题密钥正常生效可以在这里复现你的问题

是Cascader联级 然后设置了check-strictly 属性
