### ISSUE TITLE
[table] 可编辑表格可以支持按下回车后跳到下一个输入框开启编辑状态

### ISSUE THREAD

**Issue by 879291903** [Tencent/tdesign-vue-next#3389]
### 这个功能解决了什么问题

<img width="248" alt="e1f2815368dfb693288649cf8b94f63" src="https://github.com/Tencent/tdesign-vue-next/assets/51746450/f13cfb35-e1c7-4003-96df-a48d16b53171">
当输入的行数过多时，鼠标点击过于繁琐，每输入完一个需要鼠标点击下一个才能进行输入。

### 你建议的方案是什么

实现按下回车结束当前这行的编辑跳入下一行开启编辑状态

**Comment by chaishi** [comment]
已支持
