### ISSUE TITLE
[t-table]固定表头无法使用

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [Tencent/tdesign-vue-next#3396]
### tdesign-vue-next 版本

1.5.6

### 重现链接

https://tdesign.tencent.com/vue-next/components/table#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4-%E5%9B%BA%E5%AE%9A%E8%A1%8C%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

按照官方文档的demo配置

### 期望结果

可以实现固定表头

### 实际结果

没有固定表头

### 补充说明

使用的官方demo都不可以

**Comment by chaishi** [comment]
重现链接是官网地址，访问了一下，可以正常固定表头。
<img width="919" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/4d3d40d8-3cbc-42d2-8c9c-1e3013f484c9”>


点击下方按钮，进去复现你的问题，然后保存代码，把新的链接贴到“重现链接”
<img width="221" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/8352f89b-84ac-42a5-beef-aab7d21cbab7">

**Comment by revilhui** [comment]
> 重现链接是官网地址，访问了一下，可以正常固定表头。
> 
> 点击下方按钮，进去复现你的问题，然后保存代码，把新的链接贴到“重现链接” <img alt="image" width="221" src="https://user-images.githubusercontent.com/11605702/269227991-8352f89b-84ac-42a5-beef-aab7d21cbab7.png">

刚测试了。谷歌浏览器可以，双核浏览器不行，应该是有兼容性
