### ISSUE TITLE
[t-tooltip]按钮禁用时tooltip无效

### ISSUE THREAD

**Issue by flowven** [Tencent/tdesign-vue-next#3397]
mac下safari，windows下chrome，当按钮禁用时，浮窗无效，代码如下
<t-tooltip content="内容" theme="light">
    <t-button disabled>删除</t-button>
</t-tooltip>

disabled去掉后tooltip有效

**Comment by chaishi** [comment]
这个行为：属于浏览器原生行为。当按钮添加 disabled 时，会同时禁用 悬浮 hover 事件。

你可以这样解决问题
```
<t-tooltip content='tips'>
  <t-button disabled tag="div">按钮</t-button>
</t-tooltip>
```
