### ISSUE TITLE
[t-popup] 弹窗跳变

### ISSUE THREAD

**Issue by LikeDege** [Tencent/tdesign-vue-next#3398]
### tdesign-vue-next 版本

1.0.4

### 重现步骤

https://github.com/Tencent/tdesign-vue-next/assets/12826345/e30ddb41-9d86-44b9-ae0f-6004d75c897b

### 框架版本

3.3.4

**Comment by chaishi** [comment]
这个是移动端吗， tdesign vue mobile ？

当前仓库是 tdesign vue3 web 组件库，不是 mobile
