### ISSUE TITLE
[t-table]固定表头无法使用

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [Tencent/tdesign-vue-next#3400]
### tdesign-vue-next 版本

1.5.6

### 重现链接

https://stackblitz.com/edit/vitejs-vite-t3hzbj?file=src%2FApp.vue,vite.config.js,package.json,src%2Fmain.js,src%2Fstyle.css,index.html&terminal=dev

### 重现步骤

表格的固定表头按照文档上的配置无法使用

### 期望结果

可以实现表格的固定表头

### 实际结果

没有固定表头

**Comment by revilhui** [comment]
同样想问这个问题，官网介绍：表格内容高度超出后，滚动时表头会自动固定。可通过 height 或 maxHeight 设置表格高度，
但官网上给出来的demo也是没有固定表头的，滚动条滚动的时候，表头还是没有固定在最上面，而是随着滚动条的滚动而隐藏了

[](https://tdesign.tencent.com/vue-next/components/table#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4-%E5%9B%BA%E5%AE%9A%E8%A1%8C%E7%9A%84%E8%A1%A8%E6%A0%BC )

**Comment by chaishi** [comment]
根据提供的链接查看，固定表头表现正常。

<img width="1511" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/9dddf4c4-4c1c-4881-a989-dea57a5f2975">

**Comment by chaishi** [comment]
表头固定有两种：
一种是固定在表头本身所在的位置，不参与 body 滚动。
另一种，则是 吸顶表头，吸附在滚动容器的顶部，默认滚动容器为 body，可以根据业务实际情况调整滚动容器，`headerAffixedTop.attach` 用于设置吸顶表头的滚动容器

**Comment by chaishi** [comment]
上述两位同学提出的问题，无法理解具体是什么错误。无法处理，issue close。
后续发现新的问题，可以创建新的 issue，然后提供一下截图，描述再详细一些。
