### ISSUE TITLE
[t-table]表格的列拖拽第一列拖至最后一列数据错乱

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [Tencent/tdesign-vue-next#3401]
### tdesign-vue-next 版本

1.5.6

### 重现链接

https://stackblitz.com/edit/vitejs-vite-gl6gpi?file=package.json,vite.config.js,src%2Fmain.js,src%2FApp.vue,src%2Fstyle.css&terminal=dev

### 重现步骤

t-table表格的列拖拽从第一列拖至第二列没问题，但是从第一列拖至最后一列，数据错乱

### 期望结果

t-table表格的列拖拽可以正常使用

### 实际结果

t-table表格的列拖拽从第一列拖至第二列没问题，但是从第一列拖至最后一列，数据错乱

**Comment by jesseice** [comment]
它的表格加上拖拽后无论col还是row都会有bug  建议使用sorttable自己再次封装一下很简单

**Comment by revilhui** [comment]
不明白为什么列拖动到最后一列就会出现列头乱的情况，都没自测的吗？？？

[列拖动](https://tdesign.tencent.com/vue-next/components/table#%E5%88%97%E6%8B%96%E6%8B%BD%E6%8E%92%E5%BA%8F)

**Comment by jesseice** [comment]
https://stackblitz.com/edit/vitejs-vite-v6bvrb?file=package.json,vite.config.js,src%2Fmain.js,src%2FApp.vue,src%2Fstyle.css&terminal=dev
手动强制更新一下表格

**Comment by revilhui** [comment]
这是bug吧，这不应该是表格内部处理好么？？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月25日(周一) 下午3:37
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Tencent/tdesign-vue-next] [t-table]表格的列拖拽第一列拖至最后一列数据错乱 (Issue #3401)




 
https://stackblitz.com/edit/vitejs-vite-v6bvrb?file=package.json,vite.config.js,src%2Fmain.js,src%2FApp.vue,src%2Fstyle.css&amp;terminal=dev
 手动强制更新一下表格

**Comment by chaishi** [comment]
Vue3 数据响应式和 sortablejs 不兼容问题
<img width="1511" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/e037e739-4347-4c16-ad4f-cb774fdfb0a6">

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/3968

修复效果如下：

https://github.com/Tencent/tdesign-vue-next/assets/11605702/155cf582-0b6e-4978-ba44-49736d5973a0

**Comment by uyarn** [comment]
fixed 1.9.0
