### ISSUE TITLE
[列表] 列表的滚动条能优化一下吗

### ISSUE THREAD

**Issue by XAllure** [Tencent/tdesign-vue-next#3406]
### 这个功能解决了什么问题

<img width="525" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/66450680/9bd9aa34-60da-4bc4-9465-7a63f8b34733">

### 你建议的方案是什么

美化一下列表的滚动条

**Comment by imyeyu** [comment]
伪类 -webkit-scrollbar 可以修改，不过兼容性有限

**Comment by uyarn** [comment]
fixed in 1.6.1
