### ISSUE TITLE
[t-table] 在单元格编辑时，无法复制网页中的任何文字。

### ISSUE THREAD

**Issue by yunnet** [Tencent/tdesign-vue-next#3417]
### tdesign-vue-next 版本

1.5.7

### 重现步骤

在单元格编辑时，无法对网页中的任务字符，进行文字复制。
报错信息：
Uncaught TypeError: Cannot read properties of undefined (reading 'nextSibling')
    at HTMLDocument.onDragEnd2 (useColumnResize.ts:267:81)
![image](https://github.com/Tencent/tdesign-vue-next/assets/1326742/fd1a2a28-6796-42aa-aede-58b2993c5395)

### 期望结果

可以复制网页中任何文字

**Comment by chaishi** [comment]
是因为报错，所以无法复制么。
具体是如何复制的？

**Comment by chaishi** [comment]
长久没有回复，且无法复现，issue close

后续代码修改会对 nextSibling 属性对象添加判空
