### ISSUE TITLE
[t-upload]上传组件可否增加一个重新上传的方法

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [Tencent/tdesign-vue-next#3421]
### 这个功能解决了什么问题

文件上传组件，在文件上传失败后，用户可以点击或者调用组件方法进行重新上传！

### 你建议的方案是什么

组件内部增加一个这样的方法！

**Comment by chaishi** [comment]
组件目前的上传按钮，本身就是自动上传失败的文件，无需再新增单独的方案

**Comment by xiaoshuoyiyi** [comment]
上传按钮和重新上传按钮，都是我外部定义的按钮，不使用组件内部的按钮！

**Comment by xiaoshuoyiyi** [comment]
还有，我怎么清空已上传的文件在组件上的显示

**Comment by xiaoshuoyiyi** [comment]
当autoUpload为false时
1. 怎么获取组件的待上传的文件列表数据？
2. 怎么删除待上传列表的指定文件？
