### ISSUE TITLE
[Breadcrumb] 暗黑模式下图标看不见

### ISSUE THREAD

**Issue by XAllure** [Tencent/tdesign-vue-next#3424]
### tdesign-vue-next 版本

1.5.7

### 期望结果

看清分隔图标

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/66450680/13eb47b3-26b3-492c-a9b1-b848a2a84f9c)
图标看不清

**Comment by uyarn** [comment]
fixed in 1.6.1
