### ISSUE TITLE
Select 组件使用 valueType="object" 时选中的值格式只为 { value: string, label: string }

### ISSUE THREAD

**Issue by CaptainWang98** [Tencent/tdesign-vue-next#3429]
<img width="1789" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/45689473/bc292c43-74a1-487f-b8b3-ef11ee4c6eb7">

链接如下
https://stackblitz.com/edit/uzjefr?file=package.json,src%2Fdemo.vue

```[tasklist]
### Tasks
```

**Comment by uyarn** [comment]
这个是设计如此 object本身的作用也是为了远程搜索的数据回显 所以不会包含label之外的其他值 可以在onchange的第二个参数context中获取选中option的全部内容 
refer to demo https://stackblitz.com/edit/uzjefr-rcfe4f?file=package.json,src%2Fdemo.vue
