### ISSUE TITLE
[Table] 表格对于fixed的列 会把非模态框遮挡住 至少对表格列配置弹窗是这样的

### ISSUE THREAD

**Issue by XAllure** [Tencent/tdesign-vue-next#3434]
### tdesign-vue-next 版本

1.5.7

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/66450680/538c74d0-7a55-49b2-82a1-a054ffa2ca90)

**Comment by chaishi** [comment]
当前解决方案：可以先尝试给 Dialog 设置一个更高的  zIndex

**Comment by chaishi** [comment]
尝试着浮现了一下，没有看到截图中的问题。大概率是你们的项目中设置了某个 zIndex 影响到了。
辛苦下次提供一下可复现问题的链接，这样我们可以更快速的明确问题是否存在，以及如何复现，如何解决问题

https://github.com/Tencent/tdesign-vue-next/assets/11605702/5c910ca5-4cb8-46b1-b381-581592af1861

**Comment by chaishi** [comment]
<img width="973" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/90d71e27-671b-4452-b465-bc4d44d301a5">
