### ISSUE TITLE
[Bug][Taginput]输入回车提交一定几率出现undefined

### ISSUE THREAD

**Issue by carolin913** [Tencent/tdesign-vue-next#344]
### 重现链接
https://codesandbox.io/s/jvgj0s?file=/src/demo.vue

### 重现步骤
每个demo的链接均有一定几率复现，回车提交出现undefined的tag
<img width="438" alt="wecom-temp-15fe68e3b740f563a19d4b8f9c86ca0e" src="https://user-images.githubusercontent.com/2638568/155057297-5395f9a2-c634-468f-b653-6dd98bc3a86a.png">

### 期望结果
增加输入结果检查

### 实际结果
不符合预期

| Environment | Info |
|---|---|
| 相关版本 | 0.8.1 |
| 框架版本 / 基础库版本 | vue-next(0.8.x) |
| 系统、浏览器 | MacOS, Chrome(97) |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
#https://github.com/Tencent/tdesign-vue-next/pull/369

**Comment by pengYYYYY** [comment]
0.9.3 已修复
