### ISSUE TITLE
[Loading] loading的delay属性是delay毫秒后执行，还是多执行delay毫秒？

### ISSUE THREAD

**Issue by XAllure** [Tencent/tdesign-vue-next#3441]
### tdesign-vue-next 版本

1.5.7

### 补充说明

目前我使用的时候，显示的是delay毫秒后才显示loading。就算提前执行hide方法，仍是会在delay毫秒后显示loading后才执行hide。那这样子不还是闪烁吗？感觉和说明有点不符，应该是立即显示loading，然后在调用hide时多执行delay毫秒后才销毁才对啊。
<img width="702" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/66450680/3c3f488c-5c1b-4233-a266-6c8616aaf1d5">

**Comment by uyarn** [comment]
目前是延长多少秒后执行

**Comment by uyarn** [comment]
@chaishi 这个描述好像是和实现的不符？

**Comment by XAllure** [comment]
> @chaishi 这个描述好像是和实现的不符？

那不然就应该是在delay毫秒前就执行hide了 delay毫秒后就不要再显示loading了

**Comment by uyarn** [comment]
讨论了下 这个是描述错误 本意是为了不多次出现Loading来使用 我们改下文档
