### ISSUE TITLE
[Tabs] t-tab-panel设置属性destroyOnHide为false后，该面板内的组件在App.vue加载前就已经加载

### ISSUE THREAD

**Issue by QQ2439423861** [Tencent/tdesign-vue-next#3444]
### tdesign-vue-next 版本

1.5.6

### 重现步骤

1. 使用vue3 + ts + Vite开发页面

2. 文件内容

App.vue

```vue
<template>
  <t-tabs theme="card" default-value="pannel1">
    <t-tab-panel label="选项卡1" value="pannel1">
      面板1
    </t-tab-panel>
    <t-tab-panel :destroy-on-hide="false" label="选项卡2" value="pannel2">
      <MyPannel2 />
    </t-tab-panel>
  </t-tabs>
</template>

<script setup lang="ts">
import MyPannel2 from './MyPannel2.vue';
import { onMounted } from 'vue';

onMounted(() => {
  console.log('App.vue onMounted.');
});
</script>

```

MyPannel2.vue

```vue
<template>
  <div>面板2</div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue';

onMounted(() => {
  console.log('MyPannel2.vue onMounted.');
});
</script>

```

3. 启动应用，效果如下

![image](https://github.com/Tencent/tdesign-vue-next/assets/45103434/b988e62a-5612-4d86-9b01-8b936049d02a)

### 期望结果

1. 点击选项卡2时，才加载选项卡2的面板内的元素
2. 切换回选项卡1后，选项卡2的面板内的元素的状态仍然保留

### 实际结果

1. 选项卡2在App.vue之前加载，导致选项卡2内组件的状态使用pinia无法正常恢复；使用echarts组件时，在onMounted调用echarts.init警告元素没有高度和宽度（组件还没展示就调用了onMounted）

MyPannel2.vue

```
onMounted(() => {
 const myChart1 = echarts.init(document.getElementById('echart1'));
});
```

这就导致需要写额外的逻辑来初始化选项卡内容。

2. 切换回选项卡1后，选项卡2的面板内的元素的状态仍然保留。选项卡内容隐藏后确实没有销毁。

### 框架版本

Vue(3.3.4)

### 浏览器版本

Edge(103.0.1264.71)

### 系统版本

Win10(KB5015878)

### Node版本

16.19.0

**Comment by liweijie0812** [comment]
升级1.6.3，已新增lazy支持懒加载

**Comment by QQ2439423861** [comment]
> 升级1.6.3，已新增lazy支持懒加载

# 问题描述

`t-tab-panel`组件设置了`:destroy-on-hide="true"`后，在生产环境下，切换选项卡后该组件面板的内容未隐藏

## tdesign-vue-next 版本
1.6.3

## 重现链接

<https://stackblitz.com/edit/vitejs-vite-597xw5?file=App.vue>

## 重现步骤

1. `main.js`文件：按需引入组件

```ts
import { createApp } from 'vue';
import App from './App.vue';

// 引入组件库的少量全局样式变量
import 'tdesign-vue-next/es/style/index.css';

createApp(App).mount('#app');
```

2. `App.vue`

```vue
<template>
  <t-space direction="vertical" size="large">
    <t-tabs v-model="value">
      <t-tab-panel
        :value="1"
        label="选项卡1"
        :destroy-on-hide="true"
        :lazy="true"
      >
        <p style="padding: 25px">选项卡1的内容，隐藏会销毁</p>
      </t-tab-panel>
      <t-tab-panel :value="2" label="选项卡2" :lazy="true">
        <template #panel>
          <p style="padding: 25px">选项卡2的内容，隐藏不会销毁</p>
        </template>
      </t-tab-panel>
      <t-tab-panel
        :value="3"
        label="选项卡3"
        :destroy-on-hide="true"
        :lazy="true"
      >
        <p style="padding: 25px">选项卡3的内容，隐藏会销毁</p>
      </t-tab-panel>
    </t-tabs>
  </t-space>
</template>

<script setup lang="js">
import {
  Tabs as TTabs,
  TabPanel as TTabPanel,
  Space as TSpace,
} from 'tdesign-vue-next';
import { ref } from 'vue';

const value = ref(1);
</script>
```

3. 编译并运行：`npm run build && npm run preview`
4. 在预览界面切换到选项卡2
5. 切换到选项卡1或选项卡3

## 期望结果

切换到选项卡1或选项卡3后，选项卡2的内容隐藏

## 实际结果

切换到选项卡1或选项卡3后，选项卡2的内容未隐藏

## 补充说明

1. 运行`npm run dev`调试时正常

2. 经过对比发现，在生产环境下缺少样式：

```css
.t-is-hidden {
  display: none;
}
```

@liweijie0812

**Comment by liweijie0812** [comment]
<img width="1424" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/10710889/da2f0bc4-be8d-4c43-a055-cb248fc0ff93">

打包正常

**Comment by QQ2439423861** [comment]
> <img alt="image" width="1424" src="https://user-images.githubusercontent.com/10710889/276495760-da2f0bc4-be8d-4c43-a055-cb248fc0ff93.png">
> 打包正常

不是吧，我不信，要不你打开我提供的链接运行试试？

![image](https://github.com/Tencent/tdesign-vue-next/assets/45103434/09d3acfa-fd11-45c3-95e8-103bf837d0e1)

![image](https://github.com/Tencent/tdesign-vue-next/assets/45103434/2cf884c7-f581-4e6e-a179-25109ab84045)

![image](https://github.com/Tencent/tdesign-vue-next/assets/45103434/b07f9a29-f619-46a3-b7bf-95fc30572794)

![image](https://github.com/Tencent/tdesign-vue-next/assets/45103434/9740950a-717e-49ab-b70d-c28160410f25)

PS: 如果全局注册就正常：

main.js

```ts
import { createApp } from 'vue';
import TDesign from 'tdesign-vue-next';
import App from './app.vue';

// 引入组件库的少量全局样式变量
import 'tdesign-vue-next/es/style/index.css';

const app = createApp(App);
app.use(TDesign);
```

**Comment by liweijie0812** [comment]
https://cdn.jsdelivr.net/npm/tdesign-vue-next@1.6.4/es/tabs/style/index.css
css 没打包到 .t-tab-panel.t-is-hidden,要排查下那里的的问题

**Comment by liweijie0812** [comment]
升级 1.6.5
