### ISSUE TITLE
[Table]  重载 table 数据后修改数据元素的某个字段值时数据表不再更新

### ISSUE THREAD

**Issue by PDieE** [Tencent/tdesign-vue-next#3451]
### tdesign-vue-next 版本

1.5.7

### 重现链接

https://stackblitz.com/edit/9u8uyp?file=src%2Fdemo.vue

### 重现步骤

按照上述的重现链接，先点击状态列的 switch 此时 switch 会根据字段的新值表现为不同的开关状态
之后再点击重新加载数据按钮后 再点击 switch 则 switch 不会再根据字段的新值表现为不同的开关状态

### 期望结果

希望能像重新加载前一样正确应用更改

**Comment by chaishi** [comment]
看了下文中描述的“重载”操作，重新执行了 `getData()`，相当于重新给 `data`属性赋值，switch 自然会被重置，符合组件预期。

如果你希望保持开关状态，请保证传递的 data 属性中的 status 字段是期望的值

**Comment by chaishi** [comment]
#### 提供的代码用法：
https://stackblitz.com/edit/9u8uyp?file=src%2Fdemo.vue
```js
const changeStatus = (data) => {
  data.onChangeStatus = true;
  setTimeout(() => {
    data.status = data.status === 1 ? 0 : 1;
    data.onChangeStatus = false;
  }, 1000);
};
```
<img width="1035" alt="企业微信截图_ee3c001a-cc15-4846-8e38-3e1db8d384e6" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/da4d5db5-c2ef-4509-a7cc-f6a665e4ab36">

这种用法在使用的时候，Vue 的参数 data 无法正常动态更新，组件就无法收到新的值。建议再确认下 Vue Props 属性更新的使用方法。


#### 下方为建议代码用法，无论是否修改过数据，Switch 状态变化都表现正常
完整示例代码地址：https://stackblitz.com/edit/9u8uyp-bfkc1x?file=src%2Fdemo.vue

```js
const changeStatus = (row, rowIndex) => {
  const loadingData = { ...row };
  loadingData.onChangeStatus = true;
  data.value[rowIndex] = loadingData;
  setTimeout(() => {
    const newData = { ...row };
    newData.status = row.status === 1 ? 0 : 1;
    newData.onChangeStatus = false;
    data.value[rowIndex] = newData;
  }, 1000);
};
```
