### ISSUE TITLE
[TreeSelect] 样式缺失

### ISSUE THREAD

**Issue by KeroZhai** [Tencent/tdesign-vue-next#3452]
### tdesign-vue-next 版本

1.5.7

### 重现步骤

使用 TreeSelect 时，发现右侧箭头颜色不像 Select 那样为浅灰色，定位发现是对应的样式文件没有导入

### 期望结果

样式文件被导入。

### 实际结果

样式文件未被导入。

### 框架版本

Vue

### 补充说明

看了眼 `node_modules` 里打包产物的 `tdesign-vue-next/es/tree-select/style/index.css` 似乎没有被 import。

`index.mjs` 里导入了 `./style/css.mjs`，而后者的内容为：`import '../../tree/style/index.css'`。

**Comment by uyarn** [comment]
是按需引用tree-select?

**Comment by KeroZhai** [comment]
是的，按需引用的

**Comment by uyarn** [comment]
fixed 1.6.8
