### ISSUE TITLE
[Table] Table的columns属性能否不固定为PrimaryTableCol[]，然后row-key属性能不能默认为'id'呢？

### ISSUE THREAD

**Issue by XAllure** [Tencent/tdesign-vue-next#3455]
### 这个功能解决了什么问题

无

### 你建议的方案是什么

Table的row-key一般来说都是id吧，不是的话再自己写也可以啊，不然每次都要定义。
![image](https://github.com/Tencent/tdesign-vue-next/assets/66450680/a57c35bd-08c5-4ba5-890f-2b0bc649a983)
![image](https://github.com/Tencent/tdesign-vue-next/assets/66450680/7a4e3787-c186-4868-8be7-892c5b6c8615)
当我这么定义的时候，columns属性类型不匹配，必须要断言一下才行。如果columns不传入自己定义的类型，在使用cell的时候没有字段提示就很难受。而且现在不是可以泛型组件了吗，所以能把columns属性的泛型交给使用者自定义吗？这样我在使用插槽的时候也能有类型提示了。

**Comment by chaishi** [comment]
先说 rowKey 默认为 id，代码内部确实很多地方都是默认为 id，但其实也有业务特别提出希望不要这个默认值，后来就有很多地方不再默认为id。也就是说默认值 id 到底是否需要，不同业务是有不同诉求的，组件很难满足所有业务。

**Comment by XAllure** [comment]
> 先说 rowKey 默认为 id，代码内部确实很多地方都是默认为 id，但其实也有业务特别提出希望不要这个默认值，后来就有很多地方不再默认为id。也就是说默认值 id 到底是否需要，不同业务是有不同诉求的，组件很难满足所有业务。
> 
> 再有，这个 rowKey 十分 、非常、特别、无比 的重要，无论是列表渲染Vue框架本身需要，还是行选中、行展开、行删除等等，都需要。不能设置的过于随意。且很多实际业务需求中，行唯一标识字段并不是你文中提到的 id，更可能是 publish_id、user_id、order_id 更加明确含义的字段命名。
> 
> 故而 rowKey 是否添加默认值 id，暂时不做变更

那如果用户不填就默认啊 用户填了 就使用用户所填的字段啊 如果实在不行 也可以做一个全局配置啊

**Comment by XAllure** [comment]
> 再说 columns ，我在使用的时候，直接定义 columns：PrimaryTableCol< TableData > 或者使用 ref 定义 columns = ref<PrimaryTableCol< TableData >>([]) 是不需要单独写 columns as xxx 的，cell 里面的表格数据提醒也没什么问题

我使用的时候，PrimaryTableCol里填自定义类型，table组件的columns属性就会报类型不匹配的问题，只能使用ui框架已定义的类型，难道真就我一个人使用有这个问题

**Comment by chaishi** [comment]
> 我意思不是说必须只能为id，是如果用户不填就默认id 用户填了 就使用用户所填的字段啊 如果实在不行 也可以做一个全局配置啊

加了默认值，就会依赖 id，忘了，就是一堆缺陷

**Comment by chaishi** [comment]
你测试看看不用 reactive，使用 ref 看看呢

**Comment by lx11573** [comment]
> > 再说 columns ，我在使用的时候，直接定义 columns：PrimaryTableCol< TableData > 或者使用 ref 定义 columns = ref<PrimaryTableCol< TableData >>([]) 是不需要单独写 columns as xxx 的，cell 里面的表格数据提醒也没什么问题
> 
> 我使用的时候，PrimaryTableCol里填自定义类型，table组件的columns属性就会报类型不匹配的问题，只能使用ui框架已定义的类型，难道真就我一个人使用有这个问题
我这里使用，无论是`reactive`还是`ref`都是可以的，没有类型不匹配的提示

**Comment by chaishi** [comment]
看看 VsCode 有没有安装插件 volar 以及 typescript 提醒一类的
