### ISSUE TITLE
[Table] activeRowKeys无效

### ISSUE THREAD

**Issue by PDB6912** [Tencent/tdesign-vue-next#3459]
### tdesign-vue-next 版本

1.5.7

### 重现链接

https://codesandbox.io/s/highlight-table-forked-sw2q9z?file=/src/Demo.vue

### 重现步骤

设置activeRowKeys属性值，但是对应的几点并有高亮

### 框架版本

Vue(3.2.40)

### 浏览器版本

106.0.5249.121（正式版本）

### 系统版本

win10

### Node版本

v18.15.0

### 补充说明

这个问题从1.5.6版本就存在的

**Comment by chaishi** [comment]
`v-model:active-row-keys="activeRowKeys"` 有效
文档内的代码描述，我们更新下

**Comment by ldypgod** [comment]
@chaishi  v-model:active-row-keys="activeRowKeys" [还是无效，1.5.7版本]
![image](https://github.com/Tencent/tdesign-vue-next/assets/100122128/c70671c0-d20a-4222-a0a9-0179abb73573)

**Comment by chaishi** [comment]
Vue3 resolved in https://github.com/Tencent/tdesign-vue-next/pull/3463

**Comment by chaishi** [comment]
fixed at `v1.6.2` 2023-10-12

**Comment by Yh1404** [comment]
还是无效
![image](https://github.com/user-attachments/assets/227c65f5-eeee-4f22-b09d-0e8a9e63a96a)
