### ISSUE TITLE
v1.6.0+vite编译报错

### ISSUE THREAD

**Issue by zwtderek1986** [Tencent/tdesign-vue-next#3460]
### tdesign-vue-next 版本

1.6.0

### 重现步骤

将tdesign-vue-next版本更新至1.6.0后，进行编译会报错，具体情况请看截图
![Snipaste_2023-10-11_10-51-52](https://github.com/Tencent/tdesign-vue-next/assets/39580899/ea643a4f-d25e-470f-9d7b-5e580af352a1)

### 期望结果

修复UI库编译报错问题

### 实际结果

编译报错

### 框架版本

Vue(3.3.4)

### 浏览器版本

Chrome(117.0.5938.149)

### 系统版本

MacOS(13.6)

### Node版本

v18.12.1

**Comment by PengYYYYY** [comment]
修复中

**Comment by zwtderek1986** [comment]
> 修复中

谢谢

**Comment by PengYYYYY** [comment]
升级到 1.6.1 试试

**Comment by zwtderek1986** [comment]
> 升级到 1.6.1 试试

ok,可以了

**Comment by chnykn** [comment]
哈哈，果真解决了！ 我查了一上午，这个问题咋回事。
最后，在这里看到了，升级到1.6.1 就OK了。
