### ISSUE TITLE
[Cascader] 开启全路径模式下，不同层级叶子节点具有相同值时出现问题

### ISSUE THREAD

**Issue by AuroraSmile** [Tencent/tdesign-vue-next#3466]
### tdesign-vue-next 版本

1.6.1

### 重现链接

https://codesandbox.io/s/value-type-cascader-forked-mzv9l9?file=/src/Demo.vue

### 重现步骤

1.当不同层级叶子节点具有相同值时，选中其中一个叶子节点，具体相同值但不同层级得叶子节点也会被选中
2.控制台会有警告信息 TDesign Tree Warn: Dulplicate value: 1.1

### 实际结果

![cascaderbug](https://github.com/Tencent/tdesign-vue-next/assets/43204739/a39dbb97-b36d-4bfe-ba4b-fc04d6d60b28)

### 框架版本

Vue(3.3.4)

**Comment by chaishi** [comment]
暂不支持不同路径的相同值

**Comment by AuroraSmile** [comment]
> 暂不支持不同路径的相同值

这个应该可以允许相同值吧！有支持计划打算吗？😮
在element plus的Cascader组件允许不同路径相同值
