### ISSUE TITLE
[select] 当使用键盘上下切换选项时，如果该 option 不在视图内时，应该将视图滚动至该 option，使其出现在视图内

### ISSUE THREAD

**Issue by lx11573** [Tencent/tdesign-vue-next#3468]
### 这个功能解决了什么问题

当使用键盘上下切换选项时，如果该 option 不在视图内时，应该将视图滚动至该 option，使其出现在视图内

### 你建议的方案是什么

将视图滚动至该 option，使其出现在视图内

**Comment by uyarn** [comment]
supported in 1.6.6
