### ISSUE TITLE
[Select] 自定义面板的选择器中的 input 会自动 blur

### ISSUE THREAD

**Issue by lx11573** [Tencent/tdesign-vue-next#3469]
### tdesign-vue-next 版本

1.6.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/select#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%9D%A2%E6%9D%BF%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

官方示例中的自定义面板的选择器显示下拉选项后，如果要聚焦到`#panelTopContent`的`input` 时，会自动 blur

### 期望结果

正常聚焦

### 框架版本

Vue 3.3.4

### 浏览器版本

117.0.5938.149

### 系统版本

MacOS 11.5.2

### Node版本

16.17.0

**Comment by uyarn** [comment]
fixed in 1.6.5
