### ISSUE TITLE
[Improve][table]行的自动序号

### ISSUE THREAD

**Issue by whr2349** [Tencent/tdesign-vue-next#347]
### 这个功能解决了什么问题
希望[table]组件有行的自动序号功能

### 你建议的方案是什么？
希望[table]组件有行的自动序号功能

**Comment by pengYYYYY** [comment]
可以这么写
```js
col: 'index'
cell: (h, { rowIndex }) => rowIndex
```

**Comment by chaishi** [comment]
不同的业务，对于序号的需求可能不一样：

场景一：序号从 0 开始；
场景二：序号从 1 开始；
场景三：序号从第 3 行或者第 4 行开始，0 作为初始计数
场景四：序号从第 3 行或者第 4 行开始，1 作为初始计数

面对千变万化的需求，组件库难以都满足，业务侧自行实现一下吧，挺简单的，就两行关键代码。
