### ISSUE TITLE
[Slider] 滑块组件的label属性回调未实现

### ISSUE THREAD

**Issue by ziyi99** [Tencent/tdesign-vue-next#3470]
### tdesign-vue-next 版本

1.5.7

### 重现步骤

Slider 滑块组件的label属性，当定义为函数时，拿不到position=start  position=end参数，貌似是组件内部没有处理这个逻辑，

### 补充说明

目前在用这个Slider范围实现音频的裁剪， 音频实际使用秒为单位，但label需要给用户展示格式化的时分秒。   因为拿不到回调参数position作判断，卡在这了

**Comment by ziyi99** [comment]
重现链接 https://stackblitz.com/edit/4zgwub?file=package.json,src%2Fdemo.vue

**Comment by uyarn** [comment]
fixed in 1.6.6
