### ISSUE TITLE
[ColorPicker] recentColors 最近使用颜色功能异常，无法保存

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#3471]
### tdesign-vue-next 版本

最新版

### 重现链接

https://tdesign.tencent.com/vue-next/components/color-picker?tab=demo#%E5%B8%A6%E8%A7%A6%E5%8F%91%E5%85%83%E7%B4%A0%E7%9A%84%E9%A2%9C%E8%89%B2%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

- 添加一个最近使用颜色，关闭颜色面板，再打开，之前添加的颜色丢失
- 添加颜色后，重新选择一个颜色，已添加颜色丢失
- 颜色无法添加多个
- 某些情况颜色无法添加
- vue2 版本正常
- ![image](https://github.com/Tencent/tdesign-vue-next/assets/28809916/45838811-9a5d-4f01-8447-3aa75b012e26)

### 期望结果

正常使用「最近使用颜色」功能

### 实际结果

添加过的颜色丢失，无法添加多个，或直接无法添加

### 补充说明

实际项目中，使用版本1.4.x，控制台有如下warning:
```
[Vue warn] Set operation on key "recentColors" failed: target is readonly. 
```

**Comment by uyarn** [comment]
fixed in 1.6.6
