### ISSUE TITLE
[Select] select can't lose focus after selecting 选择器选中条目后未失去焦点

### ISSUE THREAD

**Issue by Cheerwhy** [Tencent/tdesign-vue-next#3485]
### tdesign-vue-next 版本

1.6.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/select

### 重现步骤

点击select展开下拉菜单选中条目后，选择器未失去焦点

### 期望结果

失去焦点

### 实际结果

未失去焦点

### 框架版本

Vue(3.3.4)

### 浏览器版本

Crome(118.0.0.0)

### 系统版本

Windows10

### Node版本

Node(16.17.0)

### 补充说明

react版本选中后会自动失去焦点
两版的反馈为何会不同？

**Comment by uyarn** [comment]
fixed in 1.6.5
