### ISSUE TITLE
[Bug] [Upload]0.8版本的upload组件max属性没生效

### ISSUE THREAD

**Issue by Miao0er** [Tencent/tdesign-vue-next#349]
### 重现链接
https://codesandbox.io/s/iu3kd9?file=/src/demo.vue

### 重现步骤
官网示例可见，一直上传，超过Max后还是可以上传

### 期望结果
超过之后不能上传

### 实际结果
超过Max后还是可以上传

| Environment | Info |
|---|---|
| 相关版本 | 0.8.1 |
| 框架版本 / 基础库版本 | vue3 |
| 系统、浏览器 | 谷歌 |
| Node版本 | 13 |
<img width="1009" alt="wecom-temp-b8d6beae4a1ed11a0ecffa7a0c22bab9" src="https://user-images.githubusercontent.com/37327757/155094556-866c6350-d421-4a63-acdc-b9b585bba921.png">

**Comment by pengYYYYY** [comment]
0.9.0 已修复
