### ISSUE TITLE
[table] 带拖拽功能的树表格表头操作全选，会选中已禁用选择的行

### ISSUE THREAD

**Issue by chenli1989** [Tencent/tdesign-vue-next#3499]
### tdesign-vue-next 版本

1.6.3

### 重现链接

https://codesandbox.io/s/tree-table-forked-n6l5vw?file=/src/Demo.vue

### 重现步骤

树表格开启选择行，设置指定行禁用选择。树表格表头操作全选，会把设置禁用选择的行一起选中。
[t-table] 组件正常。
[t-enhanced-table] 组件异常，不应该一起选中已禁用选择的行！

### 期望结果

树表格表头操作全选，不要选中已禁用选择的行

### 实际结果

树表格表头操作全选，选中已禁用选择的行

### 框架版本

3.3.4

### 浏览器版本

Chrome(118.0.5735.248)

### 系统版本

Windows 11

### Node版本

v18..17.1

### 补充说明
看重现

**Comment by chenli1989** [comment]
> ♥️ 有劳 @Louiszhai @PengYYYYY @chaishi 尽快确认问题。 确认有效后将下一步计划和可能需要的时间回复给 @chenli1989 。

升级至 1.6.6 问题还存在

**Comment by chaishi** [comment]
### 去掉行拖拽功能就表现正常了

https://codesandbox.io/s/tree-table-forked-wn7wn9?file=/src/Demo.vue:0-12596

<img width="647" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/fb483e02-7bb8-4ba3-ad1e-51f03fa3a925">

**Comment by chaishi** [comment]
涉及到表格拖拽功能的问题，后续关注 https://github.com/Tencent/tdesign-vue-next/issues/3567 这里

**Comment by chaishi** [comment]
我看官网是正常的，提供的示例代码，和官网代码，最大的区别是什么
<img width="558" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/5cd5e2ff-bbf4-40c5-9004-312df8e7a1e3">

**Comment by chenli1989** [comment]
> 我看官网是正常的，提供的示例代码，和官网代码，最大的区别是什么 <img alt="image" width="558" src="https://user-images.githubusercontent.com/11605702/280516161-5cd5e2ff-bbf4-40c5-9004-312df8e7a1e3.png">
> 
> ```
> {
>     // 列拖拽排序必要参数
>     colKey: 'drag',
>     title: '排序',
>     // eslint-disable-next-line @typescript-eslint/no-unused-vars
>     cell: (h) => <MoveIcon />,
>     width: 46,
>   },
> ```
> 
> Vue3 和 `sortablejs` 拖拽插件不兼容，会引起一些意料之外的问题， Vue2/React 中使用 `sortablejs` 没有问题。
> 
> 后续考虑方案，移除 Vue3 中使用的插件 `sortablejs`，更为单独实现，避免 Vue3 一系列不兼容的问题

@chaishi 与官网示例的差别就是在树表格上多一个开启行可拖拽功能。开启行可拖拽功能，全选操作就会出现已禁用选择的行会被选中。目前这个问题在 v1.6.8 版本还是存在。

**Comment by huangchen1031** [comment]
这个BUG应该和Vue3以及sortablejs没关系。

跟踪代码发现，第一层问题在这里：
```
// useTreeSelect.tsx
// line: 183 ~ 193

  function onInnerSelectChange(rowKeys: SelectChangeParams[0], extraData: SelectChangeParams[1]) {
    if (!tree.value || tree.value.checkStrictly) {
      setTSelectedRowKeys(rowKeys, extraData);
      return;
    }
    if (extraData.currentRowKey === 'CHECK_ALL_BOX') {
      handleSelectAll(extraData);
    } else {
      handleSelect(rowKeys, extraData);
    }
  }
```

经检验发现，`treeConfig`增加`checkStrictly`属性，全选勾选正常。然后检查下面的方法：
```
// useTreeSelect.tsx
// line 195 ~ 213

  function handleSelectAll(extraData: SelectChangeParams[1]) {
    const newRowKeys: Array<string | number> = [];
    const newRowData: TableRowData[] = [];
    if (extraData.type === 'check') {
      const arr = [...treeDataMap.value.values()];
      for (let i = 0, len = arr.length; i < len; i++) {
        const item = arr[i];
        // 问题在这里的状态不对
        if (!item.disabled) {
          newRowData.push(item.row);
          newRowKeys.push(get(item.row, rowDataKeys.value.rowKey));
        }
      }
    }
    const newExtraData = {
      ...extraData,
      selectedRowData: newRowData || [],
    };
    setTSelectedRowKeys(newRowKeys, newExtraData);
  }
```
关键在202行的判断，所以其实是`treeDataMap`里面本身的状态有问题。
然后追踪到初始化的地方：
```
// tree-store.ts
// line 648 ~ 680

  initialTreeDataMap(
    treeDataMap: TableTreeDataMap,
    dataSource: T[],
    column: PrimaryTableCol,
    keys: KeysType,
    level = 0,
    parent: TableRowState = null,
  ) {
    for (let i = 0, len = dataSource.length; i < len; i++) {
      const item = dataSource[i];
      const rowValue = getUniqueRowValue(item, keys.rowKey);
      if (isUndefined(rowValue)) {
        log.error('EnhancedTable', '`rowKey` could be wrong, can not get rowValue from `data` by `rowKey`.');
        return;
      }
      const children = get(item, keys.childrenKey);
      const state: TableRowState = {
        id: rowValue,
        row: item,
        rowIndex: level === 0 ? i : -1,
        level,
        expanded: false,
        expandChildrenLength: 0,
        disabled: isRowSelectedDisabled(column, item, i),
        parent,
      };
      state.path = parent ? parent.path.concat(state) : [state];
      treeDataMap.set(rowValue, state);
      if (children?.length) {
        this.initialTreeDataMap(treeDataMap, children, column, keys, level + 1, state);
      }
    }
  }
```
发现`disabled`是根据传进来的`column`去计算获得，于是乎：
```
// tree-store.ts
// line 72 ~ 75

  initialTreeStore(dataSource: T[], columns: PrimaryTableCol[], keys: KeysType) {
    this.treeDataMap?.clear();
    this.initialTreeDataMap(this.treeDataMap, dataSource, columns[0], keys);
  }
```
这里居然用`columns[0]`去当做复选框列进行传参。。。
改了下示例代码，调换`drag`和`row-select`的位置全选禁用又生效了~ 所以确定是这里的问题。。。

根据其他地方的写法，这里可以改写成
```
// from useTreeData.tsx
columns.find((col) => col.colKey === 'row-select')
```
又或者
```
// from useRowSelect.tsx
columns.find(({ type }) => ['multiple', 'single'].includes(type))
```
顺便吐槽一下这两个地方的写法不一致~
