### ISSUE TITLE
[Tabs] 可滑动的选项卡，动态修改选项卡数量导致滑动按钮不符合预期

### ISSUE THREAD

**Issue by ry0513** [Tencent/tdesign-vue-next#3510]
### tdesign-vue-next 版本

可以复现

### 重现链接

https://stackblitz.com/edit/rhwuut?file=src%2Fdemo.vue

### 重现步骤

动态修改选项卡数量时会导致滑动按钮显示时机不对，通过点击数量按钮复现，多变少时会出现滑动按钮，少变多时按钮会消消失

### 期望结果

期望结果希望符合预期，数量多的时候显示滑动按钮数量，数量少的时候不显示

### 实际结果

通过点击数量按钮复现，多变少时会出现滑动按钮，少变多时按钮会消消失

### 框架版本

v3.3.4

### 浏览器版本

118.0.5993.89（64 位）

### 系统版本

win11 H22

### Node版本

v18.18.0

### 补充说明
场景：左边为Menu主菜单，右边Tabs为子菜单，点击切换主菜单时会动态改变子菜单数量

**Comment by uyarn** [comment]
fixed in 1.6.6
