### ISSUE TITLE
[Form] 行内布局会换行

### ISSUE THREAD

**Issue by lin-code-world** [Tencent/tdesign-vue-next#3513]
### tdesign-vue-next 版本

1.6.5

### 重现链接

官方文档

### 重现步骤

Form 不同布局类型的表单 行内布局会换行

### 期望结果

以前我记得是好的，在一行内展现，但到1.6.5版本会换行

### 实际结果

行内布局会换行

**Comment by algerkong** [comment]
没有问题， 样式写错了吧

**Comment by uyarn** [comment]
最近没改过form的布局

**Comment by lin-code-world** [comment]
刚看了下官网，又变好了。
