### ISSUE TITLE
[EnhancedTable] 树形表格拖拽排序

### ISSUE THREAD

**Issue by tanhh326** [Tencent/tdesign-vue-next#3516]
### tdesign-vue-next 版本

1.6.5

### 重现链接

https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E6%A0%91%E5%BD%A2%E7%BB%93%E6%9E%84%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

这个树形表格怎么配置才能拖拽呢，官网这个案例好像无法拖拽排序

**Comment by chenli1989** [comment]
@tanhh326 升级至 1.6.6+ 版本就正常了。

**Comment by chaishi** [comment]
最新的官网版本应该是正常的
