### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by skjgithub950423** [Tencent/tdesign-vue-next#3524]
### tdesign-vue-next 版本

1.6.5

### 重现链接

https://codesandbox.io/s/lr6y53

### 重现步骤

滚动到指定元素按钮失效
![image](https://github.com/Tencent/tdesign-vue-next/assets/13342063/06da2ba7-1ec5-4c20-a337-71a10d79b691)
只有最新的1.6.5版本会有这个错误，切换到1.5.7版本后恢复正常

### 期望结果

滚动到指定元素功能正常使用

### 实际结果

滚动到指定元素按钮功能不正常

**Comment by AuYuHui** [comment]
我来  提个PR 吧

**Comment by skjgithub950423** [comment]
> 我来 提个PR 吧

感谢
