### ISSUE TITLE
[Improve][Bug]组件预览与实际组件的配色不一样，组件预览的配色更加和谐和舒服

### ISSUE THREAD

**Issue by JokerLoLgrey** [Tencent/tdesign-vue-next#354]
### 重现链接
这是组件预览配色（底色为#3c485c）
![image](https://user-images.githubusercontent.com/33446705/155306935-6f7c3b3b-21c7-4012-8459-784c003c86bd.png)

这是实际组件配色（底色为#2c2c2c）
![image](https://user-images.githubusercontent.com/33446705/155307285-711b941b-698d-4c86-8c14-a2511e2f9bd5.png)

### 期望结果
希望能够修改为组件预览的配色

### 实际结果
组件预览的配色和实际组件的不一致

| Environment | Info |
|---|---|
| 相关版本 | 0.8.1 |
| 框架版本 / 基础库版本 | Vue(3.2.12) |
| 系统、浏览器 | win11 edge最新版 |
| Node版本 | 16.13.0 |

**Comment by Wen1kang** [comment]
你好，这里的话概览图是仅做示意，做抽象化处理了。颜色不建议在组件UI上使用，不过我们也在加强色彩主题定制能力，后续会开放带蓝色倾向效果的tooltips，和你期望效果会比较接近。
