### ISSUE TITLE
[tree] 选中节点，出现页面卡死

### ISSUE THREAD

**Issue by chenli1989** [Tencent/tdesign-vue-next#3544]
### tdesign-vue-next 版本

1.6.6

### 重现链接

https://codesandbox.io/s/4x298f?file=/src/main.js

### 重现步骤

出现两个操作问题：
~~1、选中节点页面卡死；重现地址：【https://codesandbox.io/s/4x298f?file=/src/main.js】~~
2、
   - 选中和取消选中【节点 1】，影响【节点2】选中状态，重现地址：【https://tdesign.tencent.com/vue-next/components/tree#%E5%8F%AF%E9%80%89%E6%8B%A9%E7%9A%84%E6%A0%91】
   - 选中和取消选中【节点 2】，影响【节点1】选中状态，重现地址：【https://codesandbox.io/s/4x298f?file=/src/main.js】

### 期望结果
正常操作

### 实际结果
操作卡死，操作相互影响兄弟节点选择状态

### 框架版本

3.3.7

### 浏览器版本

Chrome(118.0.5993.118)

### 系统版本

Windows 11

### Node版本

v18..17.1

### 补充说明
看重现示例

**Comment by uyarn** [comment]
第一个问题是在codesandbox里的问题 先忽略

**Comment by uyarn** [comment]
fixed 1.6.7
