### ISSUE TITLE
[input] 不支持number类型的值回显

### ISSUE THREAD

**Issue by a1074160894** [Tencent/tdesign-vue-next#3545]
### 这个功能解决了什么问题

当返回值是number类型时，使用input组件，即便是设置了type=“number”，还是会出现以下警告

[Vue warn]: Invalid prop: type check failed for prop "modelValue". Expected String with value "0", got Number with value 0. 

### 你建议的方案是什么

看文档input的value只支持string类型，希望增加number类型的支持

**Comment by uyarn** [comment]
讨论后 input会重新支持number

**Comment by uyarn** [comment]
1.7.0已修复
