### ISSUE TITLE
使用nuxt3时，使用MessagePlugin 所有组件都加载，影响使用体验和性能的问题

### ISSUE THREAD

**Issue by wangzhishou** [Tencent/tdesign-vue-next#3561]
### tdesign-vue-next 版本

^1.6.5

### 重现步骤

<template>
  <t-button @click="test"> 点击确认 </t-button>
</template>
<script setup lang="ts">
import {MessagePlugin} from 'tdesign-vue-next/lib/';
function test() {
  MessagePlugin.success('登录成功')
}
</script>

运行以后，查看源码：
所有组件都加载进来了

<link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/style/index.css">
--
  | <link rel="stylesheet" href="/_nuxt/assets/style/index.less">
  | <link rel="stylesheet" href="/_nuxt/node_modules/vite-plugin-vue-inspector/src/Overlay.vue?vue&type=style&index=0&scoped=31d1379f&lang.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/loading/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/button/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/link/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/grid/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/layout/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/divider/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/space/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/affix/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/anchor/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/message/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/popup/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/tooltip/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/breadcrumb/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/dropdown/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/tabs/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/menu/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/input/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/input-number/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/select-input/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/tag/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/tag-input/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/checkbox/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/select/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/input-adornment/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/pagination/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/steps/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/sticky-tool/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/back-top/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/auto-complete/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/cascader/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/date-picker/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/time-picker/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/range-input/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/form/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/radio/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/slider/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/switch/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/textarea/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/transfer/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/tree/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/color-picker/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/image/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/avatar/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/badge/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/calendar/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/card/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/comment/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/image-viewer/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/dialog/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/list/style/index.css">
  | <link rel="stylesheet" href="/_nuxt/node_modules/tdesign-vue-next/es/progress/style/index.css">

<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/assets/style/index.less](http://localhost:3000/_nuxt/assets/style/index.less)">
<link rel="stylesheet" href="[/_nuxt/node_modules/vite-plugin-vue-inspector/src/Overlay.vue?vue&type=style&index=0&scoped=31d1379f&lang.css](http://localhost:3000/_nuxt/node_modules/vite-plugin-vue-inspector/src/Overlay.vue?vue&type=style&index=0&scoped=31d1379f&lang.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/loading/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/loading/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/button/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/button/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/link/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/link/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/grid/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/grid/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/layout/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/layout/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/divider/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/divider/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/space/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/space/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/affix/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/affix/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/anchor/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/anchor/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/message/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/message/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/popup/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/popup/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/tooltip/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/tooltip/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/breadcrumb/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/breadcrumb/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/dropdown/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/dropdown/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/tabs/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/tabs/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/menu/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/menu/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/input/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/input/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/input-number/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/input-number/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/select-input/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/select-input/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/tag/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/tag/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/tag-input/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/tag-input/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/checkbox/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/checkbox/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/select/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/select/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/input-adornment/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/input-adornment/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/pagination/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/pagination/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/steps/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/steps/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/sticky-tool/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/sticky-tool/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/back-top/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/back-top/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/auto-complete/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/auto-complete/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/cascader/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/cascader/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/date-picker/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/date-picker/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/time-picker/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/time-picker/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/range-input/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/range-input/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/form/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/form/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/radio/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/radio/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/slider/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/slider/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/switch/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/switch/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/textarea/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/textarea/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/transfer/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/transfer/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/tree/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/tree/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/color-picker/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/color-picker/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/image/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/image/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/avatar/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/avatar/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/badge/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/badge/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/calendar/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/calendar/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/card/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/card/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/comment/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/comment/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/image-viewer/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/image-viewer/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/dialog/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/dialog/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/list/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/list/style/index.css)">
<link rel="stylesheet" href="[/_nuxt/node_modules/tdesign-vue-next/es/progress/style/index.css](http://localhost:3000/_nuxt/node_modules/tdesign-vue-next/es/progress/style/index.css)">

### 期望结果

使用nuxt3时，使用MessagePlugin 所有组件都加载进来了，其它的组件没有这个问题，如何规避下这个问题？按需加载

### 实际结果

![企业微信截图_6f9b82df-1eeb-4107-978f-07700e36e01c](https://github.com/Tencent/tdesign-vue-next/assets/5122695/7571e7c8-91bf-49fe-b5e5-c0a56a29134b)
![企业微信截图_0373f4b8-e22c-4645-839d-98d7830570f4](https://github.com/Tencent/tdesign-vue-next/assets/5122695/86ed401a-f81f-472a-bc81-2898cc3bb3b9)

按需加载组件

### 框架版本

nuxt(3.8.0), vue(3.3.7)

**Comment by uuau99999** [comment]
这个表现是正常的。
1. 这个跟nuxt没有关系，只要用vite构建就会出现。
2. 在dev时在node_modules下的包预构建时由于esbuild没有treeshaking而且会处理css，import的样式会全部bundle进去。但在build阶段处理node_modules下的依赖使用rollup，会有treeshaking，并且不会bundle css。所以你上面看到的只是在dev会把样式打进去，build是没有的，build阶段还是依赖在你的项目代码里面显式引入tdesign的样式才会bundle。
