### ISSUE TITLE
[组件名称] nuxt项目中，使用t-icon，会从网络加载很多没有用到的icon下来，严重影响性能

### ISSUE THREAD

**Issue by wangzhishou** [Tencent/tdesign-vue-next#3564]
### tdesign-vue-next 版本

^1.6.5

### 重现步骤

nuxt项目中，使用t-icon，会从网络加载很多没有用到的icon下来，严重影响性能，请优化。

### 期望结果

按需加载所需的icon

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/5122695/3d256f43-2ffd-4202-949d-bbc377e41996)

**Comment by chaishi** [comment]
`t-icon` 的用法，就是内置了全量图标。

官网有关于“按需加载”使用到的图标示例代码，可以参考下。
https://tdesign.tencent.com/vue-next/components/icon

```
<template>
  <t-space direction="vertical">
    <t-space break-line>
      <component-checkbox-icon />
      <component-breadcrumb-icon />
      <component-input-icon />
      <component-switch-icon />
      <component-dropdown-icon />
      <component-radio-icon />
      <component-steps-icon />
    </t-space>
  </t-space>
</template>
<script setup>
import {
  ComponentCheckboxIcon,
  ComponentInputIcon,
  ComponentSwitchIcon,
  ComponentBreadcrumbIcon,
  ComponentDropdownIcon,
  ComponentRadioIcon,
  ComponentStepsIcon,
} from 'tdesign-icons-vue-next';

const onIconClick = () => {
  console.log('icon was clicked.');
};
</script>

```

**Comment by wangzhishou** [comment]
<AddIcon />
      <add-icon />
      <t-icon name="add"></t-icon>
      
      Nuxt3下面只有第三种才能工作，前两种报错如下：
      [Vue warn]: Failed to resolve component: add-icon
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
