### ISSUE TITLE
[Loading] iOS / iPadOS 加载图标不固定

### ISSUE THREAD

**Issue by OrenZhang** [Tencent/tdesign-vue-next#358]
### 重现链接

![1645699012640053](https://user-images.githubusercontent.com/41963680/155510950-16c49eb5-7e7b-408a-8e6a-8a363e2fefd7.gif)

### 重现步骤
设置加载状态，用iPhone或者iPad访问

### 期望结果
加载图标固定转圈

### 实际结果
加载图标不固定，大小也与设定不同

| Environment | Info |
|---|---|
| 相关版本 | 0.8.1 |
| 框架版本 / 基础库版本 | Vue(3.2.16) |
| 系统、浏览器 | iOS(15.4) / iPadOS(15.2) |
| Node版本 | v16.14.0 |

**Comment by uyarn** [comment]
很有意思的场景：
Safari内核在处理foreignObject时有缺陷，https://bugs.webkit.org/show_bug.cgi?id=23113，所以我们之前通过UA判断对Safari做了一段transform的兼容处理；用户在开发时使用Chrome调试Ipad的场景，发现存在异常，考虑是由于Chrome调试Ipad 手动加上了Ipad的UA（携带safari标识) 但实际还是Chrome的内核，额外的tranform导致样式异常，用户以为存在Bug，将transform unset，此时在Chrome调试正常；随后用真机Iphone调试，由于此时transform被抹掉了，此前针对safari的兼容处理丢失，在真机反而异常。
