### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by moxiaoli0813** [Tencent/tdesign-vue-next#3585]
### tdesign-vue-next 版本

1.6.5

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/103327450/9b00fdd6-1e57-47fa-8427-ba3451c9f024)

### 期望结果

使用图片组件时展示的图片期望是使用原生的这个没有白边的效果
![image](https://github.com/Tencent/tdesign-vue-next/assets/103327450/f5f198a5-d11c-4b8d-962c-8ea3037f17db)

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/103327450/9b00fdd6-1e57-47fa-8427-ba3451c9f024)

**Comment by moxiaoli0813** [comment]
> ### tdesign-vue-next 版本
> 1.6.5
> 
> ### 重现链接
> _No response_
> 
> ### 重现步骤
> ![image](https://user-images.githubusercontent.com/103327450/281115317-9b00fdd6-1e57-47fa-8427-ba3451c9f024.png)
> 
> ### 期望结果
> 使用图片组件时展示的图片期望是使用原生的这个没有白边的效果 ![image](https://user-images.githubusercontent.com/103327450/281115940-f5f198a5-d11c-4b8d-962c-8ea3037f17db.png)
> 
> ### 实际结果
> ![image](https://user-images.githubusercontent.com/103327450/281115317-9b00fdd6-1e57-47fa-8427-ba3451c9f024.png)
> 
> ### 框架版本
> _No response_
> 
> ### 浏览器版本
> _No response_
> 
> ### 系统版本
> _No response_
> 
> ### Node版本
> _No response_
> 
> ### 补充说明
> _No response_
`<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { list } from '@/api/common/upload'
const files = ref([])
const index = ref(0)
const path = ref('picture')
const view = ref(false)
onMounted(() => {
  getImageList(path.value)
})
const open = (key: number) => {
  view.value = true
  index.value = key
}
const enterDown = () => {
  getImageList(path.value)
}
function getImageList (path: string) {
  list(path).then((res) => {
    files.value = res.data
  })
}
</script>

<template>
  <div>
    <t-input v-model="path" placeholder="请输入相册位置" @enter="enterDown"/>
    <t-image-viewer v-model:index="index" v-model:visible="view" :images="files"></t-image-viewer>
    <div>
      <section class="box-group">
        <div class="box" :key="index" v-for="(item,index) in files">
          <t-image :src="item" fit="contain" @click="open(index)" lazy></t-image>

        </div>
      </section>
    </div>
    <t-affix ref="affix" :offset-top="140" :offset-bottom="20">

      <t-back-top
        :visible-height="0"
        shape="circle"
        :offset="[0, 0]"
        theme="light"
      ></t-back-top>
    </t-affix>
  </div>
</template>

<style scoped lang="less">
.box-group {
  column-count: 4;
}
.box {
  margin-bottom: 30px
}
//.box img {
//  width: 100%;
//  height: auto;
//}
@media screen and (max-width:768px) {
  .box-group {
    padding: 0 15px;
    column-count: 1;
  }
}
</style>
`
源码如上

**Comment by chaishi** [comment]
如何正确提 issue
### 1. 认真填写标题
<img width="465" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/af191230-bb97-48e2-a48a-ccc1b1924346">

### 2. 认真提供可复现问题的链接

截图中的 2 个按钮，二选一。点击进去，可以直接写代码，复现问题后，Ctrl + S 保存代码，此时会生成一个新的链接，然后把新链接粘贴在  “**重现链接**” 一栏
<img width="953" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/4c46eadf-3c0b-4e40-8c36-33752dbe51c0">
