### ISSUE TITLE
form组件使用upload组件选择了文件之后，更新了formData里的值，但是表单校验不通过

### ISSUE THREAD

**Issue by lzl132264** [Tencent/tdesign-vue-next#3587]
### tdesign-vue-next 版本

1.1.5

### 重现链接

https://stackblitz.com/edit/1mm2lr?file=package.json,src%2Fdemo.vue

### Node版本

16.20.1

**Comment by chaishi** [comment]
https://stackblitz.com/edit/1mm2lr-s1lq6t?file=package.json,src%2Fdemo.vue
这样写就对了。

提供的示例代码错误有几处错误：

1. `:rules="rules"` 是数组，但是写在了 `t-form-item` 里面。注意区分，`t-form-item`  需要的 rules 是对象，不是数组。`t-form` 需要的 rules 是数组
2. Upload 组件的 `value` 或者 `files` 是数组，不是字符串
3. 不是`<t-upload value='xxx'/>` 而是 `<t-upload :value="formData.file" />`
4. `onValidate` 函数不存在，去除就好
