### ISSUE TITLE
[Table表格]表格height和maxHeight属性无法设置为百分比

### ISSUE THREAD

**Issue by ShenyuYaqing** [Tencent/tdesign-vue-next#3588]
### tdesign-vue-next 版本

TDesign 的 Issue 列表接受 bug 报告或是新功能请求。也可加入官方社区：微信群 。 在发布一个 Issue 前，请确保： 1. 在 常见问题、更新日志 和 旧Issue列表 中搜索过你的问题。（你的问题可能已有人提出，也可能已在最新版本中被修正） 2. 如果你发现一个已经关闭的旧 Issue 在最新版本中仍然存在，不要在旧 Issue 下面留言，请建一个新的 issue。 注意：不符合issue规定将会被关闭 Issue 类别 Bug Feature 相关仓库 tdesign-vue-next Issue 标题 相关版本 1.6.8

### 重现步骤

在<t-table>中设置:height为70%报错[plugin:vite:vue] Error parsing JavaScript expression: Unexpected token (1:4)，
更换属性为:maxHeight结果相同，
不采用绑定而是直接写height或maxHeight时不报错但无效果，
只有将以上四个属性的值设置为数值70或字符串‘70‘时才会正确起效，
修改table外层标签的高度为百分比或固定结果相同

### 期望结果

按照文档示例：100, '30%', '300'，应该都可以正确起效才对。

### 实际结果

在<t-table>中设置:height为70%报错[plugin:vite:vue] Error parsing JavaScript expression: Unexpected token (1:4)，
更换属性为:maxHeight结果相同，
不采用绑定而是直接写height或maxHeight时不报错但无效果，
只有将以上四个属性的值设置为数值70或字符串‘70‘时才会正确起效，
修改table外层标签的高度为百分比或固定值也无效果

### 框架版本

Vue(3.3.7)

### 浏览器版本

Microsoft Edge 119.0.2151.44 (正式版本) (64 位)

### 系统版本

Windows10(22H2)

### Node版本

20.9.0

**Comment by ShenyuYaqing** [comment]
已解决，不是框架问题

**Comment by Devil-Ryu** [comment]
> 已解决，不是框架问题

哈喽，能请教一下这个问题时怎么解决的么，我也碰到这个问题了，目前用的tdesign版本时1.8.1，vue3
