### ISSUE TITLE
[Cascader 级联选择器] 如果设置的值在级联中没有的话会直接报错无法正常运行

### ISSUE THREAD

**Issue by Brokenstrings** [Tencent/tdesign-vue-next#3595]
### tdesign-vue-next 版本

1.6.8

### 重现步骤

我们系统创建菜品的时候用级联选择器去选择对应食材分类+食材，然后食材和食材分类有的时候需要删除一些，这就导致后续修改菜品的时候直接报错了，因为级联选择器里面没有对应的食材分类或食材了，我看elementui他们那边找不到对应数据的时候会直接显示值，而不是直接报错。

### 期望结果

如果级联选择器中没有对应的值，应该显示空或直接显示值，而不是报错影响整个项目。

### 实际结果

直接报错无法进行修改

**Comment by Brokenstrings** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/7030227/9ae17a65-eb8d-4299-8367-d9fda5cbe055)

**Comment by boogie-ben** [comment]
更新后遇到相同的问题了，应该是1.6.1版本之后出现的问题了

并且级联组件的匹配值有问题
![image](https://github.com/Tencent/tdesign-vue-next/assets/29250685/4d7975f5-b2bb-4e28-a606-e64de91abe8e)
