### ISSUE TITLE
TreeSelect 树选择 错误的显示了更多

### ISSUE THREAD

**Issue by mishizhiya** [Tencent/tdesign-vue-next#36]
![4](https://user-images.githubusercontent.com/54994665/147213512-f8eef074-ce97-4e18-8fd3-68a9e85ccb8e.png)
即使选择项全部展示也还是显示了更多

**Comment by pengYYYYY** [comment]
这个更多，我们可能想展示更多tag，这一块我们和交互设计师再讨论一下，感谢反馈

**Comment by Alexhueng** [comment]
以我的理解, minCollapsedNum这个api表示, 超出此api设置的数量, 展示为更多, 

比如设置为1, 可选项为4个, 全部选中时, 应该渲染一个和更多. 将其它3个折叠为更多.
而现在的表现是渲染了4个 + 更多.

**Comment by pattybaby110** [comment]
> 以我的理解, minCollapsedNum这个api表示, 超出此api设置的数量, 展示为更多,
> 
> 比如设置为1, 可选项为4个, 全部选中时, 应该渲染一个和更多. 将其它3个折叠为更多. 而现在的表现是渲染了4个 + 更多.

是的，这里“更多”是多余的。而且超过时，可以优化显示数量。

**Comment by pengYYYYY** [comment]
> 以我的理解, minCollapsedNum这个api表示, 超出此api设置的数量, 展示为更多,
> 
> 比如设置为1, 可选项为4个, 全部选中时, 应该渲染一个和更多. 将其它3个折叠为更多. 而现在的表现是渲染了4个 + 更多.

是边界判断的问题，了解
