### ISSUE TITLE
[Table 表格]开启列配置功能时，又对列标题做自定义样式则会报错 Warn

### ISSUE THREAD

**Issue by Menffy** [Tencent/tdesign-vue-next#3601]
### tdesign-vue-next 版本

能

### 重现步骤
1、开启列配置功能
   v-model:displayColumns="showColumns"
        v-model:columnControllerVisible="columnControllerVisible"
:column-controller="{
          dialogProps: {
            preventScrollThrough: true,
            width: 1200,
            top: 200,
          },
          displayType: 'fixed-width',
        }"
2、自定义列表题样式
<template #报备单ID>
          <div style="display: flex; align-items: center">
            报备单ID
            <copy-button @copy-select="handleCopySelect('orderId')" @copy-total="handleCopyTotal('orderId')" />
          </div>
        </template>

<t-table
        v-model:displayColumns="showColumns"
        v-model:columnControllerVisible="columnControllerVisible"
        hover
        :row-key="rowKey"
        :data="data"
        :columns="TABLE_COLUMNS"
        :column-controller="{
          dialogProps: {
            preventScrollThrough: true,
            width: 1200,
            top: 200,
          },
          displayType: 'fixed-width',
        }"
      >
        
        <template #报备单ID>
          <div style="display: flex; align-items: center">
            报备单ID
            <copy-button @copy-select="handleCopySelect('orderId')" @copy-total="handleCopyTotal('orderId')" />
          </div>
        </template>
</t-table>

### 期望结果

列配置弹窗里自动过滤掉标题附带的自定义组件，只显示文字或英文即可。

### 实际结果
<img width="1616" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/44236460/e6ca6d0a-f480-4800-bbcd-5c504324f40b">

<img width="1786" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/44236460/761c3667-f3c5-488f-9dc6-ef7427675ecb">

**Comment by chaishi** [comment]
<img width="499" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/48188692-074d-48e3-80fd-336c61cbd3df">

**Comment by chaishi** [comment]
https://stackblitz.com/edit/bfvdtv?file=package.json,src%2Fdemo.vue
辛苦在这个链接里面，复现一下你的问题

**Comment by chaishi** [comment]
没有回复，issue close。

截图中的问题提醒是指：组件不存在。
你可以尝试 import { Button } from 'tdesign-vue-next' 之后，再使用 () => <Button>按钮</Button>
