### ISSUE TITLE
[Select 选择器] 过滤选项后键盘上下键与Enter键无法正常选取值

### ISSUE THREAD

**Issue by wilonjiang** [Tencent/tdesign-vue-next#3605]
### tdesign-vue-next 版本

1.6.8

### 重现链接

https://stackblitz.com/edit/phaz5f-e1ssl4?file=src%2Fdemo.vue

### 重现步骤

BUG：enter选择选项与hover状态不符

1. 展开下拉框，上下键移动到”大数据“选项，按enter键选中
2. 再次展开下拉框，输入“1”，过滤下拉选项
3. 上下键移动过程中，hover状态不会按顺序移动
4. 上下键移动到任意选项，按enter键选中
5. 此时Select选中值不是当前hover的选项
6. 点击选项不会出现上述问题

### 期望结果

1. 展开下拉框，上下键移动到”大数据“选项，按enter键选中
2. 再次展开下拉框，输入“1”，过滤下拉选项
3. 此时上下键移动应按顺序移动
4. 上下键移动到任意选项，按enter键选中选项后，Select组件值应为当前hover状态的选项

### 实际结果

1. 展开下拉框，上下键移动到”大数据“选项，按enter键选中
2. 再次展开下拉框，输入“1”，过滤下拉选项
3. 此时上下键操作选项，部分情况下hover状态未按顺序移动，存在跳过的情况一些选项通过键盘上下移动永远无法获得hover状态
4. 上下键移动到任意选项，按enter键选中选项后，Select组件值与当前hover状态的选项不符

### Node版本

Node(v16.15.0)

**Comment by uyarn** [comment]
fixed 1.7.1
