### ISSUE TITLE
[表格组件，树形组件] 相同版本两台电脑上开发，一台有效果一台没效果

### ISSUE THREAD

**Issue by cgzDicaprio** [Tencent/tdesign-vue-next#3613]
### tdesign-vue-next 版本

1.6.5

### 重现步骤

在我这台电脑上配置表格的展开行怎么都没效果，但是我同事的电脑上加个插槽就行了，两个版本都是1.65。类似于这样的问题还有树形组件，同样的配置他那边有滚动条，我这里没有，当时我把tdesign卸载重装就好了，不知道为什么两次这种问题都会出现在我的这里，我们是一起开发，所有东西的版本都是一样的，电脑都是Windows的

### 期望结果

希望能解决这种相同版本在不同电脑上开发的问题

### 实际结果

请尽快解决，因为这个问题我以为是我配置的不对，浪费了我很多时间

### 框架版本

Vue(3.3.4）

### 浏览器版本

Chrome(119.0.6045.124（正式版本）)

### 系统版本

Windows 11

### Node版本

v18.17.1

**Comment by chaishi** [comment]
这个问题不属于组件库的问题范围，无需处理。

既然重装 tdesign 可以解决问题，就说明你来实际安装的版本号大概率是不同的。
package.json 里面看到的版本号，不一定是实际版本号。

实际安装版本号在 node_modules 里面查看。

再有，你说的问题，我这边开发的时候，在其他的依赖包中也有遇到过，有的甚至需要删除 node_modules 和 package-lock.json 重新安装。

**Comment by cgzDicaprio** [comment]
表格组件这个展开行还没解决
