### ISSUE TITLE
迫切需要Descriptions 描述列表组件

### ISSUE THREAD

**Issue by mustars** [Tencent/tdesign-vue-next#3616]
### 这个功能解决了什么问题

迫切需要Descriptions 描述列表组件

### 你建议的方案是什么

迫切需要Descriptions 描述列表组件，都停滞一年了

**Comment by uyarn** [comment]
API和视觉已经做好了 因为之前认领的贡献者一直没有完成所以delay了 现在我们找到新的参与者 预计这两周会出来

**Comment by mustars** [comment]
下个版本会更新吗？

**Comment by mustars** [comment]
不会又搁置了吧...

**Comment by uyarn** [comment]
supported 1.8.0
