### ISSUE TITLE
[Bug][Table] 在不同的 layout 布局下， table的固定列不生效

### ISSUE THREAD

**Issue by liangslin** [Tencent/tdesign-vue-next#362]
### 重现链接
https://stackblitz.com/edit/angular-n9wdrl?file=src/demo2.vue

### 重现步骤
demo.vue 下的 layout 布局 Table 固定列可正常显示。
demo2.vue 下的 layout 布局 Table 固定列显示异常。

可通过修改 main.js 第 3 行代码来使用不同的组件来展示词问题 
import Demo from './demo2.vue';

### 期望结果
协助修复此 BUG

### 实际结果
协助修复此 BUG

| Environment | Info |
|---|---|
| 相关版本 | 0.8.1 |
| 框架版本 / 基础库版本 | vue3.0 |
| 系统、浏览器 | MacOS (12.2.1) Chrome 98.0.4758.80（正式版本） (arm64) |
| Node版本 | v14.17.0 |

**Comment by pengYYYYY** [comment]
外部容器的布局问题导致的宽度问题，与table组件无关。
