### ISSUE TITLE
使用tsx写法时，html原生属性报类型错误的问题

### ISSUE THREAD

**Issue by boogie-ben** [Tencent/tdesign-vue-next#3626]
### tdesign-vue-next 版本

1.6.8

### 重现步骤

组件通过手动引入后（为了在tsx写法中获得类型注解），使用tsx写法时，使用html原生属性如 title target等会报类型错误，提升xxxx(组件类型) 上不存在属性'xxx'

这个问题是否有办法屏蔽或解决，或者说这个是ts配置或者是vue的tsx配置的问题？

![image](https://github.com/Tencent/tdesign-vue-next/assets/29250685/bce09a65-1586-41ff-991d-472f970fc59e)

![image](https://github.com/Tencent/tdesign-vue-next/assets/29250685/55c3051c-a5b6-4f32-a315-7bc3c5d27eff)

![image](https://github.com/Tencent/tdesign-vue-next/assets/29250685/e00c201d-1988-4523-a2e0-1e07fb52de78)

**Comment by uyarn** [comment]
没有的API报错 属于正常情况
