### ISSUE TITLE
[tabs] 当初始默认值为中间部分时，会遮挡选项卡文字

### ISSUE THREAD

**Issue by ry0513** [Tencent/tdesign-vue-next#3632]
### tdesign-vue-next 版本

v1.7.0 复现

### 重现链接

https://stackblitz.com/edit/d2pel1?file=src%2Fdemo.vue

### 重现步骤

点击重现链接

### 期望结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/44745967/16aae308-b299-4c8c-96d4-1ee7bb006792)
期望结果：不会遮挡可以全部显示文字

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/44745967/ec32b910-0561-4e83-a175-f77a697cbd71)
如图所示会遮挡选项卡文字

### 框架版本

"vue": "^3.3.4"

### 浏览器版本

版本 118.0.5993.89（正式版本） （64 位）

### 系统版本

win11

### Node版本

v18.18.0

**Comment by uyarn** [comment]
sorry 实现得不够完善 没有处理左右箭头

**Comment by uyarn** [comment]
fixed 1.7.1
