### ISSUE TITLE
[breadcrumb] target设置无效

### ISSUE THREAD

**Issue by JunQiGenYuan** [Tencent/tdesign-vue-next#3634]
### tdesign-vue 版本

latest

### 重现步骤

`
    <t-breadcrumb
      :max-item-width="'150'"
      class="pb-4"
    >
      <t-breadcrumbItem
        href="/xxxxxx"
        target="_parent"
      >
        xxxx
      </t-breadcrumbItem>
      <t-breadcrumbItem>xxxxx</t-breadcrumbItem>
    </t-breadcrumb>
`

### 期望结果

能识别target，与默认的a标签一样行为，如触发父窗口跳转等。

### 实际结果

target无论怎么设置，都只跳转当前窗口或iframe

### 补充说明

源码位置：https://github.com/Tencent/tdesign-vue-next/blob/develop/src/breadcrumb/breadcrumb-item.tsx#L67
只设置了href、没有设置route，不应该阻止默认行为,把e.preventDefault();移动到 if (props.href) 的else等执行即可

**Comment by Summer-Shen** [comment]
可以领取这个 issue 吗？预计近几天完成。

**Comment by uyarn** [comment]
> 可以领取这个 issue 吗？预计近几天完成。

PR is welcome

**Comment by uyarn** [comment]
fixed 1.7.1
