### ISSUE TITLE
[upload] 拖拽进入，点取消上传

### ISSUE THREAD

**Issue by JJJ-Git** [Tencent/tdesign-vue-next#3646]
### tdesign-vue-next 版本

1.7.0

### 重现链接

https://tdesign.tencent.com/vue-next/components/upload?tab=demo#%E5%8D%95%E6%96%87%E4%BB%B6-%E5%9B%BE%E7%89%87%E6%8B%96%E6%8B%BD%E4%B8%8A%E4%BC%A0

### 重现步骤

拖拽文件进入upload组件，上传过程中点击取消上传后，upload组件不会回到初始状态，也没办法继续上传文件

### 期望结果

期望取消上传后组件回到初始状态

### 实际结果

实际取消上传之后只显示取消上传按钮，点击没有效果，而且不能进行其他操作

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/3754
