### ISSUE TITLE
[Table] 使用合计时，当启用开启虚拟滚动模式时，表尾吸底不正常

### ISSUE THREAD

**Issue by yunnet** [Tencent/tdesign-vue-next#3655]
### tdesign-vue-next 版本

1.7.0

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/1326742/6d79a1db-6800-4614-8ba0-2af58186d876)
表的配置：
 <t-table class="table2" row-key="id" :columns="columnList" :data="dataList" size="small" active-row-type="single"
          :scroll="{ type: 'virtual', bufferSize: 20 }" :selected-row-keys="selectedRowKeys" select-on-row-click bordered
          resizable hover :loading="dataLoading" :max-height="tableHeight" :foot-data="footData" :table-layout="'fixed'"
          :footer-affixed-bottom="true" :filter-value="filterValue" lazy-load @filter-change="onFilterChange"
          @select-change="onSelectChange"> </t-table>
footer-affixed-bottom如果为false, 合计当做记录条，随滚动条滚动了。
![image](https://github.com/Tencent/tdesign-vue-next/assets/1326742/9ae369dd-61d3-47be-a607-ed5f027fd054)

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/3965

**Comment by uyarn** [comment]
fixed in 1.9.0
