### ISSUE TITLE
[t-upload]上传组件自定义模式，上传功能，取消上传，删除已经选中文件的方法

### ISSUE THREAD

**Issue by xiaoshuoyiyi** [Tencent/tdesign-vue-next#3659]
### 这个功能解决了什么问题

上传按钮、重新上传按钮和取消按钮，都是我外部定义的按钮，不使用组件内部的按钮！因为你们组件的布局排版不符合需求！theme也是custom，当autoUpload为false时：
1. 怎么获取组件的待上传的文件列表数据？
2. 怎么删除待上传列表的指定文件（就是删除已选择未上传的文件）？
3. 怎么获取已上传成功的文件列表

### 你建议的方案是什么

建议以上功能可以支持下！

**Comment by chaishi** [comment]
问题描述中，缺少上传场景的描述，比如：是文件上传，还是图片上传。

当`autoUpload=false`时，所有的文件列表都是通过 `files` 参数呈现的。

- optionA:`fileListDisplay` 插槽可以用于完全自定义上传组件的 UI，插槽参数包含 `displayFiles`，这个文件里面包含了所有状态的文件。
- optionB: 在批量文件/批量图片上传场景中，对于 `上传按钮` 和 `取消按钮`可以使用插槽 `cancelUploadButton` 和 `uploadButton` 进行自定义

**Comment by qiyunkong** [comment]
optionB: 在批量文件/批量图片上传场景中，对于 上传按钮 和 取消按钮可以使用插槽 cancelUploadButton 和 uploadButton 进行自定义，进行插槽并没有生效啊
