### ISSUE TITLE
[Build] 拉取源码到本地编译失败npm run build

### ISSUE THREAD

**Issue by wuhaining** [Tencent/tdesign-vue-next#3664]
### tdesign-vue-next 版本

1.7.0

### 期望结果

正常编译

### 实际结果

Error: Could not resolve './style/css.mjs' from src/affix/style/index.js
    at error (D:\projects\tests\TDesign\tdesign-vue-next\node_modules\rollup\dist\shared\rollup.js:198:30)
    at ModuleLoader.handleResolveId (D:\projects\tests\TDesign\tdesign-vue-next\node_modules\rollup\dist\shared\rollup.js:22287:24)
    at D:\projects\tests\TDesign\tdesign-vue-next\node_modules\rollup\dist\shared\rollup.js:22250:26

### 系统版本

Window 10 企业版

### Node版本

14.18.1

### 补充说明

初步定位到rollup.config.js中rollup-plugin-ignore-import没有生效
ignoreImport({
        include: ['src/*/style/*'],
        body: 'import "./style/css.mjs";',
      })

**Comment by chaishi** [comment]
子仓库拉一下，
git submodule init 
git submodule update

**Comment by PengYYYYY** [comment]
跑一下 npm run init 也可以

**Comment by uyarn** [comment]
这个是rollup的插件不支持windows的问题
