### ISSUE TITLE
[Table] 开启多选状态并且同时开启分页状态下，只有第一页生效，其他都无效

### ISSUE THREAD

**Issue by xiufj** [Tencent/tdesign-vue-next#3666]
### tdesign-vue-next 版本

1.7.0

### 重现链接

https://stackblitz.com/edit/e97w4j?file=package.json,src%2Fdemo.vue

### 重现步骤

开启多选状态并且同时开启分页状态下，只有第一页生效，其他都无效
![image](https://github.com/Tencent/tdesign-vue-next/assets/150098837/492086f0-88ec-4d22-b2ec-25b53a32fdfe)

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/3669

待发布

**Comment by uyarn** [comment]
fixed 1.7.1
