### ISSUE TITLE
[t-tree] v-model不支持外部更改

### ISSUE THREAD

**Issue by TanxiangCode** [Tencent/tdesign-vue-next#3670]
### tdesign-vue-next 版本

1.7.0

### 重现步骤

现在1.6.1之前是正确的，之后版本的tree再次出现该问题
https://github.com/Tencent/tdesign-vue-next/issues/3227

**Comment by TabSpace** [comment]
vue3 下已实现数组操作触发视图更新。
vue2 下，length 的操作无法触发视图变更。

**Comment by TanxiangCode** [comment]
> vue3 下已实现数组操作触发视图更新。 vue2 下，length 的操作无法触发视图变更。

https://stackblitz.com/edit/t2esha-sxauev?file=src%2Fdemo.vue
你可以看下复现。push方式变更是不生效的
