### ISSUE TITLE
[upload] 能否增加上传的responseType的参数

### ISSUE THREAD

**Issue by Makaite** [Tencent/tdesign-vue-next#3687]
### 这个功能解决了什么问题

当需求是上传后返回对应错误文件并下载时，t-upload并不能很好的返回的错误文件的下载，原因是因为请求发出时没有设置reponseTyoe为blob，所以是否可以增加这个参数的设置功能，以便做到这种需求场景的适配呢？

### 你建议的方案是什么

在t-upload组件传参中增加一个responseType的设置参数

**Comment by chaishi** [comment]
ResponseType 应该是指响应结果的响应头？
Upload 组件一般是设置请求头？通过参数 `headers` 进行设置。
