### ISSUE TITLE
Dialog组件 footer的按钮样式偏移

### ISSUE THREAD

**Issue by Alexhueng** [Tencent/tdesign-vue-next#37]
![image](https://user-images.githubusercontent.com/44539014/147214356-19ca3f9b-c005-41ca-8cd4-c1e9b7bf0d10.png)
鼠标悬停时, 按钮的背景会往下做出一点移动,
导致文本不再是垂直居中, 且两个按钮不在同一水平线上.

**Comment by pengYYYYY** [comment]
这个问题在0.5.0的版本存在，您是在codesandbox看的这个demo嘛
