### ISSUE TITLE
[Drawer抽屉] 在一个页面引入外部抽屉，隐藏状态下的抽屉会占用页面空间，页面向右侧滑动有一片空白

### ISSUE THREAD

**Issue by wmhost** [Tencent/tdesign-vue-next#370]
### 重现链接
https://stackblitz.com/edit/angular-2qwqej-jjnupm?devtoolsheight=33&file=src/demo.vue

### 重现步骤
1、页面中存在引入的外部抽屉
2、外部抽屉不可见的状态下，向页面右侧滑动，会有一片抽屉宽度的空白

### 期望结果
显示页面正常宽度，隐藏状态下的抽屉不要占用页面空间

### 实际结果
隐藏状态下的外部抽屉会占用页面空间

| Environment | Info |
|---|---|
| 相关版本 | 0.9.1 |
| 框架版本 / 基础库版本 | Vue(3.2.26) |
| 系统、浏览器 | Chrome(版本 98.0.4758.102（正式版本） (x86_64)) |
| Node版本 |  |

**Comment by vnues** [comment]
经研究：

这一块属于正常现象，根据代码` show-in-attached-element`为true时，需要在最外层加上`overflow:hidden`,要么就去掉` show-in-attached-element`
