### ISSUE TITLE
[Cascader] 如果有相同子节点的情况，选中的只会是后面那个的子节点

### ISSUE THREAD

**Issue by xiufj** [Tencent/tdesign-vue-next#3701]
### tdesign-vue-next 版本

1.7.0

### 重现链接

https://stackblitz.com/edit/v7pckz?file=package.json,src%2Fdemo.vue

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/150098837/86b8ba8a-303c-4555-8d89-1f0a408b9966)

**Comment by PengYYYYY** [comment]
目前所有的节点都需要唯一key
