### ISSUE TITLE
[Table] column-controller-visible-change 事件参数 `trigger` 不正确，反了

### ISSUE THREAD

**Issue by dntc** [Tencent/tdesign-vue-next#3706]
### tdesign-vue-next 版本

Table 的 column-controller-visible-change 事件参数不正确

### 重现链接

https://codesandbox.io/p/sandbox/custom-col-button-table-forked-nkp43w?file=%2Fsrc%2FDemo.vue%3A205%2C3

### 重现步骤

打开控制台输出
点击“列配置”按钮
点击“取消”和“确定”按钮，会发现 column-controller-visible-change 参数 context.trigger 的值和点击的按钮是相反的。
![QQ截图20231207113810](https://github.com/Tencent/tdesign-vue-next/assets/88528/34197186-fa88-44e4-ac48-e5cd84d095fb)

### 期望结果

参数 context.trigger  的值和点击的按钮匹配。

### 实际结果

参数 context.trigger  的值和点击的按钮相反。

### 框架版本

Vue(3.3.4)

### 浏览器版本

Edge(119.0.2151.97)

### 系统版本

Windows 11 23H2

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/3716
