### ISSUE TITLE
[Radio] radio-group variant="default-filled" 初始状态不应该执行动画

### ISSUE THREAD

**Issue by robin-dongbin** [Tencent/tdesign-vue-next#3726]
### tdesign-vue-next 版本

1.7.1

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤

刷新预览界面, 初始有一个动画, 感觉很奇怪.

### 期望结果

无动画

## IssueShoot
- 预估时长: 3
- 期望完成时间: 2023-12-20 00:00:00 +0000 UTC
- 开发难度: 中
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by loganylwu** [comment]
@LeeJim robin-dongbin
你好，这边查看了链接，发现链接打开后是一个首页，可以再自己检查一下链接，随后更新一个描述的场景Demo么？

**Comment by loganylwu** [comment]
> @robin-dongbin 你好，这边查看了链接，发现链接打开后是一个首页，可以再自己检查一下链接，随后更新一个描述的场景Demo么？
刚刚琢磨了一下，可以考虑是否是指这个初始化过程的加载动画？

https://github.com/Tencent/tdesign-vue-next/assets/26224399/833c0a33-8988-466c-89f2-c998082a9e26

**Comment by robin-dongbin** [comment]
就是只这个初始动画

**Comment by loganylwu** [comment]
> 就是指这个初始动画

好的，已收到。
我们会讨论后决定是否修复，以及修复的方案，结果会在这里同步到你，静待好消息~
