### ISSUE TITLE
[MenuItem]跳转未保留历史记录

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#373]
### 重现
![20220228164122](https://user-images.githubusercontent.com/30982989/155951698-643bde50-b0a9-4180-ab21-d494b588270d.gif)

### 重现步骤
点击菜单，无法返回上一页
修改属性replace无法生效

### 期望结果
replace：false,可以返回上一页

### 实际结果
replace：false,无法返回上一页

| Environment | Info |
|---|---|
| 相关版本 | 0.9.2 |
| 框架版本 / 基础库版本 | 3.2.31 |
| 系统、浏览器 | windows10 Edge 98.0.1108.62 (官方内部版本) (64 位) |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
0.9.3 已修复
