### ISSUE TITLE
[Upload ] 按照例子设置后报错TypeError: uploadValue.find is not a function

### ISSUE THREAD

**Issue by travelCN** [Tencent/tdesign-vue-next#3735]
### tdesign-vue-next 版本

1.7.1

### 重现链接

无

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/15223877/492d21e5-2dc4-4f63-ae14-2c744b9bb4b9)
![image](https://github.com/Tencent/tdesign-vue-next/assets/15223877/f2e51d5d-edde-4195-920d-cd368ae7766b)

### 期望结果

正常使用

**Comment by Xue-Yi-chen** [comment]
怎么解决的？

**Comment by travelCN** [comment]
我都忘了是啥毛病了。upload这我就忽略了一个初始值的问题，你看下model是不是个array。
