### ISSUE TITLE
所有组件都不支持 unocss的class

### ISSUE THREAD

**Issue by travelCN** [Tencent/tdesign-vue-next#3744]
### 这个功能解决了什么问题

好像只支持style和自己写的class，unocss等都不支持。

### 你建议的方案是什么

能否组件都支持unocss的class

**Comment by Yacj** [comment]
![微信图片_20231213150103](https://github.com/Tencent/tdesign-vue-next/assets/11175513/c9a4c102-fdee-424b-b698-b6eb47a1232e)
是支持原子化css的 可能是css优先级的问题  可以在unocss的class 加上 ! 比如 !w-full 试试

**Comment by travelCN** [comment]
感谢，加了!就可以用了。
