### ISSUE TITLE
[Table] activeRowType为single情况下，按shift点选行，不会多行高亮，1.7.0可以，1.7.1失效

### ISSUE THREAD

**Issue by lgs821** [Tencent/tdesign-vue-next#3751]
### tdesign-vue-next 版本

1.7.1

### 重现步骤

升级1.7.1版本后activeRowType为single情况下，按shift点选行不起作用。

### 期望结果

按shift点选行，可以高亮多行。

### 实际结果

只高亮一行

### 补充说明

另外，希望增加按ctrl可以跳行多选。

**Comment by chaishi** [comment]
有点奇怪，1.7.1 没有看到高亮相关的代码变更。
我抽空看下可能的原因。

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-common/pull/1680
