### ISSUE TITLE
[table]  更新本地数据，表格不会变化

### ISSUE THREAD

**Issue by Hiram-Wong** [Tencent/tdesign-vue-next#3757]
### tdesign-vue-next 版本

1.7.1

### 重现链接

https://stackblitz.com/edit/zue3jf?file=src%2Fdemo.vue

### 重现步骤

本地数据添加数据，表格不会更新
手动切换分页，表格不会更新
<img width="1414" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/30908279/1251e507-f5a7-458a-bc17-e58b4d310a64">

### 期望结果

数据正常更新

**Comment by chaishi** [comment]
凡事 `defaultXXX` 都表示非受控属性，仅第一次赋值有效，故而下方代码执行无效。
如果需要在父组件控制页码和分页大小，可以更为使用 `current` 和 `pageSize`。
```
const rehandlePageChange = (curr) => {
pagination.defaultCurrent = curr.current;
pagination.defaultPageSize = curr.pageSize;
};
```

**Comment by JinPing5306** [comment]
这个垃圾框架，你们开发人员都是废物吗？连个table都不会封装，赶紧解散吧
