### ISSUE TITLE
[t-input] 在flex布局下有值和无值状态宽度不一致

### ISSUE THREAD

**Issue by Brokenstrings** [Tencent/tdesign-vue-next#3768]
### tdesign-vue-next 版本

1.7.1

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/7030227/c8ace60e-5bca-48db-818e-2194a88777ba)

以上代码运行后，没有输入内容时候两个输入框宽度一致，其中一个输入内容后会自动边宽。好像相同的问题不止在t-input这个组件，类似还有t-select
补充说明，如果父级元素宽度不够小或输入框元素不够多看不出来问题。感觉t-input这个组件会在有内容的时候会赋值宽度并自动展开。

### 期望结果

不管有没有输入内容希望输入框都是一样的宽度。

### 实际结果

没有值的时候两个input平分宽度，如果其中一个输入了内容宽度会自动变大，导致整体布局被破坏

### Node版本

16.17.1

### 补充说明

像是t-input会有最小的宽度，输入内容的时候会自动展开，其实并不需要这样的效果。

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign-vue-next/issues/3767
