### ISSUE TITLE
[Slider] 实现changeEnd事件

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue-next#3772]
### 这个功能解决了什么问题

目前的change API无法满足部分常见的用户场景
<img width="666" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/8727c12d-6396-41f7-9dd4-9fe48e0bb33b">

### 你建议的方案是什么
实现changeEnd事件，满足用户在拖动结束时触发事件回调的需求
1. 通过API平台获取新增的changeEnd事件的类型及文档
2. 在组件中实现changeEnd事件，在拖动结束`mouseup`时及点击滑动条时都触发此事件
## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-01-05 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by Lyan-u** [comment]
已认领
