### ISSUE TITLE
[Switch] 表单内点击按钮时 返回的row应该是改变后的row而不是改变前的值

### ISSUE THREAD

**Issue by wuhongru222** [Tencent/tdesign-vue-next#3775]
### tdesign-vue-next 版本

1.6.2

### 重现步骤

当在表单中 这样写       <template #activated="{ row }">
        <t-space>
          <span>未激活</span>
          <t-switch
            v-model="row.activated"
            :custom-value="['1', '0']"
            :label="renderContent"
            size="large"
            @change="postActivated(row)"
          ></t-switch>
          <span>激活</span>
        </t-space>
      </template>
      const postActivated = async (row) => {
  console.log(8888,row)
  const data = {
    id: row.id,
    activated: row.activated,
  };
  await Api.isActivated(data);
  await getUserPage();
};
重复这样点击一两次 返回的row 里面的activated的值 不是操作的值 而是表单内的值  

### 期望结果

我点击按钮时  返回的row应该是改变后的row而不是改变前的值

### 实际结果

我点击按钮时  返回的row是操作之前的row

### 系统版本

w11

### Node版本

16.14.0

**Comment by wuhongru222** [comment]
http://218.61.32.87:3003/
账号 admin
密码 3edc_4rfv
设置 用户管理  是否激活 点两下 然后 点击上方的搜索 然后再点两下 你看传值

**Comment by uyarn** [comment]
@wuhongru222 竟是母校的项目 ：）
1. 请问说表格还是表单？row 应该是表格吧？
2. 方便的话还是把上面的代码放到codesandbox里最小复现 方便我们确认复现路径 可以打开站点找个类似的示例代码改下

**Comment by 13156550123** [comment]
> http://218.61.32.87:3003/ 账号 admin 密码 3edc_4rfv 设置 用户管理 是否激活 点两下 然后 点击上方的搜索 然后再点两下 你看传值

你用的是Tdesign开关组件的原生方法么？还是自己重新封装了一个方法。我用的一个系统里面，它是封装了一个方法，大致思路是获取当前列的id，从:data=“tableData”的tableData里面遍历，拿到这个id的对象，再从对象里面拿到switch的值，很麻烦

**Comment by ATravelerGo** [comment]
顶
