### ISSUE TITLE
[table]使用树形表格，点击展开收起后，展开单个节点节点错乱

### ISSUE THREAD

**Issue by a1074160894** [Tencent/tdesign-vue-next#3777]
### tdesign-vue-next 版本

1.7.2

### 重现步骤

官网示例
https://tdesign.tencent.com/vue-next/components/table#%E6%A0%91%E5%BD%A2%E7%BB%93%E6%9E%84%E7%9A%84%E8%A1%A8%E6%A0%BC
先点一次展开全部，然后收起全部，点击除第一个可展开节点以外的展开节点，节点错乱。
无法复现，多尝试几次
![1703572534184](https://github.com/Tencent/tdesign-vue-next/assets/17264840/1d8ff012-4cb0-457b-87fd-4ac213960200)

### 期望结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/17264840/2b91ea54-9657-4211-a806-6acf08d7f2cf)

### 实际结果

错乱节点的表格
![1703572568881](https://github.com/Tencent/tdesign-vue-next/assets/17264840/695df4b1-0ac8-4fcc-b400-a97a86cbbedc)

**Comment by a1074160894** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/17264840/53f1fb41-8180-479a-8e1b-675a70554dd3)
![image](https://github.com/Tencent/tdesign-vue-next/assets/17264840/0ab73dbb-37b2-4d90-b65a-e091c70c7cbc)
展开再收起操作之后。这里的rowIndex错误，导致点击除第一个子集非空的节点错乱，需要针对这个rowIndex重新编排。
下面是改动之后的代码，修改之后本地运行正常。
![image](https://github.com/Tencent/tdesign-vue-next/assets/17264840/7b098165-ee3a-4b76-a6e3-7b148c796d2f)
希望尽早修复 @chaishi @PengYYYYY

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-common/pull/1729

下次如果已经定位到问题，可以直接提交 PR 修复。（可以避免两个人重复花费时间定位问题，我从其他渠道得知的这个问题）

**Comment by uyarn** [comment]
fixed 1.9.0
