### ISSUE TITLE
[ColorPicker] 新增颜色节点删除功能

### ISSUE THREAD

**Issue by ananzhusen** [Tencent/tdesign-vue-next#3786]
### 这个功能解决了什么问题

![image](https://github.com/Tencent/tdesign-vue-next/assets/48847159/e0f36125-775e-47e3-b063-a8ea5a9c3461)
如图所示，希望拖动节点超出滑块，喜欢能够删除该颜色节点。

### 你建议的方案是什么

#

**Comment by uyarn** [comment]
和大多数设计工具的交互是一致的 点击回删键就删除了
