### ISSUE TITLE
获取1.7.2版本之后遇到的bug

### ISSUE THREAD

**Issue by liweixiang123** [Tencent/tdesign-vue-next#3796]
启动项目后点击菜单里的链接跳转，页面并没有刷新出想要去的页面，发现浏览器搜索框显示正确的路径。如果刷新的话页面会正常刷新，尝试解决但是现在还没有解决这个问题

**Comment by Zccf** [comment]
@liweixiang123  请问你解决了这个问题了吗 ？我也遇到类似的问题了，但是没有解决
