### ISSUE TITLE
Drawer 抽屉点击确定无法关闭抽屉&&取消关闭卡顿

### ISSUE THREAD

**Issue by mishizhiya** [Tencent/tdesign-vue-next#38]
![5](https://user-images.githubusercontent.com/54994665/147214740-acf0d98c-e48f-4fde-8def-b34a154ca268.png)
抽屉从顶部弹出时关闭明显相对于其他三个位置弹出卡顿，点击确定按钮无法关闭抽屉

**Comment by chaishi** [comment]
问题处理过，应该是还没发布

**Comment by pengYYYYY** [comment]
点击事件已经处理，顶部弹出位置暂时还未解决，有兴趣处理的话，欢迎提PR @mishizhiya

**Comment by pengYYYYY** [comment]
修复PR： https://github.com/Tencent/tdesign-common/pull/60
