### ISSUE TITLE
[Table] Dialog中的Table组件吸顶失效

### ISSUE THREAD

**Issue by guo-yonghang** [Tencent/tdesign-vue-next#3804]
### tdesign-vue-next 版本

1.7.2

### 重现链接

https://github.com/guo-yonghang/table-affix-issue

### 重现步骤

```text
<template>
  <t-button @click="visible = true">打开</t-button>
  <t-dialog v-model:visible="visible" title="demo" width="800px"
    :headerAffixedTop="{ offsetTop: 200, zIndex: 30000 }">
    <t-table row-key="id" :bordered="true" :data="data" :columns="columns"> </t-table>
  </t-dialog>
</template>

<script setup>
import { ref } from 'vue'

const visible = ref(false)

const data = ref([])

for (let i = 0; i < 20; i++) {
  data.value.push({
    id: 'id' + i,
    name: 'name' + i,
    age: 'age' + i,
    gender: 'gender' + i,
    address: 'address' + i,
    phone: 'phone' + i,
    email: 'email' + i,
  })
}

const columns = [
  { colKey: 'id', title: 'ID', align: 'center' },
  { colKey: 'name', title: '姓名', align: 'center' },
  { colKey: 'age', title: '年龄', align: 'center' },
  { colKey: 'gender', title: '性别', align: 'center' },
  { colKey: 'address', title: '地址', align: 'center' },
  { colKey: 'phone', title: '手机号', align: 'center' },
  { colKey: 'email', title: '邮箱', align: 'center' },
]
</script>
```

### 期望结果

表头区域吸顶成功

### 实际结果

表头区域吸顶失效

### 框架版本

Vue(3.3.11)

### 浏览器版本

Chrome(120.0.6099.130)

### 系统版本

Windows11

### Node版本

v20.8.0

### 补充说明

如果设置了col的width属性，配置吸顶属性时，表头尺寸会错乱

**Comment by chaishi** [comment]
通过 API `headerAffixedTop.container` 设置滚动容器为 Dialog 组件里面的滚动元素。（默认滚动容器为 body）
示例：`headerAffixedTop = { container: '.t-dialog__body' }`

https://tdesign.tencent.com/vue-next/components/affix?tab=api

<img width="912" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/86ffad31-f601-4b95-a5f5-f43373aad21d">

<img width="942" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/758be141-79c0-4a4f-a541-e489516ff051">
