### ISSUE TITLE
【table】编辑表格validateTableData会返回历史的校验信息

### ISSUE THREAD

**Issue by ZJQ0925** [Tencent/tdesign-vue-next#3812]
### tdesign-vue-next 版本

1.7.2

### 重现链接

https://stackblitz.com/edit/ksphta?file=src%2Fdemo.vue

### 重现步骤

1、点击新增一行编辑数据，点击校验按钮，这时校验会不通过，然后点击删除当前这行数据后；
2、重新点击新增一行新数据，输入信息后点击校验，这时validateTableData会返回上一次第一条的历史校验不通过的信息

### 期望结果

点击校验调用validateTableData API应该不返回历史校验信息才对，只校验当前编辑表格内数据项。

### 实际结果

调用validateTableData API会返回上一次第一条的历史校验不通过的信息

### 框架版本

vue@3.3.9

**Comment by uyarn** [comment]
fixed 1.10.6
