### ISSUE TITLE
Descriptions 描述组件

### ISSUE THREAD

**Issue by qingmang** [Tencent/tdesign-vue-next#3813]
### 这个功能解决了什么问题

完善基础组件库

### 你建议的方案是什么

这么组件为什么这么难产？

**Comment by qingmang** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/67047984/424c1760-42ab-4fcc-af16-ef912289c8b7)

**Comment by qingmang** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/67047984/9b606dc5-259e-49e0-8f4d-dc6832f66943)
@uyarn 这字体色彩是不是太浅了 。背景色太深

**Comment by uyarn** [comment]
> ![image](https://private-user-images.githubusercontent.com/67047984/294211529-9b606dc5-259e-49e0-8f4d-dc6832f66943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTUwNDgsIm5iZiI6MTcwNDYxNDc0OCwicGF0aCI6Ii82NzA0Nzk4NC8yOTQyMTE1MjktOWI2MDZkYzUtMjU5ZS00OWUwLThmNGQtZGM2ODMyZjY2OTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZDA4OTRiNWMyOTdhODIxYTA4MTBmNGJlOGM0NzMxODQ5OGNkMGM2N2NiNDA3N2U0MDYwZDAzYWRmNDBkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7t-XBs3HGx6S1gzwipWqu9AMd6TI7QiVVo8QCA7QvU) @uyarn 这字体色彩是不是太浅了 。背景色太深

@RADWIMPS426

**Comment by RADWIMPS426** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/67047984/294211529-9b606dc5-259e-49e0-8f4d-dc6832f66943.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2MTUwNDgsIm5iZiI6MTcwNDYxNDc0OCwicGF0aCI6Ii82NzA0Nzk4NC8yOTQyMTE1MjktOWI2MDZkYzUtMjU5ZS00OWUwLThmNGQtZGM2ODMyZjY2OTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA3VDA4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3ZDA4OTRiNWMyOTdhODIxYTA4MTBmNGJlOGM0NzMxODQ5OGNkMGM2N2NiNDA3N2U0MDYwZDAzYWRmNDBkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7t-XBs3HGx6S1gzwipWqu9AMd6TI7QiVVo8QCA7QvU) @uyarn这种字体色彩并不是太浅了。背景色太深了
> 
> @RADWIMPS426

是的，这里是有两个原因。第一是因为需要兼顾无边框模式下，label项和content项的一个区别对比，帮助获取重点信息。content项的颜色是几乎黑色的，所以label项的字体颜色就需要处理得比较浅。第二个原因是需要对齐其它组件原有的设计样式，比如table组件。
