### ISSUE TITLE
[Select] 希望支持 Object 对象选择

### ISSUE THREAD

**Issue by ali-pay** [Tencent/tdesign-vue-next#3823]
### 这个功能解决了什么问题

当前 options 的 value 仅支持 String Number，因此 select 获取到的只有 label 和 value，希望能参照 Element，使选中后，能获取到完整的 option 对象

### 你建议的方案是什么

Element 使用值键 value-key 属性
https://element-plus.org/zh-CN/component/select.html#%E4%BD%BF%E7%94%A8%E5%80%BC%E9%94%AE-value-key-%E5%B1%9E%E6%80%A7

**Comment by uyarn** [comment]
可以通过onChange中的context来获取整个选项的内容去做处理 支持object的改动太多 容易影响现在的功能稳定性
