### ISSUE TITLE
【select】希望多选可以配置去掉checkbox

### ISSUE THREAD

**Issue by daisy0123** [Tencent/tdesign-vue-next#383]
### 这个功能解决了什么问题
多选可以配置去掉checkbox

### 你建议的方案是什么？
多选可以配置去掉checkbox

**Comment by pengYYYYY** [comment]
哈喽，您指的是这种交互嘛
<img width="484" alt="wecom-temp-c5439bb875535f5569bbaf671f74cc28" src="https://user-images.githubusercontent.com/35833812/156169340-ed70bf4a-2b97-475c-8d61-9d86cba40a95.png">

**Comment by daisy0123** [comment]
恩恩 或者支持自定义配置 ?

**Comment by daisy0123** [comment]
checkbox 占位太多 且显得太突出 不好看，希望能支持

**Comment by pengYYYYY** [comment]
我们这边会评估一下

**Comment by daisy0123** [comment]
感谢
