### ISSUE TITLE
[Menu] 官网给出的例子传递了无用参数

### ISSUE THREAD

**Issue by Yuzu-io** [Tencent/tdesign-vue-next#3846]
### tdesign-vue-next 版本

1.8.0

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/69612382/39468639-51a4-40dc-8b84-8ee6db19c8fb)

官网中的例子传入的 height 参数无任何效果，API 文档中也无 height 参数说明，是否是写错了

**Comment by uyarn** [comment]
应该是之前比较早起的demo 我们改正下 谢谢指出
