### ISSUE TITLE
isFunction is not a function

### ISSUE THREAD

**Issue by a445073286** [Tencent/tdesign-vue-next#3848]
### tdesign-vue-next 版本

1.8.0

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/31469423/823d5881-f3f8-4984-b585-24a550a261ce)
项目之前正常，现在启动的时候报Uncaught TypeError: isFunction is not a function，升级或者重装都不可以

### 系统版本

Windows11

### Node版本

v20.9.0

**Comment by uyarn** [comment]
之前是指什么时候？

**Comment by a445073286** [comment]
> 之前是指什么时候？
安装完图标组件并全局引入之后就出现这个问题了

**Comment by uyarn** [comment]
全局引入图标组件？

**Comment by ace0109** [comment]
我也出现了一模一样的报错，引入了葡萄城的[SpreadJS](https://www.grapecity.com.cn/developer/spreadjs)后，出现这个报错，也是Activity.tsx，把图标库依赖删了，不使用td的图标库，就正常了

**Comment by uyarn** [comment]
还有一个引入了vue draggable的也有类似的问题 🤔 我们继续排查看看

**Comment by uyarn** [comment]
@ace0109 @a445073286 可以看看main.ts/main.js的import 顺序吗 我们这边有个业务是引入顺序导致的

**Comment by uyarn** [comment]
这个问题是由于几个依赖在打成chunk的时候产生的 确认下任意import tdesign-icons 的语句是否有在import vue的语句之前 如果有调整一下即可
