### ISSUE TITLE
[Select] 组件宽度与Popup宽度不一致

### ISSUE THREAD

**Issue by OrenZhang** [Tencent/tdesign-vue-next#3859]
### tdesign-vue-next 版本

1.8.0

### 重现步骤

<img width="1287" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/41963680/6c6e9dc4-4f14-481e-a1e6-95ecae356664">

### 框架版本

vue ^3.2.37

### 浏览器版本

120.0.6099.216

### 系统版本

14.3 Beta版(23D5051b)

### Node版本

18.17.0

**Comment by chaishi** [comment]
找一下 CSS，看看浮层是不是设置了 max-width: 500px 一类的限制，覆盖一下这个应该就可以了

**Comment by OrenZhang** [comment]
看了下，有个width: 1000px的配置，但不是我设置的

<img width="419" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/41963680/9df494cd-220e-4e41-91fd-6c70c1632f4f">

**Comment by OrenZhang** [comment]
看起来是这个原因导致的，请问有可以覆盖的方式吗

<img width="918" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/41963680/d74f65e1-1efc-4944-90af-4fe77f9cc257">

**Comment by uyarn** [comment]
popup默认最大1000 设计如此。
直接通过popup overlayInnerStyle设置width覆盖就行
