### ISSUE TITLE
[EnhancedTable] expandedTreeNodes回填不生效，【表格数据和expandedTreeNodes数据都是同时异步获取的时候不生效】

### ISSUE THREAD

**Issue by xinller** [Tencent/tdesign-vue-next#3873]
### tdesign-vue-next 版本

1.8.0

### 重现链接

https://codesandbox.io/p/sandbox/tree-table-forked-4cw62y?file=%2Fsrc%2FDemo.vue%3A12%2C16

### 重现步骤

data的数据如果为异步的，同时v-model:expandedTreeNodes的数据也是异步设置的，无法展开，除非在data渲染完以后在设置展开节点才能生效

**Comment by chaishi** [comment]
fixed in https://github.com/Tencent/tdesign-vue-next/pull/3967

**Comment by uyarn** [comment]
fixed 1.9.0
