### ISSUE TITLE
[table] t-card 包裹 t-table 组件，滚动条吸顶底下会有问题 

### ISSUE THREAD

**Issue by you-hei-mi** [Tencent/tdesign-vue-next#3878]
### tdesign-vue-next 版本

1.8.0

### 重现链接

https://stackblitz.com/edit/dxv5wy-sspleq?file=package.json,src%2Fdemo.vue

### 重现步骤

[table] t-card 包裹 t-table 组件，滚动条吸顶底下会有问题，但是，当表尾吸顶和滚动条吸底功能又正常。
![动画](https://github.com/Tencent/tdesign-vue-next/assets/33774921/159424a9-caa6-45a8-88cd-f3dfbcb1de47)

### 期望结果

t-card 包裹 t-table 组件，滚动条吸顶底不要异常显示

### 实际结果

t-card 包裹 t-table 组件，滚动条吸顶底异常显示，不管滚动到什么位置，滚动条依然显示

### Node版本

18.16.0

**Comment by chaishi** [comment]
所有的吸附功能，都基于组件 Affix 开发。
故而，所有的吸附功能，也需要明确指定是在哪个元素里面滚动，也就是指明滚动容器。

示例代码如下：
```html
<t-table :horizontalScrollAffixedBottom="{ container: '.t-card' }" />
```

<img width="927" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/42c30443-c8a6-4fb4-b6fb-ea66eff8e6a8">


https://tdesign.tencent.com/vue-next/components/affix?tab=api
<img width="941" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/11605702/fba46a9a-69bb-4319-8072-3acaa77bd74d">
