### ISSUE TITLE
[DatePicker] 给timepicker透传format: "HH:mm"时，切换右侧timepicker无效

### ISSUE THREAD

**Issue by xiufj** [Tencent/tdesign-vue-next#3879]
### tdesign-vue-next 版本

1.8.0

### 重现链接

https://stackblitz.com/edit/jsrtva?file=package.json,src%2Fdemo.vue

### 重现步骤

   
![image](https://github.com/Tencent/tdesign-vue-next/assets/150098837/1b4b3df5-02f0-437f-a6f5-e67733235d2c)

**Comment by uyarn** [comment]
format也配下 加个`format="YYYY-MM-DD: HH:mm"` 就可以了
