### ISSUE TITLE
[Table] 最新版本谷歌浏览器，滚动条样式不兼容

### ISSUE THREAD

**Issue by xiufj** [Tencent/tdesign-vue-next#3887]
### tdesign-vue-next 版本

1.8.0

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/150098837/69bf5a5c-d08a-4985-890a-eb9795f90445)
![314c5215da316da81433a60928bbbd20](https://github.com/Tencent/tdesign-vue-next/assets/150098837/b8b31e84-ea9a-43ae-8f4e-a6a2d84e70a8)

**Comment by xiufj** [comment]
请问这个问题还会修复吗

**Comment by zhensherlock** [comment]
mac 上的chrome和firefox也有问题

**Comment by uyarn** [comment]
已经修复了 下个版本带上

**Comment by uyarn** [comment]
fixed 1.9.4
