### ISSUE TITLE
[Dialog] 增加onBeforeClose回调

### ISSUE THREAD

**Issue by raohuiyong** [Tencent/tdesign-vue-next#3888]
### 这个功能解决了什么问题

Dialog对话框做表单的时候，点击“确定”提交数据，数据响应可能需要一些时间，这时候用户可以关闭弹窗不是很友好。
我希望在关闭前做一些业务拦截

### 你建议的方案是什么

新增onBeforeClose函数，类似于[Element对话框组件](https://element-plus.org/zh-CN/component/dialog.html#attributes)的before-close关闭前的回调，会暂停 Dialog 的关闭. 回调函数内执行 done 参数方法的时候才是真正关闭对话框的时候.

**Comment by Yacj** [comment]
可以参考这个issues 
[https://github.com/Tencent/tdesign-vue-next/issues/3086](url)
代码示例
[https://stackblitz.com/edit/gvvr1q?file=package.json,src%2Fdemo.vue](url)

**Comment by raohuiyong** [comment]
@Yacj 根据案例，并未解决我提出的问题。根据案例操作，当我打开弹窗后，再点击【保存】按钮，这个时候在加载中如果点击右上角关闭icon、取消按钮、模态框背景、ESC依然可以关闭弹窗。我的需求是，在加载中，不允许关闭弹框，[Element对话框](https://element-plus.org/zh-CN/component/dialog.html#attributes)组件是这么实现的

**Comment by czq297297** [comment]
+1 希望可以增加

**Comment by dmyz** [comment]
的确需要

**Comment by uyarn** [comment]
supported 1.10.4
