### ISSUE TITLE
Drawer 默认的确认按钮无效

### ISSUE THREAD

**Issue by Alexhueng** [Tencent/tdesign-vue-next#39]
![image](https://user-images.githubusercontent.com/44539014/147217862-bfe42523-0a80-4813-b66a-e9c55e7fee5b.png)
![image](https://user-images.githubusercontent.com/44539014/147218023-d2b129d4-e2ee-4e0e-9f44-8fdecf9a276a.png)

绑定了onConfirm属性, 点击时无效.
另外, 同时绑定属性onConfirm和事件confirmd会导致vue的警告
![image](https://user-images.githubusercontent.com/44539014/147218307-ad8af4fc-965b-43e0-8b4f-082e819a6a0f.png)
此二api是否重复.

使用自定义的按钮可以正常使用, 如图打印出了confirm.
![image](https://user-images.githubusercontent.com/44539014/147218526-7d4775d1-0905-431c-a279-34bb6e46eb51.png)

**Comment by pengYYYYY** [comment]
onConfirm这个API不触发下个版本会修复，同时传入onConfirm，@confirm，这两个其实是一样的，会被解析成数组

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/13 关于点击不生效的问题在这个PR已经处理
