### ISSUE TITLE
[TagInput] TagInput 折叠的部分看不到内容

### ISSUE THREAD

**Issue by Anturin** [Tencent/tdesign-vue-next#3914]
### 这个功能解决了什么问题

TagInput 折叠的部分看不到内容

### 你建议的方案是什么

鼠标移动到折叠的 Tag 时，能够触发弹窗，显示折叠起来的 Tags。

**Comment by uyarn** [comment]
https://tdesign.tencent.com/vue-next/components/select#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8A%98%E5%8F%A0%E9%80%89%E4%B8%AD%E9%A1%B9%E9%80%89%E6%8B%A9%E5%99%A8
<img width="951" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/a453c163-459a-414f-9e21-3a1b346d00f5">
可以参考下这个DEMO的第二个示例
