### ISSUE TITLE
[Dialog] Dialog组件的confirm-btn传入null会出现ts错误

### ISSUE THREAD

**Issue by kkk48ku** [Tencent/tdesign-vue-next#3919]
### tdesign-vue-next 版本

1.8.0

### 重现步骤

<img width="927" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/41846364/3534b798-30d9-4878-986e-18ab2170590f">

**Comment by sertceps** [comment]
1.9.0 也出现了
![image](https://github.com/Tencent/tdesign-vue-next/assets/39348429/027639e7-42a4-40b7-8007-a87a9102f29b)
