### ISSUE TITLE
dialog对话框-插件函数式调用-按空格会让背景越来越黑

### ISSUE THREAD

**Issue by Miao0er** [Tencent/tdesign-vue-next#394]
### 重现链接
https://stackblitz.com/run

### 重现步骤
官网示例dialog组件使用插件函数调用，打开弹窗时按空格会创建新的弹窗

### 期望结果
按空格不创建新的弹窗

### 实际结果
按空格会创建新的弹窗

### 补充说明
我知道可以通过判断dialog是否存在决定是否创建并调用新的dialog，但是我觉得组件应该有好的办法避免按空格重复创建的问题

| Environment | Info |
|---|---|
| 相关版本 | 0.9.2 |
| 框架版本 / 基础库版本 | VUE3 |
| 系统、浏览器 | Chrome |
| Node版本 | 13 |
<img width="641" alt="image" src="https://user-images.githubusercontent.com/37327757/156561869-84976327-65b7-45ef-b4b7-8d6861849396.png">

**Comment by pengYYYYY** [comment]
0.9.3 已修复
