### ISSUE TITLE
[Swiper] pc端鼠标拖拽无法切换slide

### ISSUE THREAD

**Issue by wiidz** [Tencent/tdesign-vue-next#3947]
### tdesign-vue-next 版本

1.8.1

### 期望结果

支持鼠标拖拽切换slide

### 实际结果

不支持

### 补充说明

pc端鼠标拖拽无法切换slide，只能通过click或hover navigation进行切换

**Comment by uyarn** [comment]
拖拽哪里？麻烦给个截图
