### ISSUE TITLE
[Descriptions] 嵌套的描述组件无法单独设置边框

### ISSUE THREAD

**Issue by dntc** [Tencent/tdesign-vue-next#3952]
### tdesign-vue-next 版本

1.8.1

### 重现链接

https://codesandbox.io/p/devbox/tdesign-vue-next-demo-forked-594rdz?file=%2Fsrc%2Fdemo.vue

### 期望结果

嵌套的描述组件能够单独控制是否显示边框

### 实际结果

嵌套的描述组件不能单独控制是否显示边框，会和外层的描述组件保持一致。

### 框架版本

Vue(3.3.9)

### 浏览器版本

Edge(121.0.2277.128)

### 系统版本

Windows 11 23H2

**Comment by uyarn** [comment]
fixed 1.9.0
