### ISSUE TITLE
[Drawer] drawer drag size

### ISSUE THREAD

**Issue by ZWkang** [Tencent/tdesign-vue-next#3954]
### 这个功能解决了什么问题

在某些场景中，我需要开启 drawer drag 动态调整宽度
而且随着 size 的变化，我希望缓存下我拖动的 drawer 距离，以便下次打开时，宽度仍然一致，但是目前似乎没有办法获得我拖拽的宽度。
还有包括是否能自定义拖拽的最大距离或最小距离。

### 你建议的方案是什么

将 size 定义为响应式，使其拖拽时候能响应 size 的变化，从而使得业务能缓存 size 值。
提供  drag max value 自定义限制拖拽范围。

**Comment by chaishi** [comment]
新增以下 API，

1. 属性：`sizeDraggable`，抽屉大小可拖拽调整，横向抽屉调整宽度，纵向抽屉调整高度。`sizeDraggable.max` 和 `sizeDraggable.min` 用于控制拖拽尺寸大小限制
TS 类型定义：`boolean | SizeDragLimit`    `interface SizeDragLimit { max: number, min: number }`

2. 事件：`sizeDragEnd`，抽屉大小拖拽结束时触发，事件参数 `size` 在横向抽屉中表示宽度，在纵向抽屉中表示高度
事件参数：`(context: { e: DragEvent; size: number })`


通过项目获取最新 API 定义
git clone https://github.com/TDesignOteam/tdesign-api
npm run api:docs Drawer "VueNext(PC)" finalProject
npm run api:docs Drawer "Vue(PC)" finalProject,useDefault
npm run api:docs Drawer "React(PC)" finalProject

**Comment by ZWkang** [comment]
@chaishi 这里的 event 事件应该是 MouseEvent ? 貌似是 binding 在 mousemove mouseup 的

**Comment by chaishi** [comment]
@ZWkang 已更新

**Comment by uyarn** [comment]
published 1.9.6
