### ISSUE TITLE
[水印组件] 可以通过修改display:none或者opacity属性，变为空白

### ISSUE THREAD

**Issue by huliang1996618** [Tencent/tdesign-vue-next#3955]
### tdesign-vue-next 版本

1.8.1

### 重现步骤

直接修改样式display:none

### 期望结果

水印存在

### 实际结果

水印消失
![image](https://github.com/Tencent/tdesign-vue-next/assets/19297983/58d35b98-6086-4bce-97fa-41aa47361787)

**Comment by uyarn** [comment]
这个问题之前讨论过 其实不论单纯前端UI水印怎么通过 js/css 防止修改 都有办法绕开 暂时不考虑修改 如果有合适的方案也可以讨论下
