### ISSUE TITLE
[t-form] input组件type=number时，表单规则设置len:11，手机号输入会报错

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#3957]
### tdesign-vue-next 版本

1.8.1

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/3871365/0f26050e-702f-4de2-b328-d60e8a95250b)

![image](https://github.com/Tencent/tdesign-vue-next/assets/3871365/abb9bad2-9f4b-44ee-9dc9-d6dc90c63d45)

input type=number 场景下， 表单验证 加了 len=11 ,  
在IOS手机端输入时验证不过去。
value值被转成number了， 导致表单验证length过去不

<img width="1007" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/3871365/cfa8a0f9-1c08-4386-9af6-6081ec9d0ece">

**Comment by uyarn** [comment]
fixed 1.9.0
