### ISSUE TITLE
[date-range-picker] 周日期选择器设置初始时间显示错误

### ISSUE THREAD

**Issue by LoveBaoDuo** [Tencent/tdesign-vue-next#3989]
### tdesign-vue-next 版本

1.8.1

### 重现链接

https://stackblitz.com/edit/angular-3diqyp-z1u1co?file=src%2Fdemo.vue

### 重现步骤

设置一个['2024-02-26', '2024-03-03']初始值

### 期望结果

正确显示该日期所在周

### 实际结果

错误显示为2024年-1周

**Comment by uyarn** [comment]
fixed 1.9.6, thanks for @Ericleungs
