### ISSUE TITLE
[Form 表单] 表单校验success状态显示异常

### ISSUE THREAD

**Issue by muduixi** [Tencent/tdesign-vue-next#3991]
### tdesign-vue-next 版本

1.8.1

### 重现步骤

<template>
  <t-dialog
    confirm-btn="添加"
    :on-confirm="submitForm"
    :visible="visible" :on-close="handleClose"
    width="600px"
  >
    <template #header>
      <div>
        <t-icon name="user-add" color="green" />
        <span style="vertical-align: middle">添加用户</span>
      </div>
    </template>
    <div>
      <t-form
        :data="userInfo"
        @submit="submitForm"
        :statusIcon="true"
        :rules="rules"
        ref="formRef"
      >

        <t-form-item label="用户名" name="username">
          <t-input v-model="userInfo.username" placeholder="请输入用户名" autocomplete="off" ></t-input>
        </t-form-item>
        <t-form-item label="密码" name="password">
          <t-input v-model="userInfo.password" type="password" placeholder="请输入密码" autocomplete="off"></t-input>
        </t-form-item>
        <t-form-item label="角色">
          <t-select v-model="userInfo.role" placeholder="请选择角色">
            <t-option v-for="role in roles" :key="role.id" :value="role.id" :label="role.zhName"></t-option>
          </t-select>
        </t-form-item>
        <t-form-item label="是否启用">
          <t-switch v-model="userInfo.enabled"></t-switch>
        </t-form-item>
      </t-form>
    </div>
  </t-dialog>
</template>

<script setup>
import { onMounted, ref} from 'vue';
import {request} from "@/utils/request";
import {MessagePlugin} from "tdesign-vue-next";

//弹窗关闭相关
const props = defineProps({
  visible: Boolean
});
const emit = defineEmits(['update:visible']);
function handleClose() {
  emit('update:visible', false);
}

//定义数据及属性
const roles = ref([]);//角色列表
const userInfo = ref({
  username: '',
  password: '',
  role:2,//默认普通用户
  enabled: true,//默认启用
});

//表单校验逻辑
const formRef = ref(null); // 用于访问表单实例
//验证用户名是否符合规则以及是否已存在
const validateUsername = async(value) => {
  try {
    const username = value;
    // 注意：使用params携带查询参数
    const response = await request.get({
      url: '/user/getUserByUsername',
      params: { username }, // 确保params是一个对象
    });
    if (response && response.code === 200) {
      // 用户名不存在，可以使用
      return {message: '用户名可用',type: 'success'}
    }
  } catch (error) {
    return  {message: '用户名已存在',type: error.message}
  }

};

const rules = ref({
  // username: [
  //   { required: true, message: '请输入用户名', trigger: 'blur' },
  //   { validator: validateUsernamew, trigger: 'blur' ,message: '错误的',type: 'error'}
  // ],
  username: [
    { required: true, message: '请输入用户名', trigger: 'blur' },
    { validator: validateUsername, trigger: 'blur' }
  ],
  // 其他规则
});

//初始化时查询权限列表
onMounted(async ()=> {
  try {
    const response = await request.get({ url: '/role/list'});
    roles.value = response.data;
  }catch (error){
    // console.error(error)
    await MessagePlugin.error(error.message);
  }
})

async function submitForm() {
  console.log(666)
}

//增加用户
async function addUser() {
  try {
    await request.post({
      url: '/user/add',
      data: {}
    });
    await MessagePlugin.success('新增用户成功');
  }catch (error){
    await MessagePlugin.error('新增用户失败，原因：'+error);
  }
}
</script>

<style scoped>

</style>

### 期望结果

前台通过校验应该是绿色的 现在通过校验是黄色的 其他正常

### 实际结果

前台校验通过是是黄色的
![1](https://github.com/Tencent/tdesign-vue-next/assets/45171029/1da44f96-5ccf-490b-8d6f-211c828a5af7)

### 框架版本

~3.3.8

### 系统版本

win11

### Node版本

21.4.0

### 补充说明

用的是TDesign的模板页面

**Comment by uyarn** [comment]
可以放到codesandbox里面复现下吗 打开站点的Form的示例随便点一个codesandbox或者stackblitz复现下呢

**Comment by uyarn** [comment]
无法复现这个问题也一直没回复 如果还确实有问题麻烦提供复现链接并打开一个issue
