### ISSUE TITLE
table

### ISSUE THREAD

**Issue by Bananer-fl** [Tencent/tdesign-vue-next#3994]
### tdesign-vue-next 版本

^1.8.0

### 重现步骤

表格组件-树形结构的数据-第一个例子 
把drag-sort的值换成col或者row-hander-col会报错，就是列拖拽会报错，行拖拽是好的

### 期望结果

解决一下，不知道是不是本身就是这么设计的，树状不让列拖拽？但是冒红报错，应该不对，本身设计应该会有提示说明

### Node版本

v20.4.0

**Comment by Bananer-fl** [comment]
1111

**Comment by uyarn** [comment]
树状目前无法拖拽
