### ISSUE TITLE
table表格 最小宽度问题

### ISSUE THREAD

**Issue by zqy159** [Tencent/tdesign-vue-next#40]
1.table表格设置了最小宽度时，挤压到最小会按照最小宽度平均值设置 
例如 ：1.有2列设置了minWidth 分别为100 和 200  挤压到最小，这两列默认的最小宽度都会置为（100+200）/2 .     
            2.有2列，1列设置了minWidth为100，另外一列自适应，这两列默认的最小宽度都会置为（100+0）/2 .     

2.table表格是不是必须要设置一个固定列，才能去进行滚动，感觉蛮奇怪的。

**Comment by pengYYYYY** [comment]
已收到问题，正在处理

**Comment by chaishi** [comment]
期望是：只要超出就会滚动

**Comment by LeeJim** [comment]
想要达成最小宽度的效果，使用 width 才对，用 minWidth 反而是错的。
后续估计会移除掉这个 minWidth 。

另外，这个滚动估计和 minWidth 的实现有关，建议将 minWidth 都改成 width 之后看看？

**Comment by pengYYYYY** [comment]
已和用户沟通并提供处理方案，issue关闭
