### ISSUE TITLE
[Table] active-change的参数好像不太对

### ISSUE THREAD

**Issue by Bananer-fl** [Tencent/tdesign-vue-next#4000]
### tdesign-vue-next 版本

^1.8.0

### 重现步骤

在多选的情况下取消一行，触发的active-change的ActiveChangeContext的activeRowList是空的无论是否还剩余有选中的行，与activeRowKeys对应不上，设计就是这样的嘛。。。那activeRowList这个命名怕是不太对。。

### 期望结果

例如多选状态下，选了三行，取消一行触发active-change时，ActiveChangeContext的activeRowList应该还有剩余的两行，与activeRowKeys对应上

### Node版本

v20.4.0

**Comment by XBIsland** [comment]
`activeRowType` 为 `multiple` 时，取消高亮时会执行 `useRowHighlight` 中的 `handleInactive` 函数，该函数将 `activeRowList` 赋值为 `[]` ，所以 `active-change` 时获取到的 `activeRowList` 永远为 `[]`。

![image](https://github.com/Tencent/tdesign-vue-next/assets/36447895/fc372d55-f71e-4465-b134-d0c6b8dbb8a2)

**Comment by uyarn** [comment]
fixed 1.9.1, thanks for @XBIsland
