### ISSUE TITLE
[select] 点击下拉列表报错 

### ISSUE THREAD

**Issue by river666** [Tencent/tdesign-vue-next#4007]
### tdesign-vue-next 版本

1.8.1

### 重现步骤

main.ts
import TDesign from 'tdesign-vue-next';
import 'tdesign-vue-next/es/style/index.css';
app.use(TDesign);
demo.vue
<template>
    <t-select>
        <t-option key="apple" label="Apple" value="apple" />
        <t-option key="orange" label="Orange" value="orange"
        >OrangeContentSlot</t-option
        >
        <t-option key="banana" label="Banana" value="banana" />
    </t-select>
</template>
效果
![image](https://github.com/Tencent/tdesign-vue-next/assets/35917804/25496ea4-6a76-43d5-ad50-8c5f99238e3f)
![image](https://github.com/Tencent/tdesign-vue-next/assets/35917804/c20658df-984e-4a04-80ea-696567397244)

### 期望结果

点击不报错

### 实际结果

点击报错
![image](https://github.com/Tencent/tdesign-vue-next/assets/35917804/b5be5b86-be9e-4092-8066-e44cb256502f)

### 框架版本

Vue(3.2.13)

### Node版本

18

**Comment by river666** [comment]
APP.vue
`<template>
    <t-select>
        <t-option key="apple" label="Apple" value="apple" />
        <t-option key="orange" label="Orange" value="orange"
        >OrangeContentSlot</t-option
        >
        <t-option key="banana" label="Banana" value="banana" />
    </t-select>
</tempalte>
`

**Comment by river666** [comment]
APP.vue
`<template>
    <t-select>
        <t-option key="apple" label="Apple" value="apple" />
        <t-option key="orange" label="Orange" value="orange"
        >OrangeContentSlot</t-option
        >
        <t-option key="banana" label="Banana" value="banana" />
    </t-select>
</tempalte>
`

**Comment by XBIsland** [comment]
> APP.vue `<template> <t-select> <t-option key="apple" label="Apple" value="apple" /> <t-option key="orange" label="Orange" value="orange" >OrangeContentSlot</t-option > <t-option key="banana" label="Banana" value="banana" /> </t-select> </tempalte> `

template 拼写错误
