### ISSUE TITLE
date-picker组件在季度模式时设置format或value-type属性会导致组件选择时错误

### ISSUE THREAD

**Issue by bingodd3** [Tencent/tdesign-vue-next#4012]
### tdesign-vue-next 版本

1.3.0

### 重现链接

https://stackblitz.com/edit/plq3x6?file=src%2Fdemo.vue

### 重现步骤

1.点击组件选择2,3,4季度
2.组件显示错误
3.设置value时同理

### 期望结果

正常显示

### 实际结果

显示错误

### Node版本

16.20.1

**Comment by uyarn** [comment]
这个问题 组件内部不太合适特地处理 可以通过要上的valueDisplay功能 自己定义下使用
