### ISSUE TITLE
global.d.ts 编辑器提示存在问题？

### ISSUE THREAD

**Issue by yanhao98** [Tencent/tdesign-vue-next#4013]
### tdesign-vue-next 版本

1.9.0

### 重现步骤

根据 [文档-快速开始-编辑器提示](https://tdesign.tencent.com/vue-next/getting-started#%E7%BC%96%E8%BE%91%E5%99%A8%E6%8F%90%E7%A4%BA) 在 tsconfig.json 的 `includes` 属性中增加 `node_modules/tdesign-vue-next/global.d.ts`

### 期望结果

编辑器能正常提示组件名。

### 实际结果

<img width="1164" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/37316281/b5f485e5-9d54-4c8a-873e-25e1815eddfb">

### 框架版本

Vue(3.4.21)

### 补充说明

我发现将 global.d.ts 文件的 `declare module '@vue/runtime-core' {` 修改成 `declare module 'vue' {` 后可以正常提示。↓
我是 vite 的项目。还根据文档配置了 [通过插件按需引用使用](https://tdesign.tencent.com/vue-next/getting-started#%E9%80%9A%E8%BF%87%E6%8F%92%E4%BB%B6%E6%8C%89%E9%9C%80%E5%BC%95%E7%94%A8%E4%BD%BF%E7%94%A8) 。插件是可以生成 `components.d.ts` 但是必须要在编译之后才会生成。会造成第一次使用某个组件没有提示。

<img width="1167" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/37316281/658882e9-fc39-4913-90a7-8b28463c4f49">

**Comment by uyarn** [comment]
如果是 vue3.3是否正常呢 现有的global.d.ts

**Comment by yanhao98** [comment]
https://github.com/unplugin/unplugin-vue-components/blob/main/src/core/declaration.ts#L123

这个是 unplugin-vue-components 生成.d.ts文件的代码。
