### ISSUE TITLE
[ColorPicker]切换其他色值点进行颜色配置又跳回第一个点的

### ISSUE THREAD

**Issue by ananzhusen** [Tencent/tdesign-vue-next#4015]
### tdesign-vue-next 版本

1.9.0

### 重现链接

https://tdesign.tencent.com/vue-next/components/color-picker

### 补充说明

官方的组件就有问题，1.8.x,1.7.x无此问题

**Comment by ananzhusen** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/48847159/7ab3b3d5-a9a4-4401-9066-74b980e284d5)

可以直接操作一下就能明白

**Comment by XBIsland** [comment]
看起来这个问题是由 #4005 引起的，这个 pr 修复的是 #4002。

1. 每次触发 `emitColorChange` 函数都会更改 `innerValue` 的值，从而触发了 `new Color()` 。
![image](https://github.com/Tencent/tdesign-vue-next/assets/36447895/3b44dfd4-31b4-41f1-9615-4b5a4e908d56)
2. `Color` 类初始化时调用的 `update` 函数会重置 `selectedId` 为第一个 `point`，导致无法拖动渐变功能的第二个 `point`。
![image](https://github.com/Tencent/tdesign-vue-next/assets/36447895/bd1d43f6-63e0-4bcf-af6a-9c1a01a481ee)

**Comment by uyarn** [comment]
fixed in 1.9.1 thanks for @XBIsland
