### ISSUE TITLE
[Cascader] 组件传入的options的某一option的value为0时，选择该option，选中态不会被改变

### ISSUE THREAD

**Issue by kkk48ku** [Tencent/tdesign-vue-next#4021]
### tdesign-vue-next 版本

1.9.0

### 重现链接

https://stackblitz.com/edit/aqa5w4?file=package.json,src%2Fdemo.vue

### 重现步骤

<img width="1108" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/41846364/669a9fae-4112-4762-b2b3-7c2b1f606fef">

**Comment by XBIsland** [comment]
https://github.com/Tencent/tdesign-vue-next/blob/e43d9b64fab33eccafddbcdf0ddc9912c4115737/src/cascader/core/effect.ts?plain=1#L207C1-L207C15

**Comment by XBIsland** [comment]
`treeStoreExpendEffect` 忽略了 `val = 0` 的情况
https://github.com/Tencent/tdesign-vue-next/blob/e43d9b64fab33eccafddbcdf0ddc9912c4115737/src/cascader/core/effect.ts#L207

`getTreeValue` 函数同上
https://github.com/Tencent/tdesign-vue-next/blob/e43d9b64fab33eccafddbcdf0ddc9912c4115737/src/cascader/core/helper.ts#L100

**Comment by uyarn** [comment]
fixed in 1.9.1
