### ISSUE TITLE
[ DatePicker] DatePicker 日期选择器 增加 valueDisplay 呈现区域的样式

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#4026]
### 这个功能解决了什么问题

<img width="400" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/3871365/e12c5738-add9-4bef-bb87-49c0eb161025">

<img width="531" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/3871365/26395c90-bf1f-40ea-af9c-609f74af941b">

### 你建议的方案是什么

<img width="937" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/3871365/ac4a5d80-bdc8-4cf4-bff5-bf9116106bad">
增加 valueDisplay 呈现区域的样式

**Comment by uyarn** [comment]
supported 1.9.1
