### ISSUE TITLE
[t-tooltip]希望tooltip中的内容可以支持html、换行

### ISSUE THREAD

**Issue by xdandyx** [Tencent/tdesign-vue-next#403]
### 这个功能解决了什么问题
多行文本展示更美观

### 你建议的方案是什么？
v-html

**Comment by pengYYYYY** [comment]
https://stackblitz.com/edit/angular-jy799g?file=src%2Fdemo.vue

**Comment by xdandyx** [comment]
> https://stackblitz.com/edit/angular-jy799g?file=src%2Fdemo.vue
> 
> 可以这么写

非常感谢！经验证:
```vue
<template #content>{{str.replace(/\n/g,'<br/>')}}</template>
```
直接写不行，还得再套一层,如下：
```vue
<template #content>
<pre v-html="str.replace(/\n/g,'<br/>')">
</template>
```
