### ISSUE TITLE
[table] expandedRow 可展开和收起的表格，jsx的map遍历后续报错

### ISSUE THREAD

**Issue by naix1024** [Tencent/tdesign-vue-next#4035]
### tdesign-vue-next 版本

0.9.0

### 期望结果

我在做一个表格，用到了可展开和收起的功能。
我想实现的是点击的时候，调用一个同步请求，用这一行的某个参数去后台获取详细信息，然后把内容在下面展开，一般的详细信息都是没问题的。
但是有一部分是明细，需要循环遍历出来，我在**jsx中使用map循环**的时候，就会出现**第一次成功**，后续**map会报错失败**。

我想问一下是我的代码错误还是**rowIndex是不是不应该这样用**，如果是的话，要怎么实现要预期的效果呢。

以下是js代码的部分

![image](https://github.com/Tencent/tdesign-vue-next/assets/29498746/9ee051a5-aaea-4090-bdf9-9dc9989609d4)
![image](https://github.com/Tencent/tdesign-vue-next/assets/29498746/7b770582-25f4-4df6-bcf4-15e8f3598ac5)
![image](https://github.com/Tencent/tdesign-vue-next/assets/29498746/6d32bba9-ad9d-4fec-8553-2ddd9a8726cb)

报错截图

![image](https://github.com/Tencent/tdesign-vue-next/assets/29498746/317ecd2c-0db8-4255-90c6-40a1e83c2528)

### 实际结果

可展开和收起的表格，jsx中map第二次遍历时报错

**Comment by naix1024** [comment]
给力嗷，铁子。
试了一下，已经实现我想要的效果了，就是还是有报错，emitsOptions是只出现一次，map是每一次都会出现。
  
**当然我现在已经很满意了，非常感谢！ **

![image](https://github.com/Tencent/tdesign-vue-next/assets/29498746/482592d2-bf81-4cb3-8b4e-f693dede59be)

![image](https://github.com/Tencent/tdesign-vue-next/assets/29498746/d978c050-4f3a-42e1-9520-c9641afef695)

![image](https://github.com/Tencent/tdesign-vue-next/assets/29498746/03b59714-f604-4c30-b956-84e22eb1400a)


> 或许你可以试试在你的 `rehandleExpandChange` 中获取异步数据，将数据添加进渲染表格的 `data`，而在 `expandedRow` 函数中只需要处理数据并返回 `TNode` 。
> 
> 下面是基于 `1.9.0` 版本的一个例子，实际和你的版本可能有点出入。
> 
> ```
> const rehandleExpandChange = async (value, params) => {
>   expandedRowKeys.value = value;
> 
>   const rowId = params?.id;
>   const { data: subData } = await fetchSubData(rowId); // 请求远程子数据
>   params.currentRowData.subData = subData; // 将子数据赋值给当前行
> };
> 
> const expandedRow = (h, { row, index }) => {
>   return (
>     <div class="more-detail">
>       {row?.subData?.map((t) => (
>         <span>{t.field}</span>
>       ))}
>     </div>
>   );
> };
> ```

**Comment by XBIsland** [comment]
@naix1024 不客气，`map`的报错用可选链运算符 (`?.`) 处理。`emitsOptions` 是 Vue 的报错，需要你自己排查下。

**Comment by naix1024** [comment]
@XBIsland     好的，map的问题用?.解决了，emitsOptions的报错也一并没有了，非常感谢你的帮助！
