### ISSUE TITLE
[Bug][Cascader] 叶子结点存在相同值时异常表现

### ISSUE THREAD

**Issue by lucktangpeng** [Tencent/tdesign-vue-next#404]
### 重现链接
https://codesandbox.io/s/condescending-roman-ujutpj?file=/src/App.vue

### 重现步骤
点击第一个选项，查看它显示的选择对象是否正确，它会显示成其他选择对象

### 期望结果
显示我点击的选项

### 实际结果
显示了下面其他选项

| Environment | Info |
|---|---|
| 相关版本 | 0.9.4 |
| 框架版本 / 基础库版本 | Vue3.0 |
| 系统、浏览器 | chrome |
| Node版本 |  |

**Comment by pengYYYYY** [comment]
cascader依赖tree组件，需要节点为唯一key，可以处理一下数据源
