### ISSUE TITLE
[t-loading] 使用unplugin-vue-components按需加载，v-loading指令无效

### ISSUE THREAD

**Issue by raohuiyong** [Tencent/tdesign-vue-next#4041]
### tdesign-vue-next 版本

1.9.0

### 重现步骤

<div style="height: 300px; background: red" v-loading="formData.loading">
    测试v-loading
 </div>

### 期望结果

按需加载，v-loading能正常使用

### 实际结果

v-loading无法生效

### 框架版本

vue 3.4.21
unplugin-vue-components 0.26.0
unplugin-auto-import 0.17.5

### 系统版本

win10

### Node版本

node 18.19.0

**Comment by XBIsland** [comment]
[unplugin-vue-components](https://github.com/unplugin/unplugin-vue-components) 项目中 `TDesignResolver` 默认只注入了 `['DialogPlugin', 'LoadingPlugin', 'MessagePlugin', 'NotifyPlugin']`，没有注入 `directive`。

**Comment by raohuiyong** [comment]
> [unplugin-vue-components](https://github.com/unplugin/unplugin-vue-components) 项目中 `TDesignResolver` 默认只注入了 `['DialogPlugin', 'LoadingPlugin', 'MessagePlugin', 'NotifyPlugin']`，没有注入 `directive`。

意思是我要单独引入loading组件的directive指令？

**Comment by uyarn** [comment]
esm -> es

**Comment by uyarn** [comment]
unplugin那边我也去提交处理下
