### ISSUE TITLE
[select] select 多选时删除能不删掉已选定的 tag 么。

### ISSUE THREAD

**Issue by LeeLejia** [Tencent/tdesign-vue-next#4043]
### 这个功能解决了什么问题

由于组件是支持自定义 选中元素的，当元素单行的时候删除很容易理解。
当元素很多，而且换行的时候，不小心 delete 了哪些元素很难发现。

### 你建议的方案是什么

提供 delete 不删除选中元素的选项。

**Comment by uyarn** [comment]
没理解需要提供什么
