### ISSUE TITLE
[Menu] 滚动条样式问题

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#4052]
### tdesign-vue-next 版本

1.9.0

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/30982989/3aa92f87-bf89-4b2c-bf63-37225040cd2b)

**Comment by uyarn** [comment]
好像是新版本的chrome.. 昨天有业务也反馈了这个情况

**Comment by uyarn** [comment]
fixed 1.9.4 https://github.com/Tencent/tdesign-common/pull/1765
