### ISSUE TITLE
[Progress] 需要可拖动的进度条

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next#4053]
### 这个功能解决了什么问题

主要音量调整等业务场景

### 你建议的方案是什么

参考arco
<img width="1204" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/8606851/cfaff12f-fe71-4c82-b15c-a12d70254f1a">

**Comment by HaixingOoO** [comment]
@Jiachang-Cai [slide-滑块更适合你吧](https://tdesign.tencent.com/vue-next/components/slider)你看看

**Comment by uyarn** [comment]
打开代码 里面是slider组件 进度条就是展示功能 不应该有交互
