### ISSUE TITLE
[t-cascader] value不允许传递数字类型，一直报警告。

### ISSUE THREAD

**Issue by kailiming** [Tencent/tdesign-vue-next#4064]
### tdesign-vue-next 版本

1.6.6

### 重现步骤

Invalid prop: type check failed for prop "value". Expected String with value "13", got Number with value 13. 

### 框架版本

Vue(3.3.4)

### 系统版本

Windows11

### Node版本

18.16.1

**Comment by kailiming** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/128564436/eea0b9a8-b569-4f34-8658-f44204eccb19)

**Comment by uyarn** [comment]
这个问题已经修复过了 升级下就可以
