### ISSUE TITLE
[Tabs 选项卡] 建议增加Tab选项卡标题编辑功能

### ISSUE THREAD

**Issue by entireyu** [Tencent/tdesign-vue-next#4072]
### 这个功能解决了什么问题

Tab选项卡目前已经支持了"Add"操作，但如果想要设置Tab的label，需要做一个输入框插槽（但这又是一个糟糕的方法，因为Input的无边框模式目前还在开发中）或者是其它方法。

### 你建议的方案是什么

建议可以加一个功能，双击选项卡时，编辑选项卡的label。

**Comment by uyarn** [comment]
等下无边框模式吧

**Comment by uyarn** [comment]
support input borderless 1.9.5
