### ISSUE TITLE
[v-loading] Failed to resolve directive: loading

### ISSUE THREAD

**Issue by ilii** [Tencent/tdesign-vue-next#4080]
### tdesign-vue-next 版本

1.9.3

### 重现链接

无

### 重现步骤

<div v-loading="loading1" class="loading-container">Loading...</div>

### 实际结果

错误详情
```
[Vue warn]: Failed to resolve directive: loading 
  at <Add onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <Content> 
  at <TContent> 
  at <TLayout> 
  at <TLayout> 
  at <Layouts class="dark" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView key="cn" class="dark" > 
  at <TConfigProvider global-config= 
Object { pagination: {…}, cascader: {…}, calendar: {…}, transfer: {…}, timePicker: {…}, dialog: {…}, drawer: {…}, popconfirm: {…}, table: {…}, select: {…}, … }
 > 
  at <App>
```

### 系统版本

Windows 11 X64

### 补充说明

vscode 开发模式 Vue 3.4.21 Vite 5.2.3 tdesign 1.9.3

**Comment by uyarn** [comment]
简单测试了一下可以正常使用 麻烦提供个最小的复现DEMO呢？

**Comment by mayday97** [comment]
我也遇到了
![image](https://github.com/Tencent/tdesign-vue-next/assets/39096258/96fb36b9-dcc7-4af7-a484-d17a010449e9)
![image](https://github.com/Tencent/tdesign-vue-next/assets/39096258/e364f8b3-2a0b-44ff-94e2-c92e3df87e6d)

"tdesign-vue-next": "^1.9.3",
"unplugin-auto-import": "^0.17.5",
    "unplugin-vue-components": "^0.26.0",
    "vue": "^3.4.21",

**Comment by mayday97** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/39096258/882fcc1e-1ba5-44e2-bc31-a47fd90ad888)

**Comment by uyarn** [comment]
@mayday97 unplugin tdesign的没有支持directive 你的场景直接用table的loading API就可以 不需要用v-loading
