### ISSUE TITLE
[t-date-range-picker] 组件format展示异常

### ISSUE THREAD

**Issue by ruanlinxin** [Tencent/tdesign-vue-next#4083]
### tdesign-vue-next 版本

1.9.3

### 重现步骤

```js
<template>
  <div>
    <t-date-range-picker v-model:value="x" format="YY-MM" value-type="YYYY-MM-DD"></t-date-range-picker>
    {{ x }}
  </div>
</template>
<script setup lang="ts">
const x = ref([]);
</script>
```

### 期望结果

输入框应该按照YY取年份后两位

### 实际结果

年份取了前两位
<img width="639" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/53412119/eff6e21d-bf6e-4fce-8e72-e74ea37014ee">

### 框架版本

3.2.31

**Comment by ruanlinxin** [comment]
补充bug,文档中描述format属性只影响展示不影响value，实际情况value受到影响
![image](https://github.com/Tencent/tdesign-vue-next/assets/53412119/890e6621-80e4-4a3d-ac66-5242c9c200a0)

```js
<template>
  <div>
    <t-date-range-picker v-model:value="x" format="YY-MM"></t-date-range-picker>
    {{ x }}
  </div>
</template>
<script setup lang="ts">
const x = ref([]);
</script>
```

![image](https://github.com/Tencent/tdesign-vue-next/assets/53412119/0c4b7bbc-0dfc-49f9-b7f7-853ddd018286)

**Comment by uyarn** [comment]
fixed 1.9.6, thanks for @Ericleungs
