### ISSUE TITLE
global.d.ts 中缺少一些组件，目前发现的有t-icon,t-content

### ISSUE THREAD

**Issue by zhangjing1992** [Tencent/tdesign-vue-next#4095]
### tdesign-vue-next 版本

1.9.3

### Node版本

20.10.9

### 补充说明

webstorm不提示，可以正常用，但是没有代码提示，并显示未知标签名称
## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-04-14 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
fixed 1.9.4
