### ISSUE TITLE
[BUG][Icon] 组件动态切换无效

### ISSUE THREAD

**Issue by zqy159** [Tencent/tdesign-vue-next#41]
`<icon-font :name="collapsed ? 'menu-fold' : 'menu-unfold'">` 当我改变collapsed值时组件name并未切换。

如果分开写成2个能正常切换 
`<icon-font v-if="collapsed" name="menu-fold"><icon-font v-else name="menu-unfold">`

**Comment by uyarn** [comment]
已修复 但由于此前锁住了版本，如果直接使用`t-icon`的方式需要等待下个vue-next的版本发布；


如果着急 可以直接`npm install tdesign-icons-vue-next@0.0.5`；

`import { Icon } from 'tdesign-icons-vue-next';`

把使用 `t-icon` 的换成 `icon` 即可
