### ISSUE TITLE
[DatePicker] 周选择器 dayjs('2023-01-01').format('YYYY-WW') 会显为 2023-52

### ISSUE THREAD

**Issue by DYS1230** [Tencent/tdesign-vue-next#4100]
### tdesign-vue-next 版本

1.9.3

### 重现链接

https://stackblitz.com/edit/jc3wkj?file=package.json,src%2Fdemo.vue

### 重现步骤

周选择器，选中 23年1月1日。会显示2023-52。

### 期望结果

显示成 2022-52周。

### 实际结果

显示2023-52

**Comment by uyarn** [comment]
这个问题已经修复了 可以先使用1.9.4-alpha.3 下周正式版本会带上

**Comment by uyarn** [comment]
fixed 1.9.4
