### ISSUE TITLE
[TextArea] autosize 属性在 Firefox 下失效

### ISSUE THREAD

**Issue by JesseCrebest** [Tencent/tdesign-vue-next#4103]
### tdesign-vue-next 版本

1.9.3

### 重现链接

https://stackblitz.com/edit/3mxvmr-wmzji2?file=src%2Fdemo.vue

### 重现步骤

分别在 Chrome 和 Firefox 浏览器打开重现链接

### 期望结果

Chrome 和 Firefox 里输入很多内容高度都可以自动撑开

### 实际结果

Chrome 里输入很多内容高度可以自动撑开，Firefox 里没有自动撑开。

### 框架版本

Vue(3.3.9)

### 浏览器版本

FireFox(124.0.2 (64 位))

### 系统版本

Windows 11 家庭版

### Node版本

v20.12.0

**Comment by XBIsland** [comment]
调试了下，发现 Firefox 对 `textarea` 设置 `overflow: hidden` 后首次获取到的 `scrollHeight` 是错误的。

**Comment by uyarn** [comment]
fixed 1.9.4
