### ISSUE TITLE
[t-tabs] 拖拽功能与手动新增结合使用时出现异常问题

### ISSUE THREAD

**Issue by Mophar-gift** [Tencent/tdesign-vue-next#4106]
### tdesign-vue-next 版本

1.9.3

### 重现链接

https://stackblitz.com/edit/xgn2bf?file=src%2Fdemo.vue

### 重现步骤

1.开启拖拽功能；
2.加一个新增按钮，当点击新增时往原数据里push一个元素；
3.通过拖拽交换最后两个元素位置（拖拽选项卡3换至选项卡4），随后点击新增添加元素；
4.问题出现：新增的元素出现在异常的位置上。

![image](https://github.com/Tencent/tdesign-vue-next/assets/67857649/20b8cffc-98d2-4631-bc0f-58c15f92dd79)

### 期望结果

push 的元素应该出现在最后，与原数据一致

### 实际结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/67857649/5efb764c-84ae-4654-be94-051458de0f22)

### 框架版本

Vue(3.3.9)

### 浏览器版本

Chrome(123.0.6312.107)

### 系统版本

win11

### Node版本

18.18.0 /  20.11.0

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-04-18 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
fixed 1.9.4 thanks @Liao-js  🌹
