### ISSUE TITLE
[dialog]  dialog里面的滚轮样式无法被修改

### ISSUE THREAD

**Issue by sizq-it** [Tencent/tdesign-vue-next#4114]
### tdesign-vue-next 版本

1.9.3

### 重现步骤

<template>
  <t-dialog v-model:visible="value3">
    <div class="attr-edit scroll-bar">
      <div class="test"></div>
    </div>
  </t-dialog>
</template>
<script lang="tsx" setup>
const value3 = ref(true);
</script>

<style lang="less">
.attr-edit {
  max-height: 500px;
  overflow-y: auto;
}
.test {
  height: 900px;
  width: 300px;
}
// 滚动条样式
.scroll-bar {
  /* 设置浏览器滚动条的样式 */
  &::-webkit-scrollbar {
    width: 8px;
    height: 8px;
  }

  /* 滚动条滑块 */
  &::-webkit-scrollbar-thumb {
    border-radius: 4px;
    -box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.2);
    background: #707070;
    border: 2px solid #3d3d3d;
  }

  /* 滚动条轨道 */
  &::-webkit-scrollbar-track {
    box-shadow: inset 0 0 5px rgba(0, 0, 0, 0.2);
    border-radius: 3px;
    background: #3d3d3d;
  }
}
</style>

**Comment by uyarn** [comment]
已知问题 已修复 1.9.4的版本会带上

**Comment by uyarn** [comment]
fixed 1.9.4
