### ISSUE TITLE
[Transfer 穿梭框] change事件 获取不到默认回显选中并禁用的数据

### ISSUE THREAD

**Issue by liu-yuren** [Tencent/tdesign-vue-next#4115]
### tdesign-vue-next 版本

1.8.1

### 重现步骤

代码示例

<script setup lang="ts">
const data = [{
  value: 1,
  label: '内容1',
  disabled: false,
}, {
  value: 2,
  label: '内容2',
  disabled: true,
}, {
  value: 3,
  label: '内容3',
  disabled: false,
}]

const value = ref([2])

function transferChange(a: string[], context: any) {
  console.log(a, 'aaa')
  console.log(context, 'context')
}
</script>

<template>
  <t-transfer
    :data="data"
    :value="value"
    @change="transferChange"
  />
</template>

### 框架版本

Vue(3.3.8)

### 浏览器版本

Chrome(123.0.6312.123)

### Node版本

v20.11.1

**Comment by XBIsland** [comment]
没理解，有空提供下最小demo。

**Comment by liu-yuren** [comment]
<script setup lang="ts">
 const data = [
  { value: 1, label: '内容1', disabled: false, }, 
  { value: 2, label: '内容2', disabled: true, }, 
  { value: 3, label: '内容3', disabled: false, }
] 

const value = ref([2])

function transferChange(a: string[]) {
   console.log(a, 'aaa')
} 
</script>
<template>
  <t-transfer
    :data="data"
    :value=value
   @change="transferChange"
  />
</template>

**Comment by liu-yuren** [comment]
[demo.txt](https://github.com/Tencent/tdesign-vue-next/files/15063813/demo.txt)
