### ISSUE TITLE
[upload] upload组件data属性传入Function会报警告

### ISSUE THREAD

**Issue by zhangjing1992** [Tencent/tdesign-vue-next#4116]
### tdesign-vue-next 版本

1.9.3

### 重现步骤

属性data传入函数

### 期望结果

无警告无报错

### 实际结果

vue警告[Vue warn]: Invalid prop: type check failed for prop "data". Expected Object, got Function  

### 框架版本

vue3.4.23

### Node版本

20.9.0

### 补充说明

虽然可以正常上传，但是每次上传控制台都会有很多警告

**Comment by uyarn** [comment]
fixed 1.9.5
