### ISSUE TITLE
[DatePicker] 季度选择器：选择任何季度都显示默认的第一个季度

### ISSUE THREAD

**Issue by Skye-wyb** [Tencent/tdesign-vue-next#4117]
### tdesign-vue-next 版本

1.9.3

### 重现步骤

<img width="492" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/83811499/c484a351-e63b-4821-a308-2563b67ff8cd">

**Comment by uyarn** [comment]
这个问题已经修复过  可以先使用1.9.4-alpha.3

**Comment by uyarn** [comment]
fixed 1.9.4
