### ISSUE TITLE
[improve][TreeSelect] 树选择 增加只会选中 《根节点》 功能

### ISSUE THREAD

**Issue by haikuotianko** [Tencent/tdesign-vue-next#412]
### 这个功能解决了什么问题
如：地区选择器，选择省份=》选择市=》选择区，前两个不会被选中，只会展开

### 你建议的方案是什么？
加一个属性，可以开启 只选择根节点 功能，有子节点的点击只会展开

**Comment by Godlike-meteor** [comment]
Hi，单选是支持选中父节点的，多选目前只能选择叶子节点，如果觉得展示不方便，建议参考这里例子实现：

**Comment by Godlike-meteor** [comment]
Hi，单选是支持选中父节点的，多选目前只能选择叶子节点，如果觉得展示不方便，下一个版本会增加valueDisplay。
