### ISSUE TITLE
[TimePicker]  时间选择器预设快捷时间选择，无法正确使用。

### ISSUE THREAD

**Issue by waney** [Tencent/tdesign-vue-next#4121]
### tdesign-vue-next 版本

1.9.3

### 重现链接

https://tdesign.tencent.com/vue-next/components/time-picker#%E9%A2%84%E8%AE%BE%E5%BF%AB%E6%8D%B7%E6%97%B6%E9%97%B4%E9%80%89%E6%8B%A9

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/69211/d4568c44-1712-4490-8f62-047e818f5781)
官网复现，https://tdesign.tencent.com/vue-next/components/time-picker#%E6%97%B6%E9%97%B4%E5%8C%BA%E9%97%B4%E9%80%89%E6%8B%A9%E5%99%A8

**Comment by uyarn** [comment]
截图里为什么每个区间还是个数组？

**Comment by waney** [comment]
对啊，我就是反馈这个问题啊。

**Comment by waney** [comment]
另外我觉得这里TimeRangePicker 的第二个值可选列表应将小于第一个值的设为不可用，比如：

**Comment by uyarn** [comment]
> 另外我觉得这里TimeRangePicker 的第二个值可选列表应将小于第一个值的设为不可用， 比如：（这里不带日期） 08:00 > 15:30 正确 15:30 > 08:00 错误 22:00 > 01:35 错误 (不能跨日期)

这个问题之前存在争议 所以就没有限制 现在是最宽松的情况 可以根据实际情况在onChange或者onPick的回调中处理不可选的情况

**Comment by waney** [comment]
> > 另外我觉得这里TimeRangePicker 的第二个值可选列表应将小于第一个值的设为不可用， 比如：（这里不带日期） 08:00 > 15:30 正确 15:30 > 08:00 错误 22:00 > 01:35 错误 (不能跨日期)
> 
> 这个问题之前存在争议 所以就没有限制 现在是最宽松的情况 可以根据实际情况在onChange或者onPick的回调中处理不可选的情况

好吧，虽然个人看法Range就应该前后关联，而且在列表里帮助用户筛选掉不可用数据减少用户成本。但只能接受目前的结果。

**Comment by waney** [comment]
> > 另外我觉得这里TimeRangePicker 的第二个值可选列表应将小于第一个值的设为不可用， 比如：（这里不带日期） 08:00 > 15:30 正确 15:30 > 08:00 错误 22:00 > 01:35 错误 (不能跨日期)
> 
> 这个问题之前存在争议 所以就没有限制 现在是最宽松的情况 可以根据实际情况在onChange或者onPick的回调中处理不可选的情况

或者也一样提供一个disabledTime？

**Comment by waney** [comment]
> 可能再新增个API好点 这个我们记录下看看要不要新增API吧 这个issue先处理preset的问题

感谢你们付出，issue实在太多了，

**Comment by waney** [comment]
> 可能再新增个API好点 这个我们记录下看看要不要新增API吧 这个issue先处理preset的问题

感谢你们付出，issue实在太多了，

**Comment by uyarn** [comment]
fixed 1.9.4

**Comment by waney** [comment]
谢谢你，已解决。
