### ISSUE TITLE
[Select] InputValue 改变，必定触发 popup-visible-change 事件

### ISSUE THREAD

**Issue by Cat1007** [Tencent/tdesign-vue-next#4135]
### tdesign-vue-next 版本

1.9.4

### 重现链接

https://tdesign.tencent.com/vue-next/components/select?tab=demo#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

监听 popup-visible-change 事件，输入改变必定触发，此时 popup 的可见性并没有改变

### 期望结果

popup 可见性是还发生变化时，才触发该事件

### 实际结果

input 后直接触发

### 补充说明

https://github.com/Tencent/tdesign-vue-next/blob/9a796eb212ee9c855ee53a8611083e85cd51759d/src/select/select.tsx#L258-L261

留意到该段代码，无论如何都会触发一个为 true 的set事件，实际上如果当前popup已经展示，不应该再反复set进行触发

**Comment by uyarn** [comment]
fixed 1.9.5
