### ISSUE TITLE
[popup] web component下显示bug

### ISSUE THREAD

**Issue by zhige1** [Tencent/tdesign-vue-next#4143]
### tdesign-vue-next 版本

1.9.0

### 重现链接

https://github.com/Tencent/tdesign-vue-next/blob/develop/src/popup/popup.tsx#L270

### 补充说明

web component下触发元素triggerEl最终的parentElement为null，不会是document.body，这就导致组件在web component下永远setVisible(false）

**Comment by uyarn** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/4091 是不是跟这个是一个问题？

**Comment by zhige1** [comment]
> #4091 是不是跟这个是一个问题？可以试试升级到1.9.4

是的是的，感谢！！！
