### ISSUE TITLE
[dialog] draggable 拖拽功能能否增加点击header进行拖拽

### ISSUE THREAD

**Issue by g420714188** [Tencent/tdesign-vue-next#4152]
### 这个功能解决了什么问题

弹出对话padding过大导致页面不美观（客户审美不同），通过修改修改padding 后导致弹出dialog无边框，拖拽失效。希望能增加header拖拽，解决这一问题。谢谢

### 你建议的方案是什么

[dialog] draggable 拖拽功能能否增加点击header进行拖拽

**Comment by uyarn** [comment]
dialog 支持拖拽的 modeless情况下 设置draggable即可

**Comment by g420714188** [comment]
我可能描述的不清楚，问题不用了，谢谢。
