### ISSUE TITLE
[dialog] 通过esc按钮关闭弹窗出错

### ISSUE THREAD

**Issue by KKDKK513** [Tencent/tdesign-vue-next#4153]
### tdesign-vue-next 版本

可以

### 重现链接

https://github.com/KKDKK513/tDesign-dialog-issue.git

### 重现步骤

下载git项目，npm i 安装依赖。npm run dev 启动项目后在浏览器打开。
弹窗默认打开，因为src/demo.vue文件中，33行设置const visible = ref(true); 此时无法通过esc按钮关闭弹窗。
若修改为const visible = ref(false);啧打开弹窗后可以通过esc关闭弹窗。
请问这是bug吗？如果不是，如果我想默认打开一个全屏弹窗，通过esc关闭弹簧，又该如何操作呢

### 期望结果

如果是bug，希望修复。如果不是期望得到如何实现此场景的方法，谢谢！

### 浏览器版本

_谷歌  版本 123.0.6312.123（正式版本） （64 位）_

### Node版本

_18.18.0_

```[tasklist]
### Tasks
```

**Comment by boogie-ben** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/29250685/d2a2fc37-093d-4bbb-aa0b-4101f88a8fee)

的确有这个问题，键盘事件要visible变更过才会设置上

**Comment by KKDKK513** [comment]
好的了解了，请问这个问题后续会修复吗？ 
我尝试这样去修改,但是还是未生效，
`<script setup name="IndexPage">  
import { reactive, onMounted, ref } from "vue"  
const dialogVisible = ref(true)  
dialogVisible.value = false  
dialogVisible.value = true  
</script>`  
或是这样  
`<script setup name="IndexPage">  
import { reactive, onMounted, ref } from "vue"  
onMounted(() => {  
  dialogVisible.value = false  
  dialogVisible.value = true  
}）  
</script>  
`去使得dialogVisible的值变更，
还是无法生效。
目前我是默认值设置为false了，在onMounted周期中设置为true，可以实现功能，但是在页面编译成功后，弹窗弹出时机会慢一点，视觉效果不太好。

**Comment by uyarn** [comment]
先这样使用 问题我们在下个版本跟进修复

**Comment by KKDKK513** [comment]
好的，谢谢
