### ISSUE TITLE
可以增加一个props控制“此刻”按钮是否显示

### ISSUE THREAD

**Issue by ouyanghui100** [Tencent/tdesign-vue-next#4170]
### 这个功能解决了什么问题

现在好像没有props控制“此刻”按钮的显示，造成disable-time规则可被绕过，从而出现bug
![image](https://github.com/Tencent/tdesign-vue-next/assets/67298401/97536647-a760-42c0-860d-74de3b9e1969)

### 你建议的方案是什么

增加一个属性控制此刻按钮的显示

**Comment by uyarn** [comment]
accept

**Comment by uyarn** [comment]
@ouyanghui100 讨论了一下 此刻其实相当于是预设的presets 所以应该是设置了preset的API之后 此刻按钮就应该被用户设置的preset替换 设置为null 应该就没有 这个我们重新调整下

**Comment by ouyanghui100** [comment]
好的， 谢谢

**Comment by uyarn** [comment]
fixed 1.9.5
