### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by wuhongru222** [Tencent/tdesign-vue-next#4175]
### tdesign-vue-next 版本

是

### 重现链接

https://codesandbox.io/p/devbox/x2mwkz?migrateFrom=k47jlg&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvvzsc6l0006356kq09jg47s%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvvzsc6l0002356kgoj8o2hb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvvzsc6l0004356k9ea2qlr1%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvvzsc6l0005356k64otgb45%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvvzsc6l0002356kgoj8o2hb%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvvzsc6k0001356kqq2onuug%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%257D%255D%252C%2522id%2522%253A%2522clvvzsc6l0002356kgoj8o2hb%2522%252C%2522activeTabId%2522%253A%2522clvvzsc6k0001356kqq2onuug%2522%257D%252C%2522clvvzsc6l0005356k64otgb45%2522%253A%257B%2522id%2522%253A%2522clvvzsc6l0005356k64otgb45%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clvvzsc6l0004356k9ea2qlr1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvvzsc6l0003356k5vqvwhkw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvvzscyt0014dcf8fry962qb%2522%257D%255D%252C%2522id%2522%253A%2522clvvzsc6l0004356k9ea2qlr1%2522%252C%2522activeTabId%2522%253A%2522clvvzsc6l0003356k5vqvwhkw%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### 重现步骤

官方哪里 menu导航 双层导航 <t-submenu> 在使用 <t-submenu value="1"  v-for="{val,index} in listArr">循环时 无法读取val中的内容。

### 期望结果

修复bug

### 框架版本

你们的最新的vue3框架

### Node版本

16.14.0

**Comment by uyarn** [comment]
`v-for="(val,index) in listArr"`
