### ISSUE TITLE
[Select] 远程搜索配合过滤，输入筛选条件后，使用键盘上下键+Enter 选择，选中的内容和显示的不符，是上一次筛选结果

### ISSUE THREAD

**Issue by shirleyYing** [Tencent/tdesign-vue-next#4179]
### tdesign-vue-next 版本

1.9.4

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤

1. 输入name，使用键盘上下键选择一个，显示正确
2. 输入test，使用键盘上下键选择，显示的是name—test3
3. 输入test1，使用键盘上下键选择，显示的是test—test3

**Comment by uyarn** [comment]
fixed 1.9.6, thanks for @ZTH520
