### ISSUE TITLE
[t-search] 搜索输入内容后，出现两个清空按钮X

### ISSUE THREAD

**Issue by 1943715762** [Tencent/tdesign-vue-next#4181]
### tdesign-vue-next 版本

复现

### 重现步骤

<t-search v-model="keyword" :clearable="true" shape="round" placeholder="请输入关键词搜索" @search="filterList"  
				@submit="filterList" @clear="filterList" ></t-search>

这段代码，出现两个X
![image](https://github.com/Tencent/tdesign-vue-next/assets/55580893/48055c5a-65ae-4e59-8bc9-9f1cc7b159ed)
![1715246406430](https://github.com/Tencent/tdesign-vue-next/assets/55580893/90f49387-746d-4753-bfc7-cbb526f4b15f)

### 期望结果

去掉前面input框本身的x，只显示后面那个清空按钮

### Node版本

16.15.1

### 补充说明

只是把官网上的案例拿过来，就不好用，但官网示例上好用 1.2.0

**Comment by uyarn** [comment]
请到mobile-vue提个issue https://github.com/Tencent/tdesign-mobile-vue 这个仓库是桌面端的
