### ISSUE TITLE
t-card中使用t-switch，无法阻止默认和冒泡

### ISSUE THREAD

**Issue by GravesDXD** [Tencent/tdesign-vue-next#4186]
### tdesign-vue-next 版本

latest

### 重现步骤

 <t-row :gutter="[16, 24]">
              <t-col v-for="(item, index) in data" :key="item.id">
                <t-card :title="item.title" hover-shadow :style="{ width: '400px' }">
                  <template #actions>
                    <t-switch v-model="item.status" @change.stop.prevent="handleSwitch(item, index)">
                      <template #label="slotProps">{{ slotProps.value ? '开' : '关' }}</template>
                    </t-switch>
                  </template>
                  <div>{{ item.content }}</div>
                  <template #footer>
                    <div class="card_footer">
                      <span><thumb-up-icon />字符数:{{ item.chars }}</span>
                      <span><chat-icon />命中：{{ item.hitNum }}</span>
                    </div>
                  </template>
                </t-card>
              </t-col>
            </t-row>

### 实际结果

![捕获](https://github.com/Tencent/tdesign-vue-next/assets/33920719/6f9be381-fbe8-4400-9d4e-2aa2858250f4)

### 浏览器版本

latest

### Node版本

18.15.0

**Comment by uyarn** [comment]
简单测试了switch在card中的使用没有看到上面的错误，需要你提供下具体的card 和 swtich 的使用代码 上面提供的渲染逻辑和默认 冒泡没有什么关系

**Comment by uyarn** [comment]
太长时间没有回复 此issue先关闭了 如果有需要再打开
