### ISSUE TITLE
[Cascader] 级联选择器 支持 readonly 时该项没有选择框

### ISSUE THREAD

**Issue by linzhenjie** [Tencent/tdesign-vue-next#4187]
### 这个功能解决了什么问题

<img width="475" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/3871365/d534cdc3-57f0-4420-a8a7-272c25f765c1">

### 你建议的方案是什么

<img width="377" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/3871365/7d8bdb38-1e7e-4927-a7bd-15a4cecbbf6b">
由于父级别分类不可勾选，建议支持 option 单项设置readonly:true 来控制checkbox隐藏

**Comment by uyarn** [comment]
讨论了下 readonly 并不合适这样使用 交互和视觉上也不合适
如果只是为了禁止功能选中，可以通过配置disabled,
如果为了保证父级不可选中，可以通过指定层级隐藏选项框的方式实现，参考这个示例 
https://codesandbox.io/p/devbox/vgvcy3?file=%2Fsrc%2Fdemo.vue%3A64%2C39-64%2C40
