### ISSUE TITLE
switch

### ISSUE THREAD

**Issue by Bananer-fl** [Tencent/tdesign-vue-next#4196]
### tdesign-vue-next 版本

1.9.0

### 重现步骤

开关在设置了customValue后，初始化不给c中的值会报错，但是customValue又只能填两个，而在有些动态表单中初始化时，switch的值就是undefined/null

### 期望结果

要么默认undefined/null时不判断customValue是否包含直接给false（customValue[1]）。（不推荐）
要么customValue优化一下允许填多个值之类的，毕竟有些情况switch的值有多种情况会判定为true。例如customValue可以是:[[1,true],[0,false,undefined,null]]。（推荐）

### 实际结果

会直接报错，给的值在customValue种未包含。

抛错地址：switch/switch.js--107行
watch(innerValue, function (val) {
      if (props2.customValue && props2.customValue.length && !props2.customValue.includes(val)) {
        throw new Error("value is not in ".concat(JSON.stringify(props2.customValue)));
      }
    }, {
      immediate: true
    });

### 框架版本

"vue": "^3.4.21",

```[tasklist]
### Tasks
- [ ] 设置defaultValue 也没有效果，如果可以设置defaultValue 也行
- [ ] 同 #4194一样
```

**Comment by uyarn** [comment]
这个样式上做不到呀，还是那个问题 switch只有01 没有第三种 也不应该为了这个场景特地去建额外的逻辑 建议表单生成的时候带上默认值或者换个组件展示吧
