### ISSUE TITLE
分割菜单（混合模式下有效）左小角的版本号不见了，期望能看到

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next#4199]
### 这个功能解决了什么问题

可以结合分割菜单（混合模式下有效）,收缩功能。。。现在版本号是直接超出，被屏幕截断的

### 你建议的方案是什么

![image](https://github.com/Tencent/tdesign-vue-next/assets/78259973/643ab53e-de7b-4b99-9efb-85d38555143f)
![eeb10e9a7f37d433d04a4797cd275d1](https://github.com/Tencent/tdesign-vue-next/assets/78259973/c963f7d3-ca78-43b7-8263-09f69e5c27ff)
![a2772583f128d2e356c31111e07cecd](https://github.com/Tencent/tdesign-vue-next/assets/78259973/e2cecac8-440b-4e48-bac9-fad83352cd00)

**Comment by uyarn** [comment]
根据自己的需求改就可以了
