### ISSUE TITLE
[Cascader 级联选择器] autofocus无效

### ISSUE THREAD

**Issue by 527430408** [Tencent/tdesign-vue-next#4203]
### tdesign-vue-next 版本

1.9.0

### 重现步骤

`<t-cascader ref="cascaderRef" autofocus/>` 无法获取焦点，用ref的形式也无法获取焦点 cascaderRef.value.focus()

 

### 期望结果

能自动获取焦点，cascaderRef.value.focus() 也能生效

### 系统版本

windows10

### Node版本

20.13

**Comment by uyarn** [comment]
autofocus确实是有问题，今天的版本会修复；
ref.focus的问题，因为 cascader 本身不是个具体的input节点 所以它的ref是不能被focus的，需要往里面找到真正的Input节点foucs

**Comment by uyarn** [comment]
autofocus API has been fixed in 1.9.6
