### ISSUE TITLE
[Tabs选项卡] tabs滑块定位问题

### ISSUE THREAD

**Issue by 21stc-09** [Tencent/tdesign-vue-next#4204]
### tdesign-vue-next 版本

1.9.5

### 重现链接

https://tdesign.tencent.com/vue-next/components/tabs?tab=demo#%E5%8F%AF%E6%BB%91%E5%8A%A8%E7%9A%84%E9%80%89%E9%A1%B9%E5%8D%A1

### 重现步骤

官网示例中 可滑动Tabs滑块定位存在问题
![image](https://github.com/Tencent/tdesign-vue-next/assets/53696264/ebd4e6ea-9c83-4bae-a942-bae3cd29d758)

**Comment by uyarn** [comment]
fixed 1.9.6, thanks for @ZTH520
