### ISSUE TITLE
[Table] 新版本设置ellipsis为true，在没有出现省略号的情况下显示Tooltips

### ISSUE THREAD

**Issue by lgs821** [Tencent/tdesign-vue-next#4211]
### tdesign-vue-next 版本

1.9.5

### 重现步骤

在表格配置中，设置ellipsis=true，并且设置table-layout="auto"情况下，单元格一般不会出现省略号，目的是为了能全部显示单元格内容，且不换行，表格内容超出页面宽度会出现横向滚动条，这样能保证表格的行高度一致

### 期望结果

在出现省略号后才显示tooltips

### 实际结果

只要设置了ellipsis，不管有没有出现省略号，都显示tooltips

### 补充说明

有些单元格采用的自定义样式，每个都出现tooltips很影响使用体验，如果需要某个单元格显示tips，建议使用自定义单元格内容的方式来设置，而不是使用ellipsis。

**Comment by uyarn** [comment]
fixed 1.9.6
