### ISSUE TITLE
[Menu 导航菜单] Menu 导航菜单自定义颜色，hove 颜色

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next#4214]
### 这个功能解决了什么问题

![467d8f5616a6ca6efbe75146ddc1c97](https://github.com/Tencent/tdesign-vue-next/assets/78259973/6d1b0380-743d-4873-bdf3-d46216335b16)
[Menu 导航菜单] Menu 导航菜单自定义颜色，hove 颜色

### 你建议的方案是什么

颜色支持修改，有文档提示

**Comment by uyarn** [comment]
<img width="1407" alt="WeChatWorkScreenshot_03c21c1b-52c5-4a1f-9eec-7411a7c14d4d" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/fed7879e-1c3c-4af9-b9bd-a72be08dcd22">
