### ISSUE TITLE
[layout] 导航布局，分割菜单（混合模式下有效），左侧的版本号布局溢出屏幕修复

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next#4216]
### tdesign-vue-next 版本

1.9.5

### 重现步骤

![image](https://github.com/Tencent/tdesign-vue-next/assets/78259973/248eb7fc-6333-4ce0-b660-9ff7d85b9b15)

![image](https://github.com/Tencent/tdesign-vue-next/assets/78259973/eea010a5-0b88-4c38-a867-42ecff8e4d88)
[layout] 导航布局，分割菜单（混合模式下有效），左侧的版本号布局溢出屏幕修复.

### 期望结果

![image](https://github.com/Tencent/tdesign-vue-next/assets/78259973/1510db05-ae9d-4d9f-8732-97cfc4a06949)

目前增加样式
.tdesign-starter-side-nav-mix-fixed {
  .t-default-menu__inner {
     height: calc(100% - var(--td-comp-size-xxxl)) !important;
  }
}
修复。
记得  空格 https://developer.mozilla.org/zh-CN/docs/Web/CSS/calc

**Comment by uyarn** [comment]
项目修复就好 这个组件无关
