### ISSUE TITLE
[Cascader] prefixIcon和suffixIcon的slot不起作用

### ISSUE THREAD

**Issue by Pang-BaiXu** [Tencent/tdesign-vue-next#4225]
### tdesign-vue-next 版本

1.9.5

### 重现步骤

`<t-cascader
        v-model="position"
        :options="options"
        :show-all-levels="false"
        borderless
        placeholder="选择广告位"
      >
        <template #prefixIcon>
          <FilterIcon />
        </template>
      </t-cascader>`

### 期望结果

可以正确作用

### 实际结果

不起作用

### 框架版本

3.4.21

### Node版本

20

## IssueShoot
- 预估时长: 2
- 期望完成时间: 2024-05-31 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by 1379255913** [comment]
已认领

**Comment by uyarn** [comment]
fixed 1.9.6, thanks for @1379255913
