### ISSUE TITLE
[radio-group] 增加一个属性当使用options时可以指定是否使用radio-button来渲染

### ISSUE THREAD

**Issue by DinoDom** [Tencent/tdesign-vue-next#4228]
### 这个功能解决了什么问题

```
<t-radio-group v-model="item.selectType">
  <t-radio-button
    v-for="o in selectTypeOptions"
    :key="o.value"
    :value="o.value"
    :label="o.label"
  />
</t-radio-group>
```

```
<t-radio-group v-model="item.required" :options="requiredOptions" />
```

如上,我想使用radio-button时就必须使用v-for了

### 你建议的方案是什么

增加一个属性当使用options时可以指定是否使用radio-button来渲染

**Comment by uyarn** [comment]
<img width="945" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/555520c7-8fa5-4af2-9eb0-882baaccccfc">

**Comment by uyarn** [comment]
@DinoDom 抱歉 讨论了下 这个现在再增加个API和variant有点难以兼容 只能暂时保持这样 需要radio-button用v for来实现
