### ISSUE TITLE
[Watermark 水印] 水印组件可通过控制台去除内容，从而使水印组件失去意义

### ISSUE THREAD

**Issue by 21stc-09** [Tencent/tdesign-vue-next#4231]
### tdesign-vue-next 版本

1.9.5

### 重现链接

https://tdesign.tencent.com/vue-next/components/watermark

### 重现步骤

在官网对应组件页面，打开控制台，通过控制台的Delete element删除水印元素，或者注释图片水印的图片路径

### 期望结果

保存操作之后，应该恢复操作前的默认属性

### 实际结果

保存操作之后，样式没有恢复示例的默认效果。
其中，图片水印模块可以保持元素依然存在，但是无法恢复图片路径。

实际在demo项目测试结果也官网示例相同
![watermark](https://github.com/Tencent/tdesign-vue-next/assets/53696264/a4773742-9a47-49d6-b4fd-59570e11b1d9)
![watermark2](https://github.com/Tencent/tdesign-vue-next/assets/53696264/136e3808-1084-452a-adaf-38bb39e5cc69)

### Node版本

v20.9.0

**Comment by 21stc-09** [comment]
> 前端的水印都可以被去掉的吧 最粗暴disable javascript 怎么恢复都没用的 如果一定追求非常严谨应该通过其他方式

通过mutationObserver是可以监听元素的状态的。我之前在一个项目中做个水印，是可以做到被修改或者删除（只要发生变化）触发回调，然后在自行回调里恢复元素即可。
我看你们的源码里也有用到mutationObserver，具体不清除你们是不是为了什么情况妥协，还是逻辑没处理完整。
也算是我个人想看看你们处理后的代码，会不会有没有我自己之前没注意到的细节。

相似效果可以看看Element的水印，他们的水印之前和你们一样的缺陷。
https://element-plus.org/zh-CN/component/watermark.html

**Comment by uyarn** [comment]
<img width="488" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/5bf55e57-5863-47a8-98ad-f8ae06d7ee3d">
你试试关闭这个是不是可以删了水印

**Comment by perspectiveboy** [comment]
![image](https://github.com/Tencent/tdesign-vue-next/assets/48466122/a1211d43-dacc-4c49-8055-3862484a4291)
![image](https://github.com/Tencent/tdesign-vue-next/assets/48466122/93bb7397-c76d-4c9a-acf8-0028cfb2651f)

**Comment by uyarn** [comment]
> > 前端的水印都可以被去掉的吧 最粗暴disable javascript 怎么恢复都没用的 如果一定追求非常严谨应该通过其他方式
> 
> 通过mutationObserver是可以监听元素的状态的。我之前在一个项目中做个水印，是可以做到被修改或者删除（只要发生变化）触发回调，然后在自行回调里恢复元素即可。 我看你们的源码里也有用到mutationObserver，具体不清除你们是不是为了什么情况妥协，还是逻辑没处理完整。 也算是我个人想看看你们处理后的代码，会不会有没有我自己之前没注意到的细节。
> 
> 相似效果可以看看Element的水印，他们的水印之前和你们一样的缺陷。 https://element-plus.org/zh-CN/component/watermark.html
mutationObserver的问题我们得确认下 我想表达的是 某个用户知道通过控制台去删元素 且已经有了这个念头 那他完全可以知道通过disable javascript的方式去处理任何存在的在前端组件层面的防御方式 所以前端UI组件只能是 最基础的防御 这个功能做得多完善都不完善。或者你有什么办法能保证你的javascript永远运行

**Comment by uyarn** [comment]
<img width="906" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/ff6620c6-748e-45e4-a0ad-6c599e488cd4">
removable关闭就会一定程度上达到这个效果，可以尝试一下

**Comment by 21stc-09** [comment]
> > > 前端的水印都可以被去掉的吧 最粗暴disable javascript 怎么恢复都没用的 如果一定追求非常严谨应该通过其他方式
> > 
> > 
> > 通过mutationObserver是可以监听元素的状态的。我之前在一个项目中做个水印，是可以做到被修改或者删除（只要发生变化）触发回调，然后在自行回调里恢复元素即可。 我看你们的源码里也有用到mutationObserver，具体不清除你们是不是为了什么情况妥协，还是逻辑没处理完整。 也算是我个人想看看你们处理后的代码，会不会有没有我自己之前没注意到的细节。
> > 相似效果可以看看Element的水印，他们的水印之前和你们一样的缺陷。 https://element-plus.org/zh-CN/component/watermark.html
> 
> mutationObserver的问题我们得确认下 我想表达的是 某个用户知道通过控制台去删元素 且已经有了这个念头 那他完全可以知道通过disable javascript的方式去处理任何存在的在前端组件层面的防御方式 所以前端UI组件只能是 最基础的防御 这个功能做得多完善都不完善。或者你有什么办法能保证你的javascript永远运行

好的，谢谢

**Comment by 21stc-09** [comment]
> ![image](https://private-user-images.githubusercontent.com/48466122/334716474-a1211d43-dacc-4c49-8055-3862484a4291.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzEwOTcsIm5iZiI6MTcxNjk3MDc5NywicGF0aCI6Ii80ODQ2NjEyMi8zMzQ3MTY0NzQtYTEyMTFkNDMtZGFjYy00YzQ5LTgwNTUtMzg2MjQ4NGE0MjkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA4MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNTYyY2ViZWYyOWJjNTIxZjc3YWViODIwMThhMzNiNGRjMzAzMjBhNWVmNTE3NzY4MzU5NzQ5YzAxOWEwNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mvT-zt-1UoMOYm9RHMSreJ48umG79wSAdr_S2AB6K9U) ![image](https://private-user-images.githubusercontent.com/48466122/334716935-93bb7397-c76d-4c9a-acf8-0028cfb2651f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NzEwOTcsIm5iZiI6MTcxNjk3MDc5NywicGF0aCI6Ii80ODQ2NjEyMi8zMzQ3MTY5MzUtOTNiYjczOTctYzc2ZC00YzlhLWFjZjgtMDAyOGNmYjI2NTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA4MTk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmZTJlZmE5YWQwODNiZGUwNmRhY2FlMjQ1YmFkYTU1N2IzZDM4YzY5ZWEyNDY3MzQyOTEzOWNkZDllNTc0MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UftNnmUGB4NEHBQwO1u6OL1mNFU4V9zwqY8IFH7XcNc)

好的谢谢，没看完api不好意思
