### ISSUE TITLE
[t-table] t-table组件的loadingProps属性无效，使用loading插槽只能更改图标后面的文字不能更改图标，不满足业务需求。

### ISSUE THREAD

**Issue by 979680721** [Tencent/tdesign-vue-next#4250]
### tdesign-vue-next 版本

1.9.4

### 重现步骤

在t-table组件上使用`loading-props`绑定一个变量customLoading，customLoading内容如下`const customLoading = ref<LoadingProps>({
  loading: false,
  content: '测试loading',
})`，有一个请求数据的函数`getTableData`,当进入这个函数的时候将`customLoading.value.loading = true`，请求完数据之后将`customLoading.value.loading = false`，经测试没有任何效果.

### 期望结果

希望官方文档给出t-table组件loading-props的使用示例或者给出t-table组件自定义loading图标的示例

### 框架版本

Vue(3.4.27)

### 浏览器版本

Edge(125.0.2535.67)

### 系统版本

Windows11专业版(22631.3447)

### Node版本

18.15.0

### 补充说明

![image](https://github.com/Tencent/tdesign-vue-next/assets/79731490/f8769e77-3790-4b45-a499-d9bd087f30e6)
![image](https://github.com/Tencent/tdesign-vue-next/assets/79731490/bbb3a11f-1487-4ba1-bdf5-60b5d8231bb2)
![image](https://github.com/Tencent/tdesign-vue-next/assets/79731490/7cf35ea7-88e4-4763-8ed0-a05356494459)

**Comment by 979680721** [comment]
> maybe you need `indicator` ` :loading-props="{ indicator: renderIndicator }"` <img alt="image" width="1065" src="https://private-user-images.githubusercontent.com/26377630/336944339-4ab11fd8-f483-4a98-af91-2f72fe5bc2fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAyOTYsIm5iZiI6MTcxNzYzOTk5NiwicGF0aCI6Ii8yNjM3NzYzMC8zMzY5NDQzMzktNGFiMTFmZDgtZjQ4My00YTk4LWFmOTEtMmY3MmZlNWJjMmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAyMTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMGIzYzIyZWZlZTJkOTA3ZjMzMzUyNjI5MzQ1Y2Q5NDZiNmNhMzgyYzM5Mjc5ODk3MDdlMzJjMWQ2NmYyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSIUdAkM0HRFPL64RH2QQQDWPZZK6WGSwZHbjtbIyb0">



> maybe you need `indicator` ` :loading-props="{ indicator: renderIndicator }"` <img alt="image" width="1065" src="https://private-user-images.githubusercontent.com/26377630/336944339-4ab11fd8-f483-4a98-af91-2f72fe5bc2fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NDAyOTYsIm5iZiI6MTcxNzYzOTk5NiwicGF0aCI6Ii8yNjM3NzYzMC8zMzY5NDQzMzktNGFiMTFmZDgtZjQ4My00YTk4LWFmOTEtMmY3MmZlNWJjMmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDAyMTMxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyMGIzYzIyZWZlZTJkOTA3ZjMzMzUyNjI5MzQ1Y2Q5NDZiNmNhMzgyYzM5Mjc5ODk3MDdlMzJjMWQ2NmYyODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FSIUdAkM0HRFPL64RH2QQQDWPZZK6WGSwZHbjtbIyb0">

这里的content为何没有生效

**Comment by uyarn** [comment]
生效了 在左边没截断 随便写了个文字 具体使用的时候再根据需求调整就可以的
