### ISSUE TITLE
[Pagination] 自定义pageSizeOptions有bug

### ISSUE THREAD

**Issue by chenxiang0010** [Tencent/tdesign-vue-next#4275]
### tdesign-vue-next 版本

1.9.6

### 重现步骤

设置了pageSizeOptions后，从第一页切换到最后一页，然后将pageSize改为最大，此时页面显示的是第一页，但是change事件中的current是最后一页。
![Clip_2024-06-11_21-17-38](https://github.com/Tencent/tdesign-vue-next/assets/42428231/bbec1c01-be97-4d32-91dc-efb61809cb40)
![recording](https://github.com/Tencent/tdesign-vue-next/assets/42428231/b4708817-fd16-4ba3-a8a6-96a90623c1af)

### 框架版本

vue@3.4.27

**Comment by uyarn** [comment]
fixed 1.9.7
