### ISSUE TITLE
[Tabel] 单元格超出省略的表格ellipsis浮层中按钮无法点击(官网可重现）

### ISSUE THREAD

**Issue by jianying9** [Tencent/tdesign-vue-next#4277]
### tdesign-vue-next 版本

1.9.6

### 重现链接

https://tdesign.tencent.com/vue-next/components/table#%E5%8D%95%E5%85%83%E6%A0%BC%E8%B6%85%E5%87%BA%E7%9C%81%E7%95%A5%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

官方示例代码，单元格超出省略的表格的列“申请事项”使用ellipsis定义超出省略的浮层内容，浮层中包含一个复制按钮图标。
升级到1.9.6版本后，鼠标移动到“申请事项”，弹出ellipsis浮层。鼠标继续往浮层中按钮图标移动时，浮层会立即消失，导致无法点击按钮。
版本<=1.9.5，鼠标可以正常移动到ellipsis浮层，并点击按钮。

### 期望结果

修复错误

**Comment by tymagic** [comment]
同样复现，另外 下面配置    预期是超出省略实际未生效
{
        colKey: 'durl',
        title: '播放地址',
        ellipsis: true,
        width: 180,
      },

**Comment by xiaojueshi** [comment]
v1.9.7 已处理 @uyarn @jianying9

**Comment by uyarn** [comment]
fixed 1.9.7
