### ISSUE TITLE
[Select] 可过滤的选择器,通过输入关键词筛选后的结果可否多选，而不是选一个之后又需要重新输入

### ISSUE THREAD

**Issue by BryantOut** [Tencent/tdesign-vue-next#4279]
### 这个功能解决了什么问题

<template>
  <t-space direction="vertical">
    <t-select
      v-model="value"
      placeholder="-请选择-"
      :options="options"
      style="width: 200px; display: inline-block; margin: 0 20px 20px 0"
      filterable
      @blur="handleBlur"
      @focus="handleFocus"
      @enter="handleEnter"
    />
    <t-select
      v-model="value2"
      multiple
      placeholder="-请选择-"
      :options="options"
      :filter="filterMethod"
      style="width: 400px; display: inline-block"
      @blur="handleBlur"
      @focus="handleFocus"
    />
  </t-space>
</template>
<script lang="ts" setup>
import { SelectProps } from 'tdesign-vue-next';
import { ref } from 'vue';

const options: SelectProps['options'] = [
  {
    label: '选项一',
    value: '1',
  },
  {
    label: '选项二',
    value: '2',
  },
  {
    label: '选项三',
    value: '3',
  },
  {
    label: 'option4',
    value: '4',
  },
  {
    label: 'OPTION5',
    value: '5',
  },
];
const value = ref('');
const value2 = ref([]);
const filterMethod: SelectProps['filter'] = (search, option) => {
  console.log('filter:', search, option);
  return option.label.indexOf(search) !== -1;
};
const handleBlur: SelectProps['onBlur'] = ({ value, e }) => {
  console.log('handleBlur: ', value, e);
};
const handleFocus: SelectProps['onFocus'] = ({ value, e }) => {
  console.log('handleFocus: ', value, e);
};
const handleEnter: SelectProps['onEnter'] = ({ value, e, inputValue }) => {
  console.log('handleEnter: ', value, e, inputValue);
};
</script>

### 你建议的方案是什么

 可过滤的选择器,通过输入关键词筛选后的结果可否可支持多选，而不是选一个之后又需要重新输入

**Comment by uyarn** [comment]
配置下`reserveKeyword`即可

**Comment by uyarn** [comment]
<img width="738" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/26377630/ea7e093d-5ec1-4681-bb24-dad80235f5ec">
