### ISSUE TITLE
[Statistic 统计数值] 如何修改组件的大小,

### ISSUE THREAD

**Issue by revilhui** [Tencent/tdesign-vue-next#4280]
### 这个功能解决了什么问题

默认的是用字体属性--td-font-size-headline-medium来控制，但这个变量只有统计数值使用么？

### 你建议的方案是什么

能否提供一个属性用来控制数值的大小

**Comment by uyarn** [comment]
可以只针对statistic配置这个变量的大小
.t-statistic { 
--td-font-size-headline-medium: xx 
}
