### ISSUE TITLE
[Select] 键盘上下键选中选项通过 onEnter 事件获取的context.value 错误

### ISSUE THREAD

**Issue by wilonjiang** [Tencent/tdesign-vue-next#4283]
### tdesign-vue-next 版本

1.9.6

### 重现链接

https://stackblitz.com/edit/od19pp?file=src%2Fdemo.vue

### 重现步骤

Select 组件展开下拉时,使用键盘通过上下键选择选项后, 按回车键触发 onEnter 事件获取的 context.value 为上一次选择的结果

### 期望结果

Select 组件展开下拉时,使用键盘通过上下键选择选项后, 按回车键触发 onEnter 事件获取的 context.value 应该为本次选择的结果

### 实际结果

Select 组件展开下拉时,使用键盘通过上下键选择选项后, 按回车键触发 onEnter 事件获取的 context.value 为上一次选择的结果

### 框架版本

vue3.2.47

**Comment by uyarn** [comment]
fixed 1.9.7
