### ISSUE TITLE
[Tag] Always keep the `span` element outside of `tagContent` to support more flexible custom design

### ISSUE THREAD

**Issue by zhangpaopao0609** [Tencent/tdesign-vue-next#4289]
### Details

As the title shows, I want to always keep the `span` element outside of `tagContent` to support more flexible custom design.

Now, the `src/tag/tag.tsx` code is as follows. 

You can see that `tagContent` will be wrapped by `span` only when `maxWidth` is not `undefined`. Otherwise, no one can style it, such as adding a background color only to the `tagContent` area or setting a color only for `tagContent`. **So I suggest that regardless of whether `maxWidth` is `undefined`, we still add `span`**

```jsx
      return (
        <div class={tagClass.value} style={tagStyle.value} onClick={handleClick}>
          {icon}
          {props.maxWidth
            ? (
              <span class={{ [`${COMPONENT_NAME.value}--text`]: props.maxWidth }} title={titleAttribute}>
                {tagContent}
              </span>
              )
            : (
                tagContent
              )}
          {!props.disabled && closeIcon}
        </div>
      );
```

**Comment by uyarn** [comment]
fixed 1.9.7
