### ISSUE TITLE
[DatePicker] 选择器模式mode属性，动态改变值时选择器面板中 Header 组件显示错误

### ISSUE THREAD

**Issue by wilonjiang** [Tencent/tdesign-vue-next#4291]
### tdesign-vue-next 版本

1.9.6

### 重现链接

[demo.vue](https://stackblitz.com/edit/od19pp-mckexv?file=src%2Fdemo.vue)

### 重现步骤

1. 日期选择器绑定mode属性，动态改变 mode 变量值 = year/quarter/month/week/date

2. 日期选择器面板中 Header 组件显示错误

3. 日期选择器面板中年份选择器下拉内容显示错误

### 期望结果

日期选择器绑定mode属性，动态改变 mode 变量值 = year/quarter/month/week/date
1.  日期选择器面板中年份选择器下拉内容显示正常
2. 日期选择器面板中 Header 组件显示随 mode 改变

### 实际结果

日期选择器绑定mode属性，动态改变 mode 变量值 = year/quarter/month/week/date

1. 日期选择器面板中 Header 组件显示错误
date 模式下有月份和年份
切换到 month 模式下任然显示月份和年份（应该只有年份）

2. 日期选择器面板中年份选择器下拉内容显示错误
 比如 year 模式下会显示1990-2000，2000-2010，2010-2020；其他默认下显示  1990,1991,1992
切换模式后会显示1990-2000，2000-2010， 2011,2012,2013 混合options

**Comment by uyarn** [comment]
fixed 1.9.7
