### ISSUE TITLE
[Menu] 收起时支持显示顶级菜单

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next#4299]
### 这个功能解决了什么问题

收起的时候能够清晰知道顶级菜单是哪个

### 你建议的方案是什么

![image](https://github.com/Tencent/tdesign-vue-next/assets/8606851/ff0f6a8b-3f14-4618-afb6-8a413a8bcbd8)
![image](https://github.com/Tencent/tdesign-vue-next/assets/8606851/fbc353c1-84e6-4634-8aa8-cf97d6c95f5f)

**Comment by uyarn** [comment]
和设计确认了下 不会增加这种样式
