### ISSUE TITLE
[t-enhanced-table] 展开或收缩节点报错：`rowKey` could be wrong, can not get rowValue from `data` by `rowKey`

### ISSUE THREAD

**Issue by yuqiuwen** [Tencent/tdesign-vue-next#4304]
### tdesign-vue-next 版本

1.9.6

### 重现步骤

<t-enhanced-table
      ref="tableRef"
      v-model:expandedTreeNodes="data"
      row-key="id"
      table-layout="fixed"
      :data="data"
      :columns="MenuCols"
      :loading="loading"
      :selected-row-keys="selectedRowKeys"
      :tree="{ indent: 12, childrenKey: 'children' }"
      @select-change="rehandleSelectChange"
      table-content-width="max(100%, 350px)"
      max-height="calc(100vh - 300px)"
    >

**Comment by uyarn** [comment]
看下data的配置 报错看来是rowKey的问题呢

**Comment by yuqiuwen** [comment]
> 看下data的配置 报错看来是rowKey的问题呢

rowkey设为id，id是主键不可能重复，我直接写死了data，还是会报错：
```ts
const res = [
      {
        id: 4,
        name: '首页',
        parent_id: 0,
        children: [
          {
            id: 5,
            name: '二级菜单',
            parent_id: 4,
            children: [
              {
                id: 6,
                name: '三级菜单',
                parent_id: 5,
                children: [],
              },
            ],
          },
        ],
      },
 ]
```
