### ISSUE TITLE
[Table] height 100% 很多问题

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next#4307]
### tdesign-vue-next 版本

1.9.6

### 重现链接

https://stackblitz.com/edit/yp4rlh?file=src%2Fdemo.vue

### 重现步骤

1. 重现链接会出现最后一行border-bottom 丢失的情况
![image](https://github.com/Tencent/tdesign-vue-next/assets/8606851/9f8a07c1-ec30-4fbb-92ef-7e6473f2a4db)
2. empty 没有撑满高度需要居中
![image](https://github.com/Tencent/tdesign-vue-next/assets/8606851/ba32714c-2b00-4c8e-b913-227e74ff9cfa)

3. 放 TDesign Starter 内 height: 100% 没有起作用是什么原因？重现链接又可以撑满哪里影响了？
![bef45a3095717d309ab0981fe706d11](https://github.com/Tencent/tdesign-vue-next/assets/8606851/79bca5bc-0604-420d-bb97-d4bf8b85cb91)

### 期望结果

不要有问题

### 实际结果

有问题

**Comment by xiaojueshi** [comment]
建议是用 table props 的 height 或 maxHeight 属性。
<img width="980" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/81723324/993c2076-8014-4b5f-9c2a-79a6ed327da4">

**Comment by Jiachang-Cai** [comment]
> 建议是用 table props 的 height 或 maxHeight 属性。 <img alt="image" width="980" src="https://private-user-images.githubusercontent.com/81723324/343984276-993c2076-8014-4b5f-9c2a-79a6ed327da4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNjI5NTYsIm5iZiI6MTcyMDE2MjY1NiwicGF0aCI6Ii84MTcyMzMyNC8zNDM5ODQyNzYtOTkzYzIwNzYtODAxNC00YjVmLTljMmEtNzlhNmVkMzI3ZGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA2NTczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0YWQyZWFiNWVhMmUzNmExMDkwNDlmZDI4NTZlMWI0Y2MwMWM1ZDcxZThkZWMyNGQ1MDc1NzQzZmY2NDI2YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qy21TC4FhzIfAt0sNqJpEpZclMg3O5nAqElUCqY3p_s">

帮忙重新看一下
