### ISSUE TITLE
[Tabs] Dialog中Tabs导航滑块定位有问题

### ISSUE THREAD

**Issue by ls-v** [Tencent/tdesign-vue-next#4309]
### tdesign-vue-next 版本

1.96

### 重现链接

https://stackblitz.com/edit/95sq2g?file=src%2Fdemo.vue

### 补充说明

<img width="715" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/15193414/03a5dc16-f937-49b7-a8e4-c90b8fee473e">

**Comment by Cat1007** [comment]
+1
