### ISSUE TITLE
[Watermark] Props removable的文档说明表述不准确

### ISSUE THREAD

**Issue by Axxandrush** [Tencent/tdesign-vue-next#4333]
### tdesign-vue-next 版本

1.9.6

### 重现链接

https://tdesign.tencent.com/vue-next/components/watermark?tab=api#watermark-props

### 重现步骤

removable 的默认值为true, 但是它的说明"水印是否可被删除，默认会开启水印节点防删"是不准确的，可删除后半段

### 期望结果

无

### 实际结果

无

### 补充说明

需要更新文档

**Comment by uyarn** [comment]
谢谢反馈 你可以直接提PR修改下
