### ISSUE TITLE
[TreeSelect] 现版本给父级增加disabled: true属性会给子集也禁用不给选用

### ISSUE THREAD

**Issue by 879291903** [Tencent/tdesign-vue-next#4345]
### tdesign-vue-next 版本

1.7.1 版本以上都有

### 重现步骤

现版本给父级增加disabled: true属性会给子集也禁用不给选用
<img width="495" alt="90c62ab83d070b1fa98af326584a12c" src="https://github.com/Tencent/tdesign-vue-next/assets/51746450/ee4944bb-b142-4423-a3a3-ddab58dd94ea">
这是之前的版本
![image](https://github.com/Tencent/tdesign-vue-next/assets/51746450/62327e8d-91b9-4c78-b5b4-ac90e2f0dc2c)

### 期望结果

给父级增加disabled: true 不影响子集选用
或新增一个属性让树选择框只能选中子集父级不给选中

### 系统版本

Windows10

**Comment by uyarn** [comment]
https://stackblitz.com/edit/hsdwph-jajttj?file=package.json,src%2Fdemo.vue 
配置下checkStrictly 即可 这个应该是这个默认配置很久了 🤔 我们改下DEMO吧 问了很多次
