### ISSUE TITLE
[Dialog] 点击对话框会提示inject() can only be used inside setup() or functional components. 

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#435]
### tdesign-vue-next 版本

0.10.0

### 重现链接
https://tdesign.tencent.com/vue-next/components/dialog?tab=demo
直接演示版网址就会有此问题

### 重现步骤

![image](https://user-images.githubusercontent.com/20961979/158121913-17447ec0-beec-40fe-9ecd-b271b429c735.png)

### 期望结果

没有此警告

### 实际结果

点击弹框就会弹出警告

**Comment by uyarn** [comment]
@pengYYYYY 反馈这个问题还没修复 看看是不是dialog本身有其他地方也用了class的hooks..
