### ISSUE TITLE
[t-Statistic] 建议可选不显示千分位

### ISSUE THREAD

**Issue by vikyd** [Tencent/tdesign-vue-next#4367]
### tdesign-vue-next 版本

1.9.7

**Comment by uyarn** [comment]
什么意思？不传不就不展示了？

**Comment by liweijie0812** [comment]
没看文档，文档有说明如何不显示
<img width="862" alt="image" src="https://github.com/Tencent/tdesign-vue-next/assets/10710889/38e56167-2d7c-4332-95e9-ead7db259a34">

**Comment by vikyd** [comment]
确实有此功能，但当时在页面搜索【千】，以为会有【千分位】的字样，没想到是【进位分隔符】。

建议在文档中出现类似【千分位分隔符】字样。
