### ISSUE TITLE
t-select滚动事件加载选项时当条目字符串过长时会触发search事件

### ISSUE THREAD

**Issue by ouyanghui100** [Tencent/tdesign-vue-next#4373]
### tdesign-vue-next 版本

1.9.5

### 重现步骤

![企业微信截图_1720095197592](https://github.com/Tencent/tdesign-vue-next/assets/67298401/72b4f6eb-c74b-449b-ab19-dfc0edc6d77a)
![企业微信截图_17200952198630](https://github.com/Tencent/tdesign-vue-next/assets/67298401/2e6d3369-9e7b-43b9-a99d-97aee365ea3b)
![企业微信截图_17200952306256](https://github.com/Tencent/tdesign-vue-next/assets/67298401/9db1245a-9d18-4d0a-825d-2c1293a90b06)
我的组件是这样的，当我没更改红框代码时，选择较长的label会再次触发search造成异常

### 期望结果

选择时不会搜索

### 实际结果

![Uploading 屏幕截图 2024-07-04 202049.png…]()

**Comment by uyarn** [comment]
麻烦点击select的某个示例的右下角的图标 给个stackblitz  截图比较难复现和排查问题

**Comment by ouyanghui100** [comment]
不好意思，是组里的人把input的长度限制了30，实在不好意思。
