### ISSUE TITLE
官网VUE NEXT WEB  1.97 版本一下的文档都 无法查看 

### ISSUE THREAD

**Issue by shiyiyuedexiaozhang** [Tencent/tdesign-vue-next#4379]
### tdesign-vue-next 版本

1.3.2

**Comment by uyarn** [comment]
旧版本依赖surge服务部署 这个我们暂时没有其他备用站点 可能国内访问会慢一些。
如果没有梯子 可以把这个仓库clone下 然后切换到1.3.2版本查看
