### ISSUE TITLE
[TTable] columns类型报错

### ISSUE THREAD

**Issue by WiseSheep1** [Tencent/tdesign-vue-next#4395]
### tdesign-vue-next 版本

1.9.6

### 重现步骤
![image](https://github.com/Tencent/tdesign-vue-next/assets/96505419/d99ff2ee-0757-483a-9c33-b889abc3b7e4)

![image](https://github.com/Tencent/tdesign-vue-next/assets/96505419/c3291719-2dca-411c-9169-885f50b41fa6)

### 期望结果

支持传入自定义类型不报错

**Comment by uyarn** [comment]
TableProps['columns'] 就可以了 站点有示例 打开Table任意一个DEMO 切换到TypeScript的tab

**Comment by WiseSheep1** [comment]
但是这个就没有类型提示的东西了
