### ISSUE TITLE
[table] 为什么table checkbox勾选上的时候，然后点击表格任意内容，按下ctrl+c就取消选中了

### ISSUE THREAD

**Issue by 2497881506** [Tencent/tdesign-vue-next#4397]
### tdesign-vue-next 版本

latest

**Comment by XBIsland** [comment]
```HTML
<!-- 设置 active-row-type="single" 行高亮后，支持键盘批量操作，
      可尝试使用 Shift/Space/ArrowUp/ArrowDown/KeyC/KeyA/KeyL 等键盘操作选中和取消选择，
      其中键 KeyC 表示 Clear，清空高亮，清空全选
      其中键 KeyA/KeyL 表示全选，全部高亮
-->
```
触发了 `C` 操作

**Comment by 2497881506** [comment]
我怎么可以禁用这个快捷键操作吗

**Comment by ruiyong0416** [comment]
> 我怎么可以禁用这个快捷键操作吗

可以使用非受控参数，然后在onSelecChange事件里，判断第二个参数的currentRowKey属性，不存在的时候return
function selectFunc(val, ctx) {
  if (!ctx.currentRowKey) return

  selectedRowKeys.value = val
  selectedRow.value = ctx.selectedRowData
}

也可以禁用hover和keyboardRowHover
