### ISSUE TITLE
[Dialog] 按钮的属性设置为null报类型错误

### ISSUE THREAD

**Issue by WiseSheep1** [Tencent/tdesign-vue-next#4400]
### tdesign-vue-next 版本

1.9.7

### 重现步骤

![image](https://github.com/user-attachments/assets/065315bb-365a-4aa8-8632-7afecfed07ae)

**Comment by chouchouji** [comment]
I would like to submit a pr to solve this issue. Can you assign it to me?

**Comment by uyarn** [comment]
@WiseSheep1 可以提供下环境吗 我这里没有复现 还有另一个issue也是类似的问题 
<img width="797" alt="image" src="https://github.com/user-attachments/assets/637a1c94-1a05-4bc3-91d1-9d61129feebb">
