### ISSUE TITLE
[Table] reserve-selected-row-on-paginate="false" 时候 表格表头的全选被禁用了

### ISSUE THREAD

**Issue by Klayt11** [Tencent/tdesign-vue-next#4403]
### tdesign-vue-next 版本

^1.9.7

### 重现步骤

reserve-selected-row-on-paginate="false" 时候 表格表头的全选被禁用了

### 期望结果

reserve-selected-row-on-paginate="false" 时，应该只是不跨页选中吧

### 实际结果

全选被禁用

**Comment by ZhuYuRan001** [comment]
我也遇到了这个问题，但是看到之前有相关的pr，还没有被修复吗？

**Comment by uyarn** [comment]
fixed 1.10.4, thanks for @ZhuYuRan001
