### ISSUE TITLE
[t-cascader] 透传属性popupProps中的onScroll，onScrollToBottom，onVisibleChange等事件无法触发

### ISSUE THREAD

**Issue by 742087271** [Tencent/tdesign-vue-next#4404]
### tdesign-vue-next 版本

1.9.4

### 重现步骤

<t-cascader
							filterable
							ref="cascaderRef"
							multiple
							:popupProps="{
							overlayInnerClassName: 'custom',
							onScroll: loadMore,
							onScrollToBottom: loadMore,
							}"
							:showAllLevels="false"
							v-model="value"
							:options="options"
							@change="handleChange"
							clearable
							:load="load"
						>
						</t-cascader>

### 期望结果

正确触发事件

### 框架版本

3.2.47

### 补充说明

希望调用onScrollToBottom事件去加载分页数据

**Comment by uyarn** [comment]
你滚动的是哪个位置 这些事件是整个Popup本身 不是某个cascader的panel

**Comment by 742087271** [comment]
级联面板的选项，t-select都是有效的
&nbsp;


你还要幼稚多久→_→
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wū ***@***.***&gt;; 
发送时间: 2024年7月15日(星期一) 下午3:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tdesign-vue-next] [t-cascader] 透传属性popupProps中的onScroll，onScrollToBottom，onVisibleChange等事件无法触发 (Issue #4404)














 
你滚动的是哪个位置 这些事件是整个Popup本身 不是某个cascader的panel

**Comment by uyarn** [comment]
两个地方不太一样，select滚动的就是Popup本身，cascader的每个面板实际有自己的滚动条，所以popup的无法监听到。

**Comment by 742087271** [comment]
好吧，请问这里要实现监听滚动有更好的办法吗

&nbsp;


你还要幼稚多久→_→
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wū ***@***.***&gt;; 
发送时间: 2024年7月15日(星期一) 下午5:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tencent/tdesign-vue-next] [t-cascader] 透传属性popupProps中的onScroll，onScrollToBottom，onVisibleChange等事件无法触发 (Issue #4404)














 
两个地方不太一样，select滚动的就是Popup本身，cascader的每个面板实际有自己的滚动条，所以popup的无法监听到。

**Comment by uyarn** [comment]
> 好吧，请问这里要实现监听滚动有更好的办法吗 &nbsp; 你还要幼稚多久→_→ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wū ***@***.***&gt;; 发送时间: 2024年7月15日(星期一) 下午5:03 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Tencent/tdesign-vue-next] [t-cascader] 透传属性popupProps中的onScroll，onScrollToBottom，onVisibleChange等事件无法触发 (Issue #4404) 两个地方不太一样，select滚动的就是Popup本身，cascader的每个面板实际有自己的滚动条，所以popup的无法监听到。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

目前需要自己 query 到具体的那个面板来增加事件监听哈
