### ISSUE TITLE
[Upload] requestMethod如何设置上传进度

### ISSUE THREAD

**Issue by HouEngineer** [Tencent/tdesign-vue-next#4409]
### 这个功能解决了什么问题

requestMethod不支持进度问题

### 你建议的方案是什么

requestMethod支持进度

**Comment by w872730491w** [comment]
同问

**Comment by w872730491w** [comment]
@HouEngineer https://tdesign.tencent.com/vue-next/components/upload#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%B8%8A%E4%BC%A0%E6%96%B9%E6%B3%95 文档更新了如何设置上传进度
