### ISSUE TITLE
组件自定义css class为什么不在wrap层

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#441]
### tdesign-vue-next 版本

0.10.1

### 重现步骤

```
<t-input class="font-medium text-gray-900 project-name" v-model="project.name" placeholder="空白项目" />
```

渲染结果：
![image](https://user-images.githubusercontent.com/1797302/158351706-bef957c5-192f-465e-bd0f-9442993086c7.png)

### 期望结果

project-name 应该在t-input__wrap层级，否则重现样式不方便。比如：

.project-name {
    width:  xxxx
}

### 实际结果

t-input__wrap 的 width 没变，布局不对

**Comment by pengYYYYY** [comment]
这边是因为之前组件只有在有`status`的情况下才存在 `t-input__wrap`，后面为了统一 `dom` 结构（为解决拥有 `status` 的时候的 `foucs` 问题），统一存在 `t-input__wrap`，并且保持原有的外部 `class` 传入到`t-input`节点不变。
