### ISSUE TITLE
[Link] prefixIcon、suffixIcon 没有对齐文本

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next#4416]
### tdesign-vue-next 版本

1.9.7

### 重现链接

https://stackblitz.com/edit/s56ym6?file=src%2Fdemo.vue

### 重现步骤

button的icon slot 可以对齐 纯图标的情况下
![image](https://github.com/user-attachments/assets/45eee747-d717-489a-a714-d745b607bc35)

### 期望结果

对齐

### 实际结果

未对齐

**Comment by uyarn** [comment]
link 本身没有高度 这个自己使用对齐就可以
