### ISSUE TITLE
[Dropdown] panelTopContent、panelBottomContent没有效果

### ISSUE THREAD

**Issue by gl4523** [Tencent/tdesign-vue-next#4418]
### tdesign-vue-next 版本

1.9.7

### 期望结果

panelTopContent能正确渲染出效果

### 实际结果

只有dropdown的插槽会渲染出来

### 框架版本

3.2.47

**Comment by uyarn** [comment]
还没发布，可以先用下 1.9.8-alpha.1的版本，下周的正式版本会带上 https://stackblitz.com/edit/kugtkb-c3myeu?file=package.json,src%2Fdemo.vue

**Comment by uyarn** [comment]
1.9.8 published
