### ISSUE TITLE
[树形列表] 树形列表的树形等级容易混淆，样式建议优化

### ISSUE THREAD

**Issue by Alien-Wangzijian** [Tencent/tdesign-vue-next#4423]
### 这个功能解决了什么问题

解决了在树形列表展示情况下，树形等级分明，可分辨出等级之间的区别，同时层级较多之后，可以展示的更完全
![image](https://github.com/user-attachments/assets/c8b31569-a0f5-4377-8b31-fcdcdbd03af6)
![image](https://github.com/user-attachments/assets/1830a9d9-ec71-4445-b0ca-4840701655de)

### 你建议的方案是什么

我建议将树形整体的展开收起控制放到第一列，并优化父子级之间的区分，避免混淆，样式建议优化一下，树形也算是较多的列表使用

**Comment by mustars** [comment]
官网API - TableTreeConfig配置。treeNodeColumnIndex：树结点在第几列渲染，默认为第一列；indent：树结点缩进距离，单位：px。
