### ISSUE TITLE
Collapse 折叠面板想让内容向左边靠齐

### ISSUE THREAD

**Issue by swscm** [Tencent/tdesign-vue-next#4425]
![QQ图片20240723103201](https://github.com/user-attachments/assets/cc202650-4860-4b8b-8cc1-8fb22cba88dc)
使用Collapse 折叠面板时，能不能设置下面内容部分向左边靠齐，因为这样浪费空间，想找t-collapse-panel_body改一下，可是找不到css文件在哪。麻烦指点一下。我使用的是vscode，vue next的版本是1.9.7。

**Comment by uyarn** [comment]
参考 https://stackblitz.com/edit/89vmoz-wcy4oj?file=package.json,src%2Fdemo.vue
