### ISSUE TITLE
[DateRangePicker] format="YYYY-MM-DD HH:mm:ss" 本月结束时间没有加23:59:59

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next#4427]
### tdesign-vue-next 版本

1.9.7

### 重现链接

https://stackblitz.com/edit/hulgav?file=src%2Fdemo.vue

### 重现步骤

![image](https://github.com/user-attachments/assets/8609937d-530d-46dc-b10f-50e1349df184)
左侧本月的任何一个结束时间选择都不会加23:59:59
但是右侧时间又加了
![image](https://github.com/user-attachments/assets/6b99ea09-e434-4e82-943d-2ea9c68282b1)

### 期望结果

结束时间都加23:59:59

### 实际结果

没有加

**Comment by uyarn** [comment]
fixed 1.10.2
