### ISSUE TITLE
[table] 表格改变每页行数时，@page-change事件参数不正确

### ISSUE THREAD

**Issue by JohnnyZhangQiao** [Tencent/tdesign-vue-next#4430]
### tdesign-vue-next 版本

最新版本

### 重现链接

[重现链接](https://stackblitz.com/edit/vitejs-vite-f5ksmh?file=package.json,src%2FApp.vue,vite.config.js,src%2Fmain.js&terminal=dev)

### 重现步骤

当前共100条数据，每页20条分5页显示，先显示最后1页，目前输出参数没问题
<img width="882" alt="image" src="https://github.com/user-attachments/assets/efdee762-1f1b-4e35-8acb-cc7c0f8f4a7d">

此时把每页显示数量改成50条，触发@page-change，但输出参数的 pageSize 依旧是20
<img width="776" alt="image" src="https://github.com/user-attachments/assets/17287bd2-1e36-4b8f-8cd2-9554cf82d4a8">
<img width="898" alt="image" src="https://github.com/user-attachments/assets/79807bb6-38e3-45aa-aa8a-f2e664ce57f4">

**Comment by 1379255913** [comment]
认领
