### ISSUE TITLE
才能把这t-space两边的空白去掉

### ISSUE THREAD

**Issue by swscm** [Tencent/tdesign-vue-next#4431]
![QQ图片20240724110133](https://github.com/user-attachments/assets/4a441d23-046d-42e1-81aa-420536a8cd6d)
要怎么才能把这两边红框部分的空白去掉。我用的是window10，vscode，vue next1.9.7版本。

**Comment by uyarn** [comment]
覆盖样式即可 学习下基础的CSS知识（包括CSS优先级计算）和Chrome的调试功能 学会查找你需要修改的样式（padding) 具体是哪个节点上的
