### ISSUE TITLE
为form和buttom添加id 和 form

### ISSUE THREAD

**Issue by renjiali** [Tencent/tdesign-vue-next#4448]
### 这个功能解决了什么问题

表单在Dialog 等组件时，提交按钮在form表单之外。应该使用原生能力去触发提交事件，而不是通过ref

### 你建议的方案是什么

![image](https://github.com/user-attachments/assets/dcc2c35e-9d3f-4fb6-a25d-4ab67af91ed8)
目前是可以触发提交事件，应为他们的ts类型加上id 和form 字段

**Comment by renjiali** [comment]
![image](https://github.com/user-attachments/assets/ebc9f40c-9bd6-465a-abbe-244f6f458aea)
这样写看起来太不方便了

**Comment by uyarn** [comment]
supported 1.10.0
