### ISSUE TITLE
[Button] 浅色模式下，theme=default, ghost 的按钮颜色不正确

### ISSUE THREAD

**Issue by dntc** [Tencent/tdesign-vue-next#4449]
### tdesign-vue-next 版本

1.9.8

### 重现步骤

浅色模式下，theme=default, ghost 的按钮颜色是白色，和背景一致，导致无法正常显示按钮

![微信截图_20240730095528](https://github.com/user-attachments/assets/69790312-8d15-4ab2-80a6-b64c0ac1ca2f)

**Comment by RADWIMPS426** [comment]
感谢你的意见～考虑到 ghost 具有细长、无边框的轮廓、透明填充，与背景融为一体等特殊属性，我们会把 ghost 从当前模块移出并作为特殊示例来展示，以确保更好的展示效果。
