### ISSUE TITLE
[cascader] cascader 组件如果二级面板值相等的话，会导致错乱 

### ISSUE THREAD

**Issue by ZWkang** [Tencent/tdesign-vue-next#4456]
### tdesign-vue-next 版本

1.9.8

### 重现链接

https://stackblitz.com/edit/hhvy6e

### 重现步骤

点击子面板的时候，会发现错乱情况

### 期望结果

期待值是正常的

### 实际结果

现在的话，交互上点击感觉错乱，值无法选中，切换时候值又选中，比较混乱

**Comment by ZWkang** [comment]
cc @uyarn

**Comment by uyarn** [comment]
value必须是唯一key
