### ISSUE TITLE
[Tree] 直接修改props里面的data属性插入节点，会白屏闪烁

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#446]
### tdesign-vue-next 版本

0.10.1

### 重现链接

https://stackblitz.com/edit/angular-gnk78t-fcehxv?file=src%2Fdemo.vue

### 重现步骤

 ``` <t-tree ref="tree" :data="data" />```

直接修改数据 data.push({label: '节点'})，不调用 tree的api

### 期望结果

tree不要白屏重构

### 实际结果

整个树白屏消失后重构

**Comment by Alsmile** [comment]
直接修改 data 数据也存在相同bug

data[0].label = 'xxx'

**Comment by pengYYYYY** [comment]
tree 目前换了维护者，新的维护者在重构，可能解决时间会长一点
