### ISSUE TITLE
[Tree] 节点激活状态再次点击会取消激活状态不合理

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next#4464]
### tdesign-vue-next 版本

1.9.8

### 重现链接

https://stackblitz.com/edit/naatu3?file=src%2Fdemo.vue

### 重现步骤

![image](https://github.com/user-attachments/assets/765071ce-0a4f-43d9-93aa-ad20b306baf0)

### 期望结果

不取消只有在 activeMultiple 时才可取消

### 实际结果

会取消

**Comment by uyarn** [comment]
一方面不认为这样不合理，如果再次点击不取消，那要取消的行为怎么办？一方面不会改动，这是breaking change;
