### ISSUE TITLE
[Table] 自定义表头

### ISSUE THREAD

**Issue by yangqi0519400** [Tencent/tdesign-vue-next#4468]
官方提供的插槽语法： <template #title-slot-name></template>只能放在模版中写吗？
如果我想在script中的columns，使用title渲染函数返回的元素，比如<t-popup>中使用插槽，<template #content>会报错，请问下这种情况怎么写呢

**Comment by uyarn** [comment]
https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%A4%B4%E7%9A%84%E8%A1%A8%E6%A0%BC 这个示例第二列就是渲染函数返回的，可以参考一下
<img width="963" alt="image" src="https://github.com/user-attachments/assets/563f9c62-50b5-4b76-aa30-12eb4a28d486">

**Comment by yangqi0519400** [comment]
> https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%A4%B4%E7%9A%84%E8%A1%A8%E6%A0%BC 这个示例第二列就是渲染函数返回的，可以参考一下 <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/26377630/355703391-563f9c62-50b5-4b76-aa30-12eb4a28d486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTQyMDksIm5iZiI6MTcyMzAxMzkwOSwicGF0aCI6Ii8yNjM3NzYzMC8zNTU3MDMzOTEtNTYzZjljNjItNTBiNS00Yjc2LWFhMzAtMTJlYjRhMjhkNDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTQ3ZmY3MjQ0NjZiMmJhN2I2OWY4MDFiYWE4ZGIzZTVjMjA2ODU5Zjk4YjU5MTIwNjI1OWU1MDQxZWM0MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bcVf4jT8lh1gUfrMn_H6FImdfn3CspGrIUZtwbRtBIE">


这个示例我看到过，也是按照这种写法写的，现在的问题是t-popup组件中的content是需要自定义样式，如图，所以我想使用content的插槽形式<template #content></template>，但是在script中这样写会报错
![微信图片_20240807155313](https://github.com/user-attachments/assets/912960a5-a917-4604-9f98-b810f3b37454)

**Comment by yangqi0519400** [comment]
> > https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%A1%A8%E5%A4%B4%E7%9A%84%E8%A1%A8%E6%A0%BC 这个示例第二列就是渲染函数返回的，可以参考一下 <img alt="image" width="963" src="https://private-user-images.githubusercontent.com/26377630/355703391-563f9c62-50b5-4b76-aa30-12eb4a28d486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMTQyMDksIm5iZiI6MTcyMzAxMzkwOSwicGF0aCI6Ii8yNjM3NzYzMC8zNTU3MDMzOTEtNTYzZjljNjItNTBiNS00Yjc2LWFhMzAtMTJlYjRhMjhkNDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDA2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwNTQ3ZmY3MjQ0NjZiMmJhN2I2OWY4MDFiYWE4ZGIzZTVjMjA2ODU5Zjk4YjU5MTIwNjI1OWU1MDQxZWM0MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bcVf4jT8lh1gUfrMn_H6FImdfn3CspGrIUZtwbRtBIE">
> 
> 这个示例我看到过，也是按照这种写法写的，现在的问题是t-popup组件中的content是需要自定义样式，如图，所以我想使用content的插槽形式<template #content>，但是在script中这样写会报错 ![微信图片_20240807155313](https://private-user-images.githubusercontent.com/48248460/355725412-912960a5-a917-4604-9f98-b810f3b37454.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwOTkwNDQsIm5iZiI6MTcyMzA5ODc0NCwicGF0aCI6Ii80ODI0ODQ2MC8zNTU3MjU0MTItOTEyOTYwYTUtYTkxNy00NjA0LTlmOTgtYjgxMGYzYjM3NDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA2MzIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2OWI4ZjBmOTgyNzMwNDQ3ZGY2YmZiODIwNGNmYzM0YzQ0YzE5NzkzY2ZjNTczY2Y4NTQ0YTlhYzYwNzNlYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cBMjUlNqU7PPqHCskpcC5nSAAWUNA_ENQ0FgjbvcZ7c)


已解决，用的是函数形式返回自定义dom元素作为content的值；
![微信图片_20240808102546](https://github.com/user-attachments/assets/0be42f69-34a3-404e-b20d-6c13d04129cb)
![微信图片_20240808102622](https://github.com/user-attachments/assets/d77fda41-b657-44bd-9c6a-5b34d4cce319)
