### ISSUE TITLE
[Card] 当文本内容为全数字和符号时无法自动换行

### ISSUE THREAD

**Issue by grantting** [Tencent/tdesign-vue-next#4471]
### tdesign-vue-next 版本

1.9.8

### 重现链接

https://jsfiddle.net/vd895s2a/

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-08-17 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by taninsist** [comment]
已认领

**Comment by taninsist** [comment]
你可以使用 word-break: break-all;
<img width="486" alt="image" src="https://github.com/user-attachments/assets/333b0335-f0b5-4c9d-b59b-a61cf5f6034e">
或者 white-space: normal; word-wrap: break-word;
<img width="488" alt="image" src="https://github.com/user-attachments/assets/701c2641-05bc-4bbe-a091-a3fb54d8e032">

但不同的 css 样式，都会丢失一些特性，请自查。
