### ISSUE TITLE
[table] 合并第一列单元格时会导致下一列数据丢失

### ISSUE THREAD

**Issue by liuyanzhou** [Tencent/tdesign-vue-next#448]
### tdesign-vue-next 版本

^0.9.4

### 重现步骤

使用table组件，并合并第一列的单元格

### 期望结果

合并第一列单元格，不丢失任何数据

### 实际结果

合并第一列单元格，丢失了数据

### Node版本

12.22.7

**Comment by liuyanzhou** [comment]
这里修复了吗

**Comment by liuyanzhou** [comment]
@pengYYYYY 这里修复了吗

**Comment by pengYYYYY** [comment]
跟随这个PR #468

**Comment by liuyanzhou** [comment]
0.11.1并没有解决这个bug 
<img width="1455" alt="image" src="https://user-images.githubusercontent.com/50945362/162111909-7d067f4f-33a4-45c1-9f03-d97efcc7c570.png">

**Comment by liuyanzhou** [comment]
<img width="292" alt="image" src="https://user-images.githubusercontent.com/50945362/162111964-430da3da-72b1-4d91-afff-4f74e95e5d5f.png">

**Comment by pengYYYYY** [comment]
0.12.0 已修复
