### ISSUE TITLE
[伸缩框] 可拖拽伸缩框组件

### ISSUE THREAD

**Issue by duhaoranc** [Tencent/tdesign-vue-next#4481]
### 这个功能解决了什么问题

![image](https://github.com/user-attachments/assets/bccb9e4f-54e4-4e48-b15e-cecdf56d995b)
很多场景下是左树右表的情况，树的层级较深时，需要进行拖拽调整数的容器宽度来进行展示

### 你建议的方案是什么

是否可以提供容器、栅格可拖拽属性，或者提供一个新的容器组件

**Comment by uyarn** [comment]
上周开会确认会做这个组件 https://github.com/Tencent/tdesign/issues/220 关注这个issue的进度即可

**Comment by duhaoranc** [comment]
> 上周开会确认会做这个组件 [Tencent/tdesign#220](https://github.com/Tencent/tdesign/issues/220) 关注这个issue的进度即可

好的，谢谢
