### ISSUE TITLE
[table] 如何固定某一列的宽度

### ISSUE THREAD

**Issue by Katarina-W** [Tencent/tdesign-vue-next#4483]
### tdesign-vue-next 版本

latest

### 重现步骤

拉伸table, 使其超出所有列设定的宽度

### 期望结果

最后一列始终固定为设置的宽度

### 实际结果

跟随其他列一起分配多余宽度

**Comment by uyarn** [comment]
是指配置resizable拉伸还是因为所在容器宽度拉伸？

**Comment by Katarina-W** [comment]
> 是指配置resizable拉伸还是因为所在容器宽度拉伸？

配置了列控制器，隐藏部分列之后，最后一列的操作栏会变宽，我希望它固定宽度不变

**Comment by Katarina-W** [comment]
> 是指配置resizable拉伸还是因为所在容器宽度拉伸？

这是我写的示例, 无论我怎么设置, 最右侧操作栏都会被拉伸

https://stackblitz.com/edit/5xetpr?file=src%2Fdemo.vue

**Comment by RSS1102** [comment]
尝试添加 ` table-layout="fixed"` 呢
见 [固定表头/固定行的表格](https://tdesign.tencent.com/vue-next/components/table?tab=demo#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4-%E5%9B%BA%E5%AE%9A%E8%A1%8C%E7%9A%84%E8%A1%A8%E6%A0%BC)
