### ISSUE TITLE
[Cascader 级联选择器 ] 选中值后， 如何获取调用方法获取键和值数据，类似getCheckedNodes

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next#4486]
### 这个功能解决了什么问题

使用 [Cascader 级联选择器 ] 选中值后，提交表单，需要 字段传

	setupAddressProvinceName: '',
	setupAddressProvinceCode: '',

	setupAddressCityName: '',
	setupAddressCityCode: '',

	setupAddressAreaName: '',
	setupAddressAreaCode: '',

但是，我只能拿到 value ，不能拿到 label ，无法拿到数据去提交。
![image](https://github.com/user-attachments/assets/0183537f-b924-4333-bc9a-734c0cc88540)

![eb196ead43fbf89c6ea2b71d369e6a8](https://github.com/user-attachments/assets/e3d4ec1a-cc6c-4931-bd27-4b3925de57f5)

### 你建议的方案是什么

[Cascader 级联选择器 ] 选中值后， 如何获取调用方法获取键和值数据，类似getCheckedNodes

**Comment by uyarn** [comment]
https://stackblitz.com/edit/react-wtydlx-jwbzsh?file=src%2Fdemo.tsx
