### ISSUE TITLE
[TagInput] 能否增加输入已经存在的不重复创建？

### ISSUE THREAD

**Issue by Brokenstrings** [Tencent/tdesign-vue-next#4488]
### 这个功能解决了什么问题

发现输入重复的还是能创建进去，虽然自己也能在保存的时候做去重处理，但是如果组件提供一个配置能在输入已经存在的项目时候能提示或直接不生成

### 你建议的方案是什么

增加一个配置是否开启重复项判断，如果开启重复的时候提示或则不生成

**Comment by uyarn** [comment]
讨论了下 不新增API了 你可以自己受控实现 参考这个DEMO https://stackblitz.com/edit/tpwcqt?file=package.json,src%2Fdemo.vue
