### ISSUE TITLE
[form] 打包时报错

### ISSUE THREAD

**Issue by ry0513** [Tencent/tdesign-vue-next#4492]
### tdesign-vue-next 版本

1.9.9

### 重现链接

https://stackblitz.com/edit/vitejs-vite-zdpele?file=src%2FApp.vue

### 重现步骤

使用vite创建了一个vue-ts项目，并引入tdesign-vue-next，修改app.vue 使用 from 组件，使用  FormProps['data']  类型定义，运行 npm run build 打包命令

### 期望结果

希望正常打包

### 实际结果

打包报错
![QQ20240820-120632](https://github.com/user-attachments/assets/216c6ff8-1f00-4476-bf3e-35593ffad980)

### 框架版本

"vue": "^3.4.38"

**Comment by XBIsland** [comment]
`FormProps['data']` 的定义是包含 `undefined` 的，所以检查报错了。

限制 `formData` 可以用 `reactive` 泛型。
```typescript
interface FormData {
  account: string 
}
const formData = reactive<FormData>({
  account: ''
})
```
