### ISSUE TITLE
[DatePicker] 周期选择器回显异常

### ISSUE THREAD

**Issue by ruanlinxin** [Tencent/tdesign-vue-next#4498]
### tdesign-vue-next 版本

1.9.9

### 重现步骤

```js
<template>
  {{ value }}
  <t-date-picker v-model:value="value" mode="week" />
</template>

<script setup lang="tsx">
const value = ref();
</script>
```
1. 打开选择器并选择周期 （value用来展示值）
2. 再次打开选择器（此时显示变为xxxx-1周）
3. 不做选择关闭选择器（此时显示依旧为xxxx-1周）

### 期望结果

第二步以及第三步时应该展示正确的周次

### 实际结果

![image](https://github.com/user-attachments/assets/e1f62cca-5103-474a-8328-961026942c32)

### 框架版本

Vue(^3.2.31)

**Comment by XBIsland** [comment]
没有复现到，可以给个 stackblitz 的在线 demo 看看。

**Comment by uyarn** [comment]
https://stackblitz.com/edit/vmq5ds-muax8s?file=package.json,src%2Fdemo.vue 在这里没有复现描述的问题

**Comment by uyarn** [comment]
如果有问题麻烦再打开
