### ISSUE TITLE
t-input-number 设置小数位数时用户输入数据显示异常

### ISSUE THREAD

**Issue by 52Hertz-1** [Tencent/tdesign-vue-next#4499]
### tdesign-vue-next 版本

lastest

### 重现链接
官网示例中即可复现

### 重现步骤

decimal-places 设置为 2时，输入 6.666 输入框的值变为 6.67，如果用户一直输入小数，并且值大于 5 则值反复四舍五入

例如小明输入 6.666 ， 输出为 6.67
输入 6.6666 输出为 6.68
输入 6.66666 输出为 6.69

原因： formatUnCompleteNumber 中格式化非大数的数使用的是 tofixed 导致数据四舍五入，输入框数据异常

### 期望结果

输入 6.666，应为 6.66，多余一位被截去而不是四舍五入

### 实际结果

6.67

**Comment by uyarn** [comment]
谢谢反馈 @52Hertz-1 我们会扩展这个API支持你的这个反馈

**Comment by zhangpaopao0609** [comment]
将按照如下的方式来进行支持：
`decimalPlaces` 接受 `number | { enableRound: boolean, decimalPlaces: number }` 
其中 `enableRound` 表示是否开启四舍五入

**Comment by uyarn** [comment]
published 1.10.0

**Comment by ouyanghui100** [comment]
官方的四舍五入好像有些问题，示例中的小数5有时候不进位有时候进一次，大于5倒是可以一直进位。
希望官方可以一起修复。

**Comment by uyarn** [comment]
> 官方的四舍五入好像有些问题，示例中的小数5有时候不进位有时候进一次，大于5倒是可以一直进位。 希望官方可以一起修复。

麻烦提供下复现示例

**Comment by ouyanghui100** [comment]
![image](https://github.com/user-attachments/assets/10accc10-722d-4af2-853a-72679c9afdef)
是的，这里输入5并不会一直进位（可能会，可能不会，没看逻辑）

**Comment by ouyanghui100** [comment]
![image](https://github.com/user-attachments/assets/0c6f973d-5ba8-4a26-bac2-895a8456ff76)

**Comment by ouyanghui100** [comment]
> ![image](https://private-user-images.githubusercontent.com/67298401/381498791-0c6f973d-5ba8-4a26-bac2-895a8456ff76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODM5MjEsIm5iZiI6MTczMDI4MzYyMSwicGF0aCI6Ii82NzI5ODQwMS8zODE0OTg3OTEtMGM2Zjk3M2QtNWJhOC00YTI2LWJhYzItODk1YTg0NTZmZjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMwVDEwMjAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjZTVmYTRkNjEzN2M4ZGUyYWI1Mzc5YjY5MGUwMmM2ZjYzZWRkM2U3NmZkYTJlZjY0MmU1NGMzYzMxNjYzZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Lmv657shvbvoVJq6_kJShTIHp71WsjNbO7GcQ4kTPxw)

如果是5的话则有时候不进位

**Comment by Lnncoco** [comment]
希望在文档里也提一下，目前如果不看类型定义或者特意搜，注意不到这个功能
![image](https://github.com/user-attachments/assets/6f8f99ac-44b5-4143-aa7e-19d43910ae02)

**Comment by uyarn** [comment]
> 希望在文档里也提一下会四舍五入，而且可以通过enableRound控制关闭，目前如果不看类型定义或者特意搜，注意不到这个功能 ![image](https://private-user-images.githubusercontent.com/57341815/398498575-6f8f99ac-44b5-4143-aa7e-19d43910ae02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDY4NzMsIm5iZiI6MTczNTEwNjU3MywicGF0aCI6Ii81NzM0MTgxNS8zOTg0OTg1NzUtNmY4Zjk5YWMtNDRiNS00MTQzLWFhN2UtMTlkNDM5MTBhZTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA2MDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMzBmMTdhMGRjNzUzMGNmZTA3YjU0NTE5ZjgyZmY1MTE1MDlkMzU1ZTZhYTI2Y2M5OGVhMDY4N2JjYTZkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VQ_UHskbpfcGDFbjMfOaEBjkgvjw7C5aHi-vq987svo)

好的 很好的建议

**Comment by Lnncoco** [comment]
> > 希望在文档里也提一下会四舍五入，而且可以通过enableRound控制关闭，目前如果不看类型定义或者特意搜，注意不到这个功能 ![image](https://private-user-images.githubusercontent.com/57341815/398498575-6f8f99ac-44b5-4143-aa7e-19d43910ae02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDY4NzMsIm5iZiI6MTczNTEwNjU3MywicGF0aCI6Ii81NzM0MTgxNS8zOTg0OTg1NzUtNmY4Zjk5YWMtNDRiNS00MTQzLWFhN2UtMTlkNDM5MTBhZTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA2MDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlMzBmMTdhMGRjNzUzMGNmZTA3YjU0NTE5ZjgyZmY1MTE1MDlkMzU1ZTZhYTI2Y2M5OGVhMDY4N2JjYTZkNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VQ_UHskbpfcGDFbjMfOaEBjkgvjw7C5aHi-vq987svo)
> 
> 好的 很好的建议

使用这个功能时发现bug，已经提供最小复现示例，有空处理下吗   https://github.com/Tencent/tdesign-vue-next/issues/4866

**Comment by uyarn** [comment]
@Lnncoco 已经有修复的PR
