### ISSUE TITLE
[table] table无法通过键盘方向左右控制滑动table 滚轮

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next#4509]
### 这个功能解决了什么问题

[table] table无法通过键盘方向左右控制滑动table 滚轮
解决使用键盘操作方便查看，通用
![Uploading image.png…]()

### 你建议的方案是什么

期望方向键左右对table控制有效
```[tasklist]
### Tasks
```

**Comment by synctimes163** [comment]
![Uploading image.png…]()

**Comment by synctimes163** [comment]
![image](https://github.com/user-attachments/assets/c770d30a-9b12-42c1-8906-fc092307cc36)

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign-vue-next/issues/4710
