### ISSUE TITLE
[List] 使用 v-if 控制虚拟滚动列表，当v-if修改为false后，控制台会有一个报错

### ISSUE THREAD

**Issue by wwklook** [Tencent/tdesign-vue-next#4511]
### tdesign-vue-next 版本

1.9.9

### 重现链接

https://stackblitz.com/edit/bzjwtw?file=vite.config.js,src%2Fdemo.vue

### 重现步骤

![image](https://github.com/user-attachments/assets/ab4913fc-382e-45ef-9fe6-e49b9c88229b)
![image](https://github.com/user-attachments/assets/f2b47774-fbe0-4e15-a9e2-02c8d22a0ad3)

### 期望结果

dom销毁了应该取消监听或者有空值判断

### 实际结果

报错
TypeError: Cannot set properties of null (setting 'scrollTop')
    at ResizeObserver.refreshVirtualScroll2 (tdesign-vue-next.js?v=6dcd0eb5:16971:33)

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-09-02 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
fixed 1.10.0
