### ISSUE TITLE
【tree树组件】allow-drop属性不生效，无法打印数据

### ISSUE THREAD

**Issue by wangxy23** [Tencent/tdesign-vue-next#4535]
### tdesign-vue-next 版本

1.9.4

### 重现链接

https://stackblitz.com/edit/tvjhnv?file=package.json,src%2Fdemo.vue

### 重现步骤

<template>
  <t-space direction="vertical">
    <t-tree
      :data="items"
      activable
      hover
      transition
      expand-all
      draggable
      :allow-drop="handleAllowDrop"
      @drag-start="handleDragStart"
      @drag-end="handleDragEnd"
      @drag-over="handleDragOver"
      @drag-leave="handleDragLeave"
      @drop="handleDrop"
    />
  </t-space>
</template>

<script setup>
import { ref } from 'vue';
const items = ref([
  {
    value: '1',
    label: '1',
    children: [
      {
        value: '1.1',
        label: '1.1',
        children: [
          {
            value: '1.1.1',
            label: '1.1.1',
            children: [
              {
                value: '1.1.1.1',
                label: '1.1.1.1',
              },
              {
                value: '1.1.1.2',
                label: '1.1.1.2',
              },
            ],
          },
          {
            value: '1.1.2',
            label: '1.1.2',
            children: [
              {
                value: '1.1.2.1',
                label: '1.1.2.1',
              },
              {
                value: '1.1.2.2',
                label: '1.1.2.2',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    value: '2',
    label: '2',
    children: [
      {
        value: '2.1',
        label: '2.1',
      },
      {
        value: '2.2',
        label: '2.2 不允许拖放为 2.2 的子节点',
      },
    ],
  },
]);
const handleDragStart = (ctx) => {
  console.log('handleDragStart', ctx);
};
const handleDragEnd = (ctx) => {
  console.log('handleDragEnd', ctx);
};
const handleDragOver = (ctx) => {
  console.log('handleDragOver', ctx);
};
const handleDragLeave = (ctx) => {
  console.log('handleDragLeave', ctx);
};
const handleDrop = (ctx) => {
  console.log('handleDrop', ctx);
};
const handleAllowDrop = (ctx) => {
  console.log("drag",ctx)
  const { dropNode, dropPosition } = ctx;
  if (dropNode.value === '2.2' && dropPosition === 0) {
    return false;
  }
};
</script>

### 期望结果

让allow-drop生效，在allow-drop中定义的方法中能够获取拖拽的数据

### 实际结果

allow-drop属性不生效，无法限制拖拽调教

### 补充说明

复制一下代码在vue环境中，控制台查看打印出来的数据，没有allow-drop方法中的数据，也不生效
<template>
  <t-space direction="vertical">
    <t-tree
      :data="items"
      activable
      hover
      transition
      expand-all
      draggable
      :allow-drop="handleAllowDrop"
      @drag-start="handleDragStart"
      @drag-end="handleDragEnd"
      @drag-over="handleDragOver"
      @drag-leave="handleDragLeave"
      @drop="handleDrop"
    />
  </t-space>
</template>

<script setup>
import { ref } from 'vue';
const items = ref([
  {
    value: '1',
    label: '1',
    children: [
      {
        value: '1.1',
        label: '1.1',
        children: [
          {
            value: '1.1.1',
            label: '1.1.1',
            children: [
              {
                value: '1.1.1.1',
                label: '1.1.1.1',
              },
              {
                value: '1.1.1.2',
                label: '1.1.1.2',
              },
            ],
          },
          {
            value: '1.1.2',
            label: '1.1.2',
            children: [
              {
                value: '1.1.2.1',
                label: '1.1.2.1',
              },
              {
                value: '1.1.2.2',
                label: '1.1.2.2',
              },
            ],
          },
        ],
      },
    ],
  },
  {
    value: '2',
    label: '2',
    children: [
      {
        value: '2.1',
        label: '2.1',
      },
      {
        value: '2.2',
        label: '2.2 不允许拖放为 2.2 的子节点',
      },
    ],
  },
]);
const handleDragStart = (ctx) => {
  console.log('handleDragStart', ctx);
};
const handleDragEnd = (ctx) => {
  console.log('handleDragEnd', ctx);
};
const handleDragOver = (ctx) => {
  console.log('handleDragOver', ctx);
};
const handleDragLeave = (ctx) => {
  console.log('handleDragLeave', ctx);
};
const handleDrop = (ctx) => {
  console.log('handleDrop', ctx);
};
const handleAllowDrop = (ctx) => {
  console.log("drag",ctx)
  const { dropNode, dropPosition } = ctx;
  if (dropNode.value === '2.2' && dropPosition === 0) {
    return false;
  }
};
</script>

**Comment by uyarn** [comment]
allowDrop is supported in tdesign-vue-next@1.9.7, please upgrade to 1.9.7 to use it
<img width="793" alt="image" src="https://github.com/user-attachments/assets/0459baa8-60aa-4068-ae45-312dea2671aa">
