### ISSUE TITLE
[Select] 远程搜索方向键选择回车确认报错

### ISSUE THREAD

**Issue by daiikaku** [Tencent/tdesign-vue-next#4537]
### tdesign-vue-next 版本

1.9.3

### 重现步骤

1、Select远程搜索后去掉查询条件，是选项变多
2、方向键选择最下面的选项，回车选中

### 期望结果

正常选中

### 实际结果

报错

### 框架版本

Vue(3.5.0)

### 补充说明

数组越界

**Comment by uyarn** [comment]
https://stackblitz.com/edit/xzsmd7?file=package.json,src%2Fdemo.vue 麻烦在这复现下操作呢？ 试了下没有复现这个问题

**Comment by daiikaku** [comment]
> https://stackblitz.com/edit/xzsmd7?file=package.json,src%2Fdemo.vue 麻烦在这复现下操作呢？ 试了下没有复现这个问题

https://stackblitz.com/edit/xzsmd7-yvgfkd?file=package.json,src%2Fdemo.vue
步骤：
1、任意输入内容，下拉框显示1条记录
2、删除输入内容，下拉框显示全部5条记录
3、方向键向下选择最后1条记录，回车确认
4、报错

**Comment by uyarn** [comment]
这个问题在1.9.6之后的版本修复了 可以升级下 https://stackblitz.com/edit/xzsmd7-dnfkpw?file=package.json,package-lock.json
