### ISSUE TITLE
[menu-item] 使用router-link（a标签）渲染to属性

### ISSUE THREAD

**Issue by Nero978** [Tencent/tdesign-vue-next#4542]
### 这个功能解决了什么问题

- 已有的问题：https://github.com/Tencent/tdesign-vue-next/issues/2742

> 可以用href，href类型的会转换成a标签

为什么不将`to`的属性用于`router-link`呢（最终渲染为`a`标签）？使用`div`渲染`menu-item`失去了右键点击-新标签页打开等能力，对于SPA来说，用户就是期望能够控制导航、路由行为的页面打开方式，在某个特定的时候选择使用新标签页打开，而不是配置`target`之后总是以新标签页打开。

如果使用目前已有的`href`属性传递路径，那就完全失去了SPA应有的能力，每次导航浏览器都将重新完整请求一次页面，失去了组件的状态和响应性，页面上的部分icon也需要重新请求一次，视图会发生闪烁，基于vue router和transition实现的路由动画也将失效，这不是纯粹脱裤子放屁么？😅

### 你建议的方案是什么

直接默认将`to`属性用`router-link`实现吧

**Comment by boogie-ben** [comment]
#3057

**Comment by Nero978** [comment]
> #3057

感谢老哥！😀
