### ISSUE TITLE
[Select]  下拉选中数据后，输入框失焦的问题

### ISSUE THREAD

**Issue by tiny-dust** [Tencent/tdesign-vue-next#4554]
### tdesign-vue-next 版本

1.10.0

### 重现链接

https://stackblitz.com/edit/dmvr2n?file=src%2Fdemo.vue

### 重现步骤

1. 选择框，点击展开下拉选项
2. 选中某个数据
3. 输入框失焦，并且没有出发 onBlur事件

### 期望结果

保持聚焦状态、或者触发 onBlur 事件

### 实际结果

输入框失焦，并且没有触发 onBlur 事件

**Comment by uyarn** [comment]
fixed 1.10.2
