### ISSUE TITLE
[Pagination 分页] 点击分页（上一页，下一页）存在bug,返回的当前页码为 NaN

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#456]
### tdesign-vue-next 版本

0.10.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/pagination?tab=demo

### 重现步骤

点击下一页的箭头即可复现

### 期望结果

期望获取当页面的数值

### 实际结果

目前获取到的是NaN

### Node版本

v16.14.1

### 补充说明

https://tdesign.tencent.com/vue-next/components/pagination?tab=demo
示例即可复现bug

**Comment by pengYYYYY** [comment]
#444 已经修复，感谢反馈
