### ISSUE TITLE
[Button] 全局特性配置希望能增加button

### ISSUE THREAD

**Issue by InsHomePgup** [Tencent/tdesign-vue-next#4567]
### 这个功能解决了什么问题

按钮目前默认是主题色的，但是如果一个项目中的大部分按钮都是空白的话，需要每次调用t-button以后配置theme以及variant

### 你建议的方案是什么

添加Button全局配置

**Comment by uyarn** [comment]
讨论了一下，这个问题建议直接封装一下业务常用theme和variant成一个组件，然后直接调用这个二次封装的按钮使用就好，如果支持了button这个配置，那其他组件这个问题也需要支持全局配置，维护成本太高了，抱歉。
