### ISSUE TITLE
[ScrollBar] 需要一个区域滚动！！带滚动条的！

### ISSUE THREAD

**Issue by InsHomePgup** [Tencent/tdesign-vue-next#4570]
### 这个功能解决了什么问题

区域滚动功能，目前还没有区域滚动的组件，可以自定义范围内的滚动，带一个滚动条。

### 你建议的方案是什么

组件！！拜托了

**Comment by uyarn** [comment]
新组件的计划可以参考这个issue，https://github.com/Tencent/tdesign/issues/220，目前如果需要滚动条的样式可以使用
