### ISSUE TITLE
[Popup] 基础弹出层的文本语句混乱

### ISSUE THREAD

**Issue by jiasy1616** [Tencent/tdesign-vue-next#4572]
### tdesign-vue-next 版本

能

### 重现步骤

![image](https://github.com/user-attachments/assets/0e76e8cd-122f-47a3-83fb-294e24ddf377)

### 期望结果

应该是 由浮层内容和触发元素组成

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-09-17 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by novlan1** [comment]
https://github.com/Tencent/tdesign-common/pull/1941
