### ISSUE TITLE
[Pagination 分页] 基础分页 少量页面当中，在选择分页条数的时候，弹出框出现更改，但是页面还是现实当前的每条/页

### ISSUE THREAD

**Issue by JakeLove2018** [Tencent/tdesign-vue-next#458]
### tdesign-vue-next 版本

Vue Next for web

### 重现链接

https://tdesign.tencent.com/vue-next/components/pagination

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/444 已经修复，感谢反馈
