### ISSUE TITLE
[组件名称] 国际化导入俄语报错

### ISSUE THREAD

**Issue by 1537372393** [Tencent/tdesign-vue-next#4591]
### tdesign-vue-next 版本

1.10.1

### 重现步骤

国际化导入俄语报错Failed to resolve import "tdesign-vue-next/es/locale/ru_RU" from "src/views/HomePage.vue". Does the file exist?是没有这个语言包吗？导入英文和中文都没有问题

### 期望结果

可以使用俄语

### 浏览器版本

edge

### Node版本

19

**Comment by uyarn** [comment]
fixed 1.10.2
