### ISSUE TITLE
[ColorPicker 颜色选择器] input-props="{style:{width:'200px'}} 设置inputprops中style的width时，颜色面板的input也同样变宽了

### ISSUE THREAD

**Issue by superextend** [Tencent/tdesign-vue-next#4594]
### tdesign-vue-next 版本

能

### 重现步骤

![QQ图片20240924115256](https://github.com/user-attachments/assets/3229067c-a2ae-4248-af43-25e652334b44)
![Uploading QQ图片20240924115256.png…]()

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-09-27 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
fixed 1.10.2
