### ISSUE TITLE
[Swiper] 指示器颜色没有适配深色主题

### ISSUE THREAD

**Issue by Cat1007** [Tencent/tdesign-vue-next#4598]
### tdesign-vue-next 版本

1.10.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/swiper

### 重现步骤

<img width="551" alt="image" src="https://github.com/user-attachments/assets/86214852-c49a-4114-8960-d89bdd096816">

暗色模式下会不可见

### 期望结果

希望可以使用语义化的css var，适配暗黑模式下的展示

**Comment by uyarn** [comment]
fixed 1.10.2
