### ISSUE TITLE
[TimePicker] 时间区间选择器，开启clearable后，点击清除按钮会报错

### ISSUE THREAD

**Issue by Atom-Sat** [Tencent/tdesign-vue-next#4607]
### tdesign-vue-next 版本

1.10.1

### 重现步骤

![image](https://github.com/user-attachments/assets/9ce4da0e-ad91-42da-a346-293280c32bc0)

### 期望结果

正确清除组件数据

### 实际结果

无法清除并报错

**Comment by Atom-Sat** [comment]
https://tdesign.tencent.com/vue-next/components/time-picker?tab=demo
可通过官方文档复现该问题

**Comment by uyarn** [comment]
fixed 1.10.2
