### ISSUE TITLE
[statistic] 数字部分的字体大小是否给配置调整？

### ISSUE THREAD

**Issue by Brokenstrings** [Tencent/tdesign-vue-next#4609]
### 这个功能解决了什么问题

Statistic 统计数值这个组件挺好用的，就是数字部分字体大小固定的不能调整大小，有时候很难适配现有的UI，能否给个配置去设置字体大小，哪怕给几个固定的值去去选。

### 你建议的方案是什么

希望提供配置去设置字体大小

**Comment by uyarn** [comment]
这个样式覆盖就可以吧？

**Comment by Brokenstrings** [comment]
> 这个样式覆盖就可以吧？
目前就是这么做的，写了几个全局的样式，要用不同字体大小加个class，暂时满足业务需求了

**Comment by uyarn** [comment]
这个暂时不打算再增加其他配置了
