### ISSUE TITLE
InputNumber小数位数配置报错

### ISSUE THREAD

**Issue by itvita** [Tencent/tdesign-vue-next#4616]
### tdesign-vue-next 版本

1.10.1

### 重现步骤

配置:decimalPlaces="2",控制台警告提示
![image](https://github.com/user-attachments/assets/d7881749-d1da-486a-9512-bb6926280086)
实际api要求类型是：Number / Object

### 框架版本

Vue(3.3.13)

**Comment by uyarn** [comment]
等会的版本会携带这个告警修复

**Comment by uyarn** [comment]
fixed 1.10.2
