### ISSUE TITLE
[Cascader 级联选择器] 请处理一下Edge游览器下：标题和二级文字之间相互嵌入的样式问题

### ISSUE THREAD

**Issue by he3393805** [Tencent/tdesign-vue-next#4618]
### tdesign-vue-next 版本

您的框架网站

### 重现链接

https://tdesign.tencent.com/vue-next/components/cascader

### 重现步骤

用win11打开Edge游览器，进入链接后，默认比例100%，就可以看见这个问题了

### 期望结果

修改为不互相嵌入的状态

### 浏览器版本

Microsoft Edge 版本 129.0.2792.52 (正式版本) (64 位)

**Comment by he3393805** [comment]
![image](https://github.com/user-attachments/assets/719c9eb1-7409-4a29-a218-a9db29739c3d)
滑轮向下后：
![image](https://github.com/user-attachments/assets/7c2f820f-ee99-4104-a40a-f54ced2600a2)

**Comment by uyarn** [comment]
duplicate of https://github.com/Tencent/tdesign/issues/535

**Comment by uyarn** [comment]
不用重复提相同的issue，留意原来的issue就可以

**Comment by he3393805** [comment]
之前的那个，忘记写标题了，不好意思哈 :-)

**Comment by uyarn** [comment]
给你修改了 
<img width="776" alt="image" src="https://github.com/user-attachments/assets/92e45066-2962-4289-86cf-35a73b49bd47">
