### ISSUE TITLE
[RadioButton] 填充型按钮样式在使用布尔值时不符合预期的失去了切换动画效果

### ISSUE THREAD

**Issue by SuperManito** [Tencent/tdesign-vue-next#4619]
### tdesign-vue-next 版本

1.10.2

### 重现链接

文档绑定的两个工具都看不了

### 重现步骤

填充型按钮样式在使用布尔值时不符合预期的失去了切换动画效果

**Comment by SuperManito** [comment]
![image](https://github.com/user-attachments/assets/2e2b1958-7ca4-4420-a7aa-6d09c4eab9bd)

**Comment by SuperManito** [comment]
经过调试，定位到问题位于 [group.tsx#L104](https://github.com/Tencent/tdesign-vue-next/blob/8f1adbf93db7c758a61633209278f56b8105fd4f/src/radio/group.tsx#L104)

`innerValue` 即 `value` 的 watch 没有正常触发，除了布尔值还需考虑 `number<0 | 1>`

**Comment by uyarn** [comment]
stackblitz 是正常的，codesandbox刚刚修复了之前需要跳到devbox打开的问题，现在应该也可以了

**Comment by SuperManito** [comment]
> stackblitz 是正常的，codesandbox刚刚修复了之前需要跳到devbox打开的问题，现在应该也可以了

用沙盒复现不出来，但确实在我的项目上出现了，我还调试了一下，可能是是Vue的问题

**Comment by uyarn** [comment]
是Vue 3.4?

**Comment by SuperManito** [comment]
> 是Vue 3.4?

3.5

**Comment by uyarn** [comment]
https://stackblitz.com/edit/pyruco-g8f114?file=package.json,src%2Fdemo.vue 
这个沙盒是3.5的版本 也可以正常触发动画 可以打开看看 还有什么相关信息可以补充吗 你的场景watch innerValue没触发？

**Comment by SuperManito** [comment]
> https://stackblitz.com/edit/pyruco-g8f114?file=package.json,src%2Fdemo.vue 这个沙盒是3.5的版本 也可以正常触发动画 可以打开看看 还有什么相关信息可以补充吗 你的场景watch innerValue没触发？

我又检查了一遍我项目的代码，是我自己写法的问题，有一些巧合的原因使我有了这样的误判，给您添麻烦了，抱歉
