### ISSUE TITLE
recommend vscode extension

### ISSUE THREAD

**Issue by Simon-He95** [Tencent/tdesign-vue-next#4623]
[common-intellisense](https://github.com/common-intellisense/common-intellisense) integrates `tdesign-vue-next`, and can be recommended to tdesign-vue-next users in the documentation. I hope to help more developers have a better development experience

**Comment by wenkeming** [comment]
Actually, VSCode itself supports custom code snippets and can be synchronized across multiple platforms, but it requires some time for yourself. The advantage of this is that it can be defined according to your own habits.
