### ISSUE TITLE
[t-select-input] focus点击input输入框时，输入框之前选中的内容消失

### ISSUE THREAD

**Issue by wangxy23** [Tencent/tdesign-vue-next#4624]
### tdesign-vue-next 版本

1.9.4

### 重现链接

https://stackblitz.com/run?file=package.json,src%2Fdemo.vue

### 重现步骤

先选中一个下拉项，再鼠标focus点击input输入框，输入框的内容消失，显示的是placeholer内容“请选择”

### 期望结果

先选中一个下拉项，再鼠标focus点击input输入框，只让输入框的字体颜色改变，而显示内容依旧是上次所选择的数据

### 实际结果

先选中一个下拉项，再鼠标focus点击input输入框，输入框的内容消失，显示的是placeholer内容“请选择”

**Comment by RSS1102** [comment]
`select-input` 是支持各种自定义需求的 
<img width="996" alt="WeChatWorkScreenshot_58b717d5-64d9-417f-bfc3-2f874aafd6d1" src="https://github.com/user-attachments/assets/20695843-3704-499b-9091-22f9761489b7">

你可以自己实现下placeholder的逻辑，高亮已选中等也是可以根据自己的需求实现的，具体可以参照下面的代码：

https://stackblitz.com/edit/cfxpms-pgsctb?file=package.json,src%2Fdemo.vue
