### ISSUE TITLE
[表格组件] ctrl+c复制表格组件里的文字，表格的多选框的选中状态自动取消了

### ISSUE THREAD

**Issue by ZHOU2014** [Tencent/tdesign-vue-next#4635]
### tdesign-vue-next 版本

1.10.2

### 重现步骤

经过测试，ctrl+c复制表格组件的文字，会触发自定义事件@select-change，参数为空数组，如下图带复选框的表格组件
![image](https://github.com/user-attachments/assets/42510bc1-0e1b-4fba-9131-d7c2400ed138)
选中表格组件的文字
![image](https://github.com/user-attachments/assets/2325be3c-8fb1-4cd1-8358-8604a36836e1)
ctrl+c组合按键，复选框选中的状态就取消了

### 期望结果

ctrl+c不会触发自定义事件@select-change

### 实际结果

ctrl+c触发自定义事件@select-change，参数为空数组

### 框架版本

Vue(3.4.14)

### 浏览器版本

Chrome(92.0.4515.131)

### 系统版本

Win10

### Node版本

v18.14.0

**Comment by uyarn** [comment]
这个确实是按键冲突了 下个版本会修复
