### ISSUE TITLE
[Cascader级联选择器] 希望可以支持只有一个节点不可选

### ISSUE THREAD

**Issue by vlxyli** [Tencent/tdesign-vue-next#464]
### 这个功能解决了什么问题

[Cascader级联选择器] 当前多选的状态，只有一个节点还能选择，希望可以支持只有一个节点不可选
![image](https://user-images.githubusercontent.com/101917922/159108991-477a55c7-efba-4642-a781-51deca4e42bc.png)

### 你建议的方案是什么

希望可以支持只有一个节点不可选

**Comment by pengYYYYY** [comment]
https://stackblitz.com/edit/angular-9qygvw?file=src%2Fdemo.vue 可以这么写
