### ISSUE TITLE
[dock系统配置组件] 如何开启？是否可以自定义功能

### ISSUE THREAD

**Issue by gaozhao7** [Tencent/tdesign-vue-next#4643]
### tdesign-vue-next 版本

1.10.2

### 重现步骤

用官网tdesign-starter-cli搭建的项目，默认   "tdesign-vue-next": "^1.9.9",
登录后系统设置在header中，如图：
![image](https://github.com/user-attachments/assets/c4b1f78c-12ee-4a85-a631-31fd7e07d04f)
与官网上的不一致：
![image](https://github.com/user-attachments/assets/30f5b011-e13c-48ae-9846-22de324cd5de)
升级到     "tdesign-vue-next": "^1.10.2",也不行，请问是需要修改哪里配置才能开启吗？
这个全局设置组件是否可以自定义功能呢？

### 期望结果

能够展示下面这个设置组件:
![image](https://github.com/user-attachments/assets/cd57f0d6-78f8-457d-99fe-8734e30a09ac)

### 框架版本

Vue 3.4

### 系统版本

MacOS 13

**Comment by uyarn** [comment]
这个组件是个web components，并不合适给具体项目直接使用，实际项目不需要这样对组件进行各种调整，如果放到下载到的页面模板代码里反而大部分情况下需要删掉这部分代码；页面模板站点是为了方便自定义主题之后展示在整个中后台系统里面呈现效果使用的所以使用了这个组件 如果有特殊场景需要使用 可以参考site分支的代码 https://github.com/Tencent/tdesign-vue-next-starter/blob/site/src/layouts/setting/index.vue
