### ISSUE TITLE
[Swiper] navigation切换轮播有bug

### ISSUE THREAD

**Issue by QAQCup** [Tencent/tdesign-vue-next#4648]
### tdesign-vue-next 版本

1.10.2

### 重现链接

https://stackblitz.com/edit/xgnimz?file=src%2Fdemo.vue

### 重现步骤

![1728895863486](https://github.com/user-attachments/assets/619d1850-7905-4671-b0f0-8757320ae1b2)
从2切换到1时需要点击两次才能切换过去

### 期望结果

点击一次导航就切换轮播

**Comment by uyarn** [comment]
fixed 1.10.4, thanks for @chensid
