### ISSUE TITLE
[Switch] 新增`before-change`API

### ISSUE THREAD

**Issue by labbomb** [Tencent/tdesign-vue-next#4653]
### 这个功能解决了什么问题

switch 状态改变前的钩子， 返回 false 或者返回 Promise 且被 reject 则停止切换

### 你建议的方案是什么

参考element plus
![image](https://github.com/user-attachments/assets/f6f4690a-dae8-4dc5-9cef-cdc844542cda)

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-10-31 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by uyarn** [comment]
这个是什么样的场景会使用到？

**Comment by labbomb** [comment]
> 这个是什么样的场景会使用到？

机器人端交互，我发送指令后，需要等待结果，如果被拒绝，则不切换，待成功后在改变值

**Comment by uyarn** [comment]
supported 1.10.4, thanks for @centuryPark 🌹
