### ISSUE TITLE
[Pagination] 非受控属性 defaultPageSize 实现，抛出的事件参数不正确，请尽快修复

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#466]
### tdesign-vue-next 版本

`v0.10.2` 截止 2022.03.20 . 周日. 最新 Develop 分支代码

### 重现链接

https://stackblitz.com/edit/angular-cig5he?file=src%2Fdemo.vue

### 重现步骤

<img width="1226" alt="image" src="https://user-images.githubusercontent.com/11605702/159163126-53f81fe2-0e5a-46c9-8ed8-83bec759323c.png">

### 期望结果

在 `change/page-change` 等事件中，`current` 和 `previous` 值正确

### 实际结果

事件参数值为 `undefined`

**Comment by arieslee** [comment]
https://tdesign.tencent.com/vue-next/components/pagination 官网的例子中，点击下一页或者上一页的箭头，还是会提示"转到第NaN页",我本地更新了0.10.2，current也是NaN
```curr {current: NaN, previous: NaN, pageSize: "10"}```

**Comment by pengYYYYY** [comment]
0.11.0已修复
