### ISSUE TITLE
[TagInput] 中文模式下, 宽度监听异常,导致输入视觉上被截断

### ISSUE THREAD

**Issue by Gestorz** [Tencent/tdesign-vue-next#4666]
### tdesign-vue-next 版本

1.10.2

### 重现步骤

TagInput 进行中文输入,即可复现

 1. 中文模式下如下图, 宽度异常
<img width="821" alt="image" src="https://github.com/user-attachments/assets/b5691292-a359-4e87-aa0b-1903010a48ed">

2. 英文模式下如下图, 宽度正常
<img width="601" alt="image" src="https://github.com/user-attachments/assets/95e1e26c-1c1a-4f63-b81d-be8c36dc151d">

中文模式下输入, t-input__input-pre的内容响应丢失, 宽度计算错误,导致input 框宽度异常
<img width="984" alt="image" src="https://github.com/user-attachments/assets/ae5ab966-c5aa-4e25-9572-b6308072067c">

### 期望结果

希望中文模式下输入宽度正常, 视觉上不会被截断

**Comment by uyarn** [comment]
fixed 1.10.4
