### ISSUE TITLE
[tree] Tree关于支持编辑的计划

### ISSUE THREAD

**Issue by Wesley-0808** [Tencent/tdesign-vue-next#4682]
### 这个功能解决了什么问题

![image](https://github.com/user-attachments/assets/68881ccd-114b-4344-a5e7-5f54b3c0abdf)
如图所示，需求是做一个动态的Tree列表，但是我看tree的根本逻辑是`不支持`动态的
我需要做的就是一个`菜单管理`功能，其包含了`主项`和`子项`。这个tree就`非常适合这样用`，但是有点复杂了
### 你建议的方案是什么

支持动态绑定（双向绑定的data）并支持传入方法以替换tree的内部方法
```[tasklist]
### Tasks
```

**Comment by uyarn** [comment]
讨论了下目前1.0的版本不打算支持双向的data 不太好维护
