### ISSUE TITLE
[t-select] 选项中 label是空字符 直接显示了 value 

### ISSUE THREAD

**Issue by XieDs911** [Tencent/tdesign-vue-next#4689]
### tdesign-vue-next 版本

1.9.6

### 重现步骤

export const getSingleContent = (
  value: TdSelectProps['value'],
  optionsMap: ComputedRef<Map<SelectValue<SelectOption>, TdOptionProps>>,
): string => {
  const option = optionsMap.value.get(value);
  return option?.label || value?.toString();
};  源码中 || 判断不严谨 当我的label 是空字符串的时候 直接显示value

### 期望结果

期望 没有

### 补充说明

期望undefined 的时候 再显示 value

**Comment by uyarn** [comment]
什么需求label要展示空字符串？空字符串用户如何知道这是个什么选项？
