### ISSUE TITLE
[t-input-number]  props类型异常 属性decimalPlaces 的类型传入number提示warning

### ISSUE THREAD

**Issue by InsHomePgup** [Tencent/tdesign-vue-next#4691]
### tdesign-vue-next 版本

1.10.3

### 重现步骤

![image](https://github.com/user-attachments/assets/329a0468-54d9-4b51-8ebe-c2289c35d4c0)
![image](https://github.com/user-attachments/assets/f72c8a3b-55b9-4e71-a03a-535a3d3a7f03)

### 期望结果

传入数字不提醒

**Comment by InsHomePgup** [comment]
![image](https://github.com/user-attachments/assets/989b55e0-6980-49e7-a0f0-34012f968628)

文档内提示类型

**Comment by uyarn** [comment]
<img width="814" alt="image" src="https://github.com/user-attachments/assets/5b28752a-0bb2-4ddb-9685-697901453f4f">
1.10.2 修复了这个问题 升级一下即可 issue描述的版本应该不是现在实际使用的版本

**Comment by InsHomePgup** [comment]
确实解决了，我昨天也是升级到最新测试的，大概是有缓存没清理。
