### ISSUE TITLE
[tabs] dialog中的tabs默认选中样式不正确

### ISSUE THREAD

**Issue by daiikaku** [Tencent/tdesign-vue-next#4692]
### tdesign-vue-next 版本

1.10.3

### 重现链接

https://stackblitz.com/edit/xzsmd7-9pbhbz?file=src%2Fdemo.vue

### 重现步骤

1、点击按钮弹出对话框
2、destroy-on-close属性的dialog，tabs默认选中样式不正确

### 期望结果

默认选中tabpanel标题下面出现蓝色直线表示选中

### 实际结果

![image](https://github.com/user-attachments/assets/a0d513ef-7473-46ea-a973-f3a64052043a)

**Comment by uyarn** [comment]
fixed 1.10.4, thanks for @chensid
