### ISSUE TITLE
inputNumber会有遮挡

### ISSUE THREAD

**Issue by clark-cui** [Tencent/tdesign-vue-next#47]
**Describe Framework**

- [ ] tdesign-vue
- [x] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

**Describe Environment**
chrome  96.0.4664.110
**Describe the bug**
数字长一点的时候，就会有数字遮挡，inputNumber的demo里可以复现

![image](https://user-images.githubusercontent.com/46164858/147259854-dd15811b-1fa1-46ef-85ee-d1526556e2de.png)
![image](https://user-images.githubusercontent.com/46164858/147259926-327e7af4-ec42-4bce-81cf-4d8783d39c8f.png)
![image](https://user-images.githubusercontent.com/46164858/147260013-b2494917-fe00-41db-990f-696d8f0c657e.png)

**我打开控制台看了一下，是这个css造成的**

![image](https://user-images.githubusercontent.com/46164858/147260174-9dc4fbba-3b3c-47b6-8bc3-9265c4991f4c.png)

**Comment by chaishi** [comment]
PR：https://github.com/Tencent/tdesign-common/pull/46
