### ISSUE TITLE
[table] 表格组件开启虚拟列表，数据量低于 200 时，滚动函数无效

### ISSUE THREAD

**Issue by tiny-dust** [Tencent/tdesign-vue-next#4705]
### tdesign-vue-next 版本

1.10.2

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-vue-next-table-virtual-scroll-demo-forked-gqxr6y

### 重现步骤

1. table 组件，开启虚拟滚动配置
2. 数据量设置少于 200 个
3. 点击滚动

### 期望结果

依旧可以正常滚动

### 实际结果

没有进行滚动

**Comment by Wesley-0808** [comment]
这可以滚动啊，是我理解错意思了吗？
![freecompress-IMG_2685](https://github.com/user-attachments/assets/f70ac387-78e2-4850-9319-4c27d3f7f4b8)

**Comment by tiny-dust** [comment]
> 这可以滚动啊，是我理解错意思了吗？ ![freecompress-IMG_2685](https://private-user-images.githubusercontent.com/69622989/382259815-f70ac387-78e2-4850-9319-4c27d3f7f4b8.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDAzNDMsIm5iZiI6MTczMDcwMDA0MywicGF0aCI6Ii82OTYyMjk4OS8zODIyNTk4MTUtZjcwYWMzODctNzhlMi00ODUwLTkzMTktNGMyN2QzZjdmNGI4LkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NzliYmYwOGVjMjk0MTJkMjE5MjFmZDcyOWMzYjU0MGJiYzA5MjQyNzE5YzNjZTZiMDY5NmY2Y2VhY2ZlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.30ehXLieJUOaezWkPHJCHdFAPYIDoROkD2ZcVUt1NNg) [ ![freecompress-IMG_2685](https://private-user-images.githubusercontent.com/69622989/382259815-f70ac387-78e2-4850-9319-4c27d3f7f4b8.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDAzNDMsIm5iZiI6MTczMDcwMDA0MywicGF0aCI6Ii82OTYyMjk4OS8zODIyNTk4MTUtZjcwYWMzODctNzhlMi00ODUwLTkzMTktNGMyN2QzZjdmNGI4LkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NzliYmYwOGVjMjk0MTJkMjE5MjFmZDcyOWMzYjU0MGJiYzA5MjQyNzE5YzNjZTZiMDY5NmY2Y2VhY2ZlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.30ehXLieJUOaezWkPHJCHdFAPYIDoROkD2ZcVUt1NNg) ](https://private-user-images.githubusercontent.com/69622989/382259815-f70ac387-78e2-4850-9319-4c27d3f7f4b8.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDAzNDMsIm5iZiI6MTczMDcwMDA0MywicGF0aCI6Ii82OTYyMjk4OS8zODIyNTk4MTUtZjcwYWMzODctNzhlMi00ODUwLTkzMTktNGMyN2QzZjdmNGI4LkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NzliYmYwOGVjMjk0MTJkMjE5MjFmZDcyOWMzYjU0MGJiYzA5MjQyNzE5YzNjZTZiMDY5NmY2Y2VhY2ZlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.30ehXLieJUOaezWkPHJCHdFAPYIDoROkD2ZcVUt1NNg) [ ](https://private-user-images.githubusercontent.com/69622989/382259815-f70ac387-78e2-4850-9319-4c27d3f7f4b8.GIF?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MDAzNDMsIm5iZiI6MTczMDcwMDA0MywicGF0aCI6Ii82OTYyMjk4OS8zODIyNTk4MTUtZjcwYWMzODctNzhlMi00ODUwLTkzMTktNGMyN2QzZjdmNGI4LkdJRj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA2MDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1NzliYmYwOGVjMjk0MTJkMjE5MjFmZDcyOWMzYjU0MGJiYzA5MjQyNzE5YzNjZTZiMDY5NmY2Y2VhY2ZlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.30ehXLieJUOaezWkPHJCHdFAPYIDoROkD2ZcVUt1NNg)

低于 200就不行了，具体低于多少我没有去验证，我待会重新改下链接，你可以改成 100 条数据试试看
