### ISSUE TITLE
[Button] 浏览器缩放文字不居中

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next#4706]
### tdesign-vue-next 版本

1.10.3

### 重现链接

https://stackblitz.com/edit/q72p3x?file=src%2Fdemo.vue

### 重现步骤

demo 不明显
官网打开浏览器往小缩放一级 比较明显
![image](https://github.com/user-attachments/assets/7c4340f1-2103-42fe-ba83-976fead35628)

### 期望结果

文本保持居中

### 实际结果

文本未保持居中显示

**Comment by uyarn** [comment]
这个问题我怎么记得处理过..

**Comment by PengYYYYY** [comment]
垂直居中嘛，看着没问题啊。
<img width="503" alt="image" src="https://github.com/user-attachments/assets/d654051c-9456-4eb0-88b8-fbd0d75a45e9">

**Comment by PengYYYYY** [comment]
先关掉了
