### ISSUE TITLE
[Cascader]自定义 Label 渲染参数错误，title 显示代码段

### ISSUE THREAD

**Issue by McPorkChop** [Tencent/tdesign-vue-next#4721]
### 重现链接
https://codesandbox.io/p/sandbox/tdesign-vue-next-cascader-base-demo-forked-l2p6fh?workspaceId=b99b6f23-3ccd-4e72-b273-549ab3968582

### 重现步骤
options 数组中的 label 使用function 声明

### 期望结果
当使用function定义 label 时，根据类型声明中，function 的第一个参数应该是 vue 的 h 函数。同时选项的 title 属性应该正常显示。

### 实际结果
当使用function定义 label 时，根据类型声明中，function 的第一个参数并非 vue 的 h 函数。同时选项的 title 为function 代码。

### 补充说明
![TreeOptionData类型声明](https://github.com/user-attachments/assets/068e10e9-c3e8-431b-a8b3-87d4f1da5eba)
![image](https://github.com/user-attachments/assets/324f436e-9c76-49bf-a801-81824e8c0580)

| Environment | Info |
|---|---|
| 相关版本 | 1.10.3 |
| 框架版本 / 基础库版本 | Vue(3.5.12) |
| 系统、浏览器 | MacOS(15.0.1) Microsoft Edge(130.0.2849.80) |
| Node版本 | 20.15.1 |

**Comment by uyarn** [comment]
fixed 1.10.4
