### ISSUE TITLE
[table] 分页数据，不允许跨页选中时，表头无法选中当前页全部数据

### ISSUE THREAD

**Issue by china-chaim** [Tencent/tdesign-vue-next#4726]
### tdesign-vue-next 版本

1.10.3

### 重现链接

https://tdesign.tencent.com/vue-next/components/table?tab=demo#可选中行的表格

### 重现步骤

示例代码，设置reserveSelectedRowOnPaginate=false，分页头部多选按钮被禁用

### 期望结果

不确定这个是bug,还是本身就这样设计的。如果本身就这样设计，麻烦在文档中标注一下说明清楚

### Node版本

20.17.0

**Comment by uyarn** [comment]
fixed 1.10.4
