### ISSUE TITLE
[Input] 1.10.3 版本后 auto-width在Dialog内没有完全正常展开

### ISSUE THREAD

**Issue by china-chaim** [Tencent/tdesign-vue-next#4727]
### tdesign-vue-next 版本

1.10.3

### 重现步骤

通过最新的脚手架拉取的最新的代码

![form select](https://github.com/user-attachments/assets/5fe94967-4532-4393-b731-d7f16bd309cf)
![select page](https://github.com/user-attachments/assets/3c67e28e-e2c3-4ee3-85f1-20ff0d6718fd)

### 期望结果

有默认值时应该展开

### Node版本

20.17.0

**Comment by uyarn** [comment]
之前的版本正常吗？

**Comment by china-chaim** [comment]
> 之前的版本正常吗？

之前没用过vue3版本，用的vue2 1.10.3版本，没出现这种情况

**Comment by uyarn** [comment]
fixed 1.10.4 by @Cat1007
