### ISSUE TITLE
InputNumber 组件 min 不起作用

### ISSUE THREAD

**Issue by JHeLiu** [Tencent/tdesign-vue-next#4735]
### tdesign-vue-next 版本

1_10_3

### 重现步骤

https://tdesign.tencent.com/vue-next/components/input-number?tab=demo

### 期望结果

min  跟  max  参数 起作用

### 实际结果

min  跟  max  参数  不应该在文本框 限制  min 跟 max 参数吗？ 

现在不起作用 
min 设置 1  虽然可以输入小于 min的参数值 甚至输入空

### 补充说明

需要输入纯数字的时候。希望固定在一个范围内输入

**Comment by Wesley-0808** [comment]
比如min为5，max为10
您是想要只能输入5-10以内的数字（超过这个范围就输不进去）吗？

**Comment by JHeLiu** [comment]
@Wesley-0808  对的  还有就是 如果键盘减掉 输入框会是空， 应该监听如果输入框是空 按道理显示默认值或者 min值。感觉这样

**Comment by Wesley-0808** [comment]
> @Wesley-0808 对的 还有就是 如果键盘减掉 输入框会是空， 应该监听如果输入框是空 按道理显示默认值或者 min值。感觉这样

1. `InputNumber`默认是允许输入超出`min`和`max`值的，将`allowInputOverLimit`设置为`false`就可以在`失去输入框焦点时`更正数据值（max值或min值），但按照您的需求来看，您需要的是定义`onInput`去限制用户输入
2. 当输入框为空时，可能代表用户清空了输入框，需要重新输入数据 也没必要显示个默认值/最小值吧

**Comment by JHeLiu** [comment]
@Wesley-0808  这样也行 我当时候去试试，如果失去焦点了 回填值  输入框不是空的就行
