### ISSUE TITLE
[t-table] 分页问题

### ISSUE THREAD

**Issue by JinPing5306** [Tencent/tdesign-vue-next#4736]
### tdesign-vue-next 版本

1.10.3

### 重现步骤

表格切换分页，数据都错乱了，赶紧改吧，第一次见table出现这种低级问题.

**Comment by uyarn** [comment]
麻烦提供下复现代码

**Comment by JinPing5306** [comment]
<t-table
        bordered
        :pagination
        :loading="tableLoading"
        row-key="jqdxbs"
        :data="tableData"
        :columns="tableColumns"
        @change="tableChange"
        :disableDataPage="true"
      ></t-table>
      
      const pagination = reactive({
  defaultCurrent: 1,
  defaultPageSize: 20,
  total: 0,
});

function tableChange(e) {
  pagination.defaultCurrent = e.pagination.current;
  pagination.defaultPageSize = e.pagination.pageSize;
  seachListFucn();
}
