### ISSUE TITLE
[t-table] 表格分页，回显数据问题

### ISSUE THREAD

**Issue by JinPing5306** [Tencent/tdesign-vue-next#4741]
### tdesign-vue-next 版本

1.10.3

### 重现步骤

1.显示5条/页，切换分页，表格显示6条数据；
2.显示20条/页，切换分页，表格会多显示序号为21那一条的数据

**Comment by uyarn** [comment]
https://stackblitz.com/edit/cf8d7q?file=package.json,src%2Fdemo.vue
https://codesandbox.io/p/sandbox/tjl397?file=%2Findex.html
麻烦在这里复现你提到问题 并没有复现你说的情况 看看是不是数据源的配置问题

**Comment by JinPing5306** [comment]
![image](https://github.com/user-attachments/assets/d709af3a-afcc-4ad3-aad9-45464099655a)
重复数据

**Comment by JinPing5306** [comment]
> [https://stackblitz.com/edit/cf8d7q?file=package.json,src%2Fdemo.vue ](https://stackblitz.com/edit/cf8d7q?file=package.json,src%2Fdemo.vue) https://codesandbox.io/p/sandbox/tjl397?file=%2Findex.html 麻烦在这里复现你提到问题并没有详细说明您所说的情况看看不是数据源的配置问题

**Comment by uyarn** [comment]
需要保持colKey对应的字段是唯一的哦 不然可能有展示的异常 这个文档是有说明的
