### ISSUE TITLE
[t-table] 切换分页，数据重复

### ISSUE THREAD

**Issue by JinPing5306** [Tencent/tdesign-vue-next#4746]
### tdesign-vue-next 版本

1.10.3

### 重现步骤

![image](https://github.com/user-attachments/assets/217559e3-b20e-4a51-b92d-a1def91b5bc1)
第一页切换到下一页，数据重复；

**Comment by JinPing5306** [comment]
<t-table
        bordered
        :pagination
        :loading="tableLoading"
        row-key="jqdxbs"
        :data="tableData"
        :columns="tableColumns"
        @change="tableChange"
        :disableDataPage="true"
      ></t-table>
      
      const pagination = reactive({
        defaultCurrent: 1,
        defaultPageSize: 20,
        total: 0,
     });
     
     function tableChange(e) {
        pagination.defaultCurrent = e.pagination.current;
        pagination.defaultPageSize = e.pagination.pageSize;
         seachListFucn();
}

**Comment by uyarn** [comment]
tableColumns  tableData 这两个字段提供一下

**Comment by JinPing5306** [comment]
> tableColumns tableData 这两个字段提供一下

const tableColumns = ref([
  { colKey: 'serial-number', title: '序号', align: 'center', ellipsis: true },
  { colKey: 'asjfskssj', title: '事发时间', align: 'center', width: '220' },
  { colKey: 'sacs_dzmc', title: '事发地点', align: 'center', ellipsis: true },
  { colKey: 'pcsmc', title: '所属派出所', align: 'center', ellipsis: true },
  { colKey: 'jflb', title: '纠纷类别', align: 'center', ellipsis: true },
  {
    colKey: 'ay',
    title: '纠纷内容',
    align: 'center',
    ellipsis: true,
  },
  { colKey: 'rs', title: '涉及人数', align: 'center' },
  { colKey: 'xm', title: '姓名', align: 'center' },
  { colKey: 'sfzh', title: '身份证号', align: 'center', ellipsis: true },
  { colKey: 'tjsj', title: '添加时间', align: 'center', width: '220' },
  {
    colKey: 'handl',
    title: '操作',
    align: 'center',
    width: '220',
    cell: (h, { row }) => {
      return (
        <div>
          <t-button variant="text" theme="primary" onClick={() => detialsShow(row)}>
            详情
          </t-button>
          <t-button variant="text" theme="primary" onClick={() => editClickDialog(row)}>
            编辑
          </t-button>
          <t-button variant="text" theme="danger" onClick={() => delFucn(row)}>
            删除
          </t-button>
        </div>
      );
    },
  },
]);

const tableData=[{
asjfskssj: "2024-11-15 01:01",
ay: "2024年11月15日08:47:43",
bz: "2024年11月15日08:47:43",
fj: "data:image/gif;base64,R0lGODlhXga6A/f/ABtNaRxZdAw,
fxdj: null,
jflb: "由工程施工引发的",
jqdxbs: "56b3fe5d478e4050b9355e696ec61a37",
jqly: "1",
pcsmc: "河北省廊坊市公安局广阳分局北旺派出所",
rs: 1,
sacs_dzmc: "2024年11月15日08:47:43",
sfxtw: "否",
sfzh: "352622195810170438",
tjsj:"11/14/2024 16:49:11",
xm: "夏劲釜",}]

**Comment by JinPing5306** [comment]
> tableColumns tableData 这两个字段提供一下
const tableColumns = ref([
{ colKey: 'serial-number', title: '序号', align: 'center', ellipsis: true },
{ colKey: 'asjfskssj', title: '事发时间', align: 'center', width: '220' },
{ colKey: 'sacs_dzmc', title: '事发地点', align: 'center', ellipsis: true },
{ colKey: 'pcsmc', title: '所属派出所', align: 'center', ellipsis: true },
{ colKey: 'jflb', title: '纠纷类别', align: 'center', ellipsis: true },
{
colKey: 'ay',
title: '纠纷内容',
align: 'center',
ellipsis: true,
},
{ colKey: 'rs', title: '涉及人数', align: 'center' },
{ colKey: 'xm', title: '姓名', align: 'center' },
{ colKey: 'sfzh', title: '身份证号', align: 'center', ellipsis: true },
{ colKey: 'tjsj', title: '添加时间', align: 'center', width: '220' },
{
colKey: 'handl',
title: '操作',
align: 'center',
width: '220',
cell: (h, { row }) => {
return (


<t-button variant="text" theme="primary" onClick={() => detialsShow(row)}>
详情

<t-button variant="text" theme="primary" onClick={() => editClickDialog(row)}>
编辑

<t-button variant="text" theme="danger" onClick={() => delFucn(row)}>
删除


);
},
},
]);
const tableData=[{
asjfskssj: "2024-11-15 01:01",
ay: "2024年11月15日08:47:43",
bz: "2024年11月15日08:47:43",
fj: "data:image/gif;base64,R0lGODlhXga6A/f/ABtNaRxZdAw,
fxdj: null,
jflb: "由工程施工引发的",
jqdxbs: "56b3fe2222b9355e696ec61a37",
jqly: "1",
pcsmc: "干啊！",
rs: 1,
sacs_dzmc: "2024年11月15日08:47:43",
sfxtw: "否",
sfzh: "312222195810170438",
tjsj:"11/14/2024 16:49:11",
xm: "夏哈哈",}]

**Comment by china-chaim** [comment]
`  const pagination = reactive({
    current: 1,
    pageSize: 20,
    total: 0,
 });
 
 function tableChange(e) {
    pagination.current= e.pagination.current;
    pagination.pageSize= e.pagination.pageSize;
`,不要用默认的default参数

**Comment by JinPing5306** [comment]
> ` const pagination = reactive({ current: 1, pageSize: 20, total: 0, });
> 
> function tableChange(e) { pagination.current= e.pagination.current; pagination.pageSize= e.pagination.pageSize; `,不要用默认的default参数
不用默认的default参数也不行

**Comment by JinPing5306** [comment]
> @page-change="onPageChange"
> 
> const pagination =ref({ current: 1, pageSize: 20, total: 0, }); const onPageChange = async (pageInfo) => { pagination.value.current = pageInfo.current; pagination.value.pageSize = pageInfo.pageSize; }; pagination 的定义reactive换成ref 我用的默认分页方法，然后受控方式分页查询，带default的查询之前也遇到问题，解决方案没找到

_解决了，谢谢大哥_

**Comment by uyarn** [comment]
> @page-change="onPageChange"
> 
> const pagination =ref({ current: 1, pageSize: 20, total: 0, }); const onPageChange = async (pageInfo) => { pagination.value.current = pageInfo.current; pagination.value.pageSize = pageInfo.pageSize; }; pagination 的定义reactive换成ref 我用的默认分页方法，然后受控方式分页查询，带default的查询之前也遇到问题，解决方案没找到

@china-chaim 是说reactive的非受控方法 会出现这个issue描述的问题？

**Comment by china-chaim** [comment]
> > @page-change="onPageChange"
> > const pagination =ref({ current: 1, pageSize: 20, total: 0, }); const onPageChange = async (pageInfo) => { pagination.value.current = pageInfo.current; pagination.value.pageSize = pageInfo.pageSize; }; pagination 的定义reactive换成ref 我用的默认分页方法，然后受控方式分页查询，带default的查询之前也遇到问题，解决方案没找到
> 
> @china-chaim 是说reactive的非受控方法 会出现这个issue描述的问题？

不确定，非受控方法除了这种情况ref的之前也有遇到过，后来全换了受控方法，效果实现后没仔细查看具体原因。还有table tree 默认展开也是无效，文档示例没问题，换成接口获取数据就出问题了。查了下资料，可能是响应式数据更新后，参数没渲染成功
