### ISSUE TITLE
[TreeSelect ] 希望组件支持禁用某个节点的时候，不要禁用它所属的子节点

### ISSUE THREAD

**Issue by jieyuming** [Tencent/tdesign-vue-next#4761]
### 这个功能解决了什么问题

目前的需求，用TreeSelect 组件展示部门的组织架构，部门下同时有子部门和人员，希望子部门不能被选中（需要禁用），但子部门下的用户可以被选中

### 你建议的方案是什么

希望可以支持，我给父的节点设置disabled： true，然后再给子节点设置disabled: false，实现子节点可选
{
    label: '江苏省',
    value: 'jiangsu',
    disabled: true,
    children: [
      {
        label: '南京市',
        value: 'nanjing',
        disabled: false，
      },
      {
        label: '苏州市',
        value: 'suzhou',
         disabled: false，
      },
    ],
  },

**Comment by uyarn** [comment]
打开 check-strictly 即可 https://stackblitz.com/edit/8ivbfp-95x3eb?file=package.json,src%2Fdemo.vue
