### ISSUE TITLE
[组件名称]下拉框popup背景色不能改变

### ISSUE THREAD

**Issue by JinPing5306** [Tencent/tdesign-vue-next#4766]
### tdesign-vue-next 版本

1.10.3

### 重现步骤

 <t-select
        :teleported="false"
        :popupProps="{ style: { backgroundColor: '#16539c' } }"
        style="width: 180px"
        placeholder="请选择"
      >
        <t-option key="apple" label="Apple" value="apple" style="color: #00ffff"> </t-option>
      </t-select>
      
      popupProps不能改变背景色

**Comment by uyarn** [comment]
你是要改变具体哪里的颜色？（给个截图

**Comment by JinPing5306** [comment]
> 你是要改变具体哪里的颜色？（给个截图

![image](https://github.com/user-attachments/assets/5c8add72-8ebc-4c24-9cc4-d27e783e9c1b)

**Comment by PengYYYYY** [comment]
可以用 select 组件的 popup-props 中的 overlay-class-name 属性，然后写样式改背景，还有 select 的选项背景之类的样式需要修改，需要使用比较 hack 的方式。没有直接改背景色的 API。
