### ISSUE TITLE
[t-cascader] 下拉面板拉起时，出现异常

### ISSUE THREAD

**Issue by jinht2** [Tencent/tdesign-vue-next#477]
### tdesign-vue-next 版本

0.10.2

### 重现步骤

前置条件：包含filterable写法
复现步骤：focus操作（在placeholder文案处）

### 期望结果

下拉面板应被正常拉起

### 实际结果

下拉面板会闪烁不定地被拉起

**Comment by pengYYYYY** [comment]
0.11.0已修复
