### ISSUE TITLE
[t-cascader] 输入内容，未被正常销毁

### ISSUE THREAD

**Issue by jinht2** [Tencent/tdesign-vue-next#478]
### tdesign-vue-next 版本

0.10.2

### 重现步骤

前置条件：包含filterable multitupe写法
复现步骤：输入xx > 下拉面板中选择某些项 > blur操作 > clear操作 > focus操作

### 期望结果

输入框应该是空的，xx不应该再出现

### 实际结果

发现xx还在

**Comment by pengYYYYY** [comment]
0.11.0已修复
