### ISSUE TITLE
[Popup] 有没有办法使用visible 保留点击其他区域主动关闭

### ISSUE THREAD

**Issue by Jiachang-Cai** [Tencent/tdesign-vue-next#4784]
### 这个功能解决了什么问题

当使用visible 点击内容区域外不能主动关闭
trigger="click" 可以 或者 trigger="click" 模式下 提供API内容点击后能主动触发关闭

### 你建议的方案是什么

![image](https://github.com/user-attachments/assets/17cd83a6-045e-4f4c-9261-fb0f3bcd90b6)
希望提供点击能触发trigger的API

**Comment by uyarn** [comment]
在onvisiblechange的回调里可以处理的 给个具体的例子看看你的使用方式

**Comment by Jiachang-Cai** [comment]
> 在onvisiblechange的回调里可以处理的 给个具体的例子看看你的使用方式

https://stackblitz.com/edit/zwb7xf?file=src%2Fdemo.vue
两个情况 看能不能实现
1. 第一种形式如何通过关闭按钮关闭
2. 第二种形式如何点击content区域外任何位置关闭

**Comment by uyarn** [comment]
参考 https://stackblitz.com/edit/wuv2fk?file=package.json,src%2Fdemo.vue

**Comment by Jiachang-Cai** [comment]
> 参考 https://stackblitz.com/edit/wuv2fk?file=package.json,src%2Fdemo.vue

感谢哦抄的demo 忘记v-model 使用了
