### ISSUE TITLE
[t-pagination]输入框颜色异常，为红色

### ISSUE THREAD

**Issue by jinht2** [Tencent/tdesign-vue-next#480]
### tdesign-vue-next 版本

0.10.2

### 重现步骤

click某个页码（比如 第3页）  > 观察：右边的GO输入框

### 期望结果

右边的GO输入框：应该颜色正常（为黑色）

### 实际结果

右边的GO输入框：为红色

**Comment by pengYYYYY** [comment]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/35833812/159832064-3f479ecb-c43b-4aa1-ac17-0a22af658fd9.png">

是这个问题吗？这是正常表现，pagination内置的input-number 会处理页码校验

**Comment by pengYYYYY** [comment]
如果不是这个复现的话，请给一个复现的链接再reopen这个issue
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/35833812/159832252-1511bd34-8e25-4949-8438-a09a584448bb.png">

**Comment by jinht2** [comment]
> closed

<img width="642" alt="截屏2022-05-06 下午4 33 57" src="https://user-images.githubusercontent.com/47624908/167096884-a7186861-caeb-4de0-93fb-b3e5009c9299.png">
<img width="748" alt="企业微信截图_d6cdcd9d-03dc-46b4-adb7-c3991592df29" src="https://user-images.githubusercontent.com/47624908/167097277-467a30ec-beee-4aa5-bdc8-808612ba87b9.png">

<img width="618" alt="企业微信截图_e17a6c16-4f94-4e6a-8afe-2342a597588b" src="https://user-images.githubusercontent.com/47624908/167097366-5d327453-5bce-4e1b-93ec-a027450165eb.png">
<img width="560" alt="企业微信截图_eb655c0e-31e1-4528-bbc4-9a9b74a36a21" src="https://user-images.githubusercontent.com/47624908/167097475-6b1c18fa-451f-4134-ab9c-029d59c49374.png">
您看看上面我贴的图，还是有问题的。
该地址，可复现bug：https://sports.woa.com/v2/galaxy#/content/all/pic
