### ISSUE TITLE
[tagInput] :value语法糖无法使用

### ISSUE THREAD

**Issue by Wesley-0808** [Tencent/tdesign-vue-next#4805]
### tdesign-vue-next 版本

1.10.4

### 重现链接

https://codesandbox.io/p/devbox/yyq8sk

### 重现步骤

重现链接可复现

### 期望结果

![image](https://github.com/user-attachments/assets/03f1fd43-8520-4c58-a60a-f2932a943755)

### 实际结果

使用了:value 输入内容按下回车后只会清空输入框

**Comment by PengYYYYY** [comment]
这个 value 值是 tagInput 的值，不是tagInput 里面的输入框的值，输入框的值，请用 inputValue。

**Comment by Wesley-0808** [comment]
@PengYYYYY 不是啊 你看看复现链接 就是使用:value的话 taginput就无法使用了 你理解错意思了吧

**Comment by Wesley-0808** [comment]
了解了，还是建议在文档中同时说明一下哈

**Comment by PengYYYYY** [comment]
<img width="937" alt="image" src="https://github.com/user-attachments/assets/74525e37-8d7c-4bc2-8129-d7d0a7be1610">

第一个 demo 就有相关使用方法了哈

**Comment by Wesley-0808** [comment]
okay~
