### ISSUE TITLE
[t-pagination] 分页器组件现在点击左右箭头获取不到对应的页码

### ISSUE THREAD

**Issue by taomas** [Tencent/tdesign-vue-next#481]
### tdesign-vue-next 版本

0.10.2

### 重现链接

https://0_10_2-tdesign-vue-next.surge.sh/vue-next/components/pagination

### 重现步骤

分页器点击左右分页，获取不到对应的页码。

### 期望结果

能正常获取左右箭头的页码。

### 实际结果

<img width="1515" alt="wecom-temp-87d04bfa0b634b0595031a3cee4d9a26" src="https://user-images.githubusercontent.com/17002702/159828131-a3d3fac9-09e7-4717-88a3-502bb06ae27c.png">

**Comment by pengYYYYY** [comment]
#471 已经修复，感谢反馈，官网会跟随下个版本修复好
