### ISSUE TITLE
[t-dialog] 设置 header为false时 还是会显示头部元素

### ISSUE THREAD

**Issue by mayday97** [Tencent/tdesign-vue-next#4832]
### tdesign-vue-next 版本

1.10.4

### 期望结果

<t-dialog
    v-model:visible="show"
    attach="body"
    width="80vw"
    :header="false"
    :footer="false"
    :closeBtn="false"
    destroyOnClose
    class="chart-detail-pop-wrap"
  >
    <div class="flex top-box">
      <div class="chart-name">图表名称</div>
    </div>
    <div class="chart-render-wrap">

    </div>
  </t-dialog>

### 实际结果

![image](https://github.com/user-attachments/assets/15c98a6e-2692-4c05-b0de-db8e78bb552e)

### 框架版本

Vue(3.5.13)

### Node版本

18.16.0

## IssueShoot
- 预估时长: 1
- 期望完成时间: 2024-12-17 00:00:00 +0000 UTC
- 开发难度: 低
- 参与人数: 1
- 需求对接人: ivringpeng
- 验收标准: 实现期望改造效果，提 PR 并通过验收无误
- 备注: 最终激励以实际提交 `pull request` 并合并为准

**Comment by coding-climber** [comment]
这个是不是对需求的理解存在分歧呀

**Comment by uyarn** [comment]
close-btn 和header 同时为false 确实没有必要渲染这个header了

**Comment by uyarn** [comment]
fixed 1.10.6
