### ISSUE TITLE
[PrimaryTable] filterIcon自定义Filter无效，不起任何作用

### ISSUE THREAD

**Issue by Tokgos** [Tencent/tdesign-vue-next#4836]
### tdesign-vue-next 版本

1.10.4

### 重现步骤

`<t-enhanced-table  :data="tableData" row-key="index" :filterIcon="filterIcon"></t-enhanced-table>`
`<script setup lang="tsx" name="Table">
const filterIcon = () => {
    return <span>Icon</span>
}
<script>`

### 框架版本

3.5.13

### Node版本

21.7.1

**Comment by Tokgos** [comment]
![image](https://github.com/user-attachments/assets/11ad6c0c-e02f-48f4-9b06-c01d772bbad1)
把FilterIcon这个属性卸载columns中一样无效。

**Comment by uyarn** [comment]
fixed 1.10.6
