### ISSUE TITLE
[select] select下拉选择框点击其他元素时自动触发收起的时间对iframe元素不生效

### ISSUE THREAD

**Issue by WebsterSun** [Tencent/tdesign-vue-next#4843]
### tdesign-vue-next 版本

1.10.2

### 重现链接

https://codesandbox.io/p/sandbox/tdesign-vue-next-select-multiple-demo-forked-34lsqy?file=%2Fsrc%2Fdemo.vue%3A33%2C13

### 重现步骤

当下拉框展开时，点击iframe区域，下拉框不会自动收起

### 期望结果

点击iframe区域，下拉框自动收起

### 实际结果

点击iframe区域，下拉框不会自动收起

### 系统版本

windows11

### Node版本

18.10.0

**Comment by uyarn** [comment]
https://stackblitz.com/edit/puopm36z?file=package.json,src%2Fdemo.vue
