### ISSUE TITLE
（示例文档）Table表格中——远程数据分页中，数据声明不合规（在ts模式下）。

### ISSUE THREAD

**Issue by RSS1102** [Tencent/tdesign-vue-next#485]
### 重现链接
[报错提示如下](https://user-images.githubusercontent.com/81673017/159970979-7f2c046a-e04e-4d67-8c7f-e5a77a2542a2.png)

### 重现步骤
1.将“远程数据分页”代码复制到“tdesign-vue-next-starter”项目中运行。
2,提示报错提示“缺少属性 \"total\"”。

### 期望结果
无ts提示报错。

### 实际结果
ts报错：
"类型“{ current: any; pageSize: any; }”的参数不能赋给类型“{ current: number; pageSize: number; total: number; }”的参数。\n  类型 \"{ current: any; pageSize: any; }\" 中缺少属性 \"total\"，但类型 \"{ current: number; pageSize: number; total: number; }\" 中需要该属性。

| Environment | Info |
|---|---|
| 相关版本 | 0.10.2 |
| 框架版本 / 基础库版本 | "vue": "^3.2.31", |
| 系统、浏览器 | Windows 10，Chrome（99.0.4844.51） |
| Node版本 | v14.18.0 |

![image](https://user-images.githubusercontent.com/81673017/159970979-7f2c046a-e04e-4d67-8c7f-e5a77a2542a2.png)

**Comment by pengYYYYY** [comment]
const pagination = ref(Object.create(null))

**Comment by RSS1102** [comment]
不应该先单独声明出 const total = 120;
然后再使用他吗？

代码：https://github.com/RSS1102/vue3-manage-tdesign/blob/main/src/components/froms/index.vue

![image](https://user-images.githubusercontent.com/81673017/160046358-fd6ab064-1664-4841-8b07-747fbb8c2f33.png)
