### ISSUE TITLE
[Radio] readonly 状态下希望变成禁用样式

### ISSUE THREAD

**Issue by Lnncoco** [Tencent/tdesign-vue-next#4857]
### tdesign-vue-next 版本

1.10.5

### 重现步骤

按钮单选框形式下，同时添加 readonly 属性

### 期望结果

鼠标样式变更为禁用样式

### 实际结果

当为只读状态时，鼠标依然是可点击的样式，导致用户容易误判

其他如input，只读状态下虽然变了，但是点击形式的，也很容易有误判。select只读状态也是可点击的，也有同样的问题。

**Comment by uyarn** [comment]
和设计同学讨论了一下 目前input相关组件的只读效果都是类似原生html的input的，所以尽量按类似的效果实现；radio原生Html没有，但是为了保持一致的风格所以也和input是一样的交互效果，这个
