### ISSUE TITLE
[ dateRangePicker] 日期区间可以只选择一个开始时间

### ISSUE THREAD

**Issue by Brokenstrings** [Tencent/tdesign-vue-next#4867]
### tdesign-vue-next 版本

1.10.5

### 重现步骤

官网demo就能复现问题，首先选择一个开始时间，然后点击开始时间的输入框，再选还是开始时间然后选择面板就消失了，然后区间范围只有一个开始时间，同理如果先选择结束时间后再点击结束位置输入框再选择只更新了结束时间然后面板消失无法选择开始时间了，导致区间只有一个时间。

![image](https://github.com/user-attachments/assets/5f3a6434-d50f-49dc-9e19-cd26e960c285)

### 期望结果

选择后如果再次点击开始时间，选择后应该是更新开始时间，选择面板还在可以继续选择结束时间。

### 实际结果

只更新开始时间，选择面板保留再选择填充结束时间再关闭面板。

**Comment by uyarn** [comment]
fixed 1.10.6
