### ISSUE TITLE
[table] 怎么给行或者单元格写样式？

### ISSUE THREAD

**Issue by whr2349** [Tencent/tdesign-vue-next#489]
### 这个功能解决了什么问题

比如说我单击或者双击某一行或者单元格，我要给他个样式怎么写？
组件有没有提供类似的功能？
是不是我需要自己去用原生的获取dom去实现？

### 你建议的方案是什么

[提供](https://element-plus.gitee.io/zh-CN/component/table.html#table-attributes)

**Comment by chaishi** [comment]
`rowClassName` 设置行样式
`column. className` 设置列样式

<img width="919" alt="image" src="https://user-images.githubusercontent.com/11605702/160070452-9f4d62eb-1ea1-400d-8879-b97fc12cb9e5.png">

<img width="894" alt="image" src="https://user-images.githubusercontent.com/11605702/160070491-0f99f5a1-f1f8-418b-a568-84f85140d159.png">
