### ISSUE TITLE
[按需引入] t-steps 报错无法使用

### ISSUE THREAD

**Issue by ceword** [Tencent/tdesign-vue-next#494]
### tdesign-vue-next 版本

0.11.0

### 重现链接

https://stackblitz.com/edit/vue-lfb1jl-j9tihh?file=src/App.vue

### 重现步骤

按照官方的按需引入教程配置完后，t-input-number 和 t-steps 引入后报错，且无法使用。

### 期望结果

t-input-number 正常显示数字
t-steps 正常使用

### 实际结果

t-input-number 不显示
t-steps 报错

### 框架版本

3.2.25

### 浏览器版本

Version 99.0.1150.46 (Official build) (64-bit)

### 系统版本

windows11

### Node版本

v17.8.0

**Comment by ceword** [comment]
0.11.2 里 t-input-number已经可以，但是t-steps依旧报错无法使用。

**Comment by uyarn** [comment]
@ceword t-steps的问题是插件规则导致的  https://github.com/antfu/unplugin-vue-components 需要等antfu发新版本处理 发了新版本在这个issue周知你一下吧

**Comment by pengYYYYY** [comment]
0.12.0 已修复
