### ISSUE TITLE
[TreeSelect 树选择] 搜索时无法输入中文,无法排除父节点选择

### ISSUE THREAD

**Issue by NameMingJie** [Tencent/tdesign-vue-next#498]
### tdesign-vue-next 版本

0.11.0

### 重现步骤

1. 属性 filterable:true 时, 筛选框无法输入中文进行过滤
2. :tree-props="{valueMode: 'onlyLeaft',}" 无法禁止选择父节点

**Comment by Godlike-meteor** [comment]
Hi, 我们已经收到你的问题。
问题1: 我们将在下个版本修复这个问题；
问题2: 目前仅多选支持 valueMode ，实际上单选是不支持的，可以参考这个例子：https://stackblitz.com/edit/angular-tdkdky?file=src%2Fdemo.vue

**Comment by pengYYYYY** [comment]
0.11.2 已修复
