### ISSUE TITLE
[TreeSelect 树选择] 允许多选情况下 max属性 无法控制点击父节点

### ISSUE THREAD

**Issue by NameMingJie** [Tencent/tdesign-vue-next#499]
### tdesign-vue-next 版本

0.11.0

### 重现步骤

<t-tree-select
                  multiple
                  :max="1"
                />
点击父节点无法控制"多选数量"

**Comment by Godlike-meteor** [comment]
@pengYYYYY 这里有个逻辑点不是很清楚，点击父节点，设计是哪种期望呢？
1、默认勾选两个，变成disabled状态（当前）；
2、默认一个都不勾选；
3、随机勾选1个，变成disabled状态；

**Comment by pengYYYYY** [comment]
0.11.2 已修复
