### ISSUE TITLE
[Tree 树] 使用filter过滤属性后 expandMutex属性和expandOnClickNode失效

### ISSUE THREAD

**Issue by NameMingJie** [Tencent/tdesign-vue-next#502]
### tdesign-vue-next 版本

0.11.0

### 重现步骤

1. 使用filter属性进行数据过滤
2. 清除过滤文本
3. 会发现 expandMutex属性和expandOnClickNode属性已失效

**Comment by TabSpace** [comment]
看了下最新的示例，没有这个问题。
注意 filter 被设置时，路径节点为锁定状态。
清除搜索条件时，filter 要设置为 null。
如果 filter 函数依然存在，仅仅返回字符串为空值，则逻辑上视为匹配了所有节点。
请查看最新示例代码，来确认 filter 使用方式。
https://codesandbox.io/s/tdesign-vue-demo-tree-filter-mutex-vxfjce?file=/src/demo.vue
