### ISSUE TITLE
[t-header-menu]使用t-submenu template #icon无效的标题

### ISSUE THREAD

**Issue by mo4223** [Tencent/tdesign-vue-next#510]
### tdesign-vue-next 版本

0.11.0

### 重现步骤

<img width="1918" alt="image" src="https://user-images.githubusercontent.com/35833812/160765208-d5d2049d-46f6-4cdd-b953-c65ccd4583d4.png">

### 浏览器版本

99.0.4844.51

**Comment by pengYYYYY** [comment]
0.14.1 已修复
