### ISSUE TITLE
为什么不使用 compositionApi 进行开发

### ISSUE THREAD

**Issue by whylost** [Tencent/tdesign-vue-next#52]
如题, 有使用 compositionApi 进行重构的计划吗

**Comment by pengYYYYY** [comment]
您好，TDesign vue 技术栈在启动初期是先从vue2开始的，vue3是在vue2的基础上做的。起步较晚，采取的技术路线是options API，同时我们的组件dom, style, API是多个技术栈复用的，复用vue2的代码逻辑可以先快速支持vue3。我们也在menu 组件里使用的是compositionAPI做的，vue2也依赖了compositionAPI 的扩展包，保持两端复用代码。后续新规划的组件我们会从vue3用compositionAPI开始做，再推到vue2。也会推动一些老组件的重构。

**Comment by pengYYYYY** [comment]
也非常欢迎贡献代码，对现有组件做 CompositionApi 的重构

**Comment by pengYYYYY** [comment]
可以参与这个
