### ISSUE TITLE
[Dialog] confirm-btn 配置项 传递null 会告知TS类型错误

### ISSUE THREAD

**Issue by 2199202809** [Tencent/tdesign-vue-next#521]
### tdesign-vue-next 版本

0.11.0

### 重现步骤

![dialog-bug](https://user-images.githubusercontent.com/57348011/161191760-c0c8f525-af7e-4121-8617-4300ea25c7c2.png)

**Comment by 2199202809** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/513  
拉取最新仓库代码，发现这个bug并没有得到解决

**Comment by pengYYYYY** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/35833812/161201470-8260783e-ecd7-4457-a7e8-22cdc513a00f.png">
注意一下类型，可以传 null

**Comment by skytt** [comment]
> <img alt="image" width="865" src="https://user-images.githubusercontent.com/35833812/161201470-8260783e-ecd7-4457-a7e8-22cdc513a00f.png">
> 
> 注意一下类型，可以传 ‘’

<img width="933" alt="wecom-temp-484348407f2fab9e902fb3d2ec7408f7" src="https://user-images.githubusercontent.com/7420660/163308053-6a61b5c6-5d80-4319-bce9-a30f1ea8c807.png">

传 '' 无法隐藏取消按钮，应该只能给null，需要按钮参数支持null类型

**Comment by chaishi** [comment]
这个错误，是哪里报出来的？内部组件，还是外部使用，前面的截图无法区分

**Comment by skytt** [comment]
> 这个错误，是哪里报出来的？内部组件，还是外部使用，前面的截图无法区分

外部使用会报

https://github.com/Tencent/tdesign-vue-next/blob/develop/src/dialog/hooks.tsx #83 和 #101 ，从这两个地方看，貌似只有 cancelBtn 属性为 null 的时候，才能隐藏这个按钮

**Comment by pengYYYYY** [comment]
0.14.0 已修复
