### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by amadeus711** [Tencent/tdesign-vue-next#53]
我有一些想法，想提 pr ，但是 fork 只有遇到了些项目问题，有可以讨论的群吗

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign readme有用户群的二维码，也可以在这边描述您的问题，和阐述你的想法

**Comment by pengYYYYY** [comment]
现在fork下来。项目ok了嘛
