### ISSUE TITLE
[Table] col值以数字结尾时，设置ellipsis: true后hover功能偶尔失效

### ISSUE THREAD

**Issue by linzcity** [Tencent/tdesign-vue-next#534]
### tdesign-vue-next 版本

Vue Next for Web

### 重现链接

https://stackblitz.com/edit/angular-mzhrde?file=src%2Fdemo.vue

### 重现步骤

某个列值设置参数如下：
{
      colKey: 'name',
      title: '测试hover',
      width: 153,
      ellipsis: true,
}

具体测试值：
name =  '这个是测试123'（有省略号，但不能hover）
name =  '这个是测试一二三' （有省略号，且能hover）

### 期望结果

能够省略多余并hover展示全部

### 实际结果

能够省略多余，但hover失效（仅当值以数字结尾时）
<img width="744" alt="截屏2022-04-02 下午2 18 20" src="https://user-images.githubusercontent.com/40171365/161369734-5f62efc2-3f75-42a9-bfa0-c6049e720b61.png">

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/468

**Comment by pengYYYYY** [comment]
0.12.0 已修复
