### ISSUE TITLE
[Message] macos 没有动画效果

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#538]
### tdesign-vue-next 版本

最新版

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/list/base

### 重现步骤

点删除看看

### 期望结果

在 macox 中动画正常

### 实际结果

在 macox 中动画不正常

### 框架版本

Vue(3.2.31)

### 系统版本

MacOs(12.2.1)

### 补充说明

Windows 正常

**Comment by pengYYYYY** [comment]
是dialog嘛

**Comment by Crazymuyang** [comment]
> 是dialog嘛

是Message。点击删除>确定
![image](https://user-images.githubusercontent.com/28809916/161387106-10f1a457-189e-4b34-a7b7-928bbd46bb1c.png)

**Comment by Crazymuyang** [comment]
> 是dialog嘛

是Message。点击删除>确定
![image](https://user-images.githubusercontent.com/28809916/161387106-10f1a457-189e-4b34-a7b7-928bbd46bb1c.png)

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/546

**Comment by pengYYYYY** [comment]
0.12.0 已修复
