### ISSUE TITLE
[t-slider]t-slider设置inputNumberProps无效

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#544]
### tdesign-vue-next 版本

0.11.1

### 重现步骤

![image](https://user-images.githubusercontent.com/10460238/161919335-162d3713-9e95-4c11-9c25-39e1e9c27066.png)
![image](https://user-images.githubusercontent.com/10460238/161919359-a81e2832-7ced-4c87-a7db-a848ead1b6f6.png)
![image](https://user-images.githubusercontent.com/10460238/161919378-5dc5286e-35fe-411c-8c04-3a8ada340ca6.png)
inputNumberProps设置了theme，但是没生效，InputNumber依然存在增加减少按钮

### 期望结果

t-slider设置inputNumberProps属性后，InputNumber组件可以正常按照inputNumberProps设置的属性显示交互

### 实际结果

inputNumberProps设置了theme，但是没生效，InputNumber依然存在增加减少按钮

**Comment by pengYYYYY** [comment]
0.12.0 已修复
