### ISSUE TITLE
[Loading] 全局加载部分的示例文本描述和实际代码不符

### ISSUE THREAD

**Issue by delbertbeta** [Tencent/tdesign-vue-next#548]
### tdesign-vue-next 版本

0.11.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/loading#%E5%85%A8%E5%B1%8F%E5%8A%A0%E8%BD%BD

### 重现步骤

示例文本描述 `1秒后自动归位`

```html
<div>
      全局加载开关（开启加载1秒后自动归位）：
      <t-switch v-model="loading"></t-switch>
</div>
```

实际代码是 timeout 了 10s

```javascript
const timer = setTimeout(() => {
   loading.value = false;
   clearTimeout(timer);
}, 10000);
```

### 期望结果

```js
setTimeout(/* .... */, 1000);
```

只 timeout 1s

### 实际结果

timeout 了 10s

**Comment by pengYYYYY** [comment]
有兴趣的话可以提个PR改一下这个示例代码

**Comment by delbertbeta** [comment]
> 有兴趣的话可以提个PR改一下这个示例代码

提了
