### ISSUE TITLE
[Table] 空数据展示错误

### ISSUE THREAD

**Issue by cowblue** [Tencent/tdesign-vue-next#550]
### tdesign-vue-next 版本

0.11.2

### 重现链接

https://0_11_2-tdesign-vue-next.surge.sh/vue-next/components/table#%E7%A9%BA%E8%A1%A8%E6%A0%BC

### 重现步骤

空数据既能重现

### 期望结果

空数据展示正确

### 补充说明

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/20150890/162111166-952160a2-e6d2-43b5-a8fd-216dcbdd6037.png">

**Comment by pengYYYYY** [comment]
0.12.0 已修复
