### ISSUE TITLE
[t-input] password的icon切换后输入文本依然是暗文

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#556]
### tdesign-vue-next 版本

0.11.1

### 重现步骤

![image](https://user-images.githubusercontent.com/10460238/162382243-4b7bb866-8326-4299-be84-93f13e4599d3.png)
官网demo

### 期望结果

点击眼睛icon密码文本明文暗文切换

### 实际结果

点击眼睛icon，只有icon变化，实际没有交互

**Comment by pengYYYYY** [comment]
0.12.0 已修复
