### ISSUE TITLE
[t-slider] 渲染过多这个组件，会变得卡顿

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#557]
### tdesign-vue-next 版本

0.11.1

### 重现步骤

![image](https://user-images.githubusercontent.com/10460238/162382593-b4518f29-3d8a-4b85-9c7e-d38d3b90c111.png)
![image](https://user-images.githubusercontent.com/10460238/162382553-a5251520-b20c-4176-859f-6dccc0ff287f.png)
渲染一个Slider组件会出现两个警告，过多会卡线程

### 期望结果

渲染Slider不要警告

### 实际结果

渲染Slider有警告

**Comment by ChrisLee0211** [comment]
@woshishade 经压测，并没有发现slider存在性能问题。这个warning实际上是chrome的提示，意思是希望对touch事件监听传入passive属性告知是否事件内部有调用preventDefault方法，好让chrome提前做优化，应该不是引起卡顿的原因。具体的进一步排查还是希望可以使用codeSandbox做一个简单的demo来复现问题
