### ISSUE TITLE
t-cascader

### ISSUE THREAD

**Issue by zhoudaxian** [Tencent/tdesign-vue-next#569]
### tdesign-vue-next 版本

0.40.2

### 重现步骤

1. filterable  不支持忽略大小写
2. filter 选项点击以后不是直接选中结果并关闭选项，而是展开选项
3. 文本过长截取采用的是特定文本长度，而不是按宽度实现
4. 省略文本的hover状态会随着组件滚动而滚动 体验不好

### 期望结果

1.filterable 支持忽略大小写搜索
2.点击filter搜索结果，直接保存并关闭弹窗
3.文本过长省略是否可以实现自定义传值，而不是组件写死。，或者按宽度自动实现
4.组件滚动时 t-tooltip状态应立即消失 而不是跟随滚动后延迟消失

### 补充说明

tdesign-vue web版本

**Comment by pengYYYYY** [comment]
0.15.0 已修复
