### ISSUE TITLE
[Table] ts类型错误导致build失败

### ISSUE THREAD

**Issue by fxiangyi** [Tencent/tdesign-vue-next#570]
### tdesign-vue-next 版本

0.12.0

### 重现步骤

TS项目引入后，在build阶段失败

### 补充说明

类型定义
<img width="455" alt="wecom-temp-79a31ad3bdc293c66b83f1c87bae0545" src="https://user-images.githubusercontent.com/6951584/162877996-5ca98d3b-f58c-4228-b1c5-64c9afb5fa48.png">

部分方法定义，如
<img width="455" alt="wecom-temp-229df47fe9b73ac6a38aff9230795d83" src="https://user-images.githubusercontent.com/6951584/162878047-000e9099-b1e9-42c8-8a78-a4d1da3b269d.png">

类型不匹配（optional vs. required）

**Comment by chaishi** [comment]
没有看明白，辛苦提供一下 TS 建议方案

**Comment by chaishi** [comment]
报错结果，方便提供一下截图么

**Comment by pengYYYYY** [comment]
经过tdesign-vue-next-starter的测试，并没有报错的现象，也是严格模式，希望能够描述更清楚，issue先关闭，如有疑问可以reopen

**Comment by Alsmile** [comment]
编译是有些类型检测错误，只能在tsconfig.json里面加：
"skipLibCheck": true
