### ISSUE TITLE
form 表单检验rules trigger改成blur不生效

### ISSUE THREAD

**Issue by xiaoxiaoxiao123qwe** [Tencent/tdesign-vue-next#573]
### tdesign-vue-next 版本

0.12.0

### 重现链接

https://tdesign.woa.com/vue-next/components/form?tab=demo#%E4%B8%8D%E5%90%8C%E6%A0%A1%E9%AA%8C%E8%A7%84%E5%88%99%E7%9A%84%E8%A1%A8%E5%8D%95

### 重现步骤

该官网例子，用户名的字段 设置了blur触发方式，但是input失去焦点的时候并触发验证。
 account: [
    { required: true, message: '姓名必填', type: 'error' },
    {
      min: 2,
      message: '至少需要两个字',
      type: 'error',
      trigger: 'blur',
    },
  ],

### 期望结果

使trigger：'blur'生效,
或者注明使用注意事项

### 框架版本

"vue": "^3.2.31",

### 浏览器版本

谷歌 版本 100.0.4896.75（正式版本） （64 位）

### 系统版本

window10

### Node版本

v16.13.2

**Comment by xiaoxiaoxiao123qwe** [comment]
您好，您的邮件本小神已收到，游行已有数日，归心似箭->

**Comment by pengYYYYY** [comment]
新的form组件在重构阶段，得等等

**Comment by pengYYYYY** [comment]
@K1nZ 正在处理

**Comment by pengYYYYY** [comment]
0.15.0 已修复

**Comment by xiaoxiaoxiao123qwe** [comment]
您好，您的邮件本小神已收到，游行已有数日，归心似箭->
