### ISSUE TITLE
Anchor 组件，click 事件没有返回 mouse 原生事件

### ISSUE THREAD

**Issue by noxussj** [Tencent/tdesign-vue-next#574]
### tdesign-vue-next 版本

^0.11.2

![image](https://user-images.githubusercontent.com/37679301/162929435-6f710717-8853-4d0b-801e-4e00e59c0089.png)

![image](https://user-images.githubusercontent.com/37679301/162929589-3ed0eabf-857e-47bc-a000-fcbdae4738d7.png)

**Comment by pengYYYYY** [comment]
0.12.2已修复
