### ISSUE TITLE
第二次上传失败示例一直转圈，处理loading的逻辑有问题

### ISSUE THREAD

**Issue by jeffrey-bin** [Tencent/tdesign-vue-next#582]
### tdesign-vue-next 版本

能

### 重现链接

https://stackblitz.com/edit/angular-qzhawe?file=src%2Fdemo.vue

### 期望结果

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/23428596/163320957-38e91176-c32c-4970-b901-539be8c1413f.png">

### 实际结果
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/23428596/163320909-eb8725e9-ae35-4e62-b1ad-f0937d19b23b.png">

_No response_

**Comment by pengYYYYY** [comment]
0.13.0 已修复

**Comment by jeffrey-bin** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
