### ISSUE TITLE
[表格-可选中行] 点击单选按钮选择时报错，导致不能取消选择

### ISSUE THREAD

**Issue by baimule** [Tencent/tdesign-vue-next#583]
### tdesign-vue-next 版本

0.12.0

### 重现链接

https://tdesign.tencent.com/vue-next/components/table#%E5%8F%AF%E9%80%89%E4%B8%AD%E8%A1%8C%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

官网文档的代码直接复制下来，没有任何修改，点击表格单选按钮选中时控制台报错，且不可取消选中
![1649916806(1)](https://user-images.githubusercontent.com/51104090/163324977-7fdee9dc-e8bd-43da-9fe9-1d86db57ec56.png)
![1649916818(1)](https://user-images.githubusercontent.com/51104090/163324985-79416128-89ea-41a8-ac96-5c2233b4c601.png)
![1649916944(1)](https://user-images.githubusercontent.com/51104090/163325108-f122c07c-9802-43f4-b182-f6171af65db4.png)

**Comment by pengYYYYY** [comment]
0.13.0 已修复
