### ISSUE TITLE
[登录页]密码显示问题，输入框#suffix-icon插槽的点击事件不触发？

### ISSUE THREAD

**Issue by a1501255708** [Tencent/tdesign-vue-next#590]
### tdesign-vue-next-starter 版本

~0.11.2

**Comment by uyarn** [comment]
按描述是组件问题 transfer到组件库仓库处理

**Comment by pengYYYYY** [comment]
能否给一个复现的Stackblitz链接，描述不是很清楚， 插槽的点击事件应该是插槽内元素处理的

**Comment by a1501255708** [comment]
可能是我没描述清除,就是https://tdesign.tencent.com/starter/vue-next/#/login登录页面密码输入框的显示密码的图标的功能失效

**Comment by pengYYYYY** [comment]
那应该和这个https://github.com/Tencent/tdesign-vue-next/issues/556 重复了，升级一下包版本即可
