### ISSUE TITLE
[t-textarea] vue修改内容添加\n换行时，组件不会自动设置高度

### ISSUE THREAD

**Issue by Rhcla1m** [Tencent/tdesign-vue-next#597]
### tdesign-vue-next 版本

0.12.0

### 重现步骤
`<template>
<t-textarea v-model="vav" :autosize="true" />
<t-button theme="warning" shape="square" @click="test" />

</template>

<script setup>
let vav = ref('');

const test= () => {
  vav.value = ('\n\n\n\n');
}
</script>`

### 期望结果

textarea会自动撑开

### 实际结果

![1650274455(1)](https://user-images.githubusercontent.com/103930212/163789359-6a468da6-7a57-4f4a-bf57-dfbdf5cfd6a4.jpg)
![1650274485(1)](https://user-images.githubusercontent.com/103930212/163789623-7639e9b5-07ae-4371-a426-7bcbe8b3618e.jpg)
![1650274499(1)](https://user-images.githubusercontent.com/103930212/163789658-b123fd97-3381-469f-9249-560d38f12891.jpg)
图一是未点击时，图二是当点击后，会向textarea添加\n换行，但是textarea的高度并不会跟随撑开，而是以滚动条方式存在，需要手动点击进去，然后回车一次，它就会撑开，如图三所示

### 框架版本

vue3.2

### Node版本

0.12.0

**Comment by wenkm** [comment]
该问题是由于赋值后dom渲染未完成就获取并设置了高度。已经提交PR：https://github.com/Tencent/tdesign-vue-next/pull/613

**Comment by pengYYYYY** [comment]
0.13.0 已修复
