### ISSUE TITLE
[Select] 可创建新条目的选择器.创建后点击创建会多出空白值的一行，一直点击会一直创建新的

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#604]
### tdesign-vue-next 版本

0.10.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/select

### 重现步骤

![image](https://user-images.githubusercontent.com/20961979/163909620-ee8244eb-c12e-4eb1-8381-59e960c67ea5.png)
可创建新条目的选择器.创建后点击创建会多出空白值的一行，一直点击会一直创建新的

### 期望结果

自动创建后希望增加一行新的，清空之前的输入

### 实际结果

实际结果创建失败

**Comment by pengYYYYY** [comment]
可以升级到最新版本

**Comment by pengYYYYY** [comment]
<img width="349" alt="image" src="https://user-images.githubusercontent.com/35833812/163910763-0ac333af-4eda-40d7-a3d8-f08508bae2be.png">
解决过这个问题

**Comment by dennlian** [comment]
![image](https://user-images.githubusercontent.com/20961979/163910954-56a25ee6-cd08-4dbc-bc24-bbace3ecc4cc.png)
就是在演示版里面操作的
