### ISSUE TITLE
TreeSelect设置默认不展开节点、 TreeSelect设置父节点只可展开不可选中只能选中子节点

### ISSUE THREAD

**Issue by Code-Megalodon** [Tencent/tdesign-vue-next#606]
### 这个功能解决了什么问题

TreeSelect默认展开了节点 很乱 父节点不是想要选择的值

### 你建议的方案是什么

TreeSelect可设置属性默认展不展开、 TreeSelect可设置父节点不可选中只能选中子节点

**Comment by Godlike-meteor** [comment]
0.12.2 默认是不会产生这个问题的

**Comment by Code-Megalodon** [comment]
> 0.12.2 默认是不会产生这个问题的
我的会 初始值为[] 请求接口赋值之后都会默认展开节点
