### ISSUE TITLE
TreeSelect透传会警告

### ISSUE THREAD

**Issue by Code-Megalodon** [Tencent/tdesign-vue-next#608]
### tdesign-vue-next 版本

0.12.2

### 重现步骤

:tree-props="{ valueMode: 'onlyLeaft' }"

### 期望结果

无警告

### 实际结果

[Vue warn]: Invalid prop: custom validator check failed for prop "valueMode". 
all、parentFirst都没有问题
只有onlyLeaft会提示这个

**Comment by Godlike-meteor** [comment]
onlyLeaf ，Tree 组件文档有误 @pengYYYYY

**Comment by chaishi** [comment]
请问，文档的哪里，显示的是 `onlyLeaft`

**Comment by Code-Megalodon** [comment]
> 请，文档的哪里，显示文字`onlyLeaft`

看Tree文档的valueMode

**Comment by pengYYYYY** [comment]
onlyLeaf，不是onlyLeaft
