### ISSUE TITLE
关于本地dev的问题

### ISSUE THREAD

**Issue by whylost** [Tencent/tdesign-vue-next#61]
- 样式链接问题
- vite依赖不存在 等

我不知道是我个人的问题, 还是项目搭建的不够严谨, 或者官方可以给出一份相应的如何参与贡献地文档

我觉的 fork 后 
 直接 `yarn` / `pnpm install` / `npm install` 
 然后运行相应的命令(如 `npm run start` )就可以启动项目, 才是一种让人愉悦的体验

**Comment by pengYYYYY** [comment]
- 我们使用了submodule 来管理common 样式和逻辑，需要安装submodule，已经对 npm run start 进行相关初始化集成。
- vite依赖不存在的问题应该是之前使用了workspaces，npm 版本导致的问题，已经revert。
以上处理的PR: https://github.com/Tencent/tdesign-vue-next/pull/60

感谢提意见喔

**Comment by whylost** [comment]
感谢及时修正

**Comment by wfq1095745112** [comment]
![image](https://user-images.githubusercontent.com/11973347/160825158-2d781a33-a9b1-431a-95ff-4ad487a3fce8.png)
npm run start  init命令失败
