### ISSUE TITLE
[Input] 数据类型与初始化设置的类型不一致

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#610]
### tdesign-vue-next 版本

最新版

### 重现步骤

input 事件发生后，值类型变为 String
- before: ![image](https://user-images.githubusercontent.com/28809916/163976629-742d86e7-5579-4457-b367-5225c1595a07.png)
- after: ![image](https://user-images.githubusercontent.com/28809916/163976655-f5336ca7-0da2-44ef-960d-8c1137fca2d7.png)

### 期望结果

数据类型保持一致

**Comment by pengYYYYY** [comment]
设计如此，01 在input里面肯定是以字符串的形式展示的喔

**Comment by Crazymuyang** [comment]
可能我们需要封装一个限定只能输入数字的组件，比如 td 里的 InputNumber
