### ISSUE TITLE
[Table] 表格列宽自适应table-layout: auto，希望能根据整列内容的最大宽度自适应，包括表头

### ISSUE THREAD

**Issue by wmhost** [Tencent/tdesign-vue-next#615]
### 这个功能解决了什么问题

列宽只根据表格单元格内容自适应时，会出现因列宽不足导致表头换行的情况
<img width="777" alt="image" src="https://user-images.githubusercontent.com/34067541/164147625-eb2d8878-055e-49f5-88e8-953417caab17.png">

### 你建议的方案是什么

列宽自适应加上表头的宽度计算

**Comment by chaishi** [comment]
表格全部属于原生 table 属性，原生支持的，Table 组件都支持。

此处属于使用不当。此处理解为在不换行的情况下，希望有个宽度根据内容自适应。
这个简单，浏览器 table 元素自带支持这种特性，无需单独开发。方法如下，

**直接给 `table` 元素，注意，是 `<table>` 元素，添加一个较大的宽度，比如：`1200px`。观察表格列宽的变化。**

还可以调整 column.width 调整相关列宽（注意，此时的宽度，浏览器会按比例分配给各个列宽。如果希望完全内容自适应，就不要自己设置 column.width）
