### ISSUE TITLE
table组件的columns属性如果不写的话，我应该怎么样渲染表格每一列的内容呢

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#617]
### 这个功能解决了什么问题

我看文档里全部都是用的:columns="columns"的写法，而且columns不是必传的，如果我不使用这个方法的话，应该怎么渲染每一列的数据呢，有没有类似
`<t-table :data="tableData">
    <t-table-column prop="date" label="Date" width="180" />
    <t-table-column prop="name" label="Name" width="180" />
    <t-table-column prop="address" label="Address" />
  </t-table>`
这种写法呢？

### 你建议的方案是什么

文档里没有看到，我不知道应该怎么写，希望有人指点一下

**Comment by pengYYYYY** [comment]
没有您说的这种方式，我们使用的是options数据驱动的方式，并非描述的插槽的方式。数据驱动的方式有什么困扰吗？

**Comment by sunjiesama** [comment]
> 没有您说的这种方式，我们使用的是options数据驱动的方式，并非描述的插槽的方式。数据驱动的方式有什么困扰吗？
因为现在业务需求是每个单元格内容都是自定义的，按照文档的写法就是说我要先把:columns定义好，然后在用插槽的方式在去定义每一列的内容，请问是这个意思吗？这样的话感觉有点。。。。=_=

**Comment by sunjiesama** [comment]
> 没有您说的这种方式，我们使用的是options数据驱动的方式，并非描述的插槽的方式。数据驱动的方式有什么困扰吗？

因为现在业务需求是每个单元格内容都是自定义的，按照文档的写法就是说我要先把:columns定义好，然后在用插槽的方式在去定义每一列的内容，请问是这个意思吗？这样的话感觉有点。。。。=_=

**Comment by chaishi** [comment]
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/11605702/164362075-9230876e-21f4-4a52-8c8c-993c2aac3cda.png">

**Comment by chaishi** [comment]
没有 `t-table-column`，只有上面提到的 4 种方式

**Comment by sunjiesama** [comment]
好的，非常感谢
