### ISSUE TITLE
table的列的自定义样式会被表格内置样式覆盖

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#619]
### tdesign-vue-next 版本

0.12.2

### 重现步骤

通过baseTableCol的calssName属性给表格列添加的类名被覆盖了。

这是我的添加列类名的写法
![image](https://user-images.githubusercontent.com/54022918/164170511-4e7ed9dd-2b32-4f59-b817-775b2cd064cd.png)

在控制台可以看到被.t-table th, .t-table td覆盖掉了
![image](https://user-images.githubusercontent.com/54022918/164170646-4275bea9-6606-46f9-9d08-a81b9a78a6c9.png)

### 期望结果

样式生效

### 实际结果

样式未生效

### 补充说明

如果是我写法问题的话，请指点一下应该怎么写，谢谢了

**Comment by pengYYYYY** [comment]
是用来tailwindcss 嘛，提升一下css样式的优先级吧
