### ISSUE TITLE
[Dialog] 在ts中使用DialogPlugin.alert会报confirmBtn错误

### ISSUE THREAD

**Issue by liu3594211** [Tencent/tdesign-vue-next#625]
### tdesign-vue 版本

0.40.3

### 重现步骤

在vue3.2+ts中使用DialogPlugin.alert报错，Argument of type '{ header: string; body: string; confirmBtn: any; onConfirm: ({ e }: { e: MouseEvent; }) => void; onClose: ({ e, trigger }: DialogCloseContext) => void; }' is not assignable to parameter of type 'Omit<DialogOptions, "confirmBtn">'.
  Object literal may only specify known properties, and 'confirmBtn' does not exist in type 'Omit<DialogOptions, "confirmBtn">'

**Comment by pengYYYYY** [comment]
0.14.0 已修复
