### ISSUE TITLE
[table] drag-sort 配置文档和源码不匹配，无法正常使用

### ISSUE THREAD

**Issue by zWeng33** [Tencent/tdesign-vue-next#626]
### tdesign-vue-next 版本

0.12.2

### 重现链接

https://stackblitz.com/edit/angular-qt8z3d-zuf9ze

row-handler 配置缺失，配置为 row/col 拖拽时，无法正常工作
官方文档中的示例代码可重现

**Comment by chaishi** [comment]
出现这个问题的原因是：文档 `row-handler` 先发布了，但是代码版本还没发布。

我找人发布一下新版本

**Comment by pengYYYYY** [comment]
0.13.0 已修复
