### ISSUE TITLE
table组件 height="100%"不生效

### ISSUE THREAD

**Issue by sunjiesama** [Tencent/tdesign-vue-next#627]
### 这个功能解决了什么问题

在table组件写上height="100%"属性后，表格内容依然超出了父元素，在控制台查看是因为，height=“100%”属性作用在了.t-table__content这个元素上，然而这个元素外层还有一个.t-table的元素，.t-table超出了父元素导致.t-table__content内容溢出
![image](https://user-images.githubusercontent.com/54022918/164354098-d72f40bd-76ef-4f62-adce-fb210d8f5d80.png)

### 你建议的方案是什么

我不知道这属于bug还是我的写法有问题，所以来求助一下，看到问题请指点一下，非常感谢

**Comment by chaishi** [comment]
`height` 属性用来设置表格内容高度。
如果希望外层高度 100%，请尝试使用 `style="height: 100%"`

**Comment by sunjiesama** [comment]
> `height` 属性用来设置表格内容高度。 如果希望外层高度 100%，请尝试使用 `style="height: 100%"`

按照这个方式写之后，表格滚动条消失了，overflow-auto也无效

**Comment by chaishi** [comment]
直接描述现象，很难帮你解决问题，发一个示例代码，我们看看你想要的效果吧

**Comment by sunjiesama** [comment]
> 直接描述现象，很难帮你解决问题，发一个示例代码，我们看看你想要的效果吧

非常感谢，我已经找到方法了，你把这个问题issues关闭吧
