### ISSUE TITLE
Table斑马纹开启之后表头显示颜色不正常

### ISSUE THREAD

**Issue by Code-Megalodon** [Tencent/tdesign-vue-next#636]
### tdesign-vue-next 版本

0.12.2

### 期望结果

![image](https://user-images.githubusercontent.com/54198396/164470702-6caa740d-8b2e-4930-b51e-4474173b9759.png)

### 实际结果

![image](https://user-images.githubusercontent.com/54198396/164470800-4a6923b3-cc8c-4523-9542-c369068bd74d.png)

**Comment by chaishi** [comment]
收到，我们处理下

**Comment by Code-Megalodon** [comment]
> 收到，我们处理下

补充一下 是在Table出现滚动条时才会这么显示

**Comment by chaishi** [comment]
下个版本会修复

**Comment by chaishi** [comment]
关注 https://github.com/Tencent/tdesign-vue-next/issues/682，会在这里，一并处理掉
