### ISSUE TITLE
[t-menu] expand-type=popup 无作用

### ISSUE THREAD

**Issue by fengxianqi** [Tencent/tdesign-vue-next#644]
### 重现链接
https://stackblitz.com/edit/angular-otuwlu-xff1y4?file=src%2Fdemo.vue

### 重现步骤
`<t-menu expand-type="popup"></t-menu>` 和 `<t-menu expand-type="normal"></t-menu>`
的表现效果是一样的，即`expand-type="popup"`属性没有生效。

### 期望结果
vue版本的效果：https://stackblitz.com/edit/angular-kqnx7y?file=src%2Fdemo.vue
（当然它也有bug，expand-type="popup"时，箭头应该是左右方向）

### 实际结果
https://stackblitz.com/edit/angular-otuwlu-xff1y4?file=src%2Fdemo.vue

| Environment | Info |
|---|---|
| 相关版本 | 0.13.0 |
| 框架版本 / 基础库版本 | Vue(3.2.26) |
| 系统、浏览器 | chrome(99.0.4844.84) |
| Node版本 | v16.14.2 |

**Comment by pengYYYYY** [comment]
感兴趣的话可以 https://github.com/Tencent/tdesign-vue-next/pull/643 顺便修复一下
