### ISSUE TITLE
[table] table拖拽和loading组合使用时，拖拽失效

### ISSUE THREAD

**Issue by zWeng33** [Tencent/tdesign-vue-next#648]
### tdesign-vue-next 版本

0.13.0

### 重现链接

https://stackblitz.com/edit/angular-aapunh

### 重现步骤

setTimeout模拟获取数据可重现，注释掉相关代码默认loading为false时拖拽正常

### 框架版本

Vue(3.2.31)

### 浏览器版本

Chrome(100.0.4896.127)

### 系统版本

Windows(11)

**Comment by hgjinfan** [comment]
Duplicate of #581

**Comment by hgjinfan** [comment]
Duplicate of #581 
实质上是一样的问题
loading变化会触发table_content 的重新渲染，这个设计总感觉有点问题
https://github.com/Tencent/tdesign-vue-next/blob/ec53e0600c1bfd21be91c1406751bc74710401c2/src/table/hooks/useDragSort.ts#L143
https://github.com/Tencent/tdesign-vue-next/blob/ec53e0600c1bfd21be91c1406751bc74710401c2/src/table/hooks/useDragSort.ts#L62
可以看到这里件会去拿table_content里面的tbody作为可拖拽容器去注册拖拽事件，但是loading态的变化会触发table_content的重新渲染那么之前的tbody拖拽容器的引用就已经丢失了，拖拽就失效了

**Comment by chaishi** [comment]
收到，我们处理下

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/694

**Comment by pengYYYYY** [comment]
0.14.1 已修复
