### ISSUE TITLE
[cascader] 未正确显示相关叶子节点

### ISSUE THREAD

**Issue by psaren** [Tencent/tdesign-vue-next#649]
### tdesign-vue-next 版本

0.12.2

### 重现链接

https://stackblitz.com/edit/angular-v24sji-y3wdow?file=src%2Fdemo.vue

### 重现步骤

<img width="704" alt="image" src="https://user-images.githubusercontent.com/18643034/164965796-311e22fe-27c6-454c-a915-40aa09111f22.png">
节点1.1.2是没有叶子节点的，但是在展示了1.1.1的叶子节点后，再去点击节点1.1.2，节点1.1.1的叶子节点没有消失

### 期望结果

正确展示叶子节点

### 实际结果

叶子节点展示错误

**Comment by pengYYYYY** [comment]
0.14.0 已修复
