### ISSUE TITLE
[tree] 在有过滤，且 filter 不为 null 的时候点击节点标签左侧箭头没法折叠

### ISSUE THREAD

**Issue by yangjunjun** [Tencent/tdesign-vue-next#651]
### tdesign-vue-next 版本

0.13.0

### 重现链接
官方“可过滤的树”例子就可以重现  https://tdesign.tencent.com/vue-next/components/tree?tab=demo#%E5%8F%AF%E8%BF%87%E6%BB%A4%E7%9A%84%E6%A0%91

另外的重现地址： https://stackblitz.com/edit/angular-emtekf

### 重现步骤

1. 点击节点左侧按钮，可以正常折叠子节点
2. filter 输入框输入1
3. 点击节点左侧按钮，无法正常折叠子节点

### 期望结果

当 filter 有值时，可以正常折叠子节点

### 实际结果

当 filter 有值时，不可以折叠子节点

**Comment by TabSpace** [comment]
按照目前的UI，过滤状态下，路径节点锁定为展开状态。
否则还原过滤后，无法判断节点展开为过滤导致还是原始状态。
设计如此。

**Comment by ardor-zhang** [comment]
目前组件存在一个 bug 和一个待优化点
- bug: 只要 filter 有值或者延迟赋值（如官方文档示例），树就不能再折叠了（即便清空 filterText）
- 待优化点：触发 filter 时（filterText 值为非空时）树无法折叠

当前结论：
- bug 目前可修复
- 待优化的点需讨论，因为当前的设计是，在 filter 存在的情况下，节点展开且锁定，所以需要在设计上做优化而非编码

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/1241 过滤交互移到另外一个issue讨论

**Comment by pengYYYYY** [comment]
0.18.0 已修复节点锁定bug
