### ISSUE TITLE
[Popup] 动态设置 trigger 后所有 trigger 触发类型都会响应

### ISSUE THREAD

**Issue by HQ-Lin** [Tencent/tdesign-vue-next#654]
### tdesign-vue-next 版本

0.13.0

### 重现链接

https://stackblitz.com/edit/angular-awcqry?file=src%2Fdemo.vue

### 重现步骤

初始化使用hover触发，之后改成click后，hover依然触发popup内容

### 期望结果

以最后设置 trigger 触发方式为准

**Comment by pengYYYYY** [comment]
0.14.0 已修复
