### ISSUE TITLE
[Form] 设置form-item的help属性，输入校验通过后字体颜色变成了绿色

### ISSUE THREAD

**Issue by AngleMi** [Tencent/tdesign-vue-next#655]
### tdesign-vue-next 版本

0.12.2版本以上

### 重现链接

https://0_12_2-tdesign-vue-next.surge.sh/vue-next/components/form

### 重现步骤

tdesign-vue-next 0.12.2版本以上 设置form-item的help属性，输入校验通过后字体颜色变成了绿色，理论上help文本的颜色不会发生改变，之前版本的help属性dom结构的class="t-form__help" ，0.12.2版本以上变成了class="t-input__extra"

### 期望结果

 设置form-item的help属性，输入校验通过help文本颜色不发生变化

### 实际结果

 设置form-item的help属性，输入校验通过后字体颜色变成了绿色

**Comment by pengYYYYY** [comment]
0.14.0 已修复
