### ISSUE TITLE
【t-table】表头吸顶、fixed：right样式重叠问题

### ISSUE THREAD

**Issue by xiaominminmin** [Tencent/tdesign-vue-next#661]
### tdesign-vue-next 版本

0.13.0

### 重现链接

https://codesandbox.io/s/crazy-mestorf-rf2ydb

### 重现步骤

demo中有体现

### 期望结果

修复表头吸顶、fixed：right样式重叠问题

### 实际结果

表头吸顶目前只兼容top = 0
列表两列设置 fixed：right 样式会发生重叠

### Node版本

v14.19.0

**Comment by pengYYYYY** [comment]
0.14.1 已修复

**Comment by chaishi** [comment]
请升级版本，尝试
