### ISSUE TITLE
[Menu] width属性设置数组无效

### ISSUE THREAD

**Issue by RionZZZ** [Tencent/tdesign-vue-next#663]
### tdesign-vue-next 版本

0.13.0

### 重现步骤

在t-menu组件内设置width属性['300px', '100px']，实则无效，只会取100px作为展开时宽度，收起还是默认64px

### 期望结果

width设置数组类型生效

### 实际结果

不生效

### 框架版本

3.2.25

**Comment by xiaosansiji** [comment]
应该实现 API 文档中的数组能力：
![image](https://user-images.githubusercontent.com/7600149/168538617-9b9e593e-2477-438f-9aa7-04f016a0de5a.png)
https://tdesign.tencent.com/vue-next/components/menu?tab=api

**Comment by LeeJim** [comment]
我修复一下

**Comment by pengYYYYY** [comment]
0.15.0 已修复
