### ISSUE TITLE
[t-slider] max和min无法通过ref动态修改

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#664]
### tdesign-vue-next 版本

0.13.0

### 重现步骤

![image](https://user-images.githubusercontent.com/10460238/165448694-fa6960c4-c976-444b-aaf8-d75d77f99d45.png)
![image](https://user-images.githubusercontent.com/10460238/165448462-a6f47d10-eb81-4231-9717-da8b545207d2.png)
![image](https://user-images.githubusercontent.com/10460238/165448671-b6798049-4f5d-47be-b0d8-72e4e1d102ef.png)

### 期望结果

min和max属性能根据ref变化动态变化

### 实际结果

从图片看出，min和max，2秒后改变后，组件最大最小值依然是旧值

**Comment by pengYYYYY** [comment]
@Github-Chrislee 处理中

**Comment by pengYYYYY** [comment]
0.14.1 已修复
