### ISSUE TITLE
[table] 展开收起功能，若使用expandedRow的插槽写法无法点击展开收起

### ISSUE THREAD

**Issue by cowblue** [Tencent/tdesign-vue-next#668]
### tdesign-vue-next 版本

0.13.0

### 重现链接

https://0_13_0-tdesign-vue-next.surge.sh/vue-next/components/table#%E5%8F%AF%E5%B1%95%E5%BC%80%E5%92%8C%E6%94%B6%E8%B5%B7%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

将expandedRow改为插槽形式

### 期望结果

可以点击展开收起

### 实际结果

无法点击展开收起

**Comment by chaishi** [comment]
最新版本为 0.14.0，我刚刚本地跑了一下代码，插槽也能正常展开/收起

https://user-images.githubusercontent.com/11605702/166217657-e28f63b8-4950-4912-a6d7-ffea5c7f96ed.mov

**Comment by chaishi** [comment]
由于 issue 提到的问题，无法在最新版本复现，且没有提供能够复现问题的 Demo，
因此，关闭 issue

如果可以再次提供复现问题的 Demo，可以 reopen this issue
