### ISSUE TITLE
[form] :class=“['a']”

### ISSUE THREAD

**Issue by zhongguodong** [Tencent/tdesign-vue-next#671]
### tdesign-vue-next 版本

最新版本

### 期望结果

不是应该出现一个的吗？

### 实际结果

页面渲染DOM节点，出现两个a a了

**Comment by xiaosansiji** [comment]
https://stackblitz.com/edit/angular-hapmeq @zhongguodong 方便来个例子帮助理解下你的用法不？

**Comment by zhongguodong** [comment]
https://stackblitz.com/edit/angular-hapmeq-zjyf6z?embed=1&file=src/demo.vue

**Comment by zhongguodong** [comment]
@LeeJim :class="['a']"，按F12，那那个form表单上的节点，出现了两个a了，这样属于bug吗？

**Comment by zhongguodong** [comment]
> https://stackblitz.com/edit/angular-hapmeq @zhongguodong 方便来个例子帮助理解下你的用法不？

https://stackblitz.com/edit/angular-hapmeq-zjyf6z?embed=1&file=src/demo.vue
:class="['a']"，按F12，那那个form表单上的节点，出现了两个a了，这样属于bug吗？有时，自己调试了，让人很奇怪，无端端多了一个出来

**Comment by zhongguodong** [comment]
@xiaosansiji 怎么不回复了？发现问题没？
![image](https://user-images.githubusercontent.com/10219953/167232352-d5891035-5332-4b3b-8b77-1119bb40040f.png)

**Comment by pengYYYYY** [comment]
@k1nz 处理中

**Comment by pengYYYYY** [comment]
0.14.2 已修复
