### ISSUE TITLE
[Table] 迁移 Vue2 的功能：拖拽调整列宽、表头吸顶、表尾吸底、横向滚动条吸底、分页器吸底

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#682]
### tdesign-vue-next 版本

最新版本

### 重现步骤

1. Table 表尾吸底（含横向滚动条吸底）
https://github.com/Tencent/tdesign-vue/pull/810

2. Table 拖拽调整列宽
https://github.com/Tencent/tdesign-vue/pull/757

3. 缺陷处理
https://github.com/Tencent/tdesign-vue/pull/860

4. 拖拽修复
https://github.com/Tencent/tdesign-vue/pull/870

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/1011

**Comment by pengYYYYY** [comment]
0.16.1 已修复
