### ISSUE TITLE
[EnhancedTable] 树状表格内容与分页兼容问题

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#708]
### tdesign-vue-next 版本

0.14.0

### 重现步骤

1.分页pageSize设为5；
2.表格内容通过树状展开；
3.如果展开后子数据无children计为一条数据，展开后子数据仍存在子数据不计为一条数据（猜想）；

### 期望结果

表格数据只统计最顶层父级数据数量，对应其pageSize。如：初始化有3条数据（最顶层父级），展开后有30条，应该不算超出pageSize大小，不作隐藏处理。

### 实际结果

![图片](https://user-images.githubusercontent.com/19170277/166890946-63743746-5698-406f-92dd-fa2386762533.png)
（初始化数据）
![图片](https://user-images.githubusercontent.com/19170277/166891180-94037653-2b77-4639-b30c-2f2bdf68bdcf.png)
（展开后）
![图片](https://user-images.githubusercontent.com/19170277/166891471-ddc9933c-5433-4083-85dc-385e5454c0e1.png)
（实际上下面有很多数据，都因为pageSize而被隐藏）

**Comment by chaishi** [comment]
目前的处理，应该就是顶层分页才对，辛苦提供 Demo

**Comment by chaishi** [comment]
官网的分页效果，就是根据第一层进行的分页

如果长时间没有提供可以复现问题的 Demo，issue 会被关闭

**Comment by Waynefong** [comment]
> 官网的分页效果，就是根据第一层进行的分页
> 
> 如果长时间没有提供可以复现问题的 Demo，issue 会被关闭

已经发现问题了，组件没有问题，是我数据处理上写的有问题没发现
