### ISSUE TITLE
[Dropdown] 下拉菜单点击后不自动关闭

### ISSUE THREAD

**Issue by arieslee** [Tencent/tdesign-vue-next#711]
### tdesign-vue-next 版本

0.14.0

### 重现链接

https://0_14_0-tdesign-vue-next.surge.sh/vue-next/components/dropdown

### 重现步骤

任意一个dropdown下拉菜单点击后都不自动关闭，控制台中出现错误
```
Uncaught TypeError: n.handleClose is not a function
    at Proxy.handleMenuClick (index.8ce5df66.js:17)
    at Proxy.handleItemClick (index.8ce5df66.js:17)
    at Kr (index.8ce5df66.js:4)
    at Xi (index.8ce5df66.js:4)
    at HTMLDivElement.n (index.8ce5df66.js:8)
handleMenuClick @ index.8ce5df66.js:17
handleItemClick @ index.8ce5df66.js:17
Kr @ index.8ce5df66.js:4
Xi @ index.8ce5df66.js:4
n @ index.8ce5df66.js:8

```

### 期望结果

点击后自动关闭，控制台中不报错

### 框架版本

3.2.31

### 浏览器版本

Microsoft Edge 版本 92.0.902.78 (官方内部版本) (x86_64)

### 系统版本

MacOS(10.15.7)

### Node版本

v14.19.1

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/691 已修复

**Comment by pengYYYYY** [comment]
0.14.1 已修复
