### ISSUE TITLE
[EnhancedTable] 收起/展开的图标可以支持自定义吗

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#717]
### 这个功能解决了什么问题

自定义收起/展开图标

### 你建议的方案是什么

像 Table 组件 的 `expand-icon` 属性一样

**Comment by AngleMi** [comment]
+1

**Comment by chaishi** [comment]
可以

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/746

**Comment by pengYYYYY** [comment]
0.14.2 已修复
