### ISSUE TITLE
[TimePicker] clearable 属性不生效问题

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#722]
### tdesign-vue-next 版本

最新版

### 重现链接

https://codesandbox.io/s/bug-td-select-showarrow-cf9ucw?file=/src/App.vue

### 重现步骤

- [TimeRangePicker] 初始值为空数组时，clearable 不生效；
- [TimePicker] 初始值为空字符串时，clearable 不生效；

### 期望结果

鼠标上移，显示关闭icon，可清除值

**Comment by pengYYYYY** [comment]
0.14.2 已修复
