### ISSUE TITLE
[Popup] 期望可以新增Popup一个预加载的props或方法

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#728]
### 这个功能解决了什么问题

1.一个后台管理系统登录后，需要显示账号所属部门；
2.因为业务需求，账号可以切换不同的部门查看该部门的数据，所以当前用了popup和tree结合；
3.部门的名称会取当前active的treeItem的值；
4.但是由于popup在页面加载后没有添加dom，所以tree是找不到的，只有在点击过popup显示后才能获取到tree的值。
![企业微信截图_20220509140936](https://user-images.githubusercontent.com/19170277/167350429-bef9625f-25e1-4ac0-b9e9-f762eb6f885e.png)
（页面刚加载时）
![企业微信截图_20220509141002](https://user-images.githubusercontent.com/19170277/167350488-1f5f993f-d59f-4b25-84ed-b7d795076c59.png)
（popup初始化后）

### 你建议的方案是什么

希望添加一个类似destroyOnClose一样的配置项，initOnMounted之类的。

**Comment by xiaosansiji** [comment]
Popup 可以通过 `visible/onVisibleChange ` 自己控制显隐，我理解这里你可以自己在 Popup 展开或收起时给目标变量赋值，不依赖 DOM 取值

**Comment by Waynefong** [comment]
> Popup 可以通过 `visible/onVisibleChange ` 自己控制显隐，我理解这里你可以自己在 Popup 展开或收起时给目标变量赋值，不依赖 DOM 取值

我想过这个做法。这样就需要在页面加载后显示隐藏一下。会有一闪而过的视觉效果。

**Comment by pengYYYYY** [comment]
可以拿个辅助的div。render一下再销毁掉，这样就能拿到数据了。内部讨论过后，应该不会加这个API了。

**Comment by Waynefong** [comment]
> 可以拿个辅助的div。render一下再销毁掉，这样就能拿到数据了。内部讨论过后，应该不会加这个API了。

好的，那我自己处理一下
