### ISSUE TITLE
[Table] 排序功能， 鼠标放在排序图标及点击排序图标会有文字提示，无法隐藏这些提示

### ISSUE THREAD

**Issue by huangzaizai** [Tencent/tdesign-vue-next#736]
### tdesign-vue-next 版本

0.14.1

**Comment by chaishi** [comment]
这是一个 feature，是否需要支持隐藏提示？

**Comment by huangzaizai** [comment]
是的，这个对于我们来说比较重要。  因为这些提示信息让人感觉内容很繁琐，不够简洁。 希望贵公司能够增加这个功能。

**Comment by chaishi** [comment]
API 规划：
- `PrimaryTable` 新增 `hideSortTips`，用于控制 单个表格 是否显示文本提示
- 全局配置新增 `hideSortTips`，用于全局控制 所有表格 是否显示文本提示

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/746

https://user-images.githubusercontent.com/11605702/167694684-4fe7cc4f-36de-477a-8c02-9439ef6dd66e.mov

**Comment by pengYYYYY** [comment]
0.14.2 已修复
