### ISSUE TITLE
[pagination] show-jumper不知道如何触发，完全无效

### ISSUE THREAD

**Issue by RionZZZ** [Tencent/tdesign-vue-next#737]
### tdesign-vue-next 版本

0.14.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/pagination?tab=demo#%E5%B8%A6%E5%BF%AB%E9%80%9F%E8%B7%B3%E8%BD%AC%E7%9A%84%E5%88%86%E9%A1%B5

### 期望结果

填入页面会触发change事件

### 实际结果

填写无效，无论失焦还是enter，没反应

**Comment by pengYYYYY** [comment]
showJumper 设置为true就可以了，这个demo可以设置
<img width="921" alt="image" src="https://user-images.githubusercontent.com/35833812/167536074-8d36d5e7-b6a3-40cd-a3f8-e4f1357c5bef.png">

**Comment by pengYYYYY** [comment]
了解了，这个属于input-number的问题，已经修复了

**Comment by pengYYYYY** [comment]
0.14.2 已修复
