### ISSUE TITLE
[Slider组件] 设置一些参数不生效，更改不了toolTip 提示信息

### ISSUE THREAD

**Issue by Rkatsiteli** [Tencent/tdesign-vue-next#741]
### tdesign-vue-next 版本

0.14.1

### 重现链接

多测试下就能发现

### 重现步骤

 <Slider
          class="gradient"
          :step="1"
          :max="128"
          :min="0"
          v-model="defaultRange"
          :tooltipProps="{
            placement: 'top',
            overlayClassName: 'tool-tip-style',
            theme: 'default',
            content: 'test',
          }"
        />

theme 
content 并不会生效

### 期望结果

期待默认值 tooltipProps   theme 恢复背景，允许toolTip 自定义内容

### 实际结果

实际结果并不友好

### Node版本

v16.15.0

**Comment by pengYYYYY** [comment]
@ChrisLee0211 处理中

**Comment by pengYYYYY** [comment]
0.14.2 已修复

**Comment by Rkatsiteli** [comment]
> 

版本已更新，但并不生效，不确定是操作的当，如下代码块

想要的功能，
1、tooltipProps  theme default为黑色背景，也就是ToolTip 可设置背景块
2、tooltipProps 支持内容设置，如: 滑块ToolTip显示百分比 "20%"



`<Slider
          class="gradient"
          :step="1"
          :max="128"
          :min="0"
          v-model="defaultRange"
          :tooltipProps="{
            placement: 'top',
            overlayClassName: 'tool-tip-style',
            theme: 'primary',
          }"
        />`

**Comment by pengYYYYY** [comment]
0.15.1 已修复

**Comment by Rkatsiteli** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
