### ISSUE TITLE
[按需引用]unplugin-vue-components 失效

### ISSUE THREAD

**Issue by Rkatsiteli** [Tencent/tdesign-vue-next#743]
### tdesign-vue-next 版本

0.14.1

### 重现链接

可直接使用就会浮现该问题

### 重现步骤

1、按照官方操作文档进行配置
2、配置完成后，生成两个问题，但文件内容导入组件包路劲是错误的
<img width="1275" alt="企业微信截图_e6b181a9-b0d2-4d86-ba65-ebba8634e914" src="https://user-images.githubusercontent.com/16810179/167596656-3c355d50-05f0-47ac-9cca-89cbe8609117.png">

### 期望结果

期望按照步骤允许按需加载要求

### 实际结果

实际结果不可用

### 框架版本

Vue@3.2.33

### Node版本

v16.15.0

**Comment by pengYYYYY** [comment]
这是nuxt3嘛

**Comment by Rkatsiteli** [comment]
> nuxt3

不是哒

**Comment by uyarn** [comment]
unplugin-vue-components 版本是多少

**Comment by Rkatsiteli** [comment]
> 

版本是 [0.19.5](https://www.npmjs.com/package/unplugin-vue-components/v/0.19.5)

**Comment by pengYYYYY** [comment]
可以补充一下使用方式嘛，目前使用并无问题，先close了
