### ISSUE TITLE
[Dialog] 希望新增一些全局配置项

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#747]
### 这个功能解决了什么问题

业务需要全系统的dialog都要满足没有closebtn，不可以点击蒙层关闭，不可以通过键盘esc关闭。

### 你建议的方案是什么

在t-config-provider中新增dialog关于这方面的配置项

**Comment by pengYYYYY** [comment]
收到

**Comment by xiaosansiji** [comment]
除了 configProvider 对模板类用法进行全局配置，可能还要支持 plugin 用法，类似：https://github.com/Tencent/tdesign-vue/pull/795

**Comment by pengYYYYY** [comment]
增加全局配置相关的需求应该会是一个长期的需求，统一搬到https://github.com/Tencent/tdesign-vue-next/issues/848
