### ISSUE TITLE
[MessagePlugin] onDurationEnd报错

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#748]
### tdesign-vue-next 版本

0.14.0

### 重现步骤

![图片](https://user-images.githubusercontent.com/19170277/167750069-c2de2982-8241-46b1-8177-69c0cea1f104.png)
（报错）
![图片](https://user-images.githubusercontent.com/19170277/167750094-8b03f262-cd59-40ef-968e-5a1fe812965d.png)
（老版本这样写是没问题的，更新后报错）

**Comment by pengYYYYY** [comment]
0.14.1 已修复，可以升级一下

**Comment by Waynefong** [comment]
![图片](https://user-images.githubusercontent.com/19170277/167758350-ddc20477-9ed4-4848-8103-9c25ffdcacb8.png)
（升级过了，还是依然报错）
![图片](https://user-images.githubusercontent.com/19170277/167758387-2f414ac1-4cb9-492b-a0c0-963b5a32d76f.png)

**Comment by Waynefong** [comment]
> 0.14.1 已修复，可以升级一下

![图片](https://user-images.githubusercontent.com/19170277/167758951-65a7ab43-72ac-4e07-aba4-81a53a82ba49.png)
（已经升级了，依然报错）
![图片](https://user-images.githubusercontent.com/19170277/167759018-ae576a05-b6be-4e9d-9f8a-d345b4370f73.png)
