### ISSUE TITLE
双层导航菜单演示错误

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#75]
**Describe Framework**

- [ ] tdesign-vue
- [x] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

vue3版本：
![image](https://user-images.githubusercontent.com/30982989/147540333-f85a55d1-2a8c-4c2c-8a0e-bf40ee08d8c7.png)
vue2版本：
![image](https://user-images.githubusercontent.com/30982989/147540344-f84bc0bc-c7eb-439b-b1b0-90a5db19037e.png)

**Comment by pengYYYYY** [comment]
已收到，会尽快处理，如果有兴趣的话，你也可以向我们提PR
