### ISSUE TITLE
[Steps] v-model下readonly不起作用

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#753]
### tdesign-vue-next 版本

0.14.1

### 重现链接

https://stackblitz.com/edit/angular-ex7key?file=src%2Fdemo.vue

### 重现步骤

![图片](https://user-images.githubusercontent.com/19170277/167796478-fda27734-355d-4676-b140-8514264a6a13.png)
（v-model的情况下，设置了readonly依然可以点击步骤条跳转，v-model:current和:current没问题）
![图片](https://user-images.githubusercontent.com/19170277/167796696-c7b454fb-a329-4d47-9831-09a329f71fec.png)
（文档是写的可以使用v-model，开发时偶然发现的bug）

**Comment by pengYYYYY** [comment]
0.14.2 已修复
