### ISSUE TITLE
[SelectInput]  autoWidth 不正确，需要和 Vue2/React 保持一致

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#755]
### tdesign-vue-next 版本

`v0.14.1`

### 重现步骤

<img width="503" alt="wecom-temp-f7099368abe1d8028ef284786f8be66d" src="https://user-images.githubusercontent.com/11605702/167800367-be156d2d-2e4d-4517-aa3c-b863e7a241dc.png">

**Comment by pengYYYYY** [comment]
0.14.2 已修复
