### ISSUE TITLE
[Table] [Popup] 筛选弹窗位置异常

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-vue-next#757]
### tdesign-vue-next 版本

0.14.1

### 重现步骤

与 #745  问题类型

https://user-images.githubusercontent.com/35833812/167767282-c48122b6-f051-4447-bc85-44cce45f4441.mov

**Comment by ikeq** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/788

**Comment by pengYYYYY** [comment]
0.15.0 已修复
