### ISSUE TITLE
[Upload] max为1时当存在图片直接上传图片或者文件无效

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#758]
### tdesign-vue-next 版本

0.10.2

### 重现链接

https://stackblitz.com/edit/angular-p3kaa6?file=src/demo.vue

### 期望结果

直接替换上传的内容
![image](https://user-images.githubusercontent.com/20961979/167985997-56aa4189-7d9e-4fb0-9d56-f0c83944956f.png)
还有就是如果theme是文件模式，如果存在文件，按钮只会显示继续上传，下方没有显示当前的文件名
![1652326233(1)](https://user-images.githubusercontent.com/20961979/167986721-2f8556de-f813-4553-8060-dbf678074e85.jpg)

### 实际结果

没有任何反应

### 框架版本

Vue3

**Comment by pengYYYYY** [comment]
文件只有一个url是无法拿到文件名的，需要按标准格式传入，如果 `theme` 为图片则可以展示出来，因为直接读链接

<img width="905" alt="image" src="https://user-images.githubusercontent.com/35833812/168117588-b96c2970-cff9-4c89-83ab-edda948dbecc.png">

**Comment by dennlian** [comment]
这个bug主要不是显示的问题，是max为1的时候点击继续上传上传不了，会提示
![image](https://user-images.githubusercontent.com/20961979/168202652-e782779b-4ec2-4275-b4a6-ee4c2cbfc7cb.png)
这个，希望要么弹出提示，要么max为1的时候直接覆盖掉之前的值
