### ISSUE TITLE
[Steps]  The steps bar of the official website - the theme selection point is disordered

### ISSUE THREAD

**Issue by Zzongke** [Tencent/tdesign-vue-next#762]
### 重现链接
https://tdesign.tencent.com/vue-next/components/steps

### 重现步骤
Open the tDesign Vue next official website, select the steps component, and select the topic dot

### 期望结果
Normal display

### 实际结果
The numbers are not hidden
![1652351610](https://user-images.githubusercontent.com/65376724/168055244-9757c3ca-34ed-4a17-a93a-f115d86dc8fb.jpg)

### 补充说明
The topic selection points of the steps step bar on the official website are disordered

| Environment | Info |
|---|---|
| 相关版本 | 0.14.1 |
| 框架版本 / 基础库版本 | Vue(3.2.12) |
| 系统、浏览器 | windows10、Chrome(101.0.4951.64) |
| Node版本 |  |

**Comment by chaishi** [comment]
收到，我们看下

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/pull/759

**Comment by pengYYYYY** [comment]
0.14.2 已修复
