### ISSUE TITLE
演示页面演示代码报错

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#77]
**Describe Framework**

- [ ] tdesign-vue
- [x] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram
![image](https://user-images.githubusercontent.com/30982989/147541971-20aa7be6-a1a7-4e54-837e-87acb57e17ab.png)

**Comment by pengYYYYY** [comment]
收到，有兴趣的话可以给我们提PR
