### ISSUE TITLE
[Upload] 支持分片上传

### ISSUE THREAD

**Issue by waset** [Tencent/tdesign-vue-next#772]
### 这个功能解决了什么问题

- [ ] 大文件自动分片
- [ ] 文件 md5 校验
- [ ] 预计剩余上传时长

### 参考：

- [simple-uploader](https://github.com/simple-uploader/Uploader)
- [vue-simple-uploader](https://github.com/simple-uploader/vue-uploader)

### 实例

- [vue2+php](https://www.helloweba.net/javascript/632.html)

**Comment by pengYYYYY** [comment]
应该需要一些时间才能抽出精力来支持，有兴趣的话可以先试试看？

**Comment by pengYYYYY** [comment]
暂时不会做这个特性的支持，分片上传功能不属于基础组件库的实现范畴，可使用基础组件做上层定制
