### ISSUE TITLE
[EnhancedTable] 树形表格增加是否默认展开所有行属性

### ISSUE THREAD

**Issue by AngleMi** [Tencent/tdesign-vue-next#776]
### 这个功能解决了什么问题

很多场景要求树形表格嵌套的内容是默认展开的，当前没有提供这样一个配置

### 你建议的方案是什么

类似elment的table提供default-expand-all属性配置来控制是否全部展开所有节点

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue/pull/879

Vue2 / Vue3 / React 都在实现中国了

**Comment by pengYYYYY** [comment]
0.15.0 已修复
