### ISSUE TITLE
tooltip提示会有白边

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#78]
element-ui
![image](https://user-images.githubusercontent.com/30982989/147542541-47183ed1-ef3a-4244-825e-b856cf320d02.png)
tdesign
![image](https://user-images.githubusercontent.com/30982989/147542635-c545e71c-5062-4f41-813b-8d3bdf15fb08.png)
![image](https://user-images.githubusercontent.com/30982989/147542656-37c3b1f4-7cf5-4964-8e23-40f5bce3a111.png)

**Comment by yixiaco** [comment]
感觉tooltop和Popup很像

**Comment by pengYYYYY** [comment]
> 感觉tooltop和Popup很像

是的

**Comment by pengYYYYY** [comment]
> element-ui ![image](https://user-images.githubusercontent.com/30982989/147542541-47183ed1-ef3a-4244-825e-b856cf320d02.png) tdesign ![image](https://user-images.githubusercontent.com/30982989/147542635-c545e71c-5062-4f41-813b-8d3bdf15fb08.png) ![image](https://user-images.githubusercontent.com/30982989/147542656-37c3b1f4-7cf5-4964-8e23-40f5bce3a111.png)

已收到

**Comment by pengYYYYY** [comment]
设计就是有白边的喔

**Comment by pengYYYYY** [comment]
三角型是实现的方式不一样

**Comment by yixiaco** [comment]
三角形底部有白色的弧线，这个也是设计吗，我看其他方向没有哇

**Comment by yixiaco** [comment]
![image](https://user-images.githubusercontent.com/30982989/148145312-205aa003-5aa5-45c7-9c5d-1474cca9666b.png)

> 设计就是有白边的喔
