### ISSUE TITLE
Anchor 锚点 item href属性使用的警告

### ISSUE THREAD

**Issue by yarnk** [Tencent/tdesign-vue-next#780]
### tdesign-vue-next 版本

~0.14.2

### 重现步骤

[Vue warn]: Invalid prop: custom validator check failed for prop "href".

**Comment by chaishi** [comment]
`[Vue warn]: Invalid prop: custom validator check failed for prop "href”.`

这个的意思是：herf 的数据类型校验未通过，请检查参数的数据类型

```
/** 锚点链接, 如果是 hash 模式需要加上当前 path */
  href: {
    type: String,
    default: '',
    required: true,
  },
```

**Comment by chaishi** [comment]
辛苦提供更完整的，可以复现问题的示例代码

如果长时间没有回复，或者提供相关代码，issue 会自动关闭
