### ISSUE TITLE
[table] 使用 `header-affixed-top` 时，异步下不能动态更新列

### ISSUE THREAD

**Issue by BeatenMo** [Tencent/tdesign-vue-next#787]
### tdesign-vue-next 版本

0.14.2

### 重现链接

https://stackblitz.com/edit/angular-krm65k-dxc7gd?file=src/demo.vue

### 重现步骤

通过axios请求api后，then内更新列报错
见demo

### 期望结果

正常动态更新列

**Comment by chaishi** [comment]
`verticalAlign: 'middle',` 使用有误 @BeatenMo 

`verticalAlign` 是 Table 的属性，不是 Column 的属性，行内容 顶部对齐 、底部对齐等
`align` 才是 Column 的属性，指 列 的左对齐、右对齐等

**Comment by pengYYYYY** [comment]
0.15.0 已修复
