### ISSUE TITLE
上方抽屉无动画效果，并且显示卡顿

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#79]
**Describe Framework**

- [x] tdesign-vue
- [x] tdesign-vue-next
- [ ] tdesign-react
- [ ] tdesign-miniprogram

![image](https://user-images.githubusercontent.com/30982989/147543486-1012bc68-1c5a-4df2-864d-445419b6ea6f.png)

**Comment by pengYYYYY** [comment]
该问题已经修复，官网未发布
https://github.com/Tencent/tdesign-vue-next/issues/38
