### ISSUE TITLE
[table] onDragSort方法参数问题

### ISSUE THREAD

**Issue by RionZZZ** [Tencent/tdesign-vue-next#790]
### tdesign-vue-next 版本

0.14.2

### 重现步骤

在定义中，
export interface DragSortContext<T> {
  currentIndex: number;
  current: T;
  targetIndex: number;
  target: T;
  currentData: T[];
  e: SortableEvent;
  sort: 'row' | 'col';
}
onDragSort方法参数打印，current和target均为undefined，一直拿不到值。

### 期望结果

能拿值。

### 实际结果

拿不到值。

### 补充说明

另外问一下，sortable的onEnd方法无效是否是onDragSort方法做了劫持？onDragSort是否就是onEnd方法？

**Comment by chaishi** [comment]
resolved in https://github.com/Tencent/tdesign-vue-next/issues/776

昨天，已经在这个 PR 里面，顺手修复了，还没来得及发布。辛苦关注这个 PR

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/11605702/168632449-2585cb1f-f047-4d8f-bed9-1696e072bae0.png">

**Comment by pengYYYYY** [comment]
0.15.0 已修复
