### ISSUE TITLE
[EnhancedTable] 树形表格，嵌套tooltip组件，无法渲染

### ISSUE THREAD

**Issue by AngleMi** [Tencent/tdesign-vue-next#796]
### tdesign-vue-next 版本

0.14.2

### 重现链接

https://stackblitz.com/edit/angular-fhtgad-nbfbjd?file=src%2Fdemo.vue

### 重现步骤

1、格式化处理表格的data数据之后
<img width="743" alt="wecom-temp-4a538e8fb46ca5aaa3f5f9bfc58eb3d8" src="https://user-images.githubusercontent.com/38134963/168709139-bfff362c-3277-47a4-9877-5ce14fdd7ead.png">

2、在template 套一层tooltip, 无法渲染这一列的数据
<img width="1730" alt="wecom-temp-6cf88750470fe5441287a897f344042c" src="https://user-images.githubusercontent.com/38134963/168709173-50dc36af-5c8d-405a-bda7-776e2b29a2f0.png">

3、去掉tooltip, 就可以正常渲染
<img width="1670" alt="wecom-temp-f8e0575a19d8340f673ac89dc538688d" src="https://user-images.githubusercontent.com/38134963/168709418-3b2b077b-af20-442a-b3b2-cdde89721f01.png">

### 期望结果

嵌套tooltip组件时，树形表格数据可以正常渲染

### 实际结果

嵌套tooltip组件时，无法渲染这一列的数据

**Comment by chaishi** [comment]
@ikeq 方便的话，一起看看这个问题

**Comment by ikeq** [comment]
加 `v-if` 后正常

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/9206414/168717101-0bff3ba9-c117-4196-80f9-e0162618b5d9.png">

直接使用 Popup 也正常

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/9206414/168717245-1406e10f-fb9c-432b-b418-e7a4ffd56ebc.png">

结论：
1. reference 元素更新后，Tooltip 似乎没更新；
2.  考虑 data 有值后，Table 做一次 re-render；
