### ISSUE TITLE
[Transfer] 异步赋值 checked 不生效

### ISSUE THREAD

**Issue by xiaosansiji** [Tencent/tdesign-vue-next#797]
### tdesign-vue-next 版本

0.14.2

### 重现链接

https://stackblitz.com/edit/angular-zexc3a?file=src%2Fdemo.vue

### 重现步骤

```
setTimeout(() => {
  checked.value = ['1', '4'];
}, 3000);
```
setTimeout 中给 Transfer 赋值，没生效

**Comment by pengYYYYY** [comment]
@btea  处理中
