### ISSUE TITLE
[Menu] defaultExpanded属性不管用，只能设置expanded

### ISSUE THREAD

**Issue by woshishade** [Tencent/tdesign-vue-next#798]
### tdesign-vue-next 版本

0.14.2

### 重现步骤

![image](https://user-images.githubusercontent.com/10460238/168745674-bed9c5ad-43ef-47cf-b37f-a1ab69217248.png)
![image](https://user-images.githubusercontent.com/10460238/168745680-3cfb8d22-853e-4dcc-ab5c-cfb6063e1438.png)

### 期望结果

设置defaultExpanded后，菜单可以正常展开

### 实际结果

设置defaultExpanded后，菜单不能展开

**Comment by LeeJim** [comment]
刚好最近改造的时候，顺便修复了这个问题：https://github.com/Tencent/tdesign-vue-next/pull/794
