### ISSUE TITLE
[ColorPickerPanel] 使用 v-model 值没有正确更新

### ISSUE THREAD

**Issue by k1nz** [Tencent/tdesign-vue-next#803]
### tdesign-vue-next 版本

0.14.2

### 重现链接

https://stackblitz.com/edit/angular-xqfqdg?file=src%2Fdemo.vue

### 重现步骤

拖动右侧颜色选择器，input中的值没有更新

### 期望结果

input内容更新

### 实际结果

input中的值没有更新

**Comment by pengYYYYY** [comment]
0.15.2 已修复
