### ISSUE TITLE
[TimePicker/TimeRangePicker] disableTime 导致的报错

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#809]
### tdesign-vue-next 版本

最新版

### 重现链接

https://codesandbox.io/s/bug-td-select-showarrow-cf9ucw?file=/src/App.vue

### 重现步骤

```html
<t-time-picker :disable-time="handleDisabledTimePicker"></t-time-picker>
<t-time-range-picker :disable-time="handleDisabledTimePicker"></t-time-picker>
```
```javascript
const handleDisabledTimePicker = (h) => {
  return h > 12;
};
```

### 实际结果

![image](https://user-images.githubusercontent.com/28809916/168990976-d2ddc485-fea6-47ba-90ff-8311a2cfecbb.png)
![image](https://user-images.githubusercontent.com/28809916/168991147-a7b3c784-a8d0-4d4c-b40e-b8d77ce606c1.png)

**Comment by uyarn** [comment]
timepicker之前disabled的API 部分场景无法使用 之前设计得不合理 重构后会调整这个API

**Comment by pengYYYYY** [comment]
0.16.0 已修复
