### ISSUE TITLE
[Bug] [Table] Vue3 树形表格，演示站

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#81]
Vue3版本的
树形表格有BUG，如果两个项展开，插入数据的位置有问题
![image](https://user-images.githubusercontent.com/20961979/147549984-09aad45d-f03e-4cbd-8bda-a0e6756d4279.png)

**Comment by pengYYYYY** [comment]
已收到

**Comment by pengYYYYY** [comment]
table重构中，重构后会修复

**Comment by whr2349** [comment]
我想问一下，树形table怎么默认全部展开啊？官方的文档书写方式看起来很难受。

**Comment by pengYYYYY** [comment]
跟随这个PR处理 https://github.com/Tencent/tdesign-vue-next/pull/468

**Comment by chaishi** [comment]
应该不是文档看起来难受的问题，默认展开全部还没有实现

**Comment by chaishi** [comment]
@whr2349 辛苦给一下操作视频，我不知道怎么复现你说的问题。
如果你是内部同学，直接企业微信沟通。
如果不是，辛苦提供一下能够复现问题的链接。或者视频。

当前这种提 issue 的方式，问题基本上很难被关注到，也就没法尽快修复。

<img width="1119" alt="image" src="https://user-images.githubusercontent.com/11605702/161440153-e0cde888-c343-4069-b61b-b571f50597fd.png">
