### ISSUE TITLE
[dialog] className属性会覆盖原dialog的class

### ISSUE THREAD

**Issue by supperdsj** [Tencent/tdesign-vue-next#810]
### tdesign-vue-next 版本

0.14.2

### 重现步骤

dialog 设置 className 属性后丢失了 t-dialog__ctx t-dialog__ctx--fixed

### 期望结果

如设置className=“img-selected-dlg”则期望实际 dialog 的 class 为 “t-dialog__ctx t-dialog__ctx--fixed img-selected-dlg”

### 实际结果

如设置className=“img-selected-dlg”则目前实际 dialog 的 class 为 “img-selected-dlg”

### 补充说明

建议 className 属性是追加 class 而不是覆盖已有的全部 dialog class

**Comment by pengYYYYY** [comment]
vue 请用 `class` 传，具体原因请参考下面issue https://github.com/Tencent/tdesign-vue-next/issues/396
