### ISSUE TITLE
[TimePicker] 提供一个事件，由组件弹出层的确定按钮触发，并传递选中的值

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#811]
### 这个功能解决了什么问题

目前 TimePicker 的 确定 按钮只是关闭的作用，有必要有一个类似的功能 表达选择已确认，方便在事件中做一些后续业务逻辑；

并且 onChange 事件在打开 picker 时会被多次触发（应该是 h/m/s 各自抛出了 change 导致？），且每一个数值的变化都会触发 change，导致它并不是一个实现上述需求的好选择，不知道是否是 bug;

### 你建议的方案是什么

简单粗暴一点，给【确定】按钮加一个 confirm 事件应该很简单；
初次打开 picker 直接自动选中 当前时段，在很多场景下会让这个组件很难用，不如去掉，或者加参数关闭这个功能；

**Comment by uyarn** [comment]
这个组件和datepicker下个月会重构 交互会改成点击确认才保留修改

**Comment by pengYYYYY** [comment]
0.16.0 已修复
