### ISSUE TITLE
[Select] value 未命中时不直接显示 value 值

### ISSUE THREAD

**Issue by Crazymuyang** [Tencent/tdesign-vue-next#813]
### 这个功能解决了什么问题

```html
<template>
      <t-select :value="tSelectValue">
        <t-option :value="1" label="一" />
        <t-option :value="2" label="二" />
        <t-option :value="3" label="三" />
      </t-select>
</template>
<script setup>
const tSelectValue = 0;
</script>
```
![image](https://user-images.githubusercontent.com/28809916/169186967-ae733503-6e08-4e39-8e7f-2dd0ddf0ff9a.png)

### 你建议的方案是什么

value 未命中 任何 option 时，可否不显示 value 值？
显示成这样 ：
![image](https://user-images.githubusercontent.com/28809916/169186738-c873d2c8-821e-4e63-b204-a8cffe326da0.png)

**Comment by pengYYYYY** [comment]
此表现属于正常行为，如果需要自定义的话可以使用 `valueDisplay` API
