### ISSUE TITLE
[Dropdown] 通过插槽方式使用下拉菜单：点击事件data内容为空 {     "value": 1,     "path": "",     "content": "" }

### ISSUE THREAD

**Issue by mengjie0320** [Tencent/tdesign-vue-next#814]
### tdesign-vue-next 版本

重现

### 重现链接

https://github.com/mengjie0320/tdesigndemo

### 重现步骤

打开项目  首页，两个下拉框，下面为模板书写，分别选择一个下拉项，下面第二个的打印data 的path、content无内容

### 期望结果

第二个下拉框的  data 的path、content应有内容， 打印示例可为 {
    "value": 1,
    "path": "/1",
    "content": "操作1"
}

### 实际结果

第二个下拉框的  data 的path、content无内容，{value: 1, path: '', content: ''}

### 框架版本

Vue(3.2.13)

### 浏览器版本

Chrome(100.0.4896.60)

### 系统版本

windows10

### Node版本

14.18.2

**Comment by pengYYYYY** [comment]
已收到

**Comment by qunbotop** [comment]
demo好像只是一个初始化的vue项目，是不是还没有更新上去？

**Comment by mengjie0320** [comment]
demo好像只是一个初始化的vue项目，是不是还没有更新上去？

**Comment by mengjie0320** [comment]
> demo好像只是一个初始化的vue项目，是不是还没有更新上去？

新建专门放bug的demo，刚才忘记推送代码了，不好意思

**Comment by mengjie0320** [comment]
> demo好像只是一个初始化的vue项目，是不是还没有更新上去？

新建专门放bug的demo，刚才忘记推送代码了，不好意思；先已推上

**Comment by pengYYYYY** [comment]
对于插槽方式的使用， `t-dropdown-item` 需要传入 `content` 属性才会返回，`path` 已经处理。
```vue
<t-dropdown :min-column-width="88" trigger="click" @click="handleClick">
  <t-button variant="text"> 下拉菜单 </t-button>
  <template #dropdown>
    <t-dropdown-menu>
      <t-dropdown-item :value="1" content="操作一"> 操作一 </t-dropdown-item>
      <t-dropdown-item :value="2"> 操作二 </t-dropdown-item>
    </t-dropdown-menu>
  </template>
</t-dropdown>
```

**Comment by pengYYYYY** [comment]
0.15.4 已修复
