### ISSUE TITLE
[Menu] 折叠后Width问题

### ISSUE THREAD

**Issue by Charles-1999** [Tencent/tdesign-vue-next#823]
### tdesign-vue-next 版本

0.14.2

### 期望结果

<img width="909" alt="image" src="https://user-images.githubusercontent.com/60194808/169452192-20ad8dae-83fc-42e2-ade0-d348975ffc72.png">

在width传入数组后，可以自定义菜单展开和折叠的宽度。

### 实际结果

width传入数组后并不会生效。

### Node版本

v17.8.0

### 补充说明

0.14.2的文档介绍是已经有这个功能的，但看了仓库代码还在devlopment分支，希望能尽快发布～

**Comment by pengYYYYY** [comment]
0.15.0 已修复
