### ISSUE TITLE
[tagInput] 文档的demo代码需优化

### ISSUE THREAD

**Issue by supperdsj** [Tencent/tdesign-vue-next#825]
### tdesign-vue-next 版本

0.14.2

### 重现链接

https://tdesign.tencent.com/vue-next/components/tag-input?tab=demo

### 重现步骤

<template><t-tagInput /></template>

### 期望结果

<template><t-tag-input /></template>

### 实际结果

<template><t-tagInput /></template>

**Comment by pengYYYYY** [comment]
已收到，待修复
