### ISSUE TITLE
[tagInput] 绑定变量未定义时绑定失效

### ISSUE THREAD

**Issue by supperdsj** [Tencent/tdesign-vue-next#826]
### tdesign-vue-next 版本

0.14.2

### 重现步骤

定义obj={}
<t-tag-input v-model='obj.value'/>

### 期望结果

绑定失效，需要预定义 obj={value:[]}

### 实际结果

期待可以自动处理并补全默认值类型

**Comment by pengYYYYY** [comment]
已收到，待修复

**Comment by pengYYYYY** [comment]
传入参数类型不符合API定义，属于正常表现。tag-input 需要数组
