### ISSUE TITLE
[Cascader] 箭头不居中

### ISSUE THREAD

**Issue by JieAnthony** [Tencent/tdesign-vue-next#829]
### tdesign-vue-next 版本

0.15.0

### 重现步骤

[img](https://cdn.learnku.com/uploads/images/202205/20/26656/pZajpQ2CUd.png!large)

### 期望结果

箭头正确展示

### 实际结果

箭头在最上方

**Comment by JieAnthony** [comment]
另外不限制<ul>的宽度对于字符串较多的时候看上去或许会比较好看

**Comment by JieAnthony** [comment]
另外不限制ul的宽度对于字符串较多的时候看上去或许会比较好看

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-common/pull/474 已经修复

**Comment by pengYYYYY** [comment]
> 另外不限制ul的宽度对于字符串较多的时候看上去或许会比较好看

这个问题我们这边与UI讨论一下
