### ISSUE TITLE
[Menu] 菜单折叠后弹出层无法hover住

### ISSUE THREAD

**Issue by taomas** [Tencent/tdesign-vue-next#830]
### tdesign-vue-next 版本

0.14.2

### 重现链接

https://tdesign.woa.com/vue-next/components/menu

### 重现步骤

侧边菜单折叠后，鼠标移动过来一直抖动，hover菜单无法选中。

<img width="394" alt="image" src="https://user-images.githubusercontent.com/17002702/169504542-e5b4e5d3-49d9-41f4-9feb-8756861896ed.png">

### 期望结果

侧边菜单折叠后，折叠状态下的子菜单能够正常展示。

**Comment by pengYYYYY** [comment]
0.15.0已修复
