### ISSUE TITLE
[t-enhanced-table] 对于数组添加子项无法双向绑定更新列表

### ISSUE THREAD

**Issue by RionZZZ** [Tencent/tdesign-vue-next#831]
### tdesign-vue-next 版本

0.14.2

### 重现步骤

使用t-enhanced-table，:data='datalist'，datalist.push(item) 页面并不会实时更新出一条数据。而t-table是可以实时更新的。添加子项使用appendTo没问题，我的需求有在最外层添加平级项

**Comment by chaishi** [comment]
辛苦参考官网示例，「重置数据」按钮更新 data，而非凭个人经验直接写 `datalist.push(item)`。

TEnhancedTable 组件，为树形结构，比较特殊，数据统一在组件内部进行管理。一般的节点插入、删除操作都是通过实例方法进行。

如果更为和官网示例一模一样的写法之后，还发现问题，再 open 另一个 issue。当前 issue 关闭
