### ISSUE TITLE
t-head-menu Vue报警

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#835]
### tdesign-vue-next 版本

是

### 重现步骤

![image](https://user-images.githubusercontent.com/46079969/169515821-84818aa7-9bc5-42bc-808c-c7d0f4314b9e.png)

出现报警：
        
    [Vue warn]: Property "head" was accessed during render but is not defined on instance. 

### 系统版本

Win10 64

**Comment by pengYYYYY** [comment]
已收到相关反馈，正在修复

**Comment by pengYYYYY** [comment]
由于周五刚发了新的 0.15.0，所以发了一个 `alpha` 版本修复此问题, 可以装一下`0.15.0-alpha.1` 先用。

**Comment by pengYYYYY** [comment]
0.15.1 已修复
