### ISSUE TITLE
[Input] Input框嵌套到拖拽排序里面报错

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#836]
### tdesign-vue-next 版本

0.15.0

### 重现步骤

类似一个拖拽排序里面增加输入框，会导致下面的报错
```
 <draggable class="qb-w-full" v-model={modelValue[key]} item-key="value">
                  {{
                    item: ({ element: it, index }) => {
                      return (
                        <div class="qb-pb-3 qb-flex ">
                          <t-input-group class="qb-overflow-hidden" separate>
                            {it.color ? (
                              <t-color-picker
                                v-model={it.color}
                                swatch-colors={['#5a78f0', '#ed7b2f', '#e34d59', '#00a870']}
                                format="HEX"
                              />
                            ) : (
                              ''
                            )}
                            <div class="qb-flex-1">
                              <t-input label="标签：" v-model={it.label} placeholder="请输入字典标签" />
                            </div>
                            <div class="qb-flex-1">
                              <t-input
                                label="键值："
                                readonly={form.status === '只读'}
                                v-model={it.value}
                                placeholder="请输入字典键值"
                              />
                            </div>
                            <div class="qb-flex qb-cursor-move qb-w-[148px]">
                              <t-button variant="text" onClick={addDic}>
                                {{ icon: () => <t-icon name="add-circle" size="large" /> }}
                              </t-button>
                              <t-button
                                variant="text"
                                onClick={() => {
                                  addColor(index, it);
                                }}
                              >
                                颜色
                              </t-button>
                              {index > 0 && !it.delete ? (
                                <t-button variant="text" onClick={() => removeDic(index)}>
                                  {{ icon: () => <t-icon name="delete" size="large" /> }}
                                </t-button>
                              ) : (
                                ''
                              )}
                            </div>
                          </t-input-group>
                        </div>
                      );
                    },
                  }}
                </draggable>
```

### 期望结果

![image](https://user-images.githubusercontent.com/20961979/169516249-b857635d-6232-411e-a905-3418a54631fd.png)
改变值不报错

### 实际结果

报错并且会失去光标

### 框架版本

Vue3

### 系统版本

windows10

**Comment by pengYYYYY** [comment]
0.14.2 有问题嘛？还是版本升级上去后的问题

**Comment by dennlian** [comment]
0.14.2有问题，0.15.0也有问题

**Comment by dennlian** [comment]
![image](https://user-images.githubusercontent.com/20961979/169522096-13be4923-cf99-4301-a1c8-64780942cfac.png)
提示报错的地方

**Comment by pengYYYYY** [comment]
好的，我们这边排查一下

**Comment by dennlian** [comment]
引入vuedraggable 里面嵌套input ，第一个可以输入不报错，第二个输入的时候会报错，这个是demo
`<template>
  <div>

    <draggable class="qb-w-full" v-model="list.from" item-key="value">
      <template #item="{ element: it }">
        <div class="qb-pb-3 qb-flex">
          <t-input-group class="qb-overflow-hidden" separate>
            <div class="qb-flex-1">
              <t-input label="标签：" v-model="it.label" placeholder="请输入字典标签" />
            </div>
            <div class="qb-flex-1">
              <t-input label="键值：" v-model="it.value" placeholder="请输入字典键值" />
            </div>
          </t-input-group>
        </div>
      </template>
    </draggable>
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive } from 'vue';
import draggable from 'vuedraggable';

export default defineComponent({
  name: 'Result404',
  components: {  draggable },
  setup() {
    return {
      list: reactive({
        from: [
          { value: 1, label: '333' },
          { value: 1, label: '333' },
          { value: 1, label: '333' },
        ],
      }),
    };
  },
});
</script>
`

**Comment by pengYYYYY** [comment]
好的

**Comment by youuss** [comment]
halo @dennlian 请问能在https://stackblitz.com/ 或者 https://codesandbox.io/ 提供复现的demo吗？我在本地没复现这类问题。 然后这里不建议使用变动值做draggable的key，这会导致重复渲染哈

**Comment by dennlian** [comment]
0.15.1里面就没有报错了

**Comment by youuss** [comment]
好的好的 @pengYYYYY close吧

**Comment by dennlian** [comment]
应该是改变了value 导致draggable 重新渲染，失去了交点，触发了input 的clear 那边然后就报错了

**Comment by youuss** [comment]
嗯 所以说不大建议使用变量在做key，这会出现一系列的问题，而且交互也不大友好🤔

**Comment by pengYYYYY** [comment]
那close咯，有问题再提issue喔
