### ISSUE TITLE
T-HEADER-MENU 箭头方向异常

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#837]
### tdesign-vue-next 版本

T-HEADER-MENU 箭头方向异常

### 重现步骤

![image](https://user-images.githubusercontent.com/46079969/169560955-caf7a5d7-c8da-41de-940e-377649288435.png)

### 期望结果

![00A1F4E0](https://user-images.githubusercontent.com/46079969/169560983-174d9ee5-d54a-417c-8a78-b9eccfcd5cd3.png)

官网显示箭头保持一直 使用下拉箭头

**Comment by LeeJim** [comment]
same as #882
