### ISSUE TITLE
[组件名称] 描述问题的标题

### ISSUE THREAD

**Issue by lwb-2021** [Tencent/tdesign-vue-next#838]
### tdesign-vue-next 版本

0.15.0

### 重现步骤

在Form中添加t-tag-input，输入标签然后按下回车

### 期望结果

标签被添加到标签输入框

### 实际结果

标签添加，但是表单直接提交

### 系统版本

Windows 10 1909

**Comment by pengYYYYY** [comment]
当form中只有一个input（tag-input依赖于input组件）的时候，回车会触发form的submit。属于浏览器行为。解决该问题可以 `submit` 时候做判断，也可以加一个隐藏的 `input` 来阻止这种行为。

**Comment by lwb-2021** [comment]
> 
但是我在form中有一个t-input
