### ISSUE TITLE
[Table] toggleExpandData 和 expandAll/FoldAll 混合使用时，树形结构展开有误

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#839]
### tdesign-vue-next 版本

0.15.0

### 重现步骤

https://user-images.githubusercontent.com/11605702/169641431-97711609-bf17-4c5d-98ef-0a5131ef0c21.mov

**Comment by pengYYYYY** [comment]
0.15.1 已修复
