### ISSUE TITLE
[t-enhanced-table]对列表一顿操作后，无法拿到操作后的整个列表data

### ISSUE THREAD

**Issue by RionZZZ** [Tencent/tdesign-vue-next#849]
### tdesign-vue-next 版本

0.15.0

### 重现步骤

和[#831](https://github.com/Tencent/tdesign-vue-next/issues/831)差不多，这个bug的问题在升级0.15后添加了insert方法后得以解决，但是数据绑定的问题还是没有解决。getData方法需要传一个key作为参数获取当前key下面数据集合。没有提供方法直接获取所有数据，像
```
<t-enhanced-table
      ref="table"
      row-key="key"
      :data="data"/>
```
data的值，用户做完操作，如何保存下面所有的数据data，而不仅仅是getData某一个item。

-------

还有，insert方法第一个参数也是需要传一个key，此时我如果没有data数据（空表格），新增，就没办法处理了。

### 期望结果

提供方法获取整个修改后的data，或者双向绑定到data上

**Comment by chaishi** [comment]
> data的值，用户做完操作，如何保存下面所有的数据data，而不仅仅是getData某一个item。

请使用 `table.value.dataSource 查看树形结构平铺数据`
<img width="705" alt="image" src="https://user-images.githubusercontent.com/11605702/170405341-9a5dc1c3-6b78-4ec7-aa41-0fb893709d9c.png">

**Comment by chaishi** [comment]
> `提供方法获取整个修改后的data，或者双向绑定到data上`

树形结构，不支持任何场景下的双向绑定。data 是树形结构，但内部维护的数据是平铺的结构。
如果支持双向绑定，会造成每一次数据更新，都全量同步数据

**Comment by chaishi** [comment]
> 还有，insert方法第一个参数也是需要传一个key，此时我如果没有data数据（空表格），新增，就没办法处理了。

后续支持不需要传 `key` 的方法

**Comment by RionZZZ** [comment]
> 
dataSource 方法我试了，是平铺数据。就是我需要再自己给整成树结构再发送给后台。。。 明明我传过来的是树形，拿到的却是平铺。可以提供一个方法，调用时封装成树形返回。

**Comment by chaishi** [comment]
@RionZZZ 

可以补充一个树形结构的获取方法

不过，平铺数据包含了所有的节点关系，自己封装一个方法也快的吧。着急的话，先自己写写

**Comment by pengYYYYY** [comment]
0.15.3 已修复
