### ISSUE TITLE
[upload] placeholder不生效

### ISSUE THREAD

**Issue by supperdsj** [Tencent/tdesign-vue-next#853]
### tdesign-vue-next 版本

0.14.2

### 重现步骤

```
<t-upload :placeholder="'测试placeholder'" theme="image"></t-upload>
```

### 期望结果

 placeholder正确显示为 "测试placeholder"

### 实际结果

placeholder显示为 "点击上传图片"

**Comment by pengYYYYY** [comment]
0.15.2 已修复
