### ISSUE TITLE
[table] 固定列的表格右侧有内边距的前提，左右拖动表格，表格右侧内边距内文案会溢出来，隐藏不掉

### ISSUE THREAD

**Issue by carolinelihui** [Tencent/tdesign-vue-next#855]
### tdesign-vue-next 版本

0.15.0

### 重现链接

https://tdesign.woa.com/vue-next/components/table#%E5%9B%BA%E5%AE%9A%E8%A1%A8%E5%A4%B4%E5%92%8C%E5%88%97%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤

手动给 t-table__content 添加右侧内边距，切换窗口大小，使表格内容可以左右滑动

### 期望结果

表格右侧内边距内不显示超出内容

### 实际结果

![image](https://user-images.githubusercontent.com/33538251/169789905-464f57b6-fd57-45ef-93ae-6a05d497aac4.png)

**Comment by chaishi** [comment]
> 手动给 t-table__content 添加右侧内边距，切换窗口大小，使表格内容可以左右滑动

使用方式有误，不予处理。（`t-table__content` 属于内部类名，有其特殊逻辑存在，不支持随意改变宽度边距类属性）

建议处理方式：左右滑动是一个横向内容超出后自动出现的过程，而非主观行为。如果真的需要及时内容没有超出也滚动，应该通过给每一列加大宽度 `width` 设置，来实现滚动效果。
