### ISSUE TITLE
[form] FormInstanceFunctions  reset方法报错

### ISSUE THREAD

**Issue by RionZZZ** [Tencent/tdesign-vue-next#856]
### tdesign-vue-next 版本

0.15.0

### 重现步骤

```
ref="form"
···
const form = ref()
···
form.value.reset()
```
报错：
form.tsx:91 Uncaught (in promise) TypeError: e.preventDefault is not a function
    at Proxy.reset2 (form.tsx:91:12)

**Comment by k1nz** [comment]
https://stackblitz.com/edit/angular-um4vtq?file=src%2Fdemo.vue

似乎没有问题呢，可以提供一下 demo

**Comment by skytt** [comment]
> https://stackblitz.com/edit/angular-um4vtq?file=src%2Fdemo.vue
> 
> 似乎没有问题呢，可以提供一下 demo

这个demo，把组件reset事件的响应给去掉，会报错，辛苦看看...
<img width="455" alt="image" src="https://user-images.githubusercontent.com/7420660/169935463-2b9bf8d4-1afe-44ff-bc53-a0372399a321.png">
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/7420660/169935451-f6d6b877-bb76-4850-a202-b57f84e89af0.png">

**Comment by pengYYYYY** [comment]
发了一个 `0.15.1-alpha.1` 的包，可以先用一下

**Comment by RionZZZ** [comment]
> https://stackblitz.com/edit/angular-um4vtq?file=src%2Fdemo.vue
> 
> 似乎没有问题呢，可以提供一下 demo

对 就是上面说的原因。一定要加@reset方法，但是我既然已经用了instance方法，为啥还要加@reset呢

**Comment by pengYYYYY** [comment]
> > https://stackblitz.com/edit/angular-um4vtq?file=src%2Fdemo.vue
> > 似乎没有问题呢，可以提供一下 demo
> 
> 对 就是上面说的原因。一定要加@reset方法，但是我既然已经用了instance方法，为啥还要加@reset呢

0.15.1-alpha.1 用这个包试试

**Comment by pengYYYYY** [comment]
0.15.2 已修复
