### ISSUE TITLE
[Bug] [Menu] 当menu父容器设置有overflow-x:auto的时候，子menu无法展示

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-vue-next#86]
![image](https://user-images.githubusercontent.com/35833812/147624521-414cbadb-765e-497c-a2e4-730d69cee403.png)

设置了 `overflow-x: auto` 就会将y的默认值`visible`改成`auto`；
因此相当于 `overflow: auto` 从而导致y轴的被隐藏。
所以，目前没办法通过简单改 css 来实现x轴溢出时滚动，需要调整下 DOM 。

**Comment by LeeJim** [comment]
我来看下
