### ISSUE TITLE
Cascader 级联选择器：选择任意一项的级联选择器无法选择

### ISSUE THREAD

**Issue by GaoXiaoBoGitHub** [Tencent/tdesign-vue-next#862]
### tdesign-vue-next 版本

0.15.1

### 重现步骤

级联选择器：选择任意一级（check-strictly）添加无效果。
官网0.15.1版本demo是可以选择的，但实际使用不可用，安装0.14.2版本没有问题

**Comment by pengYYYYY** [comment]
实际不可用的场景是什么？

**Comment by GaoXiaoBoGitHub** [comment]
> 实际不可用的情况是什么？

当选择部门树的任意一级部门时，无法单独选择，此问题为0.15.1版本，之前的版本此功能是正常的。

**Comment by pengYYYYY** [comment]
能给一个Stackblitz，这边测试没问题喔

**Comment by pengYYYYY** [comment]
无法复现，Stackblitz 的demo也没有问题，提供Stackblitz 后reopen
