### ISSUE TITLE
[layout] t-header样式影响其他组件表达

### ISSUE THREAD

**Issue by Larmyliu** [Tencent/tdesign-vue-next#863]
### tdesign-vue-next 版本

0.15.1

### 重现链接

https://stackblitz.com/edit/vitejs-vite-xxtxzt?file=src/App.vue

### 重现步骤

背景：
1、t-header和t-form，t-select等组件结合使用
2、t-header设置了height高度
结果
1、label和select组件之间对齐异常
2、label和其他相关组件展示正常
原因初步判断：
初步判断原因是.t-layout__header中的line-height影响了t-select的表现，将line-height注释后展示和期望结果相同

### 期望结果

![image](https://user-images.githubusercontent.com/57323467/169976146-989aff7b-26b6-48b4-8009-83851d127c87.png)

### 实际结果

![image](https://user-images.githubusercontent.com/57323467/169976246-2791a939-650a-468d-b13f-d470366fb3bf.png)

### 框架版本

0.15.1

### 浏览器版本

 chrome101.0.4951.67

### 系统版本

windows

### Node版本

16.14.12

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-common/pull/478

**Comment by pengYYYYY** [comment]
0.15.2 已修复
