### ISSUE TITLE
Dropdown 下拉菜单

### ISSUE THREAD

**Issue by zzzfa** [Tencent/tdesign-vue-next#869]
### tdesign-vue-next 版本

0.15.0

### 重现步骤

多点击几次弹窗就出不来了了，双击出问题的概率更大一点

### 补充说明

https://user-images.githubusercontent.com/105639204/170079195-b0ab8b7f-0edb-43b8-a028-bd3a5c3be9ef.mp4

**Comment by pengYYYYY** [comment]
https://user-images.githubusercontent.com/35833812/170199467-e93b16ac-9da6-49a6-9cb0-0a689f99a197.mov

**Comment by pengYYYYY** [comment]
升级到0.15.3看看呢？
