### ISSUE TITLE
[t-row] 栅格组件计算方式建议优化

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#873]
### 这个功能解决了什么问题

当前系统栅格使用的12等分模式， 12等分在分辨率较大的显示器上宽度难以调整， 建议将栅格组件按照24等分的模式进行设计

### 你建议的方案是什么

建议将栅格组件模式按照24等分的模式进行设计

**Comment by pengYYYYY** [comment]
可以通过改 less 的 @grid-columns token来变化
