### ISSUE TITLE
[icon] 默认尺寸缺失

### ISSUE THREAD

**Issue by supperdsj** [Tencent/tdesign-vue-next#876]
### tdesign-vue-next 版本

0.15.1

### 重现步骤

```
<t-icon name="add"/>
  <t-button>
    <template #icon>
      <t-icon name="add"/>
    </template>
    添加
  </t-button>
```

### 期望结果

可以正确显示正常尺寸的 icon

### 实际结果

![image](https://user-images.githubusercontent.com/10287320/170468667-0409c23f-3729-4dc0-9ae7-d908d4b913b8.png)

**Comment by uyarn** [comment]
https://stackblitz.com/edit/angular-dce6kc?file=src%2Fdemo.vue
<img width="460" alt="image" src="https://user-images.githubusercontent.com/26377630/170471190-d0824f5e-2f41-4ee6-9f92-f4ee31fbc69a.png">

**Comment by uyarn** [comment]
icon最近没有做什么改动 理论上不存在你说的问题 检查一下你的项目是不是有其他样式造成干扰导致的。

**Comment by pengYYYYY** [comment]
先关闭，如果是组件库的问题，麻烦reopen
