### ISSUE TITLE
[ColorPicker] 颜色选择器位置在底部200左右高度，弹框只显示一半

### ISSUE THREAD

**Issue by Alsmile** [Tencent/tdesign-vue-next#877]
### tdesign-vue-next 版本

0.15.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/color-picker

### 重现步骤

滚动颜色选择器到页面底部靠上一点点。

或者弹框后，上下不断滚动滚动条。

![image](https://user-images.githubusercontent.com/1797302/170471637-a0065634-e817-478c-b286-56f87c56ebf6.png)

### 期望结果

![image](https://user-images.githubusercontent.com/1797302/170471859-83d1089b-3d92-426f-8933-c174201c6306.png)

### 实际结果

![image](https://user-images.githubusercontent.com/1797302/170471637-a0065634-e817-478c-b286-56f87c56ebf6.png)

**Comment by pengYYYYY** [comment]
#932 跟随修复

**Comment by pengYYYYY** [comment]
0.16.0 已修复
