### ISSUE TITLE
[ColorPicker] 选中输入框时popup直接隐藏

### ISSUE THREAD

**Issue by DYS1230** [Tencent/tdesign-vue-next#878]
### tdesign-vue-next 版本

0.15.1

### 重现链接

https://stackblitz.com/edit/angular-yifap1?file=src%2Fdemo.vue

### 重现步骤

![企业微信截图_16535678949823](https://user-images.githubusercontent.com/13117927/170487498-aabae2cf-2eda-4db6-b4e4-aa8fc349513a.png)

点击时popup直接隐藏

### 期望结果

应该是可选择，可输入

### 实际结果

popup直接隐藏

**Comment by pengYYYYY** [comment]
0.15.2 已修复
