### ISSUE TITLE
[t-select] 建议减少或者关闭数据类型转换警告

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#879]
### tdesign-vue-next 版本

0.15.1

### 重现步骤

当通过变量决定是否对select组件进行多选时，绑定的ref值在组件内部进行的数据类型转换提示建议关闭

![image](https://user-images.githubusercontent.com/46079969/170496302-67955cf6-9d19-42e6-a860-297949c32ac7.png)

### 期望结果

不显示内部的设计警告

**Comment by pengYYYYY** [comment]
这个告警的前置条件是：当单选的时候，v-model的值类型为数组，当多选时，v-model值的类型不为数组。切换类型的时候把绑定值处理一下就好了
