### ISSUE TITLE
[Menu] headmenu submenu非直接子节点时样式存在异常

### ISSUE THREAD

**Issue by uyarn** [Tencent/tdesign-vue-next#882]
### tdesign-vue-next 版本

0.15.0

### 重现链接

https://tdesign.tencent.com/starter/vue-next/#/dashboard/base

### 重现步骤

子菜单不是直接写在heademenu的slot里，而是封装成另一个组件的形式存在
如
```
  <t-head-menu :class="menuCls" :theme="theme" expand-type="popup" :value="active">
      <template #logo>
        <span v-if="showLogo" class="header-logo-container" @click="handleNav('/dashboard/base')">
          <LogoFull class="t-logo" />
        </span>
        <div v-else class="header-operate-left">
          <t-button theme="default" shape="square" variant="text" @click="changeCollapsed">
            <t-icon class="collapsed-icon" name="view-list" />
          </t-button>
          <search :layout="layout" />
        </div>
      </template>
      <MenuContent v-show="layout !== 'side'" key="header-menu" class="header-menu" :nav-data="menu" />
      // 包括了submenu
      ...
</t-head-menu>
```
1. 菜单箭头样式异常
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/26377630/170643083-13ba9230-4e1b-4c7a-83da-3c638638a74d.png">

2. 选择暗黑模式、选择顶部菜单，打开任意一个子菜单
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/26377630/170642779-09d09776-6a65-4411-82d2-9599843b02b5.png">
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/26377630/170642907-b5d3c6ec-1cf4-4eef-9ec6-266b7d03c2f4.png">

### 期望结果

子菜单样式正常

### 实际结果

子菜单样式异常

**Comment by pengYYYYY** [comment]
关联issue https://github.com/Tencent/tdesign-vue-next/issues/837 https://github.com/Tencent/tdesign-vue-next/issues/832

**Comment by pengYYYYY** [comment]
0.15.4 已修复
