### ISSUE TITLE
[Transfer 穿梭框] 双向绑定无效果

### ISSUE THREAD

**Issue by JieAnthony** [Tencent/tdesign-vue-next#883]
### tdesign-vue-next 版本

0.15.1

### 重现步骤

我有一个dialog里面有Transfer 穿梭框，当我把数据准备好并且移到右侧时候，点击确认，关闭dialog。此时我应该将Transfer 穿梭框的v-model="targetValue" 和 v-model:checked="checked" 设置为空数组，设置完毕后发现无效果，被我选到右侧数据还是继续在右侧显示，请问有什么办法可以解决

**Comment by pengYYYYY** [comment]
收到

**Comment by pengYYYYY** [comment]
beta 处理中

**Comment by pengYYYYY** [comment]
0.15.3 已修复
