### ISSUE TITLE
[popconfirm] 一个项目的卡片式列表，点击部分位置的删除提示，左上角有显示初始图层

### ISSUE THREAD

**Issue by chinanf-boy** [Tencent/tdesign-vue-next#889]
### tdesign-vue-next 版本

0.15.1

### 重现链接

https://tdesign.tencent.com/vue-next/components/popconfirm?tab=demo

## 1. 简单示例，仅写明位置
1. https://tdesign.tencent.com/vue-next/components/popconfirm?tab=demo
在示例页面中，点击任一示例，不关闭
2. 点击API，切换 https://tdesign.tencent.com/vue-next/components/popconfirm?tab=api
3. 现在，确认框的位置，就是 示例GIf 中，会出现的位置

## 2. GIf 示例
一个项目的卡片式列表，点击部分位置的删除提示，左上角有显示初始图层
![左上角](https://user-images.githubusercontent.com/20272484/170679861-45d00054-518a-4ff5-94d0-a0e1ed970a2c.gif)
![图像1 42](https://user-images.githubusercontent.com/20272484/170680625-a19cd486-b4a9-4cbe-8c01-6253f071d38b.png)

### 框架版本

3.2.31

### 浏览器版本

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53'

### 系统版本

Windows(1809)

### Node版本

v14.18.1

**Comment by pengYYYYY** [comment]
https://user-images.githubusercontent.com/35833812/170681952-0989ccbe-de9e-40b7-80ff-23190f1abc84.mov


看起来没有这个问题

**Comment by pengYYYYY** [comment]
issue 未回复，先关闭

**Comment by chinanf-boy** [comment]
@pengYYYYY 就是闪了那一下，
在项目中，是先闪了那一下，才定位到点击的元素的。

**Comment by ikeq** [comment]
确实是个问题，我跟进一下
