### ISSUE TITLE
[Skeleton] 文档中有 delay 的功能描述与实际不符合

### ISSUE THREAD

**Issue by ontheroad1992** [Tencent/tdesign-vue-next#892]
### tdesign-vue-next 版本

0.15.2

### 补充说明

没有实现 delay 功能，且 ts 中无 delay 的类型
<img width="903" alt="image" src="https://user-images.githubusercontent.com/29194619/170806437-7b8183ef-640c-4b27-a618-d58567e8ca4e.png">

**Comment by pengYYYYY** [comment]
0.16.0 已修复
