### ISSUE TITLE
[Button] 未按照预期样式显示

### ISSUE THREAD

**Issue by uninjaxs** [Tencent/tdesign-vue-next#905]
### tdesign-vue-next 版本

0.15.2

### 重现链接

https://vite-base-starter.vercel.app/

### 重现步骤

Button 组件未按照预期样式显示。

--ripple-color: var(--td-brand-color-active);

css变量未编译。

### 浏览器版本

Chrome(102.0.5005.61)

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/pull/898 已经修复，稍后会发补丁版本
