### ISSUE TITLE
[Form] 使用TInput 组件增加number 类型校验，输入数字无法校验通过

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#908]
### tdesign-vue-next 版本

0.15.3

### 期望结果

![image](https://user-images.githubusercontent.com/20961979/170929005-4d98935b-f2f9-43f7-9935-56f399ed862d.png)
期望输入数字文本类型能校验通过，

### 实际结果

输入数字文本类型校验无法通过

**Comment by pengYYYYY** [comment]
已收到

**Comment by dennlian** [comment]
![image](https://user-images.githubusercontent.com/20961979/174427253-e7a44ff5-573b-42f3-b643-3e0c35d1a369.png)
0.16.0版本又有这个bug了
