### ISSUE TITLE
[Bug][Table]已设置每列宽度，当父容器变宽后标题和内容页错位

### ISSUE THREAD

**Issue by talksmallice** [Tencent/tdesign-vue-next#91]
### Describe Environment
browser version:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62
tdesign-vue-next version:0.6.0

### Describe the bug
![image](https://user-images.githubusercontent.com/96230329/147637795-17bd5361-3f40-43f0-9304-421bc38c1ea8.png)
table已设置每列宽度，当父容器变宽后标题和内容页错位
设置height属性后才会出现该问题

**Comment by pengYYYYY** [comment]
修复https://github.com/Tencent/tdesign-vue-next/pull/200
