### ISSUE TITLE
[Pagination] 当分页数量超出 `maxPageBtn` 时，不是出现省略号，隐藏中间部分页码。而是隐藏 最前面 和 最后面的页码

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#911]
### tdesign-vue-next 版本

0.15.3

### 重现链接

https://stackblitz.com/edit/nuxt-starter-lsiiyd?file=pages/index.vue

### 期望结果

例如搜索引擎百度、google、必应，不允许用户直接跳转到最后一页或第一页

### 实际结果

只隐藏了第一页和最后一页的图标，实际上还是存在可以跳转第一页和最后一页
![image](https://user-images.githubusercontent.com/30982989/170957889-95fcc6d5-a264-4a90-8185-eee61282c2dd.png)

### 补充说明

如果showFirstAndLastPageBtn为false时，不应该显示折叠选项也不应该显示第一页与最后一页的快捷按钮
或者折叠选项应该是可控的，可以折叠的个数，如果为0则不折叠等

**Comment by HQ-Lin** [comment]
emm 你理解错了，这个是显示快速跳转首页和尾页按钮的开关
<img width="527" alt="image" src="https://user-images.githubusercontent.com/24469546/170958308-570ae138-8e02-4c43-abcb-c0fd91551d72.png">

**Comment by pengYYYYY** [comment]
文档描述要改一下

**Comment by yixiaco** [comment]
那就新增一个不展示第一页和最后一页的选项，感觉这个选项名称不是这个意思吗🤔

**Comment by yixiaco** [comment]
![image](https://user-images.githubusercontent.com/30982989/170960386-eb8a1e59-b9fc-45d5-a0da-9382d2e5d6fb.png)
像这样就没办法实现
showFirstAndLastPageBtn：显示第一和最后一个页面按钮，不是这样翻译吗🤣

**Comment by pengYYYYY** [comment]
描述改了一下，名字没取好

**Comment by pengYYYYY** [comment]
> ![image](https://user-images.githubusercontent.com/30982989/170960386-eb8a1e59-b9fc-45d5-a0da-9382d2e5d6fb.png) 像这样就没办法实现 showFirstAndLastPageBtn：显示第一和最后一个页面按钮，不是这样翻译吗🤣

这样的确实没办法实现

**Comment by yixiaco** [comment]
> 描述改了一下，名字没取好

不是，我是说，能加个隐藏这两按钮的功能吗

**Comment by pengYYYYY** [comment]
pageDisplayFilter 会提供一个这样的API, 然后你这么用就好了。
```js
<t-pagination
      v-model="current"
      v-model:pageSize="pageSize"
      :total="100"
      :page-display-filter="(i) => i !== 1"
      @change="onChange"
      @page-size-change="onPageSizeChange"
      @current-change="onCurrentChange"
    />
```

**Comment by chaishi** [comment]
<img width="935" alt="image" src="https://user-images.githubusercontent.com/11605702/170982248-ffc9fdac-da31-4df7-b25f-8c17b43e1aca.png">

**Comment by yixiaco** [comment]
> <img alt="image" width="935" src="https://user-images.githubusercontent.com/11605702/170982248-ffc9fdac-da31-4df7-b25f-8c17b43e1aca.png">

如果第五页第20页呢，第一页也存在。其实是最后一页存在，这个不可控

**Comment by chaishi** [comment]
`pageDisplayFilter`，待定，我刚刚才明白是什么意思
容我们内部讨论下

**Comment by pengYYYYY** [comment]
0.16.0 修复
