### ISSUE TITLE
HeadMenu 默认激活的菜单没有回显

### ISSUE THREAD

**Issue by GaoXiaoBoGitHub** [Tencent/tdesign-vue-next#914]
### tdesign-vue-next 版本

0.15.2

### 重现链接

https://stackblitz.com/edit/hjhdss--run

### 重现步骤

进入页面，默认激活的菜单样式没有回显，只回显了子菜单

**Comment by pengYYYYY** [comment]
这个链接打不开

**Comment by pengYYYYY** [comment]
<img width="915" alt="image" src="https://user-images.githubusercontent.com/35833812/173190788-559c8152-2ae8-4ae0-b742-63ffca651454.png">
看起来没问题呢

**Comment by pengYYYYY** [comment]
先关闭咯，待更多信息后在reopen
