### ISSUE TITLE
[Table]行拖拽排序顺序不符合预期（Vue2 和 React 没有问题，单 Vue3 的数据驱动较为奇怪，研究中）欢迎有兴趣的同学共同探讨

### ISSUE THREAD

**Issue by benbenonline** [Tencent/tdesign-vue-next#915]
### 重现链接
https://tdesign.tencent.com/vue-next/components/table#%E5%8F%AF%E6%8B%96%E6%8B%BD%E6%8E%92%E5%BA%8F%E7%9A%84%E8%A1%A8%E6%A0%BC

### 重现步骤
官方例子也可以重现
示例二：有手柄列的行拖拽排序
步骤：
多次拖拽JQTest1行向上或向下，重复操作。

### 期望结果
多次拖拽JQTest1行向上或向下后，排序顺序正确

### 实际结果
顺序会乱掉，不是期望的正确排序结果。

### 补充说明
从0.13.0到目前最新版本0.15.3的官方例子，问题依旧

| Environment | Info |
|---|---|
| 相关版本 | 0.13.0 |
| 框架版本 / 基础库版本 | Vue3(3.2.25) |
| 系统、浏览器 | Chromium: 80.0.3987.163 Res: 2106.482 |
| Node版本 |  |

**Comment by chaishi** [comment]
问题已知，拖拽排序插件 和 Vue3 混合使用有问题。

跟 Vue2 和 React 配合使用没有问题。（目前初步估计是 Vue3 对节点有特殊的处理）

**Comment by chaishi** [comment]
Vue3 仓库 issue：https://github.com/vuejs/core/issues/4010

这里也有一个关于节点顺序的讨论，可以同步关注下

**Comment by benbenonline** [comment]
> 问题已知，拖拽排序插件 和 Vue3 混合使用有问题。
> 
> 跟 Vue2 和 React 配合使用没有问题。（目前初步估计是 Vue3 对节点有特殊的处理，也不排除是 BUG 的可能）
> 
> 我上个周末，看了一整天这个问题，没看出来怎么处理。Vue3 的数据驱动有点让人费解，如下图所示。明明数据已经更新为新的顺序，但是 Vue3 的渲染结果却不是同步的。
> 
> <img alt="wecom-temp-44ef846471196cd4a576ec627196b0f7" width="575" src="https://user-images.githubusercontent.com/11605702/171089224-ae48eade-7346-4a5c-8165-adc6ce637aec.png">
> 
> Vue3 仓库 issue：[vuejs/core#4010](https://github.com/vuejs/core/issues/4010)
> 
> 这里也有一个关于节点顺序的讨论，可以同步关注下


了解了，谢谢回复，我本地也是如此：响应式数组顺序已经为正确的顺序，但是渲染节点的顺序不同步，而且我手动多次触发重绘，顺序还是会有问题。
后面我打算尝试仅使用vue3的场景下实现个简单拖拽表格demo，再做下验证看看，排查下vue3的触发渲染过程哪里有问题，谢谢。

**Comment by chaishi** [comment]
确实是一个问题，在问题解决之前，issue 继续保持 open 状态，我们也会持续关注 Vue3 官方动态

**Comment by benbenonline** [comment]
目前比较笨的临时解决方案，对row-key的设置不使用后台接口返回的id，而是在前端对应的viewmodel class上添加_id，由前端生成uuid或nanoid，每次做拖拽排序后，重新给_id进行赋值，触发表格的整体重绘。

**Comment by benbenonline** [comment]
为啥每次提交自动close

**Comment by chaishi** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/893
https://github.com/Tencent/tdesign-vue-next/issues/895

**Comment by chaishi** [comment]
针对 Vue3 特殊处理
resolved in https://github.com/Tencent/tdesign-vue-next/pull/2105 https://github.com/Tencent/tdesign-vue-next/pull/2105/commits/d1fc58302908cc86d3cce512b55dd749fa5f2f35
