### ISSUE TITLE
能否提供状态持久化解决方案，登录将 store 设置成功后，刷新后 状态就消失了？

### ISSUE THREAD

**Issue by synctimes163** [Tencent/tdesign-vue-next#920]
### 这个功能解决了什么问题

能否提供状态持久化解决方案，登录将 store 设置成功后，刷新后 状态就消失了？

可以解决手动 设置 localStorage 方法。 当权限判断路由有哪些时，不是通过接口实时判断的，而是登录成功后存储的问题

### 你建议的方案是什么

提供 stroe 状态持久化解决方案

**Comment by uyarn** [comment]
你这个应该提到页面模板那边吧

**Comment by pengYYYYY** [comment]
这个issue不属于基础组件库的范畴喔
