### ISSUE TITLE
[Vue Next for Web] 是否可以新增图片组件

### ISSUE THREAD

**Issue by Hi-Rui** [Tencent/tdesign-vue-next#927]
### 这个功能解决了什么问题

桌面端 Vue Next for Web
版本：0.15.4
我想要
图片组件-懒加载&大图预览
😤 
目前痛点

- [ ] 1、图片懒加载。

- [ ] 2、图片预览。

- [ ] 3、大图浏览。

- [ ] 4、图片局部放大。

### 你建议的方案是什么

💡 
我的想法
1、图片懒加载，根据网页浏览进度，动态加载图片内容。
图片加载失败，显示失败图标，可以点击重新加载那张图片。
2、图片预览，点一下可以显示大图（带半透明遮罩层）。

3、大图浏览，也是图片浏览，不过是多张图片大图浏览，有点像全屏的轮播图。
4、图片局部放大，鼠标放到哪里，局部放大图片的细节大图。

Vue Next for Mobile端已经有了，是否可以在【桌面端 Vue Next for Web】也新增一个图片组件。

**Comment by chaishi** [comment]
开发中

**Comment by pengYYYYY** [comment]
https://github.com/Tencent/tdesign-vue-next/issues/628 关注这个issue
