### ISSUE TITLE
[table]pagination没有配置defaultCurrent时，本地分页不生效

### ISSUE THREAD

**Issue by BeatenMo** [Tencent/tdesign-vue-next#928]
### tdesign-vue-next 版本

0.15.4

### 重现链接

https://stackblitz.com/edit/angular-ba4xdq?file=src%2Fdemo.vue

### 重现步骤

pagination没有配置defaultCurrent时，本地分页不生效
在群里的沟通table是依靠pageSize 和 data 长度来进行区分是否为远程分页的，那就不应该与pagination关联，默认就是本地分页
同时文档也应该增补一下说明

### 期望结果

正常本地分页

**Comment by chaishi** [comment]
理解有误，`pageSize` 属于 `pagination` 的一部分，是强相关
