### ISSUE TITLE
[TagInput] 中文输入按下 Enter 时不触发新标签，直接迁移 React 功能

### ISSUE THREAD

**Issue by chaishi** [Tencent/tdesign-vue-next#929]
### tdesign-vue-next 版本

0.15.4

**抄代码**： https://github.com/Tencent/tdesign-react/pull/835

React 已实现，需同步迁移特性到 Vue2 https://github.com/Tencent/tdesign-vue/issues/945

**Comment by funczh** [comment]
Is this bug already fixed? I can't reappear by this demo.

**Comment by pengYYYYY** [comment]
vue3 无此问题
