### ISSUE TITLE
[improve] [Form] 表单组件自定义校验如果为数字类型存在问题

### ISSUE THREAD

**Issue by pengYYYYY** [Tencent/tdesign-vue-next#93]
## tdesign-vue-next

You will open an feature issue at tdesign-vue-next

**Is your feature request related to a problem? Please describe.**

当前情况，所有的表单校验，max/min都是默认校验字符串的长度是否符合规则，但是如果为数字类型，个人理解理论上max/min应该校验的是其值是否 >min or <max

```
 max: (val: ValueType, num: number): boolean => getCharacterLength(val) <= num,
 min: (val: ValueType, num: number): boolean => val.length >= num,
```

### 逻辑修改

如果值为数字，由于数字很少有长度的定义，校验规则 max 和 min 自动更为数值大小的校验

**Comment by chaishi** [comment]
处理 PR：https://github.com/Tencent/tdesign-vue/pull/249

**Comment by pengYYYYY** [comment]
0.7.0已支持
