### ISSUE TITLE
[t-upload] 如果自定义beforeUpload钩子，会导致sizeLimit不生效

### ISSUE THREAD

**Issue by adreamknight** [Tencent/tdesign-vue-next#931]
### tdesign-vue-next 版本

tdesign-vue-next@0.11.0

### 期望结果

1、设置了beforeUpload后，sizeLimit 也应该生效
2、源码里 SIZE_MAP 的赋值有问题？1 和 1024 写反了？
<img width="924" alt="image" src="https://user-images.githubusercontent.com/46045933/171585542-070b94c3-56a1-421d-854b-ab7d33512dc3.png">
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/46045933/171585921-76204537-193d-4988-918e-924a8d1cbe50.png">
这里就不用除以 1024了。

### 实际结果

1、设置了beforeUpload后，sizeLimit 不再生效

**Comment by chaishi** [comment]
其实这是一个不是那么好抉择的问题，组件也不清楚是不是要继续保留 sizeLimit 校验。

按理说，写了 breforeUpload 就意味着把全部的校验交给外面处理了

我们讨论下吧

**Comment by adreamknight** [comment]
![image](https://user-images.githubusercontent.com/46045933/172550609-a858a43c-8e83-42a0-8887-0684e4786fb6.png)
还有这个问题呢？源码里 SIZE_MAP 的赋值好像有问题，1 和 1024 写反了~

**Comment by pengYYYYY** [comment]
不是写反了，是以KB为基准
