### ISSUE TITLE
[BaseTableCol] fixed属性设置成left或者right都报错

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#933]
### tdesign-vue-next 版本

0.15.4

### 重现步骤

![image](https://user-images.githubusercontent.com/46079969/172037528-a973d100-3fea-428a-b468-1a6fda3ca7b5.png)

**Comment by chaishi** [comment]
只有简单的错误截图，无法知道当前错误是在什么样的代码情况下出现。官网固定列正常。

如果长时间没有回复 复现问题的 示例代码，issue 将被关闭

**Comment by pengYYYYY** [comment]
先关闭，待示例补充后可reopen
