### ISSUE TITLE
[BaseTableCol] 无法显示布尔值属性 必须使用插槽显示

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#934]
### tdesign-vue-next 版本

0.15.4

### 重现链接

0.15.4

### 重现步骤

     <template #applyStatus="{ row }">
          {{ row.applyStatus }}
        </template>
减少不必要的插槽

### 期望结果

直接在单元格内打印出 true /false

**Comment by chaishi** [comment]
代码建议：`cell: ({ row }) => String(row.applyStatus)`
