### ISSUE TITLE
[Checkbox] 二次封装多选框组件插槽定义选项失效

### ISSUE THREAD

**Issue by uncledrewzhaopeng** [Tencent/tdesign-vue-next#940]
### tdesign-vue-next 版本

0.15.2

### 二次封装t-checkbox-group和t-checkbox组件
```html
<template>
  <t-checkbox-group v-bind="$attrs">
    <template v-for="(index, name) in $slots" v-slot:[name]>
      <slot :name="name" />
    </template>
  </t-checkbox-group>
</template>
```
```html
<template>
  <t-checkbox v-bind="$attrs">
    <template v-for="(index, name) in $slots" v-slot:[name]>
      <slot :name="name" />
    </template>
  </t-checkbox>
</template>
```

### 页面中使用
```html
<div>方式：组件内置全选功能，使用插槽定义选项。选中值: {{ value2.join(', ') }}</div>
<hl-checkbox-group v-model="value2" @change="onChange2">
  <hl-checkbox :check-all="true" label="全选" />
  <hl-checkbox value="选项一">选项一</hl-checkbox>
  <hl-checkbox label="选项二" value="选项二" />
  <hl-checkbox label="选项三" value="选项三" />
</hl-checkbox-group>
```
```js
const value2 = ref(['选项一'])
const onChange2 = (val) => {
  console.log(value2.value, val)
}
```
### 问题
**1. 选择其它项的时候，全选按钮没有半选状态**
![image](https://user-images.githubusercontent.com/48023419/172510969-21865f9b-6596-44d9-8e84-492937cc9057.png)
![image](https://user-images.githubusercontent.com/48023419/172511095-db91c410-c312-4612-bcf7-6ce417af0bdd.png)

**2. 点击全选的时候，清空了其它的选项，全选按钮没有选中状态且显示选中的为`undefined`**
![image](https://user-images.githubusercontent.com/48023419/172511176-e53a0bf6-e6dd-4535-9eba-35b3cc4ee9e9.png)
![image](https://user-images.githubusercontent.com/48023419/172511160-b99245b2-0b02-43e8-ab07-3f0ca94d9070.png)

**Comment by pengYYYYY** [comment]
会在下个版本修复这个问题，需要注意的是，这个组件需要导出一个组件名为‘xxx-checkbox’，用于父组件识别子组件

```
<template>
  <t-checkbox v-bind="$attrs">
    <template v-for="(index, name) in $slots" v-slot:[name]>
      <slot :name="name" />
    </template>
  </t-checkbox>
</template>
```

**Comment by uncledrewzhaopeng** [comment]
我是封了两个组件(父组件和子组件)
<img width="528" alt="image" src="https://user-images.githubusercontent.com/48023419/173185587-a84b4f2e-7928-492a-9457-0fdf2de2bb1b.png">

**Comment by pengYYYYY** [comment]
0.16.0 修复
