### ISSUE TITLE
构建esm+cjs的postcss插件是否没有作用？

### ISSUE THREAD

**Issue by l1shu** [Tencent/tdesign-vue-next#945]
### tdesign-vue-next 版本

0.15.4

### 重现链接

no link

### 重现步骤

<img width="561" alt="image" src="https://user-images.githubusercontent.com/48285873/172287969-aac6568b-05e2-479e-a896-47f7e94029ee.png">
看了下构建代码，发现esm和cjs的这个postcss插件似乎是没有作用的，因为这两个场景的构建都是保留less的原始文件并没有处理。
<img width="678" alt="image" src="https://user-images.githubusercontent.com/48285873/172288098-0da7bc9c-9104-4e48-a56e-3f91909eb48f.png">

**Comment by pengYYYYY** [comment]
看了一下，esm+cjs的postcss插件确实没有作用，有兴趣的话可以提个PR修复一下。

**Comment by pengYYYYY** [comment]
0.16.0 修复
