### ISSUE TITLE
[EnhancedTable] tree-expand-changes死循环（疑似懒加载需求）

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#946]
### tdesign-vue-next 版本

0.15.4

### 重现步骤

使用了tree-expand-change做展开收起监听后，用代码控制树状收起展开，方法进入死循环。
![图片](https://user-images.githubusercontent.com/19170277/172292800-50d584e9-465e-4664-8c76-d1781f0db62e.png)
（业务场景是点击“+”，监听到展开动作，先把树状合起来，获取数据，然后再打开）
![图片](https://user-images.githubusercontent.com/19170277/172292959-18e67339-d41e-4bfe-9c47-7256de4144fc.png)
（老版本不会有这个问题，新版本会进入死循环）

### 期望结果

不要进入死循环

**Comment by chaishi** [comment]
不要贴图，贴代码

**Comment by chaishi** [comment]
听上去，业务需求的场景有点像是 「树节点的懒加载」功能

**Comment by Waynefong** [comment]
> 听上去，业务需求的场景有点像是 「树节点的懒加载」功能

是这个功能，只是暂时没找到树状表格实现方法。不知道有没有办法实现？

**Comment by Waynefong** [comment]
> 不要贴图。辛苦贴代码，贴复现问题的示例代码

 <t-enhanced-table
        ref="menuTable"
        :data="tableData"
        :columns="COLUMNS_OPTS"
        row-key="id"
        :tree="{ childrenKey: 'children' }"
        :onTreeExpandChange="tableExpand"
      ></t-enhanced-table>

async function tableExpand({ row, rowIndex, rowState }) {
  if (rowState.expanded) {
    menuTable.value.toggleExpandData({ row, rowIndex });
    //加载子级数据
    await menuListFunc({ parentId: row.id, data: row, type: 'tree', pageSize: row.subCount });
    menuTable.value.toggleExpandData({ row, rowIndex });
  }
}

大概这样吧

**Comment by Waynefong** [comment]
> > 不要贴图。辛苦贴代码，贴复现问题的示例代码
> 
> async function tableExpand({ row, rowIndex, rowState }) { if (rowState.expanded) { menuTable.value.toggleExpandData({ row, rowIndex }); //加载子级数据 await menuListFunc({ parentId: row.id, data: row, type: 'tree', pageSize: row.subCount }); menuTable.value.toggleExpandData({ row, rowIndex }); } }
> 
> 大概这样吧

\<t-enhanced-table
        ref="menuTable"
        :data="tableData"
        :columns="COLUMNS_OPTS"
        row-key="id"
        :tree="{ childrenKey: 'children' }"
        :onTreeExpandChange="tableExpand"
      >\</t-enhanced-table>

**Comment by chaishi** [comment]
我明天看下这个问题
懒加载功能在规划中，会逐步实现，预计本月底

**Comment by chaishi** [comment]
大兄弟，有没有完整的代码示例啊，不要只贴一丢丢，这样子，剩下的代码我还要去脑补，脑补的对不对还不一定。

辛苦给个完整的 Demo 示例，不然影响排查问题的速度。

一般优先看提供了完成 Demo 的问题了

**Comment by chaishi** [comment]
懒加载功能，在 https://github.com/Tencent/tdesign-vue-next/pull/1011 中，已处理，待发布

**Comment by chaishi** [comment]
已支持懒加载功能，且收不到完整的  demo，issue 关闭。

后续提供示例代码，可以 reopen
