### ISSUE TITLE
[Form] reset提示not a function

### ISSUE THREAD

**Issue by Waynefong** [Tencent/tdesign-vue-next#947]
### tdesign-vue-next 版本

0.15.3

### 重现步骤

通过方法调用form对象的reset()报错
![图片](https://user-images.githubusercontent.com/19170277/172306504-391da7a6-a476-49e6-8be8-0847f04db666.png)
\<t-form
          ref="form"
          :data="formData"
          layout="inline"
          labelAlign="top"
          class="custom-form"
          scroll-to-first-error="smooth"
          :rules="rules"
        >****\</t-form>
使用Dialog包裹了form，然后点击取消按钮的时候触发方法，方法内调用了form.value.reset();

**Comment by Waynefong** [comment]
form对象已声明

const form = ref()

**Comment by k1nz** [comment]
更新一下 0.15.4
