### ISSUE TITLE
[BUG][Upload] 拖拽功能，仅第一次有效，二次直接打开了文件（拖拽框不见了，如果是这样设计的，请关闭此Issue）

### ISSUE THREAD

**Issue by chinanf-boy** [Tencent/tdesign-vue-next#950]
### tdesign-vue-next 版本

0.15.3

### 重现链接

https://tdesign.tencent.com/vue-next/components/upload#%E6%89%B9%E9%87%8F%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87

### 重现步骤

1. 去到官方网址，示例 https://tdesign.tencent.com/vue-next/components/upload#%E6%89%B9%E9%87%8F%E4%B8%8A%E4%BC%A0%E5%9B%BE%E7%89%87
拖拽一次文件
2. 二次拖拽，文件直接打开了

## Bug Demo
![upload-bug](https://user-images.githubusercontent.com/20272484/172351964-942703cd-7023-4f10-89cb-75fcea281ca7.gif)

### 框架版本

3.2.31

### 浏览器版本

'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53'

### 系统版本

Windows(1809)

### Node版本

v14.18.1

**Comment by pengYYYYY** [comment]
0.16.0 修复
