### ISSUE TITLE
[Upload] 可否新增上传失败的相关api

### ISSUE THREAD

**Issue by xyalim** [Tencent/tdesign-vue-next#952]
### 这个功能解决了什么问题

Upload组件的 移除上传失败时remove事件无法监听到，而change事件又不可以实时监听到上传失败文件的变化，导致Upload组件无法准确地捕获到上传失败文件的变化。

### 你建议的方案是什么

希望可提供相关api以方便操作上传失败文件以方便做如存在上传失败文件而不允许直接上传文件等相关用户提示,又或者提供无论成功或失败均同意存放的文件列表变量，如组件TUploadFlowList内部的变量toUploadFiles 以我方便做变量监听或者变量检测到上传失败文件

**Comment by chaishi** [comment]
这个不是上传失败的事件吗？
<img width="896" alt="image" src="https://user-images.githubusercontent.com/11605702/173173602-527590a4-a7c1-4f5e-a3da-e2303132a420.png">

**Comment by chaishi** [comment]
看不懂问题或者需求是什么

**Comment by xyalim** [comment]
![dc0077c744f2ac65f987f8640c21607](https://user-images.githubusercontent.com/29698012/173175000-ed736141-6984-40ae-9284-74d9a965ceec.png)

就是目前上传组件对于上传失败只有onFail吧，但是他只能返回当前失败的文件，而其中files属性只包含上传成功的文件并不包含上传失败的文件，那么这时候我就无法获得所有的上传失败的文件，当我需要对上传失败的文件作处理的时候，我只能够自己另外设立一个变量，来记录当前已经上传的文件（无论成功或失败）再利用onFail对已上传文件进行失败文件的状态记录，那这样就略显麻烦了。

**Comment by xyalim** [comment]
> 看不懂问题或者需求是什么
大概就是可不可以提供一个上传失败的文件列表的属性又或者含有上传状态的总的上传文件列表呢？

**Comment by pengYYYYY** [comment]
files 属性里有文件的状态，可以通过文件状态过滤一下

**Comment by xyalim** [comment]
> 

假如说files属性里包含失败文件的状态，那么我有可能是遇到bug了，因为当我上传失败的时候，files用v-model双向绑定时打印，我只看到存有上传成功的文件的，无法进行失败文件的过滤，代码在公司，暂时不方便展示效果。

**Comment by xyalim** [comment]
> files 属性里有文件的状态，可以通过文件状态过滤一下，应该可以满足你的需求
有劳排查一下

**Comment by pengYYYYY** [comment]
这边 issue 我先 reopen，后续在issue回复

**Comment by xyalim** [comment]
另外 我更新了之前被关闭了的 issue #909 复现了bug 劳烦大大也看一看 多谢

**Comment by pengYYYYY** [comment]
> ![dc0077c744f2ac65f987f8640c21607](https://user-images.githubusercontent.com/29698012/173175000-ed736141-6984-40ae-9284-74d9a965ceec.png)
> 
> 就是目前上传组件对于上传失败只有onFail吧，但是他只能返回当前失败的文件，而其中files属性只包含上传成功的文件并不包含上传失败的文件，那么这时候我就无法获得所有的上传失败的文件，当我需要对上传失败的文件作处理的时候，我只能够自己另外设立一个变量，来记录当前已经上传的文件（无论成功或失败）再利用onFail对已上传文件进行失败文件的状态记录，那这样就略显麻烦了。

<img width="834" alt="image" src="https://user-images.githubusercontent.com/35833812/175247948-537d17c4-3727-47ec-9473-9ece16386564.png">

在 `onFail` 这个回掉函数可以拿到上传失败的文件。你开辟一个新的变量的实现是标准的实现。基础组件库会尽量将组件颗粒度拆到比较小，对于这种可以通过API组合实现的需求，我们应该不会去新增一个 `API`，每实现一个 `API` 都会增加用户的理解成本，且会显得冗余。
