### ISSUE TITLE
Menu在火狐浏览器中子菜单显示后不会自动收起

### ISSUE THREAD

**Issue by MyZhouGit** [Tencent/tdesign-vue-next#961]
### tdesign-vue-next 版本

0.15.3

### 重现链接

无

### 重现步骤

Menu在火狐浏览器中子菜单显示后不会自动收起

### 浏览器版本

FireFox101.2

### 系统版本

Windows

### Node版本

16.14.2

**Comment by pengYYYYY** [comment]
希望有更清晰的描述，当前描述无法排查问题

**Comment by MyZhouGit** [comment]
https://user-images.githubusercontent.com/32385383/173789823-fd36a95c-0f22-4519-a458-944ccabfa096.mp4

视频中在我系统中，使用火狐浏览器访问后，鼠标悬浮后子菜单出现，鼠标离开后子菜单没有消失。其他浏览器没有这个问题
