### ISSUE TITLE
[DatePicker] 将datePicker作为独立组件使用

### ISSUE THREAD

**Issue by zhangtianxiao** [Tencent/tdesign-vue-next#968]
### 这个功能解决了什么问题

datePicke可以与任意元素组合使用吗, 比如button, 目前文档看上去, 只能和input组合使用, 默认触发元素就是自带的input

### 你建议的方案是什么

无

**Comment by chaishi** [comment]
这个已经在规划中了，React 已经开发完成，待发布。Vue3 Vue2 也快了
