### ISSUE TITLE
[Bug][Table]设置高度后，thead属性z-index高于菜单

### ISSUE THREAD

**Issue by talksmallice** [Tencent/tdesign-vue-next#97]
![image](https://user-images.githubusercontent.com/96230329/147715398-3fd0b7c9-aef0-4382-86b2-607bc1ab638b.png)
table设置高度后，thead属性z-index高于菜单

**Comment by pengYYYYY** [comment]
已收到

**Comment by pengYYYYY** [comment]
![image](https://user-images.githubusercontent.com/35833812/149925970-00aca99f-d122-4c6d-a6ce-dfe82384a4f0.png)

**Comment by pengYYYYY** [comment]
可以提供codesandbox示例嘛

**Comment by pengYYYYY** [comment]
0.7.0已修复
