### ISSUE TITLE
[Cascader] 能和 Select 一样支持自定义搜索逻辑吗

### ISSUE THREAD

**Issue by ddosakura** [Tencent/tdesign-vue-next#971]
### 这个功能解决了什么问题
Cascader 的搜索实现有点奇怪，所有选项都匹配“/”，而且无法区分大小写。

![1654852444779](https://user-images.githubusercontent.com/26789963/173035842-ee30a399-3fdd-4d07-937e-fb0641538673.png)
![16548524688603](https://user-images.githubusercontent.com/26789963/173035865-d12fda64-bc36-4d9c-a2ee-3b6bbfe9c1f2.png)

### 你建议的方案是什么？
能和 Select 一样支持自定义搜索逻辑吗

**Comment by pengYYYYY** [comment]
0.16.1 已修复
