### ISSUE TITLE
[Upload] 增加默认图片功能

### ISSUE THREAD

**Issue by williambao** [Tencent/tdesign-vue-next#974]
### 这个功能解决了什么问题

当上传图片模式时， 这个上传框可以传入默认显示图片吗？
比如Logo, 头像等单图上传场景时， 进入页面要显示当前的头像/Logo。 

### 你建议的方案是什么

增加个默认图片字段。如果有传就显示此图片(图1)，没传就显示当前的上传框(图2)。
<img width="387" alt="CleanShot 2022-06-11 at 13 04 55@2x" src="https://user-images.githubusercontent.com/779521/173173501-12493383-6a3c-418e-9089-8f778ee4ada2.png">
<img width="356" alt="CleanShot 2022-06-11 at 13 05 02@2x" src="https://user-images.githubusercontent.com/779521/173173503-22692aff-1aec-429c-94ba-b84e7bd54830.png">

**Comment by chaishi** [comment]
直接设置 `file:[{ url: ‘xxx' }]` 即可显示图片

**Comment by williambao** [comment]
@chaishi 可以了。 谢谢。
