### ISSUE TITLE
[Pagination] 组件在nuxt3中运行报错

### ISSUE THREAD

**Issue by yixiaco** [Tencent/tdesign-vue-next#988]
### tdesign-vue-next 版本

0.16.0

### 重现步骤

nuxt3版本：3.0.0-rc.4
tdesign-vue-next版本：0.16.0

页面组件报错
```vue
<t-pagination :total="20"/>
```

### 实际结果

![63444564db3946c7eec7523d3c5349c](https://user-images.githubusercontent.com/30982989/173539567-0719cb68-a2ec-4e89-8f04-bf719c850467.png)

**Comment by pengYYYYY** [comment]
@ardor-zhang 处理中

**Comment by pengYYYYY** [comment]
0.20.0版本已修复
