### ISSUE TITLE
[DateRangePicker ] 通过快捷方式设置的时间区间高亮数据异常

### ISSUE THREAD

**Issue by 107236074** [Tencent/tdesign-vue-next#990]
### tdesign-vue-next 版本

0.16.0

### 重现步骤

DateRangePicker通过快捷方式设置的时间区间高亮数据异常
<img width="964" alt="df0d20dc5904d1274c251247694ef56" src="https://user-images.githubusercontent.com/46079969/173562473-3c2f3ffe-99d7-46d7-a655-0885109633f7.png">

**Comment by pengYYYYY** [comment]
0.16.1 已修复
