### ISSUE TITLE
[Select] 基于selectInput重构后，远程搜索功能失效了，selectinput内的value没有正确传递到select中

### ISSUE THREAD

**Issue by latte-z** [Tencent/tdesign-vue-next#992]
### tdesign-vue-next 版本

0.16.0

### 重现链接

https://tdesign.woa.com/vue-next/components/select#%E8%BF%9C%E7%A8%8B%E6%90%9C%E7%B4%A2%E9%80%89%E6%8B%A9%E5%99%A8

### 重现步骤

文档远程搜索选择器的options2例子即可复现

### 期望结果

上一个release 0.15.4是正常使用的

### 框架版本

Vue(3.2.37)

**Comment by pengYYYYY** [comment]
已收到

**Comment by pengYYYYY** [comment]
0.16.1 已修复
