### ISSUE TITLE
[Select] 使用onEnter 事件报错

### ISSUE THREAD

**Issue by dennlian** [Tencent/tdesign-vue-next#997]
### tdesign-vue-next 版本

0.16.0

### 重现步骤

当select 传入空数组的时候，onEnter事件报错，但是不影响使用，看报错位置应该是removeTag 地方
![image](https://user-images.githubusercontent.com/20961979/173809603-e62ef3f3-317c-4953-91d5-aac0631bcfd0.png)
![image](https://user-images.githubusercontent.com/20961979/173809690-f561809c-0e2e-483b-8f3e-aacdcb5cd329.png)

### 期望结果

不报错

**Comment by pengYYYYY** [comment]
收到

**Comment by pengYYYYY** [comment]
0.16.1 已修复
